package at.martinthedragon.nucleartech.datagen

import at.martinthedragon.nucleartech.NuclearTech
import at.martinthedragon.nucleartech.RegistriesAndLifecycle
import at.martinthedragon.nucleartech.block.NTechBlocks
import at.martinthedragon.nucleartech.datagen.model.RandomModelBuilder
import at.martinthedragon.nucleartech.extensions.appendToPath
import at.martinthedragon.nucleartech.fluid.NTechFluids
import at.martinthedragon.nucleartech.item.*
import at.martinthedragon.nucleartech.ntm
import net.minecraft.client.renderer.block.model.ItemTransforms
import net.minecraft.data.DataGenerator
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.item.BucketItem
import net.minecraft.world.item.Item
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.material.Fluid
import net.minecraftforge.client.model.generators.ItemModelBuilder
import net.minecraftforge.client.model.generators.ItemModelProvider
import net.minecraftforge.client.model.generators.ModelFile
import net.minecraftforge.client.model.generators.ModelFile.UncheckedModelFile
import net.minecraftforge.client.model.generators.loaders.DynamicBucketModelBuilder
import net.minecraftforge.common.data.ExistingFileHelper

class NuclearItemModelProvider(
    dataGenerator: DataGenerator,
    existingFileHelper: ExistingFileHelper
) : ItemModelProvider(dataGenerator, NuclearTech.MODID, existingFileHelper) {
    override fun getName(): String = "Nuclear Tech Mod Item Models"

    override fun registerModels() {
        simpleItem(NTechItems.rawAluminium.get())
        simpleItem(NTechItems.rawAustralium.get())
        simpleItem(NTechItems.rawBeryllium.get())
        simpleItem(NTechItems.rawCobalt.get())
        simpleItem(NTechItems.rawLead.get())
        simpleItem(NTechItems.rawLithium.get())
        simpleItem(NTechItems.rawPlutonium.get())
        simpleItem(NTechItems.rawRareEarth.get())
        simpleItem(NTechItems.rawSchrabidium.get())
        simpleItem(NTechItems.rawStarmetal.get())
        simpleItem(NTechItems.rawThorium.get())
        simpleItem(NTechItems.rawTitanium.get())
        simpleItem(NTechItems.rawTrixite.get())
        simpleItem(NTechItems.rawTungsten.get())
        simpleItem(NTechItems.rawUranium.get())

        simpleItem(NTechItems.actiniumIngot.get())
        simpleItem(NTechItems.advancedAlloyIngot.get())
        simpleItem(NTechItems.aluminiumIngot.get())
        simpleItem(NTechItems.americium241Ingot.get())
        simpleItem(NTechItems.americium242Ingot.get())
        simpleItem(NTechItems.americiumFuelIngot.get())
        simpleItem(NTechItems.arsenicIngot.get())
        simpleItem(NTechItems.australiumIngot.get())
        simpleItem(NTechItems.bakeliteIngot.get())
        simpleItem(NTechItems.berylliumIngot.get())
        simpleItem(NTechItems.bismuthIngot.get())
        simpleItem(NTechItems.boronIngot.get())
        simpleItem(NTechItems.cobaltIngot.get())
        simpleItem(NTechItems.cobalt60Ingot.get())
        simpleItem(NTechItems.combineSteelIngot.get())
        simpleItem(NTechItems.daffergonIngot.get())
        simpleItem(NTechItems.deshIngot.get())
        simpleItem(NTechItems.dineutroniumIngot.get())
        simpleItem(NTechItems.electroniumIngot.get())
        simpleItem(NTechItems.euphemiumIngot.get())
        simpleItem(NTechItems.ferricSchrabidateIngot.get())
        simpleItem(NTechItems.ghiorsium336Ingot.get())
        simpleItem(NTechItems.gold198Ingot.get())
        simpleItem(NTechItems.graphiteIngot.get())
        simpleItem(NTechItems.highEnrichedSchrabidiumFuelIngot.get())
        simpleItem(NTechItems.highSpeedSteelIngot.get())
        simpleItem(NTechItems.lanthanumIngot.get())
        simpleItem(NTechItems.leadIngot.get())
        simpleItem(NTechItems.lead209Ingot.get())
        simpleItem(NTechItems.lowEnrichedSchrabidiumFuelIngot.get())
        simpleItem(NTechItems.magnetizedTungstenIngot.get())
        simpleItem(NTechItems.moxFuelIngot.get())
        simpleItem(NTechItems.neptuniumIngot.get())
        simpleItem(NTechItems.neptuniumFuelIngot.get())
        simpleItem(NTechItems.niobiumIngot.get())
        simpleItem(NTechItems.osmiridiumIngot.get())
        simpleItem(NTechItems.plutoniumFuelIngot.get())
        simpleItem(NTechItems.plutoniumIngot.get())
        simpleItem(NTechItems.polonium210Ingot.get())
        simpleItem(NTechItems.polymerIngot.get())
        simpleItem(NTechItems.pu238Ingot.get())
        simpleItem(NTechItems.pu239Ingot.get())
        simpleItem(NTechItems.pu240Ingot.get())
        simpleItem(NTechItems.pu241Ingot.get())
        simpleItem(NTechItems.radium226Ingot.get())
        simpleItem(NTechItems.reactorGradeAmericiumIngot.get())
        simpleItem(NTechItems.reactorGradePlutoniumIngot.get())
        simpleItem(NTechItems.redCopperIngot.get())
        simpleItem(NTechItems.reiiumIngot.get())
        simpleItem(NTechItems.rubberIngot.get())
        simpleItem(NTechItems.saturniteIngot.get())
        simpleItem(NTechItems.schrabidiumFuelIngot.get())
        simpleItem(NTechItems.schrabidiumIngot.get())
        simpleItem(NTechItems.schraraniumIngot.get())
        simpleItem(NTechItems.soliniumIngot.get())
        simpleItem(NTechItems.starmetalIngot.get())
        simpleItem(NTechItems.steelIngot.get())
        simpleItem(NTechItems.strontium90Ingot.get())
        simpleItem(NTechItems.tantaliumIngot.get())
        simpleItem(NTechItems.technetium99Ingot.get())
        simpleItem(NTechItems.technetiumSteelIngot.get())
        simpleItem(NTechItems.th232Ingot.get())
        simpleItem(NTechItems.thoriumFuelIngot.get())
        simpleItem(NTechItems.titaniumIngot.get())
        simpleItem(NTechItems.tungstenIngot.get())
        simpleItem(NTechItems.u233Ingot.get())
        simpleItem(NTechItems.u235Ingot.get())
        simpleItem(NTechItems.u238Ingot.get())
        simpleItem(NTechItems.unobtainiumIngot.get())
        simpleItem(NTechItems.uraniumFuelIngot.get())
        simpleItem(NTechItems.uraniumIngot.get())
        simpleItem(NTechItems.verticiumIngot.get())
        simpleItem(NTechItems.weidaniumIngot.get())
        simpleItem(NTechItems.whitePhosphorusIngot.get())

        simpleItem(NTechItems.actinium227Billet.get())
        simpleItem(NTechItems.americium241Billet.get())
        simpleItem(NTechItems.americium242Billet.get())
        simpleItem(NTechItems.americiumFuelBillet.get())
        simpleItem(NTechItems.australiumBillet.get())
        simpleItem(NTechItems.berylliumBillet.get())
        simpleItem(NTechItems.bismuthBillet.get())
        simpleItem(NTechItems.bismuthZfbBillet.get())
        simpleItem(NTechItems.cobalt60Billet.get())
        simpleItem(NTechItems.cobaltBillet.get())
        simpleItem(NTechItems.flashgoldBillet.get())
        simpleItem(NTechItems.flashleadBillet.get())
        simpleItem(NTechItems.ghiorsium336Billet.get())
        simpleItem(NTechItems.gold198Billet.get())
        simpleItem(NTechItems.greaterAustraliumBillet.get())
        simpleItem(NTechItems.highEnrichedSchrabidiumFuelBillet.get())
        simpleItem(NTechItems.lead209Billet.get())
        simpleItem(NTechItems.lesserAustraliumBillet.get())
        simpleItem(NTechItems.lowEnrichedSchrabidiumFuelBillet.get())
        simpleItem(NTechItems.moxFuelBillet.get())
        simpleItem(NTechItems.neptuniumBillet.get())
        simpleItem(NTechItems.neptuniumFuelBillet.get())
        simpleItem(NTechItems.nuclearWasteBillet.get())
        simpleItem(NTechItems.plutoniumBillet.get())
        simpleItem(NTechItems.plutoniumFuelBillet.get())
        simpleItem(NTechItems.po210BeBillet.get())
        simpleItem(NTechItems.poloniumBillet.get())
        simpleItem(NTechItems.pu238BeBillet.get())
        simpleItem(NTechItems.pu238Billet.get())
        simpleItem(NTechItems.pu239Billet.get())
        simpleItem(NTechItems.pu240Billet.get())
        simpleItem(NTechItems.pu241Billet.get())
        simpleItem(NTechItems.pu241ZfbBillet.get())
        simpleItem(NTechItems.ra226BeBillet.get())
        simpleItem(NTechItems.radium226Billet.get())
        simpleItem(NTechItems.reactorGradeAmericiumBillet.get())
        simpleItem(NTechItems.reactorGradeAmericiumZfbBillet.get())
        simpleItem(NTechItems.reactorGradePlutoniumBillet.get())
        simpleItem(NTechItems.schrabidiumBillet.get())
        simpleItem(NTechItems.schrabidiumFuelBillet.get())
        simpleItem(NTechItems.soliniumBillet.get())
        simpleItem(NTechItems.strontium90Billet.get())
        simpleItem(NTechItems.technetium99Billet.get())
        simpleItem(NTechItems.th232Billet.get())
        simpleItem(NTechItems.thoriumFuelBillet.get())
        simpleItem(NTechItems.u233Billet.get())
        simpleItem(NTechItems.u235Billet.get())
        simpleItem(NTechItems.u238Billet.get())
        simpleItem(NTechItems.uraniumBillet.get())
        simpleItem(NTechItems.uraniumFuelBillet.get())
        simpleItem(NTechItems.yharoniteBillet.get())
        simpleItem(NTechItems.zirconiumBillet.get())

        simpleItem(NTechItems.asbestosSheet.get())
        simpleItem(NTechItems.coke.get())
        simpleItem(NTechItems.fiberglassSheet.get())
        simpleItem(NTechItems.lignite.get())
        simpleItem(NTechItems.ligniteBriquette.get())
        simpleItem(NTechItems.lithiumCube.get())
        simpleItem(NTechItems.mercuryBottle.get())
        simpleItem(NTechItems.mercuryDroplet.get())
        simpleItem(NTechItems.semtexBar.get())
        simpleItem(NTechItems.solidFuelCube.get())
        simpleItem(NTechItems.solidRocketFuelCube.get())

        simpleItem(NTechItems.actiniumPowder.get())
        simpleItem(NTechItems.advancedAlloyPowder.get())
        simpleItem(NTechItems.aluminiumPowder.get())
        simpleItem(NTechItems.asbestosPowder.get())
        simpleItem(NTechItems.australiumPowder.get())
        simpleItem(NTechItems.ballistite.get())
        simpleItem(NTechItems.berylliumPowder.get())
        simpleItem(NTechItems.ceriumPowder.get())
        simpleItem(NTechItems.chlorophytePowder.get())
        simpleItem(NTechItems.cloudResidue.get())
        simpleItem(NTechItems.coalPowder.get())
        simpleItem(NTechItems.cobaltPowder.get())
        simpleItem(NTechItems.combineSteelPowder.get())
        simpleItem(NTechItems.copperPowder.get())
        simpleItem(NTechItems.cordite.get())
        simpleItem(NTechItems.cryoPowder.get())
        simpleItem(NTechItems.daffergonPowder.get())
        simpleItem(NTechItems.desaturatedRedstone.get())
        simpleItem(NTechItems.deshMix.get())
        simpleItem(NTechItems.deshPowder.get())
        simpleItem(NTechItems.deshReadyMix.get())
        simpleItem(NTechItems.diamondPowder.get())
        simpleItem(NTechItems.dineutroniumPowder.get())
        simpleItem(NTechItems.dust.get())
        simpleItem(NTechItems.emeraldPowder.get())
        simpleItem(NTechItems.enchantmentPowder.get())
        simpleItem(NTechItems.energyPowder.get())
        simpleItem(NTechItems.euphemiumPowder.get())
        simpleItem(NTechItems.fluorite.get())
        simpleItem(NTechItems.goldPowder.get())
        simpleItem(NTechItems.highSpeedSteelPowder.get())
        simpleItem(NTechItems.ironPowder.get())
        simpleItem(NTechItems.lanthanumPowder.get())
        simpleItem(NTechItems.lapisLazuliPowder.get())
        simpleItem(NTechItems.leadPowder.get())
        simpleItem(NTechItems.lignitePowder.get())
        simpleItem(NTechItems.lithiumPowder.get())
        simpleItem(NTechItems.magnetizedTungstenPowder.get())
        simpleItem(NTechItems.meteoritePowder.get())
        simpleItem(NTechItems.neodymiumPowder.get())
        simpleItem(NTechItems.neptuniumPowder.get())
        simpleItem(NTechItems.niobiumPowder.get())
        simpleItem(NTechItems.nitaniumMix.get())
        simpleItem(NTechItems.niter.get())
        simpleItem(NTechItems.plutoniumPowder.get())
        simpleItem(NTechItems.poisonPowder.get())
        simpleItem(NTechItems.poloniumPowder.get())
        simpleItem(NTechItems.polymerPowder.get())
        simpleItem(NTechItems.quartzPowder.get())
        simpleItem(NTechItems.redCopperPowder.get())
        simpleItem(NTechItems.redPhosphorus.get())
        simpleItem(NTechItems.reiiumPowder.get())
        simpleItem(NTechItems.schrabidiumPowder.get())
        simpleItem(NTechItems.semtexMix.get())
        simpleItem(NTechItems.sparkMix.get())
        simpleItem(NTechItems.steelPowder.get())
        simpleItem(NTechItems.sulfur.get())
        simpleItem(NTechItems.thermite.get())
        simpleItem(NTechItems.thermonuclearAshes.get())
        simpleItem(NTechItems.thoriumPowder.get())
        simpleItem(NTechItems.tinyActiniumPowder.get())
        simpleItem(NTechItems.tinyCeriumPowder.get())
        simpleItem(NTechItems.tinyCobaltPowder.get())
        simpleItem(NTechItems.tinyLanthanumPowder.get())
        simpleItem(NTechItems.tinyLithiumPowder.get())
        simpleItem(NTechItems.tinyMeteoritePowder.get())
        simpleItem(NTechItems.tinyNeodymiumPowder.get())
        simpleItem(NTechItems.tinyNiobiumPowder.get())
        simpleItem(NTechItems.titaniumPowder.get())
        simpleItem(NTechItems.tungstenPowder.get())
        simpleItem(NTechItems.unobtainiumPowder.get())
        simpleItem(NTechItems.uraniumPowder.get())
        simpleItem(NTechItems.verticiumPowder.get())
        simpleItem(NTechItems.weidaniumPowder.get())
        simpleItem(NTechItems.yellowcake.get())

        simpleItem(NTechItems.aluminiumCrystals.get())
        simpleItem(NTechItems.berylliumCrystals.get())
        simpleItem(NTechItems.coalCrystals.get())
        simpleItem(NTechItems.cobaltCrystals.get())
        simpleItem(NTechItems.copperCrystals.get())
        simpleItem(NTechItems.diamondCrystals.get())
        simpleItem(NTechItems.fluoriteCrystals.get())
        simpleItem(NTechItems.goldCrystals.get())
        simpleItem(NTechItems.ironCrystals.get())
        simpleItem(NTechItems.lapisCrystals.get())
        simpleItem(NTechItems.leadCrystals.get())
        simpleItem(NTechItems.lithiumCrystals.get())
        simpleItem(NTechItems.niterCrystals.get())
        simpleItem(NTechItems.osmiridiumCrystals.get())
        simpleItem(NTechItems.plutoniumCrystals.get())
        simpleItem(NTechItems.rareEarthCrystals.get())
        simpleItem(NTechItems.redPhosphorusCrystals.get())
        simpleItem(NTechItems.redstoneCrystals.get())
        simpleItem(NTechItems.schrabidiumCrystals.get())
        simpleItem(NTechItems.schraraniumCrystals.get())
        simpleItem(NTechItems.starmetalCrystals.get())
        simpleItem(NTechItems.sulfurCrystals.get())
        simpleItem(NTechItems.thoriumCrystals.get())
        simpleItem(NTechItems.titaniumCrystals.get())
        simpleItem(NTechItems.trixiteCrystals.get())
        simpleItem(NTechItems.tungstenCrystals.get())
        simpleItem(NTechItems.uraniumCrystals.get())

        simpleItem(NTechItems.volcanicGem.get())

        simpleItem(NTechItems.actiniumFragment.get())
        simpleItem(NTechItems.ceriumFragment.get())
        simpleItem(NTechItems.cobaltFragment.get())
        simpleItem(NTechItems.lanthanumFragment.get())
        simpleItem(NTechItems.meteoriteFragment.get())
        simpleItem(NTechItems.neodymiumFragment.get())

        simpleItem(NTechItems.biomass.get())
        simpleItem(NTechItems.compressedBiomass.get())

        simpleItem(NTechItems.actinium227Nugget.get())
        simpleItem(NTechItems.americium241Nugget.get())
        simpleItem(NTechItems.americium242Nugget.get())
        simpleItem(NTechItems.americiumFuelNugget.get())
        simpleItem(NTechItems.arsenicNugget.get())
        simpleItem(NTechItems.australiumNugget.get())
        simpleItem(NTechItems.berylliumNugget.get())
        simpleItem(NTechItems.bismuthNugget.get())
        simpleItem(NTechItems.cobaltNugget.get())
        simpleItem(NTechItems.cobalt60Nugget.get())
        simpleItem(NTechItems.daffergonNugget.get())
        simpleItem(NTechItems.deshNugget.get())
        simpleItem(NTechItems.dineutroniumNugget.get())
        simpleItem(NTechItems.euphemiumNugget.get())
        simpleItem(NTechItems.ghiorsium336Nugget.get())
        simpleItem(NTechItems.gold198Nugget.get())
        simpleItem(NTechItems.highEnrichedSchrabidiumFuelNugget.get())
        simpleItem(NTechItems.leadNugget.get())
        simpleItem(NTechItems.lead209Nugget.get())
        simpleItem(NTechItems.lowEnrichedSchrabidiumFuelNugget.get())
        simpleItem(NTechItems.moxFuelNugget.get())
        simpleItem(NTechItems.neptuniumNugget.get())
        simpleItem(NTechItems.neptuniumFuelNugget.get())
        simpleItem(NTechItems.niobiumFragment.get())
        simpleItem(NTechItems.osmiridiumNugget.get())
        simpleItem(NTechItems.plutoniumFuelNugget.get())
        simpleItem(NTechItems.plutoniumNugget.get())
        simpleItem(NTechItems.poloniumNugget.get())
        simpleItem(NTechItems.pu238Nugget.get())
        simpleItem(NTechItems.pu239Nugget.get())
        simpleItem(NTechItems.pu240Nugget.get())
        simpleItem(NTechItems.pu241Nugget.get())
        simpleItem(NTechItems.radium226Nugget.get())
        simpleItem(NTechItems.reactorGradeAmericiumNugget.get())
        simpleItem(NTechItems.reactorGradePlutoniumNugget.get())
        simpleItem(NTechItems.reiiumNugget.get())
        simpleItem(NTechItems.schrabidiumFuelNugget.get())
        simpleItem(NTechItems.schrabidiumNugget.get())
        simpleItem(NTechItems.soliniumNugget.get())
        simpleItem(NTechItems.strontium90Nugget.get())
        simpleItem(NTechItems.tantaliumNugget.get())
        simpleItem(NTechItems.technetium99Nugget.get())
        simpleItem(NTechItems.th232Nugget.get())
        simpleItem(NTechItems.thoriumFuelNugget.get())
        simpleItem(NTechItems.u233Nugget.get())
        simpleItem(NTechItems.u235Nugget.get())
        simpleItem(NTechItems.u238Nugget.get())
        simpleItem(NTechItems.unobtainiumNugget.get())
        simpleItem(NTechItems.uraniumFuelNugget.get())
        simpleItem(NTechItems.uraniumNugget.get())
        simpleItem(NTechItems.verticiumNugget.get())
        simpleItem(NTechItems.weidaniumNugget.get())

        simpleItem(NTechItems.advancedAlloyPlate.get())
        simpleItem(NTechItems.aluminiumPlate.get())
        simpleItem(NTechItems.combineSteelPlate.get())
        simpleItem(NTechItems.copperPanel.get())
        simpleItem(NTechItems.copperPlate.get())
        simpleItem(NTechItems.dalekaniumPlate.get())
        simpleItem(NTechItems.deshCompoundPlate.get())
        simpleItem(NTechItems.dineutroniumCompoundPlate.get())
        simpleItem(NTechItems.euphemiumCompoundPlate.get())
        simpleItem(NTechItems.goldPlate.get())
        simpleItem(NTechItems.insulator.get())
        simpleItem(NTechItems.ironPlate.get())
        simpleItem(NTechItems.kevlarCeramicCompound.get())
        simpleItem(NTechItems.leadPlate.get())
        simpleItem(NTechItems.mixedPlate.get())
        simpleItem(NTechItems.neutronReflector.get())
        simpleItem(NTechItems.paAAlloyPlate.get())
        simpleItem(NTechItems.saturnitePlate.get())
        simpleItem(NTechItems.schrabidiumPlate.get())
        simpleItem(NTechItems.steelPlate.get())
        simpleItem(NTechItems.titaniumPlate.get())

        simpleItem(NTechItems.activatedCarbonFilter.get())
        simpleItem(NTechItems.advancedHazmatCloth.get())
        simpleItem(NTechItems.fireProximityCloth.get())
        simpleItem(NTechItems.hazmatCloth.get())
        simpleItem(NTechItems.highSpeedSteelBolt.get())
        simpleItem(NTechItems.leadReinforcedHazmatCloth.get())
        simpleItem(NTechItems.reinforcedTurbineShaft.get())
        simpleItem(NTechItems.tungstenBolt.get())

        simpleItem(NTechItems.aluminiumWire.get())
        simpleItem(NTechItems.copperCoil.get())
        simpleItem(NTechItems.copperWire.get())
        simpleItem(NTechItems.goldCoil.get())
        simpleItem(NTechItems.goldRingCoil.get())
        simpleItem(NTechItems.goldWire.get())
        simpleItem(NTechItems.heatingCoil.get())
        simpleItem(NTechItems.highTemperatureSuperConductingCoil.get())
        simpleItem(NTechItems.highTemperatureSuperConductor.get())
        simpleItem(NTechItems.redCopperWire.get())
        simpleItem(NTechItems.ringCoil.get())
        simpleItem(NTechItems.schrabidiumWire.get())
        simpleItem(NTechItems.superConductingCoil.get())
        simpleItem(NTechItems.superConductingRingCoil.get())
        simpleItem(NTechItems.superConductor.get())
        simpleItem(NTechItems.tungstenWire.get())

        simpleItem(NTechItems.aluminiumCap.get())
        simpleItem(NTechItems.bigAluminiumShell.get())
        simpleItem(NTechItems.bigSteelGridFins.get())
        simpleItem(NTechItems.bigSteelShell.get())
        simpleItem(NTechItems.bigTitaniumShell.get())
        simpleItem(NTechItems.breedingReactorCore.get())
        simpleItem(NTechItems.centrifugeElement.get())
        simpleItem(NTechItems.centrifugeTower.get())
        simpleItem(NTechItems.chlorinePinwheel.get())
        simpleItem(NTechItems.clayCatalyst.get())
        simpleItem(NTechItems.cyclotronTower.get())
        simpleItem(NTechItems.deeMagnets.get())
        simpleItem(NTechItems.ductTape.get())
        simpleItem(NTechItems.dysfunctionalNuclearReactor.get())
        simpleItem(NTechItems.emitterComponent.get())
        simpleItem(NTechItems.endothermicDistributionUnit.get())
        simpleItem(NTechItems.entanglementKit.get())
        simpleItem(NTechItems.exothermicDistributionUnit.get())
        simpleItem(NTechItems.flatMagnet.get())
        simpleItem(NTechItems.flatSteelCasing.get())
        simpleItem(NTechItems.generatorBody.get())
        simpleItem(NTechItems.generatorFront.get())
        simpleItem(NTechItems.gravityManipulator.get())
        simpleItem(NTechItems.largeSteelFins.get())
        simpleItem(NTechItems.largeSteelRotor.get())
        simpleItem(NTechItems.motor.get())
        simpleItem(NTechItems.photovoltaicPanel.get())
        simpleItem(NTechItems.reinforcedTurbofanBlades.get())
        simpleItem(NTechItems.rtgUnit.get())
        simpleItem(NTechItems.smallAluminiumShell.get())
        simpleItem(NTechItems.smallSteelGridFins.get())
        simpleItem(NTechItems.smallSteelShell.get())
        simpleItem(NTechItems.smallTitaniumFins.get())
        simpleItem(NTechItems.stabilizerComponent.get())
        simpleItem(NTechItems.steelPedestal.get())
        simpleItem(NTechItems.steelPipes.get())
        simpleItem(NTechItems.steelSphere.get())
        simpleItem(NTechItems.steelTank.get())
        simpleItem(NTechItems.telepad.get())
        simpleItem(NTechItems.thermalDistributionUnit.get())
        simpleItem(NTechItems.titaniumBlade.get())
        simpleItem(NTechItems.titaniumDrill.get())
        simpleItem(NTechItems.titaniumSteamTurbine.get())
        simpleItem(NTechItems.toothpicks.get())
        simpleItem(NTechItems.tungstenReinforcedBlade.get())

        simpleItem(NTechItems.advancedCircuit.get())
        simpleItem(NTechItems.advancedLauncherMechanism.get())
        simpleItem(NTechItems.advancedRevolverMechanism.get())
        simpleItem(NTechItems.advancedRifleMechanism.get())
        simpleItem(NTechItems.basicCircuit.get())
        simpleItem(NTechItems.basicCircuitAssembly.get())
        simpleItem(NTechItems.blankRune.get())
        simpleItem(NTechItems.buckshotCasing.get())
        simpleItem(NTechItems.buckshotPrimer.get())
        simpleItem(NTechItems.burnedOutQuadSchrabidiumFuelRod.get())
        simpleItem(NTechItems.burntBark.get())
        simpleItem(NTechItems.cableDrum.get())
        simpleItem(NTechItems.charredCrystal.get())
        simpleItem(NTechItems.combineScrapMetal.get())
        simpleItem(NTechItems.conspiracyTheory.get())
        simpleItem(NTechItems.crystalHorn.get())
        simpleItem(NTechItems.dagazRune.get())
        simpleItem(NTechItems.deathRay.get())
        simpleItem(NTechItems.denseCoalCluster.get())
        simpleItem(NTechItems.depletedMOXFuel.get())
        simpleItem(NTechItems.depletedPlutoniumFuel.get())
        simpleItem(NTechItems.depletedSchrabidiumFuel.get())
        simpleItem(NTechItems.depletedThoriumFuel.get())
        simpleItem(NTechItems.depletedUraniumFuel.get())
        simpleItem(NTechItems.deshBulletAssembly.get())
        simpleItem(NTechItems.emplacementGun.get())
        simpleItem(NTechItems.endothermicWarhead.get())
        simpleItem(NTechItems.enhancedCircuit.get())
        simpleItem(NTechItems.exothermicWarhead.get())
        simpleItem(NTechItems.explosivePellets.get())
        simpleItem(NTechItems.fivePoint56mmAssembly.get())
        simpleItem(NTechItems.flechettes.get())
        simpleItem(NTechItems.glassBulletAssembly.get())
        simpleItem(NTechItems.goldBulletAssembly.get())
        simpleItem(NTechItems.hagalazRune.get())
        simpleItem(NTechItems.heavyAxeHead.get())
        simpleItem(NTechItems.heavyHammerHead.get())
        simpleItem(NTechItems.highGainOpticalCamera.get())
        simpleItem(NTechItems.highPerformanceCircuit.get())
        simpleItem(NTechItems.highTechWeaponMechanism.get())
        simpleItem(NTechItems.hotDepletedMOXFuel.get())
        simpleItem(NTechItems.hotDepletedPlutoniumFuel.get())
        simpleItem(NTechItems.hotDepletedSchrabidiumFuel.get())
        simpleItem(NTechItems.hotDepletedThoriumFuel.get())
        simpleItem(NTechItems.hotDepletedUraniumFuel.get())
        simpleItem(NTechItems.hunterChopperBody.get())
        simpleItem(NTechItems.hunterChopperCockpit.get())
        simpleItem(NTechItems.hunterChopperRotorBlades.get())
        simpleItem(NTechItems.hunterChopperTail.get())
        simpleItem(NTechItems.hunterChopperWing.get())
        simpleItem(NTechItems.ironBulletAssembly.get())
        simpleItem(NTechItems.isaRune.get())
        simpleItem(NTechItems.jeraRune.get())
        simpleItem(NTechItems.largeBunkerBusterWarhead.get())
        simpleItem(NTechItems.largeCaliberCasing.get())
        simpleItem(NTechItems.largeCaliberPrimer.get())
        simpleItem(NTechItems.largeClusterWarhead.get())
        simpleItem(NTechItems.largeFuelTank.get())
        simpleItem(NTechItems.largeIncendiaryWarhead.get())
        simpleItem(NTechItems.largeThruster.get())
        simpleItem(NTechItems.largeWarhead.get())
        simpleItem(NTechItems.launcherMechanism.get())
        simpleItem(NTechItems.leadBulletAssembly.get())
        simpleItem(NTechItems.leadPellets.get())
        simpleItem(NTechItems.lvnNuclearRocketEngine.get())
        simpleItem(NTechItems.m700SurveyScanner.get())
        simpleItem(NTechItems.machineUpgradeTemplate.get())
        simpleItem(NTechItems.magnetron.get())
        simpleItem(NTechItems.mediumBunkerBusterWarhead.get())
        simpleItem(NTechItems.mediumClusterWarhead.get())
        simpleItem(NTechItems.mediumFuelTank.get())
        simpleItem(NTechItems.mediumIncendiaryWarhead.get())
        simpleItem(NTechItems.mediumThruster.get())
        simpleItem(NTechItems.mediumWarhead.get())
        simpleItem(NTechItems.militaryGradeCircuitBoardTier1.get())
        simpleItem(NTechItems.militaryGradeCircuitBoardTier2.get())
        simpleItem(NTechItems.militaryGradeCircuitBoardTier3.get())
        simpleItem(NTechItems.militaryGradeCircuitBoardTier4.get())
        simpleItem(NTechItems.militaryGradeCircuitBoardTier5.get())
        simpleItem(NTechItems.militaryGradeCircuitBoardTier6.get())
        simpleItem(NTechItems.nightmareBulletAssembly.get())
        simpleItem(NTechItems.nineMmAssembly.get())
        simpleItem(NTechItems.nuclearWarhead.get())
        simpleItem(NTechItems.nuclearWaste.get())
        simpleItem(NTechItems.overclockedCircuit.get())
        simpleItem(NTechItems.ownOpinion.get())
        simpleItem(NTechItems.paintingOfACartoonPony.get())
        simpleItem(NTechItems.point22LRAssembly.get())
        simpleItem(NTechItems.point357MagnumCasing.get())
        simpleItem(NTechItems.point357MagnumPrimer.get())
        simpleItem(NTechItems.point44MagnumAssembly.get())
        simpleItem(NTechItems.point44MagnumCasing.get())
        simpleItem(NTechItems.point44MagnumPrimer.get())
        simpleItem(NTechItems.point50AEAssembly.get())
        simpleItem(NTechItems.point50BMGAssembly.get())
        simpleItem(NTechItems.point5mmAssembly.get())
        simpleItem(NTechItems.poisonGasCartridge.get())
        simpleItem(NTechItems.politicalTopic.get())
        simpleItem(NTechItems.radarDish.get())
        simpleItem(NTechItems.reinforcedPolymerHandle.get())
        simpleItem(NTechItems.revolverMechanism.get())
        simpleItem(NTechItems.rifleMechanism.get())
        simpleItem(NTechItems.satelliteBase.get())
        simpleItem(NTechItems.schrabidiumBulletAssembly.get())
        simpleItem(NTechItems.scrap.get())
        simpleItem(NTechItems.silverBulletCasing.get())
        simpleItem(NTechItems.size10Connector.get())
        simpleItem(NTechItems.size15Connector.get())
        simpleItem(NTechItems.size20Connector.get())
        simpleItem(NTechItems.smallBunkerBusterWarhead.get())
        simpleItem(NTechItems.smallCaliberCasing.get())
        simpleItem(NTechItems.smallCaliberPrimer.get())
        simpleItem(NTechItems.smallClusterWarhead.get())
        simpleItem(NTechItems.smallFuelTank.get())
        simpleItem(NTechItems.smallIncendiaryWarhead.get())
        simpleItem(NTechItems.smallMissileAssembly.get())
        simpleItem(NTechItems.smallThruster.get())
        simpleItem(NTechItems.smallWarhead.get())
        simpleItem(NTechItems.thermonuclearWarhead.get())
        simpleItem(NTechItems.thurisazRune.get())
        simpleItem(NTechItems.tinyNuclearWaste.get())
        simpleItem(NTechItems.trinitite.get())
        simpleItem(NTechItems.twelvePoint8cmDUShell.get())
        simpleItem(NTechItems.twelvePoint8cmNuclearShell.get())
        simpleItem(NTechItems.twelvePoint8cmStarmetalHighEnergyShell.get())
        simpleItem(NTechItems.xeniumResonator.get())

        simpleItem(NTechItems.battery.get())
        simpleItem(NTechItems.redstonePowerCell.get())
        simpleItem(NTechItems.sixfoldRedstonePowerCell.get())
        simpleItem(NTechItems.twentyFourFoldRedstonePowerCell.get())
        simpleItem(NTechItems.advancedBattery.get())
        simpleItem(NTechItems.advancedPowerCell.get())
        simpleItem(NTechItems.quadrupleAdvancedPowerCell.get())
        simpleItem(NTechItems.twelveFoldAdvancedPowerCell.get())
        simpleItem(NTechItems.lithiumBattery.get())
        simpleItem(NTechItems.lithiumPowerCell.get())
        simpleItem(NTechItems.tripleLithiumPowerCell.get())
        simpleItem(NTechItems.sixfoldLithiumPowerCell.get())
        simpleItem(NTechItems.schrabidiumBattery.get())
        simpleItem(NTechItems.schrabidiumPowerCell.get())
        simpleItem(NTechItems.doubleSchrabidiumPowerCell.get())
        simpleItem(NTechItems.quadrupleSchrabidiumPowerCell.get())
        simpleItem(NTechItems.sparkBattery.get())
        simpleItem(NTechItems.offBrandSparkBattery.get())
        simpleItem(NTechItems.sparkPowerCell.get())
        simpleItem(NTechItems.sparkArcaneCarBattery.get())
        simpleItem(NTechItems.sparkArcaneEnergyStorageArray.get())
        simpleItem(NTechItems.sparkArcaneMassEnergyVoid.get())
        simpleItem(NTechItems.sparkArcaneDiracSea.get())
        simpleItem(NTechItems.sparkSolidSpaceTimeCrystal.get())
        simpleItem(NTechItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit.get())
        simpleItem(NTechItems.infiniteBattery.get())
        simpleItem(NTechItems.singleUseBattery.get())
        simpleItem(NTechItems.largeSingleUseBattery.get())
        simpleItem(NTechItems.potatoBattery.get())
        simpleItem(NTechItems.steamPoweredEnergyStorageTank.get())
        simpleItem(NTechItems.largeSteamPoweredEnergyStorageTank.get())

        simpleItem(NTechItems.stoneFlatStamp.get())
        simpleItem(NTechItems.stonePlateStamp.get())
        simpleItem(NTechItems.stoneWireStamp.get())
        simpleItem(NTechItems.stoneCircuitStamp.get())
        simpleItem(NTechItems.ironFlatStamp.get())
        simpleItem(NTechItems.ironPlateStamp.get())
        simpleItem(NTechItems.ironWireStamp.get())
        simpleItem(NTechItems.ironCircuitStamp.get())
        simpleItem(NTechItems.steelFlatStamp.get())
        simpleItem(NTechItems.steelPlateStamp.get())
        simpleItem(NTechItems.steelWireStamp.get())
        simpleItem(NTechItems.steelCircuitStamp.get())
        simpleItem(NTechItems.titaniumFlatStamp.get())
        simpleItem(NTechItems.titaniumPlateStamp.get())
        simpleItem(NTechItems.titaniumWireStamp.get())
        simpleItem(NTechItems.titaniumCircuitStamp.get())
        simpleItem(NTechItems.obsidianFlatStamp.get())
        simpleItem(NTechItems.obsidianPlateStamp.get())
        simpleItem(NTechItems.obsidianWireStamp.get())
        simpleItem(NTechItems.obsidianCircuitStamp.get())
        simpleItem(NTechItems.schrabidiumFlatStamp.get())
        simpleItem(NTechItems.schrabidiumPlateStamp.get())
        simpleItem(NTechItems.schrabidiumWireStamp.get())
        simpleItem(NTechItems.schrabidiumCircuitStamp.get())

        simpleItem(NTechItems.screwdriver.get())
        simpleItem(NTechItems.deshScrewdriver.get())

        simpleItem(NTechItems.speedUpgradeMk1.get())
        simpleItem(NTechItems.speedUpgradeMk2.get())
        simpleItem(NTechItems.speedUpgradeMk3.get())
        simpleItem(NTechItems.powerSavingUpgradeMk1.get())
        simpleItem(NTechItems.powerSavingUpgradeMk2.get())
        simpleItem(NTechItems.powerSavingUpgradeMk3.get())
        simpleItem(NTechItems.overdriveUpgradeMk1.get())
        simpleItem(NTechItems.overdriveUpgradeMk2.get())
        simpleItem(NTechItems.overdriveUpgradeMk3.get())
        simpleItem(NTechItems.afterBurnUpgradeMk1.get())
        simpleItem(NTechItems.afterBurnUpgradeMk2.get())
        simpleItem(NTechItems.afterBurnUpgradeMk3.get())
        simpleItem(NTechItems.aluminiumShredderBlade.get())
        simpleItem(NTechItems.goldShredderBlade.get())
        simpleItem(NTechItems.ironShredderBlade.get())
        simpleItem(NTechItems.steelShredderBlade.get())
        simpleItem(NTechItems.titaniumShredderBlade.get())
        simpleItem(NTechItems.advancedAlloyShredderBlade.get())
        simpleItem(NTechItems.combineSteelShredderBlade.get())
        simpleItem(NTechItems.schrabidiumShredderBlade.get())
        simpleItem(NTechItems.deshShredderBlade.get())

        simpleItem(NTechItems.rbmkLid.get())
        simpleItem(NTechItems.rbmkGlassLid.get())

        for (itemRegistryObject in RegistriesAndLifecycle.ITEMS.entries) {
            val item = itemRegistryObject.get()
            if (item is RBMKPelletItem) {
                getBuilder(itemRegistryObject.id.path)
                    .parent(generatedItem)
                    .texture("layer0", itemTexture(item))
                    .texture("layer1", ntm("$ITEM_FOLDER/rbmk_pellet_enrichment_overlay_0")) // base item has no depletion
                    .apply {
                        if (item.canHaveXenon) // if the item can have xenon poisoning we need the undepleted xenon version as well
                            override().predicate(ntm("depletion"), 0F).predicate(ntm("xenon"), 1F)
                                .model(getBuilder("${itemRegistryObject.id.path}_poisoned")
                                    .parent(generatedItem)
                                    .texture("layer0", itemTexture(item))
                                    .texture("layer1", ntm("$ITEM_FOLDER/rbmk_pellet_enrichment_overlay_0"))
                                    .texture("layer2", ntm("${ITEM_FOLDER}/rbmk_pellet_xenon_overlay"))
                                )
                        for (i in 1..4) { // for all depletion levels...
                            override().predicate(ntm("depletion"), i.toFloat())
                                .apply { if (item.canHaveXenon) predicate(ntm("xenon"), 0F) } // if the item can have xenon poisoning, add a false predicate for it
                                .model(getBuilder("${itemRegistryObject.id.path}_depleted_$i")
                                    .parent(generatedItem)
                                    .texture("layer0", itemTexture(item))
                                    .texture("layer1", ntm("$ITEM_FOLDER/rbmk_pellet_enrichment_overlay_$i"))
                                )
                            if (item.canHaveXenon) {
                                // if the item can have xenon poisoning, do the same thing again but with xenon
                                override().predicate(ntm("depletion"), i.toFloat()).predicate(ntm("xenon"), 1F)
                                    .model(getBuilder("${itemRegistryObject.id.path}_depleted_${i}_poisoned")
                                        .parent(generatedItem)
                                        .texture("layer0", itemTexture(item))
                                        .texture("layer1", ntm("$ITEM_FOLDER/rbmk_pellet_enrichment_overlay_$i"))
                                        .texture("layer2", ntm("$ITEM_FOLDER/rbmk_pellet_xenon_overlay"))
                                    )
                            }
                        }
                    }
            }
        }

        simpleItem(NTechItems.emptyRBMKRod.get())
        simpleItem(NTechItems.rbmkRodUeu.get())
        simpleItem(NTechItems.rbmkRodMeu.get())
        simpleItem(NTechItems.rbmkRodHeu233.get())
        simpleItem(NTechItems.rbmkRodHeu235.get())
        simpleItem(NTechItems.rbmkRodThMeu.get())
        simpleItem(NTechItems.rbmkRodLep.get())
        simpleItem(NTechItems.rbmkRodMep.get())
        simpleItem(NTechItems.rbmkRodHep239.get())
        simpleItem(NTechItems.rbmkRodHep241.get())
        simpleItem(NTechItems.rbmkRodLea.get())
        simpleItem(NTechItems.rbmkRodMea.get())
        simpleItem(NTechItems.rbmkRodHea241.get())
        simpleItem(NTechItems.rbmkRodHea242.get())
        simpleItem(NTechItems.rbmkRodMen.get())
        simpleItem(NTechItems.rbmkRodHen.get())
        simpleItem(NTechItems.rbmkRodMox.get())
        simpleItem(NTechItems.rbmkRodLes.get())
        simpleItem(NTechItems.rbmkRodMes.get())
        simpleItem(NTechItems.rbmkRodHes.get())
        simpleItem(NTechItems.rbmkRodLeaus.get())
        simpleItem(NTechItems.rbmkRodHeaus.get())
        simpleItem(NTechItems.rbmkRodPo210Be.get())
        simpleItem(NTechItems.rbmkRodRa226Be.get())
        simpleItem(NTechItems.rbmkRodPu238Be.get())
        simpleItem(NTechItems.rbmkRodBalefireGold.get())
        simpleItem(NTechItems.rbmkRodFlashlead.get())
        simpleItem(NTechItems.rbmkRodBalefire.get())
        simpleItem(NTechItems.rbmkRodZfbBismuth.get())
        simpleItem(NTechItems.rbmkRodZfbPu241.get())
        simpleItem(NTechItems.rbmkRodZfbAmMix.get())
        simpleItem(NTechItems.rbmkRodDrx.get())

        simpleItem(NTechItems.meltdownTool.get())

        simpleItem(NTechItems.graphiteDebris.get())
        simpleItem(NTechItems.metalDebris.get())
        simpleItem(NTechItems.fuelDebris.get())

        simpleItem(NTechItems.machineTemplateFolder.get())
        simpleItem(NTechItems.sirenTrackAMSSiren.get())
        simpleItem(NTechItems.sirenTrackAPCPass.get())
        simpleItem(NTechItems.sirenTrackAPCSiren.get())
        simpleItem(NTechItems.sirenTrackAirRaidSiren.get())
        simpleItem(NTechItems.sirenTrackAutopilotDisconnected.get())
        simpleItem(NTechItems.sirenTrackBankAlarm.get())
        simpleItem(NTechItems.sirenTrackBeepSiren.get())
        simpleItem(NTechItems.sirenTrackBlastDoorAlarm.get())
        simpleItem(NTechItems.sirenTrackClassicSiren.get())
        simpleItem(NTechItems.sirenTrackContainerAlarm.get())
        simpleItem(NTechItems.sirenTrackEASAlarmScreech.get())
        simpleItem(NTechItems.sirenTrackHatchSiren.get())
        simpleItem(NTechItems.sirenTrackKlaxon.get())
        simpleItem(NTechItems.sirenTrackMissileSiloSiren.get())
        simpleItem(NTechItems.sirenTrackNostromoSelfDestruct.get())
        simpleItem(NTechItems.sirenTrackRazortrainHorn.get())
        simpleItem(NTechItems.sirenTrackSecurityAlert.get())
        simpleItem(NTechItems.sirenTrackStandardSiren.get())
        simpleItem(NTechItems.sirenTrackSweepSiren.get())
        simpleItem(NTechItems.sirenTrackVaultDoorAlarm.get())

        getBuilder(NTechItems.fluidIdentifier.id.path)
            .parent(generatedItem)
            .texture("layer0", itemTexture(NTechItems.fluidIdentifier.get()))
            .texture("layer1", itemTexture(NTechItems.fluidIdentifier.get()).appendToPath("_overlay"))

        getBuilder(NTechItems.assemblyTemplate.id.path)
            .parent(generatedItem)
            .texture("layer0", itemTexture(NTechItems.assemblyTemplate.get()))
            .override()
            .predicate(ntm("shift"), 1F)
            .model(specialEntityModel)
            .end()

        getBuilder(NTechItems.chemTemplate.id.path)
            .parent(generatedItem)
            .texture("layer0", itemTexture(NTechItems.chemTemplate.get()))
            .override()
            .predicate(ntm("shift"), 1F)
            .model(specialEntityModel)
            .end()

        simpleItem(NTechItems.neutronShieldingLittleBoy.get())
        simpleItem(NTechItems.subcriticalUraniumTarget.get())
        simpleItem(NTechItems.uraniumProjectile.get())
        simpleItem(NTechItems.propellantLittleBoy.get())
        simpleItem(NTechItems.bombIgniterLittleBoy.get())
        simpleItem(NTechItems.bundleOfImplosionPropellant.get())
        simpleItem(NTechItems.bombIgniterFatMan.get())
        simpleItem(NTechItems.plutoniumCore.get())
        simpleItem(NTechItems.detonator.get())
        simpleItem(NTechItems.designator.get())
        simpleItem(NTechItems.heMissile.get())
        simpleItem(NTechItems.incendiaryMissile.get())
        simpleItem(NTechItems.clusterMissile.get())
        simpleItem(NTechItems.bunkerBusterMissile.get())
        simpleItem(NTechItems.strongMissile.get())
        simpleItem(NTechItems.strongIncendiaryMissile.get())
        simpleItem(NTechItems.strongClusterMissile.get())
        simpleItem(NTechItems.strongBunkerBusterMissile.get())
        simpleItem(NTechItems.burstMissile.get())
        simpleItem(NTechItems.infernoMissile.get())
        simpleItem(NTechItems.rainMissile.get())
        simpleItem(NTechItems.drillMissile.get())
        simpleItem(NTechItems.nuclearMissile.get())
        simpleItem(NTechItems.tectonicMissile.get())
        simpleItem(NTechItems.oilDetector.get())
        simpleItem(NTechItems.rbmkLinker.get())
        simpleItem(NTechItems.geigerCounter.get())
        simpleItem(NTechItems.ivBag.get())
        simpleItem(NTechItems.bloodBag.get())
        simpleItem(NTechItems.emptyExperienceBag.get())
        simpleItem(NTechItems.experienceBag.get())
        simpleItem(NTechItems.radAway.get())
        simpleItem(NTechItems.strongRadAway.get())
        simpleItem(NTechItems.eliteRadAway.get())

        simpleItem(NTechItems.hazmatHelmet.get())
        simpleItem(NTechItems.hazmatChestplate.get())
        simpleItem(NTechItems.hazmatLeggings.get())
        simpleItem(NTechItems.hazmatBoots.get())
        simpleItem(NTechItems.advancedHazmatHelmet.get())
        simpleItem(NTechItems.advancedHazmatChestplate.get())
        simpleItem(NTechItems.advancedHazmatLeggings.get())
        simpleItem(NTechItems.advancedHazmatBoots.get())
        simpleItem(NTechItems.reinforcedHazmatHelmet.get())
        simpleItem(NTechItems.reinforcedHazmatChestplate.get())
        simpleItem(NTechItems.reinforcedHazmatLeggings.get())
        simpleItem(NTechItems.reinforcedHazmatBoots.get())
        simpleItem(NTechItems.titaniumHelmet.get())
        simpleItem(NTechItems.titaniumChestplate.get())
        simpleItem(NTechItems.titaniumLeggings.get())
        simpleItem(NTechItems.titaniumBoots.get())
        simpleItem(NTechItems.steelHelmet.get())
        simpleItem(NTechItems.steelChestplate.get())
        simpleItem(NTechItems.steelLeggings.get())
        simpleItem(NTechItems.steelBoots.get())
        simpleItem(NTechItems.advancedAlloyHelmet.get())
        simpleItem(NTechItems.advancedAlloyChestplate.get())
        simpleItem(NTechItems.advancedAlloyLeggings.get())
        simpleItem(NTechItems.advancedAlloyBoots.get())
        simpleItem(NTechItems.combineSteelHelmet.get())
        simpleItem(NTechItems.combineSteelChestplate.get())
        simpleItem(NTechItems.combineSteelLeggings.get())
        simpleItem(NTechItems.combineSteelBoots.get())
        simpleItem(NTechItems.paAAlloyChestplate.get())
        simpleItem(NTechItems.paAAlloyLeggings.get())
        simpleItem(NTechItems.paAAlloyBoots.get())
        simpleItem(NTechItems.schrabidiumHelmet.get())
        simpleItem(NTechItems.schrabidiumChestplate.get())
        simpleItem(NTechItems.schrabidiumLeggings.get())
        simpleItem(NTechItems.schrabidiumBoots.get())

        getBuilder(NTechItems.polaroid.id.path)
            .customLoader(::RandomModelBuilder)
            .idSupplier(NTechItems.polaroid.id)
            .apply {
                for (i in 1..18) randomModel(nested().parent(generatedItem).texture("layer0", modLoc("$ITEM_FOLDER/polaroid_$i")))
            }.end()

        simpleItem(NTechItems.creativeNuclearExplosionSpawner.get())

        bombKitItem = getBuilder("template_bomb_kit").parent(generatedItem)
            .texture("layer0", modLoc("$ITEM_FOLDER/bomb_kit"))
            .texture("layer1", modLoc("$ITEM_FOLDER/bomb_kit_overlay"))

        for (bombKit in BombKitItem.allKits) bombKit(bombKit)

        spawnEgg(NTechItems.nuclearCreeperSpawnEgg.get())

        // BlockItems

        getBuilder(NTechBlockItems.glowingMushroomBlock.id.path).parent(cubeAll).texture("all", blockTexture(NTechBlocks.glowingMushroomBlock.get()))
        getBuilder(NTechBlockItems.glowingMushroomStem.id.path).parent(cubeAll).texture("all", blockTexture(NTechBlocks.glowingMushroomStem.get()))
        simpleItem(NTechBlockItems.steamPress.get())
        // TODO make a template type of thing
        specialEntityItem(NTechBlockItems.assemblerPlacer.get()).transforms()
            .transform(ItemTransforms.TransformType.GUI).rotation(30F, 45F, 0F).translation(-3F, -1F, 0F).scale(.225F, .225F, .225F).end()
            .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(0.125F, 0.125F, 0.125F).end()
            .transform(ItemTransforms.TransformType.HEAD).rotation(0F, 180F, 0F).end()
            .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 180F, 0F).scale(0.25F, 0.25F, 0.25F).end()
            .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 315F, 0F).translation(0F, 5F, 0F).scale(0.1875F, 0.1875F, 0.1875F).end()
            .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 315F, 0F).scale(.2F, .2F, .2F).end().end()
        specialEntityItem(NTechBlockItems.chemPlantPlacer.get()).transforms()
            .transform(ItemTransforms.TransformType.GUI).rotation(30F, 45F, 0F).translation(-3F, -2F, 0F).scale(.225F, .225F, .225F).end()
            .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(0.125F, 0.125F, 0.125F).end()
            .transform(ItemTransforms.TransformType.HEAD).rotation(0F, 180F, 0F).end()
            .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 180F, 0F).scale(0.25F, 0.25F, 0.25F).end()
            .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 315F, 0F).translation(0F, 5F, 0F).scale(0.1875F, 0.1875F, 0.1875F).end()
            .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 315F, 0F).scale(.2F, .2F, .2F).end().end()
        specialEntityItem(NTechBlockItems.oilDerrickPlacer.get()).transforms()
            .transform(ItemTransforms.TransformType.GUI).rotation(30F, 45F, 0F).translation(0F, -4.5F, 0F).scale(.125F, .125F, .125F).end()
            .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(0.1F, 0.1F, 0.1F).end()
            .transform(ItemTransforms.TransformType.HEAD).rotation(0F, 180F, 0F).end()
            .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 180F, 0F).scale(0.2F, 0.2F, 0.2F).end()
            .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 315F, 0F).translation(0F, 5F, 0F).scale(0.15F, 0.15F, 0.15F).end()
            .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 315F, 0F).scale(.135F, .135F, .135F).end().end()
        specialEntityItem(NTechBlockItems.pumpjackPlacer.get()).transforms()
            .transform(ItemTransforms.TransformType.GUI).rotation(30F, 45F, 0F).translation(-4F, -1F, 0F).scale(.125F, .125F, .125F).end()
            .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(0.1F, 0.1F, 0.1F).end()
            .transform(ItemTransforms.TransformType.HEAD).rotation(0F, 0F, 0F).translation(0F, 1F, 0F).end()
            .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 180F, 0F).scale(0.2F, 0.2F, 0.2F).end()
            .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 45F, 0F).translation(0F, 5F, 0F).scale(0.15F, 0.15F, 0.15F).end()
            .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 45F, 0F).translation(-5F, 0F, -6F).scale(.135F, .135F, .135F).end().end()
        specialEntityItem(NTechBlockItems.centrifugePlacer.get()).transforms()
            .transform(ItemTransforms.TransformType.GUI).rotation(30F, 45F, 0F).translation(0F, -4.5F, 0F).scale(.24F, .24F, .24F).end()
            .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(0.125F, 0.125F, 0.125F).end()
            .transform(ItemTransforms.TransformType.HEAD).rotation(0F, 180F, 0F).end()
            .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 180F, 0F).scale(0.25F, 0.25F, 0.25F).end()
            .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 315F, 0F).scale(0.25F, 0.25F, 0.25F).end()
            .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 315F, 0F).scale(.25F, .25F, .25F).end().end()
        for (itemObject in RegistriesAndLifecycle.ITEMS.entries) {
            val item = itemObject.get()
            if (item is RBMKColumnBlockItem) {
                specialEntityItem(item).transforms()
                    .transform(ItemTransforms.TransformType.GUI).rotation(30F, 45F, 0F).translation(0F, 4.5F, 0F).scale(.225F, .225F, .225F).end()
                    .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(0.2F, 0.2F, 0.2F).end()
                    .transform(ItemTransforms.TransformType.HEAD).rotation(0F, 180F, 0F).end()
                    .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 180F, 0F).scale(0.2F, 0.2F, 0.2F).end()
                    .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 45F, 0F).translation(0F, 2.5F, 0F).scale(0.3F, 0.3F, 0.3F).end()
                    .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 45F, 0F).scale(.25F, .25F, .25F).end().end()
            }
        }
        specialEntityItem(NTechBlockItems.rbmkConsole.get()).transforms()
            .transform(ItemTransforms.TransformType.GUI).rotation(30F, 225F, 0F).translation(1.5F, -4.25F, 0F).scale(.17F).end()
            .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(.18F).end()
            .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 90F, 0F).translation(0F, -2F, 0F).scale(.35F).end()
            .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 135F, 0F).translation(0F, 2.5F, 0F).scale(.17F, .17F, .17F).end()
            .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 135F, 0F).translation(0F, -4F, 0F).scale(.2F, .2F, .2F).end().end()
        specialEntityItem(NTechBlockItems.littleBoy.get()).transforms()
            .transform(ItemTransforms.TransformType.GUI).rotation(30F, 225F, 0F).translation(3F, -2F, 0F).scale(.34F).end()
            .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(.25F, .25F, .25F).end()
            .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 90F, 0F).scale(.5F).end()
            .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 45F, 0F).translation(0F, 2.5F, 0F).scale(.375F, .375F, .375F).end()
            .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 45F, 0F).scale(.4F, .4F, .4F).end().end()
        specialEntityItem(NTechBlockItems.fatMan.get()).transforms()
            .transform(ItemTransforms.TransformType.GUI).rotation(30F, 225F, 0F).translation(2.5F, -3F, 0F).scale(.34F).end()
            .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(.25F, .25F, .25F).end()
            .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 90F, 0F).translation(0F, -2F, 0F).scale(.5F).end()
            .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 45F, 0F).translation(0F, 2.5F, 0F).scale(.375F, .375F, .375F).end()
            .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 45F, 0F).scale(.4F, .4F, .4F).end().end()
        specialEntityItem(NTechBlockItems.launchPadPlacer.get()).transforms()
            .transform(ItemTransforms.TransformType.GUI).rotation(30F, 45F, 0F).scale(.2F, .2F, .2F).end()
            .transform(ItemTransforms.TransformType.GROUND).translation(0F, 3F, 0F).scale(0.125F, 0.125F, 0.125F).end()
            .transform(ItemTransforms.TransformType.HEAD).rotation(0F, 180F, 0F).end()
            .transform(ItemTransforms.TransformType.FIXED).rotation(0F, 180F, 0F).scale(0.25F, 0.25F, 0.25F).end()
            .transform(ItemTransforms.TransformType.THIRD_PERSON_RIGHT_HAND).rotation(75F, 315F, 0F).translation(0F, 5F, 0F).scale(0.1875F, 0.1875F, 0.1875F).end()
            .transform(ItemTransforms.TransformType.FIRST_PERSON_RIGHT_HAND).rotation(0F, 315F, 0F).scale(.2F, .2F, .2F).end().end()

        // Buckets
        for ((source, _, bucket, _) in NTechFluids.getFluidsList()) bucket(source.get(), bucket.get())
    }

    val specialEntityModel = UncheckedModelFile("builtin/entity")

    private val cubeAll = getExistingFile(mcLoc("block/cube_all"))
    private val generatedItem = getExistingFile(mcLoc("item/generated"))
    private val spawnEggItem = getExistingFile(mcLoc("item/template_spawn_egg"))
    private lateinit var bombKitItem: ModelFile

    private fun simpleItem(item: Item) {
        getBuilder(item.registryName!!.path)
            .parent(generatedItem)
            .texture("layer0", itemTexture(item))
    }

    private fun bombKit(item: Item) {
        getBuilder(item.registryName!!.path).parent(bombKitItem)
    }

    private fun spawnEgg(item: Item) {
        getBuilder(item.registryName!!.path).parent(spawnEggItem)
    }

    private fun bucket(fluid: Fluid, bucket: BucketItem, flipGas: Boolean = fluid.attributes.isLighterThanAir) {
        withExistingParent(bucket.registryName!!.path, ResourceLocation("forge", "item/bucket"))
            .customLoader { modelBuilder: ItemModelBuilder, existingFileHelper -> DynamicBucketModelBuilder.begin(modelBuilder, existingFileHelper) }
            .fluid(fluid)
            .flipGas(flipGas)
            .end()
    }

    private fun specialEntityItem(item: Item) = getBuilder(item.registryName!!.path).parent(specialEntityModel)

    private fun blockTexture(block: Block) =
        ResourceLocation(block.registryName!!.namespace, "$BLOCK_FOLDER/${block.registryName!!.path}")

    private fun itemTexture(item: Item) =
        ResourceLocation(item.registryName!!.namespace, "$ITEM_FOLDER/${item.registryName!!.path}")
}
