package at.martinthedragon.nucleartech.datagen

import at.martinthedragon.nucleartech.*
import at.martinthedragon.nucleartech.datagen.model.RandomModelBuilder
import at.martinthedragon.nucleartech.fluid.NTechFluids
import at.martinthedragon.nucleartech.items.BombKitItem
import net.minecraft.data.DataGenerator
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.item.BucketItem
import net.minecraft.world.item.Item
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.material.Fluid
import net.minecraftforge.client.model.generators.ItemModelBuilder
import net.minecraftforge.client.model.generators.ItemModelProvider
import net.minecraftforge.client.model.generators.ModelFile
import net.minecraftforge.client.model.generators.ModelFile.UncheckedModelFile
import net.minecraftforge.client.model.generators.loaders.DynamicBucketModelBuilder
import net.minecraftforge.common.data.ExistingFileHelper

class NuclearItemModelProvider(
    dataGenerator: DataGenerator,
    existingFileHelper: ExistingFileHelper
) : ItemModelProvider(dataGenerator, NuclearTech.MODID, existingFileHelper) {
    override fun getName(): String = "Nuclear Tech Mod Item Models"

    override fun registerModels() {
        simpleItem(ModItems.rawAluminium.get())
        simpleItem(ModItems.rawAustralium.get())
        simpleItem(ModItems.rawBeryllium.get())
        simpleItem(ModItems.rawCobalt.get())
        simpleItem(ModItems.rawLead.get())
        simpleItem(ModItems.rawLithium.get())
        simpleItem(ModItems.rawPlutonium.get())
        simpleItem(ModItems.rawRareEarth.get())
        simpleItem(ModItems.rawSchrabidium.get())
        simpleItem(ModItems.rawStarmetal.get())
        simpleItem(ModItems.rawThorium.get())
        simpleItem(ModItems.rawTitanium.get())
        simpleItem(ModItems.rawTrixite.get())
        simpleItem(ModItems.rawTungsten.get())
        simpleItem(ModItems.rawUranium.get())

        simpleItem(ModItems.actiniumIngot.get())
        simpleItem(ModItems.advancedAlloyIngot.get())
        simpleItem(ModItems.aluminiumIngot.get())
        simpleItem(ModItems.americium241Ingot.get())
        simpleItem(ModItems.americium242Ingot.get())
        simpleItem(ModItems.americiumFuelIngot.get())
        simpleItem(ModItems.arsenicIngot.get())
        simpleItem(ModItems.australiumIngot.get())
        simpleItem(ModItems.bakeliteIngot.get())
        simpleItem(ModItems.berylliumIngot.get())
        simpleItem(ModItems.bismuthIngot.get())
        simpleItem(ModItems.boronIngot.get())
        simpleItem(ModItems.cobaltIngot.get())
        simpleItem(ModItems.cobalt60Ingot.get())
        simpleItem(ModItems.combineSteelIngot.get())
        simpleItem(ModItems.daffergonIngot.get())
        simpleItem(ModItems.deshIngot.get())
        simpleItem(ModItems.dineutroniumIngot.get())
        simpleItem(ModItems.electroniumIngot.get())
        simpleItem(ModItems.euphemiumIngot.get())
        simpleItem(ModItems.ferricSchrabidateIngot.get())
        simpleItem(ModItems.ghiorsium336Ingot.get())
        simpleItem(ModItems.gold198Ingot.get())
        simpleItem(ModItems.graphiteIngot.get())
        simpleItem(ModItems.highEnrichedSchrabidiumFuelIngot.get())
        simpleItem(ModItems.highSpeedSteelIngot.get())
        simpleItem(ModItems.lanthanumIngot.get())
        simpleItem(ModItems.leadIngot.get())
        simpleItem(ModItems.lead209Ingot.get())
        simpleItem(ModItems.lowEnrichedSchrabidiumFuelIngot.get())
        simpleItem(ModItems.magnetizedTungstenIngot.get())
        simpleItem(ModItems.moxFuelIngot.get())
        simpleItem(ModItems.neptuniumIngot.get())
        simpleItem(ModItems.neptuniumFuelIngot.get())
        simpleItem(ModItems.niobiumIngot.get())
        simpleItem(ModItems.osmiridiumIngot.get())
        simpleItem(ModItems.plutoniumFuelIngot.get())
        simpleItem(ModItems.plutoniumIngot.get())
        simpleItem(ModItems.polonium210Ingot.get())
        simpleItem(ModItems.polymerIngot.get())
        simpleItem(ModItems.pu238Ingot.get())
        simpleItem(ModItems.pu239Ingot.get())
        simpleItem(ModItems.pu240Ingot.get())
        simpleItem(ModItems.pu241Ingot.get())
        simpleItem(ModItems.radium226Ingot.get())
        simpleItem(ModItems.reactorGradeAmericiumIngot.get())
        simpleItem(ModItems.reactorGradePlutoniumIngot.get())
        simpleItem(ModItems.redCopperIngot.get())
        simpleItem(ModItems.reiiumIngot.get())
        simpleItem(ModItems.rubberIngot.get())
        simpleItem(ModItems.saturniteIngot.get())
        simpleItem(ModItems.schrabidiumFuelIngot.get())
        simpleItem(ModItems.schrabidiumIngot.get())
        simpleItem(ModItems.schraraniumIngot.get())
        simpleItem(ModItems.soliniumIngot.get())
        simpleItem(ModItems.starmetalIngot.get())
        simpleItem(ModItems.steelIngot.get())
        simpleItem(ModItems.strontium90Ingot.get())
        simpleItem(ModItems.tantaliumIngot.get())
        simpleItem(ModItems.technetium99Ingot.get())
        simpleItem(ModItems.technetiumSteelIngot.get())
        simpleItem(ModItems.th232Ingot.get())
        simpleItem(ModItems.thoriumFuelIngot.get())
        simpleItem(ModItems.titaniumIngot.get())
        simpleItem(ModItems.tungstenIngot.get())
        simpleItem(ModItems.u233Ingot.get())
        simpleItem(ModItems.u235Ingot.get())
        simpleItem(ModItems.u238Ingot.get())
        simpleItem(ModItems.unobtainiumIngot.get())
        simpleItem(ModItems.uraniumFuelIngot.get())
        simpleItem(ModItems.uraniumIngot.get())
        simpleItem(ModItems.verticiumIngot.get())
        simpleItem(ModItems.weidaniumIngot.get())
        simpleItem(ModItems.whitePhosphorusIngot.get())

        simpleItem(ModItems.asbestosSheet.get())
        simpleItem(ModItems.coke.get())
        simpleItem(ModItems.fiberglassSheet.get())
        simpleItem(ModItems.lignite.get())
        simpleItem(ModItems.ligniteBriquette.get())
        simpleItem(ModItems.lithiumCube.get())
        simpleItem(ModItems.mercuryBottle.get())
        simpleItem(ModItems.mercuryDroplet.get())
        simpleItem(ModItems.semtexBar.get())
        simpleItem(ModItems.solidFuelCube.get())
        simpleItem(ModItems.solidRocketFuelCube.get())

        simpleItem(ModItems.actiniumPowder.get())
        simpleItem(ModItems.advancedAlloyPowder.get())
        simpleItem(ModItems.aluminiumPowder.get())
        simpleItem(ModItems.asbestosPowder.get())
        simpleItem(ModItems.australiumPowder.get())
        simpleItem(ModItems.ballistite.get())
        simpleItem(ModItems.berylliumPowder.get())
        simpleItem(ModItems.ceriumPowder.get())
        simpleItem(ModItems.chlorophytePowder.get())
        simpleItem(ModItems.cloudResidue.get())
        simpleItem(ModItems.coalPowder.get())
        simpleItem(ModItems.cobaltPowder.get())
        simpleItem(ModItems.combineSteelPowder.get())
        simpleItem(ModItems.copperPowder.get())
        simpleItem(ModItems.cordite.get())
        simpleItem(ModItems.cryoPowder.get())
        simpleItem(ModItems.daffergonPowder.get())
        simpleItem(ModItems.desaturatedRedstone.get())
        simpleItem(ModItems.deshMix.get())
        simpleItem(ModItems.deshPowder.get())
        simpleItem(ModItems.deshReadyMix.get())
        simpleItem(ModItems.diamondPowder.get())
        simpleItem(ModItems.dineutroniumPowder.get())
        simpleItem(ModItems.dust.get())
        simpleItem(ModItems.emeraldPowder.get())
        simpleItem(ModItems.enchantmentPowder.get())
        simpleItem(ModItems.energyPowder.get())
        simpleItem(ModItems.euphemiumPowder.get())
        simpleItem(ModItems.fluorite.get())
        simpleItem(ModItems.goldPowder.get())
        simpleItem(ModItems.highSpeedSteelPowder.get())
        simpleItem(ModItems.ironPowder.get())
        simpleItem(ModItems.lanthanumPowder.get())
        simpleItem(ModItems.lapisLazuliPowder.get())
        simpleItem(ModItems.leadPowder.get())
        simpleItem(ModItems.lignitePowder.get())
        simpleItem(ModItems.lithiumPowder.get())
        simpleItem(ModItems.magnetizedTungstenPowder.get())
        simpleItem(ModItems.meteoritePowder.get())
        simpleItem(ModItems.neodymiumPowder.get())
        simpleItem(ModItems.neptuniumPowder.get())
        simpleItem(ModItems.niobiumPowder.get())
        simpleItem(ModItems.nitaniumMix.get())
        simpleItem(ModItems.niter.get())
        simpleItem(ModItems.plutoniumPowder.get())
        simpleItem(ModItems.poisonPowder.get())
        simpleItem(ModItems.poloniumPowder.get())
        simpleItem(ModItems.polymerPowder.get())
        simpleItem(ModItems.quartzPowder.get())
        simpleItem(ModItems.redCopperPowder.get())
        simpleItem(ModItems.redPhosphorus.get())
        simpleItem(ModItems.reiiumPowder.get())
        simpleItem(ModItems.schrabidiumPowder.get())
        simpleItem(ModItems.semtexMix.get())
        simpleItem(ModItems.sparkMix.get())
        simpleItem(ModItems.steelPowder.get())
        simpleItem(ModItems.sulfur.get())
        simpleItem(ModItems.thermite.get())
        simpleItem(ModItems.thermonuclearAshes.get())
        simpleItem(ModItems.thoriumPowder.get())
        simpleItem(ModItems.tinyActiniumPowder.get())
        simpleItem(ModItems.tinyCeriumPowder.get())
        simpleItem(ModItems.tinyCobaltPowder.get())
        simpleItem(ModItems.tinyLanthanumPowder.get())
        simpleItem(ModItems.tinyLithiumPowder.get())
        simpleItem(ModItems.tinyMeteoritePowder.get())
        simpleItem(ModItems.tinyNeodymiumPowder.get())
        simpleItem(ModItems.tinyNiobiumPowder.get())
        simpleItem(ModItems.titaniumPowder.get())
        simpleItem(ModItems.tungstenPowder.get())
        simpleItem(ModItems.unobtainiumPowder.get())
        simpleItem(ModItems.uraniumPowder.get())
        simpleItem(ModItems.verticiumPowder.get())
        simpleItem(ModItems.weidaniumPowder.get())
        simpleItem(ModItems.yellowcake.get())

        simpleItem(ModItems.aluminiumCrystals.get())
        simpleItem(ModItems.berylliumCrystals.get())
        simpleItem(ModItems.coalCrystals.get())
        simpleItem(ModItems.cobaltCrystals.get())
        simpleItem(ModItems.copperCrystals.get())
        simpleItem(ModItems.diamondCrystals.get())
        simpleItem(ModItems.fluoriteCrystals.get())
        simpleItem(ModItems.goldCrystals.get())
        simpleItem(ModItems.ironCrystals.get())
        simpleItem(ModItems.lapisCrystals.get())
        simpleItem(ModItems.leadCrystals.get())
        simpleItem(ModItems.lithiumCrystals.get())
        simpleItem(ModItems.niterCrystals.get())
        simpleItem(ModItems.osmiridiumCrystals.get())
        simpleItem(ModItems.plutoniumCrystals.get())
        simpleItem(ModItems.rareEarthCrystals.get())
        simpleItem(ModItems.redPhosphorusCrystals.get())
        simpleItem(ModItems.redstoneCrystals.get())
        simpleItem(ModItems.schrabidiumCrystals.get())
        simpleItem(ModItems.schraraniumCrystals.get())
        simpleItem(ModItems.starmetalCrystals.get())
        simpleItem(ModItems.sulfurCrystals.get())
        simpleItem(ModItems.thoriumCrystals.get())
        simpleItem(ModItems.titaniumCrystals.get())
        simpleItem(ModItems.trixiteCrystals.get())
        simpleItem(ModItems.tungstenCrystals.get())
        simpleItem(ModItems.uraniumCrystals.get())

        simpleItem(ModItems.actiniumFragment.get())
        simpleItem(ModItems.ceriumFragment.get())
        simpleItem(ModItems.cobaltFragment.get())
        simpleItem(ModItems.lanthanumFragment.get())
        simpleItem(ModItems.meteoriteFragment.get())
        simpleItem(ModItems.neodymiumFragment.get())

        simpleItem(ModItems.biomass.get())
        simpleItem(ModItems.compressedBiomass.get())

        simpleItem(ModItems.actinium227Nugget.get())
        simpleItem(ModItems.americium241Nugget.get())
        simpleItem(ModItems.americium242Nugget.get())
        simpleItem(ModItems.americiumFuelNugget.get())
        simpleItem(ModItems.arsenicNugget.get())
        simpleItem(ModItems.australiumNugget.get())
        simpleItem(ModItems.berylliumNugget.get())
        simpleItem(ModItems.bismuthNugget.get())
        simpleItem(ModItems.cobaltNugget.get())
        simpleItem(ModItems.cobalt60Nugget.get())
        simpleItem(ModItems.daffergonNugget.get())
        simpleItem(ModItems.deshNugget.get())
        simpleItem(ModItems.dineutroniumNugget.get())
        simpleItem(ModItems.euphemiumNugget.get())
        simpleItem(ModItems.ghiorsium336Nugget.get())
        simpleItem(ModItems.gold198Nugget.get())
        simpleItem(ModItems.highEnrichedSchrabidiumFuelNugget.get())
        simpleItem(ModItems.leadNugget.get())
        simpleItem(ModItems.lead209Nugget.get())
        simpleItem(ModItems.lowEnrichedSchrabidiumFuelNugget.get())
        simpleItem(ModItems.moxFuelNugget.get())
        simpleItem(ModItems.neptuniumNugget.get())
        simpleItem(ModItems.neptuniumFuelNugget.get())
        simpleItem(ModItems.niobiumFragment.get())
        simpleItem(ModItems.osmiridiumNugget.get())
        simpleItem(ModItems.plutoniumFuelNugget.get())
        simpleItem(ModItems.plutoniumNugget.get())
        simpleItem(ModItems.poloniumNugget.get())
        simpleItem(ModItems.pu238Nugget.get())
        simpleItem(ModItems.pu239Nugget.get())
        simpleItem(ModItems.pu240Nugget.get())
        simpleItem(ModItems.pu241Nugget.get())
        simpleItem(ModItems.radium226Nugget.get())
        simpleItem(ModItems.reactorGradeAmericiumNugget.get())
        simpleItem(ModItems.reactorGradePlutoniumNugget.get())
        simpleItem(ModItems.reiiumNugget.get())
        simpleItem(ModItems.schrabidiumFuelNugget.get())
        simpleItem(ModItems.schrabidiumNugget.get())
        simpleItem(ModItems.soliniumNugget.get())
        simpleItem(ModItems.strontium90Nugget.get())
        simpleItem(ModItems.tantaliumNugget.get())
        simpleItem(ModItems.technetium99Nugget.get())
        simpleItem(ModItems.th232Nugget.get())
        simpleItem(ModItems.thoriumFuelNugget.get())
        simpleItem(ModItems.u233Nugget.get())
        simpleItem(ModItems.u235Nugget.get())
        simpleItem(ModItems.u238Nugget.get())
        simpleItem(ModItems.unobtainiumNugget.get())
        simpleItem(ModItems.uraniumFuelNugget.get())
        simpleItem(ModItems.uraniumNugget.get())
        simpleItem(ModItems.verticiumNugget.get())
        simpleItem(ModItems.weidaniumNugget.get())

        simpleItem(ModItems.advancedAlloyPlate.get())
        simpleItem(ModItems.aluminiumPlate.get())
        simpleItem(ModItems.combineSteelPlate.get())
        simpleItem(ModItems.copperPanel.get())
        simpleItem(ModItems.copperPlate.get())
        simpleItem(ModItems.dalekaniumPlate.get())
        simpleItem(ModItems.deshCompoundPlate.get())
        simpleItem(ModItems.dineutroniumCompoundPlate.get())
        simpleItem(ModItems.euphemiumCompoundPlate.get())
        simpleItem(ModItems.goldPlate.get())
        simpleItem(ModItems.insulator.get())
        simpleItem(ModItems.ironPlate.get())
        simpleItem(ModItems.kevlarCeramicCompound.get())
        simpleItem(ModItems.leadPlate.get())
        simpleItem(ModItems.mixedPlate.get())
        simpleItem(ModItems.neutronReflector.get())
        simpleItem(ModItems.paAAlloyPlate.get())
        simpleItem(ModItems.saturnitePlate.get())
        simpleItem(ModItems.schrabidiumPlate.get())
        simpleItem(ModItems.steelPlate.get())
        simpleItem(ModItems.titaniumPlate.get())

        simpleItem(ModItems.activatedCarbonFilter.get())
        simpleItem(ModItems.advancedHazmatCloth.get())
        simpleItem(ModItems.fireProximityCloth.get())
        simpleItem(ModItems.hazmatCloth.get())
        simpleItem(ModItems.highSpeedSteelBolt.get())
        simpleItem(ModItems.leadReinforcedHazmatCloth.get())
        simpleItem(ModItems.reinforcedTurbineShaft.get())
        simpleItem(ModItems.tungstenBolt.get())

        simpleItem(ModItems.aluminiumWire.get())
        simpleItem(ModItems.copperCoil.get())
        simpleItem(ModItems.copperWire.get())
        simpleItem(ModItems.goldCoil.get())
        simpleItem(ModItems.goldRingCoil.get())
        simpleItem(ModItems.goldWire.get())
        simpleItem(ModItems.heatingCoil.get())
        simpleItem(ModItems.highTemperatureSuperConductingCoil.get())
        simpleItem(ModItems.highTemperatureSuperConductor.get())
        simpleItem(ModItems.redCopperWire.get())
        simpleItem(ModItems.ringCoil.get())
        simpleItem(ModItems.schrabidiumWire.get())
        simpleItem(ModItems.superConductingCoil.get())
        simpleItem(ModItems.superConductingRingCoil.get())
        simpleItem(ModItems.superConductor.get())
        simpleItem(ModItems.tungstenWire.get())

        simpleItem(ModItems.aluminiumCap.get())
        simpleItem(ModItems.bigAluminiumShell.get())
        simpleItem(ModItems.bigSteelGridFins.get())
        simpleItem(ModItems.bigSteelShell.get())
        simpleItem(ModItems.bigTitaniumShell.get())
        simpleItem(ModItems.breedingReactorCore.get())
        simpleItem(ModItems.centrifugeElement.get())
        simpleItem(ModItems.centrifugeTower.get())
        simpleItem(ModItems.chlorinePinwheel.get())
        simpleItem(ModItems.clayCatalyst.get())
        simpleItem(ModItems.cyclotronTower.get())
        simpleItem(ModItems.deeMagnets.get())
        simpleItem(ModItems.ductTape.get())
        simpleItem(ModItems.dysfunctionalNuclearReactor.get())
        simpleItem(ModItems.emitterComponent.get())
        simpleItem(ModItems.endothermicDistributionUnit.get())
        simpleItem(ModItems.entanglementKit.get())
        simpleItem(ModItems.exothermicDistributionUnit.get())
        simpleItem(ModItems.flatMagnet.get())
        simpleItem(ModItems.flatSteelCasing.get())
        simpleItem(ModItems.generatorBody.get())
        simpleItem(ModItems.generatorFront.get())
        simpleItem(ModItems.gravityManipulator.get())
        simpleItem(ModItems.largeSteelFins.get())
        simpleItem(ModItems.largeSteelRotor.get())
        simpleItem(ModItems.motor.get())
        simpleItem(ModItems.photovoltaicPanel.get())
        simpleItem(ModItems.reinforcedTurbofanBlades.get())
        simpleItem(ModItems.rtgUnit.get())
        simpleItem(ModItems.smallAluminiumShell.get())
        simpleItem(ModItems.smallSteelGridFins.get())
        simpleItem(ModItems.smallSteelShell.get())
        simpleItem(ModItems.smallTitaniumFins.get())
        simpleItem(ModItems.stabilizerComponent.get())
        simpleItem(ModItems.steelPedestal.get())
        simpleItem(ModItems.steelPipes.get())
        simpleItem(ModItems.steelSphere.get())
        simpleItem(ModItems.steelTank.get())
        simpleItem(ModItems.telepad.get())
        simpleItem(ModItems.thermalDistributionUnit.get())
        simpleItem(ModItems.titaniumBlade.get())
        simpleItem(ModItems.titaniumDrill.get())
        simpleItem(ModItems.titaniumSteamTurbine.get())
        simpleItem(ModItems.toothpicks.get())
        simpleItem(ModItems.tungstenReinforcedBlade.get())

        simpleItem(ModItems.advancedCircuit.get())
        simpleItem(ModItems.advancedLauncherMechanism.get())
        simpleItem(ModItems.advancedRevolverMechanism.get())
        simpleItem(ModItems.advancedRifleMechanism.get())
        simpleItem(ModItems.basicCircuit.get())
        simpleItem(ModItems.basicCircuitAssembly.get())
        simpleItem(ModItems.blankRune.get())
        simpleItem(ModItems.buckshotCasing.get())
        simpleItem(ModItems.buckshotPrimer.get())
        simpleItem(ModItems.burnedOutQuadSchrabidiumFuelRod.get())
        simpleItem(ModItems.burntBark.get())
        simpleItem(ModItems.cableDrum.get())
        simpleItem(ModItems.charredCrystal.get())
        simpleItem(ModItems.combineScrapMetal.get())
        simpleItem(ModItems.conspiracyTheory.get())
        simpleItem(ModItems.crystalHorn.get())
        simpleItem(ModItems.dagazRune.get())
        simpleItem(ModItems.deathRay.get())
        simpleItem(ModItems.denseCoalCluster.get())
        simpleItem(ModItems.depletedMOXFuel.get())
        simpleItem(ModItems.depletedPlutoniumFuel.get())
        simpleItem(ModItems.depletedSchrabidiumFuel.get())
        simpleItem(ModItems.depletedThoriumFuel.get())
        simpleItem(ModItems.depletedUraniumFuel.get())
        simpleItem(ModItems.deshBulletAssembly.get())
        simpleItem(ModItems.emplacementGun.get())
        simpleItem(ModItems.endothermicWarhead.get())
        simpleItem(ModItems.enhancedCircuit.get())
        simpleItem(ModItems.exothermicWarhead.get())
        simpleItem(ModItems.explosivePellets.get())
        simpleItem(ModItems.fivePoint56mmAssembly.get())
        simpleItem(ModItems.flechettes.get())
        simpleItem(ModItems.glassBulletAssembly.get())
        simpleItem(ModItems.goldBulletAssembly.get())
        simpleItem(ModItems.hagalazRune.get())
        simpleItem(ModItems.heavyAxeHead.get())
        simpleItem(ModItems.heavyHammerHead.get())
        simpleItem(ModItems.highGainOpticalCamera.get())
        simpleItem(ModItems.highPerformanceCircuit.get())
        simpleItem(ModItems.highTechWeaponMechanism.get())
        simpleItem(ModItems.hotDepletedMOXFuel.get())
        simpleItem(ModItems.hotDepletedPlutoniumFuel.get())
        simpleItem(ModItems.hotDepletedSchrabidiumFuel.get())
        simpleItem(ModItems.hotDepletedThoriumFuel.get())
        simpleItem(ModItems.hotDepletedUraniumFuel.get())
        simpleItem(ModItems.hunterChopperBody.get())
        simpleItem(ModItems.hunterChopperCockpit.get())
        simpleItem(ModItems.hunterChopperRotorBlades.get())
        simpleItem(ModItems.hunterChopperTail.get())
        simpleItem(ModItems.hunterChopperWing.get())
        simpleItem(ModItems.ironBulletAssembly.get())
        simpleItem(ModItems.isaRune.get())
        simpleItem(ModItems.jeraRune.get())
        simpleItem(ModItems.largeBunkerBusterWarhead.get())
        simpleItem(ModItems.largeCaliberCasing.get())
        simpleItem(ModItems.largeCaliberPrimer.get())
        simpleItem(ModItems.largeClusterWarhead.get())
        simpleItem(ModItems.largeFuelTank.get())
        simpleItem(ModItems.largeIncendiaryWarhead.get())
        simpleItem(ModItems.largeThruster.get())
        simpleItem(ModItems.largeWarhead.get())
        simpleItem(ModItems.launcherMechanism.get())
        simpleItem(ModItems.leadBulletAssembly.get())
        simpleItem(ModItems.leadPellets.get())
        simpleItem(ModItems.lvnNuclearRocketEngine.get())
        simpleItem(ModItems.m700SurveyScanner.get())
        simpleItem(ModItems.machineUpgradeTemplate.get())
        simpleItem(ModItems.magnetron.get())
        simpleItem(ModItems.mediumBunkerBusterWarhead.get())
        simpleItem(ModItems.mediumClusterWarhead.get())
        simpleItem(ModItems.mediumFuelTank.get())
        simpleItem(ModItems.mediumIncendiaryWarhead.get())
        simpleItem(ModItems.mediumThruster.get())
        simpleItem(ModItems.mediumWarhead.get())
        simpleItem(ModItems.militaryGradeCircuitBoardTier1.get())
        simpleItem(ModItems.militaryGradeCircuitBoardTier2.get())
        simpleItem(ModItems.militaryGradeCircuitBoardTier3.get())
        simpleItem(ModItems.militaryGradeCircuitBoardTier4.get())
        simpleItem(ModItems.militaryGradeCircuitBoardTier5.get())
        simpleItem(ModItems.militaryGradeCircuitBoardTier6.get())
        simpleItem(ModItems.nightmareBulletAssembly.get())
        simpleItem(ModItems.nineMmAssembly.get())
        simpleItem(ModItems.nuclearWarhead.get())
        simpleItem(ModItems.nuclearWaste.get())
        simpleItem(ModItems.overclockedCircuit.get())
        simpleItem(ModItems.ownOpinion.get())
        simpleItem(ModItems.paintingOfACartoonPony.get())
        simpleItem(ModItems.point22LRAssembly.get())
        simpleItem(ModItems.point357MagnumCasing.get())
        simpleItem(ModItems.point357MagnumPrimer.get())
        simpleItem(ModItems.point44MagnumAssembly.get())
        simpleItem(ModItems.point44MagnumCasing.get())
        simpleItem(ModItems.point44MagnumPrimer.get())
        simpleItem(ModItems.point50AEAssembly.get())
        simpleItem(ModItems.point50BMGAssembly.get())
        simpleItem(ModItems.point5mmAssembly.get())
        simpleItem(ModItems.poisonGasCartridge.get())
        simpleItem(ModItems.politicalTopic.get())
        simpleItem(ModItems.radarDish.get())
        simpleItem(ModItems.reinforcedPolymerHandle.get())
        simpleItem(ModItems.revolverMechanism.get())
        simpleItem(ModItems.rifleMechanism.get())
        simpleItem(ModItems.satelliteBase.get())
        simpleItem(ModItems.schrabidiumBulletAssembly.get())
        simpleItem(ModItems.scrap.get())
        simpleItem(ModItems.silverBulletCasing.get())
        simpleItem(ModItems.size10Connector.get())
        simpleItem(ModItems.size15Connector.get())
        simpleItem(ModItems.size20Connector.get())
        simpleItem(ModItems.smallBunkerBusterWarhead.get())
        simpleItem(ModItems.smallCaliberCasing.get())
        simpleItem(ModItems.smallCaliberPrimer.get())
        simpleItem(ModItems.smallClusterWarhead.get())
        simpleItem(ModItems.smallFuelTank.get())
        simpleItem(ModItems.smallIncendiaryWarhead.get())
        simpleItem(ModItems.smallMissileAssembly.get())
        simpleItem(ModItems.smallThruster.get())
        simpleItem(ModItems.smallWarhead.get())
        simpleItem(ModItems.thermonuclearWarhead.get())
        simpleItem(ModItems.thurisazRune.get())
        simpleItem(ModItems.tinyNuclearWaste.get())
        simpleItem(ModItems.trinitite.get())
        simpleItem(ModItems.twelvePoint8cmDUShell.get())
        simpleItem(ModItems.twelvePoint8cmNuclearShell.get())
        simpleItem(ModItems.twelvePoint8cmStarmetalHighEnergyShell.get())
        simpleItem(ModItems.xeniumResonator.get())

        simpleItem(ModItems.battery.get())
        simpleItem(ModItems.redstonePowerCell.get())
        simpleItem(ModItems.sixfoldRedstonePowerCell.get())
        simpleItem(ModItems.twentyFourFoldRedstonePowerCell.get())
        simpleItem(ModItems.advancedBattery.get())
        simpleItem(ModItems.advancedPowerCell.get())
        simpleItem(ModItems.quadrupleAdvancedPowerCell.get())
        simpleItem(ModItems.twelveFoldAdvancedPowerCell.get())
        simpleItem(ModItems.lithiumBattery.get())
        simpleItem(ModItems.lithiumPowerCell.get())
        simpleItem(ModItems.tripleLithiumPowerCell.get())
        simpleItem(ModItems.sixfoldLithiumPowerCell.get())
        simpleItem(ModItems.schrabidiumBattery.get())
        simpleItem(ModItems.schrabidiumPowerCell.get())
        simpleItem(ModItems.doubleSchrabidiumPowerCell.get())
        simpleItem(ModItems.quadrupleSchrabidiumPowerCell.get())
        simpleItem(ModItems.sparkBattery.get())
        simpleItem(ModItems.offBrandSparkBattery.get())
        simpleItem(ModItems.sparkPowerCell.get())
        simpleItem(ModItems.sparkArcaneCarBattery.get())
        simpleItem(ModItems.sparkArcaneEnergyStorageArray.get())
        simpleItem(ModItems.sparkArcaneMassEnergyVoid.get())
        simpleItem(ModItems.sparkArcaneDiracSea.get())
        simpleItem(ModItems.sparkSolidSpaceTimeCrystal.get())
        simpleItem(ModItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit.get())
        simpleItem(ModItems.infiniteBattery.get())
        simpleItem(ModItems.singleUseBattery.get())
        simpleItem(ModItems.largeSingleUseBattery.get())
        simpleItem(ModItems.potatoBattery.get())
        simpleItem(ModItems.steamPoweredEnergyStorageTank.get())
        simpleItem(ModItems.largeSteamPoweredEnergyStorageTank.get())

        simpleItem(ModItems.stoneFlatStamp.get())
        simpleItem(ModItems.stonePlateStamp.get())
        simpleItem(ModItems.stoneWireStamp.get())
        simpleItem(ModItems.stoneCircuitStamp.get())
        simpleItem(ModItems.ironFlatStamp.get())
        simpleItem(ModItems.ironPlateStamp.get())
        simpleItem(ModItems.ironWireStamp.get())
        simpleItem(ModItems.ironCircuitStamp.get())
        simpleItem(ModItems.steelFlatStamp.get())
        simpleItem(ModItems.steelPlateStamp.get())
        simpleItem(ModItems.steelWireStamp.get())
        simpleItem(ModItems.steelCircuitStamp.get())
        simpleItem(ModItems.titaniumFlatStamp.get())
        simpleItem(ModItems.titaniumPlateStamp.get())
        simpleItem(ModItems.titaniumWireStamp.get())
        simpleItem(ModItems.titaniumCircuitStamp.get())
        simpleItem(ModItems.obsidianFlatStamp.get())
        simpleItem(ModItems.obsidianPlateStamp.get())
        simpleItem(ModItems.obsidianWireStamp.get())
        simpleItem(ModItems.obsidianCircuitStamp.get())
        simpleItem(ModItems.schrabidiumFlatStamp.get())
        simpleItem(ModItems.schrabidiumPlateStamp.get())
        simpleItem(ModItems.schrabidiumWireStamp.get())
        simpleItem(ModItems.schrabidiumCircuitStamp.get())
        simpleItem(ModItems.aluminiumShredderBlade.get())
        simpleItem(ModItems.goldShredderBlade.get())
        simpleItem(ModItems.ironShredderBlade.get())
        simpleItem(ModItems.steelShredderBlade.get())
        simpleItem(ModItems.titaniumShredderBlade.get())
        simpleItem(ModItems.advancedAlloyShredderBlade.get())
        simpleItem(ModItems.combineSteelShredderBlade.get())
        simpleItem(ModItems.schrabidiumShredderBlade.get())
        simpleItem(ModItems.deshShredderBlade.get())
        simpleItem(ModItems.machineTemplateFolder.get())

        simpleItem(ModItems.sirenTrackAMSSiren.get())
        simpleItem(ModItems.sirenTrackAPCPass.get())
        simpleItem(ModItems.sirenTrackAPCSiren.get())
        simpleItem(ModItems.sirenTrackAirRaidSiren.get())
        simpleItem(ModItems.sirenTrackAutopilotDisconnected.get())
        simpleItem(ModItems.sirenTrackBankAlarm.get())
        simpleItem(ModItems.sirenTrackBeepSiren.get())
        simpleItem(ModItems.sirenTrackBlastDoorAlarm.get())
        simpleItem(ModItems.sirenTrackClassicSiren.get())
        simpleItem(ModItems.sirenTrackContainerAlarm.get())
        simpleItem(ModItems.sirenTrackEASAlarmScreech.get())
        simpleItem(ModItems.sirenTrackHatchSiren.get())
        simpleItem(ModItems.sirenTrackKlaxon.get())
        simpleItem(ModItems.sirenTrackMissileSiloSiren.get())
        simpleItem(ModItems.sirenTrackNostromoSelfDestruct.get())
        simpleItem(ModItems.sirenTrackRazortrainHorn.get())
        simpleItem(ModItems.sirenTrackSecurityAlert.get())
        simpleItem(ModItems.sirenTrackStandardSiren.get())
        simpleItem(ModItems.sirenTrackSweepSiren.get())
        simpleItem(ModItems.sirenTrackVaultDoorAlarm.get())

        getBuilder(ModItems.assemblyTemplate.id.path)
            .parent(generatedItem)
            .texture("layer0", itemTexture(ModItems.assemblyTemplate.get()))
            .override()
            .predicate(ntm("shift"), 1F)
            .model(UncheckedModelFile("builtin/entity"))
            .end()

        getBuilder(ModItems.chemTemplate.id.path)
            .parent(generatedItem)
            .texture("layer0", itemTexture(ModItems.chemTemplate.get()))
            .override()
            .predicate(ntm("shift"), 1F)
            .model(UncheckedModelFile("builtin/entity"))
            .end()

        simpleItem(ModItems.neutronShieldingLittleBoy.get())
        simpleItem(ModItems.subcriticalUraniumTarget.get())
        simpleItem(ModItems.uraniumProjectile.get())
        simpleItem(ModItems.propellantLittleBoy.get())
        simpleItem(ModItems.bombIgniterLittleBoy.get())
        simpleItem(ModItems.bundleOfImplosionPropellant.get())
        simpleItem(ModItems.bombIgniterFatMan.get())
        simpleItem(ModItems.plutoniumCore.get())
        simpleItem(ModItems.detonator.get())
        simpleItem(ModItems.designator.get())
        simpleItem(ModItems.heMissile.get())
        simpleItem(ModItems.incendiaryMissile.get())
        simpleItem(ModItems.clusterMissile.get())
        simpleItem(ModItems.bunkerBusterMissile.get())
        simpleItem(ModItems.strongMissile.get())
        simpleItem(ModItems.strongIncendiaryMissile.get())
        simpleItem(ModItems.strongClusterMissile.get())
        simpleItem(ModItems.strongBunkerBusterMissile.get())
        simpleItem(ModItems.burstMissile.get())
        simpleItem(ModItems.infernoMissile.get())
        simpleItem(ModItems.rainMissile.get())
        simpleItem(ModItems.drillMissile.get())
        simpleItem(ModItems.nuclearMissile.get())
        simpleItem(ModItems.oilDetector.get())
        simpleItem(ModItems.geigerCounter.get())
        simpleItem(ModItems.ivBag.get())
        simpleItem(ModItems.bloodBag.get())
        simpleItem(ModItems.emptyExperienceBag.get())
        simpleItem(ModItems.experienceBag.get())
        simpleItem(ModItems.radAway.get())
        simpleItem(ModItems.strongRadAway.get())
        simpleItem(ModItems.eliteRadAway.get())

        simpleItem(ModItems.hazmatHelmet.get())
        simpleItem(ModItems.hazmatChestplate.get())
        simpleItem(ModItems.hazmatLeggings.get())
        simpleItem(ModItems.hazmatBoots.get())
        simpleItem(ModItems.advancedHazmatHelmet.get())
        simpleItem(ModItems.advancedHazmatChestplate.get())
        simpleItem(ModItems.advancedHazmatLeggings.get())
        simpleItem(ModItems.advancedHazmatBoots.get())
        simpleItem(ModItems.reinforcedHazmatHelmet.get())
        simpleItem(ModItems.reinforcedHazmatChestplate.get())
        simpleItem(ModItems.reinforcedHazmatLeggings.get())
        simpleItem(ModItems.reinforcedHazmatBoots.get())
        simpleItem(ModItems.titaniumHelmet.get())
        simpleItem(ModItems.titaniumChestplate.get())
        simpleItem(ModItems.titaniumLeggings.get())
        simpleItem(ModItems.titaniumBoots.get())
        simpleItem(ModItems.steelHelmet.get())
        simpleItem(ModItems.steelChestplate.get())
        simpleItem(ModItems.steelLeggings.get())
        simpleItem(ModItems.steelBoots.get())
        simpleItem(ModItems.advancedAlloyHelmet.get())
        simpleItem(ModItems.advancedAlloyChestplate.get())
        simpleItem(ModItems.advancedAlloyLeggings.get())
        simpleItem(ModItems.advancedAlloyBoots.get())
        simpleItem(ModItems.combineSteelHelmet.get())
        simpleItem(ModItems.combineSteelChestplate.get())
        simpleItem(ModItems.combineSteelLeggings.get())
        simpleItem(ModItems.combineSteelBoots.get())
        simpleItem(ModItems.paAAlloyChestplate.get())
        simpleItem(ModItems.paAAlloyLeggings.get())
        simpleItem(ModItems.paAAlloyBoots.get())
        simpleItem(ModItems.schrabidiumHelmet.get())
        simpleItem(ModItems.schrabidiumChestplate.get())
        simpleItem(ModItems.schrabidiumLeggings.get())
        simpleItem(ModItems.schrabidiumBoots.get())

        getBuilder(ModItems.polaroid.id.path)
            .customLoader(::RandomModelBuilder)
            .idSupplier(ModItems.polaroid.id)
            .apply {
                for (i in 1..18) randomModel(nested().parent(generatedItem).texture("layer0", modLoc("$ITEM_FOLDER/polaroid_$i")))
            }.end()

        simpleItem(ModItems.creativeNuclearExplosionSpawner.get())

        bombKitItem = getBuilder("template_bomb_kit").parent(generatedItem)
            .texture("layer0", modLoc("$ITEM_FOLDER/bomb_kit"))
            .texture("layer1", modLoc("$ITEM_FOLDER/bomb_kit_overlay"))

        for (bombKit in BombKitItem.allKits) bombKit(bombKit)

        spawnEgg(ModItems.nuclearCreeperSpawnEgg.get())

        // BlockItems

        getBuilder(ModBlockItems.glowingMushroomBlock.id.path).parent(cubeAll).texture("all", blockTexture(ModBlocks.glowingMushroomBlock.get()))
        getBuilder(ModBlockItems.glowingMushroomStem.id.path).parent(cubeAll).texture("all", blockTexture(ModBlocks.glowingMushroomStem.get()))
        simpleItem(ModBlockItems.steamPress.get())
        simpleItem(ModBlockItems.assemblerPlacer.get())
        simpleItem(ModBlockItems.chemPlantPlacer.get())
        simpleItem(ModBlockItems.launchPadPlacer.get())

        // Buckets
        for ((source, _, bucket, _) in NTechFluids.getFluidsList()) bucket(source.get(), bucket.get())
    }

    private val cubeAll = getExistingFile(mcLoc("block/cube_all"))
    private val generatedItem = getExistingFile(mcLoc("item/generated"))
    private val spawnEggItem = getExistingFile(mcLoc("item/template_spawn_egg"))
    private lateinit var bombKitItem: ModelFile

    private fun simpleItem(item: Item) {
        getBuilder(item.registryName!!.path)
            .parent(generatedItem)
            .texture("layer0", itemTexture(item))
    }

    private fun bombKit(item: Item) {
        getBuilder(item.registryName!!.path).parent(bombKitItem)
    }

    private fun spawnEgg(item: Item) {
        getBuilder(item.registryName!!.path).parent(spawnEggItem)
    }

    private fun bucket(fluid: Fluid, bucket: BucketItem) {
        withExistingParent(bucket.registryName!!.path, ResourceLocation("forge", "item/bucket"))
            .customLoader { modelBuilder: ItemModelBuilder, existingFileHelper -> DynamicBucketModelBuilder.begin(modelBuilder, existingFileHelper) }
            .fluid(fluid)
            .end()
    }

    private fun blockTexture(block: Block) =
        ResourceLocation(block.registryName!!.namespace, "$BLOCK_FOLDER/${block.registryName!!.path}")

    private fun itemTexture(item: Item) =
        ResourceLocation(item.registryName!!.namespace, "$ITEM_FOLDER/${item.registryName!!.path}")
}
