package at.martinthedragon.nucleartech.datagen.localisation

import at.martinthedragon.nucleartech.LangKeys
import at.martinthedragon.nucleartech.Materials
import at.martinthedragon.nucleartech.SoundEvents
import at.martinthedragon.nucleartech.block.NTechBlocks
import at.martinthedragon.nucleartech.datagen.NuclearLanguageProviders
import at.martinthedragon.nucleartech.entity.EntityTypes
import at.martinthedragon.nucleartech.entity.attribute.Attributes
import at.martinthedragon.nucleartech.fluid.NTechFluids
import at.martinthedragon.nucleartech.item.NTechItems
import at.martinthedragon.nucleartech.menu.MenuTypes
import at.martinthedragon.nucleartech.world.DamageSources
import net.minecraft.data.DataGenerator

class DeDeLanguageProvider(dataGenerator: DataGenerator) : NuclearLanguageProvider(dataGenerator, NuclearLanguageProviders.DE_DE) {
    override fun translate() {
        add("itemGroup.${MODID}_parts", "NTM Ressourcen und Bauteile")
        add("itemGroup.${MODID}_items", "NTM Maschinenitems")
        add("itemGroup.${MODID}_templates", "NTM Fertigungsvorlagen")
        add("itemGroup.${MODID}_blocks", "NTM Erze und Blöcke")
        add("itemGroup.${MODID}_machines", "NTM Maschinen")
        add("itemGroup.${MODID}_bombs", "NTM Bomben")
        add("itemGroup.${MODID}_rocketry", "NTM Raketen und Satelliten")
        add("itemGroup.${MODID}_consumables", "NTM Verbrauchsgüter")
        add("itemGroup.${MODID}_miscellaneous", "NTM Verschiedenes")

        addMaterials()

        addBlock(NTechBlocks.scorchedUraniumOre, "Verschmortes Uranerz")
        addBlock(NTechBlocks.thoriumOre, "Thoriumerz")
        addBlock(NTechBlocks.oilDeposit, "Ölvorkommen")
        addBlockDesc(NTechBlocks.oilDeposit, "Du hättest das nicht abbauen sollen.\nNa los, hol dir einen Bohrturm, du Idiot.")
        addBlock(NTechBlocks.emptyOilDeposit, "Leeres Ölvorkommen")
        addBlock(NTechBlocks.oilSand, "Ölsand")
        addBlock(NTechBlocks.australianOre, "Australisches Erz")
        addBlockDesc(NTechBlocks.australianOre, "Australiumerz")
        addBlock(NTechBlocks.weidite, "Weidit")
        addBlockDesc(NTechBlocks.weidite, "Weidaniumerz")
        addBlock(NTechBlocks.reiite, "Reiit")
        addBlockDesc(NTechBlocks.reiite, "Reiiumerz")
        addBlock(NTechBlocks.brightblendeOre, "Glimmerblende")
        addBlockDesc(NTechBlocks.brightblendeOre, "Unobtainiumerz")
        addBlock(NTechBlocks.dellite, "Dellit")
        addBlockDesc(NTechBlocks.dellite, "Daffergonerz")
        addBlock(NTechBlocks.dollarGreenMineral, "Dollargrünes Mineral")
        addBlockDesc(NTechBlocks.dollarGreenMineral, "Verticiumerz")
        addBlock(NTechBlocks.rareEarthOre, "Seltene-Erden-Erz")
        addBlock(NTechBlocks.netherUraniumOre, "Netheruranerz")
        addBlock(NTechBlocks.scorchedNetherUraniumOre, "Verschmortes Netheruranerz")
        addBlock(NTechBlocks.netherPlutoniumOre, "Netherplutoniumerz")
        addBlock(NTechBlocks.netherTungstenOre, "Netherwolframerz")
        addBlock(NTechBlocks.netherSulfurOre, "Netherschwefelerz")
        addBlock(NTechBlocks.netherPhosphorusOre, "Netherphosphorerz")
        addBlock(NTechBlocks.netherSchrabidiumOre, "Netherschrabidiumerz")
        addBlock(NTechBlocks.meteorUraniumOre, "Meteoritenuranerz")
        addBlock(NTechBlocks.meteorThoriumOre, "Meteoritenthoriumerz")
        addBlock(NTechBlocks.meteorTitaniumOre, "Meteoritentitanerz")
        addBlock(NTechBlocks.meteorSulfurOre, "Meteoritenschwefelerz")
        addBlock(NTechBlocks.meteorCopperOre, "Meteoritenkupfererz")
        addBlock(NTechBlocks.meteorTungstenOre, "Meteoritenwolframerz")
        addBlock(NTechBlocks.meteorAluminiumOre, "Meteoritenaluminiumerz")
        addBlock(NTechBlocks.meteorLeadOre, "Meteoritenbleierz")
        addBlock(NTechBlocks.meteorLithiumOre, "Meteoritenlithiumerz")
        addBlock(NTechBlocks.trixite, "Trixit")

        addBlock(NTechBlocks.scorchedDeepslateUraniumOre, "Verschmortes Tiefenschiefer-Uranerz")
        addBlock(NTechBlocks.deepslateOilDeposit, "Tiefenschiefer-Ölvorkommen")
        addBlockDesc(NTechBlocks.deepslateOilDeposit, "Du bist so tief gekommen und weißt\nimmer noch nicht, was zu tun ist? Wie?!")
        addBlock(NTechBlocks.emptyDeepslateOilDeposit, "Leeres Tiefenschiefer-Ölvorkommen")
        addBlock(NTechBlocks.deepslateAustralianOre, "Australisches Tiefenschiefer-Erz")
        addBlockDesc(NTechBlocks.deepslateAustralianOre, "Australiumerz")
        addBlock(NTechBlocks.deepslateRareEarthOre, "Seltene-Erden-Tiefenschiefer-Erz")

        addBlock(NTechBlocks.u233Block, "U233-Block")
        addBlock(NTechBlocks.u235Block, "U235-Block")
        addBlock(NTechBlocks.u238Block, "U238-Block")
        addBlock(NTechBlocks.pu238Block, "Pu238-Block")
        addBlock(NTechBlocks.pu239Block, "Pu239-Block")
        addBlock(NTechBlocks.pu240Block, "Pu240-Block")
        addBlock(NTechBlocks.redCopperBlock, "Roter Kupferblock")
        addBlock(NTechBlocks.advancedAlloyBlock, "Fortgeschrittener Legierungsblock")
        addBlock(NTechBlocks.scrapBlock, "Schrottblock")
        addBlock(NTechBlocks.electricalScrapBlock, "Elektroschrottblock")
        addBlock(NTechBlocks.insulatorRoll, "Isolatorrolle")
        addBlock(NTechBlocks.fiberglassRoll, "Fiberglasrolle")
        addBlock(NTechBlocks.schrabidiumCluster, "Schrabidium-Cluster")
        addBlock(NTechBlocks.euphemiumEtchedSchrabidiumCluster, "Euphemiumgeätzter Schrabidium-Cluster")
        addBlock(NTechBlocks.magnetizedTungstenBlock, "Magnetisierter Wolframblock")
        addBlock(NTechBlocks.deshReinforcedBlock, "Verstärkter Deshblock")

        addBlock(NTechBlocks.titaniumDecoBlock, "Titan-Dekoblock")
        addBlock(NTechBlocks.redCopperDecoBlock, "Roter Kupfer-Dekoblock")
        addBlock(NTechBlocks.tungstenDecoBlock, "Wolfram-Dekoblock")
        addBlock(NTechBlocks.aluminiumDecoBlock, "Aluminium-Dekoblock")
        addBlock(NTechBlocks.steelDecoBlock, "Stahl-Dekoblock")
        addBlock(NTechBlocks.leadDecoBlock, "Blei-Dekoblock")
        addBlock(NTechBlocks.berylliumDecoBlock, "Beryllium-Dekoblock")
        addBlock(NTechBlocks.asbestosRoof, "Asbestdach")
        addBlock(NTechBlocks.hazmatBlock, "Strahlenschutzstoff-Block")
        addBlock(NTechBlocks.steelBeam, "Stahlträger")

        addBlock(NTechBlocks.glowingMushroom, "Leuchtender Pilz")
        addBlock(NTechBlocks.glowingMushroomBlock, "Leuchtender Pilzblock")
        addBlock(NTechBlocks.glowingMushroomStem, "Leuchtender Pilzstamm")
        addBlock(NTechBlocks.deadGrass, "Totes Gras")
        addBlock(NTechBlocks.glowingMycelium, "Leuchtendes Myzel")
        addBlock(NTechBlocks.redTrinitite, "Rotes Trinititerz")
        addBlock(NTechBlocks.charredLog, "Verkohltes Holz")
        addBlock(NTechBlocks.charredPlanks, "Verkohlte Holzbretter")

        addBlock(NTechBlocks.slakedSellafite, "Gelöschtes Sellafit")
        addBlock(NTechBlocks.sellafite, "Sellafit")
        addBlock(NTechBlocks.hotSellafite, "Heißes Sellafit")
        addBlock(NTechBlocks.boilingSellafite, "Kochendes Sellafit")
        addBlock(NTechBlocks.blazingSellafite, "Flammendes Sellafit")
        addBlock(NTechBlocks.infernalSellafite, "Infernales Sellafit")
        addBlock(NTechBlocks.sellafiteCorium, "Sellafit-Corium")

        addBlock(NTechBlocks.siren, "Sirene")
        addBlock(NTechBlocks.steamPressBase, "Dampfpresse")
        addBlock(NTechBlocks.steamPressFrame, "Dampfpresse")
        addBlock(NTechBlocks.steamPressTop, "Dampfpresse")
        addBlock(NTechBlocks.blastFurnace, "Hochofen")
        addBlock(NTechBlocks.combustionGenerator, "Verbrennungsgenerator")
        addBlock(NTechBlocks.electricFurnace, "Elektrischer Ofen")
        addBlock(NTechBlocks.shredder, "Brecher")
        addBlock(NTechBlocks.assembler, "Fertigungsmaschine")
        addBlock(NTechBlocks.chemPlant, "Chemiewerk")
        addBlock(NTechBlocks.safe, "Panzerschrank")
        addBlock(NTechBlocks.ironAnvil, "Eisenamboss")
        addBlock(NTechBlocks.leadAnvil, "Bleiamboss")
        addBlock(NTechBlocks.steelAnvil, "Stahlamboss")
        addBlock(NTechBlocks.meteoriteAnvil, "Meteoritenamboss")
        addBlock(NTechBlocks.starmetalAnvil, "Starmetalamboss")
        addBlock(NTechBlocks.ferrouraniumAnvil, "Ferrouranamboss")
        addBlock(NTechBlocks.bismuthAnvil, "Bismutamboss")
        addBlock(NTechBlocks.schrabidateAnvil, "Eisenschrabidatamboss")
        addBlock(NTechBlocks.dineutroniumAnvil, "Dineutroniumamboss")
        addBlock(NTechBlocks.murkyAnvil, "Düsteramboss")
        addBlock(NTechBlocks.coatedCable, "Geschirmtes Rotes Kupferkabel")

        addBlock(NTechBlocks.littleBoy, "Little Boy")
        addBlock(NTechBlocks.fatMan, "Fat Man")

        addBlock(NTechBlocks.launchPad, "Raketenabschussrampe")
        addBlock(NTechBlocks.launchPadPart, "Raketenabschussrampe")

        addBlock(NTechBlocks.genericMultiBlockPart, "Multi-Block-Struktur Teil")
        addBlock(NTechBlocks.genericMultiBlockPort, "Multi-Block-Struktur Anschluss")

        addBlock(NTechFluids.uraniumHexafluoride.block, "Uranhexafluorid")

        addItem(NTechItems.rawThorium, "Rohes Thorium")
        addItem(NTechItems.rawRareEarth, "Rohe Seltene Erde")
        addItem(NTechItems.rawTrixite, "Rohes Trixit")

        addItem(NTechItems.u233Ingot, "Uran-233-Barren")
        addItem(NTechItems.u235Ingot, "Uran-235-Barren")
        addItem(NTechItems.u238Ingot, "Uran-238-Barren")
        addItem(NTechItems.th232Ingot, "Thorium-232-Barren")
        addItem(NTechItems.pu238Ingot, "Plutonium-238-Barren")
        addItem(NTechItems.pu239Ingot, "Plutonium-239-Barren")
        addItem(NTechItems.pu240Ingot, "Plutonium-240-Barren")
        addItem(NTechItems.pu241Ingot, "Plutonium-241-Barren")
        addItem(NTechItems.reactorGradePlutoniumIngot, "Reaktorfähiger Plutoniumbarren")
        addItem(NTechItems.americium241Ingot, "Americium-241-Barren")
        addItem(NTechItems.americium242Ingot, "Americium-242-Barren")
        addItem(NTechItems.reactorGradeAmericiumIngot, "Reaktorfähiger Americiumbarren")
        addItem(NTechItems.technetium99Ingot, "Technetium-99-Barren")
        addItem(NTechItems.cobalt60Ingot, "Kobalt-60-Barren")
        addItem(NTechItems.strontium90Ingot, "Strontium-90-Barren")
        addItem(NTechItems.gold198Ingot, "Gold-198-Barren")
        addItem(NTechItems.lead209Ingot, "Blei-209-Barren")
        addItem(NTechItems.radium226Ingot, "Radium-226-Barren")
        addItemDesc(NTechItems.neptuniumIngot, "Diesen hier mag ich am allerliebsten!")
        addItem(NTechItems.redCopperIngot, "Roter Kupferbarren")
        addItem(NTechItems.advancedAlloyIngot, "Fortgeschrittene Legierung")
        addItemDesc(NTechItems.tantaliumIngot, "'Tantalum'")
        addItemDesc(NTechItems.tantaliumNugget, "'Tantalum'")
        addItemDesc(NTechItems.schraraniumIngot, "Hergestellt aus Uran in einem Schrabidium-Transmutator")
        addItem(NTechItems.magnetizedTungstenIngot, "Magnetisierter Wolframbarren")
        addItemDesc(NTechItems.combineSteelIngot, "*Civil-Protection-Referenz hier einfügen*")
        addItem(NTechItems.ghiorsium336Ingot, "Ghiorsium-336-Barren")
        addItemDesc(NTechItems.ghiorsium336Ingot, "Seaborgiums Kollege.")
        addItem(NTechItems.highEnrichedSchrabidiumFuelIngot, "Stark Angereicherter Schrabidiumkernbrennstoffbarren")
        addItem(NTechItems.lowEnrichedSchrabidiumFuelIngot, "Schwach Angereicherter Schrabidiumkernbrennstoffbarren")
        addItem(NTechItems.lanthanumIngot, "Semistabiler Lanthanbarren")
        addItem(NTechItems.actiniumIngot, "Actinium-227-Barren")
        addItemDesc(NTechItems.euphemiumIngot, "Ein sehr spezielles und doch seltsames Element")
        addItem(NTechItems.whitePhosphorusIngot, "Weiße Phosphortafel")

        addItem(NTechItems.semtexBar, "Semtextafel")
        addItemDesc(
            NTechItems.semtexBar,
            "Semtex H Plastiksprengstoff\n" +
                    "Performanter Sprengstoff für viele Zwecke.\n" +
                    "Essbar"
        )

        addItem(NTechItems.lithiumCube, "Lithiumwürfel")
        addItem(NTechItems.solidFuelCube, "Festbrennstoffwürfel")
        addItem(NTechItems.solidRocketFuelCube, "Festraketentreibstoffwürfel")

        addItem(NTechItems.fiberglassSheet, "Fiberglasbogen")
        addItemDesc(NTechItems.fiberglassSheet, "Reich an \"Ballaststoffen\", reich an Glas. Alles was der Körper braucht.")
        addItem(NTechItems.asbestosSheet, "Asbestbogen")
        addItemDesc(NTechItems.asbestosSheet, "§o\"Gefüllt mit Leben, Selbstzweifel und Asbest. Das kommt mit der Luft.\"")

        addItem(NTechItems.mercuryDroplet, "Quecksilbertröpfchen")
        addItem(NTechItems.mercuryBottle, "Quecksilberflasche")

        addItem(NTechItems.coke, "Koks")
        addItem(NTechItems.lignite, "Braunkohle")
        addItem(NTechItems.ligniteBriquette, "Braunkohlebrikett")

        addItem(NTechItems.sulfur, "Schwefel")
        addItem(NTechItems.niter, "Salpeter")
        addItem(NTechItems.fluorite, "Fluorit")
        addItem(NTechItems.quartzPowder, "Quarzpulver")
        addItem(NTechItems.advancedAlloyPowder, "Fortgeschrittenes Legierungspulver")
        addItem(NTechItems.yellowcake, "Yellowcake")
        addItem(NTechItems.chlorophytePowder, "Grünalgenpulver")
        addItem(NTechItems.neodymiumPowder, "Neodympulver")
        addItem(NTechItems.ceriumPowder, "Cerpulver")
        addItem(NTechItems.actiniumPowder, "Actinium-227-Pulver")
        addItemDesc(NTechItems.asbestosPowder, "§o\"Schnauffffffff - MHHHHHHMHHHHHHHHH\"")
        addItem(NTechItems.enchantmentPowder, "Pulverisierte Verzauberung")
        addItem(NTechItems.cloudResidue, "Wolkenrückstände")
        addItem(NTechItems.thermonuclearAshes, "Thermonukleare Asche")
        addItem(NTechItems.semtexMix, "Semtexmischung")
        addItem(NTechItems.deshMix, "Desh-Mischung")
        addItem(NTechItems.deshReadyMix, "DeshReady™-Mischung")
        addItem(NTechItems.nitaniumMix, "Nitanium-Mischung")
        addItem(NTechItems.sparkMix, "Spark-Mischung")
        addItem(NTechItems.meteoritePowder, "Meteoritenpulver")
        addItemDesc(NTechItems.euphemiumPowder, "Pulverisiertes pink.\nSchmeckt nach Erdbeeren.")
        addItem(NTechItems.desaturatedRedstone, "Entsättigter Redstone-Staub")
        addItem(NTechItems.dust, "Staub")
        addItemDesc(NTechItems.dust, "I hasse Staub!")
        addItem(NTechItems.tinyLithiumPowder, "Kleiner Haufen Lithiumpulver")
        addItem(NTechItems.tinyNeodymiumPowder, "Kleiner Haufen Neodympulver")
        addItem(NTechItems.tinyCobaltPowder, "Kleiner Haufen Kobaltpulver")
        addItem(NTechItems.tinyNiobiumPowder, "Kleiner Haufen Niobpulver")
        addItem(NTechItems.tinyCeriumPowder, "Kleiner Haufen Cerpulver")
        addItem(NTechItems.tinyLanthanumPowder, "Kleiner Haufen Lanthanpulver")
        addItem(NTechItems.tinyActiniumPowder, "Kleiner Haufen Actiniumpulver")
        addItem(NTechItems.tinyMeteoritePowder, "Kleiner Haufen Meteoritenpulver")
        addItem(NTechItems.redPhosphorus, "Roter Phosphor")
        addItemDesc(NTechItems.redPhosphorus, "Wird in Mehrzweckbomben verwendet:\nBrandbomben machen Spaß!")
        addItem(NTechItems.cryoPowder, "Kryopulver")
        addItem(NTechItems.poisonPowder, "Giftpulver")
        addItemDesc(NTechItems.poisonPowder, "Wird in Mehrzweckbomben verwendet:\nAchtung: Giftig!")
        addItem(NTechItems.thermite, "Thermit")
        addItem(NTechItems.energyPowder, "Energiepulver")

        addItem(NTechItems.cordite, "Cordit")
        addItem(NTechItems.ballistite, "Ballistit")

        addItem(NTechItems.thoriumCrystals, "Thorium-232-Kristalle")
        addItem(NTechItems.rareEarthCrystals, "Seltene-Erden-Kristalle")
        addItem(NTechItems.redPhosphorusCrystals, "Rote Phosphorkristalle")
        addItem(NTechItems.trixiteCrystals, "Trixitkristalle")

        addItem(NTechItems.neodymiumFragment, "Neodymiumfragment")
        addItem(NTechItems.cobaltFragment, "Kobaltfragment")
        addItem(NTechItems.niobiumFragment, "Niobfragment")
        addItem(NTechItems.ceriumFragment, "Cerfragment")
        addItem(NTechItems.lanthanumFragment, "Lanthanfragment")
        addItem(NTechItems.actiniumFragment, "Actiniumfragment")
        addItem(NTechItems.meteoriteFragment, "Meteoritenfragment")

        addItem(NTechItems.biomass, "Biomasse")
        addItem(NTechItems.compressedBiomass, "Verdichtete Biomasse")

        addItem(NTechItems.u233Nugget, "Uran-233-Klumpen")
        addItem(NTechItems.u235Nugget, "Uran-235-Klumpen")
        addItem(NTechItems.u238Nugget, "Uran-238-Klumpen")
        addItem(NTechItems.th232Nugget, "Thorium-232-Klumpen")
        addItem(NTechItems.pu238Nugget, "Plutonium-238-Klumpen")
        addItem(NTechItems.pu239Nugget, "Plutonium-239-Klumpen")
        addItem(NTechItems.pu240Nugget, "Plutonium-240-Klumpen")
        addItem(NTechItems.pu241Nugget, "Plutonium-241-Klumpen")
        addItem(NTechItems.reactorGradePlutoniumNugget, "Reaktorfähiger Plutoniumklumpen")
        addItem(NTechItems.americium241Nugget, "Americium-241-Klumpen")
        addItem(NTechItems.americium242Nugget, "Americium-242-Klumpen")
        addItem(NTechItems.reactorGradeAmericiumNugget, "Reaktorfähiger Americiumklumpen")
        addItem(NTechItems.cobalt60Nugget, "Kobalt-60-Klumpen")
        addItem(NTechItems.strontium90Nugget, "Strontium-90-Klumpen")
        addItem(NTechItems.technetium99Nugget, "Technetium-99-Klumpen")
        addItem(NTechItems.gold198Nugget, "Gold-198-Klumpen")
        addItem(NTechItems.lead209Nugget, "Blei-209-Klumpen")
        addItem(NTechItems.radium226Nugget, "Radium-226-Klumpen")
        addItem(NTechItems.actinium227Nugget, "Actinium-227-Klumpen")
        addItem(NTechItems.ghiorsium336Nugget, "Ghiorsium-336-Klumpen")
        addItemDesc(NTechItems.ghiorsium336Nugget, "Seaborgiums Kollege.")
        addItem(NTechItems.highEnrichedSchrabidiumFuelNugget, "Stark Angereicherter Schrabidiumkernbrennstoffklumpen")
        addItem(NTechItems.lowEnrichedSchrabidiumFuelNugget, "Schwach Angereicherter Schrabidiumkernbrennstoffklumpen")
        addItemDesc(
            NTechItems.euphemiumNugget,
            "Ein kleines Stück von einem pinken Metall.\n" +
                    "Seine Eigenschaften sind immer noch unbekannt.\n" +
                    "Gehe vorsichtig damit um."
        )

        addItem(NTechItems.advancedAlloyPlate, "Fortgeschrittene Legierungsplatte")
        addItem(NTechItems.neutronReflector, "Neutronenreflektor")
        addItem(NTechItems.mixedPlate, "Gemischte Platte")
        addItem(NTechItems.paAAlloyPlate, "PaA-Legierungsplatte")
        addItem(NTechItems.insulator, "Isolator")
        addItem(NTechItems.kevlarCeramicCompound, "Kevlar-Keramik-Verbund")
        addItem(NTechItems.dalekaniumPlate, "Wütendes Metall")
        addItem(NTechItems.deshCompoundPlate, "Deshverbundplatte")
        addItem(NTechItems.euphemiumCompoundPlate, "Euphemiumverbundplatte")
        addItem(NTechItems.dineutroniumCompoundPlate, "Dineutroniumverbundplatte")
        addItem(NTechItems.copperPanel, "Kupfertafel")

        addItem(NTechItems.highSpeedSteelBolt, "Schnellarbeitsstahlbolzen")
        addItem(NTechItems.tungstenBolt, "Wolframbolzen")
        addItem(NTechItems.reinforcedTurbineShaft, "Verstärkte Turbinenwelle")

        addItem(NTechItems.hazmatCloth, "Strahlenschutzanzugsstoff")
        addItem(NTechItems.advancedHazmatCloth, "Verbesserter Strahlenschutzanzugsstoff")
        addItem(NTechItems.leadReinforcedHazmatCloth, "Bleiverstärkter Strahlenschutzanzugsstoff")
        addItem(NTechItems.fireProximityCloth, "Hitzeschutzanzugsstoff")
        addItem(NTechItems.activatedCarbonFilter, "Aktivkohlefilter")

        addItem(NTechItems.redCopperWire, "Roter Kupferdraht")
        addItem(NTechItems.superConductor, "Supraleiter")
        addItem(NTechItems.highTemperatureSuperConductor, "4000K Hochtemperaturensupraleiter")

        addItem(NTechItems.copperCoil, "Kupferspule")
        addItem(NTechItems.ringCoil, "Ringspule")
        addItem(NTechItems.superConductingCoil, "Supraleitende Magnetspule")
        addItem(NTechItems.superConductingRingCoil, "Supraleitende Ringspule")
        addItem(NTechItems.goldCoil, "Goldspule")
        addItem(NTechItems.goldRingCoil, "Gold Ringspule")
        addItem(NTechItems.heatingCoil, "Heizspirale")
        addItem(NTechItems.highTemperatureSuperConductingCoil, "4000K Hochtemperaturensupraleitermagnetspule")

        addItem(NTechItems.steelTank, "Stahltank")
        addItem(NTechItems.motor, "Motor")
        addItem(NTechItems.centrifugeElement, "Zentrifugenelement")
        addItem(NTechItems.centrifugeTower, "Zentrifugenturm")
        addItem(NTechItems.deeMagnets, "Duantenmagneten")
        addItem(NTechItems.flatMagnet, "Flachmagnet")
        addItem(NTechItems.cyclotronTower, "Zyklotronenturm")
        addItem(NTechItems.breedingReactorCore, "Brutreaktorkern")
        addItem(NTechItems.rtgUnit, "RTG-Einheit")
        addItem(NTechItems.thermalDistributionUnit, "Thermische Verteilungseinheit")
        addItem(NTechItems.endothermicDistributionUnit, "Hitzeabsorptionseinheit")
        addItem(NTechItems.exothermicDistributionUnit, "Hitzeverteilungseinheit")
        addItem(NTechItems.gravityManipulator, "Gravitationsmanipulator")
        addItem(NTechItems.steelPipes, "Stahlrohre")
        addItem(NTechItems.titaniumDrill, "Titanbohrer")
        addItem(NTechItems.photovoltaicPanel, "Photovoltaikpanele")
        addItem(NTechItems.chlorinePinwheel, "Chlorgaskonverter")
        addItem(NTechItems.telepad, "Teleplatte")
        addItem(NTechItems.entanglementKit, "Verschränkungskit")
        addItemDesc(
            NTechItems.entanglementKit,
            "Teleporter Crafting-Gegenstand.\n" +
                    "Ermöglicht Dimensionsverschiebung über einen\n" +
                    "berylliumverstärkten Ressourcenscanner."
        )
        addItem(NTechItems.stabilizerComponent, "Stabilisatorkomponente")
        addItem(NTechItems.emitterComponent, "Emitterkomponente")
        addItem(NTechItems.aluminiumCap, "Aluminiumdeckel")
        addItem(NTechItems.smallSteelShell, "Kleine Stahlhülle")
        addItem(NTechItems.smallAluminiumShell, "Kleine Aluminiumhülle")
        addItem(NTechItems.bigSteelShell, "Große Stahlhülle")
        addItem(NTechItems.bigAluminiumShell, "Große Aluminiumhülle")
        addItem(NTechItems.bigTitaniumShell, "Große Titanhülle")
        addItem(NTechItems.flatSteelCasing, "Flache Stahlabdeckung")
        addItem(NTechItems.smallSteelGridFins, "Kleine Stahlgitterfinnen")
        addItem(NTechItems.bigSteelGridFins, "Große Stahlgitterfinnen")
        addItem(NTechItems.largeSteelFins, "Große Stahlflossen")
        addItem(NTechItems.smallTitaniumFins, "Kleine Titanflossen")
        addItem(NTechItems.steelSphere, "Stahlhohlkugel")
        addItem(NTechItems.steelPedestal, "Stahlsockel")
        addItem(NTechItems.dysfunctionalNuclearReactor, "Funktionsunfähiger Atomreaktor")
        addItem(NTechItems.largeSteelRotor, "Großer Stahlrotor")
        addItem(NTechItems.generatorBody, "Generatorhauptteil")
        addItem(NTechItems.titaniumBlade, "Titanturbinenschaufel")
        addItem(NTechItems.tungstenReinforcedBlade, "Wolframverstärktes Turbinenblatt")
        addItem(NTechItems.titaniumSteamTurbine, "Titandampfturbine")
        addItem(NTechItems.reinforcedTurbofanBlades, "Verstärkte Turbofanblätter")
        addItem(NTechItems.generatorFront, "Generatorfront")
        addItem(NTechItems.toothpicks, "Zahnstocher")
        addItem(NTechItems.ductTape, "Klebeband")
        addItem(NTechItems.clayCatalyst, "Tonerdekatalysator")
        addItem(NTechItems.smallMissileAssembly, "Kleines Raketenbauset")

        addItem(NTechItems.smallWarhead, "Kleiner Sprengkopf")
        addItem(NTechItems.mediumWarhead, "Mittlerer Sprengkopf")
        addItem(NTechItems.largeWarhead, "Großer Sprengkopf")
        addItem(NTechItems.smallIncendiaryWarhead, "Kleiner Brandsprengkopf")
        addItem(NTechItems.mediumIncendiaryWarhead, "Mittlerer Brandsprengkopf")
        addItem(NTechItems.largeIncendiaryWarhead, "Großer Brandsprengkopf")
        addItem(NTechItems.smallClusterWarhead, "Kleiner Kasettensprengkopf")
        addItem(NTechItems.mediumClusterWarhead, "Mittlerer Kasettensprengkopf")
        addItem(NTechItems.largeClusterWarhead, "Großer Kasettensprengkopf")
        addItem(NTechItems.smallBunkerBusterWarhead, "Kleiner Bunkerbrechender Sprengkopf")
        addItem(NTechItems.mediumBunkerBusterWarhead, "Mittlerer Bunkerbrechender Sprengkopf")
        addItem(NTechItems.largeBunkerBusterWarhead, "Großer Bunkerbrechender Sprengkopf")
        addItem(NTechItems.nuclearWarhead, "Nuklearer Sprengkopf")
        addItem(NTechItems.thermonuclearWarhead, "Thermonuklearer Sprengkopf")
        addItem(NTechItems.endothermicWarhead, "Endothermischer Sprengkopf")
        addItem(NTechItems.exothermicWarhead, "Exothermischer Sprengkopf")

        addItem(NTechItems.smallFuelTank, "Kleiner Treibstofftank")
        addItem(NTechItems.mediumFuelTank, "Mittlerer Treibstofftank")
        addItem(NTechItems.largeFuelTank, "Großer Treibstofftank")

        addItem(NTechItems.smallThruster, "Kleines Raketentriebwerk")
        addItem(NTechItems.mediumThruster, "Mittleres Raketentriebwerk")
        addItem(NTechItems.largeThruster, "Großes Raketentriebwerk")
        addItem(NTechItems.lvnNuclearRocketEngine, "LV-N Atomares Raketentriebwerk")

        addItem(NTechItems.satelliteBase, "Satellitenkörper")
        addItem(NTechItems.highGainOpticalCamera, "Hochleistungskamera")
        addItem(NTechItems.m700SurveyScanner, "M700 Oberflächenscanner")
        addItem(NTechItems.radarDish, "Radarschüssel")
        addItem(NTechItems.deathRay, "Todesstrahl")
        addItem(NTechItems.xeniumResonator, "Xeniumresonator")

        addItem(NTechItems.size10Connector, "Größe 10 Bindeglied")
        addItem(NTechItems.size15Connector, "Größe 15 Bindeglied")
        addItem(NTechItems.size20Connector, "Größe 20 Bindeglied")

        addItem(NTechItems.hunterChopperCockpit, "Jagdschrauber Cockpit")
        addItem(NTechItems.emplacementGun, "Pulskanone")
        addItem(NTechItems.hunterChopperBody, "Jagdschrauber Rumpf")
        addItem(NTechItems.hunterChopperTail, "Jagdschrauber Heck")
        addItem(NTechItems.hunterChopperWing, "Jagdschrauber Seitentragfläche")
        addItem(NTechItems.hunterChopperRotorBlades, "Jagdschrauber Rotorblätter")
        addItem(NTechItems.combineScrapMetal, "Combine Stahlschrott")

        addItem(NTechItems.heavyHammerHead, "Schwerer Hammerkopf")
        addItem(NTechItems.heavyAxeHead, "Schwerer Axtkopf")
        addItem(NTechItems.reinforcedPolymerHandle, "Verstärkter Polymergriff")

        addItem(NTechItems.basicCircuitAssembly, "Schaltkreisrohling")
        addItem(NTechItems.basicCircuit, "Einfacher Schaltkreis")
        addItem(NTechItems.enhancedCircuit, "Erweiterter Schaltkreis")
        addItem(NTechItems.advancedCircuit, "Fortgeschrittener Schaltkreis")
        addItem(NTechItems.overclockedCircuit, "Übertakteter Schaltkreis")
        addItem(NTechItems.highPerformanceCircuit, "Leistungsstarker Schaltkreis")
        addItem(NTechItems.militaryGradeCircuitBoardTier1, "Militärische Schaltplatte (Stufe 1)")
        addItem(NTechItems.militaryGradeCircuitBoardTier2, "Militärische Schaltplatte (Stufe 2)")
        addItem(NTechItems.militaryGradeCircuitBoardTier3, "Militärische Schaltplatte (Stufe 3)")
        addItem(NTechItems.militaryGradeCircuitBoardTier4, "Militärische Schaltplatte (Stufe 4)")
        addItem(NTechItems.militaryGradeCircuitBoardTier5, "Militärische Schaltplatte (Stufe 5)")
        addItem(NTechItems.militaryGradeCircuitBoardTier6, "Militärische Schaltplatte (Stufe 6)")

        addItem(NTechItems.revolverMechanism, "Revolvermechanismus")
        addItem(NTechItems.advancedRevolverMechanism, "Fortgeschrittener Revolvermechanismus")
        addItem(NTechItems.rifleMechanism, "Gewehrmechanismus")
        addItem(NTechItems.advancedRifleMechanism, "Fortgeschrittener Gewehrmechanismus")
        addItem(NTechItems.launcherMechanism, "Werfermechanismus")
        addItem(NTechItems.advancedLauncherMechanism, "Fortgeschrittener Werfermechanismus")
        addItem(NTechItems.highTechWeaponMechanism, "High-Tech Waffenmechanismus")

        addItem(NTechItems.point357MagnumPrimer, ".357 Magnumzündhütchen (x16)")
        addItem(NTechItems.point44MagnumPrimer, ".44 Magnumzündhütchen (x16)")
        addItem(NTechItems.smallCaliberPrimer, "Kleinkaliberzündhütchen (x24)")
        addItem(NTechItems.largeCaliberPrimer, "Großkaliberzündhütchen (x8)")
        addItem(NTechItems.buckshotPrimer, "Schrotzündhütchen (x8)")

        addItem(NTechItems.point357MagnumCasing, ".357 Magnumhülse (x16)")
        addItem(NTechItems.point44MagnumCasing, ".44 Magnumhülse (x16)")
        addItem(NTechItems.smallCaliberCasing, "Kleinkaliberhülse (x24)")
        addItem(NTechItems.largeCaliberCasing, "Großkaliberhülse (x8)")
        addItem(NTechItems.buckshotCasing, "Schrothülse (x8)")

        addItem(NTechItems.ironBulletAssembly, "Eisenpatronensatz")
        addItem(NTechItems.leadBulletAssembly, "Bleipatronensatz")
        addItem(NTechItems.glassBulletAssembly, "Glaspatronensatz")
        addItem(NTechItems.goldBulletAssembly, "Goldpatronensatz")
        addItem(NTechItems.schrabidiumBulletAssembly, "Schrabidiumpatronensatz")
        addItem(NTechItems.nightmareBulletAssembly, "Nightmare-Patronensatz")
        addItem(NTechItems.deshBulletAssembly, "Deshpatronensatz")
        addItem(NTechItems.point44MagnumAssembly, ".44er Patronensatz")
        addItem(NTechItems.nineMmAssembly, "9mm Patronensatz")
        addItem(NTechItems.fivePoint56mmAssembly, "5.56mm Patronensatz")
        addItem(NTechItems.point22LRAssembly, ".22 LR Patronensatz")
        addItem(NTechItems.point5mmAssembly, ".5mm Patronensatz")
        addItem(NTechItems.point50AEAssembly, ".50 AE Patronensatz")
        addItem(NTechItems.point50BMGAssembly, ".50 BMG Patronensatz")

        addItem(NTechItems.silverBulletCasing, "Kanonenhülse")
        addItem(NTechItems.twelvePoint8cmStarmetalHighEnergyShell, "12,8cm Starmetal-Hochenergiegeschoss")
        addItem(NTechItems.twelvePoint8cmNuclearShell, "12,8cm Atomares Geschoss")
        addItem(NTechItems.twelvePoint8cmDUShell, "12.8cm DU-Geschoss")

        addItem(NTechItems.cableDrum, "Kabeltrommel")
        addItemDesc(NTechItems.cableDrum, "Rechtsklicke Masten um sie zu verbinden")
        addItem(NTechItems.paintingOfACartoonPony, "Bild eines Cartoon Ponys")
        addItemDesc(NTechItems.paintingOfACartoonPony, "Gelbes Pferd schlägt blaues Pferd, das ist eine erwiesene Tatsache!")
        addItem(NTechItems.conspiracyTheory, "Verschwörungstheorie")
        addItemDesc(NTechItems.conspiracyTheory, "Stahlträger können nicht Kerosin schmelzen!")
        addItem(NTechItems.politicalTopic, "Politisches Thema")
        addItemDesc(NTechItems.politicalTopic, "Donald Duck wird die Mauer bauen!")
        addItem(NTechItems.ownOpinion, "Eigene Meinung")
        addItemDesc(NTechItems.ownOpinion, "Nun ja, mir gefällt's...")

        addItem(NTechItems.explosivePellets, "Explosive Pellets")
        addItemDesc(NTechItems.explosivePellets, "Wird in Mehrzweckbomben verwendet:\nFür ein wenig extra Boom!")
        addItem(NTechItems.leadPellets, "Schrotkugeln")
        addItem(NTechItems.flechettes, "Flechets")
        addItem(NTechItems.poisonGasCartridge, "Giftgaskartusche")
        addItemDesc(NTechItems.poisonGasCartridge, "Wird in Mehrzweckbomben verwendet:\n*hust hust* Hilfä!")
        addItem(NTechItems.magnetron, "Magnetron")
        addItem(NTechItems.denseCoalCluster, "Dichter Kohlecluster")
        addItem(NTechItems.burntBark, "Verbrannte Rinde")
        addItemDesc(NTechItems.burntBark, "Ein Stück Rinde von einer explodierten goldenen Eiche.")
        addItem(NTechItems.machineUpgradeTemplate, "Maschinenupgrade-Vorlage")

        addItem(NTechItems.blankRune, "Blanke Katalysatormatrix")
        addItem(NTechItems.isaRune, "Kalte Katalysatormatrix")
        addItem(NTechItems.dagazRune, "Ausgeglichene Katalysatormatrix")
        addItem(NTechItems.hagalazRune, "Grobe Katalysatormatrix")
        addItem(NTechItems.jeraRune, "Multiplikative Katalysatormatrix")
        addItem(NTechItems.thurisazRune, "Additive Katalysatormatrix")

        addItem(NTechItems.burnedOutQuadSchrabidiumFuelRod, "Ausgebrannter Schrabidiumvierfachbrennstab")
        addItemDesc(NTechItems.burnedOutQuadSchrabidiumFuelRod, "Ein Vierfachbrennstab der eine kleine Menge\neines seltsamen neuen Elements beinhaltet.")

        addItem(NTechItems.scrap, "Schrott")
        addItem(NTechItems.hotDepletedUraniumFuel, "Heißer Erschöpfter Urankernbrennstoff")
        addItem(NTechItems.hotDepletedThoriumFuel, "Heißer Erschöpfter Thoriumkernbrennstoff")
        addItem(NTechItems.hotDepletedPlutoniumFuel, "Heißer Erschöpfter Plutoniumkernbrennstoff")
        addItem(NTechItems.hotDepletedMOXFuel, "Heißer Erschöpfter MOX-Kernbrennstoff")
        addItem(NTechItems.hotDepletedSchrabidiumFuel, "Heißer Erschöpfter Schrabidiumkernbrennstoff")
        addItem(NTechItems.depletedUraniumFuel, "Erschöpfter Urankernbrennstoff")
        addItem(NTechItems.depletedThoriumFuel, "Erschöpfter Thoriumkernbrennstoff")
        addItem(NTechItems.depletedPlutoniumFuel, "Erschöpfter Plutoniumkernbrennstoff")
        addItem(NTechItems.depletedMOXFuel, "Erschöpfter MOX-Kernbrennstoff")
        addItem(NTechItems.depletedSchrabidiumFuel, "Erschöpfter Schrabidiumkernbrennstoff")
        addItem(NTechItems.trinitite, "Trinitit")
        addItem(NTechItems.nuclearWaste, "Atommüll")
        addItem(NTechItems.tinyNuclearWaste, "Kleiner Haufen Atommüll")

        addItem(NTechItems.crystalHorn, "Kristallhorn")
        addItemDesc(NTechItems.crystalHorn, "Ein echtes Horn.")
        addItem(NTechItems.charredCrystal, "Verkohlter Kristall")
        addItemDesc(NTechItems.charredCrystal, "Auch ein echtes Horn. Komisch, nicht?")

        addItem(NTechItems.battery, "Batterie")
        addItem(NTechItems.redstonePowerCell, "Redstone-Energiezelle")
        addItem(NTechItems.sixfoldRedstonePowerCell, "Sechsfache Redstone-Energiezelle")
        addItem(NTechItems.twentyFourFoldRedstonePowerCell, "24-Fache Redstone-Energiezelle")
        addItem(NTechItems.advancedBattery, "Fortgeschrittene Batterie")
        addItem(NTechItems.advancedPowerCell, "Fortgeschrittene Energiezelle")
        addItem(NTechItems.quadrupleAdvancedPowerCell, "Vierfache Fortgeschrittene Energiezelle")
        addItem(NTechItems.twelveFoldAdvancedPowerCell, "Zwölffache Fortgeschrittene Energiezelle")
        addItem(NTechItems.lithiumBattery, "Lithium-Ionen-Batterie")
        addItem(NTechItems.lithiumPowerCell, "Lithium-Ionen-Energiezelle")
        addItem(NTechItems.tripleLithiumPowerCell, "Dreifache Lithium-Ionen-Energiezelle")
        addItem(NTechItems.sixfoldLithiumPowerCell, "Sechsfache Lithium-Ionen-Energiezelle")
        addItem(NTechItems.schrabidiumBattery, "Schrabidiumbatterie")
        addItem(NTechItems.schrabidiumPowerCell, "Schrabidium-Energiezelle")
        addItem(NTechItems.doubleSchrabidiumPowerCell, "Doppelte Schrabidium-Energiezelle")
        addItem(NTechItems.quadrupleSchrabidiumPowerCell, "Vierfache Schrabidium-Energiezelle")
        addItem(NTechItems.sparkBattery, "Spark-Batterie")
        addItem(NTechItems.offBrandSparkBattery, "Billige Spark-Batterie-Nachmache")
        addItem(NTechItems.sparkPowerCell, "Spark-Energiezelle")
        addItem(NTechItems.sparkArcaneCarBattery, "Spark-Arkane Autobatterie")
        addItem(NTechItems.sparkArcaneEnergyStorageArray, "Spark-Arkane Energiespeichermatrix")
        addItem(NTechItems.sparkArcaneMassEnergyVoid, "Spark-Arkane Massenenergie Speicherleere")
        addItem(NTechItems.sparkArcaneDiracSea, "Spark-Arkanes Dirac'sches Meer")
        addItem(NTechItems.sparkSolidSpaceTimeCrystal, "Spark Solider Raumzeit Kristall")
        addItem(NTechItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit, "Spark Lächerliche Physikmissachtende Energiespeichereinheit")
        addItem(NTechItems.infiniteBattery, "Unendliche Batterie")
        addItem(NTechItems.singleUseBattery, "Einwegbatterie")
        addItem(NTechItems.largeSingleUseBattery, "Große Einwegbatterie")
        addItem(NTechItems.potatoBattery, "Kartoffelbatterie")
        addItem(NTechItems.steamPoweredEnergyStorageTank, "Dampfbetriebener Energiespeichertank")
        addItem(NTechItems.largeSteamPoweredEnergyStorageTank, "Großer Dampfbetriebener Energiespeichertank")

        addItem(NTechItems.stoneFlatStamp, "Flacher Stempel (Stein)")
        addItem(NTechItems.stonePlateStamp, "Plattenstempel (Stein)")
        addItem(NTechItems.stoneWireStamp, "Kabelstempel (Stein)")
        addItem(NTechItems.stoneCircuitStamp, "Schaltkreisstempel (Stein)")
        addItem(NTechItems.ironFlatStamp, "Flacher Stempel (Eisen)")
        addItem(NTechItems.ironPlateStamp, "Plattenstempel (Eisen)")
        addItem(NTechItems.ironWireStamp, "Kabelstempel (Eisen)")
        addItem(NTechItems.ironCircuitStamp, "Schaltkreisstempel (Eisen)")
        addItem(NTechItems.steelFlatStamp, "Flacher Stempel (Stahl)")
        addItem(NTechItems.steelPlateStamp, "Plattenstempel (Stahl)")
        addItem(NTechItems.steelWireStamp, "Kabelstempel (Stahl)")
        addItem(NTechItems.steelCircuitStamp, "Schaltkreisstempel (Stahl)")
        addItem(NTechItems.titaniumFlatStamp, "Flacher Stempel (Titan)")
        addItem(NTechItems.titaniumPlateStamp, "Plattenstempel (Titan)")
        addItem(NTechItems.titaniumWireStamp, "Kabelstempel (Titan)")
        addItem(NTechItems.titaniumCircuitStamp, "Schaltkreisstempel (Titan)")
        addItem(NTechItems.obsidianFlatStamp, "Flacher Stempel (Obsidian)")
        addItem(NTechItems.obsidianPlateStamp, "Plattenstempel (Obsidian)")
        addItem(NTechItems.obsidianWireStamp, "Kabelstempel (Obsidian)")
        addItem(NTechItems.obsidianCircuitStamp, "Schaltkreisstempel (Obsidian)")
        addItem(NTechItems.schrabidiumFlatStamp, "Flacher Stempel (Schrabidium)")
        addItem(NTechItems.schrabidiumPlateStamp, "Plattenstempel (Schrabidium)")
        addItem(NTechItems.schrabidiumWireStamp, "Kabelstempel (Schrabidium)")
        addItem(NTechItems.schrabidiumCircuitStamp, "Schaltkreisstempel (Schrabidium)")

        addItem(NTechItems.speedUpgradeMk1, "Geschwindigkeitsupgrade Mk.I")
        addItem(NTechItems.speedUpgradeMk2, "Geschwindigkeitsupgrade Mk.II")
        addItem(NTechItems.speedUpgradeMk3, "Geschwindigkeitsupgrade Mk.III")
        addItem(NTechItems.powerSavingUpgradeMk1, "Stromsparupgrade Mk.I")
        addItem(NTechItems.powerSavingUpgradeMk2, "Stromsparupgrade Mk.II")
        addItem(NTechItems.powerSavingUpgradeMk3, "Stromsparupgrade Mk.III")
        addItem(NTechItems.overdriveUpgradeMk1, "Overdrive-Upgrade Mk.I")
        addItem(NTechItems.overdriveUpgradeMk2, "Overdrive-Upgrade Mk.II")
        addItem(NTechItems.overdriveUpgradeMk3, "Overdrive-Upgrade Mk.III")

        addItem(NTechItems.aluminiumShredderBlade, "Aluminiumsägeblatt")
        addItem(NTechItems.goldShredderBlade, "Goldsägeblatt")
        addItem(NTechItems.ironShredderBlade, "Eisensägeblatt")
        addItem(NTechItems.steelShredderBlade, "Stahlsägeblatt")
        addItem(NTechItems.titaniumShredderBlade, "Titansägeblatt")
        addItem(NTechItems.advancedAlloyShredderBlade, "Fortgeschrittenes Legierungssägeblatt")
        addItem(NTechItems.combineSteelShredderBlade, "Combine Stahlsägeblatt")
        addItem(NTechItems.schrabidiumShredderBlade, "Schrabidiumsägeblatt")
        addItem(NTechItems.deshShredderBlade, "Deshsägeblatt")

        addItem(NTechItems.machineTemplateFolder, "Produktionsvorlagen-Zeichenmappe")
        addItemDesc(
            NTechItems.machineTemplateFolder,
            "Maschinenvorlagen: Papier + Farbstoff\n" +
                    "Flüssigkeit-IDs: Eisenplatte + Farbstoff\n" +
                    "Pressstempel: Flacher Stempel\n" +
                    "Sirenentracks: Isolator + Stahlplatte"
        )

        addItem(NTechItems.sirenTrackHatchSiren, "Hatch Siren")
        addItem(NTechItems.sirenTrackAutopilotDisconnected, "Autopilot Disconnected")
        addItem(NTechItems.sirenTrackAMSSiren, "AMS Siren")
        addItem(NTechItems.sirenTrackBlastDoorAlarm, "Blast Door Alarm")
        addItem(NTechItems.sirenTrackAPCSiren, "APC Siren")
        addItem(NTechItems.sirenTrackKlaxon, "Klaxon")
        addItem(NTechItems.sirenTrackVaultDoorAlarm, "Vault Door Alarm")
        addItem(NTechItems.sirenTrackSecurityAlert, "Security Alert")
        addItem(NTechItems.sirenTrackStandardSiren, "Standard Siren")
        addItem(NTechItems.sirenTrackClassicSiren, "Classic Siren")
        addItem(NTechItems.sirenTrackBankAlarm, "Bank Alarm")
        addItem(NTechItems.sirenTrackBeepSiren, "Beep Siren")
        addItem(NTechItems.sirenTrackContainerAlarm, "Container Alarm")
        addItem(NTechItems.sirenTrackSweepSiren, "Sweep Siren")
        addItem(NTechItems.sirenTrackMissileSiloSiren, "Missile Silo Siren")
        addItem(NTechItems.sirenTrackAirRaidSiren, "Air Raid Siren")
        addItem(NTechItems.sirenTrackNostromoSelfDestruct, "Nostromo Self Destruct")
        addItem(NTechItems.sirenTrackEASAlarmScreech, "EAS Alarm Screech")
        addItem(NTechItems.sirenTrackAPCPass, "APC Pass")
        addItem(NTechItems.sirenTrackRazortrainHorn, "Razortrain Horn")

        addItem(NTechItems.assemblyTemplate, "Fertigungsvorlage: %s")
        addItem(NTechItems.chemTemplate, "Chemievorlage: %s")

        run {
            val usedInLittleBoy = "Wird gebraucht für:\nLittle Boy"
            addItem(NTechItems.neutronShieldingLittleBoy, "Neutronenschild")
            addItemDesc(NTechItems.neutronShieldingLittleBoy, usedInLittleBoy)
            addItem(NTechItems.subcriticalUraniumTarget, "Unterkritischer U235-Hohlkörper")
            addItemDesc(NTechItems.subcriticalUraniumTarget, usedInLittleBoy)
            addItem(NTechItems.uraniumProjectile, "U235 Geschoss")
            addItemDesc(NTechItems.uraniumProjectile, usedInLittleBoy)
            addItem(NTechItems.propellantLittleBoy, "Treibladung")
            addItemDesc(NTechItems.propellantLittleBoy, usedInLittleBoy)
            addItem(NTechItems.bombIgniterLittleBoy, "Zünder")
            addItemDesc(NTechItems.bombIgniterLittleBoy, usedInLittleBoy)
        }
        addItem(NTechItems.bundleOfImplosionPropellant, "Implosions-Treibladung")
        addItemDesc(NTechItems.bundleOfImplosionPropellant, "Wird gebraucht für:\nFat Man\nIvy Mike\nTsar Bombe")
        addItem(NTechItems.bombIgniterFatMan, "Zünder")
        addItemDesc(NTechItems.bombIgniterFatMan, "Wird gebraucht für Fat Man")
        addItem(NTechItems.plutoniumCore, "Plutoniumkern")
        addItemDesc(NTechItems.plutoniumCore, "Wird gebraucht für:\nFat Man\nIvy Mike\nTsar Bombe")
        addItem(NTechItems.detonator, "Fernzünder")
        addItemDesc(NTechItems.detonator, "Shift-Rechtsklick auf einen Sprengstoff um die Position zu setzen,\nRechtsklick um zu sprengen!")
        addItem(NTechItems.littleBoyKit, "Little Boy Kit")
        addItem(NTechItems.fatManKit, "Fat Man Kit")

        addItem(NTechItems.designator, "Kurzdistanz Zielmarkierer")
        addItem(NTechItems.heMissile, "HE Rakete")
        addItem(NTechItems.incendiaryMissile, "Brandrakete")
        addItem(NTechItems.clusterMissile, "Streurakete")
        addItem(NTechItems.bunkerBusterMissile, "Bunkerbrechende Rakete")
        addItem(NTechItems.strongMissile, "Starke HE Rakete")
        addItem(NTechItems.strongIncendiaryMissile, "Starke Brandrakete")
        addItem(NTechItems.strongClusterMissile, "Starke Streurakete")
        addItem(NTechItems.strongBunkerBusterMissile, "Verbesserte Bunkerbrechende Rakete")
        addItem(NTechItems.burstMissile, "Berstrakete")
        addItem(NTechItems.infernoMissile, "Inferno Rakete G.R.N. Mk.II")
        addItem(NTechItems.rainMissile, "Schüttbombenregen")
        addItem(NTechItems.drillMissile, "Der Betonbrecher")
        addItem(NTechItems.nuclearMissile, "Atomrakete")

        addItem(NTechItems.oilDetector, "Ölvorkommen-Detektor")
        addItemDesc(NTechItems.oilDetector, "Rechtsklick um nach Öl zu suchen.\nDetektor findet nur größere Vorkommen.")
        addItem(NTechItems.geigerCounter, "Mobiler Geigerzähler")

        addItem(NTechItems.ivBag, "Infusionsbeutel")
        addItem(NTechItems.bloodBag, "Blutbeutel")
        addItem(NTechItems.emptyExperienceBag, "Leerer Erfahrungsbeutel")
        addItem(NTechItems.experienceBag, "Erfahrungsbeutel")
        addItem(NTechItems.radAway, "RadAway")
        addItem(NTechItems.strongRadAway, "Starkes RadAway")
        addItem(NTechItems.eliteRadAway, "Elite-RadAway")

        addItem(NTechItems.hazmatHelmet, "Strahlenschutzhelm")
        addItem(NTechItems.hazmatChestplate, "Strahlenschutzbrustplatte")
        addItem(NTechItems.hazmatLeggings, "Strahlenschutzhose")
        addItem(NTechItems.hazmatBoots, "Strahlenschutzstiefel")
        addItem(NTechItems.advancedHazmatHelmet, "Verbesserter Strahlenschutzhelm")
        addItem(NTechItems.advancedHazmatChestplate, "Verbesserte Strahlenschutzbrustplatte")
        addItem(NTechItems.advancedHazmatLeggings, "Verbesserte Strahlenschutzhose")
        addItem(NTechItems.advancedHazmatBoots, "Verbesserte Strahlenschutzstiefel")
        addItem(NTechItems.reinforcedHazmatHelmet, "Hochleistungs-Strahlenschutzhelm")
        addItem(NTechItems.reinforcedHazmatChestplate, "Hochleistungs-Strahlenschutzbrustplatte")
        addItem(NTechItems.reinforcedHazmatLeggings, "Hochleistungs-Strahlenschutzhose")
        addItem(NTechItems.reinforcedHazmatBoots, "Hochleistungs-Strahlenschutzstiefel")
        addItem(NTechItems.titaniumHelmet, "Titanhelm")
        addItem(NTechItems.titaniumChestplate, "Titanharnisch")
        addItem(NTechItems.titaniumLeggings, "Titanbeinschutz")
        addItem(NTechItems.titaniumBoots, "Titanharnisch")
        addItem(NTechItems.steelHelmet, "Stahlhelm")
        addItem(NTechItems.steelChestplate, "Stahlharnisch")
        addItem(NTechItems.steelLeggings, "Stahlbeinschutz")
        addItem(NTechItems.steelBoots, "Stahlstiefel")
        addItem(NTechItems.advancedAlloyHelmet, "Legierungshelm")
        addItem(NTechItems.advancedAlloyChestplate, "Legierungsharnisch")
        addItem(NTechItems.advancedAlloyLeggings, "Legierungsbeinschutz")
        addItem(NTechItems.advancedAlloyBoots, "Legierungsstiefel")
        addItem(NTechItems.combineSteelHelmet, "Combine-Stahlhelm")
        addItem(NTechItems.combineSteelChestplate, "Combine-Stahlharnisch")
        addItem(NTechItems.combineSteelLeggings, "Combine-Stahlbeinschutz")
        addItem(NTechItems.combineSteelBoots, "Combine-Stahlstiefel")
        addItem(NTechItems.paAAlloyChestplate, "PaA-Brustschutzplatte")
        addItem(NTechItems.paAAlloyLeggings, "PaA-Beinverstärkungsschienen")
        addItem(NTechItems.paAAlloyBoots, "PaA-\"olle Latschen\"")
        addItem(NTechItems.schrabidiumHelmet, "Schrabidiumhelm")
        addItem(NTechItems.schrabidiumChestplate, "Schrabidiumharnisch")
        addItem(NTechItems.schrabidiumLeggings, "Schrabidiumbeinschutz")
        addItem(NTechItems.schrabidiumBoots, "Schrabidiumstiefel")

        addItem(NTechItems.polaroid, "Das Polaroid")

        addItem(NTechFluids.uraniumHexafluoride.bucket, "Uranhexafluorideimer")

        addItem(NTechItems.creativeNuclearExplosionSpawner, "Atomexplosionserzeuger")

        addEntityType(EntityTypes.nuclearExplosion, "Nukleare Explosion")
        addEntityType(EntityTypes.mushroomCloud, "Atompilz")
        addEntityType(EntityTypes.falloutRain, "Fallout-Regen")
        addEntityTypeWithSpawnEgg(EntityTypes.nuclearCreeper, "Nuklearer Creeper")

        addEntityType(EntityTypes.missileHE, "HE Rakete")
        addEntityType(EntityTypes.missileIncendiary, "Brandrakete")
        addEntityType(EntityTypes.missileCluster, "Streurakete")
        addEntityType(EntityTypes.missileBunkerBuster, "Bunkerbrechende Rakete")
        addEntityType(EntityTypes.missileHEStrong, "Starke HE Rakete")
        addEntityType(EntityTypes.missileIncendiaryStrong, "Starke Brandrakete")
        addEntityType(EntityTypes.missileClusterStrong, "Starke Streurakete")
        addEntityType(EntityTypes.missileBunkerBusterStrong, "Verbesserte Bunkerbrechende Rakete")
        addEntityType(EntityTypes.missileBurst, "Berstrakete")
        addEntityType(EntityTypes.missileInferno, "Inferno Rakete G.R.N. Mk.II")
        addEntityType(EntityTypes.missileRain, "Schüttbombenregen")
        addEntityType(EntityTypes.missileDrill, "Der Betonbrecher")
        addEntityType(EntityTypes.missileNuclear, "Atomrakete")

        addEntityType(EntityTypes.clusterFragment, "Schüttbombe")

        addMenuType(MenuTypes.sirenMenu, "Sirene")
        addMenuType(MenuTypes.safeMenu, "Panzerschrank")
        addMenuType(MenuTypes.anvilMenu, "Stufe %s Amboss")
        addMenuType(MenuTypes.steamPressMenu, "Dampfpresse")
        addMenuType(MenuTypes.blastFurnaceMenu, "Hochofen")
        addMenuType(MenuTypes.combustionGeneratorMenu, "Verbrennungsgenerator")
        addMenuType(MenuTypes.electricFurnaceMenu, "Elektrischer Ofen")
        addMenuType(MenuTypes.shredderMenu, "Brecher")
        addMenuType(MenuTypes.assemblerMenu, "Fertigungsmaschine")
        addMenuType(MenuTypes.chemPlantMenu, "Chemiewerk")

        addMenuType(MenuTypes.littleBoyMenu, "Little Boy")
        addMenuType(MenuTypes.fatManMenu, "Fat Man")

        addMenuType(MenuTypes.launchPadMenu, "Raketenabschussrampe")

        addSound(SoundEvents.sirenTrackHatchSiren, "Sirene läuft: Hatch Siren")
        addSound(SoundEvents.sirenTrackAutopilotDisconnected, "Sirene läuft: Autopilot Disconnected")
        addSound(SoundEvents.sirenTrackAMSSiren, "Sirene läuft: AMS Siren")
        addSound(SoundEvents.sirenTrackBlastDoorAlarm, "Sirene läuft: Blast Door Alarm")
        addSound(SoundEvents.sirenTrackAPCSiren, "Sirene läuft: APC Siren")
        addSound(SoundEvents.sirenTrackKlaxon, "Sirene läuft: Klaxon")
        addSound(SoundEvents.sirenTrackVaultDoorAlarm, "Sirene läuft: Vault Door Alarm")
        addSound(SoundEvents.sirenTrackSecurityAlert, "Sirene läuft: Security Alert")
        addSound(SoundEvents.sirenTrackStandardSiren, "Sirene läuft: Standard Siren")
        addSound(SoundEvents.sirenTrackClassicSiren, "Sirene läuft: Classic Siren")
        addSound(SoundEvents.sirenTrackBankAlarm, "Sirene läuft: Bank Alarm")
        addSound(SoundEvents.sirenTrackBeepSiren, "Sirene läuft: Beep Siren")
        addSound(SoundEvents.sirenTrackContainerAlarm, "Sirene läuft: Container Alarm")
        addSound(SoundEvents.sirenTrackSweepSiren, "Sirene läuft: Sweep Siren")
        addSound(SoundEvents.sirenTrackMissileSiloSiren, "Sirene läuft: Missile Silo Siren")
        addSound(SoundEvents.sirenTrackAirRaidSiren, "Sirene läuft: Air Raid Siren")
        addSound(SoundEvents.sirenTrackNostromoSelfDestruct, "Sirene läuft: Nostromo Self Destruct")
        addSound(SoundEvents.sirenTrackEASAlarmScreech, "Sirene läuft: EAS Alarm Screech")
        addSound(SoundEvents.sirenTrackAPCPass, "Sirene läuft: APC Pass")
        addSound(SoundEvents.sirenTrackRazortrainHorn, "Sirene läuft: Razortrain Horn")
        addSound(SoundEvents.anvilFall, "Amboss klescht")
        addSound(SoundEvents.pressOperate, "Presse stampft")
        addSound(SoundEvents.assemblerOperate, "Fertigungsmaschine arbeitet")
        addSound(SoundEvents.chemPlantOperate, "Chemiewerk arbeitet")
        addSound(SoundEvents.debris, "Trümmer schlagen ein")
        addSound(SoundEvents.installUpgrade, "Upgrade installiert")
        addSound(SoundEvents.inject, "Nadel injiziert")
        addSound(SoundEvents.emptyIVBag, "Flüssigkeit infusioniert")
        addSound(SoundEvents.randomBleep, "Gerät piepst")
        addSound(SoundEvents.randomBoop, "Gerät boopt")
        addSound(SoundEvents.randomUnpack, "Gegenstand ausgepackt")
        add("subtitle.$MODID.geiger.click", "Geigerzähler klickt")
        addSound(SoundEvents.missileTakeoff, "Rakete hebt ab")
        addSound(SoundEvents.miniNukeExplosion, "Miniatombombe explodiert")

        addDamageSource(DamageSources.extractBlood, "%1\$s hat zu viel Lebensessenz extrahiert", "%1\$s hat versucht, schön-verpackten Lebenssaft für %2\$s zu hinterlassen")
        addDamageSource(DamageSources.radiation, "%1\$s starb an Strahlenvergiftung", "%1\$s fiel während des Kampfes mit %2\$s der Strahlenkrankheit zum Opfer")
        addDamageSource(DamageSources.nuclearBlast, "%1\$s wurde von einer Atomexplosion weggeblasen", "%1\$s wurde während des Kampfes mit %2\$s atomisiert")
        addDamageSource(DamageSources.murkyAnvil, "%1\$s UNDEFINIERT", "%1\$s UNDEFINIERT beim Versuch %2\$s zu entkommen")

        addAttribute(Attributes.RADIATION_RESISTANCE, "Strahlenresistenz")

        add(LangKeys.ARMOR_BLAST_PROTECTION, "Explosionsmodifikator: %s")
        add(LangKeys.ARMOR_CUSTOM_GEIGER, "Geigerzähler-HUD")
        add(LangKeys.ARMOR_DAMAGE_CAP, "Schadensobergrenze: %s")
        add(LangKeys.ARMOR_DAMAGE_MODIFIER, "Genereller Schadensmodifikator: %s")
        add(LangKeys.ARMOR_DAMAGE_RESISTANCE_MODIFIER, "Modifikator: %s (%s)")
        add(LangKeys.ARMOR_DAMAGE_THRESHOLD, "Schadensschwelle: %s")
        add(LangKeys.ARMOR_DASH_COUNT, "Gibt %s Dashes")
        add(LangKeys.ARMOR_FIREPROOF, "Feuerfest")
        add(LangKeys.ARMOR_FULL_SET_BONUS, "Set-Bonus:")
        add(LangKeys.ARMOR_GEIGER_SOUND, "Akustischer Geigerzähler")
        add(LangKeys.ARMOR_GRAVITY, "Schwerkraftsmodifikator: %s")
        add(LangKeys.ARMOR_HARD_LANDING, "Harte Landung")
        add(LangKeys.ARMOR_NULLIFIES_DAMAGE, "Nichtet Schaden von %s")
        add(LangKeys.ARMOR_PROJECTILE_PROTECTION, "Projektilmodifikator: %s")
        add(LangKeys.ARMOR_PROTECTION_YIELD, "Schützt für Schaden <%s")
        add(LangKeys.ARMOR_THERMAL, "Wärmebildkamera")
        add(LangKeys.ARMOR_VATS, "Feinde-HUD")

        add(LangKeys.BUTTON_CANCEL, "Abbrechen")
        add(LangKeys.BUTTON_START, "Starten")

        add(LangKeys.CHEMISTRY_URANIUM_HEXAFLUORIDE, "Uranhexafluoridproduktion")

        add(LangKeys.DETONATOR_INVALID_BLOCK_ENTITY, "Serverfehler: Die BlockEntity des Ziels ist ungültig!")
        add(LangKeys.DETONATOR_MISSING_COMPONENTS, "Der Sprengstoff ist unvollständig!")
        add(LangKeys.DETONATOR_NO_EXPLOSIVE, "Das Ziel ist kein gültiger Sprengstoff!")
        add(LangKeys.DETONATOR_PROHIBITED, "Die Sprengung wurde aufgehalten!")
        add(LangKeys.DETONATOR_SUCCESS, "Sprengung!")
        add(LangKeys.DETONATOR_UNKNOWN_ERROR, "Ein unbekannter Fehler ist während der Sprengung aufgetreten")

        add(LangKeys.DEVICE_OIL_DETECTOR_BELOW, "Ölvorkommen direkt untertage!")
        add(LangKeys.DEVICE_OIL_DETECTOR_NEAR, "Ölvorkommen in der Nähe")
        add(LangKeys.DEVICE_OIL_DETECTOR_NO_OIL, "Kein Öl gefunden")
        add(LangKeys.DEVICE_POSITION_SET, "Position gesetzt!")
        add(LangKeys.DEVICE_POSITION_NOT_LOADED, "Die Zielposition ist momentan nicht in der Welt geladen!")
        add(LangKeys.DEVICE_POSITION_NOT_SET, "Keine Position gesetzt!")

        add(LangKeys.ENERGY, "Energie")
        add(LangKeys.ENERGY_ENERGY_STORED, "Energie gespeichert: %s/%sHE")
        add(LangKeys.ENERGY_CHARGE_RATE, "Laderate: %sHE/t")
        add(LangKeys.ENERGY_DISCHARGE_RATE, "Entladerate: %sHE/t")

        add(LangKeys.EXPLOSION_SPAWNER_ERROR_EXTRA_FALLOUT, "Kann den Extra-Fallout-Wert nicht lesen")
        add(LangKeys.EXPLOSION_SPAWNER_ERROR_STRENGTH, "Kann den Stärke-Wert nicht lesen")
        add(LangKeys.EXPLOSION_SPAWNER_EXTRA_FALLOUT, "Extra Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_HAS_FALLOUT, "Mit Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_MUTED, "Stumm")
        add(LangKeys.EXPLOSION_SPAWNER_NO_PERMISSION, "Kann den Atomexplosionserzeuger nicht benutzen: Unzureichende Berechtigungen")
        add(LangKeys.EXPLOSION_SPAWNER_POSITION, "Position")
        add(LangKeys.EXPLOSION_SPAWNER_STRENGTH, "Stärke")

        add(LangKeys.GEIGER_CHUNK_RADIATION, "Chunk-Strahlung:")
        add(LangKeys.GEIGER_PLAYER_IRRADIATION, "Spieler-Verstrahlung:")
        add(LangKeys.GEIGER_PLAYER_RESISTANCE, "Strahlungsresistenz:")
        add(LangKeys.GEIGER_TITLE, "GEIGERZÄHLER")
        add(LangKeys.GEIGER_TOTAL_ENVIRONMENTAL_RADIATION, "Gesamte Umgebungsstrahlung:")

        add(LangKeys.HAZARD_ASBESTOS, "[Asbest]")
        add(LangKeys.HAZARD_BLINDING, "[Blended]")
        add(LangKeys.HAZARD_COAL, "[Kohlestaub]")
        add(LangKeys.HAZARD_DIGAMMA, "[Digamma]")
        add(LangKeys.HAZARD_EXPLOSIVE, "[Entzündlich / Explosiv]")
        add(LangKeys.HAZARD_HEAT, "[Pyrophorisch / Heiß]")
        add(LangKeys.HAZARD_HYDROREACTIVE, "[Hydro-Reaktiv]")
        add(LangKeys.HAZARD_RADIATON, "[Radioaktiv]")

        add(LangKeys.INFO_INPUT, "Input:")
        add(LangKeys.INFO_INPUTS, "Inputs:")
        add(LangKeys.INFO_OUTPUT, "Output:")
        add(LangKeys.INFO_OUTPUTS, "Outputs:")
        add(LangKeys.INFO_POSITION, "Position: %d %d %d")
        add(LangKeys.INFO_PRODUCTION_TIME, "Produktionszeit:")

        add(LangKeys.JEI_CATEGORY_ASSEMBLING, "Maschienenanfertigungsrezepte")
        add(LangKeys.JEI_CATEGORY_BLASTING, "Hochofenrezepte")
        add(LangKeys.JEI_CATEGORY_CHEMISTRY, "Chemierezepte")
        add(LangKeys.JEI_CATEGORY_CONSTRUCTING, "Konstruktionsrezepe")
        add(LangKeys.JEI_CATEGORY_PRESSING, "Pressrezepte")
        add(LangKeys.JEI_CATEGORY_SHREDDING, "Zerkleinerungsrezepte")
        add(LangKeys.JEI_CATEGORY_SMITHING, "Schmiederezepte")
        add(LangKeys.JEI_CATEGORY_TEMPLATE_FOLDER, "Vorlagen-Zeichenmappe")
        add(LangKeys.JEI_EXPERIENCE, "%s EP")
        add(LangKeys.JEI_OUTPUT_CHANCE, "Wahrscheinlichkeit:")
        add(LangKeys.JEI_TIER_MINIMUM, "Mindeststufe: %s")
        add(LangKeys.JEI_TIER_RANGE, "Stufenbereich: %s..%s")

        add(LangKeys.SIREN_TRACK_LOOP, "Typ: Endlosschleife")
        add(LangKeys.SIREN_TRACK_ONCE, "Typ: Einmal abspielen")
        add(LangKeys.SIREN_TRACK_RANGE, "Reichweite: %s Meter")
        add(LangKeys.SIREN_TRACK_SIREN_TRACK, "Sirenentrack")

        add(LangKeys.UPGRADE_INFO_ACCEPTED_UPGRADES, "Akzeptierte Upgrades:")
        add(LangKeys.UPGRADE_INFO_CONSUMPTION, "Verbrauch: %s")
        add(LangKeys.UPGRADE_INFO_DELAY, "Dauer: %s")
        add(LangKeys.UPGRADE_INFO_STACKS_TO, "Stapelt bis Level %s")
        add(LangKeys.UPGRADE_NAME_OVERDRIVE, "Overdrive")
        add(LangKeys.UPGRADE_NAME_POWER_SAVING, "Stromersparung")
        add(LangKeys.UPGRADE_NAME_SPEED, "Geschwindigkeit")
        add(LangKeys.UPGRADE_WARN_INCOMPATIBLE, "Dieses Upgrade ist inkompatibel!")
        add(LangKeys.UPGRADE_WARN_MACHINE_NOT_UPGRADEABLE, "Diese Maschine ist nicht upgradebar!")
        add(LangKeys.UPGRADE_WARN_NOT_A_MACHINE, "Das ist keine Maschine!")
        add(LangKeys.UPGRADE_WARN_VIEW_MACHINE, "Betrachte eine Maschine für Info über Effekte")
        add(LangKeys.UPGRADE_WARN_UNKNOWN_COMPATIBILITY, "Kompatibilität mit der Maschine ist unbekannt")

        add(LangKeys.WORD_SECONDS, "Sekunden")
    }

    private fun addMaterials() = with(Materials) {
        addMaterial(coal, "Kohle")
        addMaterial(iron, "Eisen")
        addMaterial(copper, "Kupfer")
        addMaterial(gold, "Gold")
        addMaterial(redstone, "Redstone")
        addMaterial(emerald, "Smaragd")
        addMaterial(lazuli, "Lapis")
        addMaterial(diamond, "Diamant")

        addMaterial(actinium227, "Actinium-227")
        addMaterial(americium241, "Americium-241")
        addMaterial(americium242, "Americium-242")
        addMaterial(americiumFuel, "Americiumkernbrennstoff")
        addMaterial(advancedAlloy, "Fortgeschrittene Legierung")
        addMaterial(aluminium, "Aluminium")
        addMaterial(arsenic, "Arsen")
        addMaterial(asbestos, "Asbest")
        addMaterial(australium, "Australium")
        addMaterial(bakelite, "Bakelit")
        addMaterial(beryllium, "Beryllium")
        addMaterial(bismuth, "Bismut")
        addMaterial(boron, "Bor")
        addMaterial(cobalt, "Kobalt")
        addMaterial(cobalt60, "Kobalt-60")
        addMaterial(combineSteel, "Combine Stahl")
        addMaterial(daffergon, "Daffergon")
        addMaterial(desh, "Desh")
        addMaterial(dineutronium, "Dineutronium")
        addMaterial(electronium, "Elektronium")
        addMaterial(euphemium, "Euphemium")
        addMaterial(ferricSchrabidate, "Eisenschrabidat")
        addMaterial(fiberglass, "Fiberglas")
        addMaterial(fluorite, "Fluorit")
        addMaterial(ghiorsium336, "Ghiorsium-336")
        addMaterial(gold198, "Gold-198")
        addMaterial(graphite, "Graphit")
        addMaterial(hesFuel, "Stark Angereichertes Schrabidium")
        addMaterial(highSpeedSteel, "Schnellarbeitsstahl")
        addMaterial(insulator, "Isolator")
        addMaterial(lanthanum, "Lanthan")
        addMaterial(lead, "Blei")
        addMaterial(lead209, "Blei-209")
        addMaterial(lesFuel, "Schwach Angereichertes Schrabidium")
        addMaterial(lignite, "Braunkohle")
        addMaterial(lithium, "Lithium")
        addMaterial(magnetizedTungsten, "Magnetisiertes Wolfram")
        addMaterial(moxFuel, "MOX-Kernbrennstoff")
        addMaterial(naturalPlutonium, "Plutonium")
        addMaterial(naturalUranium, "Uran")
        addMaterial(neptunium, "Neptunium")
        addMaterial(neptuniumFuel, "Neptuniumkernbrennstoff")
        addMaterial(niobium, "Niob")
        addMaterial(niter, "Salpeter")
        addMaterial(nuclearWaste, "Atommüll")
        addMaterial(osmiridium, "Osmiridium")
        addMaterial(plutonium238, "Plutonium-238")
        addMaterial(plutonium239, "Plutonium-239")
        addMaterial(plutonium240, "Plutonium-240")
        addMaterial(plutonium241, "Plutonium-241")
        addMaterial(plutoniumFuel, "Plutoniumkernbrennstoff")
        addMaterial(polonium, "Polonium")
        addMaterial(polymer, "Polymer")
        addMaterial(radium226, "Radium-226")
        addMaterial(reactorGradeAmericium, "Reaktorfähiges Americium")
        addMaterial(reactorGradePlutonium, "Reaktorfähiges Plutonium")
        addMaterial(redCopper, "Rotes Kupfer")
        addMaterial(redPhosphorus, "Roter Phosphor")
        addMaterial(reiium, "Reiium")
        addMaterial(rubber, "Gummi")
        addMaterial(saturnite, "Saturnit")
        addMaterial(schrabidium, "Schrabidium")
        addMaterial(schrabidiumFuel, "Schrabidiumkernbrennstoff")
        addMaterial(schraranium, "Schraranium")
        addMaterial(solinium, "Solinium")
        addMaterial(starmetal, "Starmetal")
        addMaterial(steel, "Stahl")
        addMaterial(strontium90, "Strontium-90")
        addMaterial(sulfur, "Schwefel")
        addMaterial(tantalium, "Tantal")
        addMaterial(technetium99, "Technetium-99")
        addMaterial(technetiumSteel, "Technetiumstahl")
        addMaterial(thorium, "Thorium-232")
        addMaterial(thoriumFuel, "Thoriumkernbrennstoff")
        addMaterial(titanium, "Titan")
        addMaterial(trinitite, "Trinitit")
        addMaterial(tungsten, "Wolfram")
        addMaterial(unobtainium, "Unobtainium")
        addMaterial(uranium233, "Uran-233")
        addMaterial(uranium235, "Uran-235")
        addMaterial(uranium238, "Uran-238")
        addMaterial(uraniumFuel, "Urankernbrennstoff")
        addMaterial(verticium, "Verticium")
        addMaterial(weidanium, "Weidanium")
        addMaterial(whitePhosphorus, "Weißer Phosphor")
        addMaterial(yellowcake, "Yellowcake")
    }

    override val spawnEggSuffix = "-Spawn-Ei"
    override val spawnEggEntityStringWordSeparator = '-'

    override val oreFormat = "%serz"
    override val deepOreFormat = "Tiefenschiefer-%serz"
    override val blockFormat = "%sblock"
    override val rawFormat = "Rohes %s"
    override val ingotFormat = "%sbarren"
    override val nuggetFormat = "%sklumpen"
    override val crystalsFormat = "%skristalle"
    override val powderFormat = "%spulver"
    override val plateFormat = "%splatte"
    override val wireFormat = "%sdraht"
}
