package at.martinthedragon.nucleartech.datagen.localisation

import at.martinthedragon.nucleartech.*
import at.martinthedragon.nucleartech.datagen.NuclearLanguageProviders
import at.martinthedragon.nucleartech.entities.EntityTypes
import at.martinthedragon.nucleartech.items.EffectItem
import at.martinthedragon.nucleartech.menus.MenuTypes
import at.martinthedragon.nucleartech.screens.AnvilScreen
import net.minecraft.data.DataGenerator

class DeDeLanguageProvider(dataGenerator: DataGenerator) : NuclearLanguageProvider(dataGenerator, NuclearLanguageProviders.DE_DE) {
    override fun translate() {
        add("itemGroup.${MODID}_parts", "NTM Ressourcen und Bauteile")
        add("itemGroup.${MODID}_items", "NTM Maschinenitems")
        add("itemGroup.${MODID}_templates", "NTM Fertigungsvorlagen")
        add("itemGroup.${MODID}_blocks", "NTM Erze und Blöcke")
        add("itemGroup.${MODID}_machines", "NTM Maschinen")
        add("itemGroup.${MODID}_bombs", "NTM Bomben")
        add("itemGroup.${MODID}_consumables", "NTM Verbrauchsgüter")
        add("itemGroup.${MODID}_miscellaneous", "NTM Verschiedenes")

        add(EffectItem.EffectTypes.Radioactive.effectInfo.string, "[Radioaktiv]")
        add(EffectItem.EffectTypes.Blinding.effectInfo.string, "[Erblindend]")
        add(EffectItem.EffectTypes.Hot.effectInfo.string, "[Pyrophor / Heiß]")

        addMaterials()

        addBlock(ModBlocks.scorchedUraniumOre, "Verschmortes Uranerz")
        addBlock(ModBlocks.oilDeposit, "Ölvorkommen")
        addBlockDesc(ModBlocks.oilDeposit, "Du hättest das nicht abbauen sollen.\nNa los, hol dir einen Bohrturm, du Idiot.")
        addBlock(ModBlocks.emptyOilDeposit, "Leeres Ölvorkommen")
        addBlock(ModBlocks.oilSand, "Ölsand")
        addBlock(ModBlocks.australianOre, "Australisches Erz")
        addBlockDesc(ModBlocks.australianOre, "Australiumerz")
        addBlock(ModBlocks.weidite, "Weidit")
        addBlockDesc(ModBlocks.weidite, "Weidaniumerz")
        addBlock(ModBlocks.reiite, "Reiit")
        addBlockDesc(ModBlocks.reiite, "Reiiumerz")
        addBlock(ModBlocks.brightblendeOre, "Glimmerblende")
        addBlockDesc(ModBlocks.brightblendeOre, "Unobtainiumerz")
        addBlock(ModBlocks.dellite, "Dellit")
        addBlockDesc(ModBlocks.dellite, "Daffergonerz")
        addBlock(ModBlocks.dollarGreenMineral, "Dollargrünes Mineral")
        addBlockDesc(ModBlocks.dollarGreenMineral, "Verticiumerz")
        addBlock(ModBlocks.rareEarthOre, "Seltene-Erden-Erz")
        addBlock(ModBlocks.netherUraniumOre, "Netheruranerz")
        addBlock(ModBlocks.scorchedNetherUraniumOre, "Verschmortes Netheruranerz")
        addBlock(ModBlocks.netherPlutoniumOre, "Netherplutoniumerz")
        addBlock(ModBlocks.netherTungstenOre, "Netherwolframerz")
        addBlock(ModBlocks.netherSulfurOre, "Netherschwefelerz")
        addBlock(ModBlocks.netherPhosphorusOre, "Netherphosphorerz")
        addBlock(ModBlocks.netherSchrabidiumOre, "Netherschrabidiumerz")
        addBlock(ModBlocks.meteorUraniumOre, "Meteoritenuranerz")
        addBlock(ModBlocks.meteorThoriumOre, "Meteoritenthoriumerz")
        addBlock(ModBlocks.meteorTitaniumOre, "Meteoritentitanerz")
        addBlock(ModBlocks.meteorSulfurOre, "Meteoritenschwefelerz")
        addBlock(ModBlocks.meteorCopperOre, "Meteoritenkupfererz")
        addBlock(ModBlocks.meteorTungstenOre, "Meteoritenwolframerz")
        addBlock(ModBlocks.meteorAluminiumOre, "Meteoritenaluminiumerz")
        addBlock(ModBlocks.meteorLeadOre, "Meteoritenbleierz")
        addBlock(ModBlocks.meteorLithiumOre, "Meteoritenlithiumerz")
        addBlock(ModBlocks.starmetalOre, "Starmetalerz")
        addBlock(ModBlocks.trixite, "Trixit")

        addBlock(ModBlocks.scorchedDeepslateUraniumOre, "Verschmortes Tiefenschiefer-Uranerz")
        addBlock(ModBlocks.deepslateOilDeposit, "Tiefenschiefer-Ölvorkommen")
        addBlockDesc(ModBlocks.deepslateOilDeposit, "Du bist so tief gekommen und weißt\nimmer noch nicht, was zu tun ist? Wie?!")
        addBlock(ModBlocks.emptyDeepslateOilDeposit, "Leeres Tiefenschiefer-Ölvorkommen")
        addBlock(ModBlocks.deepslateAustralianOre, "Australisches Tiefenschiefer-Erz")
        addBlockDesc(ModBlocks.deepslateAustralianOre, "Australiumerz")
        addBlock(ModBlocks.deepslateRareEarthOre, "Seltene-Erden-Tiefenschiefer-Erz")

        addBlock(ModBlocks.u233Block, "U233-Block")
        addBlock(ModBlocks.u235Block, "U235-Block")
        addBlock(ModBlocks.u238Block, "U238-Block")
        addBlock(ModBlocks.pu238Block, "Pu238-Block")
        addBlock(ModBlocks.pu239Block, "Pu239-Block")
        addBlock(ModBlocks.pu240Block, "Pu240-Block")
        addBlock(ModBlocks.redCopperBlock, "Roter Kupferblock")
        addBlock(ModBlocks.advancedAlloyBlock, "Fortgeschrittener Legierungsblock")
        addBlock(ModBlocks.whitePhosphorusBlock, "Weißer Phosphorblock")
        addBlock(ModBlocks.redPhosphorusBlock, "Roter Phosphorblock")
        addBlock(ModBlocks.yellowcakeBlock, "Yellowcakeblock")
        addBlock(ModBlocks.scrapBlock, "Schrottblock")
        addBlock(ModBlocks.electricalScrapBlock, "Elektroschrottblock")
        addBlock(ModBlocks.insulatorRoll, "Isolatorrolle")
        addBlock(ModBlocks.fiberglassRoll, "Fiberglasrolle")
        addBlock(ModBlocks.trinititeBlock, "Trinititblock")
        addBlock(ModBlocks.nuclearWasteBlock, "Atommüllblock")
        addBlock(ModBlocks.schrabidiumCluster, "Schrabidium-Cluster")
        addBlock(ModBlocks.euphemiumEtchedSchrabidiumCluster, "Euphemiumgeätzter Schrabidium-Cluster")
        addBlock(ModBlocks.magnetizedTungstenBlock, "Magnetisierter Wolframblock")
        addBlock(ModBlocks.deshReinforcedBlock, "Verstärkter Deshblock")

        addBlock(ModBlocks.titaniumDecoBlock, "Titan-Dekoblock")
        addBlock(ModBlocks.redCopperDecoBlock, "Roter Kupfer-Dekoblock")
        addBlock(ModBlocks.tungstenDecoBlock, "Wolfram-Dekoblock")
        addBlock(ModBlocks.aluminiumDecoBlock, "Aluminium-Dekoblock")
        addBlock(ModBlocks.steelDecoBlock, "Stahl-Dekoblock")
        addBlock(ModBlocks.leadDecoBlock, "Blei-Dekoblock")
        addBlock(ModBlocks.berylliumDecoBlock, "Beryllium-Dekoblock")
        addBlock(ModBlocks.asbestosRoof, "Asbestdach")
        addBlock(ModBlocks.hazmatBlock, "Strahlenschutzstoff-Block")

        addBlock(ModBlocks.glowingMushroom, "Leuchtender Pilz")
        addBlock(ModBlocks.glowingMushroomBlock, "Leuchtender Pilzblock")
        addBlock(ModBlocks.glowingMushroomStem, "Leuchtender Pilzstamm")
        addBlock(ModBlocks.deadGrass, "Totes Gras")
        addBlock(ModBlocks.glowingMycelium, "Leuchtendes Myzel")
        addBlock(ModBlocks.trinitite, "Trinititerz")
        addBlock(ModBlocks.redTrinitite, "Rotes Trinititerz")
        addBlock(ModBlocks.charredLog, "Verkohltes Holz")
        addBlock(ModBlocks.charredPlanks, "Verkohlte Holzbretter")

        addBlock(ModBlocks.slakedSellafite, "Gelöschtes Sellafit")
        addBlock(ModBlocks.sellafite, "Sellafit")
        addBlock(ModBlocks.hotSellafite, "Heißes Sellafit")
        addBlock(ModBlocks.boilingSellafite, "Kochendes Sellafit")
        addBlock(ModBlocks.blazingSellafite, "Flammendes Sellafit")
        addBlock(ModBlocks.infernalSellafite, "Infernales Sellafit")
        addBlock(ModBlocks.sellafiteCorium, "Sellafit-Corium")

        addBlock(ModBlocks.siren, "Sirene")
        addBlock(ModBlocks.safe, "Panzerschrank")
        addBlock(ModBlocks.ironAnvil, "Eisenamboss")
        addBlock(ModBlocks.leadAnvil, "Bleiamboss")
        addBlock(ModBlocks.steelAnvil, "Stahlamboss")
        addBlock(ModBlocks.meteoriteAnvil, "Meteoritenamboss")
        addBlock(ModBlocks.starmetalAnvil, "Starmetalamboss")
        addBlock(ModBlocks.ferrouraniumAnvil, "Ferrouranamboss")
        addBlock(ModBlocks.bismuthAnvil, "Bismutamboss")
        addBlock(ModBlocks.schrabidateAnvil, "Eisenschrabidatamboss")
        addBlock(ModBlocks.dineutroniumAnvil, "Dineutroniumamboss")
        addBlock(ModBlocks.murkyAnvil, "Düsteramboss")
        addBlock(ModBlocks.steamPressBase, "Dampfpresse")
        addBlock(ModBlocks.steamPressFrame, "Dampfpresse")
        addBlock(ModBlocks.steamPressTop, "Dampfpresse")
        addBlock(ModBlocks.blastFurnace, "Hochofen")
        addBlock(ModBlocks.combustionGenerator, "Verbrennungsgenerator")
        addBlock(ModBlocks.electricFurnace, "Elektrischer Ofen")
        addBlock(ModBlocks.shredder, "Brecher")
        addBlock(ModBlocks.assembler, "Fertigungsmaschine")
        addBlock(ModBlocks.assemblerPart, "Fertigungsmaschine")

        addBlock(ModBlocks.littleBoy, "Little Boy")
        addBlock(ModBlocks.fatMan, "Fat Man")

        addItem(ModItems.rawRareEarth, "Rohe Seltene Erde")
        addItem(ModItems.rawTrixite, "Rohes Trixit")

        addItem(ModItems.u233Ingot, "U233-Barren")
        addItem(ModItems.u235Ingot, "U235-Barren")
        addItem(ModItems.u238Ingot, "U238-Barren")
        addItem(ModItems.th232Ingot, "Th232-Barren")
        addItem(ModItems.pu238Ingot, "Pu238-Barren")
        addItem(ModItems.pu239Ingot, "Pu239-Barren")
        addItem(ModItems.pu240Ingot, "Pu240-Barren")
        addItemDesc(ModItems.neptuniumIngot, "Diesen hier mag ich am allerliebsten!")
        addItem(ModItems.redCopperIngot, "Roter Kupferbarren")
        addItem(ModItems.advancedAlloyIngot, "Fortgeschrittene Legierung")
        addItemDesc(ModItems.schraraniumIngot, "Hergestellt aus Uran in einem Schrabidium-Transmutator")
        addItem(ModItems.magnetizedTungstenIngot, "Magnetisierter Wolframbarren")
        addItemDesc(ModItems.combineSteelIngot, "*Civil-Protection-Referenz hier einfügen*")
        addItem(ModItems.highEnrichedSchrabidiumFuelIngot, "Stark Angereicherter Schrabidiumkernbrennstoffbarren")
        addItem(ModItems.lowEnrichedSchrabidiumFuelIngot, "Schwach Angereicherter Schrabidiumkernbrennstoffbarren")
        addItem(ModItems.lanthanumIngot, "Semistabiler Lanthanbarren")
        addItem(ModItems.actiniumIngot, "Semistabiler Actiniumbarren")
        addItemDesc(ModItems.euphemiumIngot, "Ein sehr spezielles und doch seltsames Element")
        addItem(ModItems.whitePhosphorusIngot, "Weiße Phosphortafel")

        addItem(ModItems.semtexBar, "Semtextafel")
        addItemDesc(ModItems.semtexBar,
            "Semtex H Plastiksprengstoff\n" +
                    "Performanter Sprengstoff für viele Zwecke.\n" +
                    "Essbar"
        )

        addItem(ModItems.lithiumCube, "Lithiumwürfel")
        addItem(ModItems.solidFuelCube, "Festbrennstoffwürfel")
        addItem(ModItems.solidRocketFuelCube, "Festraketentreibstoffwürfel")

        addItem(ModItems.fiberglassSheet, "Fiberglasbogen")
        addItemDesc(ModItems.fiberglassSheet, "Reich an \"Ballaststoffen\", reich an Glas. Alles was der Körper braucht.")
        addItem(ModItems.asbestosSheet, "Asbestbogen")
        addItemDesc(ModItems.asbestosSheet, "§o\"Gefüllt mit Leben, Selbstzweifel und Asbest. Das kommt mit der Luft.\"")

        addItem(ModItems.mercuryDroplet, "Quecksilbertröpfchen")
        addItem(ModItems.mercuryBottle, "Quecksilberflasche")

        addItem(ModItems.coke, "Koks")
        addItem(ModItems.lignite, "Braunkohle")
        addItem(ModItems.ligniteBriquette, "Braunkohlebrikett")

        addItem(ModItems.sulfur, "Schwefel")
        addItem(ModItems.niter, "Salpeter")
        addItem(ModItems.fluorite, "Fluorit")
        addItem(ModItems.lapisLazuliPowder, "Lapis Lazuli-Pulver")
        addItem(ModItems.quartzPowder, "Quarzpulver")
        addItem(ModItems.advancedAlloyPowder, "Fortgeschrittenes Legierungspulver")
        addItem(ModItems.yellowcake, "Yellowcake")
        addItem(ModItems.chlorophytePowder, "Grünalgenpulver")
        addItem(ModItems.neodymiumPowder, "Neodympulver")
        addItem(ModItems.niobiumPowder, "Niobpulver")
        addItem(ModItems.ceriumPowder, "Cerpulver")
        addItemDesc(ModItems.asbestosPowder, "§o\"Schnauffffffff - MHHHHHHMHHHHHHHHH\"")
        addItem(ModItems.enchantmentPowder, "Pulverisierte Verzauberung")
        addItem(ModItems.cloudResidue, "Wolkenrückstände")
        addItem(ModItems.thermonuclearAshes, "Thermonukleare Asche")
        addItem(ModItems.semtexMix, "Semtexmischung")
        addItem(ModItems.deshMix, "Desh-Mischung")
        addItem(ModItems.deshReadyMix, "DeshReady™-Mischung")
        addItem(ModItems.nitaniumMix, "Nitanium-Mischung")
        addItem(ModItems.sparkMix, "Spark-Mischung")
        addItem(ModItems.meteoritePowder, "Meteoritenpulver")
        addItemDesc(ModItems.euphemiumPowder, "Pulverisiertes pink.\nSchmeckt nach Erdbeeren.")
        addItem(ModItems.desaturatedRedstone, "Entsättigter Redstone-Staub")
        addItem(ModItems.dust, "Staub")
        addItemDesc(ModItems.dust, "I hasse Staub!")
        addItem(ModItems.tinyLithiumPowder, "Kleiner Haufen Lithiumpulver")
        addItem(ModItems.tinyNeodymiumPowder, "Kleiner Haufen Neodympulver")
        addItem(ModItems.tinyCobaltPowder, "Kleiner Haufen Kobaltpulver")
        addItem(ModItems.tinyNiobiumPowder, "Kleiner Haufen Niobpulver")
        addItem(ModItems.tinyCeriumPowder, "Kleiner Haufen Cerpulver")
        addItem(ModItems.tinyLanthanumPowder, "Kleiner Haufen Lanthanpulver")
        addItem(ModItems.tinyActiniumPowder, "Kleiner Haufen Actiniumpulver")
        addItem(ModItems.tinyMeteoritePowder, "Kleiner Haufen Meteoritenpulver")
        addItem(ModItems.redPhosphorus, "Roter Phosphor")
        addItemDesc(ModItems.redPhosphorus, "Wird in Mehrzweckbomben verwendet:\nBrandbomben machen Spaß!")
        addItem(ModItems.cryoPowder, "Kryopulver")
        addItem(ModItems.poisonPowder, "Giftpulver")
        addItemDesc(ModItems.poisonPowder, "Wird in Mehrzweckbomben verwendet:\nAchtung: Giftig!")
        addItem(ModItems.thermite, "Thermit")
        addItem(ModItems.energyPowder, "Energiepulver")

        addItem(ModItems.cordite, "Cordit")
        addItem(ModItems.ballistite, "Ballistit")

        addItem(ModItems.rareEarthCrystals, "Seltene-Erden-Kristalle")
        addItem(ModItems.redPhosphorusCrystals, "Rote Phosphorkristalle")
        addItem(ModItems.trixiteCrystals, "Trixitkristalle")

        addItem(ModItems.neodymiumFragment, "Neodymiumfragment")
        addItem(ModItems.cobaltFragment, "Kobaltfragment")
        addItem(ModItems.niobiumFragment, "Niobfragment")
        addItem(ModItems.ceriumFragment, "Cerfragment")
        addItem(ModItems.lanthanumFragment, "Lanthanfragment")
        addItem(ModItems.actiniumFragment, "Actiniumfragment")
        addItem(ModItems.meteoriteFragment, "Meteoritenfragment")

        addItem(ModItems.biomass, "Biomasse")
        addItem(ModItems.compressedBiomass, "Verdichtete Biomasse")

        addItem(ModItems.u233Nugget, "U233-Klumpen")
        addItem(ModItems.u235Nugget, "U235-Klumpen")
        addItem(ModItems.u238Nugget, "U238-Klumpen")
        addItem(ModItems.th232Nugget, "Th232-Klumpen")
        addItem(ModItems.pu238Nugget, "Pu238-Klumpen")
        addItem(ModItems.pu239Nugget, "Pu239-Klumpen")
        addItem(ModItems.pu240Nugget, "Pu240-Klumpen")
        addItem(ModItems.highEnrichedSchrabidiumFuelNugget, "Stark Angereicherter Schrabidiumkernbrennstoffklumpen")
        addItem(ModItems.lowEnrichedSchrabidiumFuelNugget, "Schwach Angereicherter Schrabidiumkernbrennstoffklumpen")
        addItemDesc(ModItems.euphemiumNugget,
            "Ein kleines Stück von einem pinken Metall.\n" +
                    "Seine Eigenschaften sind immer noch unbekannt.\n" +
                    "Gehe vorsichtig damit um."
        )

        addItem(ModItems.advancedAlloyPlate, "Fortgeschrittene Legierungsplatte")
        addItem(ModItems.neutronReflector, "Neutronenreflektor")
        addItem(ModItems.mixedPlate, "Gemischte Platte")
        addItem(ModItems.paAAlloyPlate, "PaA-Legierungsplatte")
        addItem(ModItems.insulator, "Isolator")
        addItem(ModItems.kevlarCeramicCompound, "Kevlar-Keramik-Verbund")
        addItem(ModItems.dalekaniumPlate, "Wütendes Metall")
        addItem(ModItems.deshCompoundPlate, "Deshverbundplatte")
        addItem(ModItems.euphemiumCompoundPlate, "Euphemiumverbundplatte")
        addItem(ModItems.dineutroniumCompoundPlate, "Dineutroniumverbundplatte")
        addItem(ModItems.copperPanel, "Kupfertafel")

        addItem(ModItems.highSpeedSteelBolt, "Schnellarbeitsstahlbolzen")
        addItem(ModItems.tungstenBolt, "Wolframbolzen")
        addItem(ModItems.reinforcedTurbineShaft, "Verstärkte Turbinenwelle")

        addItem(ModItems.hazmatCloth, "Strahlenschutzanzugsstoff")
        addItem(ModItems.advancedHazmatCloth, "Verbesserter Strahlenschutzanzugsstoff")
        addItem(ModItems.leadReinforcedHazmatCloth, "Bleiverstärkter Strahlenschutzanzugsstoff")
        addItem(ModItems.fireProximityCloth, "Hitzeschutzanzugsstoff")
        addItem(ModItems.activatedCarbonFilter, "Aktivkohlefilter")

        addItem(ModItems.redCopperWire, "Roter Kupferdraht")
        addItem(ModItems.superConductor, "Supraleiter")
        addItem(ModItems.highTemperatureSuperConductor, "4000K Hochtemperaturensupraleiter")

        addItem(ModItems.copperCoil, "Kupferspule")
        addItem(ModItems.ringCoil, "Ringspule")
        addItem(ModItems.superConductingCoil, "Supraleitende Magnetspule")
        addItem(ModItems.superConductingRingCoil, "Supraleitende Ringspule")
        addItem(ModItems.goldCoil, "Goldspule")
        addItem(ModItems.goldRingCoil, "Gold Ringspule")
        addItem(ModItems.heatingCoil, "Heizspirale")
        addItem(ModItems.highTemperatureSuperConductingCoil, "4000K Hochtemperaturensupraleitermagnetspule")

        addItem(ModItems.steelTank, "Stahltank")
        addItem(ModItems.motor, "Motor")
        addItem(ModItems.centrifugeElement, "Zentrifugenelement")
        addItem(ModItems.centrifugeTower, "Zentrifugenturm")
        addItem(ModItems.deeMagnets, "Duantenmagneten")
        addItem(ModItems.flatMagnet, "Flachmagnet")
        addItem(ModItems.cyclotronTower, "Zyklotronenturm")
        addItem(ModItems.breedingReactorCore, "Brutreaktorkern")
        addItem(ModItems.rtgUnit, "RTG-Einheit")
        addItem(ModItems.thermalDistributionUnit, "Thermische Verteilungseinheit")
        addItem(ModItems.endothermicDistributionUnit, "Hitzeabsorptionseinheit")
        addItem(ModItems.exothermicDistributionUnit, "Hitzeverteilungseinheit")
        addItem(ModItems.gravityManipulator, "Gravitationsmanipulator")
        addItem(ModItems.steelPipes, "Stahlrohre")
        addItem(ModItems.titaniumDrill, "Titanbohrer")
        addItem(ModItems.photovoltaicPanel, "Photovoltaikpanele")
        addItem(ModItems.chlorinePinwheel, "Chlorgaskonverter")
        addItem(ModItems.telepad, "Teleplatte")
        addItem(ModItems.entanglementKit, "Verschränkungskit")
        addItemDesc(ModItems.entanglementKit,
            "Teleporter Crafting-Gegenstand.\n" +
                    "Ermöglicht Dimensionsverschiebung über einen\n" +
                    "berylliumverstärkten Ressourcenscanner."
        )
        addItem(ModItems.stabilizerComponent, "Stabilisatorkomponente")
        addItem(ModItems.emitterComponent, "Emitterkomponente")
        addItem(ModItems.aluminiumCap, "Aluminiumdeckel")
        addItem(ModItems.smallSteelShell, "Kleine Stahlhülle")
        addItem(ModItems.smallAluminiumShell, "Kleine Aluminiumhülle")
        addItem(ModItems.bigSteelShell, "Große Stahlhülle")
        addItem(ModItems.bigAluminiumShell, "Große Aluminiumhülle")
        addItem(ModItems.bigTitaniumShell, "Große Titanhülle")
        addItem(ModItems.flatSteelCasing, "Flache Stahlabdeckung")
        addItem(ModItems.smallSteelGridFins, "Kleine Stahlgitterfinnen")
        addItem(ModItems.bigSteelGridFins, "Große Stahlgitterfinnen")
        addItem(ModItems.largeSteelFins, "Große Stahlflossen")
        addItem(ModItems.smallTitaniumFins, "Kleine Titanflossen")
        addItem(ModItems.steelSphere, "Stahlhohlkugel")
        addItem(ModItems.steelPedestal, "Stahlsockel")
        addItem(ModItems.dysfunctionalNuclearReactor, "Funktionsunfähiger Atomreaktor")
        addItem(ModItems.largeSteelRotor, "Großer Stahlrotor")
        addItem(ModItems.generatorBody, "Generatorhauptteil")
        addItem(ModItems.titaniumBlade, "Titanturbinenschaufel")
        addItem(ModItems.tungstenReinforcedBlade, "Wolframverstärktes Turbinenblatt")
        addItem(ModItems.titaniumSteamTurbine, "Titandampfturbine")
        addItem(ModItems.reinforcedTurbofanBlades, "Verstärkte Turbofanblätter")
        addItem(ModItems.generatorFront, "Generatorfront")
        addItem(ModItems.toothpicks, "Zahnstocher")
        addItem(ModItems.ductTape, "Klebeband")
        addItem(ModItems.clayCatalyst, "Tonerdekatalysator")
        addItem(ModItems.smallMissileAssembly, "Kleines Raketenbauset")

        addItem(ModItems.smallWarhead, "Kleiner Sprengkopf")
        addItem(ModItems.mediumWarhead, "Mittlerer Sprengkopf")
        addItem(ModItems.largeWarhead, "Großer Sprengkopf")
        addItem(ModItems.smallIncendiaryWarhead, "Kleiner Brandsprengkopf")
        addItem(ModItems.mediumIncendiaryWarhead, "Mittlerer Brandsprengkopf")
        addItem(ModItems.largeIncendiaryWarhead, "Großer Brandsprengkopf")
        addItem(ModItems.smallClusterWarhead, "Kleiner Kasettensprengkopf")
        addItem(ModItems.mediumClusterWarhead, "Mittlerer Kasettensprengkopf")
        addItem(ModItems.largeClusterWarhead, "Großer Kasettensprengkopf")
        addItem(ModItems.smallBunkerBusterWarhead, "Kleiner Bunkerbrechender Sprengkopf")
        addItem(ModItems.mediumBunkerBusterWarhead, "Mittlerer Bunkerbrechender Sprengkopf")
        addItem(ModItems.largeBunkerBusterWarhead, "Großer Bunkerbrechender Sprengkopf")
        addItem(ModItems.nuclearWarhead, "Nuklearer Sprengkopf")
        addItem(ModItems.thermonuclearWarhead, "Thermonuklearer Sprengkopf")
        addItem(ModItems.endothermicWarhead, "Endothermischer Sprengkopf")
        addItem(ModItems.exothermicWarhead, "Exothermischer Sprengkopf")

        addItem(ModItems.smallFuelTank, "Kleiner Treibstofftank")
        addItem(ModItems.mediumFuelTank, "Mittlerer Treibstofftank")
        addItem(ModItems.largeFuelTank, "Großer Treibstofftank")

        addItem(ModItems.smallThruster, "Kleines Raketentriebwerk")
        addItem(ModItems.mediumThruster, "Mittleres Raketentriebwerk")
        addItem(ModItems.largeThruster, "Großes Raketentriebwerk")
        addItem(ModItems.lvnNuclearRocketEngine, "LV-N Atomares Raketentriebwerk")

        addItem(ModItems.satelliteBase, "Satellitenkörper")
        addItem(ModItems.highGainOpticalCamera, "Hochleistungskamera")
        addItem(ModItems.m700SurveyScanner, "M700 Oberflächenscanner")
        addItem(ModItems.radarDish, "Radarschüssel")
        addItem(ModItems.deathRay, "Todesstrahl")
        addItem(ModItems.xeniumResonator, "Xeniumresonator")

        addItem(ModItems.size10Connector, "Größe 10 Bindeglied")
        addItem(ModItems.size15Connector, "Größe 15 Bindeglied")
        addItem(ModItems.size20Connector, "Größe 20 Bindeglied")

        addItem(ModItems.hunterChopperCockpit, "Jagdschrauber Cockpit")
        addItem(ModItems.emplacementGun, "Pulskanone")
        addItem(ModItems.hunterChopperBody, "Jagdschrauber Rumpf")
        addItem(ModItems.hunterChopperTail, "Jagdschrauber Heck")
        addItem(ModItems.hunterChopperWing, "Jagdschrauber Seitentragfläche")
        addItem(ModItems.hunterChopperRotorBlades, "Jagdschrauber Rotorblätter")
        addItem(ModItems.combineScrapMetal, "Combine Stahlschrott")

        addItem(ModItems.heavyHammerHead, "Schwerer Hammerkopf")
        addItem(ModItems.heavyAxeHead, "Schwerer Axtkopf")
        addItem(ModItems.reinforcedPolymerHandle, "Verstärkter Polymergriff")

        addItem(ModItems.basicCircuitAssembly, "Schaltkreisrohling")
        addItem(ModItems.basicCircuit, "Einfacher Schaltkreis")
        addItem(ModItems.enhancedCircuit, "Erweiterter Schaltkreis")
        addItem(ModItems.advancedCircuit, "Fortgeschrittener Schaltkreis")
        addItem(ModItems.overclockedCircuit, "Übertakteter Schaltkreis")
        addItem(ModItems.highPerformanceCircuit, "Leistungsstarker Schaltkreis")
        addItem(ModItems.militaryGradeCircuitBoardTier1, "Militärische Schaltplatte (Stufe 1)")
        addItem(ModItems.militaryGradeCircuitBoardTier2, "Militärische Schaltplatte (Stufe 2)")
        addItem(ModItems.militaryGradeCircuitBoardTier3, "Militärische Schaltplatte (Stufe 3)")
        addItem(ModItems.militaryGradeCircuitBoardTier4, "Militärische Schaltplatte (Stufe 4)")
        addItem(ModItems.militaryGradeCircuitBoardTier5, "Militärische Schaltplatte (Stufe 5)")
        addItem(ModItems.militaryGradeCircuitBoardTier6, "Militärische Schaltplatte (Stufe 6)")

        addItem(ModItems.revolverMechanism, "Revolvermechanismus")
        addItem(ModItems.advancedRevolverMechanism, "Fortgeschrittener Revolvermechanismus")
        addItem(ModItems.rifleMechanism, "Gewehrmechanismus")
        addItem(ModItems.advancedRifleMechanism, "Fortgeschrittener Gewehrmechanismus")
        addItem(ModItems.launcherMechanism, "Werfermechanismus")
        addItem(ModItems.advancedLauncherMechanism, "Fortgeschrittener Werfermechanismus")
        addItem(ModItems.highTechWeaponMechanism, "High-Tech Waffenmechanismus")

        addItem(ModItems.point357MagnumPrimer, ".357 Magnumzündhütchen (x16)")
        addItem(ModItems.point44MagnumPrimer, ".44 Magnumzündhütchen (x16)")
        addItem(ModItems.smallCaliberPrimer, "Kleinkaliberzündhütchen (x24)")
        addItem(ModItems.largeCaliberPrimer, "Großkaliberzündhütchen (x8)")
        addItem(ModItems.buckshotPrimer, "Schrotzündhütchen (x8)")

        addItem(ModItems.point357MagnumCasing, ".357 Magnumhülse (x16)")
        addItem(ModItems.point44MagnumCasing, ".44 Magnumhülse (x16)")
        addItem(ModItems.smallCaliberCasing, "Kleinkaliberhülse (x24)")
        addItem(ModItems.largeCaliberCasing, "Großkaliberhülse (x8)")
        addItem(ModItems.buckshotCasing, "Schrothülse (x8)")

        addItem(ModItems.ironBulletAssembly, "Eisenpatronensatz")
        addItem(ModItems.leadBulletAssembly, "Bleipatronensatz")
        addItem(ModItems.glassBulletAssembly, "Glaspatronensatz")
        addItem(ModItems.goldBulletAssembly, "Goldpatronensatz")
        addItem(ModItems.schrabidiumBulletAssembly, "Schrabidiumpatronensatz")
        addItem(ModItems.nightmareBulletAssembly, "Nightmare-Patronensatz")
        addItem(ModItems.deshBulletAssembly, "Deshpatronensatz")
        addItem(ModItems.point44MagnumAssembly, ".44er Patronensatz")
        addItem(ModItems.nineMmAssembly, "9mm Patronensatz")
        addItem(ModItems.fivePoint56mmAssembly, "5.56mm Patronensatz")
        addItem(ModItems.point22LRAssembly, ".22 LR Patronensatz")
        addItem(ModItems.point5mmAssembly, ".5mm Patronensatz")
        addItem(ModItems.point50AEAssembly, ".50 AE Patronensatz")
        addItem(ModItems.point50BMGAssembly, ".50 BMG Patronensatz")

        addItem(ModItems.silverBulletCasing, "Kanonenhülse")
        addItem(ModItems.twelvePoint8cmStarmetalHighEnergyShell, "12,8cm Starmetal-Hochenergiegeschoss")
        addItem(ModItems.twelvePoint8cmNuclearShell, "12,8cm Atomares Geschoss")
        addItem(ModItems.twelvePoint8cmDUShell, "12.8cm DU-Geschoss")

        addItem(ModItems.cableDrum, "Kabeltrommel")
        addItemDesc(ModItems.cableDrum, "Rechtsklicke Masten um sie zu verbinden")
        addItem(ModItems.paintingOfACartoonPony, "Bild eines Cartoon Ponys")
        addItemDesc(ModItems.paintingOfACartoonPony, "Gelbes Pferd schlägt blaues Pferd, das ist eine erwiesene Tatsache!")
        addItem(ModItems.conspiracyTheory, "Verschwörungstheorie")
        addItemDesc(ModItems.conspiracyTheory, "Stahlträger können nicht Kerosin schmelzen!")
        addItem(ModItems.politicalTopic, "Politisches Thema")
        addItemDesc(ModItems.politicalTopic, "Donald Duck wird die Mauer bauen!")
        addItem(ModItems.ownOpinion, "Eigene Meinung")
        addItemDesc(ModItems.ownOpinion, "Nun ja, mir gefällt's...")

        addItem(ModItems.explosivePellets, "Explosive Pellets")
        addItemDesc(ModItems.explosivePellets, "Wird in Mehrzweckbomben verwendet:\nFür ein wenig extra Boom!")
        addItem(ModItems.leadPellets, "Schrotkugeln")
        addItem(ModItems.flechettes, "Flechets")
        addItem(ModItems.poisonGasCartridge, "Giftgaskartusche")
        addItemDesc(ModItems.poisonGasCartridge, "Wird in Mehrzweckbomben verwendet:\n*hust hust* Hilfä!")
        addItem(ModItems.magnetron, "Magnetron")
        addItem(ModItems.denseCoalCluster, "Dichter Kohlecluster")
        addItem(ModItems.burntBark, "Verbrannte Rinde")
        addItemDesc(ModItems.burntBark, "Ein Stück Rinde von einer explodierten goldenen Eiche.")
        addItem(ModItems.machineUpgradeTemplate, "Maschinenupgrade-Vorlage")

        addItem(ModItems.blankRune, "Blanke Katalysatormatrix")
        addItem(ModItems.isaRune, "Kalte Katalysatormatrix")
        addItem(ModItems.dagazRune, "Ausgeglichene Katalysatormatrix")
        addItem(ModItems.hagalazRune, "Grobe Katalysatormatrix")
        addItem(ModItems.jeraRune, "Multiplikative Katalysatormatrix")
        addItem(ModItems.thurisazRune, "Additive Katalysatormatrix")

        addItem(ModItems.burnedOutQuadSchrabidiumFuelRod, "Ausgebrannter Schrabidiumvierfachbrennstab")
        addItemDesc(ModItems.burnedOutQuadSchrabidiumFuelRod, "Ein Vierfachbrennstab der eine kleine Menge\neines seltsamen neuen Elements beinhaltet.")

        addItem(ModItems.scrap, "Schrott")
        addItem(ModItems.hotDepletedUraniumFuel, "Heißer Erschöpfter Urankernbrennstoff")
        addItem(ModItems.hotDepletedThoriumFuel, "Heißer Erschöpfter Thoriumkernbrennstoff")
        addItem(ModItems.hotDepletedPlutoniumFuel, "Heißer Erschöpfter Plutoniumkernbrennstoff")
        addItem(ModItems.hotDepletedMOXFuel, "Heißer Erschöpfter MOX-Kernbrennstoff")
        addItem(ModItems.hotDepletedSchrabidiumFuel, "Heißer Erschöpfter Schrabidiumkernbrennstoff")
        addItem(ModItems.depletedUraniumFuel, "Erschöpfter Urankernbrennstoff")
        addItem(ModItems.depletedThoriumFuel, "Erschöpfter Thoriumkernbrennstoff")
        addItem(ModItems.depletedPlutoniumFuel, "Erschöpfter Plutoniumkernbrennstoff")
        addItem(ModItems.depletedMOXFuel, "Erschöpfter MOX-Kernbrennstoff")
        addItem(ModItems.depletedSchrabidiumFuel, "Erschöpfter Schrabidiumkernbrennstoff")
        addItem(ModItems.trinitite, "Trinitit")
        addItem(ModItems.nuclearWaste, "Atommüll")
        addItem(ModItems.tinyNuclearWaste, "Kleiner Haufen Atommüll")

        addItem(ModItems.crystalHorn, "Kristallhorn")
        addItemDesc(ModItems.crystalHorn, "Ein echtes Horn.")
        addItem(ModItems.charredCrystal, "Verkohlter Kristall")
        addItemDesc(ModItems.charredCrystal, "Auch ein echtes Horn. Komisch, nicht?")

        add("item.$MODID.batteries.energy_stored", "Energie gespeichert: %s/%sHE")
        add("item.$MODID.batteries.charge_rate", "Laderate: %sHE/t")
        add("item.$MODID.batteries.discharge_rate", "Entladerate: %sHE/t")
        addItem(ModItems.battery, "Batterie")
        addItem(ModItems.redstonePowerCell, "Redstone-Energiezelle")
        addItem(ModItems.sixfoldRedstonePowerCell, "Sechsfache Redstone-Energiezelle")
        addItem(ModItems.twentyFourFoldRedstonePowerCell, "24-Fache Redstone-Energiezelle")
        addItem(ModItems.advancedBattery, "Fortgeschrittene Batterie")
        addItem(ModItems.advancedPowerCell, "Fortgeschrittene Energiezelle")
        addItem(ModItems.quadrupleAdvancedPowerCell, "Vierfache Fortgeschrittene Energiezelle")
        addItem(ModItems.twelveFoldAdvancedPowerCell, "Zwölffache Fortgeschrittene Energiezelle")
        addItem(ModItems.lithiumBattery, "Lithium-Ionen-Batterie")
        addItem(ModItems.lithiumPowerCell, "Lithium-Ionen-Energiezelle")
        addItem(ModItems.tripleLithiumPowerCell, "Dreifache Lithium-Ionen-Energiezelle")
        addItem(ModItems.sixfoldLithiumPowerCell, "Sechsfache Lithium-Ionen-Energiezelle")
        addItem(ModItems.schrabidiumBattery, "Schrabidiumbatterie")
        addItem(ModItems.schrabidiumPowerCell, "Schrabidium-Energiezelle")
        addItem(ModItems.doubleSchrabidiumPowerCell, "Doppelte Schrabidium-Energiezelle")
        addItem(ModItems.quadrupleSchrabidiumPowerCell, "Vierfache Schrabidium-Energiezelle")
        addItem(ModItems.sparkBattery, "Spark-Batterie")
        addItem(ModItems.offBrandSparkBattery, "Billige Spark-Batterie-Nachmache")
        addItem(ModItems.sparkPowerCell, "Spark-Energiezelle")
        addItem(ModItems.sparkArcaneCarBattery, "Spark-Arkane Autobatterie")
        addItem(ModItems.sparkArcaneEnergyStorageArray, "Spark-Arkane Energiespeichermatrix")
        addItem(ModItems.sparkArcaneMassEnergyVoid, "Spark-Arkane Massenenergie Speicherleere")
        addItem(ModItems.sparkArcaneDiracSea, "Spark-Arkanes Dirac'sches Meer")
        addItem(ModItems.sparkSolidSpaceTimeCrystal, "Spark Solider Raumzeit Kristall")
        addItem(ModItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit, "Spark Lächerliche Physikmissachtende Energiespeichereinheit")
        addItem(ModItems.infiniteBattery, "Unendliche Batterie")
        addItem(ModItems.singleUseBattery, "Einwegbatterie")
        addItem(ModItems.largeSingleUseBattery, "Große Einwegbatterie")
        addItem(ModItems.potatoBattery, "Kartoffelbatterie")
        addItem(ModItems.steamPoweredEnergyStorageTank, "Dampfbetriebener Energiespeichertank")
        addItem(ModItems.largeSteamPoweredEnergyStorageTank, "Großer Dampfbetriebener Energiespeichertank")

        addItem(ModItems.stoneFlatStamp, "Flacher Stempel (Stein)")
        addItem(ModItems.stonePlateStamp, "Plattenstempel (Stein)")
        addItem(ModItems.stoneWireStamp, "Kabelstempel (Stein)")
        addItem(ModItems.stoneCircuitStamp, "Schaltkreisstempel (Stein)")
        addItem(ModItems.ironFlatStamp, "Flacher Stempel (Eisen)")
        addItem(ModItems.ironPlateStamp, "Plattenstempel (Eisen)")
        addItem(ModItems.ironWireStamp, "Kabelstempel (Eisen)")
        addItem(ModItems.ironCircuitStamp, "Schaltkreisstempel (Eisen)")
        addItem(ModItems.steelFlatStamp, "Flacher Stempel (Stahl)")
        addItem(ModItems.steelPlateStamp, "Plattenstempel (Stahl)")
        addItem(ModItems.steelWireStamp, "Kabelstempel (Stahl)")
        addItem(ModItems.steelCircuitStamp, "Schaltkreisstempel (Stahl)")
        addItem(ModItems.titaniumFlatStamp, "Flacher Stempel (Titan)")
        addItem(ModItems.titaniumPlateStamp, "Plattenstempel (Titan)")
        addItem(ModItems.titaniumWireStamp, "Kabelstempel (Titan)")
        addItem(ModItems.titaniumCircuitStamp, "Schaltkreisstempel (Titan)")
        addItem(ModItems.obsidianFlatStamp, "Flacher Stempel (Obsidian)")
        addItem(ModItems.obsidianPlateStamp, "Plattenstempel (Obsidian)")
        addItem(ModItems.obsidianWireStamp, "Kabelstempel (Obsidian)")
        addItem(ModItems.obsidianCircuitStamp, "Schaltkreisstempel (Obsidian)")
        addItem(ModItems.schrabidiumFlatStamp, "Flacher Stempel (Schrabidium)")
        addItem(ModItems.schrabidiumPlateStamp, "Plattenstempel (Schrabidium)")
        addItem(ModItems.schrabidiumWireStamp, "Kabelstempel (Schrabidium)")
        addItem(ModItems.schrabidiumCircuitStamp, "Schaltkreisstempel (Schrabidium)")

        addItem(ModItems.aluminiumShredderBlade, "Aluminiumsägeblatt")
        addItem(ModItems.goldShredderBlade, "Goldsägeblatt")
        addItem(ModItems.ironShredderBlade, "Eisensägeblatt")
        addItem(ModItems.steelShredderBlade, "Stahlsägeblatt")
        addItem(ModItems.titaniumShredderBlade, "Titansägeblatt")
        addItem(ModItems.advancedAlloyShredderBlade, "Fortgeschrittenes Legierungssägeblatt")
        addItem(ModItems.combineSteelShredderBlade, "Combine Stahlsägeblatt")
        addItem(ModItems.schrabidiumShredderBlade, "Schrabidiumsägeblatt")
        addItem(ModItems.deshShredderBlade, "Deshsägeblatt")

        addItem(ModItems.machineTemplateFolder, "Produktionsvorlagen-Zeichenmappe")
        addItemDesc(ModItems.machineTemplateFolder,
            "Maschinenvorlagen: Papier + Farbstoff\n" +
                    "Flüssigkeit-IDs: Eisenplatte + Farbstoff\n" +
                    "Pressstempel: Flacher Stempel\n" +
                    "Sirenentracks: Isolator + Stahlplatte"
        )

        add("item.$MODID.siren_tracks.siren_track", "Sirenentrack")
        add("item.$MODID.siren_tracks.type_loop", "Typ: Endlosschleife")
        add("item.$MODID.siren_tracks.type_once", "Typ: Einmal abspielen")
        add("item.$MODID.siren_tracks.range", "Reichweite: %s Meter")
        addItem(ModItems.sirenTrackHatchSiren, "Hatch Siren")
        addItem(ModItems.sirenTrackAutopilotDisconnected, "Autopilot Disconnected")
        addItem(ModItems.sirenTrackAMSSiren, "AMS Siren")
        addItem(ModItems.sirenTrackBlastDoorAlarm, "Blast Door Alarm")
        addItem(ModItems.sirenTrackAPCSiren, "APC Siren")
        addItem(ModItems.sirenTrackKlaxon, "Klaxon")
        addItem(ModItems.sirenTrackVaultDoorAlarm, "Vault Door Alarm")
        addItem(ModItems.sirenTrackSecurityAlert, "Security Alert")
        addItem(ModItems.sirenTrackStandardSiren, "Standard Siren")
        addItem(ModItems.sirenTrackClassicSiren, "Classic Siren")
        addItem(ModItems.sirenTrackBankAlarm, "Bank Alarm")
        addItem(ModItems.sirenTrackBeepSiren, "Beep Siren")
        addItem(ModItems.sirenTrackContainerAlarm, "Container Alarm")
        addItem(ModItems.sirenTrackSweepSiren, "Sweep Siren")
        addItem(ModItems.sirenTrackMissileSiloSiren, "Missile Silo Siren")
        addItem(ModItems.sirenTrackAirRaidSiren, "Air Raid Siren")
        addItem(ModItems.sirenTrackNostromoSelfDestruct, "Nostromo Self Destruct")
        addItem(ModItems.sirenTrackEASAlarmScreech, "EAS Alarm Screech")
        addItem(ModItems.sirenTrackAPCPass, "APC Pass")
        addItem(ModItems.sirenTrackRazortrainHorn, "Razortrain Horn")

        addItem(ModItems.assemblyTemplate, "Fertigungsvorlage: %s")
        add("info.template.in", "Inputs:")
        add("info.template.out", "Output:")
        add("info.template.time", "Produktionszeit:")
        add("info.template.seconds", "Sekunden")

        run {
            val usedInLittleBoy = "Wird gebraucht für:\nLittle Boy"
            addItem(ModItems.neutronShieldingLittleBoy, "Neutronenschild")
            addItemDesc(ModItems.neutronShieldingLittleBoy, usedInLittleBoy)
            addItem(ModItems.subcriticalUraniumTarget, "Unterkritischer U235-Hohlkörper")
            addItemDesc(ModItems.subcriticalUraniumTarget, usedInLittleBoy)
            addItem(ModItems.uraniumProjectile, "U235 Geschoss")
            addItemDesc(ModItems.uraniumProjectile, usedInLittleBoy)
            addItem(ModItems.propellantLittleBoy, "Treibladung")
            addItemDesc(ModItems.propellantLittleBoy, usedInLittleBoy)
            addItem(ModItems.bombIgniterLittleBoy, "Zünder")
            addItemDesc(ModItems.bombIgniterLittleBoy, usedInLittleBoy)
        }
        addItem(ModItems.bundleOfImplosionPropellant, "Implosions-Treibladung")
        addItemDesc(ModItems.bundleOfImplosionPropellant, "Wird gebraucht für:\nFat Man\nIvy Mike\nTsar Bombe")
        addItem(ModItems.bombIgniterFatMan, "Zünder")
        addItemDesc(ModItems.bombIgniterFatMan, "Wird gebraucht für Fat Man")
        addItem(ModItems.plutoniumCore, "Plutoniumkern")
        addItemDesc(ModItems.plutoniumCore, "Wird gebraucht für:\nFat Man\nIvy Mike\nTsar Bombe")
        addItem(ModItems.detonator, "Fernzünder")
        addItemDesc(ModItems.detonator, "Shift-Rechtsklick auf einen Sprengstoff um die Position zu setzen,\nRechtsklick um zu sprengen!")
        val detonatorDescriptionId = ModItems.detonator.get().descriptionId
        add("$detonatorDescriptionId.tooltip_no_position_set", "Keine Position gesetzt!")
        add("$detonatorDescriptionId.position_set", "Position gesetzt!")
        add("$detonatorDescriptionId.error_position_not_set", "Die Position wurde noch nicht gesetzt!")
        add("$detonatorDescriptionId.error_position_not_loaded", "Das Ziel ist momentan nicht in der Welt geladen!")
        add("$detonatorDescriptionId.error_not_explosive", "Das Ziel ist kein gültiger Sprengstoff!")
        add("$detonatorDescriptionId.error_invalid_tile_entity", "Serverfehler: Die BlockEntity des Ziels ist ungültig!")
        add("$detonatorDescriptionId.error_missing_components", "Der Sprengstoff ist unvollständig!")
        add("$detonatorDescriptionId.error_detonation_prohibited", "Die Sprengung wurde aufgehalten!")
        add("$detonatorDescriptionId.error_unknown", "Ein unbekannter Fehler ist während der Sprengung aufgetreten")
        add("$detonatorDescriptionId.detonation_successful", "Sprengung!")
        addItem(ModItems.littleBoyKit, "Little Boy Kit")
        addItem(ModItems.fatManKit, "Fat Man Kit")

        addItem(ModItems.oilDetector, "Ölvorkommen-Detektor")
        addItemDesc(ModItems.oilDetector, "Rechtsklick um nach Öl zu suchen.\nDetektor findet nur größere Vorkommen.")
        add(ModItems.oilDetector.get().descriptionId + ".below", "Ölvorkommen direkt untertage!")
        add(ModItems.oilDetector.get().descriptionId + ".near", "Ölvorkommen in der Nähe")
        add(ModItems.oilDetector.get().descriptionId + ".no_oil", "Kein Öl gefunden")
        addItem(ModItems.geigerCounter, "Mobiler Geigerzähler")

        addItem(ModItems.ivBag, "Infusionsbeutel")
        addItem(ModItems.bloodBag, "Blutbeutel")
        addItem(ModItems.emptyExperienceBag, "Leerer Erfahrungsbeutel")
        addItem(ModItems.experienceBag, "Erfahrungsbeutel")
        addItem(ModItems.radAway, "RadAway")
        addItem(ModItems.strongRadAway, "Starkes RadAway")
        addItem(ModItems.eliteRadAway, "Elite-RadAway")

        addItem(ModItems.creativeNuclearExplosionSpawner, "Atomexplosionserzeuger")
        add("creative_nuclear_explosion_spawner.$MODID.strength", "Stärke")
        add("creative_nuclear_explosion_spawner.$MODID.muted", "Stumm")
        add("creative_nuclear_explosion_spawner.$MODID.has_fallout", "Mit Fallout")
        add("creative_nuclear_explosion_spawner.$MODID.extra_fallout", "Extra Fallout")
        add("creative_nuclear_explosion_spawner.$MODID.position", "Position")
        add("creative_nuclear_explosion_spawner.$MODID.cancel", "Abbrechen")
        add("creative_nuclear_explosion_spawner.$MODID.start", "Starten")
        add("creative_nuclear_explosion_spawner.$MODID.error_strength", "Kann den Stärke-Wert nicht lesen")
        add("creative_nuclear_explosion_spawner.$MODID.error_extra_fallout", "Kann den Extra-Fallout-Wert nicht lesen")
        add("creative_nuclear_explosion_spawner.$MODID.error_insufficient_permission", "Kann den Atomexplosionserzeuger nicht benutzen: Unzureichende Berechtigungen")

        add("energy.$MODID", "Energie")

        addEntityType(EntityTypes.nukeExplosionEntity, "Nukleare Explosion")
        addEntityType(EntityTypes.nukeCloudEntity, "Atompilz")
        addEntityType(EntityTypes.falloutRainEntity, "Fallout-Regen")
        addEntityTypeWithSpawnEgg(EntityTypes.nuclearCreeper, "Nuklearer Creeper")

        addMenuType(MenuTypes.sirenMenu, "Sirene")
        addMenuType(MenuTypes.safeMenu, "Panzerschrank")
        addMenuType(MenuTypes.anvilMenu, "Stufe %s Amboss")
        add("${AnvilScreen.CONTAINER_TRANSLATION}.inputs", "Benötigt:")
        add("${AnvilScreen.CONTAINER_TRANSLATION}.outputs", "Ergibt:")
        addMenuType(MenuTypes.steamPressMenu, "Dampfpresse")
        addMenuType(MenuTypes.blastFurnaceMenu, "Hochofen")
        addMenuType(MenuTypes.combustionGeneratorMenu, "Verbrennungsgenerator")
        addMenuType(MenuTypes.electricFurnaceMenu, "Elektrischer Ofen")
        addMenuType(MenuTypes.shredderMenu, "Brecher")
        addMenuType(MenuTypes.assemblerMenu, "Fertigungsmaschine")

        addMenuType(MenuTypes.littleBoyMenu, "Little Boy")
        addMenuType(MenuTypes.fatManMenu, "Fat Man")

        addSound(SoundEvents.sirenTrackHatchSiren, "Sirene läuft: Hatch Siren")
        addSound(SoundEvents.sirenTrackAutopilotDisconnected, "Sirene läuft: Autopilot Disconnected")
        addSound(SoundEvents.sirenTrackAMSSiren, "Sirene läuft: AMS Siren")
        addSound(SoundEvents.sirenTrackBlastDoorAlarm, "Sirene läuft: Blast Door Alarm")
        addSound(SoundEvents.sirenTrackAPCSiren, "Sirene läuft: APC Siren")
        addSound(SoundEvents.sirenTrackKlaxon, "Sirene läuft: Klaxon")
        addSound(SoundEvents.sirenTrackVaultDoorAlarm, "Sirene läuft: Vault Door Alarm")
        addSound(SoundEvents.sirenTrackSecurityAlert, "Sirene läuft: Security Alert")
        addSound(SoundEvents.sirenTrackStandardSiren, "Sirene läuft: Standard Siren")
        addSound(SoundEvents.sirenTrackClassicSiren, "Sirene läuft: Classic Siren")
        addSound(SoundEvents.sirenTrackBankAlarm, "Sirene läuft: Bank Alarm")
        addSound(SoundEvents.sirenTrackBeepSiren, "Sirene läuft: Beep Siren")
        addSound(SoundEvents.sirenTrackContainerAlarm, "Sirene läuft: Container Alarm")
        addSound(SoundEvents.sirenTrackSweepSiren, "Sirene läuft: Sweep Siren")
        addSound(SoundEvents.sirenTrackMissileSiloSiren, "Sirene läuft: Missile Silo Siren")
        addSound(SoundEvents.sirenTrackAirRaidSiren, "Sirene läuft: Air Raid Siren")
        addSound(SoundEvents.sirenTrackNostromoSelfDestruct, "Sirene läuft: Nostromo Self Destruct")
        addSound(SoundEvents.sirenTrackEASAlarmScreech, "Sirene läuft: EAS Alarm Screech")
        addSound(SoundEvents.sirenTrackAPCPass, "Sirene läuft: APC Pass")
        addSound(SoundEvents.sirenTrackRazortrainHorn, "Sirene läuft: Razortrain Horn")
        addSound(SoundEvents.anvilFall, "Amboss klescht")
        addSound(SoundEvents.pressOperate, "Presse stampft")
        addSound(SoundEvents.inject, "Nadel injiziert")
        addSound(SoundEvents.emptyIVBag, "Flüssigkeit infusioniert")
        addSound(SoundEvents.randomBleep, "Gerät piepst")
        addSound(SoundEvents.randomBoop, "Gerät boopt")
        addSound(SoundEvents.randomUnpack, "Gegenstand ausgepackt")
        add("subtitle.$MODID.geiger.click", "Geigerzähler klickt")
        addSound(SoundEvents.miniNukeExplosion, "Miniatombombe explodiert")

        addDamageSource(DamageSources.extractBlood, "%1\$s hat zu viel Lebensessenz extrahiert", "%1\$s hat versucht, schön-verpackten Lebenssaft für %2\$s zu hinterlassen")
        addDamageSource(DamageSources.radiation, "%1\$s starb an Strahlenvergiftung", "%1\$s fiel während des Kampfes mit %2\$s der Strahlenkrankheit zum Opfer")
        addDamageSource(DamageSources.nuclearBlast, "%1\$s wurde von einer Atomexplosion weggeblasen", "%1\$s wurde während des Kampfes mit %2\$s atomisiert")
        addDamageSource(DamageSources.murkyAnvil, "%1\$s UNDEFINIERT", "%1\$s UNDEFINIERT beim Versuch %2\$s zu entkommen")

        add("geiger.title", "GEIGERZÄHLER")
        add("geiger.chunkRadiation", "Chunk-Strahlung:")
        add("geiger.totalEnvironmentRadiation", "Gesamte Umgebungsstrahlung:")
        add("geiger.playerIrradiation", "Spieler-Verstrahlung:")
        add("geiger.playerResistance", "Strahlungsresistenz:")

        add("jei.$MODID.category.smithing", "Schmiederezepte")
        add("jei.$MODID.category.smithing.tier", "Mindeststufe: %s")
        add("jei.$MODID.category.constructing", "Konstruktionsrezepe")
        add("jei.$MODID.category.constructing.tier", "Mindeststufe: %s")
        add("jei.$MODID.category.constructing.tier_range", "Stufenbereich: %s..%s")
        add("jei.$MODID.category.constructing.chance", "Wahrscheinlichkeit:")
        add("jei.$MODID.category.pressing", "Pressrezepte")
        add("jei.$MODID.category.pressing.experience", "%s EP")
        add("jei.$MODID.category.blasting", "Hochofenrezepte")
        add("jei.$MODID.category.blasting.experience", "%s EP")
        add("jei.$MODID.category.template_folder_results", "Vorlagen-Zeichenmappe")
        add("jei.$MODID.category.shredding", "Zerkleinerungsrezepte")
    }

    private fun addMaterials() {
        val mat = Materials

        addMaterial(mat.coal, "Kohle")
        addMaterial(mat.iron, "Eisen")
        addMaterial(mat.copper, "Kupfer")
        addMaterial(mat.gold, "Gold")
        addMaterial(mat.redstone, "Redstone")
        addMaterial(mat.emerald, "Smaragd")
        addMaterial(mat.lazuli, "Lapis Lazuli")
        addMaterial(mat.diamond, "Diamant")

        addMaterial(mat.naturalUranium, "Uran")
        addMaterial(mat.uranium233, "U233")
        addMaterial(mat.uranium235, "U235")
        addMaterial(mat.uranium238, "U238")
        addMaterial(mat.thorium, "Thorium")
        addMaterial(mat.naturalPlutonium, "Plutonium")
        addMaterial(mat.plutonium238, "Pu238")
        addMaterial(mat.plutonium239, "Pu239")
        addMaterial(mat.plutonium240, "Pu240")
        addMaterial(mat.neptunium, "Neptunium")
        addMaterial(mat.polonium, "Polonium")
        addMaterial(mat.titanium, "Titan")
        addMaterial(mat.redCopper, "Rotes Kupfer")
        addMaterial(mat.advancedAlloy, "Fortgeschrittene Legierung")
        addMaterial(mat.tungsten, "Wolfram")
        addMaterial(mat.magnetizedTungsten, "Magnetisiertes Wolfram")
        addMaterial(mat.aluminium, "Aluminium")
        addMaterial(mat.steel, "Stahl")
        addMaterial(mat.lead, "Blei")
        addMaterial(mat.beryllium, "Beryllium")
        addMaterial(mat.cobalt, "Kobalt")
        addMaterial(mat.highSpeedSteel, "Schnellarbeitsstahl")
        addMaterial(mat.polymer, "Polymer")
        addMaterial(mat.schraranium, "Schraranium")
        addMaterial(mat.schrabidium, "Schrabidium")
        addMaterial(mat.solinium, "Solinium")
        addMaterial(mat.combineSteel, "Combine Stahl")
        addMaterial(mat.uraniumFuel, "Urankernbrennstoff")
        addMaterial(mat.thoriumFuel, "Thoriumkernbrennstoff")
        addMaterial(mat.plutoniumFuel, "Plutoniumkernbrennstoff")
        addMaterial(mat.moxFuel, "MOX-Kernbrennstoff")
        addMaterial(mat.schrabidiumFuel, "Schrabidiumkernbrennstoff")
        addMaterial(mat.hesFuel, "Stark Angereichertes Schrabidium")
        addMaterial(mat.lesFuel, "Schwach Angereichertes Schrabidium")
        addMaterial(mat.australium, "Australium")
        addMaterial(mat.weidanium, "Weidanium")
        addMaterial(mat.reiium, "Reiium")
        addMaterial(mat.unobtainium, "Unobtainium")
        addMaterial(mat.daffergon, "Daffergon")
        addMaterial(mat.verticium, "Verticium")
        addMaterial(mat.lanthanum, "Lanthan")
        addMaterial(mat.actinium, "Actinium")
        addMaterial(mat.desh, "Desh")
        addMaterial(mat.starmetal, "Starmetal")
        addMaterial(mat.saturnite, "Saturnit")
        addMaterial(mat.euphemium, "Euphemium")
        addMaterial(mat.dineutronium, "Dineutronium")
        addMaterial(mat.electronium, "Elektronium")
        addMaterial(mat.lignite, "Braunkohle")
        addMaterial(mat.sulfur, "Schwefel")
        addMaterial(mat.niter, "Salpeter")
        addMaterial(mat.fluorite, "Fluorit")
        addMaterial(mat.asbestos, "Asbest")
        addMaterial(mat.lithium, "Lithium")
    }

    override val spawnEggSuffix = "-Spawn-Ei"
    override val spawnEggEntityStringWordSeparator = '-'

    override val oreFormat = "%serz"
    override val deepOreFormat = "Tiefenschiefer-%serz"
    override val blockFormat = "%sblock"
    override val rawFormat = "Rohes %s"
    override val ingotFormat = "%sbarren"
    override val nuggetFormat = "%sklumpen"
    override val crystalsFormat = "%skristalle"
    override val powderFormat = "%spulver"
    override val plateFormat = "%splatte"
    override val wireFormat = "%sdraht"
}
