package at.martinthedragon.nucleartech.datagen.localisation

import at.martinthedragon.nucleartech.LangKeys
import at.martinthedragon.nucleartech.Materials
import at.martinthedragon.nucleartech.SoundEvents
import at.martinthedragon.nucleartech.TranslationKey
import at.martinthedragon.nucleartech.block.NTechBlocks
import at.martinthedragon.nucleartech.datagen.NuclearLanguageProviders
import at.martinthedragon.nucleartech.entity.EntityTypes
import at.martinthedragon.nucleartech.entity.attribute.Attributes
import at.martinthedragon.nucleartech.fluid.NTechFluids
import at.martinthedragon.nucleartech.item.NTechItems
import at.martinthedragon.nucleartech.menu.MenuTypes
import at.martinthedragon.nucleartech.world.DamageSources
import net.minecraft.data.DataGenerator

class EnUsLanguageProvider(dataGenerator: DataGenerator) : NuclearLanguageProvider(dataGenerator, NuclearLanguageProviders.EN_US) {
    override fun validate() {
        val additionalLangKeys = LangKeys.javaClass.declaredFields.mapNotNull { it.trySetAccessible(); it.get(LangKeys) as? String }.filter(TranslationKey::isValidKey)
        if (!translations.keys.containsAll(additionalLangKeys)) {
            val missingLangKeys = additionalLangKeys subtract translations.keys
            val errorMessage = StringBuilder().appendLine("The following additional translation keys from LangKeys are not added to the translation definition:")
            for (missing in missingLangKeys) errorMessage.appendLine(missing.prependIndent())
            throw IllegalStateException(errorMessage.toString())
        }

        NuclearLanguageProviders.keys = translations.keys.toSet()
        NuclearLanguageProviders.materialTranslations = materialTranslations.toMap()
    }

    override fun translate() {
        add("itemGroup.${MODID}_parts", "NTM Resources and Parts")
        add("itemGroup.${MODID}_items", "NTM Machine Items and Fuel")
        add("itemGroup.${MODID}_templates", "NTM Templates")
        add("itemGroup.${MODID}_blocks", "NTM Ores and Blocks")
        add("itemGroup.${MODID}_machines", "NTM Machines")
        add("itemGroup.${MODID}_bombs", "NTM Bombs")
        add("itemGroup.${MODID}_rocketry", "NTM Missiles and Satellites")
        add("itemGroup.${MODID}_consumables", "NTM Consumables and Gear")
        add("itemGroup.${MODID}_miscellaneous", "NTM Miscellaneous Items")

        addMaterials()

        addBlock(NTechBlocks.scorchedUraniumOre, "Scorched Uranium Ore")
        addBlock(NTechBlocks.thoriumOre, "Thorium Ore")
        addBlock(NTechBlocks.oilDeposit, "Oil Deposit")
        addBlockDesc(NTechBlocks.oilDeposit, "You weren't supposed to mine that.\nCome on, get a derrick you doofus.")
        addBlock(NTechBlocks.emptyOilDeposit, "Empty Oil Deposit")
        addBlock(NTechBlocks.oilSand, "Oil Sand")
        addBlock(NTechBlocks.australianOre, "Australian Ore")
        addBlockDesc(NTechBlocks.australianOre, "Australium Ore")
        addBlock(NTechBlocks.weidite, "Weidite")
        addBlockDesc(NTechBlocks.weidite, "Weidanium Ore")
        addBlock(NTechBlocks.reiite, "Reiite")
        addBlockDesc(NTechBlocks.reiite, "Reiium Ore")
        addBlock(NTechBlocks.brightblendeOre, "Brightblende Ore")
        addBlockDesc(NTechBlocks.brightblendeOre, "Unobtainium Ore")
        addBlock(NTechBlocks.dellite, "Dellite")
        addBlockDesc(NTechBlocks.dellite, "Daffergon Ore")
        addBlock(NTechBlocks.dollarGreenMineral, "Dollar Green Mineral")
        addBlockDesc(NTechBlocks.dollarGreenMineral, "Verticium Ore")
        addBlock(NTechBlocks.rareEarthOre, "Rare Earth Ore")
        addBlock(NTechBlocks.netherUraniumOre, "Nether Uranium Ore")
        addBlock(NTechBlocks.scorchedNetherUraniumOre, "Scorched Nether Uranium Ore")
        addBlock(NTechBlocks.netherPlutoniumOre, "Nether Plutonium Ore")
        addBlock(NTechBlocks.netherTungstenOre, "Nether Tungsten Ore")
        addBlock(NTechBlocks.netherSulfurOre, "Nether Sulfur Ore")
        addBlock(NTechBlocks.netherPhosphorusOre, "Nether Phosphorus Ore")
        addBlock(NTechBlocks.netherSchrabidiumOre, "Nether Schrabidium Ore")
        addBlock(NTechBlocks.meteorUraniumOre, "Meteor Uranium Ore")
        addBlock(NTechBlocks.meteorThoriumOre, "Meteor Thorium Ore")
        addBlock(NTechBlocks.meteorTitaniumOre, "Meteor Titanium Ore")
        addBlock(NTechBlocks.meteorSulfurOre, "Meteor Sulfur Ore")
        addBlock(NTechBlocks.meteorCopperOre, "Meteor Copper Ore")
        addBlock(NTechBlocks.meteorTungstenOre, "Meteor Tungsten Ore")
        addBlock(NTechBlocks.meteorAluminiumOre, "Meteor Aluminium Ore")
        addBlock(NTechBlocks.meteorLeadOre, "Meteor Lead Ore")
        addBlock(NTechBlocks.meteorLithiumOre, "Meteor Lithium Ore")
        addBlock(NTechBlocks.starmetalOre, "Starmetal Ore")
        addBlock(NTechBlocks.trixite, "Trixite")

        addBlock(NTechBlocks.scorchedDeepslateUraniumOre, "Scorched Deepslate Uranium Ore")
        addBlock(NTechBlocks.deepslateOilDeposit, "Deepslate Oil Deposit")
        addBlockDesc(NTechBlocks.deepslateOilDeposit, "You got this deep and still\ndon't know what to do? How?!")
        addBlock(NTechBlocks.emptyDeepslateOilDeposit, "Empty Deepslate Oil Deposit")
        addBlock(NTechBlocks.deepslateAustralianOre, "Deepslate Australian Ore")
        addBlockDesc(NTechBlocks.deepslateAustralianOre, "Australium Ore")
        addBlock(NTechBlocks.deepslateRareEarthOre, "Deepslate Rare Earth Ore")

        addBlock(NTechBlocks.whitePhosphorusBlock, "Block of White Phosphorus")
        addBlock(NTechBlocks.redPhosphorusBlock, "Block of Red Phosphorus")
        addBlock(NTechBlocks.yellowcakeBlock, "Block of Yellowcake")
        addBlock(NTechBlocks.scrapBlock, "Block of Scrap")
        addBlock(NTechBlocks.electricalScrapBlock, "Block of Electrical Scrap")
        addBlock(NTechBlocks.insulatorRoll, "Insulator Roll")
        addBlock(NTechBlocks.fiberglassRoll, "Fiberglass Roll")
        addBlock(NTechBlocks.trinititeBlock, "Block of Trinitite")
        addBlock(NTechBlocks.nuclearWasteBlock, "Block of Nuclear Waste")
        addBlock(NTechBlocks.schrabidiumCluster, "Schrabidium Cluster")
        addBlock(NTechBlocks.euphemiumEtchedSchrabidiumCluster, "Euphemium Etched Schrabidium Cluster")
        addBlock(NTechBlocks.deshReinforcedBlock, "Block of Reinforced Desh")

        addBlock(NTechBlocks.titaniumDecoBlock, "Titanium Deco Block")
        addBlock(NTechBlocks.redCopperDecoBlock, "Red Copper Deco Block")
        addBlock(NTechBlocks.tungstenDecoBlock, "Tungsten Deco Block")
        addBlock(NTechBlocks.aluminiumDecoBlock, "Aluminium Deco Block")
        addBlock(NTechBlocks.steelDecoBlock, "Steel Deco Block")
        addBlock(NTechBlocks.leadDecoBlock, "Lead Deco Block")
        addBlock(NTechBlocks.berylliumDecoBlock, "Beryllium Deco Block")
        addBlock(NTechBlocks.asbestosRoof, "Asbestos Roof")
        addBlock(NTechBlocks.hazmatBlock, "Hazmat Block")
        addBlock(NTechBlocks.steelBeam, "Steel Beam")

        addBlock(NTechBlocks.glowingMushroom, "Glowing Mushroom")
        addBlock(NTechBlocks.glowingMushroomBlock, "Glowing Mushroom Block")
        addBlock(NTechBlocks.glowingMushroomStem, "Glowing Mushroom Stem")
        addBlock(NTechBlocks.deadGrass, "Dead Grass")
        addBlock(NTechBlocks.glowingMycelium, "Glowing Mycelium")
        addBlock(NTechBlocks.trinitite, "Trinitite Ore")
        addBlock(NTechBlocks.redTrinitite, "Red Trinitite Ore")
        addBlock(NTechBlocks.charredLog, "Charred Log")
        addBlock(NTechBlocks.charredPlanks, "Charred Planks")

        addBlock(NTechBlocks.slakedSellafite, "Slaked Sellafite")
        addBlock(NTechBlocks.sellafite, "Sellafite")
        addBlock(NTechBlocks.hotSellafite, "Hot Sellafite")
        addBlock(NTechBlocks.boilingSellafite, "Boiling Sellafite")
        addBlock(NTechBlocks.blazingSellafite, "Blazing Sellafite")
        addBlock(NTechBlocks.infernalSellafite, "Infernal Sellafite")
        addBlock(NTechBlocks.sellafiteCorium, "Sellafite-Corium")

        addBlock(NTechBlocks.siren, "Siren")
        addBlock(NTechBlocks.safe, "Safe")
        addBlock(NTechBlocks.steamPressBase, "Steam Press")
        addBlock(NTechBlocks.steamPressFrame, "Steam Press")
        addBlock(NTechBlocks.steamPressTop, "Steam Press")
        addBlock(NTechBlocks.blastFurnace, "Blast Furnace")
        addBlock(NTechBlocks.combustionGenerator, "Combustion Generator")
        addBlock(NTechBlocks.electricFurnace, "Electric Furnace")
        addBlock(NTechBlocks.shredder, "Shredder")
        addBlock(NTechBlocks.assembler, "Assembler")
        addBlock(NTechBlocks.chemPlant, "Chemical Plant")
        addBlock(NTechBlocks.ironAnvil, "Iron Anvil")
        addBlock(NTechBlocks.leadAnvil, "Lead Anvil")
        addBlock(NTechBlocks.steelAnvil, "Steel Anvil")
        addBlock(NTechBlocks.meteoriteAnvil, "Meteorite Anvil")
        addBlock(NTechBlocks.starmetalAnvil, "Starmetal Anvil")
        addBlock(NTechBlocks.ferrouraniumAnvil, "Ferrouranium Anvil")
        addBlock(NTechBlocks.bismuthAnvil, "Bismuth Anvil")
        addBlock(NTechBlocks.schrabidateAnvil, "Ferric Schrabidate Anvil")
        addBlock(NTechBlocks.dineutroniumAnvil, "Dineutronium Anvil")
        addBlock(NTechBlocks.murkyAnvil, "Murky Anvil")
        addBlock(NTechBlocks.coatedCable, "Coated Red Copper Cable")

        addBlock(NTechBlocks.littleBoy, "Little Boy")
        addBlock(NTechBlocks.fatMan, "Fat Man")

        addBlock(NTechBlocks.launchPad, "Missile Launch Pad")
        addBlock(NTechBlocks.launchPadPart, "Missile Launch Pad")

        addBlock(NTechBlocks.genericMultiBlockPart, "Multi Block Structure Part")
        addBlock(NTechBlocks.genericMultiBlockPort, "Multi Block Structure Port")

        addBlock(NTechFluids.uraniumHexafluoride.block, "Uranium Hexafluoride")

        addItem(NTechItems.rawThorium, "Raw Thorium")
        addItem(NTechItems.rawRareEarth, "Raw Rare Earth")
        addItem(NTechItems.rawTrixite, "Raw Trixite")

        addItemDesc(NTechItems.neptuniumIngot, "That one's my favorite!")
        addItemDesc(NTechItems.tantaliumIngot, "'Tantalum'")
        addItemDesc(NTechItems.tantaliumNugget, "'Tantalum'")
        addItemDesc(NTechItems.schraraniumIngot, "Made from uranium in a schrabidium transmutator")
        addItemDesc(NTechItems.combineSteelIngot, "*insert Civil Protection reference here*")
        addItemDesc(NTechItems.ghiorsium336Ingot, "Seaborgium's colleague.")
        addItemDesc(NTechItems.ghiorsium336Nugget, "Seaborgium's colleague.")
        addItem(NTechItems.lanthanumIngot, "Semi-Stable Lanthanum Ingot")
        addItemDesc(NTechItems.euphemiumIngot, "A very special and yet strange element")
        addItem(NTechItems.whitePhosphorusIngot, "White Phosphorus Bar")

        addItem(NTechItems.semtexBar, "Semtex Bar")
        addItemDesc(
            NTechItems.semtexBar,
            "Semtex H Plastic Explosive\n" +
                    "Performant explosive for many applications.\n" +
                    "Edible"
        )

        addItem(NTechItems.lithiumCube, "Lithium Cube")
        addItem(NTechItems.solidFuelCube, "Solid Fuel Cube")
        addItem(NTechItems.solidRocketFuelCube, "Solid Rocket Fuel Cube")

        addItem(NTechItems.fiberglassSheet, "Fiberglass Sheet")
        addItemDesc(NTechItems.fiberglassSheet, "High in fiber, high in glass. Everything the body needs.")
        addItem(NTechItems.asbestosSheet, "Asbestos Sheet")
        addItemDesc(NTechItems.asbestosSheet, "§o„Filled with life, self-doubt and asbestos. That comes with the air.“")

        addItem(NTechItems.mercuryDroplet, "Mercury Droplet")
        addItem(NTechItems.mercuryBottle, "Mercury Bottle")

        addItem(NTechItems.coke, "Coke")
        addItem(NTechItems.lignite, "Lignite")
        addItem(NTechItems.ligniteBriquette, "Lignite Briquette")

        addItem(NTechItems.sulfur, "Sulfur")
        addItem(NTechItems.niter, "Niter")
        addItem(NTechItems.fluorite, "Fluorite")
        addItem(NTechItems.quartzPowder, "Quartz Powder")
        addItem(NTechItems.yellowcake, "Yellowcake")
        addItem(NTechItems.chlorophytePowder, "Chlorophyte Powder")
        addItem(NTechItems.neodymiumPowder, "Neodymium Powder")
        addItem(NTechItems.niobiumPowder, "Niobium Powder")
        addItem(NTechItems.ceriumPowder, "Cerium Powder")
        addItemDesc(NTechItems.asbestosPowder, "§o„Sniffffffff - MHHHHHHMHHHHHHHHH“")
        addItem(NTechItems.enchantmentPowder, "Enchantment Powder")
        addItem(NTechItems.cloudResidue, "Cloud Residue")
        addItem(NTechItems.thermonuclearAshes, "Thermonuclear Ashes")
        addItem(NTechItems.semtexMix, "Semtex Mix")
        addItem(NTechItems.deshMix, "Desh Mix")
        addItem(NTechItems.deshReadyMix, "DeshReady™ Mix")
        addItem(NTechItems.nitaniumMix, "Nitanium Mix")
        addItem(NTechItems.sparkMix, "Spark Mix")
        addItem(NTechItems.meteoritePowder, "Meteorite Powder")
        addItemDesc(NTechItems.euphemiumPowder, "Pulverized pink.\nTastes like strawberries.")
        addItem(NTechItems.desaturatedRedstone, "Desaturated Redstone")
        addItem(NTechItems.dust, "Dust")
        addItemDesc(NTechItems.dust, "I hate dust!")
        addItem(NTechItems.tinyLithiumPowder, "Tiny Lithium Powder")
        addItem(NTechItems.tinyNeodymiumPowder, "Tiny Neodymium Powder")
        addItem(NTechItems.tinyCobaltPowder, "Tiny Cobalt Powder")
        addItem(NTechItems.tinyNiobiumPowder, "Tiny Niobium Powder")
        addItem(NTechItems.tinyCeriumPowder, "Tiny Cerium Powder")
        addItem(NTechItems.tinyLanthanumPowder, "Tiny Lanthanum Powder")
        addItem(NTechItems.tinyActiniumPowder, "Tiny Actinium Powder")
        addItem(NTechItems.tinyMeteoritePowder, "Tiny Meteorite Powder")
        addItem(NTechItems.redPhosphorus, "Red Phosphorus")
        addItemDesc(NTechItems.redPhosphorus, "Used in multi purpose bombs:\nIncendiary bombs are fun!")
        addItem(NTechItems.cryoPowder, "Cryo Powder")
        addItem(NTechItems.poisonPowder, "Poison Powder")
        addItemDesc(NTechItems.poisonPowder, "Used in multi purpose bombs:\nWarning: Poisonous!")
        addItem(NTechItems.thermite, "Thermite")
        addItem(NTechItems.energyPowder, "Energy Powder")

        addItem(NTechItems.cordite, "Cordite")
        addItem(NTechItems.ballistite, "Ballistite")

        addItem(NTechItems.rareEarthCrystals, "Rare Earth Crystals")
        addItem(NTechItems.redPhosphorusCrystals, "Red Phosphorus Crystals")
        addItem(NTechItems.trixiteCrystals, "Trixite Crystals")

        addItem(NTechItems.neodymiumFragment, "Neodymium Fragment")
        addItem(NTechItems.cobaltFragment, "Cobalt Fragment")
        addItem(NTechItems.niobiumFragment, "Niobium Fragment")
        addItem(NTechItems.ceriumFragment, "Cerium Fragment")
        addItem(NTechItems.lanthanumFragment, "Lanthanum Fragment")
        addItem(NTechItems.actiniumFragment, "Actinium Fragment")
        addItem(NTechItems.meteoriteFragment, "Meteorite Fragment")

        addItem(NTechItems.biomass, "Biomass")
        addItem(NTechItems.compressedBiomass, "Compressed Biomass")

        addItemDesc(
            NTechItems.euphemiumNugget,
            "A small piece of a pink metal.\n" +
                    "Its properties are still unknown,\n" +
                    "DEAL WITH IT carefully."
        )

        addItem(NTechItems.neutronReflector, "Neutron Reflector")
        addItem(NTechItems.mixedPlate, "Mixed Plate")
        addItem(NTechItems.paAAlloyPlate, "PaA Alloy Plate")
        addItem(NTechItems.insulator, "Insulator")
        addItem(NTechItems.kevlarCeramicCompound, "Kevlar-Ceramic Compound")
        addItem(NTechItems.dalekaniumPlate, "Angry Metal")
        addItem(NTechItems.deshCompoundPlate, "Desh Compound Plate")
        addItem(NTechItems.euphemiumCompoundPlate, "Euphemium Compound Plate")
        addItem(NTechItems.dineutroniumCompoundPlate, "Dineutronium Compound Plate")
        addItem(NTechItems.copperPanel, "Copper Panel")

        addItem(NTechItems.highSpeedSteelBolt, "High-Speed Steel Bolt")
        addItem(NTechItems.tungstenBolt, "Tungsten Bolt")
        addItem(NTechItems.reinforcedTurbineShaft, "Reinforced Turbine Shaft")

        addItem(NTechItems.hazmatCloth, "Hazmat Cloth")
        addItem(NTechItems.advancedHazmatCloth, "Advanced Hazmat Cloth")
        addItem(NTechItems.leadReinforcedHazmatCloth, "Lead-Reinforced Hazmat Cloth")
        addItem(NTechItems.fireProximityCloth, "Fire Proximity Cloth")
        addItem(NTechItems.activatedCarbonFilter, "Activated Carbon Filter")

        addItem(NTechItems.superConductor, "Super Conductor")
        addItem(NTechItems.highTemperatureSuperConductor, "4000K High Temperature Super Conductor")

        addItem(NTechItems.copperCoil, "Copper Coil")
        addItem(NTechItems.ringCoil, "Ring Coil")
        addItem(NTechItems.superConductingCoil, "Super Conducting Coil")
        addItem(NTechItems.superConductingRingCoil, "Super Conducting Ring Coil")
        addItem(NTechItems.goldCoil, "Gold Coil")
        addItem(NTechItems.goldRingCoil, "Gold Ring Coil")
        addItem(NTechItems.heatingCoil, "Heating Coil")
        addItem(NTechItems.highTemperatureSuperConductingCoil, "4000K High Temperature Super Conducting Coil")

        addItem(NTechItems.steelTank, "Steel Tank")
        addItem(NTechItems.motor, "Motor")
        addItem(NTechItems.centrifugeElement, "Centrifuge Element")
        addItem(NTechItems.centrifugeTower, "Centrifuge Tower")
        addItem(NTechItems.deeMagnets, "Dee Magnets")
        addItem(NTechItems.flatMagnet, "Flat Magnet")
        addItem(NTechItems.cyclotronTower, "Cyclotron Tower")
        addItem(NTechItems.breedingReactorCore, "Breeding Reactor Core")
        addItem(NTechItems.rtgUnit, "RTG Unit")
        addItem(NTechItems.thermalDistributionUnit, "Thermal Distribution Unit")
        addItem(NTechItems.endothermicDistributionUnit, "Endothermic Distribution Unit")
        addItem(NTechItems.exothermicDistributionUnit, "Exothermic Distribution Unit")
        addItem(NTechItems.gravityManipulator, "Gravity Manipulator")
        addItem(NTechItems.steelPipes, "Steel Pipes")
        addItem(NTechItems.titaniumDrill, "Titanium Drill")
        addItem(NTechItems.photovoltaicPanel, "Photovoltaic Panel")
        addItem(NTechItems.chlorinePinwheel, "Chlorine Pinwheel")
        addItem(NTechItems.telepad, "Telepad")
        addItem(NTechItems.entanglementKit, "Entaglement Kit")
        addItemDesc(
            NTechItems.entanglementKit,
            "Teleporter crafting item.\n" +
                    "Enables dimension-shifting via\n" +
                    "beryllium-enhanced resource scanner."
        )
        addItem(NTechItems.stabilizerComponent, "Stabilizer Component")
        addItem(NTechItems.emitterComponent, "Emitter Component")
        addItem(NTechItems.aluminiumCap, "Aluminium Cap")
        addItem(NTechItems.smallSteelShell, "Small Steel Shell")
        addItem(NTechItems.smallAluminiumShell, "Small Aluminium Shell")
        addItem(NTechItems.bigSteelShell, "Big Steel Shell")
        addItem(NTechItems.bigAluminiumShell, "Big Aluminium Shell")
        addItem(NTechItems.bigTitaniumShell, "Big Titanium Shell")
        addItem(NTechItems.flatSteelCasing, "Flat Steel Casing")
        addItem(NTechItems.smallSteelGridFins, "Small Steel Grid Fins")
        addItem(NTechItems.bigSteelGridFins, "Big Steel Grid Fins")
        addItem(NTechItems.largeSteelFins, "Large Steel Fins")
        addItem(NTechItems.smallTitaniumFins, "Small Titanium Fins")
        addItem(NTechItems.steelSphere, "Steel Sphere")
        addItem(NTechItems.steelPedestal, "Steel Pedestal")
        addItem(NTechItems.dysfunctionalNuclearReactor, "Dysfunctional Nuclear Reactor")
        addItem(NTechItems.largeSteelRotor, "Large Steel Rotor")
        addItem(NTechItems.generatorBody, "Generator Body")
        addItem(NTechItems.titaniumBlade, "Titanium Blade")
        addItem(NTechItems.tungstenReinforcedBlade, "Tungsten Reinforced Blade")
        addItem(NTechItems.titaniumSteamTurbine, "Titanium Steam Turbine")
        addItem(NTechItems.reinforcedTurbofanBlades, "Reinforced Turbofan Blades")
        addItem(NTechItems.generatorFront, "Generator Front")
        addItem(NTechItems.toothpicks, "Toothpicks")
        addItem(NTechItems.ductTape, "Duct Tape")
        addItem(NTechItems.clayCatalyst, "Clay Catalyst")
        addItem(NTechItems.smallMissileAssembly, "Small Missile Assembly")

        addItem(NTechItems.smallWarhead, "Small Warhead")
        addItem(NTechItems.mediumWarhead, "Medium Warhead")
        addItem(NTechItems.largeWarhead, "Large Warhead")
        addItem(NTechItems.smallIncendiaryWarhead, "Small Incendiary Warhead")
        addItem(NTechItems.mediumIncendiaryWarhead, "Medium Incendiary Warhead")
        addItem(NTechItems.largeIncendiaryWarhead, "Large Incendiary Warhead")
        addItem(NTechItems.smallClusterWarhead, "Small Cluster Warhead")
        addItem(NTechItems.mediumClusterWarhead, "Medium Cluster Warhead")
        addItem(NTechItems.largeClusterWarhead, "Large Cluster Warhead")
        addItem(NTechItems.smallBunkerBusterWarhead, "Small Bunker Busting Warhead")
        addItem(NTechItems.mediumBunkerBusterWarhead, "Medium Bunker Busting Warhead")
        addItem(NTechItems.largeBunkerBusterWarhead, "Large Bunker Busting Warhead")
        addItem(NTechItems.nuclearWarhead, "Nuclear Warhead")
        addItem(NTechItems.thermonuclearWarhead, "Thermonuclear Warhead")
        addItem(NTechItems.endothermicWarhead, "Endothermic Warhead")
        addItem(NTechItems.exothermicWarhead, "Exothermic Warhead")

        addItem(NTechItems.smallFuelTank, "Small Fuel Tank")
        addItem(NTechItems.mediumFuelTank, "Medium Fuel Tank")
        addItem(NTechItems.largeFuelTank, "Large Fuel Tank")

        addItem(NTechItems.smallThruster, "Small Thruster")
        addItem(NTechItems.mediumThruster, "Medium Thruster")
        addItem(NTechItems.largeThruster, "Large Thruster")
        addItem(NTechItems.lvnNuclearRocketEngine, "LV-N Nuclear Rocket Engine")

        addItem(NTechItems.satelliteBase, "Satellite Base")
        addItem(NTechItems.highGainOpticalCamera, "High-Gain Optical Camera")
        addItem(NTechItems.m700SurveyScanner, "M700 Survey Scanner")
        addItem(NTechItems.radarDish, "Radar Dish")
        addItem(NTechItems.deathRay, "Death Ray")
        addItem(NTechItems.xeniumResonator, "Xenium Resonator")

        addItem(NTechItems.size10Connector, "Size 10 Connector")
        addItem(NTechItems.size15Connector, "Size 15 Connector")
        addItem(NTechItems.size20Connector, "Size 20 Connector")

        addItem(NTechItems.hunterChopperCockpit, "Hunter Chopper Cockpit")
        addItem(NTechItems.emplacementGun, "Emplacement Gun")
        addItem(NTechItems.hunterChopperBody, "Hunter Chopper Body")
        addItem(NTechItems.hunterChopperTail, "Hunter Chopper Tail")
        addItem(NTechItems.hunterChopperWing, "Hunter Chopper Wing")
        addItem(NTechItems.hunterChopperRotorBlades, "Hunter Chopper Rotor Blades")
        addItem(NTechItems.combineScrapMetal, "Combine Scrap Metal")

        addItem(NTechItems.heavyHammerHead, "Heavy Hammer Head")
        addItem(NTechItems.heavyAxeHead, "Heavy Axe Head")
        addItem(NTechItems.reinforcedPolymerHandle, "Reinforced Polymer Handle")

        addItem(NTechItems.basicCircuitAssembly, "Basic Circuit Assembly")
        addItem(NTechItems.basicCircuit, "Basic Circuit")
        addItem(NTechItems.enhancedCircuit, "Enhanced Circuit")
        addItem(NTechItems.advancedCircuit, "Advanced Circuit")
        addItem(NTechItems.overclockedCircuit, "Overclocked Circuit")
        addItem(NTechItems.highPerformanceCircuit, "High Performance Circuit")
        addItem(NTechItems.militaryGradeCircuitBoardTier1, "Military Grade Circuit Board (Tier 1)")
        addItem(NTechItems.militaryGradeCircuitBoardTier2, "Military Grade Circuit Board (Tier 2)")
        addItem(NTechItems.militaryGradeCircuitBoardTier3, "Military Grade Circuit Board (Tier 3)")
        addItem(NTechItems.militaryGradeCircuitBoardTier4, "Military Grade Circuit Board (Tier 4)")
        addItem(NTechItems.militaryGradeCircuitBoardTier5, "Military Grade Circuit Board (Tier 5)")
        addItem(NTechItems.militaryGradeCircuitBoardTier6, "Military Grade Circuit Board (Tier 6)")

        addItem(NTechItems.revolverMechanism, "Revolver Mechanism")
        addItem(NTechItems.advancedRevolverMechanism, "Advanced Revolver Mechanism")
        addItem(NTechItems.rifleMechanism, "Rifle Mechanism")
        addItem(NTechItems.advancedRifleMechanism, "Advanced Rifle Mechanism")
        addItem(NTechItems.launcherMechanism, "Launcher Mechanism")
        addItem(NTechItems.advancedLauncherMechanism, "Advanced Launcher Mechanism")
        addItem(NTechItems.highTechWeaponMechanism, "High-Tech Weapon Mechanism")

        addItem(NTechItems.point357MagnumPrimer, ".357 Magnum Primer (x16)")
        addItem(NTechItems.point44MagnumPrimer, ".44 Magnum Primer (x16)")
        addItem(NTechItems.smallCaliberPrimer, "Small Caliber Primer (x24)")
        addItem(NTechItems.largeCaliberPrimer, "Large Caliber Primer (x8)")
        addItem(NTechItems.buckshotPrimer, "Buckshot Primer (x8)")

        addItem(NTechItems.point357MagnumCasing, ".357 Magnum Casing (x16)")
        addItem(NTechItems.point44MagnumCasing, ".44 Magnum Casing (x16)")
        addItem(NTechItems.smallCaliberCasing, "Small Caliber Casing (x24)")
        addItem(NTechItems.largeCaliberCasing, "Large Caliber Casing (x8)")
        addItem(NTechItems.buckshotCasing, "Buckshot Casing (x8)")

        addItem(NTechItems.ironBulletAssembly, "Iron Bullet Assembly")
        addItem(NTechItems.leadBulletAssembly, "Lead Bullet Assembly")
        addItem(NTechItems.glassBulletAssembly, "Glass Bullet Assembly")
        addItem(NTechItems.goldBulletAssembly, "Gold Bullet Assembly")
        addItem(NTechItems.schrabidiumBulletAssembly, "Schrabidium Bullet Assembly")
        addItem(NTechItems.nightmareBulletAssembly, "Nightmare Bullet Assembly")
        addItem(NTechItems.deshBulletAssembly, "Desh Bullet Assembly")
        addItem(NTechItems.point44MagnumAssembly, ".44 Magnum Assembly")
        addItem(NTechItems.nineMmAssembly, "9mm Assembly")
        addItem(NTechItems.fivePoint56mmAssembly, "5.56mm Assembly")
        addItem(NTechItems.point22LRAssembly, ".22 LR Assembly")
        addItem(NTechItems.point5mmAssembly, ".5mm Assembly")
        addItem(NTechItems.point50AEAssembly, ".50 AE Assembly")
        addItem(NTechItems.point50BMGAssembly, ".50 BMG Assembly")

        addItem(NTechItems.silverBulletCasing, "Silver Bullet Casing")
        addItem(NTechItems.twelvePoint8cmStarmetalHighEnergyShell, "12.8cm Starmetal High-Energy Shell")
        addItem(NTechItems.twelvePoint8cmNuclearShell, "12.8cm Nuclear Shell")
        addItem(NTechItems.twelvePoint8cmDUShell, "12.8cm DU-Shell")

        addItem(NTechItems.cableDrum, "Cable Drum")
        addItemDesc(NTechItems.cableDrum, "Right-click poles to connect")
        addItem(NTechItems.paintingOfACartoonPony, "Painting of a Cartoon Pony")
        addItemDesc(NTechItems.paintingOfACartoonPony, "Yellow horse beats blue horse, that's a proven fact!")
        addItem(NTechItems.conspiracyTheory, "Conspiracy Theory")
        addItemDesc(NTechItems.conspiracyTheory, "Steel beams can't melt jet fuel!")
        addItem(NTechItems.politicalTopic, "Political Topic")
        addItemDesc(NTechItems.politicalTopic, "Donald Duck will build the wall!")
        addItem(NTechItems.ownOpinion, "Own Opinion")
        addItemDesc(NTechItems.ownOpinion, "Well, I like it...")

        addItem(NTechItems.explosivePellets, "Explosive Pellets")
        addItemDesc(NTechItems.explosivePellets, "Used in multi purpose bombs:\nAdds some extra boom!")
        addItem(NTechItems.leadPellets, "Lead Pellets")
        addItem(NTechItems.flechettes, "Flechettes")
        addItem(NTechItems.poisonGasCartridge, "Poison Gas Cartridge")
        addItemDesc(NTechItems.poisonGasCartridge, "Used in multi purpose bombs:\n*cough cough* Halp pls!")
        addItem(NTechItems.magnetron, "Magnetron")
        addItem(NTechItems.denseCoalCluster, "Dense Coal Cluster")
        addItem(NTechItems.burntBark, "Burnt Bark")
        addItemDesc(NTechItems.burntBark, "A piece of bark from an exploded golden oak tree.")
        addItem(NTechItems.machineUpgradeTemplate, "Machine Upgrade Template")

        addItem(NTechItems.blankRune, "Blank Catalyst Matrix")
        addItem(NTechItems.isaRune, "Cool Catalyst Matrix")
        addItem(NTechItems.dagazRune, "Balanced Catalyst Matrix")
        addItem(NTechItems.hagalazRune, "Rough Catalyst Matrix")
        addItem(NTechItems.jeraRune, "Multiplicative Catalyst Matrix")
        addItem(NTechItems.thurisazRune, "Additive Catalyst Matrix")

        addItem(NTechItems.burnedOutQuadSchrabidiumFuelRod, "Burned Out Quad Schrabidium Rod")
        addItemDesc(NTechItems.burnedOutQuadSchrabidiumFuelRod, "A quad fuel rod which contains a\nvery small amount of a strange new element.")

        addItem(NTechItems.scrap, "Scrap")
        addItem(NTechItems.hotDepletedUraniumFuel, "Hot Depleted Uranium Fuel")
        addItem(NTechItems.hotDepletedThoriumFuel, "Hot Depleted Thorium Fuel")
        addItem(NTechItems.hotDepletedPlutoniumFuel, "Hot Depleted Plutonium Fuel")
        addItem(NTechItems.hotDepletedMOXFuel, "Hot Depleted MOX Fuel")
        addItem(NTechItems.hotDepletedSchrabidiumFuel, "Hot Depleted Schrabidium Fuel")
        addItem(NTechItems.depletedUraniumFuel, "Depleted Uranium Fuel")
        addItem(NTechItems.depletedThoriumFuel, "Depleted Thorium Fuel")
        addItem(NTechItems.depletedPlutoniumFuel, "Depleted Plutonium Fuel")
        addItem(NTechItems.depletedMOXFuel, "Depleted MOX Fuel")
        addItem(NTechItems.depletedSchrabidiumFuel, "Depleted Schrabidium Fuel")
        addItem(NTechItems.trinitite, "Trinitite")
        addItem(NTechItems.nuclearWaste, "Nuclear Waste")
        addItem(NTechItems.tinyNuclearWaste, "Tiny Nuclear Waste")

        addItem(NTechItems.crystalHorn, "Crystal Horn")
        addItemDesc(NTechItems.crystalHorn, "An actual horn.")
        addItem(NTechItems.charredCrystal, "Charred Crystal")
        addItemDesc(NTechItems.charredCrystal, "Also a real horn. Weird, right?")

        addItem(NTechItems.battery, "Battery")
        addItem(NTechItems.redstonePowerCell, "Redstone Power Cell")
        addItem(NTechItems.sixfoldRedstonePowerCell, "Sixfold Redstone Power Cell")
        addItem(NTechItems.twentyFourFoldRedstonePowerCell, "24-Fold Redstone Power Cell")
        addItem(NTechItems.advancedBattery, "Advanced Battery")
        addItem(NTechItems.advancedPowerCell, "Advanced Power Cell")
        addItem(NTechItems.quadrupleAdvancedPowerCell, "Quadruple Advanced Power Cell")
        addItem(NTechItems.twelveFoldAdvancedPowerCell, "Twelvefold Advanced Power Cell")
        addItem(NTechItems.lithiumBattery, "Lithium-Ion Battery")
        addItem(NTechItems.lithiumPowerCell, "Lithium-Ion Power Cell")
        addItem(NTechItems.tripleLithiumPowerCell, "Triple Lithium-Ion Power Cell")
        addItem(NTechItems.sixfoldLithiumPowerCell, "Sixfold Lithium-Ion Power Cell")
        addItem(NTechItems.schrabidiumBattery, "Schrabidium Battery")
        addItem(NTechItems.schrabidiumPowerCell, "Schrabidium Power Cell")
        addItem(NTechItems.doubleSchrabidiumPowerCell, "Double Schrabidium Power Cell")
        addItem(NTechItems.quadrupleSchrabidiumPowerCell, "Quadruple Schrabidium Power Cell")
        addItem(NTechItems.sparkBattery, "Spark Battery")
        addItem(NTechItems.offBrandSparkBattery, "Off-Brand Spark Battery")
        addItem(NTechItems.sparkPowerCell, "Spark Power Cell")
        addItem(NTechItems.sparkArcaneCarBattery, "Spark Arcane Car Battery")
        addItem(NTechItems.sparkArcaneEnergyStorageArray, "Spark Arcane Energy Storage Array")
        addItem(NTechItems.sparkArcaneMassEnergyVoid, "Spark Arcane Mass-Energy Void")
        addItem(NTechItems.sparkArcaneDiracSea, "Spark Arcane Dirac Sea")
        addItem(NTechItems.sparkSolidSpaceTimeCrystal, "Spark Solid Space-Time Crystal")
        addItem(NTechItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit, "Spark Ludicrous Physics-Defying Energy Storage Unit")
        addItem(NTechItems.infiniteBattery, "Infinite Battery")
        addItem(NTechItems.singleUseBattery, "Single-Use Battery")
        addItem(NTechItems.largeSingleUseBattery, "Large Single-Use Battery")
        addItem(NTechItems.potatoBattery, "Potato Battery")
        addItem(NTechItems.steamPoweredEnergyStorageTank, "Steam-Powered Energy Storage Tank")
        addItem(NTechItems.largeSteamPoweredEnergyStorageTank, "Large Steam-Powered Energy Storage Tank")

        addItem(NTechItems.stoneFlatStamp, "Flat Stamp (Stone)")
        addItem(NTechItems.stonePlateStamp, "Plate Stamp (Stone)")
        addItem(NTechItems.stoneWireStamp, "Wire Stamp (Stone)")
        addItem(NTechItems.stoneCircuitStamp, "Circuit Stamp (Stone)")
        addItem(NTechItems.ironFlatStamp, "Flat Stamp (Iron)")
        addItem(NTechItems.ironPlateStamp, "Plate Stamp (Iron)")
        addItem(NTechItems.ironWireStamp, "Wire Stamp (Iron)")
        addItem(NTechItems.ironCircuitStamp, "Circuit Stamp (Iron)")
        addItem(NTechItems.steelFlatStamp, "Flat Stamp (Steel)")
        addItem(NTechItems.steelPlateStamp, "Plate Stamp (Steel)")
        addItem(NTechItems.steelWireStamp, "Wire Stamp (Steel)")
        addItem(NTechItems.steelCircuitStamp, "Circuit Stamp (Steel)")
        addItem(NTechItems.titaniumFlatStamp, "Flat Stamp (Titanium)")
        addItem(NTechItems.titaniumPlateStamp, "Plate Stamp (Titanium)")
        addItem(NTechItems.titaniumWireStamp, "Wire Stamp (Titanium)")
        addItem(NTechItems.titaniumCircuitStamp, "Circuit Stamp (Titanium)")
        addItem(NTechItems.obsidianFlatStamp, "Flat Stamp (Obsidian)")
        addItem(NTechItems.obsidianPlateStamp, "Plate Stamp (Obsidian)")
        addItem(NTechItems.obsidianWireStamp, "Wire Stamp (Obsidian)")
        addItem(NTechItems.obsidianCircuitStamp, "Circuit Stamp (Obsidian)")
        addItem(NTechItems.schrabidiumFlatStamp, "Flat Stamp (Schrabidium)")
        addItem(NTechItems.schrabidiumPlateStamp, "Plate Stamp (Schrabidium)")
        addItem(NTechItems.schrabidiumWireStamp, "Wire Stamp (Schrabidium)")
        addItem(NTechItems.schrabidiumCircuitStamp, "Circuit Stamp (Schrabidium)")

        addItem(NTechItems.speedUpgradeMk1, "Speed Upgrade Mk.I")
        addItem(NTechItems.speedUpgradeMk2, "Speed Upgrade Mk.II")
        addItem(NTechItems.speedUpgradeMk3, "Speed Upgrade Mk.III")
        addItem(NTechItems.powerSavingUpgradeMk1, "Power Saving Upgrade Mk.I")
        addItem(NTechItems.powerSavingUpgradeMk2, "Power Saving Upgrade Mk.II")
        addItem(NTechItems.powerSavingUpgradeMk3, "Power Saving Upgrade Mk.III")
        addItem(NTechItems.overdriveUpgradeMk1, "Overdrive Upgrade Mk.I")
        addItem(NTechItems.overdriveUpgradeMk2, "Overdrive Upgrade Mk.II")
        addItem(NTechItems.overdriveUpgradeMk3, "Overdrive Upgrade Mk.III")

        addItem(NTechItems.aluminiumShredderBlade, "Aluminium Shredder Blade")
        addItem(NTechItems.goldShredderBlade, "Gold Shredder Blade")
        addItem(NTechItems.ironShredderBlade, "Iron Shredder Blade")
        addItem(NTechItems.steelShredderBlade, "Steel Shredder Blade")
        addItem(NTechItems.titaniumShredderBlade, "Titanium Shredder Blade")
        addItem(NTechItems.advancedAlloyShredderBlade, "Advanced Alloy Shredder Blade")
        addItem(NTechItems.combineSteelShredderBlade, "Combine Steel Shredder Blade")
        addItem(NTechItems.schrabidiumShredderBlade, "Schrabidium Shredder Blade")
        addItem(NTechItems.deshShredderBlade, "Desh Shredder Blade")

        addItem(NTechItems.machineTemplateFolder, "Machine Template Folder")
        addItemDesc(
            NTechItems.machineTemplateFolder,
            "Machine Templates: Paper + Dye\n" +
                    "Fluid IDs: Iron Plate + Dye\n" +
                    "Press Stamps: Flat Stamp\n" +
                    "Siren Tracks: Insulator + Steel Plate"
        )

        addItem(NTechItems.sirenTrackHatchSiren, "Hatch Siren")
        addItem(NTechItems.sirenTrackAutopilotDisconnected, "Autopilot Disconnected")
        addItem(NTechItems.sirenTrackAMSSiren, "AMS Siren")
        addItem(NTechItems.sirenTrackBlastDoorAlarm, "Blast Door Alarm")
        addItem(NTechItems.sirenTrackAPCSiren, "APC Siren")
        addItem(NTechItems.sirenTrackKlaxon, "Klaxon")
        addItem(NTechItems.sirenTrackVaultDoorAlarm, "Vault Door Alarm")
        addItem(NTechItems.sirenTrackSecurityAlert, "Security Alert")
        addItem(NTechItems.sirenTrackStandardSiren, "Standard Siren")
        addItem(NTechItems.sirenTrackClassicSiren, "Classic Siren")
        addItem(NTechItems.sirenTrackBankAlarm, "Bank Alarm")
        addItem(NTechItems.sirenTrackBeepSiren, "Beep Siren")
        addItem(NTechItems.sirenTrackContainerAlarm, "Container Alarm")
        addItem(NTechItems.sirenTrackSweepSiren, "Sweep Siren")
        addItem(NTechItems.sirenTrackMissileSiloSiren, "Missile Silo Siren")
        addItem(NTechItems.sirenTrackAirRaidSiren, "Air Raid Siren")
        addItem(NTechItems.sirenTrackNostromoSelfDestruct, "Nostromo Self Destruct")
        addItem(NTechItems.sirenTrackEASAlarmScreech, "EAS Alarm Screech")
        addItem(NTechItems.sirenTrackAPCPass, "APC Pass")
        addItem(NTechItems.sirenTrackRazortrainHorn, "Razortrain Horn")

        addItem(NTechItems.assemblyTemplate, "Assembly Template: %s")
        addItem(NTechItems.chemTemplate, "Chemistry Template: %s")

        run {
            val usedInLittleBoy = "Used in:\nLittle Boy"
            addItem(NTechItems.neutronShieldingLittleBoy, "Neutron Shielding")
            addItemDesc(NTechItems.neutronShieldingLittleBoy, usedInLittleBoy)
            addItem(NTechItems.subcriticalUraniumTarget, "Subcritical U235 Target")
            addItemDesc(NTechItems.subcriticalUraniumTarget, usedInLittleBoy)
            addItem(NTechItems.uraniumProjectile, "U235 Projectile")
            addItemDesc(NTechItems.uraniumProjectile, usedInLittleBoy)
            addItem(NTechItems.propellantLittleBoy, "Propellant")
            addItemDesc(NTechItems.propellantLittleBoy, usedInLittleBoy)
            addItem(NTechItems.bombIgniterLittleBoy, "Bomb Igniter")
            addItemDesc(NTechItems.bombIgniterLittleBoy, usedInLittleBoy)
        }
        addItem(NTechItems.bundleOfImplosionPropellant, "Bundle of Implosion Propellant")
        addItemDesc(NTechItems.bundleOfImplosionPropellant, "Used in:\nFat Man\nIvy Mike\nTsar Bomba")
        addItem(NTechItems.bombIgniterFatMan, "Bomb Igniter")
        addItemDesc(NTechItems.bombIgniterFatMan, "Used in Fat Man")
        addItem(NTechItems.plutoniumCore, "Plutonium Core")
        addItemDesc(NTechItems.plutoniumCore, "Used in:\nFat Man\nIvy Mike\nTsar Bomba")
        addItem(NTechItems.detonator, "Detonator")
        addItemDesc(NTechItems.detonator, "Shift-right-click an explosive to set the position,\nright-click to detonate!")
        addItem(NTechItems.littleBoyKit, "Little Boy Kit")
        addItem(NTechItems.fatManKit, "Fat Man Kit")

        addItem(NTechItems.designator, "Short Range Target Designator")
        addItem(NTechItems.heMissile, "High Explosive Missile")
        addItem(NTechItems.incendiaryMissile, "Incendiary Missile")
        addItem(NTechItems.clusterMissile, "Cluster Missile")
        addItem(NTechItems.bunkerBusterMissile, "Bunker Buster")
        addItem(NTechItems.strongMissile, "Strong High Explosive Missile")
        addItem(NTechItems.strongIncendiaryMissile, "Strong Incendiary Missile")
        addItem(NTechItems.strongClusterMissile, "Strong Cluster Missile")
        addItem(NTechItems.strongBunkerBusterMissile, "Enhanced Bunker Buster")
        addItem(NTechItems.burstMissile, "Burst Missile")
        addItem(NTechItems.infernoMissile, "Inferno Missile G.R.N. Mk.II")
        addItem(NTechItems.rainMissile, "Bomblet Rain")
        addItem(NTechItems.drillMissile, "The Concrete Cracker")
        addItem(NTechItems.nuclearMissile, "Nuclear Missile")

        addItem(NTechItems.oilDetector, "Oil Reservoir Detector")
        addItemDesc(NTechItems.oilDetector, "Right-click to scan for oil.\nDetector will only find large deposits.")
        addItem(NTechItems.geigerCounter, "Handheld Geiger Counter")

        addItem(NTechItems.ivBag, "IV Bag")
        addItem(NTechItems.bloodBag, "Blood Bag")
        addItem(NTechItems.emptyExperienceBag, "Empty Experience Bag")
        addItem(NTechItems.experienceBag, "Experience Bag")
        addItem(NTechItems.radAway, "RadAway")
        addItem(NTechItems.strongRadAway, "Strong RadAway")
        addItem(NTechItems.eliteRadAway, "Elite RadAway")

        addItem(NTechItems.hazmatHelmet, "Hazmat Helmet")
        addItem(NTechItems.hazmatChestplate, "Hazmat Chestplate")
        addItem(NTechItems.hazmatLeggings, "Hazmat Leggings")
        addItem(NTechItems.hazmatBoots, "Hazmat Boots")
        addItem(NTechItems.advancedHazmatHelmet, "Advanced Hazmat Helmet")
        addItem(NTechItems.advancedHazmatChestplate, "Advanced Hazmat Chestplate")
        addItem(NTechItems.advancedHazmatLeggings, "Advanced Hazmat Leggings")
        addItem(NTechItems.advancedHazmatBoots, "Advanced Hazmat Boots")
        addItem(NTechItems.reinforcedHazmatHelmet, "High-Performance Hazmat Helmet")
        addItem(NTechItems.reinforcedHazmatChestplate, "High-Performance Hazmat Chestplate")
        addItem(NTechItems.reinforcedHazmatLeggings, "High-Performance Hazmat Leggings")
        addItem(NTechItems.reinforcedHazmatBoots, "High-Performance Hazmat Boots")
        addItem(NTechItems.titaniumHelmet, "Titanium Helmet")
        addItem(NTechItems.titaniumChestplate, "Titanium Chestplate")
        addItem(NTechItems.titaniumLeggings, "Titanium Leggings")
        addItem(NTechItems.titaniumBoots, "Titanium Boots")
        addItem(NTechItems.steelHelmet, "Steel Helmet")
        addItem(NTechItems.steelChestplate, "Steel Chestplate")
        addItem(NTechItems.steelLeggings, "Steel Leggings")
        addItem(NTechItems.steelBoots, "Steel Boots")
        addItem(NTechItems.advancedAlloyHelmet, "Advanced Alloy Helmet")
        addItem(NTechItems.advancedAlloyChestplate, "Advanced Alloy Chestplate")
        addItem(NTechItems.advancedAlloyLeggings, "Advanced Alloy Leggings")
        addItem(NTechItems.advancedAlloyBoots, "Advanced Alloy Boots")
        addItem(NTechItems.combineSteelHelmet, "Combine Steel Helmet")
        addItem(NTechItems.combineSteelChestplate, "Combine Steel Chestplate")
        addItem(NTechItems.combineSteelLeggings, "Combine Steel Leggings")
        addItem(NTechItems.combineSteelBoots, "Combine Steel Boots")
        addItem(NTechItems.paAAlloyChestplate, "PaA Chest Protection Plate")
        addItem(NTechItems.paAAlloyLeggings, "PaA Leg Reinforcements")
        addItem(NTechItems.paAAlloyBoots, "PaA \"good ol' shoes\"")
        addItem(NTechItems.schrabidiumHelmet, "Schrabidium Helmet")
        addItem(NTechItems.schrabidiumChestplate, "Schrabidium Chestplate")
        addItem(NTechItems.schrabidiumLeggings, "Schrabidium Leggings")
        addItem(NTechItems.schrabidiumBoots, "Schrabidium Boots")

        addItem(NTechItems.polaroid, "The Polaroid")

        addItem(NTechFluids.uraniumHexafluoride.bucket, "Uranium Hexafluoride Bucket")

        addItem(NTechItems.creativeNuclearExplosionSpawner, "Nuclear Explosion Spawner")

        addEntityType(EntityTypes.nuclearExplosion, "Nuclear Explosion")
        addEntityType(EntityTypes.mushroomCloud, "Mushroom Cloud")
        addEntityType(EntityTypes.falloutRain, "Fallout Rain")
        addEntityTypeWithSpawnEgg(EntityTypes.nuclearCreeper, "Nuclear Creeper")

        addEntityType(EntityTypes.missileHE, "High Explosive Missile")
        addEntityType(EntityTypes.missileIncendiary, "Incendiary Missile")
        addEntityType(EntityTypes.missileCluster, "Cluster Missile")
        addEntityType(EntityTypes.missileBunkerBuster, "Bunker Buster")
        addEntityType(EntityTypes.missileHEStrong, "Strong High Explosive Missile")
        addEntityType(EntityTypes.missileIncendiaryStrong, "Strong Incendiary Missile")
        addEntityType(EntityTypes.missileClusterStrong, "Strong Cluster Missile")
        addEntityType(EntityTypes.missileBunkerBusterStrong, "Enhanced Bunker Buster")
        addEntityType(EntityTypes.missileBurst, "Burst Missile")
        addEntityType(EntityTypes.missileInferno, "Inferno Missile G.R.N. Mk.II")
        addEntityType(EntityTypes.missileRain, "Bomblet Rain")
        addEntityType(EntityTypes.missileDrill, "The Concrete Cracker")
        addEntityType(EntityTypes.missileNuclear, "Nuclear Missile")

        addEntityType(EntityTypes.clusterFragment, "Bomblet")

        addMenuType(MenuTypes.sirenMenu, "Siren")
        addMenuType(MenuTypes.safeMenu, "Safe")
        addMenuType(MenuTypes.anvilMenu, "Anvil Tier %s")
        addMenuType(MenuTypes.steamPressMenu, "Steam Press")
        addMenuType(MenuTypes.blastFurnaceMenu, "Blast Furnace")
        addMenuType(MenuTypes.combustionGeneratorMenu, "Combustion Generator")
        addMenuType(MenuTypes.electricFurnaceMenu, "Electric Furnace")
        addMenuType(MenuTypes.shredderMenu, "Shredder")
        addMenuType(MenuTypes.assemblerMenu, "Assembler")
        addMenuType(MenuTypes.chemPlantMenu, "Chemical Plant")

        addMenuType(MenuTypes.littleBoyMenu, "Little Boy")
        addMenuType(MenuTypes.fatManMenu, "Fat Man")

        addMenuType(MenuTypes.launchPadMenu, "Missile Launch Pad")

        addSound(SoundEvents.sirenTrackHatchSiren, "Siren running: Hatch Siren")
        addSound(SoundEvents.sirenTrackAutopilotDisconnected, "Siren running: Autopilot Disconnected")
        addSound(SoundEvents.sirenTrackAMSSiren, "Siren running: AMS Siren")
        addSound(SoundEvents.sirenTrackBlastDoorAlarm, "Siren running: Blast Door Alarm")
        addSound(SoundEvents.sirenTrackAPCSiren, "Siren running: APC Siren")
        addSound(SoundEvents.sirenTrackKlaxon, "Siren running: Klaxon")
        addSound(SoundEvents.sirenTrackVaultDoorAlarm, "Siren running: Vault Door Alarm")
        addSound(SoundEvents.sirenTrackSecurityAlert, "Siren running: Security Alert")
        addSound(SoundEvents.sirenTrackStandardSiren, "Siren running: Standard Siren")
        addSound(SoundEvents.sirenTrackClassicSiren, "Siren running: Classic Siren")
        addSound(SoundEvents.sirenTrackBankAlarm, "Siren running: Bank Alarm")
        addSound(SoundEvents.sirenTrackBeepSiren, "Siren running: Beep Siren")
        addSound(SoundEvents.sirenTrackContainerAlarm, "Siren running: Container Alarm")
        addSound(SoundEvents.sirenTrackSweepSiren, "Siren running: Sweep Siren")
        addSound(SoundEvents.sirenTrackMissileSiloSiren, "Siren running: Missile Silo Siren")
        addSound(SoundEvents.sirenTrackAirRaidSiren, "Siren running: Air Raid Siren")
        addSound(SoundEvents.sirenTrackNostromoSelfDestruct, "Siren running: Nostromo Self Destruct")
        addSound(SoundEvents.sirenTrackEASAlarmScreech, "Siren running: EAS Alarm Screech")
        addSound(SoundEvents.sirenTrackAPCPass, "Siren running: APC Pass")
        addSound(SoundEvents.sirenTrackRazortrainHorn, "Siren running: Razortrain Horn")
        addSound(SoundEvents.anvilFall, "Anvil clashes")
        addSound(SoundEvents.pressOperate, "Press stamps")
        addSound(SoundEvents.assemblerOperate, "Assembler whirs")
        addSound(SoundEvents.chemPlantOperate, "Chemical Plant operates")
        addSound(SoundEvents.debris, "Debris hit the ground")
        addSound(SoundEvents.installUpgrade, "Upgrade installed")
        addSound(SoundEvents.inject, "Needle injected")
        addSound(SoundEvents.emptyIVBag, "Liquid infused")
        addSound(SoundEvents.randomBleep, "Device bleeps")
        addSound(SoundEvents.randomBoop, "Device boops")
        addSound(SoundEvents.randomUnpack, "Item unpacked")
        add("subtitle.$MODID.geiger.click", "Geiger Counter clicks")
        addSound(SoundEvents.missileTakeoff, "Missile takes off")
        addSound(SoundEvents.miniNukeExplosion, "Mini nuke explodes")

        addDamageSource(DamageSources.extractBlood, "%1\$s extracted too much life essence", "%1\$s tried to leave neatly-packaged life juice for %2\$s")
        addDamageSource(DamageSources.radiation, "%1\$s died from radiation poisoning", "%1\$s fell victim to acute radiation syndrome whilst fighting %2\$s")
        addDamageSource(DamageSources.nuclearBlast, "%1\$s was blown away by a nuclear explosion", "%1\$s got nuked whilst fighting %2\$s")
        addDamageSource(DamageSources.murkyAnvil, "%1\$s UNDEFINED", "%1\$s UNDEFINED whilst trying to escape %2\$s")

        addAttribute(Attributes.RADIATION_RESISTANCE, "Radiation Resistance")

        add(LangKeys.ARMOR_BLAST_PROTECTION, "Damage modifier of %s against explosions")
        add(LangKeys.ARMOR_CUSTOM_GEIGER, "Built-In Geiger Counter HUD")
        add(LangKeys.ARMOR_DAMAGE_CAP, "Hard damage cap of %s")
        add(LangKeys.ARMOR_DAMAGE_MODIFIER, "General damage modifier of %s")
        add(LangKeys.ARMOR_DAMAGE_RESISTANCE_MODIFIER, "Damage modifier of %s against %s")
        add(LangKeys.ARMOR_DAMAGE_THRESHOLD, "Damage threshold of %s")
        add(LangKeys.ARMOR_DASH_COUNT, "Grants %s dashes")
        add(LangKeys.ARMOR_FIREPROOF, "Fireproof")
        add(LangKeys.ARMOR_FULL_SET_BONUS, "Full Set Bonus:")
        add(LangKeys.ARMOR_GEIGER_SOUND, "Auditory Geiger Counter")
        add(LangKeys.ARMOR_GRAVITY, "Gravity modifier of %s")
        add(LangKeys.ARMOR_HARD_LANDING, "Hard Landing")
        add(LangKeys.ARMOR_NULLIFIES_DAMAGE, "Nullifies all damage from %s")
        add(LangKeys.ARMOR_PROJECTILE_PROTECTION, "Damage modifier of %s against projectiles")
        add(LangKeys.ARMOR_PROTECTION_YIELD, "Protection applies to damage <%s")
        add(LangKeys.ARMOR_THERMAL, "Thermal Sight")
        add(LangKeys.ARMOR_VATS, "Enemy HUD")

        add(LangKeys.BUTTON_CANCEL, "Cancel")
        add(LangKeys.BUTTON_START, "Start")

        add(LangKeys.CHEMISTRY_URANIUM_HEXAFLUORIDE, "Uranium Hexafluoride Production")

        add(LangKeys.DETONATOR_INVALID_BLOCK_ENTITY, "Server Error: The target's BlockEntity is invalid!")
        add(LangKeys.DETONATOR_MISSING_COMPONENTS, "The explosive is missing components!")
        add(LangKeys.DETONATOR_NO_EXPLOSIVE, "Target is not a valid explosive!")
        add(LangKeys.DETONATOR_PROHIBITED, "The detonation was prohibited!")
        add(LangKeys.DETONATOR_SUCCESS, "Detonated!")
        add(LangKeys.DETONATOR_UNKNOWN_ERROR, "An unknown error occurred during the detonation")

        add(LangKeys.DEVICE_OIL_DETECTOR_BELOW, "Oil deposit directly below!")
        add(LangKeys.DEVICE_OIL_DETECTOR_NEAR, "Oil deposit detected nearby")
        add(LangKeys.DEVICE_OIL_DETECTOR_NO_OIL, "No oil detected")
        add(LangKeys.DEVICE_POSITION_SET, "Position set!")
        add(LangKeys.DEVICE_POSITION_NOT_LOADED, "Position is currently not loaded in the world!")
        add(LangKeys.DEVICE_POSITION_NOT_SET, "No position set!")

        add(LangKeys.ENERGY, "Energy")
        add(LangKeys.ENERGY_ENERGY_STORED, "Energy Stored: %s/%sHE")
        add(LangKeys.ENERGY_CHARGE_RATE, "Charge Rate: %sHE/t")
        add(LangKeys.ENERGY_DISCHARGE_RATE, "Discharge Rate: %sHE/t")

        add(LangKeys.EXPLOSION_SPAWNER_ERROR_EXTRA_FALLOUT, "Cannot parse extra fallout value")
        add(LangKeys.EXPLOSION_SPAWNER_ERROR_STRENGTH, "Cannot parse strength value")
        add(LangKeys.EXPLOSION_SPAWNER_EXTRA_FALLOUT, "Extra Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_HAS_FALLOUT, "Has Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_MUTED, "Muted")
        add(LangKeys.EXPLOSION_SPAWNER_NO_PERMISSION, "Cannot use Nuclear Explosion Spawner: Insufficient permission")
        add(LangKeys.EXPLOSION_SPAWNER_POSITION, "Position")
        add(LangKeys.EXPLOSION_SPAWNER_STRENGTH, "Strength")

        add(LangKeys.GEIGER_CHUNK_RADIATION, "Current chunk radiation:")
        add(LangKeys.GEIGER_PLAYER_IRRADIATION, "Player irradiation:")
        add(LangKeys.GEIGER_PLAYER_RESISTANCE, "Player resistance:")
        add(LangKeys.GEIGER_TITLE, "GEIGER COUNTER")
        add(LangKeys.GEIGER_TOTAL_ENVIRONMENTAL_RADIATION, "Total environmental radiation:")

        add(LangKeys.HAZARD_ASBESTOS, "[Asbestos]")
        add(LangKeys.HAZARD_BLINDING, "[Blinding]")
        add(LangKeys.HAZARD_COAL, "[Coal Dust]")
        add(LangKeys.HAZARD_DIGAMMA, "[Digamma]")
        add(LangKeys.HAZARD_EXPLOSIVE, "[Flammable / Explosive]")
        add(LangKeys.HAZARD_HEAT, "[Pyrophoric / Hot]")
        add(LangKeys.HAZARD_HYDROREACTIVE, "[Hydroreactive]")
        add(LangKeys.HAZARD_RADIATON, "[Radioactive]")

        add(LangKeys.INFO_INPUT, "Input:")
        add(LangKeys.INFO_INPUTS, "Inputs:")
        add(LangKeys.INFO_OUTPUT, "Output:")
        add(LangKeys.INFO_OUTPUTS, "Outputs:")
        add(LangKeys.INFO_POSITION, "Position: %d %d %d")
        add(LangKeys.INFO_PRODUCTION_TIME, "Production Time:")

        add(LangKeys.JEI_CATEGORY_ASSEMBLING, "Assembling")
        add(LangKeys.JEI_CATEGORY_BLASTING, "Blasting")
        add(LangKeys.JEI_CATEGORY_CHEMISTRY, "Chemistry")
        add(LangKeys.JEI_CATEGORY_CONSTRUCTING, "Constructing")
        add(LangKeys.JEI_CATEGORY_PRESSING, "Pressing")
        add(LangKeys.JEI_CATEGORY_SHREDDING, "Shredding")
        add(LangKeys.JEI_CATEGORY_SMITHING, "Smithing")
        add(LangKeys.JEI_CATEGORY_TEMPLATE_FOLDER, "Template Folder")
        add(LangKeys.JEI_EXPERIENCE, "%s XP")
        add(LangKeys.JEI_OUTPUT_CHANCE, "Output chance:")
        add(LangKeys.JEI_TIER_MINIMUM, "Minimum Tier: %s")
        add(LangKeys.JEI_TIER_RANGE, "Tier Range: %s..%s")

        add(LangKeys.SIREN_TRACK_LOOP, "Type: Loop")
        add(LangKeys.SIREN_TRACK_ONCE, "Type: Play Once")
        add(LangKeys.SIREN_TRACK_RANGE, "Range: %s Meters")
        add(LangKeys.SIREN_TRACK_SIREN_TRACK, "Siren Track")

        add(LangKeys.UPGRADE_INFO_ACCEPTED_UPGRADES, "Accepted Upgrades:")
        add(LangKeys.UPGRADE_INFO_CONSUMPTION, "Consumption: %s")
        add(LangKeys.UPGRADE_INFO_DELAY, "Delay: %s")
        add(LangKeys.UPGRADE_INFO_STACKS_TO, "Stacks to level %s")
        add(LangKeys.UPGRADE_NAME_OVERDRIVE, "Overdrive")
        add(LangKeys.UPGRADE_NAME_POWER_SAVING, "Power Saving")
        add(LangKeys.UPGRADE_NAME_SPEED, "Speed")
        add(LangKeys.UPGRADE_WARN_INCOMPATIBLE, "This upgrade is incompatible!")
        add(LangKeys.UPGRADE_WARN_MACHINE_NOT_UPGRADEABLE, "This machine is not upgradeable!")
        add(LangKeys.UPGRADE_WARN_NOT_A_MACHINE, "This is not a machine!")
        add(LangKeys.UPGRADE_WARN_VIEW_MACHINE, "View a machine for info about effects")
        add(LangKeys.UPGRADE_WARN_UNKNOWN_COMPATIBILITY, "Compatibility with the machine is unknown")

        add(LangKeys.WORD_SECONDS, "Seconds")
    }

    private fun addMaterials() = with(Materials) {
        addMaterial(coal, "Coal")
        addMaterial(iron, "Iron")
        addMaterial(copper, "Copper")
        addMaterial(gold, "Gold")
        addMaterial(redstone, "Redstone")
        addMaterial(emerald, "Emerald")
        addMaterial(lazuli, "Lapis Lazuli")
        addMaterial(diamond, "Diamond")

        addMaterial(actinium227, "Actinium-227")
        addMaterial(advancedAlloy, "Advanced Alloy")
        addMaterial(aluminium, "Aluminium")
        addMaterial(americium241, "Americium-241")
        addMaterial(americium242, "Americium-242")
        addMaterial(americiumFuel, "Americium Fuel")
        addMaterial(arsenic, "Arsenic")
        addMaterial(asbestos, "Asbestos")
        addMaterial(australium, "Australium")
        addMaterial(bakelite, "Bakelite")
        addMaterial(beryllium, "Beryllium")
        addMaterial(bismuth, "Bismuth")
        addMaterial(boron, "Boron")
        addMaterial(cobalt, "Cobalt")
        addMaterial(cobalt60, "Cobalt-60")
        addMaterial(combineSteel, "Combine Steel")
        addMaterial(daffergon, "Daffergon")
        addMaterial(desh, "Desh")
        addMaterial(dineutronium, "Dineutronium")
        addMaterial(electronium, "Electronium")
        addMaterial(euphemium, "Euphemium")
        addMaterial(ferricSchrabidate, "Ferric Schrabidate")
        addMaterial(fiberglass, "Fiberglass")
        addMaterial(fluorite, "Fluorite")
        addMaterial(ghiorsium336, "Ghiorsium-336")
        addMaterial(gold198, "Gold-198")
        addMaterial(graphite, "Graphite")
        addMaterial(hesFuel, "Highly Enriched Schrabidium Fuel")
        addMaterial(highSpeedSteel, "High-Speed Steel")
        addMaterial(insulator, "Insulator")
        addMaterial(lanthanum, "Lanthanum")
        addMaterial(lead, "Lead")
        addMaterial(lead209, "Lead-209")
        addMaterial(lesFuel, "Low Enriched Schrabidium Fuel")
        addMaterial(lignite, "Lignite")
        addMaterial(lithium, "Lithium")
        addMaterial(magnetizedTungsten, "Magnetized Tungsten")
        addMaterial(moxFuel, "MOX Fuel")
        addMaterial(naturalPlutonium, "Plutonium")
        addMaterial(naturalUranium, "Uranium")
        addMaterial(neptunium, "Neptunium")
        addMaterial(neptuniumFuel, "Neptunium Fuel")
        addMaterial(niobium, "Niobium")
        addMaterial(niter, "Niter")
        addMaterial(nuclearWaste, "Nuclear Waste")
        addMaterial(osmiridium, "Osmiridium")
        addMaterial(plutonium238, "Plutonium-238")
        addMaterial(plutonium239, "Plutonium-239")
        addMaterial(plutonium240, "Plutonium-240")
        addMaterial(plutonium241, "Plutonium-241")
        addMaterial(plutoniumFuel, "Plutonium Fuel")
        addMaterial(polonium, "Polonium")
        addMaterial(polymer, "Polymer")
        addMaterial(radium226, "Radium-226")
        addMaterial(reactorGradeAmericium, "Reactor Grade Americium")
        addMaterial(reactorGradePlutonium, "Reactor Grade Plutonium")
        addMaterial(redCopper, "Red Copper")
        addMaterial(redPhosphorus, "Red Phosphorus")
        addMaterial(reiium, "Reiium")
        addMaterial(rubber, "Rubber")
        addMaterial(saturnite, "Saturnite")
        addMaterial(schrabidium, "Schrabidium")
        addMaterial(schrabidiumFuel, "Schrabidium Fuel")
        addMaterial(schraranium, "Schraranium")
        addMaterial(solinium, "Solinium")
        addMaterial(starmetal, "Starmetal")
        addMaterial(steel, "Steel")
        addMaterial(strontium90, "Strontium-90")
        addMaterial(sulfur, "Sulfur")
        addMaterial(tantalium, "Tantalium")
        addMaterial(technetium99, "Technetium-99")
        addMaterial(technetiumSteel, "Technetium Steel")
        addMaterial(thorium, "Thorium-232")
        addMaterial(thoriumFuel, "Thorium Fuel")
        addMaterial(titanium, "Titanium")
        addMaterial(trinitite, "Trinitite")
        addMaterial(tungsten, "Tungsten")
        addMaterial(unobtainium, "Unobtainium")
        addMaterial(uranium233, "Uranium-233")
        addMaterial(uranium235, "Uranium-235")
        addMaterial(uranium238, "Uranium-238")
        addMaterial(uraniumFuel, "Uranium Fuel")
        addMaterial(verticium, "Verticium")
        addMaterial(weidanium, "Weidanium")
        addMaterial(whitePhosphorus, "White Phosphorus")
        addMaterial(yellowcake, "Yellowcake")
    }

    override val spawnEggSuffix = " Spawn Egg"

    override val oreFormat = "%s Ore"
    override val deepOreFormat = "Deepslate %s Ore"
    override val blockFormat = "Block of %s"
    override val rawFormat = "Raw %s"
    override val ingotFormat = "%s Ingot"
    override val nuggetFormat = "%s Nugget"
    override val crystalsFormat = "%s Crystals"
    override val powderFormat = "%s Powder"
    override val plateFormat = "%s Plate"
    override val wireFormat = "%s Wire"
}
