package at.martinthedragon.nucleartech.datagen.localisation

import at.martinthedragon.nucleartech.*
import at.martinthedragon.nucleartech.datagen.NuclearLanguageProviders
import at.martinthedragon.nucleartech.entities.EntityTypes
import at.martinthedragon.nucleartech.items.EffectItem
import at.martinthedragon.nucleartech.menus.MenuTypes
import at.martinthedragon.nucleartech.screens.AnvilScreen
import net.minecraft.data.DataGenerator

class EnUsLanguageProvider(dataGenerator: DataGenerator) : NuclearLanguageProvider(dataGenerator, NuclearLanguageProviders.EN_US) {
    override fun validate() {
        NuclearLanguageProviders.keys = translations.keys.toSet()
        NuclearLanguageProviders.materialTranslations = materialTranslations.toMap()
    }

    override fun translate() {
        add("itemGroup.${MODID}_parts", "NTM Resources and Parts")
        add("itemGroup.${MODID}_items", "NTM Machine Items and Fuel")
        add("itemGroup.${MODID}_templates", "NTM Templates")
        add("itemGroup.${MODID}_blocks", "NTM Ores and Blocks")
        add("itemGroup.${MODID}_machines", "NTM Machines")
        add("itemGroup.${MODID}_bombs", "NTM Bombs")
        add("itemGroup.${MODID}_consumables", "NTM Consumables and Gear")
        add("itemGroup.${MODID}_miscellaneous", "NTM Miscellaneous Items")

        add(EffectItem.EffectTypes.Radioactive.effectInfo.string, "[Radioactive]")
        add(EffectItem.EffectTypes.Blinding.effectInfo.string, "[Blinding]")
        add(EffectItem.EffectTypes.Hot.effectInfo.string, "[Pyrophoric / Hot]")

        addMaterials()

        addBlock(ModBlocks.scorchedUraniumOre, "Scorched Uranium Ore")
        addBlock(ModBlocks.oilDeposit, "Oil Deposit")
        addBlockDesc(ModBlocks.oilDeposit, "You weren't supposed to mine that.\nCome on, get a derrick you doofus.")
        addBlock(ModBlocks.emptyOilDeposit, "Empty Oil Deposit")
        addBlock(ModBlocks.oilSand, "Oil Sand")
        addBlock(ModBlocks.australianOre, "Australian Ore")
        addBlockDesc(ModBlocks.australianOre, "Australium Ore")
        addBlock(ModBlocks.weidite, "Weidite")
        addBlockDesc(ModBlocks.weidite, "Weidanium Ore")
        addBlock(ModBlocks.reiite, "Reiite")
        addBlockDesc(ModBlocks.reiite, "Reiium Ore")
        addBlock(ModBlocks.brightblendeOre, "Brightblende Ore")
        addBlockDesc(ModBlocks.brightblendeOre, "Unobtainium Ore")
        addBlock(ModBlocks.dellite, "Dellite")
        addBlockDesc(ModBlocks.dellite, "Daffergon Ore")
        addBlock(ModBlocks.dollarGreenMineral, "Dollar Green Mineral")
        addBlockDesc(ModBlocks.dollarGreenMineral, "Verticium Ore")
        addBlock(ModBlocks.rareEarthOre, "Rare Earth Ore")
        addBlock(ModBlocks.netherUraniumOre, "Nether Uranium Ore")
        addBlock(ModBlocks.scorchedNetherUraniumOre, "Scorched Nether Uranium Ore")
        addBlock(ModBlocks.netherPlutoniumOre, "Nether Plutonium Ore")
        addBlock(ModBlocks.netherTungstenOre, "Nether Tungsten Ore")
        addBlock(ModBlocks.netherSulfurOre, "Nether Sulfur Ore")
        addBlock(ModBlocks.netherPhosphorusOre, "Nether Phosphorus Ore")
        addBlock(ModBlocks.netherSchrabidiumOre, "Nether Schrabidium Ore")
        addBlock(ModBlocks.meteorUraniumOre, "Meteor Uranium Ore")
        addBlock(ModBlocks.meteorThoriumOre, "Meteor Thorium Ore")
        addBlock(ModBlocks.meteorTitaniumOre, "Meteor Titanium Ore")
        addBlock(ModBlocks.meteorSulfurOre, "Meteor Sulfur Ore")
        addBlock(ModBlocks.meteorCopperOre, "Meteor Copper Ore")
        addBlock(ModBlocks.meteorTungstenOre, "Meteor Tungsten Ore")
        addBlock(ModBlocks.meteorAluminiumOre, "Meteor Aluminium Ore")
        addBlock(ModBlocks.meteorLeadOre, "Meteor Lead Ore")
        addBlock(ModBlocks.meteorLithiumOre, "Meteor Lithium Ore")
        addBlock(ModBlocks.starmetalOre, "Starmetal Ore")
        addBlock(ModBlocks.trixite, "Trixite")

        addBlock(ModBlocks.scorchedDeepslateUraniumOre, "Scorched Deepslate Uranium Ore")
        addBlock(ModBlocks.deepslateOilDeposit, "Deepslate Oil Deposit")
        addBlockDesc(ModBlocks.deepslateOilDeposit, "You got this deep and still\ndon't know what to do? How?!")
        addBlock(ModBlocks.emptyDeepslateOilDeposit, "Empty Deepslate Oil Deposit")
        addBlock(ModBlocks.deepslateAustralianOre, "Deepslate Australian Ore")
        addBlockDesc(ModBlocks.deepslateAustralianOre, "Australium Ore")
        addBlock(ModBlocks.deepslateRareEarthOre, "Deepslate Rare Earth Ore")

        addBlock(ModBlocks.whitePhosphorusBlock, "Block of White Phosphorus")
        addBlock(ModBlocks.redPhosphorusBlock, "Block of Red Phosphorus")
        addBlock(ModBlocks.yellowcakeBlock, "Block of Yellowcake")
        addBlock(ModBlocks.scrapBlock, "Block of Scrap")
        addBlock(ModBlocks.electricalScrapBlock, "Block of Electrical Scrap")
        addBlock(ModBlocks.insulatorRoll, "Insulator Roll")
        addBlock(ModBlocks.fiberglassRoll, "Fiberglass Roll")
        addBlock(ModBlocks.trinititeBlock, "Block of Trinitite")
        addBlock(ModBlocks.nuclearWasteBlock, "Block of Nuclear Waste")
        addBlock(ModBlocks.schrabidiumCluster, "Schrabidium Cluster")
        addBlock(ModBlocks.euphemiumEtchedSchrabidiumCluster, "Euphemium Etched Schrabidium Cluster")
        addBlock(ModBlocks.deshReinforcedBlock, "Block of Reinforced Desh")

        addBlock(ModBlocks.titaniumDecoBlock, "Titanium Deco Block")
        addBlock(ModBlocks.redCopperDecoBlock, "Red Copper Deco Block")
        addBlock(ModBlocks.tungstenDecoBlock, "Tungsten Deco Block")
        addBlock(ModBlocks.aluminiumDecoBlock, "Aluminium Deco Block")
        addBlock(ModBlocks.steelDecoBlock, "Steel Deco Block")
        addBlock(ModBlocks.leadDecoBlock, "Lead Deco Block")
        addBlock(ModBlocks.berylliumDecoBlock, "Beryllium Deco Block")
        addBlock(ModBlocks.asbestosRoof, "Asbestos Roof")
        addBlock(ModBlocks.hazmatBlock, "Hazmat Block")

        addBlock(ModBlocks.glowingMushroom, "Glowing Mushroom")
        addBlock(ModBlocks.glowingMushroomBlock, "Glowing Mushroom Block")
        addBlock(ModBlocks.glowingMushroomStem, "Glowing Mushroom Stem")
        addBlock(ModBlocks.deadGrass, "Dead Grass")
        addBlock(ModBlocks.glowingMycelium, "Glowing Mycelium")
        addBlock(ModBlocks.trinitite, "Trinitite Ore")
        addBlock(ModBlocks.redTrinitite, "Red Trinitite Ore")
        addBlock(ModBlocks.charredLog, "Charred Log")
        addBlock(ModBlocks.charredPlanks, "Charred Planks")

        addBlock(ModBlocks.slakedSellafite, "Slaked Sellafite")
        addBlock(ModBlocks.sellafite, "Sellafite")
        addBlock(ModBlocks.hotSellafite, "Hot Sellafite")
        addBlock(ModBlocks.boilingSellafite, "Boiling Sellafite")
        addBlock(ModBlocks.blazingSellafite, "Blazing Sellafite")
        addBlock(ModBlocks.infernalSellafite, "Infernal Sellafite")
        addBlock(ModBlocks.sellafiteCorium, "Sellafite-Corium")

        addBlock(ModBlocks.siren, "Siren")
        addBlock(ModBlocks.safe, "Safe")
        addBlock(ModBlocks.ironAnvil, "Iron Anvil")
        addBlock(ModBlocks.leadAnvil, "Lead Anvil")
        addBlock(ModBlocks.steelAnvil, "Steel Anvil")
        addBlock(ModBlocks.meteoriteAnvil, "Meteorite Anvil")
        addBlock(ModBlocks.starmetalAnvil, "Starmetal Anvil")
        addBlock(ModBlocks.ferrouraniumAnvil, "Ferrouranium Anvil")
        addBlock(ModBlocks.bismuthAnvil, "Bismuth Anvil")
        addBlock(ModBlocks.schrabidateAnvil, "Ferric Schrabidate Anvil")
        addBlock(ModBlocks.dineutroniumAnvil, "Dineutronium Anvil")
        addBlock(ModBlocks.murkyAnvil, "Murky Anvil")
        addBlock(ModBlocks.steamPressBase, "Steam Press")
        addBlock(ModBlocks.steamPressFrame, "Steam Press")
        addBlock(ModBlocks.steamPressTop, "Steam Press")
        addBlock(ModBlocks.blastFurnace, "Blast Furnace")
        addBlock(ModBlocks.combustionGenerator, "Combustion Generator")
        addBlock(ModBlocks.electricFurnace, "Electric Furnace")
        addBlock(ModBlocks.shredder, "Shredder")
        addBlock(ModBlocks.assembler, "Assembler")
        addBlock(ModBlocks.assemblerPart, "Assembler")

        addBlock(ModBlocks.littleBoy, "Little Boy")
        addBlock(ModBlocks.fatMan, "Fat Man")

        addItem(ModItems.rawRareEarth, "Raw Rare Earth")
        addItem(ModItems.rawTrixite, "Raw Trixite")

        addItem(ModItems.th232Ingot, "Th232 Ingot")
        addItemDesc(ModItems.neptuniumIngot, "That one's my favorite!")
        addItemDesc(ModItems.schraraniumIngot, "Made from uranium in a schrabidium transmutator")
        addItemDesc(ModItems.combineSteelIngot, "*insert Civil Protection reference here*")
        addItem(ModItems.lanthanumIngot, "Semi-Stable Lanthanum Ingot")
        addItem(ModItems.actiniumIngot, "Semi-Stable Actinium Ingot")
        addItemDesc(ModItems.euphemiumIngot, "A very special and yet strange element")
        addItem(ModItems.whitePhosphorusIngot, "White Phosphorus Bar")

        addItem(ModItems.semtexBar, "Semtex Bar")
        addItemDesc(ModItems.semtexBar,
            "Semtex H Plastic Explosive\n" +
                    "Performant explosive for many applications.\n" +
                    "Edible"
        )

        addItem(ModItems.lithiumCube, "Lithium Cube")
        addItem(ModItems.solidFuelCube, "Solid Fuel Cube")
        addItem(ModItems.solidRocketFuelCube, "Solid Rocket Fuel Cube")

        addItem(ModItems.fiberglassSheet, "Fiberglass Sheet")
        addItemDesc(ModItems.fiberglassSheet, "High in fiber, high in glass. Everything the body needs.")
        addItem(ModItems.asbestosSheet, "Asbestos Sheet")
        addItemDesc(ModItems.asbestosSheet, "§o„Filled with life, self-doubt and asbestos. That comes with the air.“")

        addItem(ModItems.mercuryDroplet, "Mercury Droplet")
        addItem(ModItems.mercuryBottle, "Mercury Bottle")

        addItem(ModItems.coke, "Coke")
        addItem(ModItems.lignite, "Lignite")
        addItem(ModItems.ligniteBriquette, "Lignite Briquette")

        addItem(ModItems.sulfur, "Sulfur")
        addItem(ModItems.niter, "Niter")
        addItem(ModItems.fluorite, "Fluorite")
        addItem(ModItems.quartzPowder, "Quartz Powder")
        addItem(ModItems.yellowcake, "Yellowcake")
        addItem(ModItems.chlorophytePowder, "Chlorophyte Powder")
        addItem(ModItems.neodymiumPowder, "Neodymium Powder")
        addItem(ModItems.niobiumPowder, "Niobium Powder")
        addItem(ModItems.ceriumPowder, "Cerium Powder")
        addItemDesc(ModItems.asbestosPowder, "§o„Sniffffffff - MHHHHHHMHHHHHHHHH“")
        addItem(ModItems.enchantmentPowder, "Enchantment Powder")
        addItem(ModItems.cloudResidue, "Cloud Residue")
        addItem(ModItems.thermonuclearAshes, "Thermonuclear Ashes")
        addItem(ModItems.semtexMix, "Semtex Mix")
        addItem(ModItems.deshMix, "Desh Mix")
        addItem(ModItems.deshReadyMix, "DeshReady™ Mix")
        addItem(ModItems.nitaniumMix, "Nitanium Mix")
        addItem(ModItems.sparkMix, "Spark Mix")
        addItem(ModItems.meteoritePowder, "Meteorite Powder")
        addItemDesc(ModItems.euphemiumPowder, "Pulverized pink.\nTastes like strawberries.")
        addItem(ModItems.desaturatedRedstone, "Desaturated Redstone")
        addItem(ModItems.dust, "Dust")
        addItemDesc(ModItems.dust, "I hate dust!")
        addItem(ModItems.tinyLithiumPowder, "Tiny Lithium Powder")
        addItem(ModItems.tinyNeodymiumPowder, "Tiny Neodymium Powder")
        addItem(ModItems.tinyCobaltPowder, "Tiny Cobalt Powder")
        addItem(ModItems.tinyNiobiumPowder, "Tiny Niobium Powder")
        addItem(ModItems.tinyCeriumPowder, "Tiny Cerium Powder")
        addItem(ModItems.tinyLanthanumPowder, "Tiny Lanthanum Powder")
        addItem(ModItems.tinyActiniumPowder, "Tiny Actinium Powder")
        addItem(ModItems.tinyMeteoritePowder, "Tiny Meteorite Powder")
        addItem(ModItems.redPhosphorus, "Red Phosphorus")
        addItemDesc(ModItems.redPhosphorus, "Used in multi purpose bombs:\nIncendiary bombs are fun!")
        addItem(ModItems.cryoPowder, "Cryo Powder")
        addItem(ModItems.poisonPowder, "Poison Powder")
        addItemDesc(ModItems.poisonPowder, "Used in multi purpose bombs:\nWarning: Poisonous!")
        addItem(ModItems.thermite, "Thermite")
        addItem(ModItems.energyPowder, "Energy Powder")

        addItem(ModItems.cordite, "Cordite")
        addItem(ModItems.ballistite, "Ballistite")

        addItem(ModItems.rareEarthCrystals, "Rare Earth Crystals")
        addItem(ModItems.redPhosphorusCrystals, "Red Phosphorus Crystals")
        addItem(ModItems.trixiteCrystals, "Trixite Crystals")

        addItem(ModItems.neodymiumFragment, "Neodymium Fragment")
        addItem(ModItems.cobaltFragment, "Cobalt Fragment")
        addItem(ModItems.niobiumFragment, "Niobium Fragment")
        addItem(ModItems.ceriumFragment, "Cerium Fragment")
        addItem(ModItems.lanthanumFragment, "Lanthanum Fragment")
        addItem(ModItems.actiniumFragment, "Actinium Fragment")
        addItem(ModItems.meteoriteFragment, "Meteorite Fragment")

        addItem(ModItems.biomass, "Biomass")
        addItem(ModItems.compressedBiomass, "Compressed Biomass")

        addItem(ModItems.th232Nugget, "Th232 Nugget")
        addItemDesc(ModItems.euphemiumNugget,
            "A small piece of a pink metal.\n" +
                    "Its properties are still unknown,\n" +
                    "DEAL WITH IT carefully."
        )

        addItem(ModItems.neutronReflector, "Neutron Reflector")
        addItem(ModItems.mixedPlate, "Mixed Plate")
        addItem(ModItems.paAAlloyPlate, "PaA Alloy Plate")
        addItem(ModItems.insulator, "Insulator")
        addItem(ModItems.kevlarCeramicCompound, "Kevlar-Ceramic Compound")
        addItem(ModItems.dalekaniumPlate, "Angry Metal")
        addItem(ModItems.deshCompoundPlate, "Desh Compound Plate")
        addItem(ModItems.euphemiumCompoundPlate, "Euphemium Compound Plate")
        addItem(ModItems.dineutroniumCompoundPlate, "Dineutronium Compound Plate")
        addItem(ModItems.copperPanel, "Copper Panel")

        addItem(ModItems.highSpeedSteelBolt, "High-Speed Steel Bolt")
        addItem(ModItems.tungstenBolt, "Tungsten Bolt")
        addItem(ModItems.reinforcedTurbineShaft, "Reinforced Turbine Shaft")

        addItem(ModItems.hazmatCloth, "Hazmat Cloth")
        addItem(ModItems.advancedHazmatCloth, "Advanced Hazmat Cloth")
        addItem(ModItems.leadReinforcedHazmatCloth, "Lead-Reinforced Hazmat Cloth")
        addItem(ModItems.fireProximityCloth, "Fire Proximity Cloth")
        addItem(ModItems.activatedCarbonFilter, "Activated Carbon Filter")

        addItem(ModItems.superConductor, "Super Conductor")
        addItem(ModItems.highTemperatureSuperConductor, "4000K High Temperature Super Conductor")

        addItem(ModItems.copperCoil, "Copper Coil")
        addItem(ModItems.ringCoil, "Ring Coil")
        addItem(ModItems.superConductingCoil, "Super Conducting Coil")
        addItem(ModItems.superConductingRingCoil, "Super Conducting Ring Coil")
        addItem(ModItems.goldCoil, "Gold Coil")
        addItem(ModItems.goldRingCoil, "Gold Ring Coil")
        addItem(ModItems.heatingCoil, "Heating Coil")
        addItem(ModItems.highTemperatureSuperConductingCoil, "4000K High Temperature Super Conducting Coil")

        addItem(ModItems.steelTank, "Steel Tank")
        addItem(ModItems.motor, "Motor")
        addItem(ModItems.centrifugeElement, "Centrifuge Element")
        addItem(ModItems.centrifugeTower, "Centrifuge Tower")
        addItem(ModItems.deeMagnets, "Dee Magnets")
        addItem(ModItems.flatMagnet, "Flat Magnet")
        addItem(ModItems.cyclotronTower, "Cyclotron Tower")
        addItem(ModItems.breedingReactorCore, "Breeding Reactor Core")
        addItem(ModItems.rtgUnit, "RTG Unit")
        addItem(ModItems.thermalDistributionUnit, "Thermal Distribution Unit")
        addItem(ModItems.endothermicDistributionUnit, "Endothermic Distribution Unit")
        addItem(ModItems.exothermicDistributionUnit, "Exothermic Distribution Unit")
        addItem(ModItems.gravityManipulator, "Gravity Manipulator")
        addItem(ModItems.steelPipes, "Steel Pipes")
        addItem(ModItems.titaniumDrill, "Titanium Drill")
        addItem(ModItems.photovoltaicPanel, "Photovoltaic Panel")
        addItem(ModItems.chlorinePinwheel, "Chlorine Pinwheel")
        addItem(ModItems.telepad, "Telepad")
        addItem(ModItems.entanglementKit, "Entaglement Kit")
        addItemDesc(ModItems.entanglementKit,
            "Teleporter crafting item.\n" +
                    "Enables dimension-shifting via\n" +
                    "beryllium-enhanced resource scanner."
        )
        addItem(ModItems.stabilizerComponent, "Stabilizer Component")
        addItem(ModItems.emitterComponent, "Emitter Component")
        addItem(ModItems.aluminiumCap, "Aluminium Cap")
        addItem(ModItems.smallSteelShell, "Small Steel Shell")
        addItem(ModItems.smallAluminiumShell, "Small Aluminium Shell")
        addItem(ModItems.bigSteelShell, "Big Steel Shell")
        addItem(ModItems.bigAluminiumShell, "Big Aluminium Shell")
        addItem(ModItems.bigTitaniumShell, "Big Titanium Shell")
        addItem(ModItems.flatSteelCasing, "Flat Steel Casing")
        addItem(ModItems.smallSteelGridFins, "Small Steel Grid Fins")
        addItem(ModItems.bigSteelGridFins, "Big Steel Grid Fins")
        addItem(ModItems.largeSteelFins, "Large Steel Fins")
        addItem(ModItems.smallTitaniumFins, "Small Titanium Fins")
        addItem(ModItems.steelSphere, "Steel Sphere")
        addItem(ModItems.steelPedestal, "Steel Pedestal")
        addItem(ModItems.dysfunctionalNuclearReactor, "Dysfunctional Nuclear Reactor")
        addItem(ModItems.largeSteelRotor, "Large Steel Rotor")
        addItem(ModItems.generatorBody, "Generator Body")
        addItem(ModItems.titaniumBlade, "Titanium Blade")
        addItem(ModItems.tungstenReinforcedBlade, "Tungsten Reinforced Blade")
        addItem(ModItems.titaniumSteamTurbine, "Titanium Steam Turbine")
        addItem(ModItems.reinforcedTurbofanBlades, "Reinforced Turbofan Blades")
        addItem(ModItems.generatorFront, "Generator Front")
        addItem(ModItems.toothpicks, "Toothpicks")
        addItem(ModItems.ductTape, "Duct Tape")
        addItem(ModItems.clayCatalyst, "Clay Catalyst")
        addItem(ModItems.smallMissileAssembly, "Small Missile Assembly")

        addItem(ModItems.smallWarhead, "Small Warhead")
        addItem(ModItems.mediumWarhead, "Medium Warhead")
        addItem(ModItems.largeWarhead, "Large Warhead")
        addItem(ModItems.smallIncendiaryWarhead, "Small Incendiary Warhead")
        addItem(ModItems.mediumIncendiaryWarhead, "Medium Incendiary Warhead")
        addItem(ModItems.largeIncendiaryWarhead, "Large Incendiary Warhead")
        addItem(ModItems.smallClusterWarhead, "Small Cluster Warhead")
        addItem(ModItems.mediumClusterWarhead, "Medium Cluster Warhead")
        addItem(ModItems.largeClusterWarhead, "Large Cluster Warhead")
        addItem(ModItems.smallBunkerBusterWarhead, "Small Bunker Busting Warhead")
        addItem(ModItems.mediumBunkerBusterWarhead, "Medium Bunker Busting Warhead")
        addItem(ModItems.largeBunkerBusterWarhead, "Large Bunker Busting Warhead")
        addItem(ModItems.nuclearWarhead, "Nuclear Warhead")
        addItem(ModItems.thermonuclearWarhead, "Thermonuclear Warhead")
        addItem(ModItems.endothermicWarhead, "Endothermic Warhead")
        addItem(ModItems.exothermicWarhead, "Exothermic Warhead")

        addItem(ModItems.smallFuelTank, "Small Fuel Tank")
        addItem(ModItems.mediumFuelTank, "Medium Fuel Tank")
        addItem(ModItems.largeFuelTank, "Large Fuel Tank")

        addItem(ModItems.smallThruster, "Small Thruster")
        addItem(ModItems.mediumThruster, "Medium Thruster")
        addItem(ModItems.largeThruster, "Large Thruster")
        addItem(ModItems.lvnNuclearRocketEngine, "LV-N Nuclear Rocket Engine")

        addItem(ModItems.satelliteBase, "Satellite Base")
        addItem(ModItems.highGainOpticalCamera, "High-Gain Optical Camera")
        addItem(ModItems.m700SurveyScanner, "M700 Survey Scanner")
        addItem(ModItems.radarDish, "Radar Dish")
        addItem(ModItems.deathRay, "Death Ray")
        addItem(ModItems.xeniumResonator, "Xenium Resonator")

        addItem(ModItems.size10Connector, "Size 10 Connector")
        addItem(ModItems.size15Connector, "Size 15 Connector")
        addItem(ModItems.size20Connector, "Size 20 Connector")

        addItem(ModItems.hunterChopperCockpit, "Hunter Chopper Cockpit")
        addItem(ModItems.emplacementGun, "Emplacement Gun")
        addItem(ModItems.hunterChopperBody, "Hunter Chopper Body")
        addItem(ModItems.hunterChopperTail, "Hunter Chopper Tail")
        addItem(ModItems.hunterChopperWing, "Hunter Chopper Wing")
        addItem(ModItems.hunterChopperRotorBlades, "Hunter Chopper Rotor Blades")
        addItem(ModItems.combineScrapMetal, "Combine Scrap Metal")

        addItem(ModItems.heavyHammerHead, "Heavy Hammer Head")
        addItem(ModItems.heavyAxeHead, "Heavy Axe Head")
        addItem(ModItems.reinforcedPolymerHandle, "Reinforced Polymer Handle")

        addItem(ModItems.basicCircuitAssembly, "Basic Circuit Assembly")
        addItem(ModItems.basicCircuit, "Basic Circuit")
        addItem(ModItems.enhancedCircuit, "Enhanced Circuit")
        addItem(ModItems.advancedCircuit, "Advanced Circuit")
        addItem(ModItems.overclockedCircuit, "Overclocked Circuit")
        addItem(ModItems.highPerformanceCircuit, "High Performance Circuit")
        addItem(ModItems.militaryGradeCircuitBoardTier1, "Military Grade Circuit Board (Tier 1)")
        addItem(ModItems.militaryGradeCircuitBoardTier2, "Military Grade Circuit Board (Tier 2)")
        addItem(ModItems.militaryGradeCircuitBoardTier3, "Military Grade Circuit Board (Tier 3)")
        addItem(ModItems.militaryGradeCircuitBoardTier4, "Military Grade Circuit Board (Tier 4)")
        addItem(ModItems.militaryGradeCircuitBoardTier5, "Military Grade Circuit Board (Tier 5)")
        addItem(ModItems.militaryGradeCircuitBoardTier6, "Military Grade Circuit Board (Tier 6)")

        addItem(ModItems.revolverMechanism, "Revolver Mechanism")
        addItem(ModItems.advancedRevolverMechanism, "Advanced Revolver Mechanism")
        addItem(ModItems.rifleMechanism, "Rifle Mechanism")
        addItem(ModItems.advancedRifleMechanism, "Advanced Rifle Mechanism")
        addItem(ModItems.launcherMechanism, "Launcher Mechanism")
        addItem(ModItems.advancedLauncherMechanism, "Advanced Launcher Mechanism")
        addItem(ModItems.highTechWeaponMechanism, "High-Tech Weapon Mechanism")

        addItem(ModItems.point357MagnumPrimer, ".357 Magnum Primer (x16)")
        addItem(ModItems.point44MagnumPrimer, ".44 Magnum Primer (x16)")
        addItem(ModItems.smallCaliberPrimer, "Small Caliber Primer (x24)")
        addItem(ModItems.largeCaliberPrimer, "Large Caliber Primer (x8)")
        addItem(ModItems.buckshotPrimer, "Buckshot Primer (x8)")

        addItem(ModItems.point357MagnumCasing, ".357 Magnum Casing (x16)")
        addItem(ModItems.point44MagnumCasing, ".44 Magnum Casing (x16)")
        addItem(ModItems.smallCaliberCasing, "Small Caliber Casing (x24)")
        addItem(ModItems.largeCaliberCasing, "Large Caliber Casing (x8)")
        addItem(ModItems.buckshotCasing, "Buckshot Casing (x8)")

        addItem(ModItems.ironBulletAssembly, "Iron Bullet Assembly")
        addItem(ModItems.leadBulletAssembly, "Lead Bullet Assembly")
        addItem(ModItems.glassBulletAssembly, "Glass Bullet Assembly")
        addItem(ModItems.goldBulletAssembly, "Gold Bullet Assembly")
        addItem(ModItems.schrabidiumBulletAssembly, "Schrabidium Bullet Assembly")
        addItem(ModItems.nightmareBulletAssembly, "Nightmare Bullet Assembly")
        addItem(ModItems.deshBulletAssembly, "Desh Bullet Assembly")
        addItem(ModItems.point44MagnumAssembly, ".44 Magnum Assembly")
        addItem(ModItems.nineMmAssembly, "9mm Assembly")
        addItem(ModItems.fivePoint56mmAssembly, "5.56mm Assembly")
        addItem(ModItems.point22LRAssembly, ".22 LR Assembly")
        addItem(ModItems.point5mmAssembly, ".5mm Assembly")
        addItem(ModItems.point50AEAssembly, ".50 AE Assembly")
        addItem(ModItems.point50BMGAssembly, ".50 BMG Assembly")

        addItem(ModItems.silverBulletCasing, "Silver Bullet Casing")
        addItem(ModItems.twelvePoint8cmStarmetalHighEnergyShell, "12.8cm Starmetal High-Energy Shell")
        addItem(ModItems.twelvePoint8cmNuclearShell, "12.8cm Nuclear Shell")
        addItem(ModItems.twelvePoint8cmDUShell, "12.8cm DU-Shell")

        addItem(ModItems.cableDrum, "Cable Drum")
        addItemDesc(ModItems.cableDrum, "Right-click poles to connect")
        addItem(ModItems.paintingOfACartoonPony, "Painting of a Cartoon Pony")
        addItemDesc(ModItems.paintingOfACartoonPony, "Yellow horse beats blue horse, that's a proven fact!")
        addItem(ModItems.conspiracyTheory, "Conspiracy Theory")
        addItemDesc(ModItems.conspiracyTheory, "Steel beams can't melt jet fuel!")
        addItem(ModItems.politicalTopic, "Political Topic")
        addItemDesc(ModItems.politicalTopic, "Donald Duck will build the wall!")
        addItem(ModItems.ownOpinion, "Own Opinion")
        addItemDesc(ModItems.ownOpinion, "Well, I like it...")

        addItem(ModItems.explosivePellets, "Explosive Pellets")
        addItemDesc(ModItems.explosivePellets, "Used in multi purpose bombs:\nAdds some extra boom!")
        addItem(ModItems.leadPellets, "Lead Pellets")
        addItem(ModItems.flechettes, "Flechettes")
        addItem(ModItems.poisonGasCartridge, "Poison Gas Cartridge")
        addItemDesc(ModItems.poisonGasCartridge, "Used in multi purpose bombs:\n*cough cough* Halp pls!")
        addItem(ModItems.magnetron, "Magnetron")
        addItem(ModItems.denseCoalCluster, "Dense Coal Cluster")
        addItem(ModItems.burntBark, "Burnt Bark")
        addItemDesc(ModItems.burntBark, "A piece of bark from an exploded golden oak tree.")
        addItem(ModItems.machineUpgradeTemplate, "Machine Upgrade Template")

        addItem(ModItems.blankRune, "Blank Catalyst Matrix")
        addItem(ModItems.isaRune, "Cool Catalyst Matrix")
        addItem(ModItems.dagazRune, "Balanced Catalyst Matrix")
        addItem(ModItems.hagalazRune, "Rough Catalyst Matrix")
        addItem(ModItems.jeraRune, "Multiplicative Catalyst Matrix")
        addItem(ModItems.thurisazRune, "Additive Catalyst Matrix")

        addItem(ModItems.burnedOutQuadSchrabidiumFuelRod, "Burned Out Quad Schrabidium Rod")
        addItemDesc(ModItems.burnedOutQuadSchrabidiumFuelRod, "A quad fuel rod which contains a\nvery small amount of a strange new element.")

        addItem(ModItems.scrap, "Scrap")
        addItem(ModItems.hotDepletedUraniumFuel, "Hot Depleted Uranium Fuel")
        addItem(ModItems.hotDepletedThoriumFuel, "Hot Depleted Thorium Fuel")
        addItem(ModItems.hotDepletedPlutoniumFuel, "Hot Depleted Plutonium Fuel")
        addItem(ModItems.hotDepletedMOXFuel, "Hot Depleted MOX Fuel")
        addItem(ModItems.hotDepletedSchrabidiumFuel, "Hot Depleted Schrabidium Fuel")
        addItem(ModItems.depletedUraniumFuel, "Depleted Uranium Fuel")
        addItem(ModItems.depletedThoriumFuel, "Depleted Thorium Fuel")
        addItem(ModItems.depletedPlutoniumFuel, "Depleted Plutonium Fuel")
        addItem(ModItems.depletedMOXFuel, "Depleted MOX Fuel")
        addItem(ModItems.depletedSchrabidiumFuel, "Depleted Schrabidium Fuel")
        addItem(ModItems.trinitite, "Trinitite")
        addItem(ModItems.nuclearWaste, "Nuclear Waste")
        addItem(ModItems.tinyNuclearWaste, "Tiny Nuclear Waste")

        addItem(ModItems.crystalHorn, "Crystal Horn")
        addItemDesc(ModItems.crystalHorn, "An actual horn.")
        addItem(ModItems.charredCrystal, "Charred Crystal")
        addItemDesc(ModItems.charredCrystal, "Also a real horn. Weird, right?")

        add("item.$MODID.batteries.energy_stored", "Energy Stored: %s/%sHE")
        add("item.$MODID.batteries.charge_rate", "Charge Rate: %sHE/t")
        add("item.$MODID.batteries.discharge_rate", "Discharge Rate: %sHE/t")
        addItem(ModItems.battery, "Battery")
        addItem(ModItems.redstonePowerCell, "Redstone Power Cell")
        addItem(ModItems.sixfoldRedstonePowerCell, "Sixfold Redstone Power Cell")
        addItem(ModItems.twentyFourFoldRedstonePowerCell, "24-Fold Redstone Power Cell")
        addItem(ModItems.advancedBattery, "Advanced Battery")
        addItem(ModItems.advancedPowerCell, "Advanced Power Cell")
        addItem(ModItems.quadrupleAdvancedPowerCell, "Quadruple Advanced Power Cell")
        addItem(ModItems.twelveFoldAdvancedPowerCell, "Twelvefold Advanced Power Cell")
        addItem(ModItems.lithiumBattery, "Lithium-Ion Battery")
        addItem(ModItems.lithiumPowerCell, "Lithium-Ion Power Cell")
        addItem(ModItems.tripleLithiumPowerCell, "Triple Lithium-Ion Power Cell")
        addItem(ModItems.sixfoldLithiumPowerCell, "Sixfold Lithium-Ion Power Cell")
        addItem(ModItems.schrabidiumBattery, "Schrabidium Battery")
        addItem(ModItems.schrabidiumPowerCell, "Schrabidium Power Cell")
        addItem(ModItems.doubleSchrabidiumPowerCell, "Double Schrabidium Power Cell")
        addItem(ModItems.quadrupleSchrabidiumPowerCell, "Quadruple Schrabidium Power Cell")
        addItem(ModItems.sparkBattery, "Spark Battery")
        addItem(ModItems.offBrandSparkBattery, "Off-Brand Spark Battery")
        addItem(ModItems.sparkPowerCell, "Spark Power Cell")
        addItem(ModItems.sparkArcaneCarBattery, "Spark Arcane Car Battery")
        addItem(ModItems.sparkArcaneEnergyStorageArray, "Spark Arcane Energy Storage Array")
        addItem(ModItems.sparkArcaneMassEnergyVoid, "Spark Arcane Mass-Energy Void")
        addItem(ModItems.sparkArcaneDiracSea, "Spark Arcane Dirac Sea")
        addItem(ModItems.sparkSolidSpaceTimeCrystal, "Spark Solid Space-Time Crystal")
        addItem(ModItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit, "Spark Ludicrous Physics-Defying Energy Storage Unit")
        addItem(ModItems.infiniteBattery, "Infinite Battery")
        addItem(ModItems.singleUseBattery, "Single-Use Battery")
        addItem(ModItems.largeSingleUseBattery, "Large Single-Use Battery")
        addItem(ModItems.potatoBattery, "Potato Battery")
        addItem(ModItems.steamPoweredEnergyStorageTank, "Steam-Powered Energy Storage Tank")
        addItem(ModItems.largeSteamPoweredEnergyStorageTank, "Large Steam-Powered Energy Storage Tank")

        addItem(ModItems.stoneFlatStamp, "Flat Stamp (Stone)")
        addItem(ModItems.stonePlateStamp, "Plate Stamp (Stone)")
        addItem(ModItems.stoneWireStamp, "Wire Stamp (Stone)")
        addItem(ModItems.stoneCircuitStamp, "Circuit Stamp (Stone)")
        addItem(ModItems.ironFlatStamp, "Flat Stamp (Iron)")
        addItem(ModItems.ironPlateStamp, "Plate Stamp (Iron)")
        addItem(ModItems.ironWireStamp, "Wire Stamp (Iron)")
        addItem(ModItems.ironCircuitStamp, "Circuit Stamp (Iron)")
        addItem(ModItems.steelFlatStamp, "Flat Stamp (Steel)")
        addItem(ModItems.steelPlateStamp, "Plate Stamp (Steel)")
        addItem(ModItems.steelWireStamp, "Wire Stamp (Steel)")
        addItem(ModItems.steelCircuitStamp, "Circuit Stamp (Steel)")
        addItem(ModItems.titaniumFlatStamp, "Flat Stamp (Titanium)")
        addItem(ModItems.titaniumPlateStamp, "Plate Stamp (Titanium)")
        addItem(ModItems.titaniumWireStamp, "Wire Stamp (Titanium)")
        addItem(ModItems.titaniumCircuitStamp, "Circuit Stamp (Titanium)")
        addItem(ModItems.obsidianFlatStamp, "Flat Stamp (Obsidian)")
        addItem(ModItems.obsidianPlateStamp, "Plate Stamp (Obsidian)")
        addItem(ModItems.obsidianWireStamp, "Wire Stamp (Obsidian)")
        addItem(ModItems.obsidianCircuitStamp, "Circuit Stamp (Obsidian)")
        addItem(ModItems.schrabidiumFlatStamp, "Flat Stamp (Schrabidium)")
        addItem(ModItems.schrabidiumPlateStamp, "Plate Stamp (Schrabidium)")
        addItem(ModItems.schrabidiumWireStamp, "Wire Stamp (Schrabidium)")
        addItem(ModItems.schrabidiumCircuitStamp, "Circuit Stamp (Schrabidium)")

        addItem(ModItems.aluminiumShredderBlade, "Aluminium Shredder Blade")
        addItem(ModItems.goldShredderBlade, "Gold Shredder Blade")
        addItem(ModItems.ironShredderBlade, "Iron Shredder Blade")
        addItem(ModItems.steelShredderBlade, "Steel Shredder Blade")
        addItem(ModItems.titaniumShredderBlade, "Titanium Shredder Blade")
        addItem(ModItems.advancedAlloyShredderBlade, "Advanced Alloy Shredder Blade")
        addItem(ModItems.combineSteelShredderBlade, "Combine Steel Shredder Blade")
        addItem(ModItems.schrabidiumShredderBlade, "Schrabidium Shredder Blade")
        addItem(ModItems.deshShredderBlade, "Desh Shredder Blade")

        addItem(ModItems.machineTemplateFolder, "Machine Template Folder")
        addItemDesc(ModItems.machineTemplateFolder,
            "Machine Templates: Paper + Dye\n" +
                    "Fluid IDs: Iron Plate + Dye\n" +
                    "Press Stamps: Flat Stamp\n" +
                    "Siren Tracks: Insulator + Steel Plate"
        )

        add("item.$MODID.siren_tracks.siren_track", "Siren Track")
        add("item.$MODID.siren_tracks.type_loop", "Type: Loop")
        add("item.$MODID.siren_tracks.type_once", "Type: Play Once")
        add("item.$MODID.siren_tracks.range", "Range: %s Meters")
        addItem(ModItems.sirenTrackHatchSiren, "Hatch Siren")
        addItem(ModItems.sirenTrackAutopilotDisconnected, "Autopilot Disconnected")
        addItem(ModItems.sirenTrackAMSSiren, "AMS Siren")
        addItem(ModItems.sirenTrackBlastDoorAlarm, "Blast Door Alarm")
        addItem(ModItems.sirenTrackAPCSiren, "APC Siren")
        addItem(ModItems.sirenTrackKlaxon, "Klaxon")
        addItem(ModItems.sirenTrackVaultDoorAlarm, "Vault Door Alarm")
        addItem(ModItems.sirenTrackSecurityAlert, "Security Alert")
        addItem(ModItems.sirenTrackStandardSiren, "Standard Siren")
        addItem(ModItems.sirenTrackClassicSiren, "Classic Siren")
        addItem(ModItems.sirenTrackBankAlarm, "Bank Alarm")
        addItem(ModItems.sirenTrackBeepSiren, "Beep Siren")
        addItem(ModItems.sirenTrackContainerAlarm, "Container Alarm")
        addItem(ModItems.sirenTrackSweepSiren, "Sweep Siren")
        addItem(ModItems.sirenTrackMissileSiloSiren, "Missile Silo Siren")
        addItem(ModItems.sirenTrackAirRaidSiren, "Air Raid Siren")
        addItem(ModItems.sirenTrackNostromoSelfDestruct, "Nostromo Self Destruct")
        addItem(ModItems.sirenTrackEASAlarmScreech, "EAS Alarm Screech")
        addItem(ModItems.sirenTrackAPCPass, "APC Pass")
        addItem(ModItems.sirenTrackRazortrainHorn, "Razortrain Horn")

        addItem(ModItems.assemblyTemplate, "Assembly Template: %s")
        add("info.template.in", "Inputs:")
        add("info.template.out", "Output:")
        add("info.template.time", "Production Time:")
        add("info.template.seconds", "Seconds")

        run {
            val usedInLittleBoy = "Used in:\nLittle Boy"
            addItem(ModItems.neutronShieldingLittleBoy, "Neutron Shielding")
            addItemDesc(ModItems.neutronShieldingLittleBoy, usedInLittleBoy)
            addItem(ModItems.subcriticalUraniumTarget, "Subcritical U235 Target")
            addItemDesc(ModItems.subcriticalUraniumTarget, usedInLittleBoy)
            addItem(ModItems.uraniumProjectile, "U235 Projectile")
            addItemDesc(ModItems.uraniumProjectile, usedInLittleBoy)
            addItem(ModItems.propellantLittleBoy, "Propellant")
            addItemDesc(ModItems.propellantLittleBoy, usedInLittleBoy)
            addItem(ModItems.bombIgniterLittleBoy, "Bomb Igniter")
            addItemDesc(ModItems.bombIgniterLittleBoy, usedInLittleBoy)
        }
        addItem(ModItems.bundleOfImplosionPropellant, "Bundle of Implosion Propellant")
        addItemDesc(ModItems.bundleOfImplosionPropellant, "Used in:\nFat Man\nIvy Mike\nTsar Bomba")
        addItem(ModItems.bombIgniterFatMan, "Bomb Igniter")
        addItemDesc(ModItems.bombIgniterFatMan, "Used in Fat Man")
        addItem(ModItems.plutoniumCore, "Plutonium Core")
        addItemDesc(ModItems.plutoniumCore, "Used in:\nFat Man\nIvy Mike\nTsar Bomba")
        addItem(ModItems.detonator, "Detonator")
        addItemDesc(ModItems.detonator, "Shift-right-click an explosive to set the position,\nright-click to detonate!")
        val detonatorDescriptionId = ModItems.detonator.get().descriptionId
        add("$detonatorDescriptionId.tooltip_no_position_set", "No position set!")
        add("$detonatorDescriptionId.position_set", "Position set!")
        add("$detonatorDescriptionId.error_position_not_set", "Position has not been set!")
        add("$detonatorDescriptionId.error_position_not_loaded", "Target is currently not loaded in the world!")
        add("$detonatorDescriptionId.error_not_explosive", "Target is not a valid explosive!")
        add("$detonatorDescriptionId.error_invalid_tile_entity", "Server Error: The target's BlockEntity is invalid!")
        add("$detonatorDescriptionId.error_missing_components", "The explosive is missing components!")
        add("$detonatorDescriptionId.error_detonation_prohibited", "The detonation was prohibited!")
        add("$detonatorDescriptionId.error_unknown", "An unknown error occurred during the detonation")
        add("$detonatorDescriptionId.detonation_successful", "Detonated!")
        addItem(ModItems.littleBoyKit, "Little Boy Kit")
        addItem(ModItems.fatManKit, "Fat Man Kit")

        addItem(ModItems.oilDetector, "Oil Reservoir Detector")
        addItemDesc(ModItems.oilDetector, "Right-click to scan for oil.\nDetector will only find large deposits.")
        add(ModItems.oilDetector.get().descriptionId + ".below", "Oil deposit directly below!")
        add(ModItems.oilDetector.get().descriptionId + ".near", "Oil deposit detected nearby")
        add(ModItems.oilDetector.get().descriptionId + ".no_oil", "No oil detected")
        addItem(ModItems.geigerCounter, "Handheld Geiger Counter")

        addItem(ModItems.ivBag, "IV Bag")
        addItem(ModItems.bloodBag, "Blood Bag")
        addItem(ModItems.emptyExperienceBag, "Empty Experience Bag")
        addItem(ModItems.experienceBag, "Experience Bag")
        addItem(ModItems.radAway, "RadAway")
        addItem(ModItems.strongRadAway, "Strong RadAway")
        addItem(ModItems.eliteRadAway, "Elite RadAway")

        addItem(ModItems.titaniumHelmet, "Titanium Helmet")
        addItem(ModItems.titaniumChestplate, "Titanium Chestplate")
        addItem(ModItems.titaniumLeggings, "Titanium Leggings")
        addItem(ModItems.titaniumBoots, "Titanium Boots")
        addItem(ModItems.steelHelmet, "Steel Helmet")
        addItem(ModItems.steelChestplate, "Steel Chestplate")
        addItem(ModItems.steelLeggings, "Steel Leggings")
        addItem(ModItems.steelBoots, "Steel Boots")
        addItem(ModItems.advancedAlloyHelmet, "Advanced Alloy Helmet")
        addItem(ModItems.advancedAlloyChestplate, "Advanced Alloy Chestplate")
        addItem(ModItems.advancedAlloyLeggings, "Advanced Alloy Leggings")
        addItem(ModItems.advancedAlloyBoots, "Advanced Alloy Boots")
        addItem(ModItems.combineSteelHelmet, "Combine Steel Helmet")
        addItem(ModItems.combineSteelChestplate, "Combine Steel Chestplate")
        addItem(ModItems.combineSteelLeggings, "Combine Steel Leggings")
        addItem(ModItems.combineSteelBoots, "Combine Steel Boots")
        addItem(ModItems.paAAlloyChestplate, "PaA Chest Protection Plate")
        addItem(ModItems.paAAlloyLeggings, "PaA Leg Reinforcements")
        addItem(ModItems.paAAlloyBoots, "PaA \"good ol' shoes\"")
        addItem(ModItems.schrabidiumHelmet, "Schrabidium Helmet")
        addItem(ModItems.schrabidiumChestplate, "Schrabidium Chestplate")
        addItem(ModItems.schrabidiumLeggings, "Schrabidium Leggings")
        addItem(ModItems.schrabidiumBoots, "Schrabidium Boots")

        addItem(ModItems.creativeNuclearExplosionSpawner, "Nuclear Explosion Spawner")
        add("creative_nuclear_explosion_spawner.$MODID.strength", "Strength")
        add("creative_nuclear_explosion_spawner.$MODID.muted", "Muted")
        add("creative_nuclear_explosion_spawner.$MODID.has_fallout", "Has Fallout")
        add("creative_nuclear_explosion_spawner.$MODID.extra_fallout", "Extra Fallout")
        add("creative_nuclear_explosion_spawner.$MODID.position", "Position")
        add("creative_nuclear_explosion_spawner.$MODID.cancel", "Cancel")
        add("creative_nuclear_explosion_spawner.$MODID.start", "Start")
        add("creative_nuclear_explosion_spawner.$MODID.error_strength", "Cannot parse strength value")
        add("creative_nuclear_explosion_spawner.$MODID.error_extra_fallout", "Cannot parse extra fallout value")
        add("creative_nuclear_explosion_spawner.$MODID.error_insufficient_permission", "Cannot use Nuclear Explosion Spawner: Insufficient permission")

        add("energy.$MODID", "Energy")

        addEntityType(EntityTypes.nukeExplosionEntity, "Nuclear Explosion")
        addEntityType(EntityTypes.nukeCloudEntity, "Mushroom Cloud")
        addEntityType(EntityTypes.falloutRainEntity, "Fallout Rain")
        addEntityTypeWithSpawnEgg(EntityTypes.nuclearCreeper, "Nuclear Creeper")

        addMenuType(MenuTypes.sirenMenu, "Siren")
        addMenuType(MenuTypes.safeMenu, "Safe")
        addMenuType(MenuTypes.anvilMenu, "Anvil Tier %s")
        add("${AnvilScreen.CONTAINER_TRANSLATION}.inputs", "Inputs:")
        add("${AnvilScreen.CONTAINER_TRANSLATION}.outputs", "Outputs:")
        addMenuType(MenuTypes.steamPressMenu, "Steam Press")
        addMenuType(MenuTypes.blastFurnaceMenu, "Blast Furnace")
        addMenuType(MenuTypes.combustionGeneratorMenu, "Combustion Generator")
        addMenuType(MenuTypes.electricFurnaceMenu, "Electric Furnace")
        addMenuType(MenuTypes.shredderMenu, "Shredder")
        addMenuType(MenuTypes.assemblerMenu, "Assembler")

        addMenuType(MenuTypes.littleBoyMenu, "Little Boy")
        addMenuType(MenuTypes.fatManMenu, "Fat Man")

        addSound(SoundEvents.sirenTrackHatchSiren, "Siren running: Hatch Siren")
        addSound(SoundEvents.sirenTrackAutopilotDisconnected, "Siren running: Autopilot Disconnected")
        addSound(SoundEvents.sirenTrackAMSSiren, "Siren running: AMS Siren")
        addSound(SoundEvents.sirenTrackBlastDoorAlarm, "Siren running: Blast Door Alarm")
        addSound(SoundEvents.sirenTrackAPCSiren, "Siren running: APC Siren")
        addSound(SoundEvents.sirenTrackKlaxon, "Siren running: Klaxon")
        addSound(SoundEvents.sirenTrackVaultDoorAlarm, "Siren running: Vault Door Alarm")
        addSound(SoundEvents.sirenTrackSecurityAlert, "Siren running: Security Alert")
        addSound(SoundEvents.sirenTrackStandardSiren, "Siren running: Standard Siren")
        addSound(SoundEvents.sirenTrackClassicSiren, "Siren running: Classic Siren")
        addSound(SoundEvents.sirenTrackBankAlarm, "Siren running: Bank Alarm")
        addSound(SoundEvents.sirenTrackBeepSiren, "Siren running: Beep Siren")
        addSound(SoundEvents.sirenTrackContainerAlarm, "Siren running: Container Alarm")
        addSound(SoundEvents.sirenTrackSweepSiren, "Siren running: Sweep Siren")
        addSound(SoundEvents.sirenTrackMissileSiloSiren, "Siren running: Missile Silo Siren")
        addSound(SoundEvents.sirenTrackAirRaidSiren, "Siren running: Air Raid Siren")
        addSound(SoundEvents.sirenTrackNostromoSelfDestruct, "Siren running: Nostromo Self Destruct")
        addSound(SoundEvents.sirenTrackEASAlarmScreech, "Siren running: EAS Alarm Screech")
        addSound(SoundEvents.sirenTrackAPCPass, "Siren running: APC Pass")
        addSound(SoundEvents.sirenTrackRazortrainHorn, "Siren running: Razortrain Horn")
        addSound(SoundEvents.anvilFall, "Anvil clashes")
        addSound(SoundEvents.pressOperate, "Press stamps")
        addSound(SoundEvents.inject, "Needle injected")
        addSound(SoundEvents.emptyIVBag, "Liquid infused")
        addSound(SoundEvents.randomBleep, "Device bleeps")
        addSound(SoundEvents.randomBoop, "Device boops")
        addSound(SoundEvents.randomUnpack, "Item unpacked")
        add("subtitle.$MODID.geiger.click", "Geiger Counter clicks")
        addSound(SoundEvents.miniNukeExplosion, "Mini nuke explodes")

        addDamageSource(DamageSources.extractBlood, "%1\$s extracted too much life essence", "%1\$s tried to leave neatly-packaged life juice for %2\$s")
        addDamageSource(DamageSources.radiation, "%1\$s died from radiation poisoning", "%1\$s fell victim to acute radiation syndrome whilst fighting %2\$s")
        addDamageSource(DamageSources.nuclearBlast, "%1\$s was blown away by a nuclear explosion", "%1\$s got nuked whilst fighting %2\$s")
        addDamageSource(DamageSources.murkyAnvil, "%1\$s UNDEFINED", "%1\$s UNDEFINED whilst trying to escape %2\$s")

        addAttribute(Attributes.RADIATION_RESISTANCE, "Radiation Resistance")

        add("geiger.title", "GEIGER COUNTER")
        add("geiger.chunkRadiation", "Current chunk radiation:")
        add("geiger.totalEnvironmentRadiation", "Total environmental radiation:")
        add("geiger.playerIrradiation", "Player irradiation:")
        add("geiger.playerResistance", "Player resistance:")

        add(ntmTranslationString("armor.full_set_bonus"), "Full Set Bonus:")
        add(ntmTranslationString("armor.damage_resistance_modifier"), "Damage modifier of %s against %s")
        add(ntmTranslationString("armor.nullifies_damage"), "Nullifies all damage from %s")
        add(ntmTranslationString("armor.blast_protection"), "Damage modifier of %s against explosions")
        add(ntmTranslationString("armor.projectile_protection"), "Damage modifier of %s against projectiles")
        add(ntmTranslationString("armor.damage_cap"), "Hard damage cap of %s")
        add(ntmTranslationString("armor.damage_modifier"), "General damage modifier of %s")
        add(ntmTranslationString("armor.damage_threshold"), "Damage threshold of %s")
        add(ntmTranslationString("armor.fireproof"), "Fireproof")
        add(ntmTranslationString("armor.geiger_sound"), "Auditory Geiger Counter")
        add(ntmTranslationString("armor.custom_geiger"), "Built-In Geiger Counter HUD")
        add(ntmTranslationString("armor.vats"), "Enemy HUD")
        add(ntmTranslationString("armor.thermal"), "Thermal Sight")
        add(ntmTranslationString("armor.hard_landing"), "Hard Landing")
        add(ntmTranslationString("armor.gravity"), "Gravity modifier of %s")
        add(ntmTranslationString("armor.dash_count"), "Grants %s dashes")
        add(ntmTranslationString("armor.protection_yield"), "Protection applies to damage <%s")

        add("jei.$MODID.category.smithing", "Smithing")
        add("jei.$MODID.category.smithing.tier", "Minimum Tier: %s")
        add("jei.$MODID.category.constructing", "Constructing")
        add("jei.$MODID.category.constructing.tier", "Minimum Tier: %s")
        add("jei.$MODID.category.constructing.tier_range", "Tier Range: %s..%s")
        add("jei.$MODID.category.constructing.chance", "Output chance:")
        add("jei.$MODID.category.pressing", "Pressing")
        add("jei.$MODID.category.pressing.experience", "%s XP")
        add("jei.$MODID.category.blasting", "Blasting")
        add("jei.$MODID.category.blasting.experience", "%s XP")
        add("jei.$MODID.category.template_folder_results", "Template Folder")
        add("jei.$MODID.category.shredding", "Shredding")
    }

    private fun addMaterials() {
        val mat = Materials

        addMaterial(mat.coal, "Coal")
        addMaterial(mat.iron, "Iron")
        addMaterial(mat.copper, "Copper")
        addMaterial(mat.gold, "Gold")
        addMaterial(mat.redstone, "Redstone")
        addMaterial(mat.emerald, "Emerald")
        addMaterial(mat.lazuli, "Lapis Lazuli")
        addMaterial(mat.diamond, "Diamond")

        addMaterial(mat.naturalUranium, "Uranium")
        addMaterial(mat.uranium233, "U233")
        addMaterial(mat.uranium235, "U235")
        addMaterial(mat.uranium238, "U238")
        addMaterial(mat.thorium, "Thorium")
        addMaterial(mat.naturalPlutonium, "Plutonium")
        addMaterial(mat.plutonium238, "Pu238")
        addMaterial(mat.plutonium239, "Pu239")
        addMaterial(mat.plutonium240, "Pu240")
        addMaterial(mat.neptunium, "Neptunium")
        addMaterial(mat.polonium, "Polonium")
        addMaterial(mat.titanium, "Titanium")
        addMaterial(mat.redCopper, "Red Copper")
        addMaterial(mat.advancedAlloy, "Advanced Alloy")
        addMaterial(mat.tungsten, "Tungsten")
        addMaterial(mat.magnetizedTungsten, "Magnetized Tungsten")
        addMaterial(mat.aluminium, "Aluminium")
        addMaterial(mat.steel, "Steel")
        addMaterial(mat.lead, "Lead")
        addMaterial(mat.beryllium, "Beryllium")
        addMaterial(mat.cobalt, "Cobalt")
        addMaterial(mat.highSpeedSteel, "High-Speed Steel")
        addMaterial(mat.polymer, "Polymer")
        addMaterial(mat.schraranium, "Schraranium")
        addMaterial(mat.schrabidium, "Schrabidium")
        addMaterial(mat.solinium, "Solinium")
        addMaterial(mat.combineSteel, "Combine Steel")
        addMaterial(mat.uraniumFuel, "Uranium Fuel")
        addMaterial(mat.thoriumFuel, "Thorium Fuel")
        addMaterial(mat.plutoniumFuel, "Plutonium Fuel")
        addMaterial(mat.moxFuel, "MOX Fuel")
        addMaterial(mat.schrabidiumFuel, "Schrabidium Fuel")
        addMaterial(mat.hesFuel, "High Enriched Schrabidium Fuel")
        addMaterial(mat.lesFuel, "Low Enriched Schrabidium Fuel")
        addMaterial(mat.australium, "Australium")
        addMaterial(mat.weidanium, "Weidanium")
        addMaterial(mat.reiium, "Reiium")
        addMaterial(mat.unobtainium, "Unobtainium")
        addMaterial(mat.daffergon, "Daffergon")
        addMaterial(mat.verticium, "Verticium")
        addMaterial(mat.lanthanum, "Lanthanum")
        addMaterial(mat.actinium, "Actinium")
        addMaterial(mat.desh, "Desh")
        addMaterial(mat.starmetal, "Starmetal")
        addMaterial(mat.saturnite, "Saturnite")
        addMaterial(mat.euphemium, "Euphemium")
        addMaterial(mat.dineutronium, "Dineutronium")
        addMaterial(mat.electronium, "Electronium")
        addMaterial(mat.lignite, "Lignite")
        addMaterial(mat.sulfur, "Sulfur")
        addMaterial(mat.niter, "Niter")
        addMaterial(mat.fluorite, "Fluorite")
        addMaterial(mat.asbestos, "Asbestos")
        addMaterial(mat.lithium, "Lithium")
    }

    override val spawnEggSuffix = " Spawn Egg"

    override val oreFormat = "%s Ore"
    override val deepOreFormat = "Deepslate %s Ore"
    override val blockFormat = "Block of %s"
    override val rawFormat = "Raw %s"
    override val ingotFormat = "%s Ingot"
    override val nuggetFormat = "%s Nugget"
    override val crystalsFormat = "%s Crystals"
    override val powderFormat = "%s Powder"
    override val plateFormat = "%s Plate"
    override val wireFormat = "%s Wire"
}
