package at.martinthedragon.nucleartech.datagen.localisation

import at.martinthedragon.nucleartech.LangKeys
import at.martinthedragon.nucleartech.Materials
import at.martinthedragon.nucleartech.SoundEvents
import at.martinthedragon.nucleartech.block.NTechBlocks
import at.martinthedragon.nucleartech.datagen.NuclearLanguageProviders
import at.martinthedragon.nucleartech.entity.EntityTypes
import at.martinthedragon.nucleartech.entity.attribute.Attributes
import at.martinthedragon.nucleartech.fluid.NTechFluids
import at.martinthedragon.nucleartech.item.NTechItems
import at.martinthedragon.nucleartech.menu.MenuTypes
import at.martinthedragon.nucleartech.world.DamageSources
import net.minecraft.data.DataGenerator

class ItItLanguageProvider(dataGenerator: DataGenerator) : NuclearLanguageProvider(dataGenerator, NuclearLanguageProviders.IT_IT) {
    override fun translate() {
        add("itemGroup.${MODID}_parts", "NTM Parti e Risorse")
        add("itemGroup.${MODID}_items", "NTM Carburante e Pezzi")
        add("itemGroup.${MODID}_templates", "NTM Modelli")
        add("itemGroup.${MODID}_blocks", "NTM Minerali e Blocchi")
        add("itemGroup.${MODID}_machines", "NTM Macchinari")
        add("itemGroup.${MODID}_bombs", "NTM Bombe")
        add("itemGroup.${MODID}_rocketry", "NTM Missili e Satelliti")
        add("itemGroup.${MODID}_consumables", "NTM Consumabili ed Equipaggiamento")
        add("itemGroup.${MODID}_miscellaneous", "NTM Varie")

        addMaterials()

        addBlock(NTechBlocks.scorchedUraniumOre, "Minerale di Uranio scottato")
        addBlock(NTechBlocks.thoriumOre, "Minerale di Torio")
        addBlock(NTechBlocks.oilDeposit, "Deposito di Petrolio")
        addBlockDesc(NTechBlocks.oilDeposit, "Non avresti dovuto scavarlo.\nAndiamo, usa una torre petrolifera.")
        addBlock(NTechBlocks.emptyOilDeposit, "Deposito di Petrolio vuoto")
        addBlock(NTechBlocks.oilSand, "Sabbia con Petrolio")
        addBlock(NTechBlocks.australianOre, "Minerale di Australian")
        addBlockDesc(NTechBlocks.australianOre, "Minerale di Australium")
        addBlock(NTechBlocks.weidite, "Weidite")
        addBlockDesc(NTechBlocks.weidite, "Minerale di Weidanio")
        addBlock(NTechBlocks.reiite, "Reiite")
        addBlockDesc(NTechBlocks.reiite, "Minerale di Reiium")
        addBlock(NTechBlocks.brightblendeOre, "Minerale di Brightblende")
        addBlockDesc(NTechBlocks.brightblendeOre, "Minerale di Unobtainium")
        addBlock(NTechBlocks.dellite, "Dellite")
        addBlockDesc(NTechBlocks.dellite, "Minerale di Daffergon")
        addBlock(NTechBlocks.dollarGreenMineral, "Dollar Green Mineral")
        addBlockDesc(NTechBlocks.dollarGreenMineral, "Minerale di Verticio")
        addBlock(NTechBlocks.rareEarthOre, "Minerale delle Terre Rare")
        addBlock(NTechBlocks.netherUraniumOre, "Minerale di Uranio del Nether")
        addBlock(NTechBlocks.scorchedNetherUraniumOre, "Minerale di Uranio del Nether scottato")
        addBlock(NTechBlocks.netherPlutoniumOre, "Minerale di Plutonio del Nether")
        addBlock(NTechBlocks.netherTungstenOre, "Minerale di Tungsteno del Nether")
        addBlock(NTechBlocks.netherSulfurOre, "Minerale di Zolfo del Nether")
        addBlock(NTechBlocks.netherPhosphorusOre, "Minerale di Fosforo del Nether")
        addBlock(NTechBlocks.netherSchrabidiumOre, "Minerale di Schrabidio del Nether")
        addBlock(NTechBlocks.meteorUraniumOre, "Minerale di Uranio Meteorico")
        addBlock(NTechBlocks.meteorThoriumOre, "Minerale di Thorium Meteorico")
        addBlock(NTechBlocks.meteorTitaniumOre, "Minerale di Titanio Meteoric")
        addBlock(NTechBlocks.meteorSulfurOre, "Minerale di Zolfo Meteorico")
        addBlock(NTechBlocks.meteorCopperOre, "Minerale di Rame Meteorico")
        addBlock(NTechBlocks.meteorTungstenOre, "Minerale di Tungsteno Meteorico")
        addBlock(NTechBlocks.meteorAluminiumOre, "Minerale di Alluminio Meteorico")
        addBlock(NTechBlocks.meteorLeadOre, "Minerale di Piombo Meteorico")
        addBlock(NTechBlocks.meteorLithiumOre, "Minerale di Litio Meteorico")
        addBlock(NTechBlocks.starmetalOre, "Minerale di Metallo Stellare")
        addBlock(NTechBlocks.trixite, "Trixite")
        addBlock(NTechBlocks.basaltSulfurOre, "Basalto arricchito di Zolfo")
        addBlock(NTechBlocks.basaltFluoriteOre, "Basalto arricchito di Fluorite")
        addBlock(NTechBlocks.basaltAsbestosOre, "Basalto arricchito di Amianto")
        addBlock(NTechBlocks.basaltVolcanicGemOre, "Basalto arricchito di Gemme Vulcaniche")

        addBlock(NTechBlocks.scorchedDeepslateUraniumOre, "Minerale di Uranio scottato in Ardesia Profonda")
        addBlock(NTechBlocks.deepslateOilDeposit, "Deposito di Petrolio in Ardesia Profonda")
        addBlockDesc(NTechBlocks.deepslateOilDeposit, "Così in profondita e ancora\nnon sai che fare? Come?!")
        addBlock(NTechBlocks.emptyDeepslateOilDeposit, "Deposito di Petrolio vuoto in Ardesia Profonda")
        addBlock(NTechBlocks.deepslateAustralianOre, "Minerale di Australian in Ardesia Profonda")
        addBlockDesc(NTechBlocks.deepslateAustralianOre, "Minerale di Australian")
        addBlock(NTechBlocks.deepslateRareEarthOre, "Minerale delle Terre Rare in Ardesia Profonda")

        addBlock(NTechBlocks.whitePhosphorusBlock, "Blocco di Fosforo Bianco")
        addBlock(NTechBlocks.redPhosphorusBlock, "Blocco di Fosforo Rosso")
        addBlock(NTechBlocks.yellowcakeBlock, "Blocco di Torta gialla")
        addBlock(NTechBlocks.scrapBlock, "Blocco di Rottami")
        addBlock(NTechBlocks.electricalScrapBlock, "Blocco di Rottami elettrici")
        addBlock(NTechBlocks.insulatorRoll, "Nastro Isolante")
        addBlock(NTechBlocks.fiberglassRoll, "Nastro in Fibra di Vetro")
        addBlock(NTechBlocks.trinititeBlock, "Blocco di Trinitite")
        addBlock(NTechBlocks.nuclearWasteBlock, "Blocco di Scarti Nucleari")
        addBlock(NTechBlocks.schrabidiumCluster, "Ammasso di Schrabidio")
        addBlock(NTechBlocks.euphemiumEtchedSchrabidiumCluster, "Ammasso di Schrabidio inciso in Euphemium")
        addBlock(NTechBlocks.deshReinforcedBlock, "Blocco Rinforzato di Desh")

        addBlock(NTechBlocks.titaniumDecoBlock, "Blocco decorativo di Titanio")
        addBlock(NTechBlocks.redCopperDecoBlock, "Blocco decorativo di Rame Rosso")
        addBlock(NTechBlocks.tungstenDecoBlock, "Blocco decorativo di Tungsteno")
        addBlock(NTechBlocks.aluminiumDecoBlock, "Blocco decorativo di Alluminio")
        addBlock(NTechBlocks.steelDecoBlock, "Blocco decorativo di Acciaio")
        addBlock(NTechBlocks.leadDecoBlock, "Blocco decorativo di Piombo")
        addBlock(NTechBlocks.berylliumDecoBlock, "Blocco decorativo di Berillio")
        addBlock(NTechBlocks.asbestosRoof, "Tetto di Amianto")
        addBlock(NTechBlocks.hazmatBlock, "Blocco Anti-Radiazioni")
        addBlock(NTechBlocks.steelBeam, "Asse di Acciaio")
        addBlock(NTechBlocks.steelScaffold, "Impalcatura di Acciaio")
        addBlock(NTechBlocks.steelGrate, "Grata di Acciaio")

        addBlock(NTechBlocks.glowingMushroom, "Fungo Luminescente")
        addBlock(NTechBlocks.glowingMushroomBlock, "Blocco di Fungo Luminescente")
        addBlock(NTechBlocks.glowingMushroomStem, "Gambo di Fungo Luminescente")
        addBlock(NTechBlocks.deadGrass, "Erba Morta")
        addBlock(NTechBlocks.glowingMycelium, "Micelio Luminescente")
        addBlock(NTechBlocks.trinitite, "Minerale di Trinitite")
        addBlock(NTechBlocks.redTrinitite, "Minerale di Trinitite Rossa")
        addBlock(NTechBlocks.charredLog, "Tronco Bruciato")
        addBlock(NTechBlocks.charredPlanks, "Assi Bruciate")

        addBlock(NTechBlocks.slakedSellafite, "Sellafite Fredda")
        addBlock(NTechBlocks.sellafite, "Sellafite")
        addBlock(NTechBlocks.hotSellafite, "Sellafite Calda")
        addBlock(NTechBlocks.boilingSellafite, "Sellafite Bollente")
        addBlock(NTechBlocks.blazingSellafite, "Sellafite in Fiamme")
        addBlock(NTechBlocks.infernalSellafite, "Sellafite Infernale")
        addBlock(NTechBlocks.sellafiteCorium, "Corio di Sellafite")

        addBlock(NTechBlocks.corium, "Corio")
        addBlock(NTechBlocks.corebblestone, "Pietrisco di Corio")

        addBlock(NTechBlocks.siren, "Sirena")
        addBlock(NTechBlocks.safe, "Cassaforte")
        addBlock(NTechBlocks.steamPressBase, "Pressa a Vapore")
        addBlock(NTechBlocks.steamPressFrame, "Pressa a Vapore")
        addBlock(NTechBlocks.steamPressTop, "Pressa a Vapore")
        addBlock(NTechBlocks.blastFurnace, "Forno Fusorio")
        addBlock(NTechBlocks.combustionGenerator, "Generatore a Combustione")
        addBlock(NTechBlocks.electricFurnace, "Fornace Elettrica")
        addBlock(NTechBlocks.shredder, "Trituratore")
        addBlock(NTechBlocks.assembler, "Assemblatore")
        addBlock(NTechBlocks.chemPlant, "Impianto Chimico")
        addBlock(NTechBlocks.oilDerrick, "Torre Petrolifera")
        addBlock(NTechBlocks.pumpjack, "Pompa Petrolifera")
        addBlockDesc11(NTechBlocks.pumpjack, "Una vera zanzara")
        addBlock(NTechBlocks.centrifuge, "Centrifuga")
        addBlock(NTechBlocks.ironAnvil, "Incudine di Ferro")
        addBlock(NTechBlocks.leadAnvil, "Incudine di Piombo")
        addBlock(NTechBlocks.steelAnvil, "Incudine di Acciaio")
        addBlock(NTechBlocks.meteoriteAnvil, "Incudine di Meteorite")
        addBlock(NTechBlocks.starmetalAnvil, "Incudine di Metallo Stellare")
        addBlock(NTechBlocks.ferrouraniumAnvil, "Incudine di Ferro-uranio")
        addBlock(NTechBlocks.bismuthAnvil, "Incudine di Bismuto")
        addBlock(NTechBlocks.schrabidateAnvil, "Incudine di Schrabidate Ferrica")
        addBlock(NTechBlocks.dineutroniumAnvil, "Incudine di Dineutronium")
        addBlock(NTechBlocks.murkyAnvil, "Incudine Torbido")

        addBlock(NTechBlocks.rbmkColumn, "Colonna RBMK")
        addBlock(NTechBlocks.rbmkRod, "Barra di Carburante RBMK")
        addBlock(NTechBlocks.rbmkModeratedRod, "Barra di Carburante Moderata RBMK")
        addBlock(NTechBlocks.rbmkReaSimRod, "Barra di Carburante RBMK (ReaSim)")
        addBlock(NTechBlocks.rbmkModeratedReaSimRod, "Barra di Carburante Moderata RBMK (ReaSim)")
        addBlock(NTechBlocks.rbmkReflector, "Riflettore di Neutroni al Carburo di Tungsteno RBMK")
        addBlock(NTechBlocks.rbmkModerator, "Moderatore di Grafite RBMK")
        addBlock(NTechBlocks.rbmkAbsorber, "Assorbitore di Neutroni al Boro RBMK")
        addBlock(NTechBlocks.rbmkBoilerColumn, "Bollitore a Vapore RBMK")
        addBlock(NTechBlocks.rbmkBoiler, "Bollitore a Vapore RBMK")
        addBlock(NTechBlocks.rbmkBlank, "Colonna Strutturalev RBMK")
        addBlock(NTechBlocks.rbmkManualControlRod, "Barre di Controllo RBMK")
        addBlock(NTechBlocks.rbmkModeratedControlRod, "Barre di Controllo Moderate RBMK")
        addBlock(NTechBlocks.rbmkAutoControlRod, "Barre di Controllo Automatiche RBMK")
        addBlock(NTechBlocks.rbmkSteamConnector, "Connettore di Vapore RBMK")
        addBlock(NTechBlocks.rbmkInlet, "Entrata Idrica RBMK ReaSim")
        addBlock(NTechBlocks.rbmkOutlet, "Uscita di Vapire RBMK ReaSim")
        addBlock(NTechBlocks.rbmkConsole, "Console RBMK")
        addBlock(NTechBlocks.rbmkDebris, "Detriti RBMK")
        addBlock(NTechBlocks.rbmkBurningDebris, "Detriti in Fiamme RBMK")
        addBlock(NTechBlocks.rbmkRadioactiveDebris, "Detriti Fumanti Radioattivi RBMK")

        addBlock(NTechBlocks.coatedCable, "Cavo di Rame Rosso Rivestito")
        addBlock(NTechBlocks.coatedUniversalFluidDuct, "Tubo per Fluidi Unviersale Rivestito")

        addBlock(NTechBlocks.littleBoy, "Little Boy")
        addBlock(NTechBlocks.fatMan, "Fat Man")
        addBlock(NTechBlocks.volcanoCore, "Nucleo Vulcanico")

        addBlock(NTechBlocks.launchPad, "Pedana per Missili")
        addBlock(NTechBlocks.launchPadPart, "Pedana per Missili")

        addBlock(NTechBlocks.genericMultiBlockPart, "Parte di Struttura Multiblocco")
        addBlock(NTechBlocks.genericMultiBlockPort, "Parte di Struttura Multiblocco")
        addBlock(NTechBlocks.oilPipe, "Tubo Petrolifero")

        addBlock(NTechFluids.steam.block, "Vapore")
        addBlock(NTechFluids.steamHot.block, "Vapore Denso")
        addBlock(NTechFluids.steamSuperHot.block, "Vapore Super Denso")
        addBlock(NTechFluids.steamUltraHot.block, "Vapore Ultra Denso")
        addBlock(NTechFluids.oil.block, "Petrolio")
        addBlock(NTechFluids.gas.block, "Gas Naturale")
        addBlock(NTechFluids.uraniumHexafluoride.block, "Esafluoruro di Uranio")
        addBlock(NTechFluids.corium.block, "Corio")
        addBlock(NTechFluids.volcanicLava.block, "Lava Vulcanica")

        addItem(NTechItems.rawThorium, "Torio Grezzo")
        addItem(NTechItems.rawRareEarth, "Terre Rare Grezzo")
        addItem(NTechItems.rawTrixite, "Trixite Grezza")

        addItemDesc(NTechItems.neptuniumIngot, "La mia preferita!")
        addItemDesc(NTechItems.tantaliumIngot, "'Tantalum'")
        addItemDesc(NTechItems.tantaliumNugget, "'Tantalum'")
        addItemDesc(NTechItems.schraraniumIngot, "Fatto dall'uranio in un trasmutatore di schrabidio")
        addItemDesc(NTechItems.combineSteelIngot, "*Inserire relazione della Protezione Civile qui*")
        addItemDesc(NTechItems.ghiorsium336Ingot, "Collega di Seaborgium.")
        addItemDesc(NTechItems.ghiorsium336Nugget, "Collega di Seaborgium.")
        addItem(NTechItems.lanthanumIngot, "Lingotto di Lantanio Semi-Stabile")
        addItemDesc(NTechItems.euphemiumIngot, "Un elemento molto speciale e strano")
        addItem(NTechItems.whitePhosphorusIngot, "Barra di Fosforo Biancio")

        addItem(NTechItems.semtexBar, "Carica di Semtex")
        addItemDesc(
            NTechItems.semtexBar,
            "Esplodivo plastico Semtex H\n" +
                    "Esplosivo performante per varie applicazioni.\n" +
                    "Consumabile"
        )

        addItem(NTechItems.lithiumCube, "Cubo di Litio")
        addItem(NTechItems.solidFuelCube, "Cubo di Carburante Solido")
        addItem(NTechItems.solidRocketFuelCube, "Cubo di Carburante Solido per Razzi")

        addItem(NTechItems.fiberglassSheet, "Panno di Fibra di Vetro")
        addItemDesc(NTechItems.fiberglassSheet, "Tanto di fibra, tanto di vetro. Tutto ciò che il corpo ha bisogno.")
        addItem(NTechItems.asbestosSheet, "Lastra di Amianto")
        addItemDesc(NTechItems.asbestosSheet, "§o„Pieno di vita, insicurezze e amianto. Ciò arriva con l'aria.“")

        addItem(NTechItems.mercuryDroplet, "Goccia di Mercurio")
        addItem(NTechItems.mercuryBottle, "Bottiglia di Mercurio")

        addItem(NTechItems.coke, "Coke")
        addItem(NTechItems.lignite, "Lignite")
        addItem(NTechItems.ligniteBriquette, "Mattonella di Lignite")

        addItem(NTechItems.sulfur, "Zolfo")
        addItem(NTechItems.niter, "Nitrati")
        addItem(NTechItems.fluorite, "Fluorite")
        addItem(NTechItems.quartzPowder, "Polvere di Quarzo")
        addItem(NTechItems.yellowcake, "Torta gialla")
        addItem(NTechItems.chlorophytePowder, "Polvere di Clorofito")
        addItem(NTechItems.neodymiumPowder, "Polvere di Neodio")
        addItem(NTechItems.niobiumPowder, "Polvere di Niobio")
        addItem(NTechItems.ceriumPowder, "Polvere di Cerio")
        addItemDesc(NTechItems.asbestosPowder, "§o„Sniffffffff - MHHHHHHMHHHHHHHHH“")
        addItem(NTechItems.enchantmentPowder, "Polvere di Incantesimi")
        addItem(NTechItems.cloudResidue, "Residuo di Nuvole")
        addItem(NTechItems.thermonuclearAshes, "Ceneri Termonucleari")
        addItem(NTechItems.semtexMix, "Misto per Semtex")
        addItem(NTechItems.deshMix, "Misto per Desh")
        addItem(NTechItems.deshReadyMix, "Misto di DeshReady™")
        addItem(NTechItems.nitaniumMix, "Misto di Nitanio")
        addItem(NTechItems.sparkMix, "Misto di Scintille")
        addItem(NTechItems.meteoritePowder, "Polvere di Meteorite")
        addItemDesc(NTechItems.euphemiumPowder, "Rosa polverizzato.\nsa di fragole.")
        addItem(NTechItems.desaturatedRedstone, "Redstone Destaurata")
        addItem(NTechItems.dust, "Polvere")
        addItemDesc(NTechItems.dust, "Odio la polvere!")
        addItem(NTechItems.tinyLithiumPowder, "Polverina di Litio")
        addItem(NTechItems.tinyNeodymiumPowder, "Polverina di Neodio")
        addItem(NTechItems.tinyCobaltPowder, "Polverina di Cobalto")
        addItem(NTechItems.tinyNiobiumPowder, "Polverina di Niobio")
        addItem(NTechItems.tinyCeriumPowder, "Polverina di Cerio")
        addItem(NTechItems.tinyLanthanumPowder, "Polverina di Lantanio")
        addItem(NTechItems.tinyActiniumPowder, "Polverina di Actinio")
        addItem(NTechItems.tinyMeteoritePowder, "Polverina di Meteorite")
        addItem(NTechItems.redPhosphorus, "Fosforo Rosso")
        addItemDesc(NTechItems.redPhosphorus, "Usata in varie bombe:\nLe bombe incendiarie sono divertenti!")
        addItem(NTechItems.cryoPowder, "Polvere Gelante")
        addItem(NTechItems.poisonPowder, "Polvere Velenosa")
        addItemDesc(NTechItems.poisonPowder, "Usata in varie bombe:\nAttenzione: Velenoso!")
        addItem(NTechItems.thermite, "Termite")
        addItem(NTechItems.energyPowder, "Polvere Energetica")

        addItem(NTechItems.cordite, "Cordite")
        addItem(NTechItems.ballistite, "Ballistite")

        addItem(NTechItems.rareEarthCrystals, "Cristallo delle Terre Rare")
        addItem(NTechItems.redPhosphorusCrystals, "Cristallo di Fosforo Rosso")
        addItem(NTechItems.trixiteCrystals, "Cristallo do Trixite")

        addItem(NTechItems.volcanicGem, "Gemma Vulcanica")

        addItem(NTechItems.neodymiumFragment, "Frammento di Neodio")
        addItem(NTechItems.cobaltFragment, "Frammento di Cobalto")
        addItem(NTechItems.niobiumFragment, "Frammento di Niobio")
        addItem(NTechItems.ceriumFragment, "Frammento di Cera Fragment")
        addItem(NTechItems.lanthanumFragment, "Frammento di Lantanio")
        addItem(NTechItems.actiniumFragment, "Frammento di Attinio")
        addItem(NTechItems.meteoriteFragment, "Frammento Meteorico")

        addItem(NTechItems.biomass, "Biomassa")
        addItem(NTechItems.compressedBiomass, "Biomassa Compressa")

        addItemDesc(
            NTechItems.euphemiumNugget,
            "Un piccolo pezzo di metallo rosa.\n" +
                    "Le sue proprietà sono ancora sconosciute,\n" +
                    "Maneggiare CON CURA."
        )

        addItem(NTechItems.neutronReflector, "Riflettore di Neutroni")
        addItem(NTechItems.mixedPlate, "Piastra Mista")
        addItem(NTechItems.paAAlloyPlate, "Lastra di Lega PaA")
        addItem(NTechItems.insulator, "Isolante")
        addItem(NTechItems.kevlarCeramicCompound, "Composto di Ceramica al Kevlar")
        addItem(NTechItems.dalekaniumPlate, "Metallo Arrabbiato")
        addItem(NTechItems.deshCompoundPlate, "Lastra Composta di Desh")
        addItem(NTechItems.euphemiumCompoundPlate, "Lastra Composta di Euphemium")
        addItem(NTechItems.dineutroniumCompoundPlate, "Lastra Composta di Dineutronium")
        addItem(NTechItems.copperPanel, "Pannello di Rame")

        addItem(NTechItems.highSpeedSteelBolt, "Bullone di Acciaio ad Alta velocità")
        addItem(NTechItems.tungstenBolt, "Bullone di Tungsteno")
        addItem(NTechItems.reinforcedTurbineShaft, "Asse Rinforzata per Turbina")

        addItem(NTechItems.hazmatCloth, "Tessuto Anti-Radiazioni")
        addItem(NTechItems.advancedHazmatCloth, "Tessuto Avanzato Anti-Radiazioni")
        addItem(NTechItems.leadReinforcedHazmatCloth, "Tessuto Anti-Radiazioni rinforzato al Piombo")
        addItem(NTechItems.fireProximityCloth, "Tessuto per Fuoco di Prossimità")
        addItem(NTechItems.activatedCarbonFilter, "Filtro al Carbone Attivo")

        addItem(NTechItems.superConductor, "Superconduttore")
        addItem(NTechItems.highTemperatureSuperConductor, "Superconduttore ad alta Temperatura 4000K")

        addItem(NTechItems.copperCoil, "Bobina di Rame")
        addItem(NTechItems.ringCoil, "Bobina ad Anello")
        addItem(NTechItems.superConductingCoil, "Bobina superconduttore")
        addItem(NTechItems.superConductingRingCoil, "Bobina ad Anello Superconduttore")
        addItem(NTechItems.goldCoil, "Bobina di Oro")
        addItem(NTechItems.goldRingCoil, "Bobina ad Anello di Oro")
        addItem(NTechItems.heatingCoil, "Bobina Riscaldante")
        addItem(NTechItems.highTemperatureSuperConductingCoil, "Superconduttore ad alta Temperatura 4000K")

        addItem(NTechItems.steelTank, "Tanica di Acciaio")
        addItem(NTechItems.motor, "Motore")
        addItem(NTechItems.centrifugeElement, "Elemento della Centrifuga")
        addItem(NTechItems.centrifugeTower, "Torre della Centrifuga")
        addItem(NTechItems.deeMagnets, "Magnete Dee")
        addItem(NTechItems.flatMagnet, "Magnete Piatto")
        addItem(NTechItems.cyclotronTower, "Torre del Ciclotrone")
        addItem(NTechItems.breedingReactorCore, "Nucleo del Reattore di Allevamento")
        addItem(NTechItems.rtgUnit, "Unità RTG")
        addItem(NTechItems.thermalDistributionUnit, "Unità di Distribuzione Termica")
        addItem(NTechItems.endothermicDistributionUnit, "Unità di Distribuzione Endotermica")
        addItem(NTechItems.exothermicDistributionUnit, "Unità di Distribuzione Esotermica")
        addItem(NTechItems.gravityManipulator, "Manipolatore della Gravità")
        addItem(NTechItems.steelPipes, "Tubi di Acciaio")
        addItem(NTechItems.titaniumDrill, "Trapano di Titanio")
        addItem(NTechItems.photovoltaicPanel, "Pannello Fotovoltaico")
        addItem(NTechItems.chlorinePinwheel, "Girandola al Cloro")
        addItem(NTechItems.telepad, "Pedana di Teletrasporto")
        addItem(NTechItems.entanglementKit, "Kit di Intrappolamento")
        addItemDesc(
            NTechItems.entanglementKit,
            "Oggetto di Fabbricazione per Teletrasporto.\n" +
                    "Abilita lo spostamento tra le dimensioni usando\n" +
                    "uno scanner migliorato al berillio."
        )
        addItem(NTechItems.stabilizerComponent, "Componente di Stabilizzazione")
        addItem(NTechItems.emitterComponent, "Componente Emettitore")
        addItem(NTechItems.aluminiumCap, "Coperchio di Alluminio")
        addItem(NTechItems.smallSteelShell, "Pallottola piccola di Acciaio")
        addItem(NTechItems.smallAluminiumShell, "Pallottola piccola di Alluminio")
        addItem(NTechItems.bigSteelShell, "Pallettone di Acciaio")
        addItem(NTechItems.bigAluminiumShell, "Pallettone di Alluminio")
        addItem(NTechItems.bigTitaniumShell, "Pallettone di Titanio")
        addItem(NTechItems.flatSteelCasing, "iìInvolucro piatto di Acciaio")
        addItem(NTechItems.smallSteelGridFins, "Piccole pinne di Acciaio per Griglia")
        addItem(NTechItems.bigSteelGridFins, "Grandi pinne di Acciaio per Griglia")
        addItem(NTechItems.largeSteelFins, "Pinne larghe di Acciaio")
        addItem(NTechItems.smallTitaniumFins, "Pinne larghe di Titanio")
        addItem(NTechItems.steelSphere, "Sfera di Acciaio")
        addItem(NTechItems.steelPedestal, "Piedistallo di Acciaio")
        addItem(NTechItems.dysfunctionalNuclearReactor, "Reattore Nucleare Disfunzionale")
        addItem(NTechItems.largeSteelRotor, "Rotore largo di Acciaio")
        addItem(NTechItems.generatorBody, "Corpo del Generatore")
        addItem(NTechItems.titaniumBlade, "Lama di Titanio")
        addItem(NTechItems.tungstenReinforcedBlade, "Lama Rinforzata di Tungsteno")
        addItem(NTechItems.titaniumSteamTurbine, "Turbina a Vapore di Acciaio")
        addItem(NTechItems.reinforcedTurbofanBlades, "Lame inforzate del Turboventilatore")
        addItem(NTechItems.generatorFront, "Faccia del Generatore")
        addItem(NTechItems.toothpicks, "Stuzzicadenti")
        addItem(NTechItems.ductTape, "Nastro Adesivo")
        addItem(NTechItems.clayCatalyst, "Catalista di Argilla")
        addItem(NTechItems.smallMissileAssembly, "Assemblaggio per Missile Piccolo")

        addItem(NTechItems.smallWarhead, "Testata Piccola")
        addItem(NTechItems.mediumWarhead, "Testata Media")
        addItem(NTechItems.largeWarhead, "Testata Grande")
        addItem(NTechItems.smallIncendiaryWarhead, "Testata Incendiaria Piccola")
        addItem(NTechItems.mediumIncendiaryWarhead, "Testata Incendiaria Media")
        addItem(NTechItems.largeIncendiaryWarhead, "Testata Incendiaria Grande")
        addItem(NTechItems.smallClusterWarhead, "Testata Piccola a Grappolo")
        addItem(NTechItems.mediumClusterWarhead, "Testata Media a Grappolo")
        addItem(NTechItems.largeClusterWarhead, "Testata Grande a Grappolo")
        addItem(NTechItems.smallBunkerBusterWarhead, "Testata Sfonda-Bunker Piccola")
        addItem(NTechItems.mediumBunkerBusterWarhead, "Testata Sfonda-Bunker Media")
        addItem(NTechItems.largeBunkerBusterWarhead, "Testata Sfonda-Bunker Grande")
        addItem(NTechItems.nuclearWarhead, "Testata Nucleare")
        addItem(NTechItems.thermonuclearWarhead, "Testata Termonucleare")
        addItem(NTechItems.endothermicWarhead, "Testata Endotermica")
        addItem(NTechItems.exothermicWarhead, "Testata Esotermica")

        addItem(NTechItems.smallFuelTank, "Tanica di Benzina Piccola")
        addItem(NTechItems.mediumFuelTank, "Tanica di Benzina Media")
        addItem(NTechItems.largeFuelTank, "Tanica di Benzina Grande")

        addItem(NTechItems.smallThruster, "Propulsore Piccolo")
        addItem(NTechItems.mediumThruster, "Propulsore Medio")
        addItem(NTechItems.largeThruster, "Propulsore Grande")
        addItem(NTechItems.lvnNuclearRocketEngine, "Propulsore Nucleare LV-N")

        addItem(NTechItems.satelliteBase, "Base del Satellite")
        addItem(NTechItems.highGainOpticalCamera, "Telecamera Ottica ad alta Acquisizione")
        addItem(NTechItems.m700SurveyScanner, "Scanner Sonda M700")
        addItem(NTechItems.radarDish, "Piatto del Radar")
        addItem(NTechItems.deathRay, "Raggio della Morte")
        addItem(NTechItems.xeniumResonator, "Risonatore allo Xenio")

        addItem(NTechItems.size10Connector, "Connettore con Taglia 10")
        addItem(NTechItems.size15Connector, "Connettore con Taglia 15")
        addItem(NTechItems.size20Connector, "Connettore con Taglia 20")

        addItem(NTechItems.hunterChopperCockpit, "Cabina dell'Elicottero Cacciatore")
        addItem(NTechItems.emplacementGun, "Arma da Postazione")
        addItem(NTechItems.hunterChopperBody, "Involucro dell'Elicottero Cacciatore")
        addItem(NTechItems.hunterChopperTail, "Coda dell'Elicottero Cacciatore")
        addItem(NTechItems.hunterChopperWing, "Ala dell'Elicottero Cacciatore")
        addItem(NTechItems.hunterChopperRotorBlades, "Pale del Rotore dell'Elicottero Cacciatore")
        addItem(NTechItems.combineScrapMetal, "Rottami Metallici Combinati")

        addItem(NTechItems.heavyHammerHead, "Testa di Martello Pesante")
        addItem(NTechItems.heavyAxeHead, "Testa di Ascia Pesante")
        addItem(NTechItems.reinforcedPolymerHandle, "Manico Rinforzato di Polimero")

        addItem(NTechItems.basicCircuitAssembly, "Assemblaggio per Circiuto Base")
        addItem(NTechItems.basicCircuit, "Circiito Base")
        addItem(NTechItems.enhancedCircuit, "Circuito Migliorato")
        addItem(NTechItems.advancedCircuit, "Circuito Avanzato")
        addItem(NTechItems.overclockedCircuit, "Circuito Overcloccato")
        addItem(NTechItems.highPerformanceCircuit, "Circuito ad Alta Prestazione")
        addItem(NTechItems.militaryGradeCircuitBoardTier1, "Circuito di Grado Militare (Tier 1)")
        addItem(NTechItems.militaryGradeCircuitBoardTier2, "Circuito di Grado Militare (Tier 2)")
        addItem(NTechItems.militaryGradeCircuitBoardTier3, "Circuito di Grado Militare (Tier 3)")
        addItem(NTechItems.militaryGradeCircuitBoardTier4, "Circuito di Grado Militare (Tier 4)")
        addItem(NTechItems.militaryGradeCircuitBoardTier5, "Circuito di Grado Militare (Tier 5)")
        addItem(NTechItems.militaryGradeCircuitBoardTier6, "Circuito di Grado Militare (Tier 6)")

        addItem(NTechItems.revolverMechanism, "Meccanismo Per Rivoltella")
        addItem(NTechItems.advancedRevolverMechanism, "Meccanismo Avanzato per Rivoltella")
        addItem(NTechItems.rifleMechanism, "Meccanismo per Fucile")
        addItem(NTechItems.advancedRifleMechanism, "Meccanismo Avanzato per Fucile")
        addItem(NTechItems.launcherMechanism, "Meccanismo per Lanciatore")
        addItem(NTechItems.advancedLauncherMechanism, "Meccansimo Avanzato per Lanciatore")
        addItem(NTechItems.highTechWeaponMechanism, "Meccansimo High-Tech")

        addItem(NTechItems.point357MagnumPrimer, "Innesco per Magnum .357 (x16)")
        addItem(NTechItems.point44MagnumPrimer, "Innesco per Magnum .44 (x16)")
        addItem(NTechItems.smallCaliberPrimer, "Innesco per Piccolo Calibro (x24)")
        addItem(NTechItems.largeCaliberPrimer, "Innesco per Grande Calibro (x8)")
        addItem(NTechItems.buckshotPrimer, "Innesco per Grappolo (x8)")

        addItem(NTechItems.point357MagnumCasing, "Cartuccia per Magnum .357 (x16)")
        addItem(NTechItems.point44MagnumCasing, "Cartuccia per Magnum .44 (x16)")
        addItem(NTechItems.smallCaliberCasing, "Cartuccia per Piccolo Calibro (x24)")
        addItem(NTechItems.largeCaliberCasing, "Cartuccia per Grande Calibro (x8)")
        addItem(NTechItems.buckshotCasing, "Cartuccia per Grappolo (x8)")

        addItem(NTechItems.ironBulletAssembly, "Assemblaggio per Proiettile di Ferro")
        addItem(NTechItems.leadBulletAssembly, "Assemblaggio per Proiettile di Piombo")
        addItem(NTechItems.glassBulletAssembly, "Assemblaggio per Proiettile di Vetro")
        addItem(NTechItems.goldBulletAssembly, "Assemblaggio per Proiettile di Oro")
        addItem(NTechItems.schrabidiumBulletAssembly, "Assemblaggio per Proiettile di Schrabidio")
        addItem(NTechItems.nightmareBulletAssembly, "Assemblaggio per Proiettile Incubo")
        addItem(NTechItems.deshBulletAssembly, "Assemblaggio per Proiettile di Desh")
        addItem(NTechItems.point44MagnumAssembly, "Assemblaggio per Proiettile .44 Magnum")
        addItem(NTechItems.nineMmAssembly, "Assemblaggio per Proiettile 9mm")
        addItem(NTechItems.fivePoint56mmAssembly, "Assemblaggio per Proiettile 5.56mm")
        addItem(NTechItems.point22LRAssembly, "Assemblaggio per Proiettile .22")
        addItem(NTechItems.point5mmAssembly, "Assemblaggio per Proiettile .5mm")
        addItem(NTechItems.point50AEAssembly, "Assemblaggio per Proiettile .50 AE")
        addItem(NTechItems.point50BMGAssembly, "Assemblaggio per Proiettile .50 BMG")

        addItem(NTechItems.silverBulletCasing, "Cartuccia di Argento")
        addItem(NTechItems.twelvePoint8cmStarmetalHighEnergyShell, "Proiettile di Metallo Stellare ad Alta Energia 12.8cm")
        addItem(NTechItems.twelvePoint8cmNuclearShell, "Proiettile Nucleare 12.8cm")
        addItem(NTechItems.twelvePoint8cmDUShell, "Proiettile all'Uranio Impoverito 12.8cm")

        addItem(NTechItems.cableDrum, "Bobina per Cavo")
        addItemDesc(NTechItems.cableDrum, "Click sinistro per connettere i paletti")
        addItem(NTechItems.paintingOfACartoonPony, "Disegno di un Pony Cartone")
        addItemDesc(NTechItems.paintingOfACartoonPony, "Il cavallo giallo batte quello blu, è un dato di fatto!")
        addItem(NTechItems.conspiracyTheory, "Teoria Cospirazionista")
        addItemDesc(NTechItems.conspiracyTheory, "Le aste di Acciaio non possono sciogliere il carburante per jet!")
        addItem(NTechItems.politicalTopic, "Argomento Politico")
        addItemDesc(NTechItems.politicalTopic, "Paperino costruirà il muro!")
        addItem(NTechItems.ownOpinion, "Propria Opinione")
        addItemDesc(NTechItems.ownOpinion, "Beh, mi piace...")

        addItem(NTechItems.explosivePellets, "Pallini Esplosivi")
        addItemDesc(NTechItems.explosivePellets, "Usata in varie bombe:\nFarà dei botti extra!")
        addItem(NTechItems.leadPellets, "Pallini di Piombo")
        addItem(NTechItems.flechettes, "Freccette")
        addItem(NTechItems.poisonGasCartridge, "Carica di Gas Velenoso")
        addItemDesc(NTechItems.poisonGasCartridge, "Usata in varie bombe:\n*tossisce* Vi prego, aiutatemi!")
        addItem(NTechItems.magnetron, "Magnetron")
        addItem(NTechItems.denseCoalCluster, "Ammasso di Carbone Denso")
        addItem(NTechItems.burntBark, "Corteccia Bruciata")
        addItemDesc(NTechItems.burntBark, "Un pezzo di corteccia bruciata da un albero di quercia esploso.")
        addItem(NTechItems.machineUpgradeTemplate, "Modello per Potenziamento Macchine")

        addItem(NTechItems.blankRune, "Catalista della Matrice Vuoto")
        addItem(NTechItems.isaRune, "Catalista della Matrice Freddo")
        addItem(NTechItems.dagazRune, "Catalista della Matrice Bilanciato")
        addItem(NTechItems.hagalazRune, "Catalista della Matrice Grezzo")
        addItem(NTechItems.jeraRune, "Catalista della Matrice Moltiplicativa")
        addItem(NTechItems.thurisazRune, "Catalista della Matrice Addizionale")

        addItem(NTechItems.burnedOutQuadSchrabidiumFuelRod, "Quadrupla barra di Schrabidio Consumato")
        addItemDesc(NTechItems.burnedOutQuadSchrabidiumFuelRod, "Una quadrupla barra di carburante che contiene un\npò di elemento molto strano e nuovo.")

        addItem(NTechItems.scrap, "Rottame")
        addItem(NTechItems.hotDepletedUraniumFuel, "Carburante di Uranio Impoverito Rovente")
        addItem(NTechItems.hotDepletedThoriumFuel, "Carburante di Torio Impoverito Rovente")
        addItem(NTechItems.hotDepletedPlutoniumFuel, "Carburante di Plutonio Impovrito Rovente")
        addItem(NTechItems.hotDepletedMOXFuel, "Carburante MOX Impoverito Rovente")
        addItem(NTechItems.hotDepletedSchrabidiumFuel, "Carburante di Schrabidio Impoverito Rovente")
        addItem(NTechItems.depletedUraniumFuel, "Carburante di Uranio Impoverito")
        addItem(NTechItems.depletedThoriumFuel, "Carburante di Torio Impoverito")
        addItem(NTechItems.depletedPlutoniumFuel, "Carburante di Plutonio Impoverito")
        addItem(NTechItems.depletedMOXFuel, "Carburante MOX Impoverito")
        addItem(NTechItems.depletedSchrabidiumFuel, "Carburante di Schrabidio Impoverito")
        addItem(NTechItems.trinitite, "Trinitite")
        addItem(NTechItems.nuclearWaste, "Scarti Nucleari")
        addItem(NTechItems.tinyNuclearWaste, "Piccoli Scarti Nucleari")

        addItem(NTechItems.crystalHorn, "Corno di Cristallo")
        addItemDesc(NTechItems.crystalHorn, "Un vero corno.")
        addItem(NTechItems.charredCrystal, "Cristallo Carbonizzato")
        addItemDesc(NTechItems.charredCrystal, "Anche questo è un vero corno. Strano, vero?")

        addItem(NTechItems.battery, "Batteria")
        addItem(NTechItems.redstonePowerCell, "Cella Energetica di Redstone")
        addItem(NTechItems.sixfoldRedstonePowerCell, "Cella Energetica Sestupla di Redstone")
        addItem(NTechItems.twentyFourFoldRedstonePowerCell, "Cella Energetica con 24 parti di Redstone")
        addItem(NTechItems.advancedBattery, "Batteria Avanzata")
        addItem(NTechItems.advancedPowerCell, "Cella Energetica Avanzata")
        addItem(NTechItems.quadrupleAdvancedPowerCell, "Cella Energetica Quadrupla Avanzata")
        addItem(NTechItems.twelveFoldAdvancedPowerCell, "Cella Energetica alla Dodicesima Avanzata")
        addItem(NTechItems.lithiumBattery, "Batteria agli Ioni di Litio")
        addItem(NTechItems.lithiumPowerCell, "Cella Energetica agli Ioni di Litio")
        addItem(NTechItems.tripleLithiumPowerCell, "Cella Energetica Tripla agli Ioni di Litio")
        addItem(NTechItems.sixfoldLithiumPowerCell, "Cella Energetica x6 agli Ioni di Litio")
        addItem(NTechItems.schrabidiumBattery, "Batteria di Schrabidio")
        addItem(NTechItems.schrabidiumPowerCell, "Cella Energetica di Schrabidio")
        addItem(NTechItems.doubleSchrabidiumPowerCell, "Cella Energetica Doppia di Schrabidio")
        addItem(NTechItems.quadrupleSchrabidiumPowerCell, "Cella Energetica Quadrupla di Schrabidio")
        addItem(NTechItems.sparkBattery, "Batteria a Scintilla")
        addItem(NTechItems.offBrandSparkBattery, "Batteria a Scintilla Fuori Marchio")
        addItem(NTechItems.sparkPowerCell, "Cella Energetica a Scintilla")
        addItem(NTechItems.sparkArcaneCarBattery, "Batteria per Auto Arcana a Scintilla")
        addItem(NTechItems.sparkArcaneEnergyStorageArray, "Apparato Energetico Arcano per Scintilla")
        addItem(NTechItems.sparkArcaneMassEnergyVoid, "Scintilla Arcana con Vuoto Massa-Energia")
        addItem(NTechItems.sparkArcaneDiracSea, "Scintilla Arcana del Mare di Dirac")
        addItem(NTechItems.sparkSolidSpaceTimeCrystal, "Scintilla Arcana del Cristallo Spazio-Tempo")
        addItem(NTechItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit, "Unità di Energia Scintilla Assurda di Energia Piega-Fisica")
        addItem(NTechItems.infiniteBattery, "Batteria Infinita")
        addItem(NTechItems.singleUseBattery, "Batteria a Uso Singolo")
        addItem(NTechItems.largeSingleUseBattery, "Batteria Grande a Uso Singolo")
        addItem(NTechItems.potatoBattery, "Batteria Patata")
        addItem(NTechItems.steamPoweredEnergyStorageTank, "Tanica conserva Energia Alimentata a Vapore")
        addItem(NTechItems.largeSteamPoweredEnergyStorageTank, "Tanica conserva Energia Alimentata a Vapore Grande")

        addItem(NTechItems.stoneFlatStamp, "Stampo Piatto (Pietra)")
        addItem(NTechItems.stonePlateStamp, "Stampo per Lastre (Pietra)")
        addItem(NTechItems.stoneWireStamp, "Stampo per Cavi (Pietra)")
        addItem(NTechItems.stoneCircuitStamp, "Stampo per Circuiti (Pietra)")
        addItem(NTechItems.ironFlatStamp, "Stampo Piatto (Ferro)")
        addItem(NTechItems.ironPlateStamp, "Stampo per Lastre (Ferro)")
        addItem(NTechItems.ironWireStamp, "Stampo per Cavi (Ferro)")
        addItem(NTechItems.ironCircuitStamp, "Stampo per Circuiti (Ferro)")
        addItem(NTechItems.steelFlatStamp, "Stampo Piatto (Acciaio)")
        addItem(NTechItems.steelPlateStamp, "Stampo per Lastre (Acciaio)")
        addItem(NTechItems.steelWireStamp, "Stampo per Cavi (Acciaio)")
        addItem(NTechItems.steelCircuitStamp, "Stampo per Circuiti (Acciaio)")
        addItem(NTechItems.titaniumFlatStamp, "Stampo Piatto (Titanio)")
        addItem(NTechItems.titaniumPlateStamp, "Stampo per Lastre (Titanio)")
        addItem(NTechItems.titaniumWireStamp, "Stampo per Cavi (Titanio)")
        addItem(NTechItems.titaniumCircuitStamp, "Stampo per Circuiti (Titanio)")
        addItem(NTechItems.obsidianFlatStamp, "Stampo Piatto (Ossidiana)")
        addItem(NTechItems.obsidianPlateStamp, "Stampo per Lastre (Ossidiana)")
        addItem(NTechItems.obsidianWireStamp, "Stampo per Cavi (Ossidiana)")
        addItem(NTechItems.obsidianCircuitStamp, "Stampo per Circuiti (Ossidiana)")
        addItem(NTechItems.schrabidiumFlatStamp, "Stampo Piatto (Schrabidio)")
        addItem(NTechItems.schrabidiumPlateStamp, "Stampo per Lastre (Schrabidio)")
        addItem(NTechItems.schrabidiumWireStamp, "Stampo per Cavi (Schrabidio)")
        addItem(NTechItems.schrabidiumCircuitStamp, "Stampo per Circuiti (Schrabidio)")

        addItem(NTechItems.screwdriver, "Cacciavite")
        addItemDesc(NTechItems.screwdriver, "Potrebbe essere usato al posto di un fusibile...")
        addItem(NTechItems.deshScrewdriver, "Cacciavite di Desh")

        addItem(NTechItems.speedUpgradeMk1, "Potenziamento Velocità Mk.I")
        addItem(NTechItems.speedUpgradeMk2, "Potenziamento Velocità Mk.II")
        addItem(NTechItems.speedUpgradeMk3, "Potenziamento Velocità Mk.III")
        addItem(NTechItems.powerSavingUpgradeMk1, "Potenziamento Salva-Energia Mk.I")
        addItem(NTechItems.powerSavingUpgradeMk2, "Potenziamento Salva-Energia Mk.II")
        addItem(NTechItems.powerSavingUpgradeMk3, "Potenziamento Salva-Energia Mk.III")
        addItem(NTechItems.overdriveUpgradeMk1, "Potenziamento Overdrive Mk.I")
        addItem(NTechItems.overdriveUpgradeMk2, "Potenziamento Overdrive Mk.II")
        addItem(NTechItems.overdriveUpgradeMk3, "Potenziamento Overdrive Mk.III")
        addItem(NTechItems.afterBurnUpgradeMk1, "Potenziamento Postbruciatore Mk.I")
        addItem(NTechItems.afterBurnUpgradeMk2, "Potenziamento Postbruciatore Mk.II")
        addItem(NTechItems.afterBurnUpgradeMk3, "Potenziamento Postbruciatore Mk.III")

        addItem(NTechItems.aluminiumShredderBlade, "Lame per Trituratore di Alluminio")
        addItem(NTechItems.goldShredderBlade, "Lame per Trituratore di Oro")
        addItem(NTechItems.ironShredderBlade, "Lame per Trituratore di Ferro")
        addItem(NTechItems.steelShredderBlade, "Lame per Trituratore di Acciaio")
        addItem(NTechItems.titaniumShredderBlade, "Lame per Trituratore di Titanio")
        addItem(NTechItems.advancedAlloyShredderBlade, "Lame per Trituratore di Lega Avanzata")
        addItem(NTechItems.combineSteelShredderBlade, "Lame per Trituratore di Acciaio Combinato")
        addItem(NTechItems.schrabidiumShredderBlade, "Lame per Trituratore di Schrabidio")
        addItem(NTechItems.deshShredderBlade, "Lame per Trituratore di Desh")

        addItem(NTechItems.rbmkLid, "Pannello di Copertura RBMK")
        addItem(NTechItems.rbmkGlassLid, "Pannello di Copertira di Vetro RBMK")

        addItem(NTechItems.rbmkPelletBalefire, "Pepita di Carburante di Balefire")
        addItem(NTechItems.rbmkPelletBalefireGold, "Pepita di Carburante di Flashgold")
        addItem(NTechItems.rbmkPelletDrx, "§cPepita di Carburante di Digamma§r")
        addItem(NTechItems.rbmkPelletFlashlead, "Pepita di Carburante di Flashlead")
        addItem(NTechItems.rbmkPelletHea241, "Pepita di Carburante di HEA-241")
        addItem(NTechItems.rbmkPelletHea242, "Pepita di Carburante di HEA-242")
        addItem(NTechItems.rbmkPelletHeaus, "Pepita di Carburante di HEAus")
        addItem(NTechItems.rbmkPelletHen, "Pepita di Carburante di HEN")
        addItem(NTechItems.rbmkPelletHes, "Pepita di Carburante di HEP-239")
        addItem(NTechItems.rbmkPelletHep239, "Pepita di Carburante di HEP-241")
        addItem(NTechItems.rbmkPelletHep241, "Pepita di Carburante di HEU-233")
        addItem(NTechItems.rbmkPelletHeu233, "Pepita di Carburante di HEU-235")
        addItem(NTechItems.rbmkPelletHeu235, "Pepita di Carburante di HES")
        addItem(NTechItems.rbmkPelletLea, "Pepita di Carburante di LEA")
        addItem(NTechItems.rbmkPelletLeaus, "Pepita di Carburante di LEAus")
        addItem(NTechItems.rbmkPelletLep, "Pepita di Carburante di LEP")
        addItem(NTechItems.rbmkPelletLes, "Pepita di Carburante di LES")
        addItem(NTechItems.rbmkPelletMea, "Pepita di Carburante di MEA")
        addItem(NTechItems.rbmkPelletMen, "Pepita di Carburante di MEN")
        addItem(NTechItems.rbmkPelletMep, "Pepita di Carburante di MEP")
        addItem(NTechItems.rbmkPelletMes, "Pepita di Carburante di MES")
        addItem(NTechItems.rbmkPelletMeu, "Pepita di Carburante di MEU")
        addItem(NTechItems.rbmkPelletMox, "Pepita di Carburante di MOX")
        addItem(NTechItems.rbmkPelletPo210Be, "Pepita Risorsa di Neutroni Po210Be")
        addItem(NTechItems.rbmkPelletPu238Be, "Pepita Risorsa di Neutroni Pu238Be")
        addItem(NTechItems.rbmkPelletRa226Be, "Pepita Risorsa di Neutroni Ra226Be")
        addItem(NTechItems.rbmkPelletThMeu, "Pepita di Carburante ThMEU")
        addItem(NTechItems.rbmkPelletUeu, "Pepita di Carburante NU")
        addItem(NTechItems.rbmkPelletZfbAmMix, "Pepita di Carburante di Americio Graduato ZFB")
        addItem(NTechItems.rbmkPelletZfbBismuth, "Pellet di Bismuto ZFB")
        addItem(NTechItems.rbmkPelletZfbPu241, "Pellet di Pu-241 ZFB")

        addItem(NTechItems.emptyRBMKRod, "Barra di Carburante RBMK Vuota")
        addItem(NTechItems.rbmkRodBalefire, "Barra di Carburante Balefire RBMK")
        addItem(NTechItems.rbmkRodBalefireGold, "Barra di Carburante Flashgold RBMK")
        addItem(NTechItems.rbmkRodDrx, "§cBarra di Carburante Digamma RBMK§r")
        addItem(NTechItems.rbmkRodFlashlead, "Barra di Carburante Flashlead RBMK")
        addItem(NTechItems.rbmkRodHea241, "Barra di Carburante HEA-241 RBMK")
        addItem(NTechItems.rbmkRodHea242, "Barra di Carburante HEA-242 RBMK")
        addItem(NTechItems.rbmkRodHeaus, "Barra di Carburante HEAus RBMK")
        addItem(NTechItems.rbmkRodHen, "Barra di Carburante HEN RBMK")
        addItem(NTechItems.rbmkRodHes, "Barra di Carburante HES RBMK")
        addItem(NTechItems.rbmkRodHep239, "Barra di Carburante HEP-239 RBMK")
        addItem(NTechItems.rbmkRodHep241, "Barra di Carburante HEP-241 RBMK")
        addItem(NTechItems.rbmkRodHeu233, "Barra di Carburante HEU-233 RBMK")
        addItem(NTechItems.rbmkRodHeu235, "Barra di Carburante HEU-235 RBMK")
        addItem(NTechItems.rbmkRodLea, "Barra di Carburante LEA RBMK")
        addItem(NTechItems.rbmkRodLeaus, "Barra di Carburante LEAus RBMK")
        addItem(NTechItems.rbmkRodLep, "Barra di Carburante LEP-239 RBMK")
        addItem(NTechItems.rbmkRodLes, "Barra di Carburante LES RBMK")
        addItem(NTechItems.rbmkRodMea, "Barra di Carburante MEA RBMK")
        addItem(NTechItems.rbmkRodMen, "Barra di Carburante MEN RBMK")
        addItem(NTechItems.rbmkRodMep, "Barra di Carburante MEP-239 RBMK")
        addItem(NTechItems.rbmkRodMes, "Barra di Carburante MES RBMK")
        addItem(NTechItems.rbmkRodMeu, "Barra di Carburante MEU RBMK")
        addItem(NTechItems.rbmkRodMox, "Barra di Carburante MOX RBMK")
        addItem(NTechItems.rbmkRodPo210Be, "Risorsa di Neutroni Po210Be RBMK")
        addItem(NTechItems.rbmkRodPu238Be, "Risorsa di Neutroni Pu238Be RBMK")
        addItem(NTechItems.rbmkRodRa226Be, "Risorsa di Neutroni Ra226Be RBMK")
        addItem(NTechItems.rbmkRodThMeu, "Barra di Carburante ThMEU RBMK")
        addItem(NTechItems.rbmkRodUeu, "Barra di Carburante NU RBMK")
        addItem(NTechItems.rbmkRodZfbAmMix, "Barra di Carburante di Americio Graduato ZFB RBMK")
        addItem(NTechItems.rbmkRodZfbBismuth, "Barra di Carburante Bismuto RBMK ZFB")
        addItem(NTechItems.rbmkRodZfbPu241, "Barra Pu-241 RBMK ZFB")

        addItem(NTechItems.meltdownTool, "Applicatore Istantaneo di Fusione Dyatlov")

        addItem(NTechItems.graphiteDebris, "Pezzo di Grafite Rovente")
        addItem(NTechItems.metalDebris, "Asta di Metallo rotta")
        addItem(NTechItems.fuelDebris, "Pezzo di Carburante RBMK")

        addItem(NTechItems.machineTemplateFolder, "Cartella dei Modelli della Macchina")
        addItemDesc(
            NTechItems.machineTemplateFolder,
            "Modelli della Macchina: Carta + Colorante\n" +
                    "ID dei Fluidi: Lastra di Ferro + Colorante\n" +
                    "Stampi della Pressa: Stampo Piatto\n" +
                    "Audio della Sirena: Isolante + Lastra di Acciaio"
        )

        addItem(NTechItems.sirenTrackHatchSiren, "Sirena del Portellone")
        addItem(NTechItems.sirenTrackAutopilotDisconnected, "Autopilota Disconnesso")
        addItem(NTechItems.sirenTrackAMSSiren, "Sirena AMS")
        addItem(NTechItems.sirenTrackBlastDoorAlarm, "Allarme della Porta Blindata")
        addItem(NTechItems.sirenTrackAPCSiren, "Sirena APC")
        addItem(NTechItems.sirenTrackKlaxon, "Clacson")
        addItem(NTechItems.sirenTrackVaultDoorAlarm, "Allarme della Porta del Caveau")
        addItem(NTechItems.sirenTrackSecurityAlert, "Allarme di Sicurezza")
        addItem(NTechItems.sirenTrackStandardSiren, "Sirena Standard")
        addItem(NTechItems.sirenTrackClassicSiren, "Sirena Classica")
        addItem(NTechItems.sirenTrackBankAlarm, "Allarme della Banca")
        addItem(NTechItems.sirenTrackBeepSiren, "Sirena Bip")
        addItem(NTechItems.sirenTrackContainerAlarm, "Allarme del Container")
        addItem(NTechItems.sirenTrackSweepSiren, "Allarme Spazzata")
        addItem(NTechItems.sirenTrackMissileSiloSiren, "Allarme Silo Missilistico")
        addItem(NTechItems.sirenTrackAirRaidSiren, "Allarme Assalto Aereo")
        addItem(NTechItems.sirenTrackNostromoSelfDestruct, "Autodistruzione Nostromo")
        addItem(NTechItems.sirenTrackEASAlarmScreech, "Allarme Stridio di EAS")
        addItem(NTechItems.sirenTrackAPCPass, "APC Pass")
        addItem(NTechItems.sirenTrackRazortrainHorn, "Corno Razortrain")

        addItem(NTechItems.fluidIdentifier, "Identificatore di Fluidi: %s")
        addItemDesc(NTechItems.fluidIdentifier, "Click destro sul tubo per fluidi per designarli a quel fluido.\nShift click destro li designerà a un condotto adiacente\nfino a un massimo di 64 condotti.")

        addItem(NTechItems.assemblyTemplate, "Modello di Assemblaggio: %s")
        addItem(NTechItems.chemTemplate, "Modello di Chimica: %s")

        run {
            val usedInLittleBoy = "Usato per:\nLittle Boy"
            addItem(NTechItems.neutronShieldingLittleBoy, "Schermata di Neutroni")
            addItemDesc(NTechItems.neutronShieldingLittleBoy, usedInLittleBoy)
            addItem(NTechItems.subcriticalUraniumTarget, "Bersaglio Supercritico di U235")
            addItemDesc(NTechItems.subcriticalUraniumTarget, usedInLittleBoy)
            addItem(NTechItems.uraniumProjectile, "Proiettile U235")
            addItemDesc(NTechItems.uraniumProjectile, usedInLittleBoy)
            addItem(NTechItems.propellantLittleBoy, "Propellente")
            addItemDesc(NTechItems.propellantLittleBoy, usedInLittleBoy)
            addItem(NTechItems.bombIgniterLittleBoy, "Attivatore della Bomba")
            addItemDesc(NTechItems.bombIgniterLittleBoy, usedInLittleBoy)
        }
        addItem(NTechItems.bundleOfImplosionPropellant, "Pacchetto di Propellente Implosivo")
        addItemDesc(NTechItems.bundleOfImplosionPropellant, "Usato per:\nFat Man\nIvy Mike\nBomba Tsar")
        addItem(NTechItems.bombIgniterFatMan, "Attivatore della Bomba")
        addItemDesc(NTechItems.bombIgniterFatMan, "Usato per Fat Man")
        addItem(NTechItems.plutoniumCore, "Nucleo di Plutonio")
        addItemDesc(NTechItems.plutoniumCore, "Usato per:\nFat Man\nIvy Mike\nBomba Tsar")
        addItem(NTechItems.detonator, "Detonatore")
        addItemDesc(NTechItems.detonator, "Shift clock destro su un ordigno per impostare la posizione,\nclick destro per detonare!")
        addItem(NTechItems.littleBoyKit, "Pacchetto Little Boy")
        addItem(NTechItems.fatManKit, "Pacchetto Fat Man")

        addItem(NTechItems.designator, "Designatore di Bersagli a Corto Raggio")
        addItem(NTechItems.heMissile, "Missile Altamente Esplosivo")
        addItem(NTechItems.incendiaryMissile, "Missile Incendiario")
        addItem(NTechItems.clusterMissile, "Missile a Grappolo")
        addItem(NTechItems.bunkerBusterMissile, "Sfonda Bunker")
        addItem(NTechItems.strongMissile, "Missile Altamente Esplosivo Forte")
        addItem(NTechItems.strongIncendiaryMissile, "Missile Incendiario Forte")
        addItem(NTechItems.strongClusterMissile, "Missile a Grappolo Forte")
        addItem(NTechItems.strongBunkerBusterMissile, "Sfonda Bunker Migliorato")
        addItem(NTechItems.burstMissile, "Missile a Fiammata")
        addItem(NTechItems.infernoMissile, "Missile Inferno G.R.N. Mk.II")
        addItem(NTechItems.rainMissile, "Pioggia di Bombette")
        addItem(NTechItems.drillMissile, "Lo spezza Cemento")
        addItem(NTechItems.nuclearMissile, "Missile Nucleare")
        addItem(NTechItems.tectonicMissile, "Missile Tettonico")
        addItemDesc(NTechItems.tectonicMissile, "Con il potere delle bombe nucleari, possiamo generare un vulcano!")

        addItem(NTechItems.oilDetector, "Rilevatore di Riserve Petrolifere")
        addItemDesc(NTechItems.oilDetector, "Click destro per cercare petrolio.\nIl rilevatore troverà solo depositi grandi.")
        addItem(NTechItems.rbmkLinker, "Connettore Console RBMK")
        addItemDesc(NTechItems.rbmkLinker, "Shift click destro su RBMK per salvare la posizione, shift click destro sulla console per collegare!")
        addItem(NTechItems.geigerCounter, "Contatore Geiger a mano")

        addItem(NTechItems.ivBag, "Borsa Flebo")
        addItem(NTechItems.bloodBag, "Flebo di Sangue")
        addItem(NTechItems.emptyExperienceBag, "Flebo per Esperienza Vuota")
        addItem(NTechItems.experienceBag, "Flebo di Esperienza")
        addItem(NTechItems.hazmatBoots, "Stivali Anti-Radiazioni")
        addItem(NTechItems.hazmatHelmet, "Elmetto Anti-Radizioni")
        addItem(NTechItems.hazmatLeggings, "Pantaloni Anti-Radiazioni")
        addItem(NTechItems.hazmatChestplate, "Corpetto Anti-Radiazioni")
        addItem(NTechItems.advancedHazmatHelmet, "Elmetto Anti-Radiazioni Avanzato")
        addItem(NTechItems.advancedHazmatChestplate, "Corpetto Anti-Radiazioni Avanzato")
        addItem(NTechItems.advancedHazmatLeggings, "Pantaloni Anti-Radiazioni Avanzato")
        addItem(NTechItems.advancedHazmatBoots, "Stivali Anti-Radiazioni Avanzato")
        addItem(NTechItems.reinforcedHazmatHelmet, "Elmetto Anti-Radiazioni ad Alte Prestazioni")
        addItem(NTechItems.reinforcedHazmatChestplate, "Corpetto Anti-Radiazioni ad Alte Prestazioni")
        addItem(NTechItems.reinforcedHazmatLeggings, "Pantaloni Anti-Radiazioni ad Alte Prestazioni")
        addItem(NTechItems.reinforcedHazmatBoots, "Stivali Anti-Radiazioni ad Alte Prestazioni")
        addItem(NTechItems.titaniumHelmet, "Elmetto in Titanio")
        addItem(NTechItems.titaniumChestplate, "Corpetto in Titanio")
        addItem(NTechItems.titaniumLeggings, "Pantaloni in Titanio")
        addItem(NTechItems.titaniumBoots, "Stivali in Titanio")
        addItem(NTechItems.steelHelmet, "Elmetto in Acciaio")
        addItem(NTechItems.steelChestplate, "Corpetto in Acciaio")
        addItem(NTechItems.steelLeggings, "Pantaloni in Acciaio")
        addItem(NTechItems.steelBoots, "Stivali in Acciaio")
        addItem(NTechItems.advancedAlloyHelmet, "Elmetto di Lega Avanzata")
        addItem(NTechItems.advancedAlloyChestplate, "Corpetto di Lega Avanzata")
        addItem(NTechItems.advancedAlloyLeggings, "Pantaloni di Lega Avanzata")
        addItem(NTechItems.advancedAlloyBoots, "Stivali di Lega Avanzata")
        addItem(NTechItems.combineSteelHelmet, "Elmetto di Acciaio Combinato")
        addItem(NTechItems.combineSteelChestplate, "Elmetto di Acciaio Combinato")
        addItem(NTechItems.combineSteelLeggings, "Pantaloni di Acciaio Combinato")
        addItem(NTechItems.combineSteelBoots, "Stivali di Acciaio Combinato")
        addItem(NTechItems.paAAlloyChestplate, "Piastra Proteggi-Petto PaA")
        addItem(NTechItems.paAAlloyLeggings, "Piastra Proteggi-Gambe PaA")
        addItem(NTechItems.paAAlloyBoots, "\"Le vecchie buone scarpe \"PaA")
        addItem(NTechItems.schrabidiumHelmet, "Elmetto di Schrabidio")
        addItem(NTechItems.schrabidiumChestplate, "Corpetto di Schrabidio Chestplate")
        addItem(NTechItems.schrabidiumLeggings, "Pantaloni Schrabidio")
        addItem(NTechItems.schrabidiumBoots, "Stivali di Schrabidio")

        addItem(NTechItems.polaroid, "La Fotografia")

        addItem(NTechFluids.steam.bucket, "Secchio di Vapore")
        addItem(NTechFluids.steamHot.bucket, "Secchio di Vapore Denso")
        addItem(NTechFluids.steamSuperHot.bucket, "Secchio di Vapore Super Denso")
        addItem(NTechFluids.steamUltraHot.bucket, "Secchio di Vapore Ultra Denso")
        addItem(NTechFluids.gas.bucket, "Secchio di Gas Naturale")
        addItem(NTechFluids.oil.bucket, "Secchio di Petrolio")
        addItem(NTechFluids.uraniumHexafluoride.bucket, "Secchio di Esafluoruro di Uranio")
        addItem(NTechFluids.corium.bucket, "Secchio di Corio")
        addItem(NTechFluids.volcanicLava.bucket, "Secchio di Lava Vulcanica")

        addItem(NTechItems.creativeNuclearExplosionSpawner, "Generatore di Esplosioni Nucleari")

        addEntityType(EntityTypes.nuclearExplosion, "Esplosione Nucleare")
        addEntityType(EntityTypes.mushroomCloud, "Nuvola a Fungo")
        addEntityType(EntityTypes.falloutRain, "Pioggia Nucleare")
        addEntityTypeWithSpawnEgg(EntityTypes.nuclearCreeper, "Creeper Nucleare")

        addEntityType(EntityTypes.missileHE, "Missile Altamente Esplosivo")
        addEntityType(EntityTypes.missileIncendiary, "Missile Incendiario")
        addEntityType(EntityTypes.missileCluster, "Missile a Grappolo")
        addEntityType(EntityTypes.missileBunkerBuster, "Sfonda Bunker")
        addEntityType(EntityTypes.missileHEStrong, "Missile Altamente Esplosivo Forte")
        addEntityType(EntityTypes.missileIncendiaryStrong, "Missile Incendiario Forte")
        addEntityType(EntityTypes.missileClusterStrong, "Missile a Grappolo Forte")
        addEntityType(EntityTypes.missileBunkerBusterStrong, "Sfonda Bunker Migliorato")
        addEntityType(EntityTypes.missileBurst, "Missile a Fiammata")
        addEntityType(EntityTypes.missileInferno, "Missile Inferno G.R.N. Mk.II")
        addEntityType(EntityTypes.missileRain, "Pioggia di Bombette")
        addEntityType(EntityTypes.missileDrill, "Lo Spacca Cemento")
        addEntityType(EntityTypes.missileNuclear, "Missile Nucleare")
        addEntityType(EntityTypes.missileTectonic, "Missile Tettonico")

        addEntityType(EntityTypes.oilSpill, "Goccia di Petrolio")

        addEntityType(EntityTypes.clusterFragment, "Bombetta")
        addEntityType(EntityTypes.shrapnel, "Scheggia")
        addEntityType(EntityTypes.volcanicShrapnel, "Scheggia Vulcanica")

        addMenuType(MenuTypes.sirenMenu, "Sirena")
        addMenuType(MenuTypes.safeMenu, "Cassaforte")
        addMenuType(MenuTypes.anvilMenu, "Incudine di Livello %s")
        addMenuType(MenuTypes.steamPressMenu, "Pressa a Vapore")
        addMenuType(MenuTypes.blastFurnaceMenu, "Forno Fusorio")
        addMenuType(MenuTypes.combustionGeneratorMenu, "Generatore a Combustione")
        addMenuType(MenuTypes.electricFurnaceMenu, "Fornace Elettrica")
        addMenuType(MenuTypes.shredderMenu, "Trituratore")
        addMenuType(MenuTypes.assemblerMenu, "Assemblatore")
        addMenuType(MenuTypes.chemPlantMenu, "Impianto Chimico")
        addMenuType(MenuTypes.oilWellMenu, "Pozzo di Petrolio")
        add(LangKeys.CONTAINER_OIL_DERRICK, "Torre Petrolifera")
        add(LangKeys.CONTAINER_PUMPJACK, "Pompa Petrolifera")
        addMenuType(MenuTypes.centrifugeMenu, "Centrifuga")
        addMenuType(MenuTypes.rbmkRodMenu, "Barra di Carburante RBMK")
        add(LangKeys.CONTAINER_RBMK_REASIM_ROD, "Barra di Carburante RBMK (ReaSim)")
        addMenuType(MenuTypes.rbmkBoilerMenu, "Bollitore a Vapore RBMK")
        addMenuType(MenuTypes.rbmkManualControlMenu, "Barre di Controllo RBMK")
        add(LangKeys.CONTAINER_RBMK_CONTROL_MODERATED, "Barre di Controllo Moderate RBMK")
        addMenuType(MenuTypes.rbmkAutoControlMenu, "Barre di Controllo Automatiche RBMK")
        addMenuType(MenuTypes.rbmkConsoleMenu, "Console RBMK")

        addMenuType(MenuTypes.littleBoyMenu, "Little Boy")
        addMenuType(MenuTypes.fatManMenu, "Fat Man")

        addMenuType(MenuTypes.launchPadMenu, "Pedana per Missili")

        add("subtitle.$MODID.geiger.click", "Contatore Geiger suona")
        addSound(SoundEvents.anvilFall, "Incudine impatta")
        addSound(SoundEvents.assemblerOperate, "Assemblatore ronza")
        addSound(SoundEvents.chemPlantOperate, "Impianto Chimico opera")
        addSound(SoundEvents.centrifugeOperate, "Centrifuga mormora")
        addSound(SoundEvents.debris, "Detriti colpiscono il terreno")
        addSound(SoundEvents.emptyIVBag, "Liquido infuso")
        addSound(SoundEvents.inject, "Ago iniettato")
        addSound(SoundEvents.installUpgrade, "Potenziamento installato")
        addSound(SoundEvents.miniNukeExplosion, "Mini nuke esplode")
        addSound(SoundEvents.missileTakeoff, "Missile decolla")
        addSound(SoundEvents.pressOperate, "Pressa stampa")
        addSound(SoundEvents.randomBleep, "Dispositivo suona")
        addSound(SoundEvents.randomBoop, "Dispositivo suona")
        addSound(SoundEvents.randomUnpack, "Oggetto disimballato")
        addSound(SoundEvents.rbmkAz5Cover, "Coperchio AZ-3 aperto")
        addSound(SoundEvents.rbmkShutdown, "RBMK si spegne")
        addSound(SoundEvents.sirenTrackAMSSiren, "Sirena suona: Sirena AMS")
        addSound(SoundEvents.sirenTrackAPCPass, "Sirena suona: Passaggio APC")
        addSound(SoundEvents.sirenTrackAPCSiren, "Sirena suona: Sirena APC")
        addSound(SoundEvents.sirenTrackAirRaidSiren, "Sirena suona: Allarme Assalto Aereo")
        addSound(SoundEvents.sirenTrackAutopilotDisconnected, "Sirena suona: Autopilota Disconnesso")
        addSound(SoundEvents.sirenTrackBankAlarm, "Sirena suona: Allarme della Banca")
        addSound(SoundEvents.sirenTrackBeepSiren, "Sirena suona Siren running: Sirena Bip")
        addSound(SoundEvents.sirenTrackBlastDoorAlarm, "Sirena suona: Allarme della Porta Blindata")
        addSound(SoundEvents.sirenTrackClassicSiren, "Sirena suona : Sirena Classica")
        addSound(SoundEvents.sirenTrackContainerAlarm, "Sirena suona: Allarme del Container")
        addSound(SoundEvents.sirenTrackEASAlarmScreech, "Sirena suona Siren running: Allarme Stridio di EAS")
        addSound(SoundEvents.sirenTrackHatchSiren, "Sirena suona: Sirena del Portellone")
        addSound(SoundEvents.sirenTrackKlaxon, "Sirena suona: Clacson")
        addSound(SoundEvents.sirenTrackMissileSiloSiren, "Sirena suona: Sirena del SIlo Missilistico")
        addSound(SoundEvents.sirenTrackNostromoSelfDestruct, "Sirena suona: Autodistruzione Nostromo")
        addSound(SoundEvents.sirenTrackRazortrainHorn, "Sirena suona: Corno Razortrain")
        addSound(SoundEvents.sirenTrackSecurityAlert, "Sirena suona: Allarme di Sicurezza")
        addSound(SoundEvents.sirenTrackStandardSiren, "Sirena suona: Sirena Standard")
        addSound(SoundEvents.sirenTrackSweepSiren, "Sirena suona: Allarme Spazzata")
        addSound(SoundEvents.sirenTrackVaultDoorAlarm, "Sirena suona: Allarme della Porta del Caveau")

        addDamageSource(DamageSources.extractBlood, "%1\$s ha estratto troppa essenza vitale", "%1\$s ha provato a lasciare ben confezionato del succo vitale per %2\$s")
        addDamageSource(DamageSources.murkyAnvil, "%1\$s NON DEFINITO", "%1\$s NON DEFINITO mentre cercava di scappare da %2\$s")
        addDamageSource(DamageSources.nuclearBlast, "%1\$s è esploso per mezzo di un'esplosione nucleare", "%1\$s è stato nuclearizzato mentre combatteva contro %2\$s")
        addDamageSource(DamageSources.radiation, "%1\$s è morto di avvelenamento da radiazioni", "%1\$s è stato/a vittima di un'acute sindrome da radiazioni mentre combatteva contro %2\$s")
        addDamageSource(DamageSources.shrapnel, "%1\$s è stato perforato da delle scheggie", "%1\$s è stato perforato da delle scheggie mentre combatteva contro %2\$s")

        addAttribute(Attributes.RADIATION_RESISTANCE, "Resistenza da Radiazioni")

        add(LangKeys.ARMOR_BLAST_PROTECTION, "Moltiplicatore del Danno di %s contro le esplosioni")
        add(LangKeys.ARMOR_CUSTOM_GEIGER, "Contatore Geiger pre-costruito nell'interfaccia")
        add(LangKeys.ARMOR_DAMAGE_CAP, "Capacità di danni pesanti di %s")
        add(LangKeys.ARMOR_DAMAGE_MODIFIER, "Modificatore del Danno di %s")
        add(LangKeys.ARMOR_DAMAGE_RESISTANCE_MODIFIER, "Modificatore del Danno di %s contro %s")
        add(LangKeys.ARMOR_DAMAGE_THRESHOLD, "Soglia del Danno di %s")
        add(LangKeys.ARMOR_DASH_COUNT, "Garantisce %s tratti")
        add(LangKeys.ARMOR_FIREPROOF, "Immunità al Fuoco")
        add(LangKeys.ARMOR_FULL_SET_BONUS, "Bonus Set Completo:")
        add(LangKeys.ARMOR_GEIGER_SOUND, "Contatore Geiger uditivo")
        add(LangKeys.ARMOR_GRAVITY, "Modificatore della Gravità di %s")
        add(LangKeys.ARMOR_HARD_LANDING, "Atterraggio Pesante")
        add(LangKeys.ARMOR_NULLIFIES_DAMAGE, "Annulla tutti i danni da %s")
        add(LangKeys.ARMOR_PROJECTILE_PROTECTION, "Modificatore del Danno di %s contro i proiettili")
        add(LangKeys.ARMOR_PROTECTION_YIELD, "La protezione si applica al danno <%s")
        add(LangKeys.ARMOR_THERMAL, "Vista Termica")
        add(LangKeys.ARMOR_VATS, "Interfaccia Nemica")

        add(LangKeys.BUTTON_CANCEL, "Cancella")
        add(LangKeys.BUTTON_START, "Inizia")

        add(LangKeys.CHEMISTRY_URANIUM_HEXAFLUORIDE, "Prodizione di Esafluoruro di Uranio")

        add(LangKeys.DETONATOR_INVALID_BLOCK_ENTITY, "Errore del Server: L'obbiettivo di BlockEntity non è valido!")
        add(LangKeys.DETONATOR_MISSING_COMPONENTS, "Mancano dei componenti all'esplosivo!")
        add(LangKeys.DETONATOR_NO_EXPLOSIVE, "L'obbiettivo non è un esplosivo valido!")
        add(LangKeys.DETONATOR_PROHIBITED, "La detonazione è stata proibita!")
        add(LangKeys.DETONATOR_SUCCESS, "Detonazione!")
        add(LangKeys.DETONATOR_UNKNOWN_ERROR, "Un errore sconosciuto si è presentato durante la detonazione")

        add(LangKeys.DEVICE_OIL_DETECTOR_BELOW, "Deposito di Petrolio rilevato sotto!")
        add(LangKeys.DEVICE_OIL_DETECTOR_NEAR, "Deposito di Petrolio rilevato vicino")
        add(LangKeys.DEVICE_OIL_DETECTOR_NO_OIL, "Nessun deposito rilevato")
        add(LangKeys.DEVICE_POSITION_SET, "Posizione impostata!")
        add(LangKeys.DEVICE_POSITION_NOT_LOADED, "La posizione non è caricata nel mondo al momento!")
        add(LangKeys.DEVICE_POSITION_NOT_SET, "Nessuna posizoine impostata!")

        add(LangKeys.ENERGY, "Energia")
        add(LangKeys.ENERGY_ENERGY_STORED, "Energia Conservata: %s/%sHE")
        add(LangKeys.ENERGY_CHARGE_RATE, "In entrata: %sHE/t")
        add(LangKeys.ENERGY_DISCHARGE_RATE, "In uscita: %sHE/t")

        add(LangKeys.EXPLOSION_SPAWNER_ERROR_EXTRA_FALLOUT, "Non è possibile analizzare altri valori di ricaduta")
        add(LangKeys.EXPLOSION_SPAWNER_ERROR_STRENGTH, "Non è possibile analizzare i valri di forza")
        add(LangKeys.EXPLOSION_SPAWNER_EXTRA_FALLOUT, "Ricaduta Extra")
        add(LangKeys.EXPLOSION_SPAWNER_HAS_FALLOUT, "Ha una Ricaduta")
        add(LangKeys.EXPLOSION_SPAWNER_MUTED, "Mutato")
        add(LangKeys.EXPLOSION_SPAWNER_NO_PERMISSION, "Non è possibile usare Generatore di Esplosioni Nucleari: Permessi mancanti")
        add(LangKeys.EXPLOSION_SPAWNER_POSITION, "Posizione")
        add(LangKeys.EXPLOSION_SPAWNER_STRENGTH, "Forza")

        add(LangKeys.GEIGER_CHUNK_RADIATION, "Radiazione nel chunk:")
        add(LangKeys.GEIGER_PLAYER_IRRADIATION, "Irradiazione del giocatore:")
        add(LangKeys.GEIGER_PLAYER_RESISTANCE, "Resistenza del giocatore:")
        add(LangKeys.GEIGER_TITLE, "CONTATORE GEIGER")
        add(LangKeys.GEIGER_TOTAL_ENVIRONMENTAL_RADIATION, "Radiazione completa dell'ambiente:")

        add(LangKeys.HAZARD_ASBESTOS, "[Amianto]")
        add(LangKeys.HAZARD_BLINDING, "[Accecante]")
        add(LangKeys.HAZARD_COAL, "[Polvere di Carbone]")
        add(LangKeys.HAZARD_DIGAMMA, "[Digamma]")
        add(LangKeys.HAZARD_EXPLOSIVE, "[Infiammabile / Esplosivo]")
        add(LangKeys.HAZARD_HEAT, "[Piroforico / Rovente]")
        add(LangKeys.HAZARD_HYDROREACTIVE, "[Idroreattivo]")
        add(LangKeys.HAZARD_RADIATON, "[Radioattivo]")

        add(LangKeys.INFO_INPUT, "Entrata:")
        add(LangKeys.INFO_INPUTS, "Entrate:")
        add(LangKeys.INFO_ORE_CLUSTER, "Rilascia solo quando rotto da un giocatore")
        add(LangKeys.INFO_OUTPUT, "Uscita:")
        add(LangKeys.INFO_OUTPUTS, "Uscite:")
        add(LangKeys.INFO_POSITION, "Posizione: %d %d %d")
        add(LangKeys.INFO_PRODUCTION_TIME, "Tempo di Produzione:")

        add(LangKeys.JEI_CATEGORY_ASSEMBLING, "Assemblaggio")
        add(LangKeys.JEI_CATEGORY_BLASTING, "Fondendo")
        add(LangKeys.JEI_CATEGORY_CHEMISTRY, "Chimica")
        add(LangKeys.JEI_CATEGORY_CONSTRUCTING, "Costruzione")
        add(LangKeys.JEI_CATEGORY_PRESSING, "Pressatura")
        add(LangKeys.JEI_CATEGORY_SHREDDING, "Triturazione")
        add(LangKeys.JEI_CATEGORY_SMITHING, "Fabbricazione")
        add(LangKeys.JEI_CATEGORY_TEMPLATE_FOLDER, "Cartella dei Modelli")
        add(LangKeys.JEI_EXPERIENCE, "%s Esperienza")
        add(LangKeys.JEI_OUTPUT_CHANCE, "Probabilità di Uscita:")
        add(LangKeys.JEI_TIER_MINIMUM, "Livello Minimo: %s")
        add(LangKeys.JEI_TIER_RANGE, "Grado del Livello: %s..%s")

        add(LangKeys.OIL_WELL_STATUS_OK, "Stato: Ok")
        add(LangKeys.OIL_WELL_STATUS_NO_OIL_SOURCE, "Stato: Nessuna risorsa di petoilo")
        add(LangKeys.OIL_WELL_STATUS_ERROR, "Stato: Non può operare")
        add(LangKeys.OIL_WELL_STATUS_OUT_OF_FLUID, "Stato: Nessuna soluzione di fracking")
        add(LangKeys.OIL_WELL_STATUS_LOOKING_FOR_OIL, "Stato: In cerca di petrolio")
        add(LangKeys.OIL_WELL_STATUS_NO_POWER, "Stato: Non c'è energia")

        add(LangKeys.RBMK_BOILER_STEAM, "Vapore: %d / %d")
        add(LangKeys.RBMK_BOILER_TYPE, "Compressore: %s")
        add(LangKeys.RBMK_BOILER_WATER, "Alimentazione di Acqua: %d / %d")
        add(LangKeys.RBMK_BURN_EULER, "SICURO / EULERIANA")
        add(LangKeys.RBMK_BURN_LINEAR, "PERICOLOSO / LINEARE")
        add(LangKeys.RBMK_BURN_LOGARITHMIC, "MEDIO / LOGARITMICA")
        add(LangKeys.RBMK_BURN_NEGATIVE_QUADRATIC, "PERICOLOSO / QUADRATICA NEGATIVA")
        add(LangKeys.RBMK_BURN_PASSIVE, "SICURA / PASSIVA")
        add(LangKeys.RBMK_BURN_QUADRATIC, "PERICOLOSA / QUADRATICA")
        add(LangKeys.RBMK_BURN_SIGMOID, "SICURA / SIGMOIDE")
        add(LangKeys.RBMK_BURN_SINE_SLOPE, "SPERIMENTALE / PENDENZA SINE")
        add(LangKeys.RBMK_BURN_SQUARE_ROOT, "MEDIA / RADICE QUADRATA")
        add(LangKeys.RBMK_CONSOLE_ASSIGN, "Assegnamento delle colonne selezionate su schermo #%d")
        add(LangKeys.RBMK_CONSOLE_DESELECT_CONTROL_RODS, "Deseleziona tutto")
        add(LangKeys.RBMK_CONSOLE_LINK, "RBMK collegato!")
        add(LangKeys.RBMK_CONSOLE_SELECT_CONTROL_RODS, "Seleziona tutte le barre di controllo")
        add(LangKeys.RBMK_CONSOLE_SELECT_GROUP, "Seleziona gruppo %s")
        add(LangKeys.RBMK_CONTROL_GROUP_BLUE, "§1Gruppo Blu")
        add(LangKeys.RBMK_CONTROL_GROUP_GREEN, "§aGruppo Verde")
        add(LangKeys.RBMK_CONTROL_GROUP_PURPLE, "§5Gruppo Viola")
        add(LangKeys.RBMK_CONTROL_GROUP_RED, "§cGruppo Rosso")
        add(LangKeys.RBMK_CONTROL_GROUP_YELLOW, "§eGruppo Giallo")
        add(LangKeys.RBMK_CONTROL_ROD_LEVEL, "%.1f%%")
        add(LangKeys.RBMK_HEAT, "Temperatura della Colonna: %.1f°C")
        add(LangKeys.RBMK_MODERATED, "Moderata")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE, "Fiamme Draconiche")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE_GOLD, "Anti-Idrogeno da del Lattice Magnetizzato di Oro-198")
        add(LangKeys.RBMK_NAME_PELLET_DRX, "§knon lo senti, non senti il tuono?")
        add(LangKeys.RBMK_NAME_PELLET_FLASHLEAD, "Anti-Idrogeno confinato da del Lattice Magnetizzato di Oro-198 e Piombo-209")
        add(LangKeys.RBMK_NAME_PELLET_HEA241, "Americio-241 Altamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_HEA242, "Americio-242 Altamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_HEAUS, "Australium Altamente Arricchito (Ayerite)")
        add(LangKeys.RBMK_NAME_PELLET_HEN, "Nettunio-237 Altamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_HEP239, "Plutonio-239 Altamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_HEP241, "Plutonio-241 Altamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_HES, "Schrabidio-326 Altamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_HEU233, "Uranio-233 Altamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_HEU235, "Uranio-235 Altamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_LEA, "Americio-242 Lievemente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_LEAUS, "Australium Lievemente Arricchito (Tasmanite)")
        add(LangKeys.RBMK_NAME_PELLET_LEP, "Plutonio-239 Lievemente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_LES, "Schrabidio Lievemente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_MEA, "Americio-242 Mediamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_MEN, "Neptunio-237 Mediamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_MEP, "Plutonio-239 Mediamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_MES, "Schrabidio-326 Mediamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_MEU, "Uranio-235 Mediamente Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_MOX, "Misto di Ossido di MEU & LEP")
        add(LangKeys.RBMK_NAME_PELLET_PO210BE, "Risorsa di Neutroni di Polonio-210 & Berillio")
        add(LangKeys.RBMK_NAME_PELLET_PU238BE, "Risorsa di Neutroni di Plutonio-238 & Berillio")
        add(LangKeys.RBMK_NAME_PELLET_RA226BE, "Risorsa di Neutroni di Radio-226 & Berillio")
        add(LangKeys.RBMK_NAME_PELLET_THMEU, "Torio con Carburante MEU Guidato")
        add(LangKeys.RBMK_NAME_PELLET_UEU, "Uranio non Arricchito")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_AM_MIX, "Allevatore Veloce di Zirconio - HEP-241#MEA")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_BISMUTH, "Allevatore Veloce di Zirconio - LEU/HEP-241#Bi")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_PU241, "Allevatore Veloce di Zirconio - HEU-235/HEP-240#Pu-241")
        add(LangKeys.RBMK_NEUTRON_FAST, "Neutroni Veloci")
        add(LangKeys.RBMK_NEUTRON_SLOW, "Neutroni Lenti")
        add(LangKeys.RBMK_NEUTRON_ANY, "Tutti i Neutroni")
        add(LangKeys.RBMK_PELLET_DEPLETION_FULL, "Completamente Impoverito")
        add(LangKeys.RBMK_PELLET_DEPLETION_HIGH, "Altamente Impoverito")
        add(LangKeys.RBMK_PELLET_DEPLETION_MODERATE, "Moderatemente Impoverito")
        add(LangKeys.RBMK_PELLET_DEPLETION_NEW, "Totalmente Nuovo")
        add(LangKeys.RBMK_PELLET_DEPLETION_SLIGHT, "Lievemente Impoverito")
        add(LangKeys.RBMK_PELLET_XENON_POISONED, "Veleno Xeno potente")
        add(LangKeys.RBMK_PELLET_RECYCLE, "Pellet per riciclo")
        add(LangKeys.RBMK_ROD_DEPLETION, "Impoverimento: %.3f%%")
        add(LangKeys.RBMK_ROD_DIFFUSION, "Diffusione: %s")
        add(LangKeys.RBMK_ROD_FLUX_FUNC, "Funzione del Flusso: %s")
        add(LangKeys.RBMK_ROD_FUNC_TYPE, "Tipo di Funzione: %s")
        add(LangKeys.RBMK_ROD_HEAT, "Calore per Flusso: %s")
        add(LangKeys.RBMK_ROD_HEAT_CORE, "Temperatura del Nucleo: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL, "Temperatura della Pelle: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL_TO_MELTING_POINT, "Temperature della Pelle: %.1f°C / %.1f°C")
        add(LangKeys.RBMK_ROD_MELTING_POINT, "Punto di Fusione: %s")
        add(LangKeys.RBMK_ROD_SOURCE, "Auto-Infiammabile")
        add(LangKeys.RBMK_ROD_SPLITS_INTO, "Si divide in: %s")
        add(LangKeys.RBMK_ROD_SPLITS_WITH, "Si divide con: %s")
        add(LangKeys.RBMK_ROD_XENON, "Avvelenamento di Xeno: %.3f%%")
        add(LangKeys.RBMK_ROD_XENON_BURN, "Funzione consumo di Xenon: %s")
        add(LangKeys.RBMK_ROD_XENON_GEN, "Funzione generazione di Xeno: %s")
        add(LangKeys.RBMK_SCREEN_DEPLETION, "Impov: %.1f%%")
        add(LangKeys.RBMK_SCREEN_FUEL_TEMPERATURE, "Nucleo: %.1f°C")
        add(LangKeys.RBMK_SCREEN_POISON, "Xeno: %.1f%%")
        add(LangKeys.RBMK_SCREEN_ROD_EXTRACTION, "Controllo: %.1f%%")
        add(LangKeys.RBMK_SCREEN_TEMPERATURE, "Temp: %.1f°C")
        add(LangKeys.RBMK_SCREEN_TYPE_COLUMN_TEMPERATURE, "Controllare la temperatura media della colonna")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_DEPLETION, "Controllare l'impoverimento medio del carburante")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_POISON, "Controllare l'avvelenamento da xeno")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_TEMPERATURE, "Controllare la temperatura media del carburante")
        add(LangKeys.RBMK_SCREEN_TYPE_NONE, "Spento")
        add(LangKeys.RBMK_SCREEN_TYPE_ROD_EXTRACTION, "Controllare l'estrazione media delle barre di controllo")

        add(LangKeys.SIREN_TRACK_LOOP, "Tipo: Ciclo continuo")
        add(LangKeys.SIREN_TRACK_ONCE, "Tipo: Suona una volta")
        add(LangKeys.SIREN_TRACK_RANGE, "Distanza: %s Metri")
        add(LangKeys.SIREN_TRACK_SIREN_TRACK, "Traccia della Sirena")

        add(LangKeys.UPGRADE_INFO_ACCEPTED_UPGRADES, "Potenziamenti Accettati:")
        add(LangKeys.UPGRADE_INFO_BURN_GAS, "Bruciare %smB di gas per %s")
        add(LangKeys.UPGRADE_INFO_CONSUMPTION, "Consumo: %s")
        add(LangKeys.UPGRADE_INFO_DELAY, "Ritardo: %s")
        add(LangKeys.UPGRADE_INFO_STACKS_TO, "Pile a Livello %s")
        add(LangKeys.UPGRADE_NAME_AFTER_BURNER, "Postbruciatore")
        add(LangKeys.UPGRADE_NAME_OVERDRIVE, "Overdrive")
        add(LangKeys.UPGRADE_NAME_POWER_SAVING, "Salva Energia")
        add(LangKeys.UPGRADE_NAME_SPEED, "Velocità")
        add(LangKeys.UPGRADE_WARN_INCOMPATIBLE, "Questo potenziamento non è compatibile!")
        add(LangKeys.UPGRADE_WARN_MACHINE_NOT_UPGRADEABLE, "Questa macchine non è potenziabile!")
        add(LangKeys.UPGRADE_WARN_NOT_A_MACHINE, "Questa non è una macchina!")
        add(LangKeys.UPGRADE_WARN_VIEW_MACHINE, "Vedi su una macchina per informazioni sugli effetti")
        add(LangKeys.UPGRADE_WARN_UNKNOWN_COMPATIBILITY, "La compatibilità della macchina è sconosciuta")

        add(LangKeys.VOLCANO_EXTINGUISHING, "SI ESTINGUE")
        add(LangKeys.VOLCANO_GROWING, "CRESCE")
        add(LangKeys.VOLCANO_NOT_EXTINGUISHING, "NON SI ESTINGUE")
        add(LangKeys.VOLCANO_NOT_GROWING, "NON CRESCE")
        add(LangKeys.VOLCANO_SMOLDERING, "VULCANO A SCUDO")

        add(LangKeys.WORD_SECONDS, "Secondi")
    }

    private fun addMaterials() = with(Materials) {
        addMaterial(coal, "Carbone")
        addMaterial(iron, "Ferro")
        addMaterial(copper, "Rame")
        addMaterial(gold, "Oro")
        addMaterial(redstone, "Pietra rossa")
        addMaterial(emerald, "Smeraldo")
        addMaterial(lazuli, "Lapislazzuli")
        addMaterial(diamond, "Diamante")

        addMaterial(actinium227, "Attinio-227")
        addMaterial(advancedAlloy, "Lega Avanzata")
        addMaterial(aluminium, "Alluminio")
        addMaterial(americium241, "Americio-241")
        addMaterial(americium242, "Americio-242")
        addMaterial(americiumFuel, "Americio Fuel")
        addMaterial(arsenic, "Arsenico")
        addMaterial(asbestos, "Amianto")
        addMaterial(australium, "Australium")
        addMaterial(bakelite, "Bakelite")
        addMaterial(beryllium, "Berillio")
        addMaterial(bismuth, "Bismuto")
        addMaterial(boron, "Boro")
        addMaterial(cobalt, "Cobalto")
        addMaterial(cobalt60, "Cobalto-60")
        addMaterial(combineSteel, "Acciaio Combinato")
        addMaterial(daffergon, "Daffergon")
        addMaterial(desh, "Desh")
        addMaterial(dineutronium, "Dineutronium")
        addMaterial(electronium, "Electronium")
        addMaterial(euphemium, "Euphemium")
        addMaterial(ferricSchrabidate, "Schrabidate Ferrica")
        addMaterial(fiberglass, "Fibra di Vetro")
        addMaterial(fluorite, "Fluorite")
        addMaterial(ghiorsium336, "Ghiorsio-336")
        addMaterial(gold198, "Oro-198")
        addMaterial(graphite, "Grafite")
        addMaterial(hesFuel, "Carburante di Schrabidio Altamente Arricchito")
        addMaterial(highSpeedSteel, "Acciaio ad Alta VeloctiàHigh-Speed Steel")
        addMaterial(insulator, "Isolante")
        addMaterial(lanthanum, "Lantanio")
        addMaterial(lead, "Piombo")
        addMaterial(lead209, "Piombo-209")
        addMaterial(lesFuel, "Carburante di Schrabidio Lievemente Arricchito")
        addMaterial(lignite, "Lignite")
        addMaterial(lithium, "Litio")
        addMaterial(magnetizedTungsten, "Tungsteno Magnetizzato")
        addMaterial(moxFuel, "Carburante MOX")
        addMaterial(naturalPlutonium, "Plutonio")
        addMaterial(naturalUranium, "Uranio")
        addMaterial(neptunium, "Nettunio")
        addMaterial(neptuniumFuel, "Carburante di Nettunio")
        addMaterial(niobium, "Niobio")
        addMaterial(niter, "Nitrati")
        addMaterial(nuclearWaste, "Scarti Nucleari")
        addMaterial(osmiridium, "Osmiridio")
        addMaterial(plutonium238, "Plutonio-238")
        addMaterial(plutonium239, "Plutonio-239")
        addMaterial(plutonium240, "Plutonio-240")
        addMaterial(plutonium241, "Plutonio-241")
        addMaterial(plutoniumFuel, "Carburante di Plutonio")
        addMaterial(polonium, "Polonio")
        addMaterial(polymer, "Polimero")
        addMaterial(radium226, "Radio-226")
        addMaterial(reactorGradeAmericium, "Reattore di Grado Americio")
        addMaterial(reactorGradePlutonium, "Reattore di Grado Plutonio")
        addMaterial(redCopper, "Rame Rosso")
        addMaterial(redPhosphorus, "Fosforo Rosso")
        addMaterial(reiium, "Reiium")
        addMaterial(rubber, "Gomma")
        addMaterial(saturnite, "Saturnite")
        addMaterial(schrabidium, "Schrabidio")
        addMaterial(schrabidiumFuel, "Carburante di Schrabidio")
        addMaterial(schraranium, "Schraranio")
        addMaterial(solinium, "Solinio")
        addMaterial(starmetal, "Metallo stellare")
        addMaterial(steel, "Acciaio")
        addMaterial(strontium90, "Stronzio-90")
        addMaterial(sulfur, "Zolfo")
        addMaterial(tantalium, "Tantalio")
        addMaterial(technetium99, "Tecnezio-99")
        addMaterial(technetiumSteel, "Acciaio di Tecnezio")
        addMaterial(thorium, "Torio-232")
        addMaterial(thoriumFuel, "Carburante di Torio")
        addMaterial(titanium, "Titanio")
        addMaterial(trinitite, "Trinitite")
        addMaterial(tungsten, "Tungsteno")
        addMaterial(unobtainium, "Unobtainium")
        addMaterial(uranium233, "Uranio-233")
        addMaterial(uranium235, "Uranio-235")
        addMaterial(uranium238, "Uranio-238")
        addMaterial(uraniumFuel, "Carburante di Uranio")
        addMaterial(verticium, "Verticio")
        addMaterial(weidanium, "Weidanio")
        addMaterial(whitePhosphorus, "Fosforo Bianco")
        addMaterial(yellowcake, "Torta gialla")
    }

    override val spawnEggSuffix = "Spawner"

    override val oreFormat = "Minerale di %s"
    override val deepOreFormat = "Minerale di %s in Ardesia Profonda"
    override val blockFormat = "Blocco di %s"
    override val rawFormat = "%s grezzo"
    override val ingotFormat = "Lingotto di %s"
    override val nuggetFormat = "Pepita di %s"
    override val crystalsFormat = "Cristallo di %s"
    override val powderFormat = "Polvere di %s"
    override val plateFormat = "Lastra di %s"
    override val wireFormat = "Cavo di %s"
}
