package at.martinthedragon.nucleartech.datagen.localisation

import at.martinthedragon.nucleartech.CreativeTabs
import at.martinthedragon.nucleartech.LangKeys
import at.martinthedragon.nucleartech.Materials
import at.martinthedragon.nucleartech.TranslationKey
import at.martinthedragon.nucleartech.block.NTechBlocks
import at.martinthedragon.nucleartech.datagen.NuclearLanguageProviders
import at.martinthedragon.nucleartech.entity.EntityTypes
import at.martinthedragon.nucleartech.entity.attribute.Attributes
import at.martinthedragon.nucleartech.fluid.NTechFluids
import at.martinthedragon.nucleartech.fluid.trait.NTechFluidTraits
import at.martinthedragon.nucleartech.item.NTechItems
import at.martinthedragon.nucleartech.menu.MenuTypes
import at.martinthedragon.nucleartech.world.DamageSources
import net.minecraft.data.DataGenerator

class KoKrLanguageProvider(dataGenerator: DataGenerator) : NuclearLanguageProvider(dataGenerator, NuclearLanguageProviders.KO_KR) {
    override fun translate() {
        addCreativeTab(CreativeTabs.Parts, "NTM 자원과 부품들")
        addCreativeTab(CreativeTabs.Items, "NTM 기계 아이템과 연료")
        addCreativeTab(CreativeTabs.Templates, "NTM 설계도")
        addCreativeTab(CreativeTabs.Blocks, "NTM 광물과 블럭들")
        addCreativeTab(CreativeTabs.Machines, "NTM 기계들")
        addCreativeTab(CreativeTabs.Bombs, "NTM 폭탄들")
        addCreativeTab(CreativeTabs.Rocketry, "NTM 미사일과 위성들")
        addCreativeTab(CreativeTabs.Consumables, "NTM 소모품과 장비들")
        addCreativeTab(CreativeTabs.Miscellaneous, "NTM 기타 아이템들")

        addMaterials()

        addBlock(NTechBlocks.scorchedUraniumOre, "불탄 우라늄 광석")
        addBlock(NTechBlocks.thoriumOre, "토륨 광석")
        addBlock(NTechBlocks.oilDeposit, "원유 매장지")
        addBlockDesc(NTechBlocks.oilDeposit, "그건 채굴하면 안 되는데요.\n자, 가서 유정탑이나 만들어 오세요.")
        addBlock(NTechBlocks.emptyOilDeposit, "빈 원유 매장지")
        addBlock(NTechBlocks.oilSand, "오일샌드")
        addBlock(NTechBlocks.australianOre, "오스트레일리안 광석")
        addBlockDesc(NTechBlocks.australianOre, "오스트레일륨 광석")
        addBlock(NTechBlocks.weidite, "웨이다이트")
        addBlockDesc(NTechBlocks.weidite, "웨이다늄 광석")
        addBlock(NTechBlocks.reiite, "레이아이트")
        addBlockDesc(NTechBlocks.reiite, "레이움 광석")
        addBlock(NTechBlocks.brightblendeOre, "브라이트블렌드 광석")
        addBlockDesc(NTechBlocks.brightblendeOre, "언옵테이늄 광석")
        addBlock(NTechBlocks.dellite, "델라이트")
        addBlockDesc(NTechBlocks.dellite, "다퍼곤 광석")
        addBlock(NTechBlocks.dollarGreenMineral, "달러 그린 미네랄")
        addBlockDesc(NTechBlocks.dollarGreenMineral, "버티슘 광석")
        addBlock(NTechBlocks.rareEarthOre, "희토류 광석")
        addBlock(NTechBlocks.netherUraniumOre, "네더 우라늄 광석")
        addBlock(NTechBlocks.scorchedNetherUraniumOre, "불탄 네더 우라늄 광석")
        addBlock(NTechBlocks.netherPlutoniumOre, "네더 플루토늄 광석")
        addBlock(NTechBlocks.netherTungstenOre, "네더 텅스텐 광석")
        addBlock(NTechBlocks.netherSulfurOre, "네더 황 광석")
        addBlock(NTechBlocks.netherPhosphorusOre, "네더 인 광석")
        addBlock(NTechBlocks.netherSchrabidiumOre, "네더 스크라비듐 광석")
        addBlock(NTechBlocks.meteorUraniumOre, "운석 우라늄 광석")
        addBlock(NTechBlocks.meteorThoriumOre, "운석 토륨 광석")
        addBlock(NTechBlocks.meteorTitaniumOre, "운석 티타늄 광석")
        addBlock(NTechBlocks.meteorSulfurOre, "운석 황 광석")
        addBlock(NTechBlocks.meteorCopperOre, "운석 구리 광석")
        addBlock(NTechBlocks.meteorTungstenOre, "운석 텅스텐 광석")
        addBlock(NTechBlocks.meteorAluminiumOre, "운석 알루미늄 광석")
        addBlock(NTechBlocks.meteorLeadOre, "운석 납 광석")
        addBlock(NTechBlocks.meteorLithiumOre, "운석 리튬 광석")
        addBlock(NTechBlocks.starmetalOre, "스타메탈 광석")
        addBlock(NTechBlocks.trixite, "트라이사이트 ")
        addBlock(NTechBlocks.basaltSulfurOre, "황이 풍부한 현무암")
        addBlock(NTechBlocks.basaltFluoriteOre, "형석이 풍부한 현무암")
        addBlock(NTechBlocks.basaltAsbestosOre, "석면이 풍부한 현무암")
        addBlock(NTechBlocks.basaltVolcanicGemOre, "보석이 풍부한 현무암")

        addBlock(NTechBlocks.scorchedDeepslateUraniumOre, "불탄 심층암 우라늄 광석")
        addBlock(NTechBlocks.deepslateOilDeposit, "심층암 원유 매장지")
        addBlockDesc(NTechBlocks.deepslateOilDeposit, "이렇게 깊이까지 파들어오고도\n뭘 어떻게 해야 할지 모른다고? 어떻게?!")
        addBlock(NTechBlocks.emptyDeepslateOilDeposit, "빈 심층암 원유 매장지")
        addBlock(NTechBlocks.deepslateAustralianOre, "심층암 오스트레일리안 광석")
        addBlockDesc(NTechBlocks.deepslateAustralianOre, "오스트레일륨 광석")
        addBlock(NTechBlocks.deepslateRareEarthOre, "심층암 희토류 광석")

        addBlock(NTechBlocks.whitePhosphorusBlock, "백린 블록")
        addBlock(NTechBlocks.redPhosphorusBlock, "적린 블록")
        addBlock(NTechBlocks.yellowcakeBlock, "우라늄정광 블록")
        addBlock(NTechBlocks.scrapBlock, "폐기물 블록")
        addBlock(NTechBlocks.electricalScrapBlock, "전자 폐기물 블록")
        addBlock(NTechBlocks.insulatorRoll, "절연체 말이")
        addBlock(NTechBlocks.fiberglassRoll, "유리섬유 말이")
        addBlock(NTechBlocks.trinititeBlock, "트리니타이트 블록")
        addBlock(NTechBlocks.nuclearWasteBlock, "핵 폐기물 블록")
        addBlock(NTechBlocks.schrabidiumCluster, "스크라비듐 덩어리 블록")
        addBlock(NTechBlocks.euphemiumEtchedSchrabidiumCluster, "유페뮴이 새겨진 스크라비듐 덩어리 블록")
        addBlock(NTechBlocks.deshReinforcedBlock, "강화된 데쉬 블록")

        addBlock(NTechBlocks.titaniumDecoBlock, "티타늄 장식 블록")
        addBlock(NTechBlocks.redCopperDecoBlock, "붉은 구리 장식 블록")
        addBlock(NTechBlocks.tungstenDecoBlock, "텅스텐 장식 블록")
        addBlock(NTechBlocks.aluminiumDecoBlock, "알루미늄 장식 블록")
        addBlock(NTechBlocks.steelDecoBlock, "강철 장식 블록")
        addBlock(NTechBlocks.leadDecoBlock, "납 장식 블록")
        addBlock(NTechBlocks.berylliumDecoBlock, "베릴륨 장식 블록")
        addBlock(NTechBlocks.asbestosRoof, "석면 지붕")
        addBlock(NTechBlocks.hazmatBlock, "방호 블록")
        addBlock(NTechBlocks.meteorite, "운석")
        addBlock(NTechBlocks.meteoriteCobblestone, "운석 조약돌")
        addBlock(NTechBlocks.brokenMeteorite, "부서진 운석")
        addBlock(NTechBlocks.hotMeteoriteCobblestone, "뜨거운 운석 조약돌")
        addBlock(NTechBlocks.meteoriteTreasure, "운석 보물")
        addBlock(NTechBlocks.steelBeam, "강철 빔")
        addBlock(NTechBlocks.steelScaffold, "강철 비계")
        addBlock(NTechBlocks.steelGrate, "강철 상자")

        addBlock(NTechBlocks.glowingMushroom, "빛나는 버섯")
        addBlock(NTechBlocks.glowingMushroomBlock, "빛나는 버섯 블록")
        addBlock(NTechBlocks.glowingMushroomStem, "빛나는 버섯 줄기")
        addBlock(NTechBlocks.deadGrass, "죽은 잔디")
        addBlock(NTechBlocks.glowingMycelium, "빛나는 균사체")
        addBlock(NTechBlocks.trinitite, "트리니타이트 광석")
        addBlock(NTechBlocks.redTrinitite, "붉은 트리니타이트 광석")
        addBlock(NTechBlocks.charredLog, "탄화된 나무")
        addBlock(NTechBlocks.charredPlanks, "탄화된 나무판자")

        addBlock(NTechBlocks.slakedSellafite, "식은 셀라파이트")
        addBlock(NTechBlocks.sellafite, "셀라파이트")
        addBlock(NTechBlocks.hotSellafite, "뜨거운 셀라파이트")
        addBlock(NTechBlocks.boilingSellafite, "끓는 셀라파이트")
        addBlock(NTechBlocks.blazingSellafite, "녹아내리는 셀라파이트")
        addBlock(NTechBlocks.infernalSellafite, "불타는 셀라파이트")
        addBlock(NTechBlocks.sellafiteCorium, "셀라파이트-용융물")

        addBlock(NTechBlocks.corium, "노심용융물")
        addBlock(NTechBlocks.corebblestone, "노심용융물 조약돌")

        addBlock(NTechBlocks.siren, "사이렌")
        addBlock(NTechBlocks.safe, "금고")
        addBlock(NTechBlocks.steamPressBase, "증기 압착기")
        addBlock(NTechBlocks.steamPressFrame, "증기 압착기")
        addBlock(NTechBlocks.steamPressTop, "증기 압착기")
        addBlock(NTechBlocks.blastFurnace, "용광로")
        addBlock(NTechBlocks.combustionGenerator, "연소 발전기")
        addBlock(NTechBlocks.electricFurnace, "전기로")
        addBlock(NTechBlocks.shredder, "분쇄기")
        addBlock(NTechBlocks.assembler, "조립기")
        addBlock(NTechBlocks.chemPlant, "화학 공장")
        addBlock(NTechBlocks.turbine, "증기 터빈")
        addBlock(NTechBlocks.smallCoolingTower, "외부 냉각탑")
        addBlock(NTechBlocks.largeCoolingTower, "냉각탑")
        addBlockDesc(NTechBlocks.turbine, "효율: 85%")
        addBlock(NTechBlocks.oilDerrick, "정유탑")
        addBlock(NTechBlocks.pumpjack, "펌프잭")
        addBlockDesc11(NTechBlocks.pumpjack, "ㄹㅇ 모기")
        addBlock(NTechBlocks.centrifuge, "원심분리기")
        addBlock(NTechBlocks.ironAnvil, "철 모루")
        addBlock(NTechBlocks.leadAnvil, "납 모루")
        addBlock(NTechBlocks.steelAnvil, "강철 모루")
        addBlock(NTechBlocks.meteoriteAnvil, "운석 모루")
        addBlock(NTechBlocks.starmetalAnvil, "스타메탈 모루")
        addBlock(NTechBlocks.ferrouraniumAnvil, "우라늄철합금 모루")
        addBlock(NTechBlocks.bismuthAnvil, "비스무트 모루")
        addBlock(NTechBlocks.schrabidateAnvil, "철-스크라비듐 모루")
        addBlock(NTechBlocks.dineutroniumAnvil, "다이뉴트론 모루")
        addBlock(NTechBlocks.murkyAnvil, "흐린 모루")

        addBlock(NTechBlocks.decoRbmkBlock, "RBMK 장식 블록")
        addBlock(NTechBlocks.decoRbmkSmoothBlock, "부드러운 RBMK 장식 블록")

        addBlock(NTechBlocks.rbmkColumn, "RBMK Column Part")
        addBlock(NTechBlocks.rbmkRod, "RBMK 연료봉")
        addBlock(NTechBlocks.rbmkModeratedRod, "RBMK 감속 연료봉")
        addBlock(NTechBlocks.rbmkReaSimRod, "RBMK 연료봉 (ReaSim)")
        addBlock(NTechBlocks.rbmkModeratedReaSimRod, "RBMK 감속 연료봉 (ReaSim)")
        addBlock(NTechBlocks.rbmkReflector, "RBMK 텅스텐 카바이드 중성자 반사체")
        addBlock(NTechBlocks.rbmkModerator, "RBMK 흑연 감속재")
        addBlock(NTechBlocks.rbmkAbsorber, "RBMK 붕소 중성자 흡수재")
        addBlock(NTechBlocks.rbmkBoilerColumn, "RBMK 증기 채널 부품")
        addBlock(NTechBlocks.rbmkBoiler, "RBMK 증기 채널")
        addBlock(NTechBlocks.rbmkBlank, "RBMK 구조물 기중")
        addBlock(NTechBlocks.rbmkManualControlRod, "RBMK 제어봉")
        addBlock(NTechBlocks.rbmkModeratedControlRod, "RBMK 감속 제어봉")
        addBlock(NTechBlocks.rbmkAutoControlRod, "RBMK 자동 제어봉")
        addBlock(NTechBlocks.rbmkSteamConnector, "RBMK 증기 연결기")
        addBlock(NTechBlocks.rbmkInlet, "RBMK ReaSim 급수구")
        addBlock(NTechBlocks.rbmkOutlet, "RBMK ReaSim 증기 배출구")
        addBlock(NTechBlocks.rbmkConsole, "RBMK 제어기")
        addBlock(NTechBlocks.rbmkDebris, "RBMK 파편")
        addBlock(NTechBlocks.rbmkBurningDebris, "불타는 RBMK 파편")
        addBlock(NTechBlocks.rbmkRadioactiveDebris, "연기나는 RBMK 파편")

        addBlock(NTechBlocks.coatedCable, "코팅된 붉은 구리 케이블")
        addBlock(NTechBlocks.coatedUniversalFluidDuct, "코팅된 범용 유체 파이프")

        addBlock(NTechBlocks.littleBoy, "리틀 보이")
        addBlock(NTechBlocks.fatMan, "팻 맨")
        addBlock(NTechBlocks.volcanoCore, "화산 핵")

        addBlock(NTechBlocks.launchPad, "미사일 발사대")
        addBlock(NTechBlocks.launchPadPart, "미사일 발사대")

        addBlock(NTechBlocks.genericMultiBlockPart, "멀티블록 구조물 부품")
        addBlock(NTechBlocks.genericMultiBlockPort, "멀티블록 구조물 포트")
        addBlock(NTechBlocks.oilPipe, "기름 파이프")

        addBlock(NTechFluids.spentSteam.block, "저압 증기")
        addBlock(NTechFluids.steam.block, "증기")
        addBlock(NTechFluids.steamHot.block, "고압 증기")
        addBlock(NTechFluids.steamSuperHot.block, "초고압 증기")
        addBlock(NTechFluids.steamUltraHot.block, "극초고압 증기")
        addBlock(NTechFluids.oil.block, "원유")
        addBlock(NTechFluids.gas.block, "천연가스")
        addBlock(NTechFluids.uraniumHexafluoride.block, "육불화우라늄")
        addBlock(NTechFluids.corium.block, "노심용융물")
        addBlock(NTechFluids.volcanicLava.block, "화산 용암")

        addItem(NTechItems.rawThorium, "토륨 원석")
        addItem(NTechItems.rawRareEarth, "희토류 원석")
        addItem(NTechItems.rawTrixite, "트라이사이트 원석")

        addItemDesc(NTechItems.neptuniumIngot, "내가 좋아하는 것 중 하나잖아!")
        addItemDesc(NTechItems.tantaliumIngot, "'탄탈럼'")
        addItemDesc(NTechItems.tantaliumNugget, "'탄탈럼'")
        addItemDesc(NTechItems.schraraniumIngot, "스크라비듐 변환기에서 우라늄으로 만듭니다.")
        addItemDesc(NTechItems.combineSteelIngot, "*대충 시민 보호 기동대 패러디*")
        addItemDesc(NTechItems.ghiorsium336Ingot, "시보귬의 동지.")
        addItemDesc(NTechItems.ghiorsium336Nugget, "시보귬의 동지.")
        addItem(NTechItems.lanthanumIngot, "반쯤 안정적인 란타넘 주괴")
        addItemDesc(NTechItems.euphemiumIngot, "정말 특별하고도 이상한 물질")
        addItem(NTechItems.whitePhosphorusIngot, "백린 막대")

        addItem(NTechItems.semtexBar, "셈텍스 막대")
        addItemDesc(
            NTechItems.semtexBar,
            "셈텍스 H 플라스틱 폭발물\n" +
                    "사용처가 많은 성능 좋은 폭발물.\n" +
                    "식용 가능"
        )

        addItem(NTechItems.lithiumCube, "리튬 큐브")
        addItem(NTechItems.solidFuelCube, "고체 연료 큐브")
        addItem(NTechItems.solidRocketFuelCube, "고체 로켓 연료 큐브")

        addItem(NTechItems.fiberglassSheet, "유리섬유 판")
        addItemDesc(NTechItems.fiberglassSheet, "섬유 많이, 유리 많이. 몸에 필요한 건 다 있어요.")
        addItem(NTechItems.asbestosSheet, "석면 판")
        addItemDesc(NTechItems.asbestosSheet, "§o„생명, 자괴감, 석면으로 가득 차있어요. 산소도 같이 드립니다.“")

        addItem(NTechItems.lesserAustraliumBillet, "작은 오스트레일륨 동전")
        addItem(NTechItems.greaterAustraliumBillet, "큰 오스트레일륨 동전")
        addItem(NTechItems.po210BeBillet, "Po210Be 동전")
        addItem(NTechItems.ra226BeBillet, "Ra226Be 동전")
        addItem(NTechItems.pu238BeBillet, "Pu238Be 동전")
        addItem(NTechItems.zirconiumBillet, "지르코늄 동전")
        addItem(NTechItems.bismuthZfbBillet, "비스무트 ZFB 동전")
        addItem(NTechItems.pu241ZfbBillet, "플루토늄-241 ZFB 동전")
        addItem(NTechItems.reactorGradeAmericiumZfbBillet, "원자로급 아메리슘 ZFB 동전")
        addItem(NTechItems.yharoniteBillet, "야로나이트 동전")
        addItem(NTechItems.flashgoldBillet, "플래시골드 동전")
        addItem(NTechItems.flashleadBillet, "플래시리드 동전")
        addItemDesc(NTechItems.flashleadBillet, "격자가 붕괴하면서, 쌍소멸 반응을 일으킵니다.\n이로 인해 피온이 방출되고,\n그 피온은 뮤온으로 붕괴하여, 원자핵의 융합을 촉진합으로써\n새 물질을 만들어냅니다.\n이해해 보세요.")

        addItem(NTechItems.mercuryDroplet, "수은 방울")
        addItem(NTechItems.mercuryBottle, "수은 병")

        addItem(NTechItems.coke, "코크스")
        addItem(NTechItems.lignite, "갈탄")
        addItem(NTechItems.ligniteBriquette, "갈탄 조개탄")

        addItem(NTechItems.sulfur, "황")
        addItem(NTechItems.niter, "초석")
        addItem(NTechItems.fluorite, "형석")
        addItem(NTechItems.quartzPowder, "석영 가루")
        addItem(NTechItems.yellowcake, "우라늄정광")
        addItem(NTechItems.chlorophytePowder, "녹조류 가루")
        addItem(NTechItems.neodymiumPowder, "네오디뮴 가루")
        addItem(NTechItems.niobiumPowder, "나이오븀 가루")
        addItem(NTechItems.ceriumPowder, "세륨 가루")
        addItemDesc(NTechItems.asbestosPowder, "§o„스으으으읍 - 으흐으으음...“")
        addItem(NTechItems.enchantmentPowder, "마법 가루")
        addItem(NTechItems.cloudResidue, "Cloud Residue")
        addItem(NTechItems.thermonuclearAshes, "열핵 재")
        addItem(NTechItems.semtexMix, "셈텍스 혼합물")
        addItem(NTechItems.deshMix, "데쉬 혼합물")
        addItem(NTechItems.deshReadyMix, "데쉬레디™ 혼합물")
        addItem(NTechItems.nitaniumMix, "니타늄 혼합물")
        addItem(NTechItems.sparkMix, "스파크 혼합물")
        addItem(NTechItems.meteoritePowder, "운석 가루")
        addItemDesc(NTechItems.euphemiumPowder, "분쇄된 분홍색 가루.\n딸기맛이 납니다.")
        addItem(NTechItems.desaturatedRedstone, "탈포화 레드스톤")
        addItem(NTechItems.dust, "먼지")
        addItemDesc(NTechItems.dust, "난 먼지가 싫어!")
        addItem(NTechItems.tinyLithiumPowder, "작은 리튬 가루")
        addItem(NTechItems.tinyNeodymiumPowder, "작은 네오디뮴 가루")
        addItem(NTechItems.tinyCobaltPowder, "작은 코발트 가루")
        addItem(NTechItems.tinyNiobiumPowder, "작은 나이오븀 가루")
        addItem(NTechItems.tinyCeriumPowder, "작은 세륨 가루")
        addItem(NTechItems.tinyLanthanumPowder, "작은 란타넘 가루")
        addItem(NTechItems.tinyActiniumPowder, "작은 악티늄 가루")
        addItem(NTechItems.tinyMeteoritePowder, "작은 운석 가루")
        addItem(NTechItems.redPhosphorus, "적린")
        addItemDesc(NTechItems.redPhosphorus, "다용도 폭탄에서 사용됩니다:\n소이폭탄은 재밌어!")
        addItem(NTechItems.cryoPowder, "냉매 가루")
        addItem(NTechItems.poisonPowder, "독 가루")
        addItemDesc(NTechItems.poisonPowder, "다용도 폭탄에서 사용됩니다:\n경고: 독극물!")
        addItem(NTechItems.thermite, "테르밋")
        addItem(NTechItems.energyPowder, "에너지 가루")

        addItem(NTechItems.cordite, "코다이트")
        addItem(NTechItems.ballistite, "발리스타이트")

        addItem(NTechItems.rareEarthCrystals, "희토류 결정")
        addItem(NTechItems.redPhosphorusCrystals, "적린 결정")
        addItem(NTechItems.trixiteCrystals, "트라이사이트 결정")

        addItem(NTechItems.volcanicGem, "화산 보석")

        addItem(NTechItems.neodymiumFragment, "네오디뮴 파편")
        addItem(NTechItems.cobaltFragment, "코발트 파편")
        addItem(NTechItems.niobiumFragment, "나이오븀 파편")
        addItem(NTechItems.ceriumFragment, "세륨 파편")
        addItem(NTechItems.lanthanumFragment, "란타넘 파편")
        addItem(NTechItems.actiniumFragment, "악티늄 파편")
        addItem(NTechItems.meteoriteFragment, "운석 파편")

        addItem(NTechItems.biomass, "바이오매스")
        addItem(NTechItems.compressedBiomass, "압축 바이오매스")

        addItemDesc(
            NTechItems.euphemiumNugget,
            "작은 분홍색 금속 조각.\n" +
                    "성질은 아직 불명입니다,\n" +
                    "조심히 다뤄 줘요."
        )

        addItem(NTechItems.neutronReflector, "중성자 반사체")
        addItem(NTechItems.mixedPlate, "혼합 판")
        addItem(NTechItems.paAAlloyPlate, "PaA 합금 판")
        addItem(NTechItems.insulator, "절연체")
        addItem(NTechItems.kevlarCeramicCompound, "케블라-세라믹 화합물")
        addItem(NTechItems.dalekaniumPlate, "화난 금속")
        addItem(NTechItems.deshCompoundPlate, "데쉬 화합물 판")
        addItem(NTechItems.euphemiumCompoundPlate, "유페뮴 화합물 판")
        addItem(NTechItems.dineutroniumCompoundPlate, "다이뉴트로늄 화합물 판")
        addItem(NTechItems.copperPanel, "구리 판")

        addItem(NTechItems.highSpeedSteelBolt, "고속 강철 볼트")
        addItem(NTechItems.tungstenBolt, "텅스텐 볼트")
        addItem(NTechItems.reinforcedTurbineShaft, "강화된 터빈 축")

        addItem(NTechItems.hazmatCloth, "방호 천")
        addItem(NTechItems.advancedHazmatCloth, "고급 방호 천")
        addItem(NTechItems.leadReinforcedHazmatCloth, "납-강화된 방호 천")
        addItem(NTechItems.fireProximityCloth, "방화 천")
        addItem(NTechItems.activatedCarbonFilter, "활성탄 필터")

        addItem(NTechItems.superConductor, "초전도체")
        addItem(NTechItems.highTemperatureSuperConductor, "4000K 고온 초전도체")

        addItem(NTechItems.copperCoil, "구리 코일")
        addItem(NTechItems.ringCoil, "링 코일")
        addItem(NTechItems.superConductingCoil, "초전도 코일")
        addItem(NTechItems.superConductingRingCoil, "초전도 링 코일")
        addItem(NTechItems.goldCoil, "금 코일")
        addItem(NTechItems.goldRingCoil, "금 링 코일")
        addItem(NTechItems.heatingCoil, "가열 코일")
        addItem(NTechItems.highTemperatureSuperConductingCoil, "4000K 고온 초전도 코일")

        addItem(NTechItems.steelTank, "강철 탱크")
        addItem(NTechItems.motor, "모터")
        addItem(NTechItems.centrifugeElement, "원심분리기 부품")
        addItem(NTechItems.centrifugeTower, "원심분리기 탑")
        addItem(NTechItems.deeMagnets, "D형 자석")
        addItem(NTechItems.flatMagnet, "판형 자석")
        addItem(NTechItems.cyclotronTower, "사이클로트론 탑")
        addItem(NTechItems.breedingReactorCore, "증식로 핵")
        addItem(NTechItems.rtgUnit, "RTG 유닛")
        addItem(NTechItems.thermalDistributionUnit, "열 분배 장치")
        addItem(NTechItems.endothermicDistributionUnit, "흡열 분배 장치")
        addItem(NTechItems.exothermicDistributionUnit, "방열 분배 장치")
        addItem(NTechItems.gravityManipulator, "중력 조작기")
        addItem(NTechItems.steelPipes, "강철 관")
        addItem(NTechItems.titaniumDrill, "티타늄 드릴")
        addItem(NTechItems.photovoltaicPanel, "광전 패널")
        addItem(NTechItems.chlorinePinwheel, "염소 핀휠")
        addItem(NTechItems.telepad, "텔레패드")
        addItem(NTechItems.entanglementKit, "얽힘 키트")
        addItemDesc(
            NTechItems.entanglementKit,
            "텔레포터 제작용 아이템입니다.\n" +
                    "베릴륨으로 강화된 자원 스캐너를 이용해\n" +
                    "차원 이동을 가능케 합니다."
        )
        addItem(NTechItems.stabilizerComponent, "안정기 부품")
        addItem(NTechItems.emitterComponent, "방출기 부품")
        addItem(NTechItems.aluminiumCap, "알루미늄 뚜껑")
        addItem(NTechItems.smallSteelShell, "작은 강철 외피")
        addItem(NTechItems.smallAluminiumShell, "작은 알루미늄 외피")
        addItem(NTechItems.bigSteelShell, "큰 강철 외피")
        addItem(NTechItems.bigAluminiumShell, "큰 알루미늄 외피")
        addItem(NTechItems.bigTitaniumShell, "큰 티타늄 외피")
        addItem(NTechItems.flatSteelCasing, "평평한 강철 케이싱")
        addItem(NTechItems.smallSteelGridFins, "작은 강철 그리드 핀")
        addItem(NTechItems.bigSteelGridFins, "큰 강철 그리드 핀")
        addItem(NTechItems.largeSteelFins, "작은 강철 핀")
        addItem(NTechItems.smallTitaniumFins, "작은 티타늄 핀")
        addItem(NTechItems.steelSphere, "강철 구")
        addItem(NTechItems.steelPedestal, "강철 받힘대")
        addItem(NTechItems.dysfunctionalNuclearReactor, "고장난 원자로")
        addItem(NTechItems.largeSteelRotor, "큰 강철 로터")
        addItem(NTechItems.generatorBody, "발전기 몸체")
        addItem(NTechItems.titaniumBlade, "티타늄 날")
        addItem(NTechItems.tungstenReinforcedBlade, "텅스텐 강화된 날")
        addItem(NTechItems.titaniumSteamTurbine, "티타늄 증기 터빈")
        addItem(NTechItems.reinforcedTurbofanBlades, "강화된 터보팬 날")
        addItem(NTechItems.generatorFront, "발전기 전면부")
        addItem(NTechItems.toothpicks, "이쑤시개")
        addItem(NTechItems.ductTape, "덕트 테이프")
        addItem(NTechItems.clayCatalyst, "점토 촉매")
        addItem(NTechItems.smallMissileAssembly, "작은 미사일 부품")

        addItem(NTechItems.smallWarhead, "소형 탄두")
        addItem(NTechItems.mediumWarhead, "중형 탄두")
        addItem(NTechItems.largeWarhead, "대형 탄두")
        addItem(NTechItems.smallIncendiaryWarhead, "소형 소이탄두")
        addItem(NTechItems.mediumIncendiaryWarhead, "중형 소이탄두")
        addItem(NTechItems.largeIncendiaryWarhead, "대형 소이탄두")
        addItem(NTechItems.smallClusterWarhead, "소형 집속 탄두")
        addItem(NTechItems.mediumClusterWarhead, "중형 집속 탄두")
        addItem(NTechItems.largeClusterWarhead, "대형 집속 탄두")
        addItem(NTechItems.smallBunkerBusterWarhead, "소형 벙커 버스터 탄두")
        addItem(NTechItems.mediumBunkerBusterWarhead, "중형 벙커 버스터 탄두")
        addItem(NTechItems.largeBunkerBusterWarhead, "대형 벙커 버스터 탄두")
        addItem(NTechItems.nuclearWarhead, "핵탄두")
        addItem(NTechItems.thermonuclearWarhead, "열핵탄두")
        addItem(NTechItems.endothermicWarhead, "흡열탄두")
        addItem(NTechItems.exothermicWarhead, "방열탄두")

        addItem(NTechItems.smallFuelTank, "소형 연료 탱크")
        addItem(NTechItems.mediumFuelTank, "중형 연료 탱크")
        addItem(NTechItems.largeFuelTank, "대형 연료 탱크")

        addItem(NTechItems.smallThruster, "소형 추진기")
        addItem(NTechItems.mediumThruster, "중형 추진기")
        addItem(NTechItems.largeThruster, "대형 추진기")
        addItem(NTechItems.lvnNuclearRocketEngine, "LV-N 핵 로켓 엔진")

        addItem(NTechItems.satelliteBase, "인공위성 몸체")
        addItem(NTechItems.highGainOpticalCamera, "고배율 광학 카메라")
        addItem(NTechItems.m700SurveyScanner, "M700 측량 스캐너")
        addItem(NTechItems.radarDish, "레이더 접시")
        addItem(NTechItems.deathRay, "데스레이")
        addItem(NTechItems.xeniumResonator, "제니움 공명기")

        addItem(NTechItems.size10Connector, "10 사이즈 연결기")
        addItem(NTechItems.size15Connector, "15 사이즈 연결기")
        addItem(NTechItems.size20Connector, "20 사이즈 연결기")

        addItem(NTechItems.hunterChopperCockpit, "헌터 헬기 조종석")
        addItem(NTechItems.emplacementGun, "헌터 헬기 기총")
        addItem(NTechItems.hunterChopperBody, "헌터 헬기 몸체")
        addItem(NTechItems.hunterChopperTail, "헌터 헬기 꼬리날개")
        addItem(NTechItems.hunterChopperWing, "헌터 헬기 날개")
        addItem(NTechItems.hunterChopperRotorBlades, "헌터 헬기 로터 날")
        addItem(NTechItems.combineScrapMetal, "콤바인 고철")

        addItem(NTechItems.heavyHammerHead, "중형 망치 머리")
        addItem(NTechItems.heavyAxeHead, "중형 도끼 머리")
        addItem(NTechItems.reinforcedPolymerHandle, "강화된 폴리머 손잡이")

        addItem(NTechItems.basicCircuitAssembly, "기본 회로 부품")
        addItem(NTechItems.basicCircuit, "기본 회로")

        addItem(NTechItems.enhancedCircuit, "향상된 회로")
        addItem(NTechItems.advancedCircuit, "고급 회로")
        addItem(NTechItems.overclockedCircuit, "오버클럭된 회로")
        addItem(NTechItems.highPerformanceCircuit, "고성능 회로")
        addItem(NTechItems.militaryGradeCircuitBoardTier1, "군사 등급 회로판 (티어 1)")
        addItem(NTechItems.militaryGradeCircuitBoardTier2, "군사 등급 회로판 (티어 2)")
        addItem(NTechItems.militaryGradeCircuitBoardTier3, "군사 등급 회로판 (티어 3)")
        addItem(NTechItems.militaryGradeCircuitBoardTier4, "군사 등급 회로판 (티어 4)")
        addItem(NTechItems.militaryGradeCircuitBoardTier5, "군사 등급 회로판 (티어 5)")
        addItem(NTechItems.militaryGradeCircuitBoardTier6, "군사 등급 회로판 (티어 6)")

        addItem(NTechItems.revolverMechanism, "리볼버 부품")
        addItem(NTechItems.advancedRevolverMechanism, "고급 리볼버 부품")
        addItem(NTechItems.rifleMechanism, "소총 부품")
        addItem(NTechItems.advancedRifleMechanism, "고급 소총 부품")
        addItem(NTechItems.launcherMechanism, "발사기 부품")
        addItem(NTechItems.advancedLauncherMechanism, "고급 발사기 부품")
        addItem(NTechItems.highTechWeaponMechanism, "첨단 무기 부품")

        addItem(NTechItems.point357MagnumPrimer, ".357 매그넘 뇌관 (x16)")
        addItem(NTechItems.point44MagnumPrimer, ".44 매그넘 뇌관 (x16)")
        addItem(NTechItems.smallCaliberPrimer, "소구경 뇌관 (x24)")
        addItem(NTechItems.largeCaliberPrimer, "대구경 뇌관 (x8)")
        addItem(NTechItems.buckshotPrimer, "산탄 뇌관 (x8)")

        addItem(NTechItems.point357MagnumCasing, ".357 매그넘 탄피 (x16)")
        addItem(NTechItems.point44MagnumCasing, ".44 매그넘 탄피 (x16)")
        addItem(NTechItems.smallCaliberCasing, "소구경 탄피 (x24)")
        addItem(NTechItems.largeCaliberCasing, "대구경 탄피 (x8)")
        addItem(NTechItems.buckshotCasing, "산탄 탄피 (x8)")

        addItem(NTechItems.ironBulletAssembly, "철 탄약 부품")
        addItem(NTechItems.leadBulletAssembly, "납 탄약 부품")
        addItem(NTechItems.glassBulletAssembly, "유리 탄약 부품")
        addItem(NTechItems.goldBulletAssembly, "금 탄약 부품")
        addItem(NTechItems.schrabidiumBulletAssembly, "스크라비듐 탄약 부품")
        addItem(NTechItems.nightmareBulletAssembly, "나이트메어 탄약 부품")
        addItem(NTechItems.deshBulletAssembly, "데쉬 탄약 부품")
        addItem(NTechItems.point44MagnumAssembly, ".44 매그넘 부품")
        addItem(NTechItems.nineMmAssembly, "9mm 부품")
        addItem(NTechItems.fivePoint56mmAssembly, "5.56mm 부품")
        addItem(NTechItems.point22LRAssembly, ".22 LR 부품")
        addItem(NTechItems.point5mmAssembly, ".5mm 부품")
        addItem(NTechItems.point50AEAssembly, ".50 AE 부품")
        addItem(NTechItems.point50BMGAssembly, ".50 BMG 부품")

        addItem(NTechItems.silverBulletCasing, "은 탄피")
        addItem(NTechItems.twelvePoint8cmStarmetalHighEnergyShell, "12.8cm 스타메탈 고에너지 탄피")
        addItem(NTechItems.twelvePoint8cmNuclearShell, "12.8cm 핵 탄피")
        addItem(NTechItems.twelvePoint8cmDUShell, "12.8cm DU-탄피")

        addItem(NTechItems.cableDrum, "케이블 롤")
        addItemDesc(NTechItems.cableDrum, "전신주를 우클릭해 연결합니다.")
        addItem(NTechItems.paintingOfACartoonPony, "만화 당나귀 그림")
        addItemDesc(NTechItems.paintingOfACartoonPony, "노란 말이 파란 말을 이기는건 증명된 팩트라고!")
        addItem(NTechItems.conspiracyTheory, "음모론")
        addItemDesc(NTechItems.conspiracyTheory, "강철은 항공유를 못 녹여!")
        addItem(NTechItems.politicalTopic, "정치적 주제")
        addItemDesc(NTechItems.politicalTopic, "도널드 덕이 벽을 세울 것이다!")
        addItem(NTechItems.ownOpinion, "내 의견")
        addItemDesc(NTechItems.ownOpinion, "글쎄, 난 맘에 드는데...")

        addItem(NTechItems.explosivePellets, "폭발성 펠릿")
        addItemDesc(NTechItems.explosivePellets, "다용도 폭탄에서 사용됩니다:\n주모 여기 폭발력 추가요!")
        addItem(NTechItems.leadPellets, "납 펠릿")
        addItem(NTechItems.flechettes, "플레셰트")
        addItem(NTechItems.poisonGasCartridge, "독가스 카트리지")
        addItemDesc(NTechItems.poisonGasCartridge, "다용도 폭탄에서 사용됩니다:\n폐에 감각이 없으니.. 이게 어떻게 된 거요?")
        addItem(NTechItems.magnetron, "마그네트론")
        addItem(NTechItems.denseCoalCluster, "밀집 석탄 클러스터")
        addItem(NTechItems.burntBark, "탄 나무껍질")
        addItemDesc(NTechItems.burntBark, "핵폭발에 휩쓸린 참나무에서 떨어저 나온 나무 껍질 조각")
        addItem(NTechItems.machineUpgradeTemplate, "기계 업그레이드 설계도")

        addItem(NTechItems.blankRune, "빈 촉매 격자")
        addItem(NTechItems.isaRune, "차가운 촉매 격자")
        addItem(NTechItems.dagazRune, "균형잡힌 촉매 격자")
        addItem(NTechItems.hagalazRune, "거친 촉매 격자")
        addItem(NTechItems.jeraRune, "곱셈 촉매 격자")
        addItem(NTechItems.thurisazRune, "덧셈 촉매 격자")

        addItem(NTechItems.burnedOutQuadSchrabidiumFuelRod, "열화 4중 스크라비듐 봉")
        addItemDesc(NTechItems.burnedOutQuadSchrabidiumFuelRod, "극미량의 이상한 신물질이 담긴\n열화된 4중 연료봉.")

        addItem(NTechItems.scrap, "폐기물")
        addItem(NTechItems.hotDepletedUraniumFuel, "뜨거운 열화 우라늄 연료")
        addItem(NTechItems.hotDepletedThoriumFuel, "뜨거운 열화 토륨 연료")
        addItem(NTechItems.hotDepletedPlutoniumFuel, "뜨거운 열화 플루토늄 연료")
        addItem(NTechItems.hotDepletedMOXFuel, "뜨거운 열화 혼합 산화물 연료")
        addItem(NTechItems.hotDepletedSchrabidiumFuel, "뜨거운 열화 스크라비듐 연료")
        addItem(NTechItems.depletedUraniumFuel, "열화 우라늄 연료")
        addItem(NTechItems.depletedThoriumFuel, "열화 토륨 연료")
        addItem(NTechItems.depletedPlutoniumFuel, "열화 플루토늄 연료")
        addItem(NTechItems.depletedMOXFuel, "열화 혼합 산화물 연료")
        addItem(NTechItems.depletedSchrabidiumFuel, "열화 스크라비듐 연료")
        addItem(NTechItems.trinitite, "트리니타이트")
        addItem(NTechItems.nuclearWaste, "핵 폐기물")
        addItem(NTechItems.tinyNuclearWaste, "작은 핵 폐기물")

        addItem(NTechItems.crystalHorn, "수정 뿔")
        addItemDesc(NTechItems.crystalHorn, "진짜 뿔.")
        addItem(NTechItems.charredCrystal, "불탄 수정")
        addItemDesc(NTechItems.charredCrystal, "이것도 진짜 뿔입니다. 이상하죠?")

        addItem(NTechItems.battery, "전지")
        addItem(NTechItems.redstonePowerCell, "레드스톤 전력 셀")
        addItem(NTechItems.sixfoldRedstonePowerCell, "6중 레드스톤 전력 셀")
        addItem(NTechItems.twentyFourFoldRedstonePowerCell, "24중 레드스톤 전력 셀")
        addItem(NTechItems.advancedBattery, "고급 전지")
        addItem(NTechItems.advancedPowerCell, "고급 전력 셀")
        addItem(NTechItems.quadrupleAdvancedPowerCell, "4중 고급 전력 셀")
        addItem(NTechItems.twelveFoldAdvancedPowerCell, "12중 고급 전력 셀")
        addItem(NTechItems.lithiumBattery, "리튬-이온 전지")
        addItem(NTechItems.lithiumPowerCell, "리튬-이온 전력 셀")
        addItem(NTechItems.tripleLithiumPowerCell, "3중 리튬-이온 전력 셀")
        addItem(NTechItems.sixfoldLithiumPowerCell, "6중 리튬-이온 전력 셀")
        addItem(NTechItems.schrabidiumBattery, "스크라비듐 전지")
        addItem(NTechItems.schrabidiumPowerCell, "스크라비듐 전력 셀")
        addItem(NTechItems.doubleSchrabidiumPowerCell, "2중 스크라비듐 전력 셀")
        addItem(NTechItems.quadrupleSchrabidiumPowerCell, "4중 스크라비듐 전력 셀")
        addItem(NTechItems.sparkBattery, "스파크 전지")
        addItem(NTechItems.offBrandSparkBattery, "짝퉁 스파크 전지")
        addItem(NTechItems.sparkPowerCell, "스파크 전력 셀")
        addItem(NTechItems.sparkArcaneCarBattery, "스파크 아케인 자동차 배터리")
        addItem(NTechItems.sparkArcaneEnergyStorageArray, "스파크 아케인 전력 저장 어레이")
        addItem(NTechItems.sparkArcaneMassEnergyVoid, "스파크 아케인 질량-에너지 보이드")
        addItem(NTechItems.sparkArcaneDiracSea, "스파크 아케인 다이락의 바다")
        addItem(NTechItems.sparkSolidSpaceTimeCrystal, "스파크 고체 시공간 수정")
        addItem(NTechItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit, "스파크 유사과학 역학무시 에너지 저장장치")
        addItem(NTechItems.infiniteBattery, "무한 전지")
        addItem(NTechItems.singleUseBattery, "일회용 전지")
        addItem(NTechItems.largeSingleUseBattery, "대용량 일회용 전지")
        addItem(NTechItems.potatoBattery, "감자 전지")
        addItem(NTechItems.steamPoweredEnergyStorageTank, "증기기관 에너지 저장 탱크")
        addItem(NTechItems.largeSteamPoweredEnergyStorageTank, "대형 증기기관 에너지 저장 탱크")

        addItem(NTechItems.stoneFlatStamp, "평평한 틀  (돌)")
        addItem(NTechItems.stonePlateStamp, "판 틀  (돌)")
        addItem(NTechItems.stoneWireStamp, "전선 틀  (돌)")
        addItem(NTechItems.stoneCircuitStamp, "회로 틀  (돌)")
        addItem(NTechItems.ironFlatStamp, "평평한 틀  (철)")
        addItem(NTechItems.ironPlateStamp, "판 틀  (철)")
        addItem(NTechItems.ironWireStamp, "전선 틀  (철)")
        addItem(NTechItems.ironCircuitStamp, "회로 틀  (철)")
        addItem(NTechItems.steelFlatStamp, "평평한 틀  (강철)")
        addItem(NTechItems.steelPlateStamp, "판 틀  (강철)")
        addItem(NTechItems.steelWireStamp, "전선 틀  (강철)")
        addItem(NTechItems.steelCircuitStamp, "회로 틀  (강철)")
        addItem(NTechItems.titaniumFlatStamp, "평평한 틀  (티타늄)")
        addItem(NTechItems.titaniumPlateStamp, "판 틀  (티타늄)")
        addItem(NTechItems.titaniumWireStamp, "전선 틀  (티타늄)")
        addItem(NTechItems.titaniumCircuitStamp, "회로 틀  (티타늄)")
        addItem(NTechItems.obsidianFlatStamp, "평평한 틀  (흑요석")
        addItem(NTechItems.obsidianPlateStamp, "판 틀  (흑요석")
        addItem(NTechItems.obsidianWireStamp, "전선 틀  (흑요석")
        addItem(NTechItems.obsidianCircuitStamp, "회로 틀  (흑요석")
        addItem(NTechItems.schrabidiumFlatStamp, "평평한 틀  (스크라비듐)")
        addItem(NTechItems.schrabidiumPlateStamp, "판 틀  (스크라비듐)")
        addItem(NTechItems.schrabidiumWireStamp, "전선 틀  (스크라비듐)")
        addItem(NTechItems.schrabidiumCircuitStamp, "회로 틀  (스크라비듐)")

        addItem(NTechItems.screwdriver, "드라이버")
        addItemDesc(NTechItems.screwdriver, "퓨즈 대신 사용 가능...")
        addItem(NTechItems.deshScrewdriver, "데쉬 드라이버")

        addItem(NTechItems.speedUpgradeMk1, "속도 업그레이드 Mk.I")
        addItem(NTechItems.speedUpgradeMk2, "속도 업그레이드 Mk.II")
        addItem(NTechItems.speedUpgradeMk3, "속도 업그레이드 Mk.III")
        addItem(NTechItems.powerSavingUpgradeMk1, "에너지 절약 업그레이드 Mk.I")
        addItem(NTechItems.powerSavingUpgradeMk2, "에너지 절약 업그레이드 Mk.II")
        addItem(NTechItems.powerSavingUpgradeMk3, "에너지 절약 업그레이드 Mk.III")
        addItem(NTechItems.overdriveUpgradeMk1, "과부하 업그레이드 Mk.I")
        addItem(NTechItems.overdriveUpgradeMk2, "과부하 업그레이드 Mk.II")
        addItem(NTechItems.overdriveUpgradeMk3, "과부하 업그레이드 Mk.III")
        addItem(NTechItems.afterBurnUpgradeMk1, "후기연소기 업그레이드 Mk.I")
        addItem(NTechItems.afterBurnUpgradeMk2, "후기연소기 업그레이드 Mk.II")
        addItem(NTechItems.afterBurnUpgradeMk3, "후기연소기 업그레이드 Mk.III")

        addItem(NTechItems.aluminiumShredderBlade, "알루미늄 분쇄기 날")
        addItem(NTechItems.goldShredderBlade, "Gold 분쇄기 날")
        addItem(NTechItems.ironShredderBlade, "철 분쇄기 날")
        addItem(NTechItems.steelShredderBlade, "강철 분쇄기 날")
        addItem(NTechItems.titaniumShredderBlade, "티타늄 분쇄기 날")
        addItem(NTechItems.advancedAlloyShredderBlade, "고급 합금 분쇄기 날")
        addItem(NTechItems.combineSteelShredderBlade, "콤바인 강철 분쇄기 날")
        addItem(NTechItems.schrabidiumShredderBlade, "스크라비듐 분쇄기 날")
        addItem(NTechItems.deshShredderBlade, "데쉬 분쇄기 날")

        addItem(NTechItems.rbmkLid, "RBMK 덮개 패널")
        addItem(NTechItems.rbmkGlassLid, "RBMK 유리 덮개 패널")

        addItem(NTechItems.rbmkPelletBalefire, "베일파이어 연료 펠릿")
        addItem(NTechItems.rbmkPelletBalefireGold, "플래쉬골드 연료 펠릿")
        addItem(NTechItems.rbmkPelletDrx, "§c다이감마 연료 펠릿§r")
        addItem(NTechItems.rbmkPelletFlashlead, "플래쉬리드 연료 펠릿")
        addItem(NTechItems.rbmkPelletHea241, "고농축 아메리슘-241 연료 펠릿")
        addItem(NTechItems.rbmkPelletHea242, "고농축 아메리슘-242 연료 펠릿")
        addItem(NTechItems.rbmkPelletHeaus, "고농축 오스트레일륨 연료 펠릿")
        addItem(NTechItems.rbmkPelletHen, "고농축 넵투늄연료 펠릿")
        addItem(NTechItems.rbmkPelletHes, "고농축 플루토늄-239 연료 펠릿")
        addItem(NTechItems.rbmkPelletHep239, "고농축 우라늄-241 연료 펠릿")
        addItem(NTechItems.rbmkPelletHep241, "고농축 우라늄-233 연료 펠릿")
        addItem(NTechItems.rbmkPelletHeu233, "고농축 우라늄-235 연료 펠릿")
        addItem(NTechItems.rbmkPelletHeu235, "HES 연료 펠릿")
        addItem(NTechItems.rbmkPelletLea, "LEA 연료 펠릿")
        addItem(NTechItems.rbmkPelletLeaus, "LEAus 연료 펠릿")
        addItem(NTechItems.rbmkPelletLep, "LEP 연료 펠릿")
        addItem(NTechItems.rbmkPelletLes, "LES 연료 펠릿")
        addItem(NTechItems.rbmkPelletMea, "MEA 연료 펠릿")
        addItem(NTechItems.rbmkPelletMen, "MEN 연료 펠릿")
        addItem(NTechItems.rbmkPelletMep, "MEP 연료 펠릿")
        addItem(NTechItems.rbmkPelletMes, "MES 연료 펠릿")
        addItem(NTechItems.rbmkPelletMeu, "MEU 연료 펠릿")
        addItem(NTechItems.rbmkPelletMox, "혼합 산화물 연료 펠릿")
        addItem(NTechItems.rbmkPelletPo210Be, "Po210Be 중성자원 펠릿")
        addItem(NTechItems.rbmkPelletPu238Be, "Pu238Be 중성자원 펠릿")
        addItem(NTechItems.rbmkPelletRa226Be, "Ra226Be 중성자원 펠릿")
        addItem(NTechItems.rbmkPelletThMeu, "ThMEU 연료 펠릿")
        addItem(NTechItems.rbmkPelletUeu, "NU 연료 펠릿")
        addItem(NTechItems.rbmkPelletZfbAmMix, "연료 등급 아메리슘 ZFB 펠릿")
        addItem(NTechItems.rbmkPelletZfbBismuth, "비스무트 ZFB 펠릿")
        addItem(NTechItems.rbmkPelletZfbPu241, "Pu-241 ZFB 펠릿")

        addItem(NTechItems.emptyRBMKRod, "빈 RBMK 연료봉")
        addItem(NTechItems.rbmkRodBalefire, "베일파이어 RBMK 연료봉")
        addItem(NTechItems.rbmkRodBalefireGold, "플래쉬골드 RBMK 연료봉")
        addItem(NTechItems.rbmkRodDrx, "§c다이감마 RBMK 연료봉§r")
        addItem(NTechItems.rbmkRodFlashlead, "플래쉬리드 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHea241, "고농축 아메리슘-241 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHea242, "고농축 아메리슘-242 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHeaus, "고농축 오스트레일륨 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHen, "고농축 넵투늄 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHes, "HES RBMK 연료봉")
        addItem(NTechItems.rbmkRodHep239, "고농축 플루토늄-239 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHep241, "고농축 플루토늄-241 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHeu233, "고농축 우라늄-233 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHeu235, "고농축 우라늄-235 RBMK 연료봉")
        addItem(NTechItems.rbmkRodLea, "LEA RBMK 연료봉")
        addItem(NTechItems.rbmkRodLeaus, "LEAus RBMK 연료봉")
        addItem(NTechItems.rbmkRodLep, "LEP-239 RBMK 연료봉")
        addItem(NTechItems.rbmkRodLes, "LES RBMK 연료봉")
        addItem(NTechItems.rbmkRodMea, "MEA RBMK 연료봉")
        addItem(NTechItems.rbmkRodMen, "MEN RBMK 연료봉")
        addItem(NTechItems.rbmkRodMep, "MEP-239 RBMK 연료봉")
        addItem(NTechItems.rbmkRodMes, "MES RBMK 연료봉")
        addItem(NTechItems.rbmkRodMeu, "MEU RBMK 연료봉")
        addItem(NTechItems.rbmkRodMox, "혼합 산화물 RBMK 연료봉")
        addItem(NTechItems.rbmkRodPo210Be, "Po210Be RBMK 중성자원")
        addItem(NTechItems.rbmkRodPu238Be, "Pu238Be RBMK 중성자원")
        addItem(NTechItems.rbmkRodRa226Be, "Ra226Be RBMK 중성자원")
        addItem(NTechItems.rbmkRodThMeu, "ThMEU RBMK 연료봉")
        addItem(NTechItems.rbmkRodUeu, "NU RBMK 연료봉")
        addItem(NTechItems.rbmkRodZfbAmMix, "연료 등급 아메리슘 RBMK ZFB봉")
        addItem(NTechItems.rbmkRodZfbBismuth, "비스무트 RBMK ZFB봉")
        addItem(NTechItems.rbmkRodZfbPu241, "Pu-241 RBMK ZFB봉")

        addItem(NTechItems.meltdownTool, "댜틀로프 즉석 노심용융 적용기")

        addItem(NTechItems.graphiteDebris, "뜨거운 흑연 덩어리")
        addItem(NTechItems.metalDebris, "부서진 철근")
        addItem(NTechItems.fuelDebris, "RBMK 연료 덩어리")

        addItem(NTechItems.machineTemplateFolder, "기계 설계도 폴더")
        addItemDesc(
            NTechItems.machineTemplateFolder,
            "기계 설계도: 종이 + 염료\n" +
                    "유체 ID들: 철 판 + 염료\n" +
                    "압착기 틀: 평평한 틀\n" +
                    "사이렌 소리: 절연체 + 강철 판"
        )

        addItem(NTechItems.sirenTrackHatchSiren, "해치 개방 경보 사이렌")
        addItem(NTechItems.sirenTrackAutopilotDisconnected, "오토파일럿 해제")
        addItem(NTechItems.sirenTrackAMSSiren, "AMS 경보 사이렌")
        addItem(NTechItems.sirenTrackBlastDoorAlarm, "방폭문 경고음")
        addItem(NTechItems.sirenTrackAPCSiren, "APC 사이렌")
        addItem(NTechItems.sirenTrackKlaxon, "경적")
        addItem(NTechItems.sirenTrackVaultDoorAlarm, "볼트 문 경고음")
        addItem(NTechItems.sirenTrackSecurityAlert, "보안 경고음")
        addItem(NTechItems.sirenTrackStandardSiren, "일반 사이렌")
        addItem(NTechItems.sirenTrackClassicSiren, "구형 사이렌")
        addItem(NTechItems.sirenTrackBankAlarm, "은행 경고음")
        addItem(NTechItems.sirenTrackBeepSiren, "비프음 사이렌")
        addItem(NTechItems.sirenTrackContainerAlarm, "컨테이너 경고음")
        addItem(NTechItems.sirenTrackSweepSiren, "스윕 사이렌")
        addItem(NTechItems.sirenTrackMissileSiloSiren, "미사일 사일로 사이렌")
        addItem(NTechItems.sirenTrackAirRaidSiren, "공습 경고 사이렌")
        addItem(NTechItems.sirenTrackNostromoSelfDestruct, "노스트로모 자폭 경고음")
        addItem(NTechItems.sirenTrackEASAlarmScreech, "EAS 경고음")
        addItem(NTechItems.sirenTrackAPCPass, "APC Pass")
        addItem(NTechItems.sirenTrackRazortrainHorn, "레이저트레인 경적")

        addItem(NTechItems.fluidIdentifier, "유체 ID: %s")
        addItemDesc(NTechItems.fluidIdentifier, "플루이드 덕트를 우클릭해서 해당 덕트에 이 유체를 할당합니다.\n쉬프트 우클릭시 최대 64개의 인접 덕트에도\n해당 유체를 할당합니다.")

        addItem(NTechItems.assemblyTemplate, "조립 설계도: %s")
        addItem(NTechItems.chemTemplate, "화학 설계도: %s")

        run {
            val usedInLittleBoy = "사용처:\n리틀 보이"
            addItem(NTechItems.neutronShieldingLittleBoy, "중성자 차폐막")
            addItemDesc(NTechItems.neutronShieldingLittleBoy, usedInLittleBoy)
            addItem(NTechItems.subcriticalUraniumTarget, "아임계 U235 표적")
            addItemDesc(NTechItems.subcriticalUraniumTarget, usedInLittleBoy)
            addItem(NTechItems.uraniumProjectile, "U235 발사체")
            addItemDesc(NTechItems.uraniumProjectile, usedInLittleBoy)
            addItem(NTechItems.propellantLittleBoy, "추진체")
            addItemDesc(NTechItems.propellantLittleBoy, usedInLittleBoy)
            addItem(NTechItems.bombIgniterLittleBoy, "폭탄 점화기")
            addItemDesc(NTechItems.bombIgniterLittleBoy, usedInLittleBoy)
        }
        addItem(NTechItems.bundleOfImplosionPropellant, "내파 추진체 묶음")
        addItemDesc(NTechItems.bundleOfImplosionPropellant, "사용처:\n팻 맨\nIvy Mike\n차르 봄바")
        addItem(NTechItems.bombIgniterFatMan, "폭탄 점화기")
        addItemDesc(NTechItems.bombIgniterFatMan, "팻 맨에서 사용됨")
        addItem(NTechItems.plutoniumCore, "플루토늄 핵")
        addItemDesc(NTechItems.plutoniumCore, "사용처:\n팻 맨\n아이비 마이크\n차르 봄바")
        addItem(NTechItems.detonator, "기폭장치")
        addItemDesc(NTechItems.detonator, "쉬프트 우클릭으로 폭발물의 위치를 지정하고,\n우클릭으로 기폭합니다!")
        addItem(NTechItems.littleBoyKit, "리틀 보이 키트")
        addItem(NTechItems.fatManKit, "팻 맨 키트")

        addItem(NTechItems.designator, "단거리 표적지시기")
        addItem(NTechItems.heMissile, "고폭 미사일")
        addItem(NTechItems.incendiaryMissile, "소이 미사일")
        addItem(NTechItems.clusterMissile, "집속 미사일")
        addItem(NTechItems.bunkerBusterMissile, "벙커 버스터")
        addItem(NTechItems.strongMissile, "고위력 고폭 미사일")
        addItem(NTechItems.strongIncendiaryMissile, "고위력 소이 미사일")
        addItem(NTechItems.strongClusterMissile, "고위력 집속 미사일")
        addItem(NTechItems.strongBunkerBusterMissile, "개선형 벙커 버스터")
        addItem(NTechItems.burstMissile, "버스트 미사일")
        addItem(NTechItems.infernoMissile, "화염 미사일 G.R.N. Mk.II")
        addItem(NTechItems.rainMissile, "폭탄 비")
        addItem(NTechItems.drillMissile, "콘크리트 분쇄기")
        addItem(NTechItems.nuclearMissile, "핵미사일")
        addItem(NTechItems.tectonicMissile, "지진 미사일")
        addItemDesc(NTechItems.tectonicMissile, "핵폭발의 위력으로, 활화산을 만들 수 있습니다!")

        addItem(NTechItems.meteorRemote, "운석 리모컨")
        addItemDesc(NTechItems.meteorRemote, "우클릭으로 운석을 떨어뜨립니다!")
        addItem(NTechItems.oilDetector, "유정 감지기")
        addItemDesc(NTechItems.oilDetector, "우클릭으로 유정을 찾습니다.\n해당 감지기는 대형 유정만 찾습니다.")
        addItem(NTechItems.rbmkLinker, "RBMK 콘솔 연결장치")
        addItemDesc(NTechItems.rbmkLinker, "RBMK를 쉬프트 우클릭해 위치를 저장하고, 콘솔이나 크레인을 쉬프트 우클릭해 연결합니다!")
        addItem(NTechItems.geigerCounter, "휴대용 가이거 계수기")

        addItem(NTechItems.ivBag, "IV 팩")
        addItem(NTechItems.bloodBag, "혈액 팩")
        addItem(NTechItems.emptyExperienceBag, "빈 경험치 팩")
        addItem(NTechItems.experienceBag, "경험치 팩")
        addItem(NTechItems.radAway, "라드어웨이")
        addItem(NTechItems.strongRadAway, "강한 라드어웨이")
        addItem(NTechItems.eliteRadAway, "엘리트 라드어웨이")

        addItem(NTechItems.hazmatHelmet, "방호복 헬멧")
        addItem(NTechItems.hazmatChestplate, "방호복 흉갑")
        addItem(NTechItems.hazmatLeggings, "방호복 레깅스")
        addItem(NTechItems.hazmatBoots, "방호복 부츠")
        addItem(NTechItems.advancedHazmatHelmet, "고급 방호복 헬멧")
        addItem(NTechItems.advancedHazmatChestplate, "고급 방호복 흉갑")
        addItem(NTechItems.advancedHazmatLeggings, "고급 방호복 레깅스")
        addItem(NTechItems.advancedHazmatBoots, "고급 방호복 부츠")
        addItem(NTechItems.reinforcedHazmatHelmet, "고성능 방호복 헬멧")
        addItem(NTechItems.reinforcedHazmatChestplate, "고성능 방호복 흉갑")
        addItem(NTechItems.reinforcedHazmatLeggings, "고성능 방호복 레깅스")
        addItem(NTechItems.reinforcedHazmatBoots, "고성능 방호복 부츠")
        addItem(NTechItems.titaniumHelmet, "티타늄 헬멧")
        addItem(NTechItems.titaniumChestplate, "티타늄 흉갑")
        addItem(NTechItems.titaniumLeggings, "티타늄 레깅스")
        addItem(NTechItems.titaniumBoots, "티타늄 부츠")
        addItem(NTechItems.steelHelmet, "강철 헬멧")
        addItem(NTechItems.steelChestplate, "강철 흉갑")
        addItem(NTechItems.steelLeggings, "강철 레깅스")
        addItem(NTechItems.steelBoots, "강철 부츠")
        addItem(NTechItems.advancedAlloyHelmet, "고급 합금 헬멧")
        addItem(NTechItems.advancedAlloyChestplate, "고급 합금 흉갑")
        addItem(NTechItems.advancedAlloyLeggings, "고급 합금 레깅스")
        addItem(NTechItems.advancedAlloyBoots, "고급 합금 부츠")
        addItem(NTechItems.combineSteelHelmet, "콤바인 강철 헬멧")
        addItem(NTechItems.combineSteelChestplate, "콤바인 강철 흉갑")
        addItem(NTechItems.combineSteelLeggings, "콤바인 강철 레깅스")
        addItem(NTechItems.combineSteelBoots, "콤바인 강철 부츠")
        addItem(NTechItems.paAAlloyChestplate, "PaA 신체 보호재")
        addItem(NTechItems.paAAlloyLeggings, "PaA 다리 보포재")
        addItem(NTechItems.paAAlloyBoots, "PaA \"좋은 신발\"")
        addItem(NTechItems.schrabidiumHelmet, "스크라비듐 헬멧")
        addItem(NTechItems.schrabidiumChestplate, "스크라비듐 흉갑")
        addItem(NTechItems.schrabidiumLeggings, "스크라비듐 레깅스")
        addItem(NTechItems.schrabidiumBoots, "스크라비듐 부츠")

        addItem(NTechItems.polaroid, "폴라로이드")

        addItem(NTechFluids.spentSteam.bucket, "저압 증기 양동이")
        addItem(NTechFluids.steam.bucket, "증기 양동이")
        addItem(NTechFluids.steamHot.bucket, "고압 증기 양동이")
        addItem(NTechFluids.steamSuperHot.bucket, "초고압 증기 양동이")
        addItem(NTechFluids.steamUltraHot.bucket, "극고압 증기 양동이")
        addItem(NTechFluids.gas.bucket, "천연 가스 양동이")
        addItem(NTechFluids.oil.bucket, "원유 양동이")
        addItem(NTechFluids.uraniumHexafluoride.bucket, "육불화우라늄 양동이")
        addItem(NTechFluids.corium.bucket, "노심용융물 양동이")
        addItem(NTechFluids.volcanicLava.bucket, "화산 용암 양동이")

        addItem(NTechItems.creativeNuclearExplosionSpawner, "핵폭발 생성기")
        addItemDesc(NTechItems.creativeNuclearExplosionSpawner, "CakeCo 생산\nEast Spawn Rd 2, 68-419 RetroMC")

        addEntityType(EntityTypes.clusterFragment, "소형 폭탄")
        addEntityType(EntityTypes.falloutRain, "낙진 비")
        addEntityType(EntityTypes.meteor, "운석")
        addEntityType(EntityTypes.missileBunkerBuster, "벙커 버스터")
        addEntityType(EntityTypes.missileBunkerBusterStrong, "상급 벙커 버스터")
        addEntityType(EntityTypes.missileBurst, "버스트 미사일")
        addEntityType(EntityTypes.missileCluster, "집속 미사일")
        addEntityType(EntityTypes.missileClusterStrong, "고위력 집속 미사일")
        addEntityType(EntityTypes.missileDrill, "콘크리트 분쇄기")
        addEntityType(EntityTypes.missileHE, "고폭 미사일")
        addEntityType(EntityTypes.missileHEStrong, "고위력 고폭 미사일")
        addEntityType(EntityTypes.missileIncendiary, "소이 미사일")
        addEntityType(EntityTypes.missileIncendiaryStrong, "고위력 소이 미사일")
        addEntityType(EntityTypes.missileInferno, "화염 미사일 G.R.N. Mk.II")
        addEntityType(EntityTypes.missileNuclear, "핵 미사일")
        addEntityType(EntityTypes.missileRain, "폭탄 비")
        addEntityType(EntityTypes.missileTectonic, "지진 미사일")
        addEntityType(EntityTypes.mushroomCloud, "버섯 구름")
        addEntityType(EntityTypes.nuclearExplosion, "핵폭발")
        addEntityType(EntityTypes.oilSpill, "유출된 원유")
        addEntityType(EntityTypes.rbmkDebris, "RBMK 잔해")
        addEntityType(EntityTypes.shrapnel, "파편")
        addEntityType(EntityTypes.volcanicShrapnel, "화산 파편")

        addEntityTypeWithSpawnEgg(EntityTypes.nuclearCreeper, NTechItems.nuclearCreeperSpawnEgg, "핵 크리퍼")

        addMenuType(MenuTypes.sirenMenu, "사이렌")
        addMenuType(MenuTypes.safeMenu, "금고")
        addMenuType(MenuTypes.anvilMenu, "%s 티어 모루")
        addMenuType(MenuTypes.steamPressMenu, "증기 압착기")
        addMenuType(MenuTypes.blastFurnaceMenu, "용광로")
        addMenuType(MenuTypes.combustionGeneratorMenu, "연소 발전기")
        addMenuType(MenuTypes.electricFurnaceMenu, "전기로")
        addMenuType(MenuTypes.shredderMenu, "분쇄기")
        addMenuType(MenuTypes.assemblerMenu, "조립기")
        addMenuType(MenuTypes.chemPlantMenu, "화학 공장")
        addMenuType(MenuTypes.turbineMenu, "증기 터빈")
        addMenuType(MenuTypes.oilWellMenu, "유정")
        add(LangKeys.CONTAINER_OIL_DERRICK, "유정탑")
        add(LangKeys.CONTAINER_PUMPJACK, "펌프잭")
        addMenuType(MenuTypes.centrifugeMenu, "원심분리기")
        addMenuType(MenuTypes.rbmkRodMenu, "RBMK 연료봉")
        add(LangKeys.CONTAINER_RBMK_REASIM_ROD, "RBMK 연료봉 (ReaSim)")
        addMenuType(MenuTypes.rbmkBoilerMenu, "RBMK 증기 채널")
        addMenuType(MenuTypes.rbmkManualControlMenu, "RBMK 제어봉")
        add(LangKeys.CONTAINER_RBMK_CONTROL_MODERATED, "RBMK 감속 제어봉")
        addMenuType(MenuTypes.rbmkAutoControlMenu, "RBMK 자동 제어봉")
        addMenuType(MenuTypes.rbmkConsoleMenu, "RBMK 제어기")

        addMenuType(MenuTypes.littleBoyMenu, "리틀 보이")
        addMenuType(MenuTypes.fatManMenu, "팻 맨")

        addMenuType(MenuTypes.launchPadMenu, "미사일 발사대")

        addDamageSource(DamageSources.extractBlood, "%1\$s extracted too much life essence", "%1\$s tried to leave neatly-packaged life juice for %2\$s")
        addDamageSource(DamageSources.meteorite, "%1\$s was hit by a falling rock from outer space", "%1\$s was hit by a falling rock from outer space whilst trying to escape %2\$s")
        addDamageSource(DamageSources.murkyAnvil, "%1\$s UNDEFINED", "%1\$s UNDEFINED whilst trying to escape %2\$s")
        addDamageSource(DamageSources.nuclearBlast, "%1\$s was blown away by a nuclear explosion", "%1\$s got nuked whilst fighting %2\$s")
        addDamageSource(DamageSources.radiation, "%1\$s died from radiation poisoning", "%1\$s fell victim to acute radiation syndrome whilst fighting %2\$s")
        addDamageSource(DamageSources.shrapnel, "%1\$s was ragged by a shrapnel", "%1\$s was ragged by a shrapnel whilst fighting %2\$s")

        addAttribute(Attributes.RADIATION_RESISTANCE, "Radiation Resistance")

        addFluidTrait(NTechFluidTraits.liquid, "유체")
        addFluidTrait(NTechFluidTraits.gaseous, "기체")
        addFluidTrait(NTechFluidTraits.gaseousRoomTemp, "상온에서 기체")
        addFluidTrait(NTechFluidTraits.plasma, "플라즈마")
        addFluidTrait(NTechFluidTraits.antimatter, "반물질")
        addFluidTrait(NTechFluidTraits.delicious, "맛있음")
        addFluidTrait(NTechFluidTraits.combustible, "폭발성")
        addFluidTrait(NTechFluidTraits.coolable, "냉각 가능")
        addFluidTrait(NTechFluidTraits.corrosive, "부식성")
        addFluidTrait(NTechFluidTraits.flammable, "가연성")
        addFluidTrait(NTechFluidTraits.heatable, "가열 가능")
        addFluidTrait(NTechFluidTraits.radioactive, "방사성")
        addFluidTrait(NTechFluidTraits.toxic, "유독 가스")

        add(LangKeys.ARMOR_BLAST_PROTECTION, "Damage modifier of %s against explosions")
        add(LangKeys.ARMOR_CUSTOM_GEIGER, "Built-In Geiger Counter HUD")
        add(LangKeys.ARMOR_DAMAGE_CAP, "Hard damage cap of %s")
        add(LangKeys.ARMOR_DAMAGE_MODIFIER, "General damage modifier of %s")
        add(LangKeys.ARMOR_DAMAGE_RESISTANCE_MODIFIER, "Damage modifier of %s against %s")
        add(LangKeys.ARMOR_DAMAGE_THRESHOLD, "Damage threshold of %s")
        add(LangKeys.ARMOR_DASH_COUNT, "Grants %s dashes")
        add(LangKeys.ARMOR_FIREPROOF, "Fireproof")
        add(LangKeys.ARMOR_FULL_SET_BONUS, "Full Set Bonus:")
        add(LangKeys.ARMOR_GEIGER_SOUND, "Auditory Geiger Counter")
        add(LangKeys.ARMOR_GRAVITY, "Gravity modifier of %s")
        add(LangKeys.ARMOR_HARD_LANDING, "Hard Landing")
        add(LangKeys.ARMOR_NULLIFIES_DAMAGE, "Nullifies all damage from %s")
        add(LangKeys.ARMOR_PROJECTILE_PROTECTION, "Damage modifier of %s against projectiles")
        add(LangKeys.ARMOR_PROTECTION_YIELD, "Protection applies to damage <%s")
        add(LangKeys.ARMOR_THERMAL, "Thermal Sight")
        add(LangKeys.ARMOR_VATS, "Enemy HUD")

        add(LangKeys.BUTTON_CANCEL, "취소")
        add(LangKeys.BUTTON_START, "시작")

        add(LangKeys.CHEMISTRY_URANIUM_HEXAFLUORIDE, "육불화우라늄 생산")

        add(LangKeys.DETONATOR_INVALID_BLOCK_ENTITY, "서버 오류: 목표 타일엔티티가 올바르지 않습니다!")
        add(LangKeys.DETONATOR_MISSING_COMPONENTS, "The explosive is missing components!")
        add(LangKeys.DETONATOR_NO_EXPLOSIVE, "Target is not a valid explosive!")
        add(LangKeys.DETONATOR_PROHIBITED, "The detonation was prohibited!")
        add(LangKeys.DETONATOR_SUCCESS, "Detonated!")
        add(LangKeys.DETONATOR_UNKNOWN_ERROR, "An unknown error occurred during the detonation")

        add(LangKeys.DEVICE_METEOR_REMOTE_WATCH_OUT, "Watch your head!")
        add(LangKeys.DEVICE_OIL_DETECTOR_BELOW, "Oil deposit directly below!")
        add(LangKeys.DEVICE_OIL_DETECTOR_NEAR, "Oil deposit detected nearby")
        add(LangKeys.DEVICE_OIL_DETECTOR_NO_OIL, "No oil detected")
        add(LangKeys.DEVICE_POSITION_SET, "Position set!")
        add(LangKeys.DEVICE_POSITION_NOT_LOADED, "Position is currently not loaded in the world!")
        add(LangKeys.DEVICE_POSITION_NOT_SET, "No position set!")

        add(LangKeys.ENERGY, "Energy")
        add(LangKeys.ENERGY_ENERGY_STORED, "Energy Stored: %s/%sHE")
        add(LangKeys.ENERGY_CHARGE_RATE, "Charge Rate: %sHE/t")
        add(LangKeys.ENERGY_DISCHARGE_RATE, "Discharge Rate: %sHE/t")

        add(LangKeys.EXPLOSION_SPAWNER_ERROR_EXTRA_FALLOUT, "Cannot parse extra fallout value")
        add(LangKeys.EXPLOSION_SPAWNER_ERROR_STRENGTH, "Cannot parse strength value")
        add(LangKeys.EXPLOSION_SPAWNER_EXTRA_FALLOUT, "Extra Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_HAS_FALLOUT, "Has Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_MUTED, "Muted")
        add(LangKeys.EXPLOSION_SPAWNER_NO_PERMISSION, "Cannot use Nuclear Explosion Spawner: Insufficient permission")
        add(LangKeys.EXPLOSION_SPAWNER_POSITION, "Position")
        add(LangKeys.EXPLOSION_SPAWNER_STRENGTH, "Strength")

        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE, "Fuel grade: %s")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_AERO, "Aviation")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_GAS, "Gaseous")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_HIGH, "High")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_LOW, "Low")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_MEDIUM, "Medium")
        add(LangKeys.FLUID_TRAIT_COOLABLE_HEAT_EXCHANGER, "Coolable")
        add(LangKeys.FLUID_TRAIT_COOLABLE_TURBINE, "Turbine Steam")
        add(LangKeys.FLUID_TRAIT_CORROSIVE_STRONG, "Strongly Corrosive")
        add(LangKeys.FLUID_TRAIT_EFFICIENCY, "효율: %s%%")
        add(LangKeys.FLUID_TRAIT_ENERGY_INFO, "Provides %s per bucket")
        add(LangKeys.FLUID_TRAIT_HEATABLE_BOILER, "Boilable")
        add(LangKeys.FLUID_TRAIT_HEATABLE_HEAT_EXCHANGER, "Heatable")

        add(LangKeys.GEIGER_CHUNK_RADIATION, "Current chunk radiation:")
        add(LangKeys.GEIGER_PLAYER_IRRADIATION, "Player irradiation:")
        add(LangKeys.GEIGER_PLAYER_RESISTANCE, "Player resistance:")
        add(LangKeys.GEIGER_TITLE, "GEIGER COUNTER")
        add(LangKeys.GEIGER_TOTAL_ENVIRONMENTAL_RADIATION, "Total environmental radiation:")

        add(LangKeys.HAZARD_ASBESTOS, "[석면]")
        add(LangKeys.HAZARD_BLINDING, "[실명]")
        add(LangKeys.HAZARD_COAL, "[석탄 가루]")
        add(LangKeys.HAZARD_DIGAMMA, "[다이감마]")
        add(LangKeys.HAZARD_EXPLOSIVE, "[가연성 / 폭발성]")
        add(LangKeys.HAZARD_HEAT, "[발화성 / 고온]")
        add(LangKeys.HAZARD_HYDROREACTIVE, "[수소 반응성]")
        add(LangKeys.HAZARD_RADIATON, "[방사성]")

        add(LangKeys.INFO_HOLD_KEY_FOR_INFO, "Hold %s to display more info")
        add(LangKeys.INFO_INPUT, "Input:")
        add(LangKeys.INFO_INPUTS, "Inputs:")
        add(LangKeys.INFO_ORE_CLUSTER, "Drops only when broken by a player")
        add(LangKeys.INFO_OUTPUT, "Output:")
        add(LangKeys.INFO_OUTPUTS, "Outputs:")
        add(LangKeys.INFO_POSITION, "Position: %d %d %d")
        add(LangKeys.INFO_PRODUCTION_TIME, "Production Time:")

        add(LangKeys.JEI_CATEGORY_ASSEMBLING, "Assembling")
        add(LangKeys.JEI_CATEGORY_BLASTING, "Blasting")
        add(LangKeys.JEI_CATEGORY_CHEMISTRY, "Chemistry")
        add(LangKeys.JEI_CATEGORY_CONSTRUCTING, "Constructing")
        add(LangKeys.JEI_CATEGORY_PRESSING, "Pressing")
        add(LangKeys.JEI_CATEGORY_SHREDDING, "Shredding")
        add(LangKeys.JEI_CATEGORY_SMITHING, "Smithing")
        add(LangKeys.JEI_CATEGORY_TEMPLATE_FOLDER, "Template Folder")
        add(LangKeys.JEI_EXPERIENCE, "%s XP")
        add(LangKeys.JEI_OUTPUT_CHANCE, "Output chance:")
        add(LangKeys.JEI_TIER_MINIMUM, "Minimum Tier: %s")
        add(LangKeys.JEI_TIER_RANGE, "Tier Range: %s..%s")

        add(LangKeys.OIL_WELL_STATUS_OK, "상태: 정상")
        add(LangKeys.OIL_WELL_STATUS_NO_OIL_SOURCE, "상태: 유정 없음")
        add(LangKeys.OIL_WELL_STATUS_ERROR, "상태: 작동 불가")
        add(LangKeys.OIL_WELL_STATUS_OUT_OF_FLUID, "상태: 수압파쇄액 없음")
        add(LangKeys.OIL_WELL_STATUS_LOOKING_FOR_OIL, "상태: 원유를 찾는 중")
        add(LangKeys.OIL_WELL_STATUS_NO_POWER, "상태: 전력 없음")

        add(LangKeys.RBMK_BOILER_STEAM, "Steam: %d / %d")
        add(LangKeys.RBMK_BOILER_TYPE, "Compressor: %s")
        add(LangKeys.RBMK_BOILER_WATER, "Feedwater: %d / %d")
        add(LangKeys.RBMK_BURN_EULER, "SAFE / EULER")
        add(LangKeys.RBMK_BURN_LINEAR, "DANGEROUS / LINEAR")
        add(LangKeys.RBMK_BURN_LOGARITHMIC, "MEDIUM / LOGARITHMIC")
        add(LangKeys.RBMK_BURN_NEGATIVE_QUADRATIC, "DANGEROUS / NEGATIVE-QUADRATIC")
        add(LangKeys.RBMK_BURN_PASSIVE, "SAFE / PASSIVE")
        add(LangKeys.RBMK_BURN_QUADRATIC, "DANGEROUS / QUADRATIC")
        add(LangKeys.RBMK_BURN_SIGMOID, "SAFE / SIGMOID")
        add(LangKeys.RBMK_BURN_SINE_SLOPE, "EXPERIMENTAL / SINE SLOPE")
        add(LangKeys.RBMK_BURN_SQUARE_ROOT, "MEDIUM / SQUARE ROOT")
        add(LangKeys.RBMK_CONSOLE_ASSIGN, "Assign selected columns to screen #%d")
        add(LangKeys.RBMK_CONSOLE_DESELECT_CONTROL_RODS, "Deselect all")
        add(LangKeys.RBMK_CONSOLE_LINK, "RBMK 연결됨!")
        add(LangKeys.RBMK_CONSOLE_SELECT_CONTROL_RODS, "모든 제어봉 선택")
        add(LangKeys.RBMK_CONSOLE_SELECT_GROUP, "Select %s group")
        add(LangKeys.RBMK_CONTROL_GROUP_BLUE, "§1Blue Group")
        add(LangKeys.RBMK_CONTROL_GROUP_GREEN, "§aGreen Group")
        add(LangKeys.RBMK_CONTROL_GROUP_PURPLE, "§5Purple Group")
        add(LangKeys.RBMK_CONTROL_GROUP_RED, "§cRed Group")
        add(LangKeys.RBMK_CONTROL_GROUP_YELLOW, "§eYellow Group")
        add(LangKeys.RBMK_CONTROL_ROD_LEVEL, "%.1f%%")
        add(LangKeys.RBMK_HEAT, "Column Temperature: %.1f°C")
        add(LangKeys.RBMK_MODERATED, "Moderated")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE, "Draconic Flames")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE_GOLD, "Antihydrogen in a Magnetized Gold-198 Lattice")
        add(LangKeys.RBMK_NAME_PELLET_DRX, "§kcan't you hear, can't you hear the thunder?")
        add(LangKeys.RBMK_NAME_PELLET_FLASHLEAD, "Antihydrogen confined by a Magnetized Gold-198 and Lead-209 Lattice")
        add(LangKeys.RBMK_NAME_PELLET_HEA241, "고농축 아메리슘-241")
        add(LangKeys.RBMK_NAME_PELLET_HEA242, "고농축 아메리슘-242")
        add(LangKeys.RBMK_NAME_PELLET_HEAUS, "고농축 오스트레일륨 (Ayerite)")
        add(LangKeys.RBMK_NAME_PELLET_HEN, "고농축 넵투늄-237")
        add(LangKeys.RBMK_NAME_PELLET_HEP239, "고농축 플루토늄-239")
        add(LangKeys.RBMK_NAME_PELLET_HEP241, "고농축 플루토늄-241")
        add(LangKeys.RBMK_NAME_PELLET_HES, "고농축 스크라비듐-326")
        add(LangKeys.RBMK_NAME_PELLET_HEU233, "고농축 우라늄-233")
        add(LangKeys.RBMK_NAME_PELLET_HEU235, "고농축 우라늄-235")
        add(LangKeys.RBMK_NAME_PELLET_LEA, "저농축 아메리슘-242")
        add(LangKeys.RBMK_NAME_PELLET_LEAUS, "저농축 오스트레일륨 (Tasmanite)")
        add(LangKeys.RBMK_NAME_PELLET_LEP, "저농축 플루토늄-239")
        add(LangKeys.RBMK_NAME_PELLET_LES, "저농축 스크라비듐-326")
        add(LangKeys.RBMK_NAME_PELLET_MEA, "중농축 아메리슘-242")
        add(LangKeys.RBMK_NAME_PELLET_MEN, "중농축 넵투늄-237")
        add(LangKeys.RBMK_NAME_PELLET_MEP, "중농축 플루토늄-239")
        add(LangKeys.RBMK_NAME_PELLET_MES, "중농축 스크라비듐-326")
        add(LangKeys.RBMK_NAME_PELLET_MEU, "중농축 우라늄-235")
        add(LangKeys.RBMK_NAME_PELLET_MOX, "중농축 우라늄, 저농축 이산화 플루토늄 혼합물")
        add(LangKeys.RBMK_NAME_PELLET_PO210BE, "폴로늄-210 & 베릴륨 중성자원")
        add(LangKeys.RBMK_NAME_PELLET_PU238BE, "플루토늄-238 & 베릴륨 중성자원")
        add(LangKeys.RBMK_NAME_PELLET_RA226BE, "Radium-226 & 베릴륨 중성자원")
        add(LangKeys.RBMK_NAME_PELLET_THMEU, "토륨 with MEU Driver Fuel")
        add(LangKeys.RBMK_NAME_PELLET_UEU, "Unenriched 우라늄")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_AM_MIX, "Zirconium Fast Breeder - 고농축 플루토늄-241#MEA")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_BISMUTH, "Zirconium Fast Breeder - LEU/고농축 플루토늄-241#Bi")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_PU241, "Zirconium Fast Breeder - HEU-235/고농축 플루토늄-240#Pu-241")
        add(LangKeys.RBMK_NEUTRON_FAST, "Fast Neutrons")
        add(LangKeys.RBMK_NEUTRON_SLOW, "Slow Neutrons")
        add(LangKeys.RBMK_NEUTRON_ANY, "All Neutrons")
        add(LangKeys.RBMK_PELLET_DEPLETION_FULL, "Fully Depleted")
        add(LangKeys.RBMK_PELLET_DEPLETION_HIGH, "Highly Depleted")
        add(LangKeys.RBMK_PELLET_DEPLETION_MODERATE, "Moderately Depleted")
        add(LangKeys.RBMK_PELLET_DEPLETION_NEW, "Brand New")
        add(LangKeys.RBMK_PELLET_DEPLETION_SLIGHT, "Barely Depleted")
        add(LangKeys.RBMK_PELLET_XENON_POISONED, "High Xenon Poison")
        add(LangKeys.RBMK_PELLET_RECYCLE, "Pellet for recycling")
        add(LangKeys.RBMK_ROD_DEPLETION, "Depletion: %.3f%%")
        add(LangKeys.RBMK_ROD_DIFFUSION, "Diffusion: %s")
        add(LangKeys.RBMK_ROD_FLUX_FUNC, "Flux function: %s")
        add(LangKeys.RBMK_ROD_FUNC_TYPE, "Function type: %s")
        add(LangKeys.RBMK_ROD_HEAT, "Heat per flux: %s")
        add(LangKeys.RBMK_ROD_HEAT_CORE, "Core temp: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL, "Skin temp: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL_TO_MELTING_POINT, "Skin temp: %.1f°C / %.1f°C")
        add(LangKeys.RBMK_ROD_MELTING_POINT, "Melting point: %s")
        add(LangKeys.RBMK_ROD_SOURCE, "Self-igniting")
        add(LangKeys.RBMK_ROD_SPLITS_INTO, "Splits into: %s")
        add(LangKeys.RBMK_ROD_SPLITS_WITH, "Splits with: %s")
        add(LangKeys.RBMK_ROD_XENON, "Xenon poison: %.3f%%")
        add(LangKeys.RBMK_ROD_XENON_BURN, "Xenon burn function: %s")
        add(LangKeys.RBMK_ROD_XENON_GEN, "Xenon gen function: %s")
        add(LangKeys.RBMK_SCREEN_DEPLETION, "Depl: %.1f%%")
        add(LangKeys.RBMK_SCREEN_FUEL_TEMPERATURE, "Core: %.1f°C")
        add(LangKeys.RBMK_SCREEN_POISON, "Xenon: %.1f%%")
        add(LangKeys.RBMK_SCREEN_ROD_EXTRACTION, "Control: %.1f%%")
        add(LangKeys.RBMK_SCREEN_TEMPERATURE, "Temp: %.1f°C")
        add(LangKeys.RBMK_SCREEN_TYPE_COLUMN_TEMPERATURE, "Monitor average column temperature")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_DEPLETION, "Monitor average fuel depletion")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_POISON, "Monitor average xenon poisoning")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_TEMPERATURE, "Monitor average fuel temperature")
        add(LangKeys.RBMK_SCREEN_TYPE_NONE, "Off")
        add(LangKeys.RBMK_SCREEN_TYPE_ROD_EXTRACTION, "Monitor average control rod extraction")

        add(LangKeys.SIREN_TRACK_LOOP, "Type: Loop")
        add(LangKeys.SIREN_TRACK_ONCE, "Type: Play Once")
        add(LangKeys.SIREN_TRACK_RANGE, "Range: %s Meters")
        add(LangKeys.SIREN_TRACK_SIREN_TRACK, "Siren Track")

        add(LangKeys.SUBTITLE_ANVIL_FALL, "Anvil clashes")
        add(LangKeys.SUBTITLE_ASSEMBLER_OPERATE, "Assembler whirs")
        add(LangKeys.SUBTITLE_BLEEP, "Device bleeps")
        add(LangKeys.SUBTITLE_BLOCK_DEBRIS, "Debris hit the ground")
        add(LangKeys.SUBTITLE_BOOP, "Device boops")
        add(LangKeys.SUBTITLE_CENTRIFUGE_OPERATE, "Centrifuge hums")
        add(LangKeys.SUBTITLE_CHEM_PLANT_OPERATE, "Chemical Plant operates")
        add(LangKeys.SUBTITLE_GEIGER_CLICK, "Geiger Counter clicks")
        add(LangKeys.SUBTITLE_ITEM_INJECT, "Needle injected")
        add(LangKeys.SUBTITLE_ITEM_UNPACK, "Item unpacked")
        add(LangKeys.SUBTITLE_METEOR_IMPACT, "운석이 충돌함")
        add(LangKeys.SUBTITLE_MINI_NUKE_EXPLODE, "Mini nuke explodes")
        add(LangKeys.SUBTITLE_MISSILE_TAKEOFF, "Missile takes off")
        add(LangKeys.SUBTITLE_PRESS_OPERATE, "Press stamps")
        add(LangKeys.SUBTITLE_RBMK_AZ5_COVER, "AZ-3 lid opened")
        add(LangKeys.SUBTITLE_RBMK_EXPLODE, "RBMK explodes")
        add(LangKeys.SUBTITLE_RBMK_SHUTDOWN, "RBMK shutting down")
        add(LangKeys.SUBTITLE_SIREN_AIR_RAID, "사이렌 작동: Air Raid Siren")
        add(LangKeys.SUBTITLE_SIREN_AMS, "사이렌 작동: AMS Siren")
        add(LangKeys.SUBTITLE_SIREN_APC, "사이렌 작동: APC Siren")
        add(LangKeys.SUBTITLE_SIREN_APC_PASS, "사이렌 작동: APC Pass")
        add(LangKeys.SUBTITLE_SIREN_AUTOPILOT_DISCONNECTED, "사이렌 작동: Autopilot Disconnected")
        add(LangKeys.SUBTITLE_SIREN_BANK, "사이렌 작동: Bank Alarm")
        add(LangKeys.SUBTITLE_SIREN_BEEP, "사이렌 작동: Beep Siren")
        add(LangKeys.SUBTITLE_SIREN_BLAST_DOOR, "사이렌 작동: Blast Door Alarm")
        add(LangKeys.SUBTITLE_SIREN_CLASSIC, "사이렌 작동: Classic Siren")
        add(LangKeys.SUBTITLE_SIREN_CONTAINER, "사이렌 작동: Container Alarm")
        add(LangKeys.SUBTITLE_SIREN_EAS, "사이렌 작동: EAS Alarm Screech")
        add(LangKeys.SUBTITLE_SIREN_HATCH, "사이렌 작동: Hatch Siren")
        add(LangKeys.SUBTITLE_SIREN_KLAXON, "사이렌 작동: Klaxon")
        add(LangKeys.SUBTITLE_SIREN_MISSILE_SILO, "사이렌 작동: 미사일 Silo Siren")
        add(LangKeys.SUBTITLE_SIREN_NOSTROMO_SELF_DESTRUCT, "사이렌 작동: Nostromo Self Destruct")
        add(LangKeys.SUBTITLE_SIREN_RAZORTRAIN_HORN, "사이렌 작동: Razortrain Horn")
        add(LangKeys.SUBTITLE_SIREN_SECURITY, "사이렌 작동: Security Alert")
        add(LangKeys.SUBTITLE_SIREN_STANDARD, "사이렌 작동: Standard Siren")
        add(LangKeys.SUBTITLE_SIREN_SWEEP, "사이렌 작동: Sweep Siren")
        add(LangKeys.SUBTITLE_SIREN_VAULT_DOOR, "사이렌 작동: Vault Door Alarm")
        add(LangKeys.SUBTITLE_UPGRADE_INSTALL, "업그레이드가 설치됨")
        add(LangKeys.SUBTITLE_USE_RADAWAY, "Liquid infused")

        add(LangKeys.UPGRADE_INFO_ACCEPTED_UPGRADES, "적용 가능 업그레이드:")
        add(LangKeys.UPGRADE_INFO_BURN_GAS, "%smB 의 가스를 %s간 연소")
        add(LangKeys.UPGRADE_INFO_CONSUMPTION, "소모량: %s")
        add(LangKeys.UPGRADE_INFO_DELAY, "Delay: %s")
        add(LangKeys.UPGRADE_INFO_STACKS_TO, "Stacks to level %s")
        add(LangKeys.UPGRADE_NAME_AFTER_BURNER, "후기연소기")
        add(LangKeys.UPGRADE_NAME_OVERDRIVE, "과부하")
        add(LangKeys.UPGRADE_NAME_POWER_SAVING, "에너지 절약")
        add(LangKeys.UPGRADE_NAME_SPEED, "속도")
        add(LangKeys.UPGRADE_WARN_INCOMPATIBLE, "이 업그레이드는 호환되지 않습니다!")
        add(LangKeys.UPGRADE_WARN_MACHINE_NOT_UPGRADEABLE, "This machine is not upgradeable!")
        add(LangKeys.UPGRADE_WARN_NOT_A_MACHINE, "This is not a machine!")
        add(LangKeys.UPGRADE_WARN_VIEW_MACHINE, "View a machine for info about effects")
        add(LangKeys.UPGRADE_WARN_UNKNOWN_COMPATIBILITY, "Compatibility with the machine is unknown")

        add(LangKeys.VERSION_CHECKER_ANNOUNCEMENT, "-- NTM 버전 확인기 --")
        add(LangKeys.VERSION_CHECKER_BLEEDING_EDGE, "Running on the bleeding edge!")
        add(LangKeys.VERSION_CHECKER_CHANGES_LIST, "Short list of changes:")
        add(LangKeys.VERSION_CHECKER_CUTTING_EDGE, "Running on the cutting edge of beta!")
        add(LangKeys.VERSION_CHECKER_UPDATE, "NTM 새 버전이 나왔습니다!")
        add(LangKeys.VERSION_CHECKER_VIEW_RELEASES, "Click here to get to the releases page!")

        add(LangKeys.VOLCANO_EXTINGUISHING, "DOES EXTINGUISH")
        add(LangKeys.VOLCANO_GROWING, "DOES GROW")
        add(LangKeys.VOLCANO_NOT_EXTINGUISHING, "DOES NOT EXTINGUISH")
        add(LangKeys.VOLCANO_NOT_GROWING, "DOES NOT GROW")
        add(LangKeys.VOLCANO_SMOLDERING, "SHIELD VOLCANO")

        add(LangKeys.WORD_SECONDS, "Seconds")
    }

    private fun addMaterials() = with(Materials) {
        addMaterial(coal, "석탄")
        addMaterial(iron, "철")
        addMaterial(copper, "구리")
        addMaterial(gold, "금")
        addMaterial(redstone, "레드스톤")
        addMaterial(emerald, "에메랄드")
        addMaterial(lazuli, "청금석")
        addMaterial(diamond, "다이아몬드")

        addMaterial(actinium227, "악티늄-227")
        addMaterial(advancedAlloy, "고급 합금")
        addMaterial(aluminium, "알루미늄")
        addMaterial(americium241, "아메리슘-241")
        addMaterial(americium242, "아메리슘-242")
        addMaterial(americiumFuel, "아메리슘 연료")
        addMaterial(arsenic, "비소")
        addMaterial(asbestos, "석면")
        addMaterial(australium, "오스트레일륨")
        addMaterial(bakelite, "베이클라이트")
        addMaterial(beryllium, "베릴륨")
        addMaterial(bismuth, "비스무트")
        addMaterial(boron, "Boron")
        addMaterial(cobalt, "코발트")
        addMaterial(cobalt60, "코발트-60")
        addMaterial(combineSteel, "콤바인 강철")
        addMaterial(daffergon, "Daffergon")
        addMaterial(desh, "Desh")
        addMaterial(dineutronium, "Dineutronium")
        addMaterial(electronium, "Electronium")
        addMaterial(euphemium, "유페뮴")
        addMaterial(ferricSchrabidate, "Ferric Schrabidate")
        addMaterial(fiberglass, "Fiberglass")
        addMaterial(fluorite, "형석")
        addMaterial(ghiorsium336, "Ghiorsium-336")
        addMaterial(gold198, "Gold-198")
        addMaterial(graphite, "흑연")
        addMaterial(hesFuel, "고농축 스크라비듐 연료")
        addMaterial(highSpeedSteel, "High-Speed Steel")
        addMaterial(insulator, "절연체")
        addMaterial(lanthanum, "란타넘")
        addMaterial(lead, "납")
        addMaterial(lead209, "납-209")
        addMaterial(lesFuel, "저농축 스크라비듐 연료")
        addMaterial(lignite, "갈탄")
        addMaterial(lithium, "리튬")
        addMaterial(magnetizedTungsten, "자기화 텅스텐")
        addMaterial(moxFuel, "혼합 산화물 연료")
        addMaterial(naturalPlutonium, "플루토늄")
        addMaterial(naturalUranium, "우라늄")
        addMaterial(neptunium, "넵튜늄")
        addMaterial(neptuniumFuel, "넵튜늄 연료")
        addMaterial(niobium, "나이오븀")
        addMaterial(niter, "초석")
        addMaterial(nuclearWaste, "핵 폐기물")
        addMaterial(osmiridium, "Osmiridium")
        addMaterial(plutonium238, "플루토늄-238")
        addMaterial(plutonium239, "플루토늄-239")
        addMaterial(plutonium240, "플루토늄-240")
        addMaterial(plutonium241, "플루토늄-241")
        addMaterial(plutoniumFuel, "플루토늄 연료")
        addMaterial(polonium, "폴로늄")
        addMaterial(polymer, "Polymer")
        addMaterial(radium226, "Radium-226")
        addMaterial(reactorGradeAmericium, "Reactor Grade 아메리슘")
        addMaterial(reactorGradePlutonium, "Reactor Grade 플루토늄")
        addMaterial(redCopper, "붉은 구리")
        addMaterial(redPhosphorus, "적린")
        addMaterial(reiium, "Reiium")
        addMaterial(rubber, "Rubber")
        addMaterial(saturnite, "Saturnite")
        addMaterial(schrabidium, "스크라비듐")
        addMaterial(schrabidiumFuel, "스크라비듐 연료")
        addMaterial(schraranium, "Schraranium")
        addMaterial(solinium, "Solinium")
        addMaterial(starmetal, "Starmetal")
        addMaterial(steel, "강철")
        addMaterial(strontium90, "Strontium-90")
        addMaterial(sulfur, "황")
        addMaterial(tantalium, "Tantalium")
        addMaterial(technetium99, "테크네튬-99")
        addMaterial(technetiumSteel, "테크네튬 강철")
        addMaterial(thorium, "토륨-232")
        addMaterial(thoriumFuel, "토륨 연료")
        addMaterial(titanium, "티타늄")
        addMaterial(trinitite, "트리니타이트")
        addMaterial(tungsten, "텅스텐")
        addMaterial(unobtainium, "언옵테이늄")
        addMaterial(uranium233, "우라늄-233")
        addMaterial(uranium235, "우라늄-235")
        addMaterial(uranium238, "우라늄-238")
        addMaterial(uraniumFuel, "우라늄 연료")
        addMaterial(verticium, "버티슘")
        addMaterial(weidanium, "웨이다늄")
        addMaterial(whitePhosphorus, "백린")
        addMaterial(yellowcake, "우라늄정광")
    }

    override val spawnEggFormat = "%s 생정 알"

    override val oreFormat = "%s 광석"
    override val deepOreFormat = "심층암 %s 광석"
    override val blockFormat = "%s 블록"
    override val rawFormat = "%s 원석"
    override val ingotFormat = "%s 주괴"
    override val billetFormat = "%s 동전"
    override val nuggetFormat = "%s 조각"
    override val crystalsFormat = "%s 결정"
    override val powderFormat = "%s 가루"
    override val plateFormat = "%s 판"
    override val wireFormat = "%s 전선"
}
