package at.martinthedragon.nucleartech.datagen.localisation

import at.martinthedragon.nucleartech.CreativeTabs
import at.martinthedragon.nucleartech.LangKeys
import at.martinthedragon.nucleartech.Materials
import at.martinthedragon.nucleartech.TranslationKey
import at.martinthedragon.nucleartech.block.NTechBlocks
import at.martinthedragon.nucleartech.datagen.NuclearLanguageProviders
import at.martinthedragon.nucleartech.entity.EntityTypes
import at.martinthedragon.nucleartech.entity.attribute.Attributes
import at.martinthedragon.nucleartech.fluid.NTechFluids
import at.martinthedragon.nucleartech.fluid.trait.NTechFluidTraits
import at.martinthedragon.nucleartech.item.NTechItems
import at.martinthedragon.nucleartech.menu.MenuTypes
import at.martinthedragon.nucleartech.world.DamageSources
import net.minecraft.data.DataGenerator

class KoKrLanguageProvider(dataGenerator: DataGenerator) : NuclearLanguageProvider(dataGenerator, NuclearLanguageProviders.KO_KR) {
    override fun validate() {
        val additionalLangKeys = LangKeys.javaClass.declaredFields.mapNotNull { it.trySetAccessible(); it.get(LangKeys) as? String }.filter(TranslationKey::isValidKey)
        if (!translations.keys.containsAll(additionalLangKeys)) {
            val missingLangKeys = additionalLangKeys subtract translations.keys
            val errorMessage = StringBuilder().appendLine("다음 LangKeys의 추가 번역 키가 번역 정의에 포함되지 않았습니다:")
            for (missing in missingLangKeys) errorMessage.appendLine(missing.prependIndent())
            throw IllegalStateException(errorMessage.toString())
        }

        NuclearLanguageProviders.keys = translations.keys.toSet()
        NuclearLanguageProviders.materialTranslations = materialTranslations.toMap()
    }

    override fun translate() {
        addCreativeTab(CreativeTabs.Parts, "NTM 자원과 부품들")
        addCreativeTab(CreativeTabs.Items, "NTM 기계 아이템과 연료")
        addCreativeTab(CreativeTabs.Templates, "NTM 설계도")
        addCreativeTab(CreativeTabs.Blocks, "NTM 광물과 블럭들")
        addCreativeTab(CreativeTabs.Machines, "NTM 기계들")
        addCreativeTab(CreativeTabs.Bombs, "NTM 폭탄들")
        addCreativeTab(CreativeTabs.Rocketry, "NTM 미사일과 위성들")
        addCreativeTab(CreativeTabs.Consumables, "NTM 소모품과 장비들")
        addCreativeTab(CreativeTabs.Miscellaneous, "NTM 기타 아이템들")

        addMaterials()

        addBlock(NTechBlocks.scorchedUraniumOre, "불탄 우라늄 광석")
        addBlock(NTechBlocks.thoriumOre, "토륨 광석")
        addBlock(NTechBlocks.oilDeposit, "원유 매장지")
        addBlockDesc(NTechBlocks.oilDeposit, "그건 채굴하면 안 되는데요.\n자, 가서 유정탑이나 만들어 오세요.")
        addBlock(NTechBlocks.emptyOilDeposit, "빈 원유 매장지")
        addBlock(NTechBlocks.oilSand, "오일샌드")
        addBlock(NTechBlocks.australianOre, "오스트레일리안 광석")
        addBlockDesc(NTechBlocks.australianOre, "오스트레일륨 광석")
        addBlock(NTechBlocks.weidite, "웨이다이트")
        addBlockDesc(NTechBlocks.weidite, "웨이다늄 광석")
        addBlock(NTechBlocks.reiite, "레이아이트")
        addBlockDesc(NTechBlocks.reiite, "레이움 광석")
        addBlock(NTechBlocks.brightblendeOre, "브라이트블렌드 광석")
        addBlockDesc(NTechBlocks.brightblendeOre, "언옵테이늄 광석")
        addBlock(NTechBlocks.dellite, "델라이트")
        addBlockDesc(NTechBlocks.dellite, "다퍼곤 광석")
        addBlock(NTechBlocks.dollarGreenMineral, "달러 그린 미네랄")
        addBlockDesc(NTechBlocks.dollarGreenMineral, "버티슘 광석")
        addBlock(NTechBlocks.rareEarthOre, "희토류 광석")
        addBlock(NTechBlocks.netherUraniumOre, "네더 우라늄 광석")
        addBlock(NTechBlocks.scorchedNetherUraniumOre, "불탄 네더 우라늄 광석")
        addBlock(NTechBlocks.netherPlutoniumOre, "네더 플루토늄 광석")
        addBlock(NTechBlocks.netherTungstenOre, "네더 텅스텐 광석")
        addBlock(NTechBlocks.netherSulfurOre, "네더 황 광석")
        addBlock(NTechBlocks.netherPhosphorusOre, "네더 인 광석")
        addBlock(NTechBlocks.netherSchrabidiumOre, "네더 스크라비듐 광석")
        addBlock(NTechBlocks.meteorUraniumOre, "운석 우라늄 광석")
        addBlock(NTechBlocks.meteorThoriumOre, "운석 토륨 광석")
        addBlock(NTechBlocks.meteorTitaniumOre, "운석 티타늄 광석")
        addBlock(NTechBlocks.meteorSulfurOre, "운석 황 광석")
        addBlock(NTechBlocks.meteorCopperOre, "운석 구리 광석")
        addBlock(NTechBlocks.meteorTungstenOre, "운석 텅스텐 광석")
        addBlock(NTechBlocks.meteorAluminiumOre, "운석 알루미늄 광석")
        addBlock(NTechBlocks.meteorLeadOre, "운석 납 광석")
        addBlock(NTechBlocks.meteorLithiumOre, "운석 리튬 광석")
        addBlock(NTechBlocks.starmetalOre, "스타메탈 광석")
        addBlock(NTechBlocks.trixite, "트라이사이트 ")
        addBlock(NTechBlocks.basaltSulfurOre, "황이 풍부한 현무암")
        addBlock(NTechBlocks.basaltFluoriteOre, "형석이 풍부한 현무암")
        addBlock(NTechBlocks.basaltAsbestosOre, "석면이 풍부한 현무암")
        addBlock(NTechBlocks.basaltVolcanicGemOre, "보석이 풍부한 현무암")

        addBlock(NTechBlocks.scorchedDeepslateUraniumOre, "불탄 심층암 우라늄 광석")
        addBlock(NTechBlocks.deepslateOilDeposit, "심층암 원유 매장지")
        addBlockDesc(NTechBlocks.deepslateOilDeposit, "이렇게 깊이까지 파들어오고도\n뭘 어떻게 해야 할지 모른다고? 어떻게?!")
        addBlock(NTechBlocks.emptyDeepslateOilDeposit, "빈 심층암 원유 매장지")
        addBlock(NTechBlocks.deepslateAustralianOre, "심층암 오스트레일리안 광석")
        addBlockDesc(NTechBlocks.deepslateAustralianOre, "오스트레일륨 광석")
        addBlock(NTechBlocks.deepslateRareEarthOre, "심층암 희토류 광석")

        addBlock(NTechBlocks.whitePhosphorusBlock, "백린 블록")
        addBlock(NTechBlocks.redPhosphorusBlock, "적린 블록")
        addBlock(NTechBlocks.yellowcakeBlock, "우라늄정광 블록")
        addBlock(NTechBlocks.scrapBlock, "폐기물 블록")
        addBlock(NTechBlocks.electricalScrapBlock, "전자 폐기물 블록")
        addBlock(NTechBlocks.insulatorRoll, "절연체 말이")
        addBlock(NTechBlocks.fiberglassRoll, "유리섬유 말이")
        addBlock(NTechBlocks.trinititeBlock, "트리니타이트 블록")
        addBlock(NTechBlocks.nuclearWasteBlock, "핵 폐기물 블록")
        addBlock(NTechBlocks.schrabidiumCluster, "스크라비듐 덩어리 블록")
        addBlock(NTechBlocks.euphemiumEtchedSchrabidiumCluster, "유페뮴이 새겨진 스크라비듐 덩어리 블록")
        addBlock(NTechBlocks.deshReinforcedBlock, "강화된 데쉬 블록")

        addBlock(NTechBlocks.titaniumDecoBlock, "티타늄 장식 블록")
        addBlock(NTechBlocks.redCopperDecoBlock, "붉은 구리 장식 블록")
        addBlock(NTechBlocks.tungstenDecoBlock, "텅스텐 장식 블록")
        addBlock(NTechBlocks.aluminiumDecoBlock, "알루미늄 장식 블록")
        addBlock(NTechBlocks.steelDecoBlock, "강철 장식 블록")
        addBlock(NTechBlocks.leadDecoBlock, "납 장식 블록")
        addBlock(NTechBlocks.berylliumDecoBlock, "베릴륨 장식 블록")
        addBlock(NTechBlocks.asbestosRoof, "석면 지붕")
        addBlock(NTechBlocks.hazmatBlock, "방호 블록")
        addBlock(NTechBlocks.meteorite, "운석")
        addBlock(NTechBlocks.meteoriteCobblestone, "운석 조약돌")
        addBlock(NTechBlocks.brokenMeteorite, "부서진 운석")
        addBlock(NTechBlocks.hotMeteoriteCobblestone, "뜨거운 운석 조약돌")
        addBlock(NTechBlocks.meteoriteTreasure, "운석 보물")
        addBlock(NTechBlocks.steelBeam, "강철 빔")
        addBlock(NTechBlocks.steelScaffold, "강철 비계")
        addBlock(NTechBlocks.steelGrate, "강철 상자")

        addBlock(NTechBlocks.glowingMushroom, "빛나는 버섯")
        addBlock(NTechBlocks.glowingMushroomBlock, "빛나는 버섯 블록")
        addBlock(NTechBlocks.glowingMushroomStem, "빛나는 버섯 줄기")
        addBlock(NTechBlocks.deadGrass, "죽은 잔디")
        addBlock(NTechBlocks.glowingMycelium, "빛나는 균사체")
        addBlock(NTechBlocks.trinitite, "트리니타이트 광석")
        addBlock(NTechBlocks.redTrinitite, "붉은 트리니타이트 광석")
        addBlock(NTechBlocks.charredLog, "탄화된 나무")
        addBlock(NTechBlocks.charredPlanks, "탄화된 나무판자")

        addBlock(NTechBlocks.slakedSellafite, "식은 셀라파이트")
        addBlock(NTechBlocks.sellafite, "셀라파이트")
        addBlock(NTechBlocks.hotSellafite, "뜨거운 셀라파이트")
        addBlock(NTechBlocks.boilingSellafite, "끓는 셀라파이트")
        addBlock(NTechBlocks.blazingSellafite, "녹아내리는 셀라파이트")
        addBlock(NTechBlocks.infernalSellafite, "불타는 셀라파이트")
        addBlock(NTechBlocks.sellafiteCorium, "셀라파이트-용융물")

        addBlock(NTechBlocks.corium, "노심용융물")
        addBlock(NTechBlocks.corebblestone, "노심용융물 조약돌")

        addBlock(NTechBlocks.siren, "사이렌")
        addBlock(NTechBlocks.safe, "금고")
        addBlock(NTechBlocks.steamPressBase, "증기 압착기")
        addBlock(NTechBlocks.steamPressFrame, "증기 압착기")
        addBlock(NTechBlocks.steamPressTop, "증기 압착기")
        addBlock(NTechBlocks.blastFurnace, "용광로")
        addBlock(NTechBlocks.combustionGenerator, "연소 발전기")
        addBlock(NTechBlocks.electricFurnace, "전기로")
        addBlock(NTechBlocks.shredder, "분쇄기")
        addBlock(NTechBlocks.assembler, "조립기")
        addBlock(NTechBlocks.chemPlant, "화학 공장")
        addBlock(NTechBlocks.turbine, "증기 터빈")
        addBlock(NTechBlocks.smallCoolingTower, "외부 냉각탑")
        addBlock(NTechBlocks.largeCoolingTower, "냉각탑")
        addBlockDesc(NTechBlocks.turbine, "효율: 85%")
        addBlock(NTechBlocks.oilDerrick, "정유탑")
        addBlock(NTechBlocks.pumpjack, "펌프잭")
        addBlockDesc11(NTechBlocks.pumpjack, "ㄹㅇ 모기")
        addBlock(NTechBlocks.centrifuge, "원심분리기")
        addBlock(NTechBlocks.ironAnvil, "철 모루")
        addBlock(NTechBlocks.leadAnvil, "납 모루")
        addBlock(NTechBlocks.steelAnvil, "강철 모루")
        addBlock(NTechBlocks.meteoriteAnvil, "운석 모루")
        addBlock(NTechBlocks.starmetalAnvil, "스타메탈 모루")
        addBlock(NTechBlocks.ferrouraniumAnvil, "우라늄철합금 모루")
        addBlock(NTechBlocks.bismuthAnvil, "비스무트 모루")
        addBlock(NTechBlocks.schrabidateAnvil, "철-스크라비듐 모루")
        addBlock(NTechBlocks.dineutroniumAnvil, "다이뉴트론 모루")
        addBlock(NTechBlocks.murkyAnvil, "흐린 모루")

        addBlock(NTechBlocks.decoRbmkBlock, "RBMK 장식 블록")
        addBlock(NTechBlocks.decoRbmkSmoothBlock, "부드러운 RBMK 장식 블록")

        addBlock(NTechBlocks.rbmkColumn, "RBMK Column Part")
        addBlock(NTechBlocks.rbmkRod, "RBMK 연료봉")
        addBlock(NTechBlocks.rbmkModeratedRod, "RBMK 감속 연료봉")
        addBlock(NTechBlocks.rbmkReaSimRod, "RBMK 연료봉 (ReaSim)")
        addBlock(NTechBlocks.rbmkModeratedReaSimRod, "RBMK 감속 연료봉 (ReaSim)")
        addBlock(NTechBlocks.rbmkReflector, "RBMK 텅스텐 카바이드 중성자 반사체")
        addBlock(NTechBlocks.rbmkModerator, "RBMK 흑연 감속재")
        addBlock(NTechBlocks.rbmkAbsorber, "RBMK 붕소 중성자 흡수재")
        addBlock(NTechBlocks.rbmkBoilerColumn, "RBMK 증기 채널 부품")
        addBlock(NTechBlocks.rbmkBoiler, "RBMK 증기 채널")
        addBlock(NTechBlocks.rbmkBlank, "RBMK 구조물 기중")
        addBlock(NTechBlocks.rbmkManualControlRod, "RBMK 제어봉")
        addBlock(NTechBlocks.rbmkModeratedControlRod, "RBMK 감속 제어봉")
        addBlock(NTechBlocks.rbmkAutoControlRod, "RBMK 자동 제어봉")
        addBlock(NTechBlocks.rbmkSteamConnector, "RBMK 증기 연결기")
        addBlock(NTechBlocks.rbmkInlet, "RBMK ReaSim 급수구")
        addBlock(NTechBlocks.rbmkOutlet, "RBMK ReaSim 증기 배출구")
        addBlock(NTechBlocks.rbmkConsole, "RBMK 제어기")
        addBlock(NTechBlocks.rbmkDebris, "RBMK 파편")
        addBlock(NTechBlocks.rbmkBurningDebris, "불타는 RBMK 파편")
        addBlock(NTechBlocks.rbmkRadioactiveDebris, "연기나는 RBMK 파편")

        addBlock(NTechBlocks.coatedCable, "코팅된 붉은 구리 케이블")
        addBlock(NTechBlocks.coatedUniversalFluidDuct, "코팅된 범용 유체 파이프")

        addBlock(NTechBlocks.littleBoy, "리틀 보이")
        addBlock(NTechBlocks.fatMan, "팻 맨")
        addBlock(NTechBlocks.volcanoCore, "화산 핵")

        addBlock(NTechBlocks.launchPad, "미사일 발사대")
        addBlock(NTechBlocks.launchPadPart, "미사일 발사대")

        addBlock(NTechBlocks.genericMultiBlockPart, "멀티블록 구조물 부품")
        addBlock(NTechBlocks.genericMultiBlockPort, "멀티블록 구조물 포트")
        addBlock(NTechBlocks.oilPipe, "기름 파이프")

        addBlock(NTechFluids.spentSteam.block, "저압 증기")
        addBlock(NTechFluids.steam.block, "증기")
        addBlock(NTechFluids.steamHot.block, "고압 증기")
        addBlock(NTechFluids.steamSuperHot.block, "초고압 증기")
        addBlock(NTechFluids.steamUltraHot.block, "극초고압 증기")
        addBlock(NTechFluids.oil.block, "원유")
        addBlock(NTechFluids.gas.block, "천연가스")
        addBlock(NTechFluids.uraniumHexafluoride.block, "육불화우라늄")
        addBlock(NTechFluids.corium.block, "노심용융물")
        addBlock(NTechFluids.volcanicLava.block, "화산 용암")

        addItem(NTechItems.rawThorium, "토륨 원석")
        addItem(NTechItems.rawRareEarth, "희토류 원석")
        addItem(NTechItems.rawTrixite, "트라이사이트 원석")

        addItemDesc(NTechItems.neptuniumIngot, "내가 좋아하는 것 중 하나잖아!")
        addItemDesc(NTechItems.tantaliumIngot, "'탄탈럼'")
        addItemDesc(NTechItems.tantaliumNugget, "'탄탈럼'")
        addItemDesc(NTechItems.schraraniumIngot, "스크라비듐 변환기에서 우라늄으로 만듭니다.")
        addItemDesc(NTechItems.combineSteelIngot, "*대충 시민 보호 기동대 패러디*")
        addItemDesc(NTechItems.ghiorsium336Ingot, "시보귬의 동지.")
        addItemDesc(NTechItems.ghiorsium336Nugget, "시보귬의 동지.")
        addItem(NTechItems.lanthanumIngot, "반쯤 안정적인 란타넘 주괴")
        addItemDesc(NTechItems.euphemiumIngot, "정말 특별하고도 이상한 물질")
        addItem(NTechItems.whitePhosphorusIngot, "백린 막대")

        addItem(NTechItems.semtexBar, "셈텍스 막대")
        addItemDesc(
            NTechItems.semtexBar,
            "셈텍스 H 플라스틱 폭발물\n" +
                    "사용처가 많은 성능 좋은 폭발물.\n" +
                    "식용 가능"
        )

        addItem(NTechItems.lithiumCube, "리튬 큐브")
        addItem(NTechItems.solidFuelCube, "고체 연료 큐브")
        addItem(NTechItems.solidRocketFuelCube, "고체 로켓 연료 큐브")

        addItem(NTechItems.fiberglassSheet, "유리섬유 판")
        addItemDesc(NTechItems.fiberglassSheet, "섬유 많이, 유리 많이. 몸에 필요한 건 다 있어요.")
        addItem(NTechItems.asbestosSheet, "석면 판")
        addItemDesc(NTechItems.asbestosSheet, "§o„생명, 자괴감, 석면으로 가득 차있어요. 산소도 같이 드립니다.“")

        addItem(NTechItems.lesserAustraliumBillet, "작은 오스트레일륨 동전")
        addItem(NTechItems.greaterAustraliumBillet, "큰 오스트레일륨 동전")
        addItem(NTechItems.po210BeBillet, "Po210Be 동전")
        addItem(NTechItems.ra226BeBillet, "Ra226Be 동전")
        addItem(NTechItems.pu238BeBillet, "Pu238Be 동전")
        addItem(NTechItems.zirconiumBillet, "지르코늄 동전")
        addItem(NTechItems.bismuthZfbBillet, "비스무트 ZFB 동전")
        addItem(NTechItems.pu241ZfbBillet, "플루토늄-241 ZFB 동전")
        addItem(NTechItems.reactorGradeAmericiumZfbBillet, "원자로급 아메리슘 ZFB 동전")
        addItem(NTechItems.yharoniteBillet, "Yharonite 동전")
        addItem(NTechItems.flashgoldBillet, "Flashgold 동전")
        addItem(NTechItems.flashleadBillet, "Flashlead 동전")
        addItemDesc(NTechItems.flashleadBillet, "The lattice decays, causing antimatter-matter\nannihilation reactions, causing the release of\npions, decaying into muons, catalyzing fusion of\nthe nuclei, creating the new element.\nPlease try to keep up.")

        addItem(NTechItems.mercuryDroplet, "수은 방울")
        addItem(NTechItems.mercuryBottle, "수은 병")

        addItem(NTechItems.coke, "코크스")
        addItem(NTechItems.lignite, "갈탄")
        addItem(NTechItems.ligniteBriquette, "갈탄 조개탄")

        addItem(NTechItems.sulfur, "황")
        addItem(NTechItems.niter, "초석")
        addItem(NTechItems.fluorite, "형석")
        addItem(NTechItems.quartzPowder, "석영 가루")
        addItem(NTechItems.yellowcake, "우라늄정광")
        addItem(NTechItems.chlorophytePowder, "녹조류 가루")
        addItem(NTechItems.neodymiumPowder, "네오디뮴 가루")
        addItem(NTechItems.niobiumPowder, "나이오븀 가루")
        addItem(NTechItems.ceriumPowder, "세륨 가루")
        addItemDesc(NTechItems.asbestosPowder, "§o„스으으으읍 - 으흐으으음...“")
        addItem(NTechItems.enchantmentPowder, "마법 가루")
        addItem(NTechItems.cloudResidue, "Cloud Residue")
        addItem(NTechItems.thermonuclearAshes, "Thermonuclear Ashes")
        addItem(NTechItems.semtexMix, "셈텍스 혼합물")
        addItem(NTechItems.deshMix, "데쉬 혼합물")
        addItem(NTechItems.deshReadyMix, "데쉬레디™ 혼합물")
        addItem(NTechItems.nitaniumMix, "Nitanium 혼합물")
        addItem(NTechItems.sparkMix, "Spark 혼합물")
        addItem(NTechItems.meteoritePowder, "운석 가루")
        addItemDesc(NTechItems.euphemiumPowder, "분쇄된 분홍색 가루.\n딸기맛이 납니다.")
        addItem(NTechItems.desaturatedRedstone, "탈포화 레드스톤")
        addItem(NTechItems.dust, "먼지")
        addItemDesc(NTechItems.dust, "난 먼지가 싫어!")
        addItem(NTechItems.tinyLithiumPowder, "작은 리튬 가루")
        addItem(NTechItems.tinyNeodymiumPowder, "작은 네오디뮴 가루")
        addItem(NTechItems.tinyCobaltPowder, "작은 코발트 가루")
        addItem(NTechItems.tinyNiobiumPowder, "작은 나이오븀 가루")
        addItem(NTechItems.tinyCeriumPowder, "작은 세륨 가루")
        addItem(NTechItems.tinyLanthanumPowder, "작은 란타넘 가루")
        addItem(NTechItems.tinyActiniumPowder, "작은 악티늄 가루")
        addItem(NTechItems.tinyMeteoritePowder, "작은 운석 가루")
        addItem(NTechItems.redPhosphorus, "적린")
        addItemDesc(NTechItems.redPhosphorus, "다용도 폭탄에서 사용됩니다:\n소이폭탄은 재밌어!")
        addItem(NTechItems.cryoPowder, "냉매 가루")
        addItem(NTechItems.poisonPowder, "독 가루")
        addItemDesc(NTechItems.poisonPowder, "다용도 폭탄에서 사용됩니다:\n경고: 독극물!")
        addItem(NTechItems.thermite, "테르밋")
        addItem(NTechItems.energyPowder, "에너지 가루")

        addItem(NTechItems.cordite, "코다이트")
        addItem(NTechItems.ballistite, "발리스타이트")

        addItem(NTechItems.rareEarthCrystals, "희토류 결정")
        addItem(NTechItems.redPhosphorusCrystals, "적린 결정")
        addItem(NTechItems.trixiteCrystals, "트라이사이트 결정")

        addItem(NTechItems.volcanicGem, "화산 보석")

        addItem(NTechItems.neodymiumFragment, "네오디뮴 파편")
        addItem(NTechItems.cobaltFragment, "코발트 파편")
        addItem(NTechItems.niobiumFragment, "나이오븀 파편")
        addItem(NTechItems.ceriumFragment, "세륨 파편")
        addItem(NTechItems.lanthanumFragment, "란타넘 파편")
        addItem(NTechItems.actiniumFragment, "악티늄 파편")
        addItem(NTechItems.meteoriteFragment, "운석 파편")

        addItem(NTechItems.biomass, "바이오매스")
        addItem(NTechItems.compressedBiomass, "압축 바이오매스")

        addItemDesc(
            NTechItems.euphemiumNugget,
            "작은 분홍색 금속 조각.\n" +
                    "성질은 아직 불명입니다,\n" +
                    "조심히 다뤄 줘요."
        )

        addItem(NTechItems.neutronReflector, "중성자 반사체")
        addItem(NTechItems.mixedPlate, "Mixed Plate")
        addItem(NTechItems.paAAlloyPlate, "PaA Alloy Plate")
        addItem(NTechItems.insulator, "절연체")
        addItem(NTechItems.kevlarCeramicCompound, "케블라-세라믹 화합물")
        addItem(NTechItems.dalekaniumPlate, "화난 금속")
        addItem(NTechItems.deshCompoundPlate, "데쉬 화합물 판")
        addItem(NTechItems.euphemiumCompoundPlate, "유페뮴 화합물 판")
        addItem(NTechItems.dineutroniumCompoundPlate, "다이뉴트로늄 화합물 판")
        addItem(NTechItems.copperPanel, "구리 Panel")

        addItem(NTechItems.highSpeedSteelBolt, "High-Speed 강철 Bolt")
        addItem(NTechItems.tungstenBolt, "텅스텐 Bolt")
        addItem(NTechItems.reinforcedTurbineShaft, "강화된 Turbine Shaft")

        addItem(NTechItems.hazmatCloth, "방호 천")
        addItem(NTechItems.advancedHazmatCloth, "Advanced 방호 천")
        addItem(NTechItems.leadReinforcedHazmatCloth, "Lead-강화된 방호 천")
        addItem(NTechItems.fireProximityCloth, "Fire Proximity Cloth")
        addItem(NTechItems.activatedCarbonFilter, "Activated Carbon Filter")

        addItem(NTechItems.superConductor, "Super Conductor")
        addItem(NTechItems.highTemperatureSuperConductor, "4000K High Temperature Super Conductor")

        addItem(NTechItems.copperCoil, "구리 Coil")
        addItem(NTechItems.ringCoil, "Ring Coil")
        addItem(NTechItems.superConductingCoil, "Super Conducting Coil")
        addItem(NTechItems.superConductingRingCoil, "Super Conducting Ring Coil")
        addItem(NTechItems.goldCoil, "Gold Coil")
        addItem(NTechItems.goldRingCoil, "Gold Ring Coil")
        addItem(NTechItems.heatingCoil, "Heating Coil")
        addItem(NTechItems.highTemperatureSuperConductingCoil, "4000K High Temperature Super Conducting Coil")

        addItem(NTechItems.steelTank, "강철 Tank")
        addItem(NTechItems.motor, "Motor")
        addItem(NTechItems.centrifugeElement, "Centrifuge Element")
        addItem(NTechItems.centrifugeTower, "Centrifuge Tower")
        addItem(NTechItems.deeMagnets, "Dee Magnets")
        addItem(NTechItems.flatMagnet, "Flat Magnet")
        addItem(NTechItems.cyclotronTower, "Cyclotron Tower")
        addItem(NTechItems.breedingReactorCore, "Breeding Reactor Core")
        addItem(NTechItems.rtgUnit, "RTG Unit")
        addItem(NTechItems.thermalDistributionUnit, "Thermal Distribution Unit")
        addItem(NTechItems.endothermicDistributionUnit, "Endothermic Distribution Unit")
        addItem(NTechItems.exothermicDistributionUnit, "Exothermic Distribution Unit")
        addItem(NTechItems.gravityManipulator, "Gravity Manipulator")
        addItem(NTechItems.steelPipes, "강철 Pipes")
        addItem(NTechItems.titaniumDrill, "티타늄 Drill")
        addItem(NTechItems.photovoltaicPanel, "Photovoltaic Panel")
        addItem(NTechItems.chlorinePinwheel, "Chlorine Pinwheel")
        addItem(NTechItems.telepad, "Telepad")
        addItem(NTechItems.entanglementKit, "Entaglement Kit")
        addItemDesc(
            NTechItems.entanglementKit,
            "Teleporter crafting item.\n" +
                    "Enables dimension-shifting via\n" +
                    "beryllium-enhanced resource scanner."
        )
        addItem(NTechItems.stabilizerComponent, "Stabilizer Component")
        addItem(NTechItems.emitterComponent, "Emitter Component")
        addItem(NTechItems.aluminiumCap, "알루미늄 Cap")
        addItem(NTechItems.smallSteelShell, "Small 강철 Shell")
        addItem(NTechItems.smallAluminiumShell, "Small 알루미늄 Shell")
        addItem(NTechItems.bigSteelShell, "Big 강철 Shell")
        addItem(NTechItems.bigAluminiumShell, "Big 알루미늄 Shell")
        addItem(NTechItems.bigTitaniumShell, "Big 티타늄 Shell")
        addItem(NTechItems.flatSteelCasing, "Flat 강철 Casing")
        addItem(NTechItems.smallSteelGridFins, "Small 강철 Grid Fins")
        addItem(NTechItems.bigSteelGridFins, "Big 강철 Grid Fins")
        addItem(NTechItems.largeSteelFins, "Large 강철 Fins")
        addItem(NTechItems.smallTitaniumFins, "Small 티타늄 Fins")
        addItem(NTechItems.steelSphere, "강철 Sphere")
        addItem(NTechItems.steelPedestal, "강철 Pedestal")
        addItem(NTechItems.dysfunctionalNuclearReactor, "Dysfunctional Nuclear Reactor")
        addItem(NTechItems.largeSteelRotor, "Large 강철 Rotor")
        addItem(NTechItems.generatorBody, "Generator Body")
        addItem(NTechItems.titaniumBlade, "티타늄 Blade")
        addItem(NTechItems.tungstenReinforcedBlade, "텅스텐 강화된 Blade")
        addItem(NTechItems.titaniumSteamTurbine, "티타늄 Steam Turbine")
        addItem(NTechItems.reinforcedTurbofanBlades, "강화된 Turbofan Blades")
        addItem(NTechItems.generatorFront, "Generator Front")
        addItem(NTechItems.toothpicks, "Toothpicks")
        addItem(NTechItems.ductTape, "Duct Tape")
        addItem(NTechItems.clayCatalyst, "Clay Catalyst")
        addItem(NTechItems.smallMissileAssembly, "Small Missile Assembly")

        addItem(NTechItems.smallWarhead, "Small Warhead")
        addItem(NTechItems.mediumWarhead, "Medium Warhead")
        addItem(NTechItems.largeWarhead, "Large Warhead")
        addItem(NTechItems.smallIncendiaryWarhead, "Small Incendiary Warhead")
        addItem(NTechItems.mediumIncendiaryWarhead, "Medium Incendiary Warhead")
        addItem(NTechItems.largeIncendiaryWarhead, "Large Incendiary Warhead")
        addItem(NTechItems.smallClusterWarhead, "Small 집속 Warhead")
        addItem(NTechItems.mediumClusterWarhead, "Medium 집속 Warhead")
        addItem(NTechItems.largeClusterWarhead, "Large 집속 Warhead")
        addItem(NTechItems.smallBunkerBusterWarhead, "Small Bunker Busting Warhead")
        addItem(NTechItems.mediumBunkerBusterWarhead, "Medium Bunker Busting Warhead")
        addItem(NTechItems.largeBunkerBusterWarhead, "Large Bunker Busting Warhead")
        addItem(NTechItems.nuclearWarhead, "Nuclear Warhead")
        addItem(NTechItems.thermonuclearWarhead, "Thermonuclear Warhead")
        addItem(NTechItems.endothermicWarhead, "Endothermic Warhead")
        addItem(NTechItems.exothermicWarhead, "Exothermic Warhead")

        addItem(NTechItems.smallFuelTank, "Small Fuel Tank")
        addItem(NTechItems.mediumFuelTank, "Medium Fuel Tank")
        addItem(NTechItems.largeFuelTank, "Large Fuel Tank")

        addItem(NTechItems.smallThruster, "Small Thruster")
        addItem(NTechItems.mediumThruster, "Medium Thruster")
        addItem(NTechItems.largeThruster, "Large Thruster")
        addItem(NTechItems.lvnNuclearRocketEngine, "LV-N Nuclear Rocket Engine")

        addItem(NTechItems.satelliteBase, "Satellite Base")
        addItem(NTechItems.highGainOpticalCamera, "High-Gain Optical Camera")
        addItem(NTechItems.m700SurveyScanner, "M700 Survey Scanner")
        addItem(NTechItems.radarDish, "Radar Dish")
        addItem(NTechItems.deathRay, "Death Ray")
        addItem(NTechItems.xeniumResonator, "Xenium Resonator")

        addItem(NTechItems.size10Connector, "Size 10 Connector")
        addItem(NTechItems.size15Connector, "Size 15 Connector")
        addItem(NTechItems.size20Connector, "Size 20 Connector")

        addItem(NTechItems.hunterChopperCockpit, "Hunter Chopper Cockpit")
        addItem(NTechItems.emplacementGun, "Emplacement Gun")
        addItem(NTechItems.hunterChopperBody, "Hunter Chopper Body")
        addItem(NTechItems.hunterChopperTail, "Hunter Chopper Tail")
        addItem(NTechItems.hunterChopperWing, "Hunter Chopper Wing")
        addItem(NTechItems.hunterChopperRotorBlades, "Hunter Chopper Rotor Blades")
        addItem(NTechItems.combineScrapMetal, "Combine Scrap Metal")

        addItem(NTechItems.heavyHammerHead, "Heavy Hammer Head")
        addItem(NTechItems.heavyAxeHead, "Heavy Axe Head")
        addItem(NTechItems.reinforcedPolymerHandle, "강화된 Polymer Handle")

        addItem(NTechItems.basicCircuitAssembly, "Basic Circuit Assembly")
        addItem(NTechItems.basicCircuit, "Basic Circuit")

        addItem(NTechItems.enhancedCircuit, "Enhanced Circuit")
        addItem(NTechItems.advancedCircuit, "Advanced Circuit")
        addItem(NTechItems.overclockedCircuit, "Overclocked Circuit")
        addItem(NTechItems.highPerformanceCircuit, "High Performance Circuit")
        addItem(NTechItems.militaryGradeCircuitBoardTier1, "Military Grade Circuit Board (Tier 1)")
        addItem(NTechItems.militaryGradeCircuitBoardTier2, "Military Grade Circuit Board (Tier 2)")
        addItem(NTechItems.militaryGradeCircuitBoardTier3, "Military Grade Circuit Board (Tier 3)")
        addItem(NTechItems.militaryGradeCircuitBoardTier4, "Military Grade Circuit Board (Tier 4)")
        addItem(NTechItems.militaryGradeCircuitBoardTier5, "Military Grade Circuit Board (Tier 5)")
        addItem(NTechItems.militaryGradeCircuitBoardTier6, "Military Grade Circuit Board (Tier 6)")

        addItem(NTechItems.revolverMechanism, "Revolver Mechanism")
        addItem(NTechItems.advancedRevolverMechanism, "Advanced Revolver Mechanism")
        addItem(NTechItems.rifleMechanism, "Rifle Mechanism")
        addItem(NTechItems.advancedRifleMechanism, "Advanced Rifle Mechanism")
        addItem(NTechItems.launcherMechanism, "Launcher Mechanism")
        addItem(NTechItems.advancedLauncherMechanism, "Advanced Launcher Mechanism")
        addItem(NTechItems.highTechWeaponMechanism, "High-Tech Weapon Mechanism")

        addItem(NTechItems.point357MagnumPrimer, ".357 매그넘 Primer (x16)")
        addItem(NTechItems.point44MagnumPrimer, ".44 매그넘 Primer (x16)")
        addItem(NTechItems.smallCaliberPrimer, "Small Caliber Primer (x24)")
        addItem(NTechItems.largeCaliberPrimer, "Large Caliber Primer (x8)")
        addItem(NTechItems.buckshotPrimer, "Buckshot Primer (x8)")

        addItem(NTechItems.point357MagnumCasing, ".357 매그넘 탄피 (x16)")
        addItem(NTechItems.point44MagnumCasing, ".44 매그넘 탄피 (x16)")
        addItem(NTechItems.smallCaliberCasing, "Small Caliber 탄피 (x24)")
        addItem(NTechItems.largeCaliberCasing, "Large Caliber 탄피 (x8)")
        addItem(NTechItems.buckshotCasing, "Buckshot 탄피 (x8)")

        addItem(NTechItems.ironBulletAssembly, "철 Bullet Assembly")
        addItem(NTechItems.leadBulletAssembly, "납 Bullet Assembly")
        addItem(NTechItems.glassBulletAssembly, "Glass Bullet Assembly")
        addItem(NTechItems.goldBulletAssembly, "Gold Bullet Assembly")
        addItem(NTechItems.schrabidiumBulletAssembly, "스크라비듐 Bullet Assembly")
        addItem(NTechItems.nightmareBulletAssembly, "Nightmare Bullet Assembly")
        addItem(NTechItems.deshBulletAssembly, "데쉬 Bullet Assembly")
        addItem(NTechItems.point44MagnumAssembly, ".44 매그넘 Assembly")
        addItem(NTechItems.nineMmAssembly, "9mm Assembly")
        addItem(NTechItems.fivePoint56mmAssembly, "5.56mm Assembly")
        addItem(NTechItems.point22LRAssembly, ".22 LR Assembly")
        addItem(NTechItems.point5mmAssembly, ".5mm Assembly")
        addItem(NTechItems.point50AEAssembly, ".50 AE Assembly")
        addItem(NTechItems.point50BMGAssembly, ".50 BMG Assembly")

        addItem(NTechItems.silverBulletCasing, "Silver Bullet Casing")
        addItem(NTechItems.twelvePoint8cmStarmetalHighEnergyShell, "12.8cm 스타메탈 High-Energy Shell")
        addItem(NTechItems.twelvePoint8cmNuclearShell, "12.8cm Nuclear Shell")
        addItem(NTechItems.twelvePoint8cmDUShell, "12.8cm DU-Shell")

        addItem(NTechItems.cableDrum, "Cable Drum")
        addItemDesc(NTechItems.cableDrum, "Right-click poles to connect")
        addItem(NTechItems.paintingOfACartoonPony, "Painting of a Cartoon Pony")
        addItemDesc(NTechItems.paintingOfACartoonPony, "Yellow horse beats blue horse, that's a proven fact!")
        addItem(NTechItems.conspiracyTheory, "음모론")
        addItemDesc(NTechItems.conspiracyTheory, "강철은 항공유를 못 녹여!")
        addItem(NTechItems.politicalTopic, "정치적 주제")
        addItemDesc(NTechItems.politicalTopic, "도널드 덕이 벽을 세울 것이다!")
        addItem(NTechItems.ownOpinion, "내 의견")
        addItemDesc(NTechItems.ownOpinion, "글쎄, 난 맘에 드는데...")

        addItem(NTechItems.explosivePellets, "Explosive Pellets")
        addItemDesc(NTechItems.explosivePellets, "다용도 폭탄에서 사용됩니다:\n주모 여기 폭발력 추가요!")
        addItem(NTechItems.leadPellets, "납 Pellets")
        addItem(NTechItems.flechettes, "Flechettes")
        addItem(NTechItems.poisonGasCartridge, "독가스 카트리지")
        addItemDesc(NTechItems.poisonGasCartridge, "다용도 폭탄에서 사용됩니다:\n폐에 감각이 없으니.. 이게 어떻게 된 거요?")
        addItem(NTechItems.magnetron, "Magnetron")
        addItem(NTechItems.denseCoalCluster, "Dense Coal Cluster")
        addItem(NTechItems.burntBark, "Burnt Bark")
        addItemDesc(NTechItems.burntBark, "A piece of bark from an exploded golden oak tree.")
        addItem(NTechItems.machineUpgradeTemplate, "Machine Upgrade Template")

        addItem(NTechItems.blankRune, "Blank Catalyst Matrix")
        addItem(NTechItems.isaRune, "Cool Catalyst Matrix")
        addItem(NTechItems.dagazRune, "Balanced Catalyst Matrix")
        addItem(NTechItems.hagalazRune, "Rough Catalyst Matrix")
        addItem(NTechItems.jeraRune, "Multiplicative Catalyst Matrix")
        addItem(NTechItems.thurisazRune, "Additive Catalyst Matrix")

        addItem(NTechItems.burnedOutQuadSchrabidiumFuelRod, "Burned Out Quad 스크라비듐 Rod")
        addItemDesc(NTechItems.burnedOutQuadSchrabidiumFuelRod, "A quad fuel rod which contains a\nvery small amount of a strange new element.")

        addItem(NTechItems.scrap, "Scrap")
        addItem(NTechItems.hotDepletedUraniumFuel, "뜨거운 열화 우라늄 연료")
        addItem(NTechItems.hotDepletedThoriumFuel, "뜨거운 열화 토륨 연료")
        addItem(NTechItems.hotDepletedPlutoniumFuel, "뜨거운 열화 플루토늄 연료")
        addItem(NTechItems.hotDepletedMOXFuel, "뜨거운 열화 혼합 산화물 연료")
        addItem(NTechItems.hotDepletedSchrabidiumFuel, "뜨거운 열화 스크라비듐 연료")
        addItem(NTechItems.depletedUraniumFuel, "열화 우라늄 연료")
        addItem(NTechItems.depletedThoriumFuel, "열화 토륨 연료")
        addItem(NTechItems.depletedPlutoniumFuel, "열화 플루토늄 연료")
        addItem(NTechItems.depletedMOXFuel, "열화 혼합 산화물 연료")
        addItem(NTechItems.depletedSchrabidiumFuel, "열화 스크라비듐 연료")
        addItem(NTechItems.trinitite, "트리니타이트")
        addItem(NTechItems.nuclearWaste, "핵 폐기물")
        addItem(NTechItems.tinyNuclearWaste, "작은 핵 폐기물")

        addItem(NTechItems.crystalHorn, "Crystal Horn")
        addItemDesc(NTechItems.crystalHorn, "An actual horn.")
        addItem(NTechItems.charredCrystal, "Charred Crystal")
        addItemDesc(NTechItems.charredCrystal, "Also a real horn. Weird, right?")

        addItem(NTechItems.battery, "Battery")
        addItem(NTechItems.redstonePowerCell, "Redstone Power Cell")
        addItem(NTechItems.sixfoldRedstonePowerCell, "Sixfold Redstone Power Cell")
        addItem(NTechItems.twentyFourFoldRedstonePowerCell, "24-Fold Redstone Power Cell")
        addItem(NTechItems.advancedBattery, "Advanced Battery")
        addItem(NTechItems.advancedPowerCell, "Advanced Power Cell")
        addItem(NTechItems.quadrupleAdvancedPowerCell, "Quadruple Advanced Power Cell")
        addItem(NTechItems.twelveFoldAdvancedPowerCell, "Twelvefold Advanced Power Cell")
        addItem(NTechItems.lithiumBattery, "리튬-Ion Battery")
        addItem(NTechItems.lithiumPowerCell, "리튬-Ion Power Cell")
        addItem(NTechItems.tripleLithiumPowerCell, "Triple 리튬-Ion Power Cell")
        addItem(NTechItems.sixfoldLithiumPowerCell, "Sixfold 리튬-Ion Power Cell")
        addItem(NTechItems.schrabidiumBattery, "스크라비듐 Battery")
        addItem(NTechItems.schrabidiumPowerCell, "스크라비듐 Power Cell")
        addItem(NTechItems.doubleSchrabidiumPowerCell, "Double 스크라비듐 Power Cell")
        addItem(NTechItems.quadrupleSchrabidiumPowerCell, "Quadruple 스크라비듐 Power Cell")
        addItem(NTechItems.sparkBattery, "Spark Battery")
        addItem(NTechItems.offBrandSparkBattery, "Off-Brand Spark Battery")
        addItem(NTechItems.sparkPowerCell, "Spark Power Cell")
        addItem(NTechItems.sparkArcaneCarBattery, "Spark Arcane Car Battery")
        addItem(NTechItems.sparkArcaneEnergyStorageArray, "Spark Arcane Energy Storage Array")
        addItem(NTechItems.sparkArcaneMassEnergyVoid, "Spark Arcane Mass-Energy Void")
        addItem(NTechItems.sparkArcaneDiracSea, "Spark Arcane Dirac Sea")
        addItem(NTechItems.sparkSolidSpaceTimeCrystal, "Spark Solid Space-Time Crystal")
        addItem(NTechItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit, "Spark Ludicrous Physics-Defying Energy Storage Unit")
        addItem(NTechItems.infiniteBattery, "Infinite Battery")
        addItem(NTechItems.singleUseBattery, "Single-Use Battery")
        addItem(NTechItems.largeSingleUseBattery, "Large Single-Use Battery")
        addItem(NTechItems.potatoBattery, "Potato Battery")
        addItem(NTechItems.steamPoweredEnergyStorageTank, "Steam-Powered Energy Storage Tank")
        addItem(NTechItems.largeSteamPoweredEnergyStorageTank, "Large Steam-Powered Energy Storage Tank")

        addItem(NTechItems.stoneFlatStamp, "Flat Stamp (Stone)")
        addItem(NTechItems.stonePlateStamp, "Plate Stamp (Stone)")
        addItem(NTechItems.stoneWireStamp, "Wire Stamp (Stone)")
        addItem(NTechItems.stoneCircuitStamp, "Circuit Stamp (Stone)")
        addItem(NTechItems.ironFlatStamp, "Flat Stamp (Iron)")
        addItem(NTechItems.ironPlateStamp, "Plate Stamp (Iron)")
        addItem(NTechItems.ironWireStamp, "Wire Stamp (Iron)")
        addItem(NTechItems.ironCircuitStamp, "Circuit Stamp (Iron)")
        addItem(NTechItems.steelFlatStamp, "Flat Stamp (Steel)")
        addItem(NTechItems.steelPlateStamp, "Plate Stamp (Steel)")
        addItem(NTechItems.steelWireStamp, "Wire Stamp (Steel)")
        addItem(NTechItems.steelCircuitStamp, "Circuit Stamp (Steel)")
        addItem(NTechItems.titaniumFlatStamp, "Flat Stamp (티타늄)")
        addItem(NTechItems.titaniumPlateStamp, "Plate Stamp (티타늄)")
        addItem(NTechItems.titaniumWireStamp, "Wire Stamp (티타늄)")
        addItem(NTechItems.titaniumCircuitStamp, "Circuit Stamp (티타늄)")
        addItem(NTechItems.obsidianFlatStamp, "Flat Stamp (Obsidian)")
        addItem(NTechItems.obsidianPlateStamp, "Plate Stamp (Obsidian)")
        addItem(NTechItems.obsidianWireStamp, "Wire Stamp (Obsidian)")
        addItem(NTechItems.obsidianCircuitStamp, "Circuit Stamp (Obsidian)")
        addItem(NTechItems.schrabidiumFlatStamp, "Flat Stamp (스크라비듐)")
        addItem(NTechItems.schrabidiumPlateStamp, "Plate Stamp (스크라비듐)")
        addItem(NTechItems.schrabidiumWireStamp, "Wire Stamp (스크라비듐)")
        addItem(NTechItems.schrabidiumCircuitStamp, "Circuit Stamp (스크라비듐)")

        addItem(NTechItems.screwdriver, "Screwdriver")
        addItemDesc(NTechItems.screwdriver, "Could be used instead of a fuse...")
        addItem(NTechItems.deshScrewdriver, "데쉬 Screwdriver")

        addItem(NTechItems.speedUpgradeMk1, "속도 업그레이드 Mk.I")
        addItem(NTechItems.speedUpgradeMk2, "속도 업그레이드 Mk.II")
        addItem(NTechItems.speedUpgradeMk3, "속도 업그레이드 Mk.III")
        addItem(NTechItems.powerSavingUpgradeMk1, "에너지 절약 업그레이드 Mk.I")
        addItem(NTechItems.powerSavingUpgradeMk2, "에너지 절약 업그레이드 Mk.II")
        addItem(NTechItems.powerSavingUpgradeMk3, "에너지 절약 업그레이드 Mk.III")
        addItem(NTechItems.overdriveUpgradeMk1, "과부하 업그레이드 Mk.I")
        addItem(NTechItems.overdriveUpgradeMk2, "과부하 업그레이드 Mk.II")
        addItem(NTechItems.overdriveUpgradeMk3, "과부하 업그레이드 Mk.III")
        addItem(NTechItems.afterBurnUpgradeMk1, "후기연소기 업그레이드 Mk.I")
        addItem(NTechItems.afterBurnUpgradeMk2, "후기연소기 업그레이드 Mk.II")
        addItem(NTechItems.afterBurnUpgradeMk3, "후기연소기 업그레이드 Mk.III")

        addItem(NTechItems.aluminiumShredderBlade, "알루미늄 분쇄기 날")
        addItem(NTechItems.goldShredderBlade, "Gold 분쇄기 날")
        addItem(NTechItems.ironShredderBlade, "철 분쇄기 날")
        addItem(NTechItems.steelShredderBlade, "강철 분쇄기 날")
        addItem(NTechItems.titaniumShredderBlade, "티타늄 분쇄기 날")
        addItem(NTechItems.advancedAlloyShredderBlade, "Advanced Alloy 분쇄기 날")
        addItem(NTechItems.combineSteelShredderBlade, "콤바인 강철 분쇄기 날")
        addItem(NTechItems.schrabidiumShredderBlade, "스크라비듐 분쇄기 날")
        addItem(NTechItems.deshShredderBlade, "데쉬 분쇄기 날")

        addItem(NTechItems.rbmkLid, "RBMK Cover Panel")
        addItem(NTechItems.rbmkGlassLid, "RBMK Glass Cover Panel")

        addItem(NTechItems.rbmkPelletBalefire, "Balefire 연료 펠릿")
        addItem(NTechItems.rbmkPelletBalefireGold, "Flashgold 연료 펠릿")
        addItem(NTechItems.rbmkPelletDrx, "§cDigamma 연료 펠릿§r")
        addItem(NTechItems.rbmkPelletFlashlead, "Flashlead 연료 펠릿")
        addItem(NTechItems.rbmkPelletHea241, "고농축 아메리슘-241 연료 펠릿")
        addItem(NTechItems.rbmkPelletHea242, "고농축 아메리슘-242 연료 펠릿")
        addItem(NTechItems.rbmkPelletHeaus, "고농축 오스트레일륨 연료 펠릿")
        addItem(NTechItems.rbmkPelletHen, "고농축 넵투늄연료 펠릿")
        addItem(NTechItems.rbmkPelletHes, "고농축 플루토늄-239 연료 펠릿")
        addItem(NTechItems.rbmkPelletHep239, "고농축 우라늄-241 연료 펠릿")
        addItem(NTechItems.rbmkPelletHep241, "고농축 우라늄-233 연료 펠릿")
        addItem(NTechItems.rbmkPelletHeu233, "고농축 우라늄-235 연료 펠릿")
        addItem(NTechItems.rbmkPelletHeu235, "HES 연료 펠릿")
        addItem(NTechItems.rbmkPelletLea, "LEA 연료 펠릿")
        addItem(NTechItems.rbmkPelletLeaus, "LEAus 연료 펠릿")
        addItem(NTechItems.rbmkPelletLep, "LEP 연료 펠릿")
        addItem(NTechItems.rbmkPelletLes, "LES 연료 펠릿")
        addItem(NTechItems.rbmkPelletMea, "MEA 연료 펠릿")
        addItem(NTechItems.rbmkPelletMen, "MEN 연료 펠릿")
        addItem(NTechItems.rbmkPelletMep, "MEP 연료 펠릿")
        addItem(NTechItems.rbmkPelletMes, "MES 연료 펠릿")
        addItem(NTechItems.rbmkPelletMeu, "MEU 연료 펠릿")
        addItem(NTechItems.rbmkPelletMox, "혼합 산화물 연료 펠릿")
        addItem(NTechItems.rbmkPelletPo210Be, "Po210Be 중성자원 Pellet")
        addItem(NTechItems.rbmkPelletPu238Be, "Pu238Be 중성자원 Pellet")
        addItem(NTechItems.rbmkPelletRa226Be, "Ra226Be 중성자원 Pellet")
        addItem(NTechItems.rbmkPelletThMeu, "ThMEU 연료 펠릿")
        addItem(NTechItems.rbmkPelletUeu, "NU 연료 펠릿")
        addItem(NTechItems.rbmkPelletZfbAmMix, "Fuel Grade 아메리슘 ZFB Pellet")
        addItem(NTechItems.rbmkPelletZfbBismuth, "비스무트 ZFB Pellet")
        addItem(NTechItems.rbmkPelletZfbPu241, "Pu-241 ZFB Pellet")

        addItem(NTechItems.emptyRBMKRod, "Empty RBMK 연료봉")
        addItem(NTechItems.rbmkRodBalefire, "Balefire RBMK 연료봉")
        addItem(NTechItems.rbmkRodBalefireGold, "Flashgold RBMK 연료봉")
        addItem(NTechItems.rbmkRodDrx, "§cDigamma RBMK 연료봉§r")
        addItem(NTechItems.rbmkRodFlashlead, "Flashlead RBMK 연료봉")
        addItem(NTechItems.rbmkRodHea241, "고농축 아메리슘-241 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHea242, "고농축 아메리슘-242 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHeaus, "고농축 오스트레일륨 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHen, "고농축 넵투늄 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHes, "HES RBMK 연료봉")
        addItem(NTechItems.rbmkRodHep239, "고농축 플루토늄-239 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHep241, "고농축 플루토늄-241 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHeu233, "고농축 우라늄-233 RBMK 연료봉")
        addItem(NTechItems.rbmkRodHeu235, "고농축 우라늄-235 RBMK 연료봉")
        addItem(NTechItems.rbmkRodLea, "LEA RBMK 연료봉")
        addItem(NTechItems.rbmkRodLeaus, "LEAus RBMK 연료봉")
        addItem(NTechItems.rbmkRodLep, "LEP-239 RBMK 연료봉")
        addItem(NTechItems.rbmkRodLes, "LES RBMK 연료봉")
        addItem(NTechItems.rbmkRodMea, "MEA RBMK 연료봉")
        addItem(NTechItems.rbmkRodMen, "MEN RBMK 연료봉")
        addItem(NTechItems.rbmkRodMep, "MEP-239 RBMK 연료봉")
        addItem(NTechItems.rbmkRodMes, "MES RBMK 연료봉")
        addItem(NTechItems.rbmkRodMeu, "MEU RBMK 연료봉")
        addItem(NTechItems.rbmkRodMox, "혼합 산화물 RBMK 연료봉")
        addItem(NTechItems.rbmkRodPo210Be, "Po210Be RBMK 중성자원")
        addItem(NTechItems.rbmkRodPu238Be, "Pu238Be RBMK 중성자원")
        addItem(NTechItems.rbmkRodRa226Be, "Ra226Be RBMK 중성자원")
        addItem(NTechItems.rbmkRodThMeu, "ThMEU RBMK 연료봉")
        addItem(NTechItems.rbmkRodUeu, "NU RBMK 연료봉")
        addItem(NTechItems.rbmkRodZfbAmMix, "Fuel Grade 아메리슘 RBMK ZFB Rod")
        addItem(NTechItems.rbmkRodZfbBismuth, "비스무트 RBMK ZFB Rod")
        addItem(NTechItems.rbmkRodZfbPu241, "Pu-241 RBMK ZFB Rod")

        addItem(NTechItems.meltdownTool, "Dyatlov Instant Meltdown Applicator")

        addItem(NTechItems.graphiteDebris, "뜨거운 흑연 덩어리")
        addItem(NTechItems.metalDebris, "부서진 철근")
        addItem(NTechItems.fuelDebris, "RBMK 연료 덩어리")

        addItem(NTechItems.machineTemplateFolder, "Machine Template Folder")
        addItemDesc(
            NTechItems.machineTemplateFolder,
            "Machine Templates: Paper + Dye\n" +
                    "Fluid IDs: 철 Plate + Dye\n" +
                    "Press Stamps: Flat Stamp\n" +
                    "Siren Tracks: 절연체 + 강철 Plate"
        )

        addItem(NTechItems.sirenTrackHatchSiren, "Hatch Siren")
        addItem(NTechItems.sirenTrackAutopilotDisconnected, "Autopilot Disconnected")
        addItem(NTechItems.sirenTrackAMSSiren, "AMS Siren")
        addItem(NTechItems.sirenTrackBlastDoorAlarm, "Blast Door Alarm")
        addItem(NTechItems.sirenTrackAPCSiren, "APC Siren")
        addItem(NTechItems.sirenTrackKlaxon, "Klaxon")
        addItem(NTechItems.sirenTrackVaultDoorAlarm, "Vault Door Alarm")
        addItem(NTechItems.sirenTrackSecurityAlert, "Security Alert")
        addItem(NTechItems.sirenTrackStandardSiren, "Standard Siren")
        addItem(NTechItems.sirenTrackClassicSiren, "Classic Siren")
        addItem(NTechItems.sirenTrackBankAlarm, "Bank Alarm")
        addItem(NTechItems.sirenTrackBeepSiren, "Beep Siren")
        addItem(NTechItems.sirenTrackContainerAlarm, "Container Alarm")
        addItem(NTechItems.sirenTrackSweepSiren, "Sweep Siren")
        addItem(NTechItems.sirenTrackMissileSiloSiren, "Missile Silo Siren")
        addItem(NTechItems.sirenTrackAirRaidSiren, "Air Raid Siren")
        addItem(NTechItems.sirenTrackNostromoSelfDestruct, "Nostromo Self Destruct")
        addItem(NTechItems.sirenTrackEASAlarmScreech, "EAS Alarm Screech")
        addItem(NTechItems.sirenTrackAPCPass, "APC Pass")
        addItem(NTechItems.sirenTrackRazortrainHorn, "Razortrain Horn")

        addItem(NTechItems.fluidIdentifier, "Fluid Identifier: %s")
        addItemDesc(NTechItems.fluidIdentifier, "Right click fluid ducts to designate them for that fluid.\nShift right click fluid ducts to designate adjacent ducts\nup to a maximum range of 64 ducts.")

        addItem(NTechItems.assemblyTemplate, "Assembly Template: %s")
        addItem(NTechItems.chemTemplate, "Chemistry Template: %s")

        run {
            val usedInLittleBoy = "사용처:\n리틀 보이"
            addItem(NTechItems.neutronShieldingLittleBoy, "Neutron Shielding")
            addItemDesc(NTechItems.neutronShieldingLittleBoy, usedInLittleBoy)
            addItem(NTechItems.subcriticalUraniumTarget, "Subcritical U235 Target")
            addItemDesc(NTechItems.subcriticalUraniumTarget, usedInLittleBoy)
            addItem(NTechItems.uraniumProjectile, "U235 Projectile")
            addItemDesc(NTechItems.uraniumProjectile, usedInLittleBoy)
            addItem(NTechItems.propellantLittleBoy, "Propellant")
            addItemDesc(NTechItems.propellantLittleBoy, usedInLittleBoy)
            addItem(NTechItems.bombIgniterLittleBoy, "Bomb Igniter")
            addItemDesc(NTechItems.bombIgniterLittleBoy, usedInLittleBoy)
        }
        addItem(NTechItems.bundleOfImplosionPropellant, "Bundle of Implosion Propellant")
        addItemDesc(NTechItems.bundleOfImplosionPropellant, "사용처:\n팻 맨\nIvy Mike\n차르 봄바")
        addItem(NTechItems.bombIgniterFatMan, "폭탄 점화기")
        addItemDesc(NTechItems.bombIgniterFatMan, "팻 맨에서 사용됨")
        addItem(NTechItems.plutoniumCore, "플루토늄 핵")
        addItemDesc(NTechItems.plutoniumCore, "사용처:\n팻 맨\nIvy Mike\n차르 봄바")
        addItem(NTechItems.detonator, "Detonator")
        addItemDesc(NTechItems.detonator, "Shift-right-click an explosive to set the position,\nright-click to detonate!")
        addItem(NTechItems.littleBoyKit, "리틀 보이 키트")
        addItem(NTechItems.fatManKit, "팻 맨 키트")

        addItem(NTechItems.designator, "Short Range Target Designator")
        addItem(NTechItems.heMissile, "High Explosive Missile")
        addItem(NTechItems.incendiaryMissile, "Incendiary Missile")
        addItem(NTechItems.clusterMissile, "집속 Missile")
        addItem(NTechItems.bunkerBusterMissile, "Bunker Buster")
        addItem(NTechItems.strongMissile, "Strong High Explosive Missile")
        addItem(NTechItems.strongIncendiaryMissile, "Strong Incendiary Missile")
        addItem(NTechItems.strongClusterMissile, "Strong 집속 Missile")
        addItem(NTechItems.strongBunkerBusterMissile, "Enhanced Bunker Buster")
        addItem(NTechItems.burstMissile, "Burst Missile")
        addItem(NTechItems.infernoMissile, "Inferno Missile G.R.N. Mk.II")
        addItem(NTechItems.rainMissile, "Bomblet Rain")
        addItem(NTechItems.drillMissile, "The Concrete Cracker")
        addItem(NTechItems.nuclearMissile, "Nuclear Missile")
        addItem(NTechItems.tectonicMissile, "Tectonic Missile")
        addItemDesc(NTechItems.tectonicMissile, "Using the power of nuclear explosives, we can summon a volcano!")

        addItem(NTechItems.meteorRemote, "운석 Remote")
        addItemDesc(NTechItems.meteorRemote, "Right click to summon a meteor!")
        addItem(NTechItems.oilDetector, "Oil Reservoir Detector")
        addItemDesc(NTechItems.oilDetector, "Right-click to scan for oil.\nDetector will only find large deposits.")
        addItem(NTechItems.rbmkLinker, "RBMK Console Linking Device")
        addItemDesc(NTechItems.rbmkLinker, "Sneak and right-click RBMK to save the position, sneak and right-click console or crane to link!")
        addItem(NTechItems.geigerCounter, "Handheld Geiger Counter")

        addItem(NTechItems.ivBag, "IV Bag")
        addItem(NTechItems.bloodBag, "Blood Bag")
        addItem(NTechItems.emptyExperienceBag, "Empty Experience Bag")
        addItem(NTechItems.experienceBag, "경험치 Bag")
        addItem(NTechItems.radAway, "RadAway")
        addItem(NTechItems.strongRadAway, "Strong RadAway")
        addItem(NTechItems.eliteRadAway, "Elite RadAway")

        addItem(NTechItems.hazmatHelmet, "방호복 Helmet")
        addItem(NTechItems.hazmatChestplate, "방호복 Chestplate")
        addItem(NTechItems.hazmatLeggings, "방호복 Leggings")
        addItem(NTechItems.hazmatBoots, "방호복 Boots")
        addItem(NTechItems.advancedHazmatHelmet, "Advanced 방호복 Helmet")
        addItem(NTechItems.advancedHazmatChestplate, "Advanced 방호복 Chestplate")
        addItem(NTechItems.advancedHazmatLeggings, "Advanced 방호복 Leggings")
        addItem(NTechItems.advancedHazmatBoots, "Advanced 방호복 Boots")
        addItem(NTechItems.reinforcedHazmatHelmet, "High-Performance 방호복 Helmet")
        addItem(NTechItems.reinforcedHazmatChestplate, "High-Performance 방호복 Chestplate")
        addItem(NTechItems.reinforcedHazmatLeggings, "High-Performance 방호복 Leggings")
        addItem(NTechItems.reinforcedHazmatBoots, "High-Performance 방호복 Boots")
        addItem(NTechItems.titaniumHelmet, "티타늄 Helmet")
        addItem(NTechItems.titaniumChestplate, "티타늄 Chestplate")
        addItem(NTechItems.titaniumLeggings, "티타늄 Leggings")
        addItem(NTechItems.titaniumBoots, "티타늄 Boots")
        addItem(NTechItems.steelHelmet, "강철 Helmet")
        addItem(NTechItems.steelChestplate, "강철 Chestplate")
        addItem(NTechItems.steelLeggings, "강철 Leggings")
        addItem(NTechItems.steelBoots, "강철 Boots")
        addItem(NTechItems.advancedAlloyHelmet, "Advanced Alloy Helmet")
        addItem(NTechItems.advancedAlloyChestplate, "Advanced Alloy Chestplate")
        addItem(NTechItems.advancedAlloyLeggings, "Advanced Alloy Leggings")
        addItem(NTechItems.advancedAlloyBoots, "Advanced Alloy Boots")
        addItem(NTechItems.combineSteelHelmet, "콤바인 강철 Helmet")
        addItem(NTechItems.combineSteelChestplate, "콤바인 강철 Chestplate")
        addItem(NTechItems.combineSteelLeggings, "콤바인 강철 Leggings")
        addItem(NTechItems.combineSteelBoots, "콤바인 강철 Boots")
        addItem(NTechItems.paAAlloyChestplate, "PaA Chest Protection Plate")
        addItem(NTechItems.paAAlloyLeggings, "PaA Leg Reinforcements")
        addItem(NTechItems.paAAlloyBoots, "PaA \"good ol' shoes\"")
        addItem(NTechItems.schrabidiumHelmet, "스크라비듐 Helmet")
        addItem(NTechItems.schrabidiumChestplate, "스크라비듐 Chestplate")
        addItem(NTechItems.schrabidiumLeggings, "스크라비듐 Leggings")
        addItem(NTechItems.schrabidiumBoots, "스크라비듐 Boots")

        addItem(NTechItems.polaroid, "The Polaroid")

        addItem(NTechFluids.spentSteam.bucket, "저압 증기 양동이")
        addItem(NTechFluids.steam.bucket, "증기 양동이")
        addItem(NTechFluids.steamHot.bucket, "Dense 증기 양동이")
        addItem(NTechFluids.steamSuperHot.bucket, "Super Dense 증기 양동이")
        addItem(NTechFluids.steamUltraHot.bucket, "Ultra Dense 증기 양동이")
        addItem(NTechFluids.gas.bucket, "천연 가스 양동이")
        addItem(NTechFluids.oil.bucket, "원유 양동이")
        addItem(NTechFluids.uraniumHexafluoride.bucket, "육불화우라늄 양동이")
        addItem(NTechFluids.corium.bucket, "노심용융물 양동이")
        addItem(NTechFluids.volcanicLava.bucket, "화산 용암 양동이")

        addItem(NTechItems.creativeNuclearExplosionSpawner, "Nuclear Explosion Spawner")
        addItemDesc(NTechItems.creativeNuclearExplosionSpawner, "Manufactured by CakeCo\nEast Spawn Rd 2, 68-419 RetroMC")

        addEntityType(EntityTypes.clusterFragment, "Bomblet")
        addEntityType(EntityTypes.falloutRain, "낙진 비")
        addEntityType(EntityTypes.meteor, "운석")
        addEntityType(EntityTypes.missileBunkerBuster, "벙커 버스터")
        addEntityType(EntityTypes.missileBunkerBusterStrong, "상급 벙커 버스터")
        addEntityType(EntityTypes.missileBurst, "Burst 미사일")
        addEntityType(EntityTypes.missileCluster, "집속 미사일")
        addEntityType(EntityTypes.missileClusterStrong, "Strong 집속 미사일")
        addEntityType(EntityTypes.missileDrill, "The Concrete Cracker")
        addEntityType(EntityTypes.missileHE, "High Explosive 미사일")
        addEntityType(EntityTypes.missileHEStrong, "Strong High Explosive 미사일")
        addEntityType(EntityTypes.missileIncendiary, "Incendiary 미사일")
        addEntityType(EntityTypes.missileIncendiaryStrong, "Strong Incendiary 미사일")
        addEntityType(EntityTypes.missileInferno, "Inferno 미사일 G.R.N. Mk.II")
        addEntityType(EntityTypes.missileNuclear, "Nuclear 미사일")
        addEntityType(EntityTypes.missileRain, "Bomblet Rain")
        addEntityType(EntityTypes.missileTectonic, "Tectonic 미사일")
        addEntityType(EntityTypes.mushroomCloud, "Mushroom Cloud")
        addEntityType(EntityTypes.nuclearExplosion, "Nuclear Explosion")
        addEntityType(EntityTypes.oilSpill, "유출된 원유")
        addEntityType(EntityTypes.rbmkDebris, "RBMK 잔해")
        addEntityType(EntityTypes.shrapnel, "파편")
        addEntityType(EntityTypes.volcanicShrapnel, "화산 파편")

        addEntityTypeWithSpawnEgg(EntityTypes.nuclearCreeper, NTechItems.nuclearCreeperSpawnEgg, "Nuclear Creeper")

        addMenuType(MenuTypes.sirenMenu, "사이렌")
        addMenuType(MenuTypes.safeMenu, "금고")
        addMenuType(MenuTypes.anvilMenu, "%s 티어 모루")
        addMenuType(MenuTypes.steamPressMenu, "증기 압착기")
        addMenuType(MenuTypes.blastFurnaceMenu, "용광로")
        addMenuType(MenuTypes.combustionGeneratorMenu, "연소 발전기")
        addMenuType(MenuTypes.electricFurnaceMenu, "전기로")
        addMenuType(MenuTypes.shredderMenu, "Shredder")
        addMenuType(MenuTypes.assemblerMenu, "Assembler")
        addMenuType(MenuTypes.chemPlantMenu, "Chemical Plant")
        addMenuType(MenuTypes.turbineMenu, "Steam Turbine")
        addMenuType(MenuTypes.oilWellMenu, "유정")
        add(LangKeys.CONTAINER_OIL_DERRICK, "유정탑")
        add(LangKeys.CONTAINER_PUMPJACK, "펌프잭")
        addMenuType(MenuTypes.centrifugeMenu, "원심분리기")
        addMenuType(MenuTypes.rbmkRodMenu, "RBMK 연료봉")
        add(LangKeys.CONTAINER_RBMK_REASIM_ROD, "RBMK 연료봉 (ReaSim)")
        addMenuType(MenuTypes.rbmkBoilerMenu, "RBMK 증기 채널")
        addMenuType(MenuTypes.rbmkManualControlMenu, "RBMK 제어봉")
        add(LangKeys.CONTAINER_RBMK_CONTROL_MODERATED, "RBMK Moderated 제어봉")
        addMenuType(MenuTypes.rbmkAutoControlMenu, "RBMK 자동 제어봉")
        addMenuType(MenuTypes.rbmkConsoleMenu, "RBMK 제어기")

        addMenuType(MenuTypes.littleBoyMenu, "리틀 보이")
        addMenuType(MenuTypes.fatManMenu, "팻 맨")

        addMenuType(MenuTypes.launchPadMenu, "미사일 발사대")

        addDamageSource(DamageSources.extractBlood, "%1\$s extracted too much life essence", "%1\$s tried to leave neatly-packaged life juice for %2\$s")
        addDamageSource(DamageSources.meteorite, "%1\$s was hit by a falling rock from outer space", "%1\$s was hit by a falling rock from outer space whilst trying to escape %2\$s")
        addDamageSource(DamageSources.murkyAnvil, "%1\$s UNDEFINED", "%1\$s UNDEFINED whilst trying to escape %2\$s")
        addDamageSource(DamageSources.nuclearBlast, "%1\$s was blown away by a nuclear explosion", "%1\$s got nuked whilst fighting %2\$s")
        addDamageSource(DamageSources.radiation, "%1\$s died from radiation poisoning", "%1\$s fell victim to acute radiation syndrome whilst fighting %2\$s")
        addDamageSource(DamageSources.shrapnel, "%1\$s was ragged by a shrapnel", "%1\$s was ragged by a shrapnel whilst fighting %2\$s")

        addAttribute(Attributes.RADIATION_RESISTANCE, "Radiation Resistance")

        addFluidTrait(NTechFluidTraits.liquid, "Liquid")
        addFluidTrait(NTechFluidTraits.gaseous, "Gaseous")
        addFluidTrait(NTechFluidTraits.gaseousRoomTemp, "Gaseous at Room Temperature")
        addFluidTrait(NTechFluidTraits.plasma, "Plasma")
        addFluidTrait(NTechFluidTraits.antimatter, "Antimatter")
        addFluidTrait(NTechFluidTraits.delicious, "Delicious")
        addFluidTrait(NTechFluidTraits.combustible, "Combustible")
        addFluidTrait(NTechFluidTraits.coolable, "Coolable")
        addFluidTrait(NTechFluidTraits.corrosive, "Corrosive")
        addFluidTrait(NTechFluidTraits.flammable, "Flammable")
        addFluidTrait(NTechFluidTraits.heatable, "Heatable")
        addFluidTrait(NTechFluidTraits.radioactive, "Radioactive")
        addFluidTrait(NTechFluidTraits.toxic, "Toxic Fumes")

        add(LangKeys.ARMOR_BLAST_PROTECTION, "Damage modifier of %s against explosions")
        add(LangKeys.ARMOR_CUSTOM_GEIGER, "Built-In Geiger Counter HUD")
        add(LangKeys.ARMOR_DAMAGE_CAP, "Hard damage cap of %s")
        add(LangKeys.ARMOR_DAMAGE_MODIFIER, "General damage modifier of %s")
        add(LangKeys.ARMOR_DAMAGE_RESISTANCE_MODIFIER, "Damage modifier of %s against %s")
        add(LangKeys.ARMOR_DAMAGE_THRESHOLD, "Damage threshold of %s")
        add(LangKeys.ARMOR_DASH_COUNT, "Grants %s dashes")
        add(LangKeys.ARMOR_FIREPROOF, "Fireproof")
        add(LangKeys.ARMOR_FULL_SET_BONUS, "Full Set Bonus:")
        add(LangKeys.ARMOR_GEIGER_SOUND, "Auditory Geiger Counter")
        add(LangKeys.ARMOR_GRAVITY, "Gravity modifier of %s")
        add(LangKeys.ARMOR_HARD_LANDING, "Hard Landing")
        add(LangKeys.ARMOR_NULLIFIES_DAMAGE, "Nullifies all damage from %s")
        add(LangKeys.ARMOR_PROJECTILE_PROTECTION, "Damage modifier of %s against projectiles")
        add(LangKeys.ARMOR_PROTECTION_YIELD, "Protection applies to damage <%s")
        add(LangKeys.ARMOR_THERMAL, "Thermal Sight")
        add(LangKeys.ARMOR_VATS, "Enemy HUD")

        add(LangKeys.BUTTON_CANCEL, "Cancel")
        add(LangKeys.BUTTON_START, "Start")

        add(LangKeys.CHEMISTRY_URANIUM_HEXAFLUORIDE, "육불화우라늄 Production")

        add(LangKeys.DETONATOR_INVALID_BLOCK_ENTITY, "서버 오류: 목표 타일엔티티가 올바르지 않습니다!")
        add(LangKeys.DETONATOR_MISSING_COMPONENTS, "The explosive is missing components!")
        add(LangKeys.DETONATOR_NO_EXPLOSIVE, "Target is not a valid explosive!")
        add(LangKeys.DETONATOR_PROHIBITED, "The detonation was prohibited!")
        add(LangKeys.DETONATOR_SUCCESS, "Detonated!")
        add(LangKeys.DETONATOR_UNKNOWN_ERROR, "An unknown error occurred during the detonation")

        add(LangKeys.DEVICE_METEOR_REMOTE_WATCH_OUT, "Watch your head!")
        add(LangKeys.DEVICE_OIL_DETECTOR_BELOW, "Oil deposit directly below!")
        add(LangKeys.DEVICE_OIL_DETECTOR_NEAR, "Oil deposit detected nearby")
        add(LangKeys.DEVICE_OIL_DETECTOR_NO_OIL, "No oil detected")
        add(LangKeys.DEVICE_POSITION_SET, "Position set!")
        add(LangKeys.DEVICE_POSITION_NOT_LOADED, "Position is currently not loaded in the world!")
        add(LangKeys.DEVICE_POSITION_NOT_SET, "No position set!")

        add(LangKeys.ENERGY, "Energy")
        add(LangKeys.ENERGY_ENERGY_STORED, "Energy Stored: %s/%sHE")
        add(LangKeys.ENERGY_CHARGE_RATE, "Charge Rate: %sHE/t")
        add(LangKeys.ENERGY_DISCHARGE_RATE, "Discharge Rate: %sHE/t")

        add(LangKeys.EXPLOSION_SPAWNER_ERROR_EXTRA_FALLOUT, "Cannot parse extra fallout value")
        add(LangKeys.EXPLOSION_SPAWNER_ERROR_STRENGTH, "Cannot parse strength value")
        add(LangKeys.EXPLOSION_SPAWNER_EXTRA_FALLOUT, "Extra Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_HAS_FALLOUT, "Has Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_MUTED, "Muted")
        add(LangKeys.EXPLOSION_SPAWNER_NO_PERMISSION, "Cannot use Nuclear Explosion Spawner: Insufficient permission")
        add(LangKeys.EXPLOSION_SPAWNER_POSITION, "Position")
        add(LangKeys.EXPLOSION_SPAWNER_STRENGTH, "Strength")

        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE, "Fuel grade: %s")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_AERO, "Aviation")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_GAS, "Gaseous")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_HIGH, "High")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_LOW, "Low")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_MEDIUM, "Medium")
        add(LangKeys.FLUID_TRAIT_COOLABLE_HEAT_EXCHANGER, "Coolable")
        add(LangKeys.FLUID_TRAIT_COOLABLE_TURBINE, "Turbine Steam")
        add(LangKeys.FLUID_TRAIT_CORROSIVE_STRONG, "Strongly Corrosive")
        add(LangKeys.FLUID_TRAIT_EFFICIENCY, "효율: %s%%")
        add(LangKeys.FLUID_TRAIT_ENERGY_INFO, "Provides %s per bucket")
        add(LangKeys.FLUID_TRAIT_HEATABLE_BOILER, "Boilable")
        add(LangKeys.FLUID_TRAIT_HEATABLE_HEAT_EXCHANGER, "Heatable")

        add(LangKeys.GEIGER_CHUNK_RADIATION, "Current chunk radiation:")
        add(LangKeys.GEIGER_PLAYER_IRRADIATION, "Player irradiation:")
        add(LangKeys.GEIGER_PLAYER_RESISTANCE, "Player resistance:")
        add(LangKeys.GEIGER_TITLE, "GEIGER COUNTER")
        add(LangKeys.GEIGER_TOTAL_ENVIRONMENTAL_RADIATION, "Total environmental radiation:")

        add(LangKeys.HAZARD_ASBESTOS, "[석면]")
        add(LangKeys.HAZARD_BLINDING, "[Blinding]")
        add(LangKeys.HAZARD_COAL, "[석탄 가루]")
        add(LangKeys.HAZARD_DIGAMMA, "[Digamma]")
        add(LangKeys.HAZARD_EXPLOSIVE, "[Flammable / Explosive]")
        add(LangKeys.HAZARD_HEAT, "[Pyrophoric / Hot]")
        add(LangKeys.HAZARD_HYDROREACTIVE, "[Hydroreactive]")
        add(LangKeys.HAZARD_RADIATON, "[Radioactive]")

        add(LangKeys.INFO_HOLD_KEY_FOR_INFO, "Hold %s to display more info")
        add(LangKeys.INFO_INPUT, "Input:")
        add(LangKeys.INFO_INPUTS, "Inputs:")
        add(LangKeys.INFO_ORE_CLUSTER, "Drops only when broken by a player")
        add(LangKeys.INFO_OUTPUT, "Output:")
        add(LangKeys.INFO_OUTPUTS, "Outputs:")
        add(LangKeys.INFO_POSITION, "Position: %d %d %d")
        add(LangKeys.INFO_PRODUCTION_TIME, "Production Time:")

        add(LangKeys.JEI_CATEGORY_ASSEMBLING, "Assembling")
        add(LangKeys.JEI_CATEGORY_BLASTING, "Blasting")
        add(LangKeys.JEI_CATEGORY_CHEMISTRY, "Chemistry")
        add(LangKeys.JEI_CATEGORY_CONSTRUCTING, "Constructing")
        add(LangKeys.JEI_CATEGORY_PRESSING, "Pressing")
        add(LangKeys.JEI_CATEGORY_SHREDDING, "Shredding")
        add(LangKeys.JEI_CATEGORY_SMITHING, "Smithing")
        add(LangKeys.JEI_CATEGORY_TEMPLATE_FOLDER, "Template Folder")
        add(LangKeys.JEI_EXPERIENCE, "%s XP")
        add(LangKeys.JEI_OUTPUT_CHANCE, "Output chance:")
        add(LangKeys.JEI_TIER_MINIMUM, "Minimum Tier: %s")
        add(LangKeys.JEI_TIER_RANGE, "Tier Range: %s..%s")

        add(LangKeys.OIL_WELL_STATUS_OK, "상태: 정상")
        add(LangKeys.OIL_WELL_STATUS_NO_OIL_SOURCE, "상태: 유정 없음")
        add(LangKeys.OIL_WELL_STATUS_ERROR, "상태: 작동 불가")
        add(LangKeys.OIL_WELL_STATUS_OUT_OF_FLUID, "상태: 수압파쇄액 없음")
        add(LangKeys.OIL_WELL_STATUS_LOOKING_FOR_OIL, "상태: 원유를 찾는 중")
        add(LangKeys.OIL_WELL_STATUS_NO_POWER, "상태: 전력 없음")

        add(LangKeys.RBMK_BOILER_STEAM, "Steam: %d / %d")
        add(LangKeys.RBMK_BOILER_TYPE, "Compressor: %s")
        add(LangKeys.RBMK_BOILER_WATER, "Feedwater: %d / %d")
        add(LangKeys.RBMK_BURN_EULER, "SAFE / EULER")
        add(LangKeys.RBMK_BURN_LINEAR, "DANGEROUS / LINEAR")
        add(LangKeys.RBMK_BURN_LOGARITHMIC, "MEDIUM / LOGARITHMIC")
        add(LangKeys.RBMK_BURN_NEGATIVE_QUADRATIC, "DANGEROUS / NEGATIVE-QUADRATIC")
        add(LangKeys.RBMK_BURN_PASSIVE, "SAFE / PASSIVE")
        add(LangKeys.RBMK_BURN_QUADRATIC, "DANGEROUS / QUADRATIC")
        add(LangKeys.RBMK_BURN_SIGMOID, "SAFE / SIGMOID")
        add(LangKeys.RBMK_BURN_SINE_SLOPE, "EXPERIMENTAL / SINE SLOPE")
        add(LangKeys.RBMK_BURN_SQUARE_ROOT, "MEDIUM / SQUARE ROOT")
        add(LangKeys.RBMK_CONSOLE_ASSIGN, "Assign selected columns to screen #%d")
        add(LangKeys.RBMK_CONSOLE_DESELECT_CONTROL_RODS, "Deselect all")
        add(LangKeys.RBMK_CONSOLE_LINK, "RBMK 연결됨!")
        add(LangKeys.RBMK_CONSOLE_SELECT_CONTROL_RODS, "모든 제어봉 선택")
        add(LangKeys.RBMK_CONSOLE_SELECT_GROUP, "Select %s group")
        add(LangKeys.RBMK_CONTROL_GROUP_BLUE, "§1Blue Group")
        add(LangKeys.RBMK_CONTROL_GROUP_GREEN, "§aGreen Group")
        add(LangKeys.RBMK_CONTROL_GROUP_PURPLE, "§5Purple Group")
        add(LangKeys.RBMK_CONTROL_GROUP_RED, "§cRed Group")
        add(LangKeys.RBMK_CONTROL_GROUP_YELLOW, "§eYellow Group")
        add(LangKeys.RBMK_CONTROL_ROD_LEVEL, "%.1f%%")
        add(LangKeys.RBMK_HEAT, "Column Temperature: %.1f°C")
        add(LangKeys.RBMK_MODERATED, "Moderated")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE, "Draconic Flames")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE_GOLD, "Antihydrogen in a Magnetized Gold-198 Lattice")
        add(LangKeys.RBMK_NAME_PELLET_DRX, "§kcan't you hear, can't you hear the thunder?")
        add(LangKeys.RBMK_NAME_PELLET_FLASHLEAD, "Antihydrogen confined by a Magnetized Gold-198 and Lead-209 Lattice")
        add(LangKeys.RBMK_NAME_PELLET_HEA241, "고농축 아메리슘-241")
        add(LangKeys.RBMK_NAME_PELLET_HEA242, "고농축 아메리슘-242")
        add(LangKeys.RBMK_NAME_PELLET_HEAUS, "고농축 오스트레일륨 (Ayerite)")
        add(LangKeys.RBMK_NAME_PELLET_HEN, "고농축 넵투늄-237")
        add(LangKeys.RBMK_NAME_PELLET_HEP239, "고농축 플루토늄-239")
        add(LangKeys.RBMK_NAME_PELLET_HEP241, "고농축 플루토늄-241")
        add(LangKeys.RBMK_NAME_PELLET_HES, "고농축 스크라비듐-326")
        add(LangKeys.RBMK_NAME_PELLET_HEU233, "고농축 우라늄-233")
        add(LangKeys.RBMK_NAME_PELLET_HEU235, "고농축 우라늄-235")
        add(LangKeys.RBMK_NAME_PELLET_LEA, "저농축 아메리슘-242")
        add(LangKeys.RBMK_NAME_PELLET_LEAUS, "저농축 오스트레일륨 (Tasmanite)")
        add(LangKeys.RBMK_NAME_PELLET_LEP, "저농축 플루토늄-239")
        add(LangKeys.RBMK_NAME_PELLET_LES, "저농축 스크라비듐-326")
        add(LangKeys.RBMK_NAME_PELLET_MEA, "중농축 아메리슘-242")
        add(LangKeys.RBMK_NAME_PELLET_MEN, "중농축 넵투늄-237")
        add(LangKeys.RBMK_NAME_PELLET_MEP, "중농축 플루토늄-239")
        add(LangKeys.RBMK_NAME_PELLET_MES, "중농축 스크라비듐-326")
        add(LangKeys.RBMK_NAME_PELLET_MEU, "중농축 우라늄-235")
        add(LangKeys.RBMK_NAME_PELLET_MOX, "중농축 우라늄, 저농축 이산화 플루토늄 혼합물")
        add(LangKeys.RBMK_NAME_PELLET_PO210BE, "폴로늄-210 & 베릴륨 중성자원")
        add(LangKeys.RBMK_NAME_PELLET_PU238BE, "플루토늄-238 & 베릴륨 중성자원")
        add(LangKeys.RBMK_NAME_PELLET_RA226BE, "Radium-226 & 베릴륨 중성자원")
        add(LangKeys.RBMK_NAME_PELLET_THMEU, "토륨 with MEU Driver Fuel")
        add(LangKeys.RBMK_NAME_PELLET_UEU, "Unenriched 우라늄")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_AM_MIX, "Zirconium Fast Breeder - 고농축 플루토늄-241#MEA")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_BISMUTH, "Zirconium Fast Breeder - LEU/고농축 플루토늄-241#Bi")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_PU241, "Zirconium Fast Breeder - HEU-235/고농축 플루토늄-240#Pu-241")
        add(LangKeys.RBMK_NEUTRON_FAST, "Fast Neutrons")
        add(LangKeys.RBMK_NEUTRON_SLOW, "Slow Neutrons")
        add(LangKeys.RBMK_NEUTRON_ANY, "All Neutrons")
        add(LangKeys.RBMK_PELLET_DEPLETION_FULL, "Fully Depleted")
        add(LangKeys.RBMK_PELLET_DEPLETION_HIGH, "Highly Depleted")
        add(LangKeys.RBMK_PELLET_DEPLETION_MODERATE, "Moderately Depleted")
        add(LangKeys.RBMK_PELLET_DEPLETION_NEW, "Brand New")
        add(LangKeys.RBMK_PELLET_DEPLETION_SLIGHT, "Barely Depleted")
        add(LangKeys.RBMK_PELLET_XENON_POISONED, "High Xenon Poison")
        add(LangKeys.RBMK_PELLET_RECYCLE, "Pellet for recycling")
        add(LangKeys.RBMK_ROD_DEPLETION, "Depletion: %.3f%%")
        add(LangKeys.RBMK_ROD_DIFFUSION, "Diffusion: %s")
        add(LangKeys.RBMK_ROD_FLUX_FUNC, "Flux function: %s")
        add(LangKeys.RBMK_ROD_FUNC_TYPE, "Function type: %s")
        add(LangKeys.RBMK_ROD_HEAT, "Heat per flux: %s")
        add(LangKeys.RBMK_ROD_HEAT_CORE, "Core temp: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL, "Skin temp: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL_TO_MELTING_POINT, "Skin temp: %.1f°C / %.1f°C")
        add(LangKeys.RBMK_ROD_MELTING_POINT, "Melting point: %s")
        add(LangKeys.RBMK_ROD_SOURCE, "Self-igniting")
        add(LangKeys.RBMK_ROD_SPLITS_INTO, "Splits into: %s")
        add(LangKeys.RBMK_ROD_SPLITS_WITH, "Splits with: %s")
        add(LangKeys.RBMK_ROD_XENON, "Xenon poison: %.3f%%")
        add(LangKeys.RBMK_ROD_XENON_BURN, "Xenon burn function: %s")
        add(LangKeys.RBMK_ROD_XENON_GEN, "Xenon gen function: %s")
        add(LangKeys.RBMK_SCREEN_DEPLETION, "Depl: %.1f%%")
        add(LangKeys.RBMK_SCREEN_FUEL_TEMPERATURE, "Core: %.1f°C")
        add(LangKeys.RBMK_SCREEN_POISON, "Xenon: %.1f%%")
        add(LangKeys.RBMK_SCREEN_ROD_EXTRACTION, "Control: %.1f%%")
        add(LangKeys.RBMK_SCREEN_TEMPERATURE, "Temp: %.1f°C")
        add(LangKeys.RBMK_SCREEN_TYPE_COLUMN_TEMPERATURE, "Monitor average column temperature")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_DEPLETION, "Monitor average fuel depletion")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_POISON, "Monitor average xenon poisoning")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_TEMPERATURE, "Monitor average fuel temperature")
        add(LangKeys.RBMK_SCREEN_TYPE_NONE, "Off")
        add(LangKeys.RBMK_SCREEN_TYPE_ROD_EXTRACTION, "Monitor average control rod extraction")

        add(LangKeys.SIREN_TRACK_LOOP, "Type: Loop")
        add(LangKeys.SIREN_TRACK_ONCE, "Type: Play Once")
        add(LangKeys.SIREN_TRACK_RANGE, "Range: %s Meters")
        add(LangKeys.SIREN_TRACK_SIREN_TRACK, "Siren Track")

        add(LangKeys.SUBTITLE_ANVIL_FALL, "Anvil clashes")
        add(LangKeys.SUBTITLE_ASSEMBLER_OPERATE, "Assembler whirs")
        add(LangKeys.SUBTITLE_BLEEP, "Device bleeps")
        add(LangKeys.SUBTITLE_BLOCK_DEBRIS, "Debris hit the ground")
        add(LangKeys.SUBTITLE_BOOP, "Device boops")
        add(LangKeys.SUBTITLE_CENTRIFUGE_OPERATE, "Centrifuge hums")
        add(LangKeys.SUBTITLE_CHEM_PLANT_OPERATE, "Chemical Plant operates")
        add(LangKeys.SUBTITLE_GEIGER_CLICK, "Geiger Counter clicks")
        add(LangKeys.SUBTITLE_ITEM_INJECT, "Needle injected")
        add(LangKeys.SUBTITLE_ITEM_UNPACK, "Item unpacked")
        add(LangKeys.SUBTITLE_METEOR_IMPACT, "운석이 충돌함")
        add(LangKeys.SUBTITLE_MINI_NUKE_EXPLODE, "Mini nuke explodes")
        add(LangKeys.SUBTITLE_MISSILE_TAKEOFF, "Missile takes off")
        add(LangKeys.SUBTITLE_PRESS_OPERATE, "Press stamps")
        add(LangKeys.SUBTITLE_RBMK_AZ5_COVER, "AZ-3 lid opened")
        add(LangKeys.SUBTITLE_RBMK_EXPLODE, "RBMK explodes")
        add(LangKeys.SUBTITLE_RBMK_SHUTDOWN, "RBMK shutting down")
        add(LangKeys.SUBTITLE_SIREN_AIR_RAID, "사이렌 작동: Air Raid Siren")
        add(LangKeys.SUBTITLE_SIREN_AMS, "사이렌 작동: AMS Siren")
        add(LangKeys.SUBTITLE_SIREN_APC, "사이렌 작동: APC Siren")
        add(LangKeys.SUBTITLE_SIREN_APC_PASS, "사이렌 작동: APC Pass")
        add(LangKeys.SUBTITLE_SIREN_AUTOPILOT_DISCONNECTED, "사이렌 작동: Autopilot Disconnected")
        add(LangKeys.SUBTITLE_SIREN_BANK, "사이렌 작동: Bank Alarm")
        add(LangKeys.SUBTITLE_SIREN_BEEP, "사이렌 작동: Beep Siren")
        add(LangKeys.SUBTITLE_SIREN_BLAST_DOOR, "사이렌 작동: Blast Door Alarm")
        add(LangKeys.SUBTITLE_SIREN_CLASSIC, "사이렌 작동: Classic Siren")
        add(LangKeys.SUBTITLE_SIREN_CONTAINER, "사이렌 작동: Container Alarm")
        add(LangKeys.SUBTITLE_SIREN_EAS, "사이렌 작동: EAS Alarm Screech")
        add(LangKeys.SUBTITLE_SIREN_HATCH, "사이렌 작동: Hatch Siren")
        add(LangKeys.SUBTITLE_SIREN_KLAXON, "사이렌 작동: Klaxon")
        add(LangKeys.SUBTITLE_SIREN_MISSILE_SILO, "사이렌 작동: 미사일 Silo Siren")
        add(LangKeys.SUBTITLE_SIREN_NOSTROMO_SELF_DESTRUCT, "사이렌 작동: Nostromo Self Destruct")
        add(LangKeys.SUBTITLE_SIREN_RAZORTRAIN_HORN, "사이렌 작동: Razortrain Horn")
        add(LangKeys.SUBTITLE_SIREN_SECURITY, "사이렌 작동: Security Alert")
        add(LangKeys.SUBTITLE_SIREN_STANDARD, "사이렌 작동: Standard Siren")
        add(LangKeys.SUBTITLE_SIREN_SWEEP, "사이렌 작동: Sweep Siren")
        add(LangKeys.SUBTITLE_SIREN_VAULT_DOOR, "사이렌 작동: Vault Door Alarm")
        add(LangKeys.SUBTITLE_UPGRADE_INSTALL, "업그레이드가 설치됨")
        add(LangKeys.SUBTITLE_USE_RADAWAY, "Liquid infused")

        add(LangKeys.UPGRADE_INFO_ACCEPTED_UPGRADES, "적용 가능 업그레이드:")
        add(LangKeys.UPGRADE_INFO_BURN_GAS, "%smB 의 가스를 %s간 연소")
        add(LangKeys.UPGRADE_INFO_CONSUMPTION, "소모량: %s")
        add(LangKeys.UPGRADE_INFO_DELAY, "Delay: %s")
        add(LangKeys.UPGRADE_INFO_STACKS_TO, "Stacks to level %s")
        add(LangKeys.UPGRADE_NAME_AFTER_BURNER, "후기연소기")
        add(LangKeys.UPGRADE_NAME_OVERDRIVE, "과부하")
        add(LangKeys.UPGRADE_NAME_POWER_SAVING, "에너지 절약")
        add(LangKeys.UPGRADE_NAME_SPEED, "속도")
        add(LangKeys.UPGRADE_WARN_INCOMPATIBLE, "이 업그레이드는 호환되지 않습니다!")
        add(LangKeys.UPGRADE_WARN_MACHINE_NOT_UPGRADEABLE, "This machine is not upgradeable!")
        add(LangKeys.UPGRADE_WARN_NOT_A_MACHINE, "This is not a machine!")
        add(LangKeys.UPGRADE_WARN_VIEW_MACHINE, "View a machine for info about effects")
        add(LangKeys.UPGRADE_WARN_UNKNOWN_COMPATIBILITY, "Compatibility with the machine is unknown")

        add(LangKeys.VERSION_CHECKER_ANNOUNCEMENT, "-- NTM 버전 확인기 --")
        add(LangKeys.VERSION_CHECKER_BLEEDING_EDGE, "Running on the bleeding edge!")
        add(LangKeys.VERSION_CHECKER_CHANGES_LIST, "Short list of changes:")
        add(LangKeys.VERSION_CHECKER_CUTTING_EDGE, "Running on the cutting edge of beta!")
        add(LangKeys.VERSION_CHECKER_UPDATE, "NTM 새 버전이 나왔습니다!")
        add(LangKeys.VERSION_CHECKER_VIEW_RELEASES, "Click here to get to the releases page!")

        add(LangKeys.VOLCANO_EXTINGUISHING, "DOES EXTINGUISH")
        add(LangKeys.VOLCANO_GROWING, "DOES GROW")
        add(LangKeys.VOLCANO_NOT_EXTINGUISHING, "DOES NOT EXTINGUISH")
        add(LangKeys.VOLCANO_NOT_GROWING, "DOES NOT GROW")
        add(LangKeys.VOLCANO_SMOLDERING, "SHIELD VOLCANO")

        add(LangKeys.WORD_SECONDS, "Seconds")
    }

    private fun addMaterials() = with(Materials) {
        addMaterial(coal, "석탄")
        addMaterial(iron, "철")
        addMaterial(copper, "구리")
        addMaterial(gold, "금")
        addMaterial(redstone, "레드스톤")
        addMaterial(emerald, "에메랄드")
        addMaterial(lazuli, "청금석")
        addMaterial(diamond, "다이아몬드")

        addMaterial(actinium227, "악티늄-227")
        addMaterial(advancedAlloy, "Advanced Alloy")
        addMaterial(aluminium, "알루미늄")
        addMaterial(americium241, "아메리슘-241")
        addMaterial(americium242, "아메리슘-242")
        addMaterial(americiumFuel, "아메리슘 연료")
        addMaterial(arsenic, "비소")
        addMaterial(asbestos, "석면")
        addMaterial(australium, "오스트레일륨")
        addMaterial(bakelite, "베이클라이트")
        addMaterial(beryllium, "베릴륨")
        addMaterial(bismuth, "비스무트")
        addMaterial(boron, "Boron")
        addMaterial(cobalt, "코발트")
        addMaterial(cobalt60, "코발트-60")
        addMaterial(combineSteel, "콤바인 강철")
        addMaterial(daffergon, "Daffergon")
        addMaterial(desh, "Desh")
        addMaterial(dineutronium, "Dineutronium")
        addMaterial(electronium, "Electronium")
        addMaterial(euphemium, "유페뮴")
        addMaterial(ferricSchrabidate, "Ferric Schrabidate")
        addMaterial(fiberglass, "Fiberglass")
        addMaterial(fluorite, "형석")
        addMaterial(ghiorsium336, "Ghiorsium-336")
        addMaterial(gold198, "Gold-198")
        addMaterial(graphite, "흑연")
        addMaterial(hesFuel, "고농축 스크라비듐 연료")
        addMaterial(highSpeedSteel, "High-Speed Steel")
        addMaterial(insulator, "절연체")
        addMaterial(lanthanum, "란타넘")
        addMaterial(lead, "납")
        addMaterial(lead209, "납-209")
        addMaterial(lesFuel, "저농축 스크라비듐 연료")
        addMaterial(lignite, "갈탄")
        addMaterial(lithium, "리튬")
        addMaterial(magnetizedTungsten, "자기화 텅스텐")
        addMaterial(moxFuel, "혼합 산화물 연료")
        addMaterial(naturalPlutonium, "플루토늄")
        addMaterial(naturalUranium, "우라늄")
        addMaterial(neptunium, "넵튜늄")
        addMaterial(neptuniumFuel, "넵튜늄 연료")
        addMaterial(niobium, "나이오븀")
        addMaterial(niter, "초석")
        addMaterial(nuclearWaste, "핵 폐기물")
        addMaterial(osmiridium, "Osmiridium")
        addMaterial(plutonium238, "플루토늄-238")
        addMaterial(plutonium239, "플루토늄-239")
        addMaterial(plutonium240, "플루토늄-240")
        addMaterial(plutonium241, "플루토늄-241")
        addMaterial(plutoniumFuel, "플루토늄 연료")
        addMaterial(polonium, "폴로늄")
        addMaterial(polymer, "Polymer")
        addMaterial(radium226, "Radium-226")
        addMaterial(reactorGradeAmericium, "Reactor Grade 아메리슘")
        addMaterial(reactorGradePlutonium, "Reactor Grade 플루토늄")
        addMaterial(redCopper, "붉은 구리")
        addMaterial(redPhosphorus, "적린")
        addMaterial(reiium, "Reiium")
        addMaterial(rubber, "Rubber")
        addMaterial(saturnite, "Saturnite")
        addMaterial(schrabidium, "스크라비듐")
        addMaterial(schrabidiumFuel, "스크라비듐 연료")
        addMaterial(schraranium, "Schraranium")
        addMaterial(solinium, "Solinium")
        addMaterial(starmetal, "Starmetal")
        addMaterial(steel, "강철")
        addMaterial(strontium90, "Strontium-90")
        addMaterial(sulfur, "황")
        addMaterial(tantalium, "Tantalium")
        addMaterial(technetium99, "테크네튬-99")
        addMaterial(technetiumSteel, "테크네튬 강철")
        addMaterial(thorium, "토륨-232")
        addMaterial(thoriumFuel, "토륨 연료")
        addMaterial(titanium, "티타늄")
        addMaterial(trinitite, "트리니타이트")
        addMaterial(tungsten, "텅스텐")
        addMaterial(unobtainium, "언옵테이늄")
        addMaterial(uranium233, "우라늄-233")
        addMaterial(uranium235, "우라늄-235")
        addMaterial(uranium238, "우라늄-238")
        addMaterial(uraniumFuel, "우라늄 연료")
        addMaterial(verticium, "버티슘")
        addMaterial(weidanium, "웨이다늄")
        addMaterial(whitePhosphorus, "백린")
        addMaterial(yellowcake, "우라늄정광")
    }

    override val spawnEggFormat = "%s 생정 알"

    override val oreFormat = "%s 광석"
    override val deepOreFormat = "심층암 %s 광석"
    override val blockFormat = "%s 블록"
    override val rawFormat = "%s 원석"
    override val ingotFormat = "%s 주괴"
    override val billetFormat = "%s 동전"
    override val nuggetFormat = "%s 조각"
    override val crystalsFormat = "%s 결정"
    override val powderFormat = "%s 가루"
    override val plateFormat = "%s 판"
    override val wireFormat = "%s 전선"
}
