package at.martinthedragon.nucleartech.datagen.localisation

import at.martinthedragon.nucleartech.CreativeTabs
import at.martinthedragon.nucleartech.LangKeys
import at.martinthedragon.nucleartech.Materials
import at.martinthedragon.nucleartech.block.NTechBlocks
import at.martinthedragon.nucleartech.datagen.NuclearLanguageProviders
import at.martinthedragon.nucleartech.entity.EntityTypes
import at.martinthedragon.nucleartech.entity.attribute.Attributes
import at.martinthedragon.nucleartech.fluid.NTechFluids
import at.martinthedragon.nucleartech.item.NTechItems
import at.martinthedragon.nucleartech.menu.MenuTypes
import at.martinthedragon.nucleartech.world.DamageSources
import net.minecraft.data.DataGenerator

class PlPlLanguageProvider(dataGenerator: DataGenerator) : NuclearLanguageProvider(dataGenerator, NuclearLanguageProviders.PL_PL, false) {
    override fun translate() {
        addCreativeTab(CreativeTabs.Parts, "NTM Materiały i Części")
        addCreativeTab(CreativeTabs.Items, "NTM Części Maszyn i Paliwa")
        addCreativeTab(CreativeTabs.Templates, "NTM Szablony")
        addCreativeTab(CreativeTabs.Blocks, "NTM Surowce i Bloki")
        addCreativeTab(CreativeTabs.Machines, "NTM Maszyny")
        addCreativeTab(CreativeTabs.Bombs, "NTM Bomby")
        addCreativeTab(CreativeTabs.Rocketry, "NTM Rakiety i Satelity")
        addCreativeTab(CreativeTabs.Consumables, "NTM Mat. eksploat. i Przybory")
        addCreativeTab(CreativeTabs.Miscellaneous, "NTM Różne")

        addMaterials()

        addBlock(NTechBlocks.scorchedUraniumOre, "Spieczone Złoże Uranu")
        addBlock(NTechBlocks.thoriumOre, "Złoże Toru")
        addBlock(NTechBlocks.oilDeposit, "Złoże Ropy Naftowej")
        addBlockDesc(NTechBlocks.oilDeposit, "Nie masz tego kopać\nUżyj wiertnicy ty głupku.")
        addBlock(NTechBlocks.emptyOilDeposit, "Puste Złoże Ropy Naftowej")
        addBlock(NTechBlocks.oilSand, "Piasek Olejowy")
        addBlock(NTechBlocks.australianOre, "Złoże Australijskie")
        addBlockDesc(NTechBlocks.australianOre, "Złoże Australium")
        addBlock(NTechBlocks.weidite, "Weidit")
        addBlockDesc(NTechBlocks.weidite, "Złoże Weiditu")
        addBlock(NTechBlocks.reiite, "Reiit")
        addBlockDesc(NTechBlocks.reiite, "Złoże Reiitu")
        addBlock(NTechBlocks.brightblendeOre, "Złoże Brightblendu")
        addBlockDesc(NTechBlocks.brightblendeOre, "Złoże Unobtainium")
        addBlock(NTechBlocks.dellite, "Dellit")
        addBlockDesc(NTechBlocks.dellite, "Złoże Daffergonu")
        addBlock(NTechBlocks.dollarGreenMineral, "Minerał Dollar Green")
        addBlockDesc(NTechBlocks.dollarGreenMineral, "Złoże Verticium")
        addBlock(NTechBlocks.rareEarthOre, "Złoże Metali Ziem Rzadkich")
        addBlock(NTechBlocks.netherUraniumOre, "Netherowe Złoże Uranu")
        addBlock(NTechBlocks.scorchedNetherUraniumOre, "Spieczone Netherowe Złoże Uranu")
        addBlock(NTechBlocks.netherPlutoniumOre, "Netherowe Złoże Plutonu")
        addBlock(NTechBlocks.netherTungstenOre, "Netherowe Złoże Wolframu")
        addBlock(NTechBlocks.netherSulfurOre, "Netherowe Złoże Siarki")
        addBlock(NTechBlocks.netherPhosphorusOre, "Netherowe Złoże Fosforu")
        addBlock(NTechBlocks.netherSchrabidiumOre, "Netherowe Złoże Schrabidium")
        addBlock(NTechBlocks.meteorUraniumOre, "Meteorowe Złoże Uranu")
        addBlock(NTechBlocks.meteorThoriumOre, "Meteorowe Złoże Toru")
        addBlock(NTechBlocks.meteorTitaniumOre, "Meteorowe Złoże Tytanu")
        addBlock(NTechBlocks.meteorSulfurOre, "Meteorowe Złoże Siarki")
        addBlock(NTechBlocks.meteorCopperOre, "Meteorowe Złoże Miedzi")
        addBlock(NTechBlocks.meteorTungstenOre, "Meteorowe Złoże Wolframu")
        addBlock(NTechBlocks.meteorAluminiumOre, "Meteorowe Złoże Aluminium")
        addBlock(NTechBlocks.meteorLeadOre, "Meteorowe Złoże Ołowiu")
        addBlock(NTechBlocks.meteorLithiumOre, "Meteorowe Złoże Litu")
        addBlock(NTechBlocks.trixite, "Trycyt")
        addBlock(NTechBlocks.basaltSulfurOre, "Bazalt Bogaty w Siarkę")
        addBlock(NTechBlocks.basaltFluoriteOre, "Bazalt bogaty we Fluoryt")
        addBlock(NTechBlocks.basaltAsbestosOre, "Bazalt bogaty w Azbest")
        addBlock(NTechBlocks.basaltVolcanicGemOre, "Bazalt bogaty w Klejnoty")

        addBlock(NTechBlocks.scorchedDeepslateUraniumOre, "Spieczone Łupkowe Złoże Uranu")
        addBlock(NTechBlocks.deepslateOilDeposit, "Łupkowe Złoże Ropy Naftowej")
        addBlockDesc(NTechBlocks.deepslateOilDeposit, "Zaszedłeś tak głęboko i dalej\nnie wiesz co robić? Jak?!")
        addBlock(NTechBlocks.emptyDeepslateOilDeposit, "Puste Łupkowe Złoże Ropy Naftowej")
        addBlockDesc(NTechBlocks.deepslateAustralianOre, "Złoże Australium")
        addBlock(NTechBlocks.deepslateRareEarthOre, "Łupkowe Złoże Metali Ziem Rzadkich")

        addBlock(NTechBlocks.scrapBlock, "Blok Złomu")
        addBlock(NTechBlocks.electricalScrapBlock, "Blok Elektrycznego Złomu")
        addBlock(NTechBlocks.insulatorRoll, "Rolka Izolatora")
        addBlock(NTechBlocks.fiberglassRoll, "Rolka Włókna Szklanego")
        addBlock(NTechBlocks.trinititeBlock, "Blok Trynitytu")
        addBlock(NTechBlocks.schrabidiumCluster, "Kępa Schrabidium")
        addBlock(NTechBlocks.euphemiumEtchedSchrabidiumCluster, "Kępa Schrabidium Wyryta Euphemium")
        addBlock(NTechBlocks.deshReinforcedBlock, "Blok Wzmocnionego Deszu")

        addBlock(NTechBlocks.titaniumDecoBlock, "Dekoracyjny Blok Tytanu")
        addBlock(NTechBlocks.redCopperDecoBlock, "Dekoracyjny Blok Czerwonej Miedzi")
        addBlock(NTechBlocks.tungstenDecoBlock, "Dekoracyjny Blok Wolframu")
        addBlock(NTechBlocks.aluminiumDecoBlock, "Dekoracyjny Blok Aluminium")
        addBlock(NTechBlocks.steelDecoBlock, "Dekoracyjny Blok Stali")
        addBlock(NTechBlocks.leadDecoBlock, "Dekoracyjny Blok Ołowiu")
        addBlock(NTechBlocks.berylliumDecoBlock, "Dekoracyjny Blok Berylu")
        addBlock(NTechBlocks.asbestosRoof, "Azbestowe Zadaszenie")
        addBlock(NTechBlocks.hazmatBlock, "Blok Hazmat")
        addBlock(NTechBlocks.steelBeam, "Stalowa Belka")
        addBlock(NTechBlocks.steelScaffold, "Stalowe Rusztowanie")
        addBlock(NTechBlocks.steelGrate, "Stalowa Kratownica")

        addBlock(NTechBlocks.glowingMushroom, "Świecący Grzyb")
        addBlock(NTechBlocks.glowingMushroomBlock, "Blok Świecącego Grzyba")
        addBlock(NTechBlocks.glowingMushroomStem, "Trzon Świecącego Grzyba")
        addBlock(NTechBlocks.deadGrass, "Blok Martwej Trawy")
        addBlock(NTechBlocks.glowingMycelium, "Blok Świecącej Grzybni")
        addBlock(NTechBlocks.trinitite, "Złoże Trynitytu")
        addBlock(NTechBlocks.redTrinitite, "Czerwone Złoże Trynitytu")
        addBlock(NTechBlocks.charredLog, "Zwęglony Pień")
        addBlock(NTechBlocks.charredPlanks, "Zwęglone Deski")

        addBlock(NTechBlocks.slakedSellafite, "Zimny Sellafit")
        addBlock(NTechBlocks.sellafite, "Sellafit")
        addBlock(NTechBlocks.hotSellafite, "Ciepły Sellafit")
        addBlock(NTechBlocks.boilingSellafite, "Wrzący Sellafit")
        addBlock(NTechBlocks.blazingSellafite, "Płonący Sellafit")
        addBlock(NTechBlocks.infernalSellafite, "Piekielny Sellafit")
        addBlock(NTechBlocks.sellafiteCorium, "Sellafit-Korium")

        addBlock(NTechBlocks.corium, "Korium")
        addBlock(NTechBlocks.corebblestone, "Korbruk")

        addBlock(NTechBlocks.siren, "Syrena")
        addBlock(NTechBlocks.safe, "Sejf")
        addBlock(NTechBlocks.steamPressBase, "Prasa na Parę")
        addBlock(NTechBlocks.steamPressFrame, "Prasa na Parę")
        addBlock(NTechBlocks.steamPressTop, "Prasa na Parę")
        addBlock(NTechBlocks.blastFurnace, "Piec Hutniczy")
        addBlock(NTechBlocks.combustionGenerator, "Prądnica Spaleniowa")
        addBlock(NTechBlocks.electricFurnace, "Piec Elektryczny")
        addBlock(NTechBlocks.shredder, "Strzępiarka")
        addBlock(NTechBlocks.assembler, "Monter")
        addBlock(NTechBlocks.chemPlant, "Maszyna Chemiczna")
        addBlock(NTechBlocks.oilDerrick, "Wiertnica Naftowa")
        addBlock(NTechBlocks.pumpjack, "Kiwon")
        addBlockDesc11(NTechBlocks.pumpjack, "Prawdziwy komar")
        addBlock(NTechBlocks.centrifuge, "Wirówka")
        addBlock(NTechBlocks.ironAnvil, "Żelazne Kowadło")
        addBlock(NTechBlocks.leadAnvil, "Ołowiane Kowadło")
        addBlock(NTechBlocks.steelAnvil, "Stalowe Kowadło")
        addBlock(NTechBlocks.meteoriteAnvil, "Meteorytowe Kowadło")
        addBlock(NTechBlocks.starmetalAnvil, "Gwiazdometalowe Kowadło")
        addBlock(NTechBlocks.ferrouraniumAnvil, "Żelazouranowe Kowadło")
        addBlock(NTechBlocks.bismuthAnvil, "Bizmutowe Kowadło")
        addBlock(NTechBlocks.schrabidateAnvil, "Kowadło z Schrabidanu Żelaznego")
        addBlock(NTechBlocks.dineutroniumAnvil, "Dineutronowe Kowadło")
        addBlock(NTechBlocks.murkyAnvil, "Mroczne Kowadło")

        addBlock(NTechBlocks.decoRbmkBlock, "Blok Dekoracyjny RBMK")
        addBlock(NTechBlocks.decoRbmkSmoothBlock, "Gładki Blok Dekoracyjny RBMK")

        addBlock(NTechBlocks.rbmkColumn, "Część Kolumny RBMK")
        addBlock(NTechBlocks.rbmkRod, "Pręt Paliwowy RBMK")
        addBlock(NTechBlocks.rbmkModeratedRod, "Moderowany Pręt Paliwowy RBMK")
        addBlock(NTechBlocks.rbmkReaSimRod, "Pręt Paliwowy RBMK (ReaSim)")
        addBlock(NTechBlocks.rbmkModeratedReaSimRod, "Moderowany Pręt Paliwowy RBMK (ReaSim)")
        addBlock(NTechBlocks.rbmkReflector, "Reflektor Neutronowy z Węgliku Wolframu RBMK")
        addBlock(NTechBlocks.rbmkModerator, "Grafitowy Moderator RBMK")
        addBlock(NTechBlocks.rbmkAbsorber, "Absorber Neutronów z Boru RBMK")
        addBlock(NTechBlocks.rbmkBoilerColumn, "Część Kanału Pary Wodnej RBMK")
        addBlock(NTechBlocks.rbmkBoiler, "Kanał Pary Wodnej RBMK")
        addBlock(NTechBlocks.rbmkBlank, "Kolumna Strukturalna RBMK")
        addBlock(NTechBlocks.rbmkManualControlRod, "Pręty Sterujące RBMK")
        addBlock(NTechBlocks.rbmkModeratedControlRod, "Moderowane Pręty Sterujące RBMK")
        addBlock(NTechBlocks.rbmkAutoControlRod, "Automatyczne Pręty Sterujące RBMK")
        addBlock(NTechBlocks.rbmkSteamConnector, "Złącze Pary Wodnej RBMK")
        addBlock(NTechBlocks.rbmkInlet, "Wlot Wody ReaSim RBMK")
        addBlock(NTechBlocks.rbmkOutlet, "Wylot Wody ReaSim RBMK")
        addBlock(NTechBlocks.rbmkConsole, "Pulpit Sterowniczy RBMK")
        addBlock(NTechBlocks.rbmkDebris, "Gruz RBMK")
        addBlock(NTechBlocks.rbmkBurningDebris, "Ognisty Gruz RBMK")
        addBlock(NTechBlocks.rbmkRadioactiveDebris, "Tlący Gruz RBMK")

        addBlock(NTechBlocks.coatedCable, "Pokryty Kabel z Czerwonej Miedzi")
        addBlock(NTechBlocks.coatedUniversalFluidDuct, "Pokryta Uniwersalna Rura Płynu")

        addBlock(NTechBlocks.littleBoy, "Little Boy")
        addBlock(NTechBlocks.fatMan, "Fat Man")
        addBlock(NTechBlocks.volcanoCore, "Rdzeń Wulkanu")

        addBlock(NTechBlocks.launchPad, "Wyrzutnia Rakiet")
        addBlock(NTechBlocks.launchPadPart, "Wyrzutnia Rakiet")

        addBlock(NTechBlocks.genericMultiBlockPart, "Część Struktury Wieloblokowej")
        addBlock(NTechBlocks.genericMultiBlockPort, "Wejście/Wyjście Struktury Wieloblokowej")
        addBlock(NTechBlocks.oilPipe, "Rura Naftowa")

        addBlock(NTechFluids.steam.block, "Para Wodna")
        addBlock(NTechFluids.steamHot.block, "Gęsta Para Wodna")
        addBlock(NTechFluids.steamSuperHot.block, "Bardzo Gęsta Para Wodna")
        addBlock(NTechFluids.steamUltraHot.block, "Niesamowicie Gęsta Para Wodna")
        addBlock(NTechFluids.oil.block, "Ropa Naftowa")
        addBlock(NTechFluids.gas.block, "Gaz Ziemny")
        addBlock(NTechFluids.uraniumHexafluoride.block, "Sześciofluorku Uranu")
        addBlock(NTechFluids.corium.block, "Korium")
        addBlock(NTechFluids.volcanicLava.block, "Lawa Wulkaniczna")

        addItem(NTechItems.rawThorium, "Surowy Tor")
        addItem(NTechItems.rawRareEarth, "Surowe Metale Ziem Rzadkich")
        addItem(NTechItems.rawTrixite, "Surowy Trycyt")

        addItemDesc(NTechItems.neptuniumIngot, "To mój ulubiony!")
        addItemDesc(NTechItems.tantaliumIngot, "'Tantal'")
        addItemDesc(NTechItems.tantaliumNugget, "'Tantal'")
        addItemDesc(NTechItems.schraraniumIngot, "Zrobiony z uranu z Transmutatora Schrabidium")
        addItemDesc(NTechItems.combineSteelIngot, "*wstaw tutaj odniesienie do Civil Protection*")
        addItemDesc(NTechItems.ghiorsium336Ingot, "Kolega z Pracy Seaborga.")
        addItemDesc(NTechItems.ghiorsium336Nugget, "Kolega z Pracy Seaborga.")
        addItem(NTechItems.lanthanumIngot, "Półstabilna Sztabka Lantanu")
        addItemDesc(NTechItems.euphemiumIngot, "Bardzo specialny, lecz dziwny element")
        addItem(NTechItems.whitePhosphorusIngot, "Tabliczka Białego Fosforu")

        addItem(NTechItems.semtexBar, "Tabliczka Semtex")
        addItemDesc(
            NTechItems.semtexBar,
            "Semtex H Plastikowy materiał wybuchowy\n" +
                "Wydajny materiał wybuchowy do wielu zastosowań.\n" +
                "Jadalny"
        )

        addItem(NTechItems.lithiumCube, "Kostka z Litu")
        addItem(NTechItems.solidFuelCube, "Kostka Paliwa Stałego")
        addItem(NTechItems.solidRocketFuelCube, "Kostka Stałego Paliwa Rakietowego")

        addItem(NTechItems.fiberglassSheet, "Arkusz Włókna Szklanego")
        addItemDesc(NTechItems.fiberglassSheet, "Wysoki we włókno, wysoki w szkło. Wszystko, czego potrzebuje ludzkie ciało.")
        addItem(NTechItems.asbestosSheet, "Arkusz Azbestu")
        addItemDesc(NTechItems.asbestosSheet, "§o„Wypełniony życiem, zwątpieniem w siebie i azbestem. To przychodzi z powietrzem.“")

        addItem(NTechItems.lesserAustraliumBillet, "Lepsza Pastylka Australium")
        addItem(NTechItems.greaterAustraliumBillet, "Gorsza Pastylka Australium")
        addItem(NTechItems.po210BeBillet, "Pastylka Po210Be")
        addItem(NTechItems.ra226BeBillet, "Pastylka Ra226Be")
        addItem(NTechItems.pu238BeBillet, "Pastylka Pu238Be")
        addItem(NTechItems.zirconiumBillet, "Pastylka Cyrkonu")
        addItem(NTechItems.bismuthZfbBillet, "Pastylka Bizmutu ZFB")
        addItem(NTechItems.pu241ZfbBillet, "Pastylka Plutonu-241 ZFB")
        addItem(NTechItems.reactorGradeAmericiumZfbBillet, "Pastylka Ameryku ZFB Klasy Reaktora")
        addItem(NTechItems.yharoniteBillet, "Pastylka Yharonitu")
        addItem(NTechItems.flashgoldBillet, "Pastylka Flashgold")
        addItem(NTechItems.flashleadBillet, "Pastylka Flashlead")
        addItemDesc(NTechItems.flashleadBillet, "Sieć się rozpada, tworząc reakcje anihilacji materii i antymaterii,\npowodując tworzenie pionów, które się rozpadają na miony,\nkatalizujące fuzję jąder nuklearnych, tworzących nowy element.\nPostaraj się nadążyć.")

        addItem(NTechItems.mercuryDroplet, "Kropla Rtęci")
        addItem(NTechItems.mercuryBottle, "Butelka Rtęci")

        addItem(NTechItems.coke, "Koks")
        addItem(NTechItems.lignite, "Węgiel Brunatny")
        addItem(NTechItems.ligniteBriquette, "Brykiet z Węgla Brunatnego")

        addItem(NTechItems.sulfur, "Siarka")
        addItem(NTechItems.niter, "Saletra")
        addItem(NTechItems.fluorite, "Fluoryt")
        addItem(NTechItems.quartzPowder, "Proszek Kwarcu")
        addItem(NTechItems.yellowcake, "Yellowcake")
        addItem(NTechItems.chlorophytePowder, "Proszek Chlorofitu")
        addItem(NTechItems.neodymiumPowder, "Proszek Neodymu")
        addItem(NTechItems.niobiumPowder, "Proszek Niobu")
        addItem(NTechItems.ceriumPowder, "Proszek Ceru")
        addItemDesc(NTechItems.asbestosPowder, "§o„Sniffffffff - MHHHHHHMHHHHHHHHH“")
        addItem(NTechItems.enchantmentPowder, "Proszek Zaklęcia")
        addItem(NTechItems.cloudResidue, "Pozostałość po Chmurze")
        addItem(NTechItems.thermonuclearAshes, "Proch Termojądrowy")
        addItem(NTechItems.semtexMix, "Mieszanka Semtex")
        addItem(NTechItems.deshMix, "Mieszanka Deszu")
        addItem(NTechItems.deshReadyMix, "Mieszanka DeshReady™")
        addItem(NTechItems.nitaniumMix, "Mieszanka Nitanu")
        addItem(NTechItems.sparkMix, "Mieszanka Spark")
        addItem(NTechItems.meteoritePowder, "Proszek Meteorytowy")
        addItemDesc(NTechItems.euphemiumPowder, "Sproszkowany róż.\nSmakuje jak truskawki.")
        addItem(NTechItems.desaturatedRedstone, "Desaturowany Redstone")
        addItem(NTechItems.dust, "Kurz")
        addItemDesc(NTechItems.dust, "Nie cierpię kurzu!")
        addItem(NTechItems.tinyLithiumPowder, "Malutki Proszek Litu")
        addItem(NTechItems.tinyNeodymiumPowder, "Malutki Proszek Neodymu")
        addItem(NTechItems.tinyCobaltPowder, "Malutki Proszek Kobaltu")
        addItem(NTechItems.tinyNiobiumPowder, "Malutki Proszek Niobu")
        addItem(NTechItems.tinyCeriumPowder, "Malutki Proszek Ceru")
        addItem(NTechItems.tinyLanthanumPowder, "Malutki Proszek Lantanu")
        addItem(NTechItems.tinyActiniumPowder, "Malutki Proszek Aktynu")
        addItem(NTechItems.tinyMeteoritePowder, "Malutki Proszek Meteorytu")
        addItem(NTechItems.redPhosphorus, "Czerwony Fosfor")
        addItemDesc(NTechItems.redPhosphorus, "Używany w bombach wielofunkcyjnych:\nBomby zapalające są śmieszne!")
        addItem(NTechItems.cryoPowder, "Proszek Kriogeniczny")
        addItem(NTechItems.poisonPowder, "Proszek Trucizny")
        addItemDesc(NTechItems.poisonPowder, "Używany w bombach wielofunkcyjnych:\nUwaga: Trujące!")
        addItem(NTechItems.thermite, "Termit")
        addItem(NTechItems.energyPowder, "Proszek Energii")

        addItem(NTechItems.cordite, "Kordyt")
        addItem(NTechItems.ballistite, "Balistyt")

        addItem(NTechItems.rareEarthCrystals, "Kryształ Metali Ziem Rzadkich")
        addItem(NTechItems.redPhosphorusCrystals, "Kryształ Czerwonego Fosforu")
        addItem(NTechItems.trixiteCrystals, "Kryształy Trycytu")

        addItem(NTechItems.volcanicGem, "Klejnot Wulkaniczny")

        addItem(NTechItems.neodymiumFragment, "Fragment Neodymu")
        addItem(NTechItems.cobaltFragment, "Fragment Kobaltu")
        addItem(NTechItems.niobiumFragment, "Fragment Niobu")
        addItem(NTechItems.ceriumFragment, "Fragment Ceru")
        addItem(NTechItems.lanthanumFragment, "Fragment Lantanu")
        addItem(NTechItems.actiniumFragment, "Fragment Aktynu")
        addItem(NTechItems.meteoriteFragment, "Fragment Meteorytu")

        addItem(NTechItems.biomass, "Biomasa")
        addItem(NTechItems.compressedBiomass, "Sprasowana Biomasa")

        addItemDesc(
            NTechItems.euphemiumNugget,
            "Mały kawałek różowego metalu.\n" +
                "Właściwości nadal nieznane,\n" +
                "POSTĘPUJ Z TYM ostrożnie."
        )

        addItem(NTechItems.neutronReflector, "Reflektor Neutronów")
        addItem(NTechItems.mixedPlate, "Mieszana Płytka")
        addItem(NTechItems.paAAlloyPlate, "Płytka ze Stopu PaA")
        addItem(NTechItems.insulator, "Izolator")
        addItem(NTechItems.kevlarCeramicCompound, "Mieszanka Kevlarowo-Ceramiczna")
        addItem(NTechItems.dalekaniumPlate, "Gniewny Metal")
        addItem(NTechItems.deshCompoundPlate, "Płytka Mieszanki Desz")
        addItem(NTechItems.euphemiumCompoundPlate, "Płytka Mieszanki Euphemium")
        addItem(NTechItems.dineutroniumCompoundPlate, "Płytka Mieszanki Dineutronium")
        addItem(NTechItems.copperPanel, "Płyta z Miedzi")

        addItem(NTechItems.highSpeedSteelBolt, "Pręt ze Stali Szybkotnącej")
        addItem(NTechItems.tungstenBolt, "Pręt z Wolframu")
        addItem(NTechItems.reinforcedTurbineShaft, "Wzmocniony Wał Turbiny")

        addItem(NTechItems.hazmatCloth, "Płótno Hazmat")
        addItem(NTechItems.advancedHazmatCloth, "Zaawansowane Płótno Hazmat")
        addItem(NTechItems.leadReinforcedHazmatCloth, "Wzmocnione Ołowiem Płótno Hazmat")
        addItem(NTechItems.fireProximityCloth, "Płótno Bliskości Pożaru")
        addItem(NTechItems.activatedCarbonFilter, "Filtr z Węglem Aktywnym")

        addItem(NTechItems.superConductor, "Nadprzewodnik")
        addItem(NTechItems.highTemperatureSuperConductor, "Nadprzewodnik Wysokotemperaturowy 4000K")

        addItem(NTechItems.copperCoil, "Miedziana Cewka")
        addItem(NTechItems.ringCoil, "Cewka Pierścieniowa")
        addItem(NTechItems.superConductingCoil, "Cewka Nadprzewodnikowa")
        addItem(NTechItems.superConductingRingCoil, "Nadprzewodnikowa Cewka Pierścieniowa")
        addItem(NTechItems.goldCoil, "Złota Cewka")
        addItem(NTechItems.goldRingCoil, "Złota Cewka Pierścieniowa")
        addItem(NTechItems.heatingCoil, "Cewka Grzewcza")
        addItem(NTechItems.highTemperatureSuperConductingCoil, "Cewka Nadprzewodnikowa Wysokotemperaturowa 4000K")

        addItem(NTechItems.steelTank, "Zbiornik Stalowy")
        addItem(NTechItems.motor, "Silnik Elektryczny")
        addItem(NTechItems.centrifugeElement, "Element Wirówki")
        addItem(NTechItems.centrifugeTower, "Wieża Wirówki")
        addItem(NTechItems.deeMagnets, "Magnesy Dee")
        addItem(NTechItems.flatMagnet, "Płaski Magnes")
        addItem(NTechItems.cyclotronTower, "Wieża Cyklotronu")
        addItem(NTechItems.breedingReactorCore, "Rdzeń Reaktora Hodowlanego")
        addItem(NTechItems.rtgUnit, "Element RTG")
        addItem(NTechItems.thermalDistributionUnit, "Element Dystrybucji Ciepła")
        addItem(NTechItems.endothermicDistributionUnit, "Element Dystrybucji Endotermicznej")
        addItem(NTechItems.exothermicDistributionUnit, "Element Dystrybucji Egzotermicznej")
        addItem(NTechItems.gravityManipulator, "Manipulator Grawitacji")
        addItem(NTechItems.steelPipes, "Stalowe Rury")
        addItem(NTechItems.titaniumDrill, "Wiertło Tytanowe")
        addItem(NTechItems.photovoltaicPanel, "Panel Fotowoltaiczny")
        addItem(NTechItems.chlorinePinwheel, "Wiatrak Chloru")
        addItem(NTechItems.telepad, "Telepad")
        addItem(NTechItems.entanglementKit, "Zestaw do Plątania")
        addItemDesc(
            NTechItems.entanglementKit,
            "Element rzemieślniczy teleportera.\n" +
                "Umożliwia zmianę wymiarów za pomocą\n" +
                "skanera zasobów wzmocnionych berylem."
        )
        addItem(NTechItems.stabilizerComponent, "Komponent Stabilizatora")
        addItem(NTechItems.emitterComponent, "Komponent Emitera")
        addItem(NTechItems.aluminiumCap, "Czapka Aluminiowa")
        addItem(NTechItems.smallSteelShell, "Mała Stalowa Powłoka")
        addItem(NTechItems.smallAluminiumShell, "Mała Aluminiowa Powłoka")
        addItem(NTechItems.bigSteelShell, "Duża Stalowa Powłoka")
        addItem(NTechItems.bigAluminiumShell, "Duża Stalowa Powłoka")
        addItem(NTechItems.bigTitaniumShell, "Duża Tytanowa Powłoka")
        addItem(NTechItems.flatSteelCasing, "Płaska Stalowa Obudowa")
        addItem(NTechItems.smallSteelGridFins, "Małe Stalowe Stateczniki Siatkowe")
        addItem(NTechItems.bigSteelGridFins, "Duże Stalowe Stateczniki Siatkowe")
        addItem(NTechItems.largeSteelFins, "Duże Stalowe Stateczniki")
        addItem(NTechItems.smallTitaniumFins, "Małe Tytanowe Stateczniki")
        addItem(NTechItems.steelSphere, "Stalowa Sfera")
        addItem(NTechItems.steelPedestal, "Stalowy Piedestał")
        addItem(NTechItems.dysfunctionalNuclearReactor, "Dysfunkcjonalny Reaktor Nuklearny")
        addItem(NTechItems.largeSteelRotor, "Duży Stalowy Rotor")
        addItem(NTechItems.generatorBody, "Ciało Generatora")
        addItem(NTechItems.titaniumBlade, "Tytanowe Ostrze")
        addItem(NTechItems.tungstenReinforcedBlade, "Ostrze Wzmocnione Wolframem")
        addItem(NTechItems.titaniumSteamTurbine, "Tytanowa Turbina Parowa")
        addItem(NTechItems.reinforcedTurbofanBlades, "Wzmocnione Ostrza Turbofan")
        addItem(NTechItems.generatorFront, "Front Generatora")
        addItem(NTechItems.toothpicks, "Wykałaczki")
        addItem(NTechItems.ductTape, "Taśma Klejąca")
        addItem(NTechItems.clayCatalyst, "Katalizator Gliniany")
        addItem(NTechItems.smallMissileAssembly, "Mały Montaż Rakietowy")

        addItem(NTechItems.smallWarhead, "Mała Głowica")
        addItem(NTechItems.mediumWarhead, "Średnia Głowica")
        addItem(NTechItems.largeWarhead, "Duża Głowica")
        addItem(NTechItems.smallIncendiaryWarhead, "Mała Głowica Zapalająca")
        addItem(NTechItems.mediumIncendiaryWarhead, "Średnia Głowica Zapalająca")
        addItem(NTechItems.largeIncendiaryWarhead, "Duża Głowica Zapalająca")
        addItem(NTechItems.smallClusterWarhead, "Mała Głowica Kasetowa")
        addItem(NTechItems.mediumClusterWarhead, "Średnia Głowica Kasetowa ")
        addItem(NTechItems.largeClusterWarhead, "Duża Głowica Kasetowa")
        addItem(NTechItems.smallBunkerBusterWarhead, "Mała Głowica do Niszczenia Bunkrów")
        addItem(NTechItems.mediumBunkerBusterWarhead, "Średnia Głowica do Niszczenia Bunkrów")
        addItem(NTechItems.largeBunkerBusterWarhead, "Duża Głowica do Niszczenia Bunkrów")
        addItem(NTechItems.nuclearWarhead, "Głowica Jądrowa")
        addItem(NTechItems.thermonuclearWarhead, "Głowica Termojądrowa")
        addItem(NTechItems.endothermicWarhead, "Głowica Endotermiczna")
        addItem(NTechItems.exothermicWarhead, "Głowica Egzotermiczna")

        addItem(NTechItems.smallFuelTank, "Mały Zbiornik Paliwa")
        addItem(NTechItems.mediumFuelTank, "Średni Zbiornik Paliwa")
        addItem(NTechItems.largeFuelTank, "Duży Zbiornik Paliwa")

        addItem(NTechItems.smallThruster, "Mały Silnik Rakietowy")
        addItem(NTechItems.mediumThruster, "Średni Silnik Rakietowy")
        addItem(NTechItems.largeThruster, "Duży Silnik Rakietowy")
        addItem(NTechItems.lvnNuclearRocketEngine, "LV-N Jądrowy Silnik Rakietowy")

        addItem(NTechItems.satelliteBase, "Baza Satelitarna")
        addItem(NTechItems.highGainOpticalCamera, "Kamera Optyczna o Dużym Wzmocnieniu")
        addItem(NTechItems.m700SurveyScanner, "Skaner Przeglądowy M700")
        addItem(NTechItems.radarDish, "Antena Radarowa")
        addItem(NTechItems.deathRay, "Promień Śmierci")
        addItem(NTechItems.xeniumResonator, "Rezonator Xenium")

        addItem(NTechItems.size10Connector, "Łącznik Rozmiaru 10")
        addItem(NTechItems.size15Connector, "Łącznik Rozmiaru 15")
        addItem(NTechItems.size20Connector, "Łącznik Rozmiaru 20")

        addItem(NTechItems.hunterChopperCockpit, "Kokpit Hunter Choppera")
        addItem(NTechItems.emplacementGun, "Działo Pulsacyjne")
        addItem(NTechItems.hunterChopperBody, "Ciało Hunter Choppera")
        addItem(NTechItems.hunterChopperTail, "Tył Hunter Choppera")
        addItem(NTechItems.hunterChopperWing, "Skrzydło Hunter Choppera")
        addItem(NTechItems.hunterChopperRotorBlades, "Rotor Hunter Choppera")
        addItem(NTechItems.combineScrapMetal, "Złom Metalu Kombinatu")

        addItem(NTechItems.heavyHammerHead, "Ciężka Głowa Młota")
        addItem(NTechItems.heavyAxeHead, "Ciężka Głowa Siekiery")
        addItem(NTechItems.reinforcedPolymerHandle, "Wzmocniony Uchwyt Polimerowy")

        addItem(NTechItems.basicCircuitAssembly, "Montaż Podstawowego Obwodu Elektrycznego")
        addItem(NTechItems.basicCircuit, "Podstawowy Obwód Elektryczny")
        addItem(NTechItems.enhancedCircuit, "Ulepszony Obwód Elektryczny")
        addItem(NTechItems.advancedCircuit, "Zaawansowany Obwód Elektryczny")
        addItem(NTechItems.overclockedCircuit, "Przetaktowany Obwód Elektryczny")
        addItem(NTechItems.highPerformanceCircuit, "Wysoko Wydajnościowy Obwód Elektryczny")
        addItem(NTechItems.militaryGradeCircuitBoardTier1, "Obwód Elektryczny Klasy Wojennej (Poziom 1)")
        addItem(NTechItems.militaryGradeCircuitBoardTier2, "Obwód Elektryczny Klasy Wojennej (Poziom 2)")
        addItem(NTechItems.militaryGradeCircuitBoardTier3, "Obwód Elektryczny Klasy Wojennej (Poziom 3)")
        addItem(NTechItems.militaryGradeCircuitBoardTier4, "Obwód Elektryczny Klasy Wojennej (Poziom 4)")
        addItem(NTechItems.militaryGradeCircuitBoardTier5, "Obwód Elektryczny Klasy Wojennej (Poziom 5)")
        addItem(NTechItems.militaryGradeCircuitBoardTier6, "Obwód Elektryczny Klasy Wojennej (Poziom 6)")

        addItem(NTechItems.revolverMechanism, "Mechanizm Rewolwera")
        addItem(NTechItems.advancedRevolverMechanism, "Zaawansowany Mechanizm Rewolwera")
        addItem(NTechItems.rifleMechanism, "Mechanizm Karabinu")
        addItem(NTechItems.advancedRifleMechanism, "Zaawansowany Mechanizm Karabinu")
        addItem(NTechItems.launcherMechanism, "Mechanizm Wyrzutni")
        addItem(NTechItems.advancedLauncherMechanism, "Zaawansowany Mechanizm Wyrzutni")
        addItem(NTechItems.highTechWeaponMechanism, "Zaawansowany Technologicznie Mechanizm Broni")

        addItem(NTechItems.point357MagnumPrimer, "Spłonka Magnum .357 (x16)")
        addItem(NTechItems.point44MagnumPrimer, "Spłonka Magnum .44 (x16)")
        addItem(NTechItems.smallCaliberPrimer, "Spłonka Małego Kalibru (x24)")
        addItem(NTechItems.largeCaliberPrimer, "Spłonka Dużego Kalibru (x8)")
        addItem(NTechItems.buckshotPrimer, "Słonka Buckshot (x8)")

        addItem(NTechItems.point357MagnumCasing, "Obudowa Magnum .357 (x16)")
        addItem(NTechItems.point44MagnumCasing, "Obudowa Magnum .44 (x16)")
        addItem(NTechItems.smallCaliberCasing, "Obudowa Małego Kalibru (x24)")
        addItem(NTechItems.largeCaliberCasing, "Obudowa Dużego Kalibru (x8)")
        addItem(NTechItems.buckshotCasing, "Obudowa Buckshot (x8)")

        addItem(NTechItems.ironBulletAssembly, "Montaż Żelaznego Pocisku")
        addItem(NTechItems.leadBulletAssembly, "Montaż Ołowianego Pocisku")
        addItem(NTechItems.glassBulletAssembly, "Montaż Szklanego Pocisku")
        addItem(NTechItems.goldBulletAssembly, "Montaż Złotego Pocisku")
        addItem(NTechItems.schrabidiumBulletAssembly, "Montaż Pocisku ze Schrabidium")
        addItem(NTechItems.nightmareBulletAssembly, "Montaż Koszmarnego Pocisku")
        addItem(NTechItems.deshBulletAssembly, "Montaż Pocisku z Deszu")
        addItem(NTechItems.point44MagnumAssembly, "Montaż Pocisku Magnum .44")
        addItem(NTechItems.nineMmAssembly, "Montaż Pocisku 9mm")
        addItem(NTechItems.fivePoint56mmAssembly, "Montaż Pocisku 5.56mm")
        addItem(NTechItems.point22LRAssembly, "Montaż Pocisku .22 LR")
        addItem(NTechItems.point5mmAssembly, "Montaż Pocisku .5mm")
        addItem(NTechItems.point50AEAssembly, "Montaż Pocisku .50 AE")
        addItem(NTechItems.point50BMGAssembly, "Montaż Pocisku .50 BMG")

        addItem(NTechItems.silverBulletCasing, "Obudowa Srebrnego Pocisku")
        addItem(NTechItems.twelvePoint8cmStarmetalHighEnergyShell, "Pocisk ze GwiazdoMetalu o Wysokiej Energii 12.8cm")
        addItem(NTechItems.twelvePoint8cmNuclearShell, "Pocisk Nuklearny 12.8cm")
        addItem(NTechItems.twelvePoint8cmDUShell, "Pocisk DU 12.8cm")

        addItem(NTechItems.cableDrum, "Bęben Kabli")
        addItemDesc(NTechItems.cableDrum, "Naciśnij słupy prawym przyciskiem myszy, żeby połączyć")
        addItem(NTechItems.paintingOfACartoonPony, "Obraz Kreskówkego Kucyka")
        addItemDesc(NTechItems.paintingOfACartoonPony, "Żółty kucyk pokonuje niebieskiego, jest to potwierdzone!")
        addItem(NTechItems.conspiracyTheory, "Teoria Spiskowa")
        addItemDesc(NTechItems.conspiracyTheory, "Stalowe pręty nie potrafią topić paliwa odrzutowego!")
        addItem(NTechItems.politicalTopic, "Temat Polityczny")
        addItemDesc(NTechItems.politicalTopic, "Kaczor Donald wybuduje ścianę!")
        addItem(NTechItems.ownOpinion, "Własna Opinia")
        addItemDesc(NTechItems.ownOpinion, "No, ja tam to lubię...")

        addItem(NTechItems.explosivePellets, "Wybuchowe Pellety")
        addItemDesc(NTechItems.explosivePellets, "Używane w bombach wielofunkcyjnych:\nDodaje ekstra bum!")
        addItem(NTechItems.leadPellets, "Pellety Ołowiane")
        addItem(NTechItems.flechettes, "Fleszetki")
        addItem(NTechItems.poisonGasCartridge, "Nabój z Gazem Trującym")
        addItemDesc(NTechItems.poisonGasCartridge, "Używany w bombach wielofunkcyjnych:\n*cough cough* Pomóż pls!")
        addItem(NTechItems.magnetron, "Magnetron")
        addItem(NTechItems.denseCoalCluster, "Gęsta Kępa Węgla")
        addItem(NTechItems.burntBark, "Spalona Kora")
        addItemDesc(NTechItems.burntBark, "Kawałek kory z eksplodowanego drzewa złotego dębu.")
        addItem(NTechItems.machineUpgradeTemplate, "Szablon Ulepszacza Maszyn")

        addItem(NTechItems.blankRune, "Pusta Matryca Katalizatora")
        addItem(NTechItems.isaRune, "Zimna Matryca Katalizatora")
        addItem(NTechItems.dagazRune, "Zrównoważona Matryca Katalizatora")
        addItem(NTechItems.hagalazRune, "Szorstka Matryca Katalizatora")
        addItem(NTechItems.jeraRune, "Multiplikatywna Matryca Katalizatora")
        addItem(NTechItems.thurisazRune, "Dodatkowa Matryca Katalizatora")

        addItem(NTechItems.burnedOutQuadSchrabidiumFuelRod, "Wypalony Poczwórny Pręt Paliwowy Schrabidium")
        addItemDesc(NTechItems.burnedOutQuadSchrabidiumFuelRod, "Poczwórny pręt paliwowy, który zawiera\nbardzo małą ilość dziwnego nowego elementu.")

        addItem(NTechItems.scrap, "Złom")
        addItem(NTechItems.hotDepletedUraniumFuel, "Wypalone Gorące Paliwo Uranu")
        addItem(NTechItems.hotDepletedThoriumFuel, "Wypalone Gorące Paliwo Toru")
        addItem(NTechItems.hotDepletedPlutoniumFuel, "Wypalone Gorące Paliwo Plutonu")
        addItem(NTechItems.hotDepletedMOXFuel, "Wypalone Gorące Paliwo MOX")
        addItem(NTechItems.hotDepletedSchrabidiumFuel, "Wypalone Gorące Paliwo Schrabidium")
        addItem(NTechItems.depletedUraniumFuel, "Wypalone Paliwo Uranu")
        addItem(NTechItems.depletedThoriumFuel, "Wypalone Paliwo Toru")
        addItem(NTechItems.depletedPlutoniumFuel, "Wypalone Paliwo Plutonu")
        addItem(NTechItems.depletedMOXFuel, "Wypalone Paliwo MOX")
        addItem(NTechItems.depletedSchrabidiumFuel, "Wypalone Paliwo Schrabidium")
        addItem(NTechItems.trinitite, "Trynityt")
        addItem(NTechItems.nuclearWaste, "Odpady Nuklearne")
        addItem(NTechItems.tinyNuclearWaste, "Mała Ilość Odpadów Nuklearnych")

        addItem(NTechItems.crystalHorn, "Kryształowy Róg")
        addItemDesc(NTechItems.crystalHorn, "Tak naprawdę nie prawdziwy Róg")
        addItem(NTechItems.charredCrystal, "Zwęglony Kryształ")
        addItemDesc(NTechItems.charredCrystal, "Też nie prawdziwy. Dziwnę prawda?")

        addItem(NTechItems.battery, "Bateria")
        addItem(NTechItems.redstonePowerCell, "Ogniwo Zasilające z Redstone")
        addItem(NTechItems.sixfoldRedstonePowerCell, "Sześciokrotne Ogniwo Zasilające z Redstone")
        addItem(NTechItems.twentyFourFoldRedstonePowerCell, "24-krotne Ogniwo Zasilające z Redstone")
        addItem(NTechItems.advancedBattery, "Zaawansowana Bateria")
        addItem(NTechItems.advancedPowerCell, "Zaawansowane Ogniwo Zasilające")
        addItem(NTechItems.quadrupleAdvancedPowerCell, "Poczwórne Zaawansowane Ogniwo Zasilające")
        addItem(NTechItems.twelveFoldAdvancedPowerCell, "12-krotne Zaawansowane Ogniwo Zasilające ")
        addItem(NTechItems.lithiumBattery, "Bateria Litowo-Jonowa")
        addItem(NTechItems.lithiumPowerCell, "Ogniwo Zasilające Litowo-Jonowe")
        addItem(NTechItems.tripleLithiumPowerCell, "Potrójne Ogniwo Zasilające Litowo-Jonowe")
        addItem(NTechItems.sixfoldLithiumPowerCell, "Sześciokrotne Ogniwo Zasilające Litowo-Jonowe")
        addItem(NTechItems.schrabidiumBattery, "Bateria z Schrabidium")
        addItem(NTechItems.schrabidiumPowerCell, "Ogniwo Zasilające z Schrabidium")
        addItem(NTechItems.doubleSchrabidiumPowerCell, "Podwójne Ogniwo z Zasilające Schrabidium")
        addItem(NTechItems.quadrupleSchrabidiumPowerCell, "Poczwórne Ogniwo Zasilające z Schrabidium")
        addItem(NTechItems.sparkBattery, "Bateria Spark")
        addItem(NTechItems.offBrandSparkBattery, "Podrabiana Bateria Spark")
        addItem(NTechItems.sparkPowerCell, "Ogniwo zasilające Spark")
        addItem(NTechItems.sparkArcaneCarBattery, "Tajemny Akumulator Spark")
        addItem(NTechItems.sparkArcaneEnergyStorageArray, "Tajemny Układ Magazynowania Energii Spark")
        addItem(NTechItems.sparkArcaneMassEnergyVoid, "Tajemna Energia Masy Pustki Spark")
        addItem(NTechItems.sparkArcaneDiracSea, "Tajemne Morze Diraca Spark")
        addItem(NTechItems.sparkSolidSpaceTimeCrystal, "Solidny Kryształ Czasoprzestrzeni Spark")
        addItem(NTechItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit, "Absurdalna Sprzeciwiająca się Fizyce Jednostka Magazynowania Energii Spark")
        addItem(NTechItems.infiniteBattery, "Nieskończona Bateria")
        addItem(NTechItems.singleUseBattery, "Bateria Jednorazowa")
        addItem(NTechItems.largeSingleUseBattery, "Duża Bateria Jednorazowa")
        addItem(NTechItems.potatoBattery, "Bateria z Ziemniaka")
        addItem(NTechItems.steamPoweredEnergyStorageTank, "Zbiornik Magazynowania Energii Napędzany Parą Wodną")
        addItem(NTechItems.largeSteamPoweredEnergyStorageTank, "Duży Zbiornik Magazynowania Energii Napędzany Parą Wodną")

        addItem(NTechItems.stoneFlatStamp, "Kamienny Element Tłoczny (Płaski)")
        addItem(NTechItems.stonePlateStamp, "Kamienny Element Tłoczny (Płytka)")
        addItem(NTechItems.stoneWireStamp, "Kamienny Element Tłoczny (Drut)")
        addItem(NTechItems.stoneCircuitStamp, "Kamienny Element Tłoczny (Obwód Elektryczny)")
        addItem(NTechItems.ironFlatStamp, "Żelazny Element Tłoczny (Płaski)")
        addItem(NTechItems.ironPlateStamp, "Żelazny Element Tłoczny (Płytka)")
        addItem(NTechItems.ironWireStamp, "Żelazny Element Tłoczny (Drut)")
        addItem(NTechItems.ironCircuitStamp, "Żelazny Element Tłoczny (Obwód Elektryczny)")
        addItem(NTechItems.steelFlatStamp, "Stalowy Element Tłoczny (Płaski)")
        addItem(NTechItems.steelPlateStamp, "Stalowy Element Tłoczny (Płytka)")
        addItem(NTechItems.steelWireStamp, "Stalowy Element Tłoczny (Drut)")
        addItem(NTechItems.steelCircuitStamp, "Stalowy Element Tłoczny (Obwód Elektryczny)")
        addItem(NTechItems.titaniumFlatStamp, "Tytanowy Element Tłoczny (Płaski)")
        addItem(NTechItems.titaniumPlateStamp, "Tytanowy Element Tłoczny (Płytka)")
        addItem(NTechItems.titaniumWireStamp, "Tytanowy Element Tłoczny (Drut)")
        addItem(NTechItems.titaniumCircuitStamp, "Tytanowy Element Tłoczny (Obwód Elektryczny)")
        addItem(NTechItems.obsidianFlatStamp, "Obsydianowy Element Tłoczny (Płaski)")
        addItem(NTechItems.obsidianPlateStamp, "Obsydianowy Element Tłoczny (Płytka)")
        addItem(NTechItems.obsidianWireStamp, "Obsydianowy Element Tłoczny (Drut)")
        addItem(NTechItems.obsidianCircuitStamp, "Obsydianowy Element Tłoczny (Obwód Elektryczny)")
        addItem(NTechItems.schrabidiumFlatStamp, "Schrabidianowy Element Tłoczny (Płaski)")
        addItem(NTechItems.schrabidiumPlateStamp, "Schrabidianowy Element Tłoczny (Płytka)")
        addItem(NTechItems.schrabidiumWireStamp, "Schrabidianowy Element Tłoczny (Drut)")
        addItem(NTechItems.schrabidiumCircuitStamp, "Schrabidianowy Element Tłoczny (Obwód Elektryczny)")

        addItem(NTechItems.screwdriver, "Śrubokręt")
        addItemDesc(NTechItems.screwdriver, "Może być użyty zamiast bezpiecznika...")
        addItem(NTechItems.deshScrewdriver, "Śrubokręt z Deszu")

        addItem(NTechItems.speedUpgradeMk1, "Ulepszacz Prędkości Mk.I")
        addItem(NTechItems.speedUpgradeMk2, "Ulepszacz Prędkości Mk.II")
        addItem(NTechItems.speedUpgradeMk3, "Ulepszacz Prędkości Mk.III")
        addItem(NTechItems.powerSavingUpgradeMk1, "Ulepszacz Oszczędzania Energii Mk.I")
        addItem(NTechItems.powerSavingUpgradeMk2, "Ulepszacz Oszczędzania Energii Mk.II")
        addItem(NTechItems.powerSavingUpgradeMk3, "Ulepszacz Oszczędzania Energii Mk.III")
        addItem(NTechItems.overdriveUpgradeMk1, "Ulepszacz Przesterowania Mk.I")
        addItem(NTechItems.overdriveUpgradeMk2, "Ulepszacz Przesterowania Mk.II")
        addItem(NTechItems.overdriveUpgradeMk3, "Ulepszacz Przesterowania Mk.III")
        addItem(NTechItems.afterBurnUpgradeMk1, "Ulepszacz Dopalacza Mk.I")
        addItem(NTechItems.afterBurnUpgradeMk2, "Ulepszacz Dopalacza Mk.II")
        addItem(NTechItems.afterBurnUpgradeMk3, "Ulepszacz Dopalacza Mk.III")

        addItem(NTechItems.aluminiumShredderBlade, "Aluminiowe Ostrze Strzępiarki")
        addItem(NTechItems.goldShredderBlade, "Złote Ostrze Strzępiarki")
        addItem(NTechItems.ironShredderBlade, "Żelazne Ostrze Strzępiarki")
        addItem(NTechItems.steelShredderBlade, "Stalowe Ostrze Strzępiarki")
        addItem(NTechItems.titaniumShredderBlade, "Tytanowe Ostrze Strzępiarki")
        addItem(NTechItems.advancedAlloyShredderBlade, "Ostrze Strzępiarki z Zaawansowanego Stopu")
        addItem(NTechItems.combineSteelShredderBlade, "Ostrze Strzępiarki z Metalu Kombinatu")
        addItem(NTechItems.schrabidiumShredderBlade, "Ostrze Strzępiarki z Schrabidium")
        addItem(NTechItems.deshShredderBlade, "Ostrze Strzępiarki z Deszu")

        addItem(NTechItems.rbmkLid, "Panel Osłonowy RBMK")
        addItem(NTechItems.rbmkGlassLid, "Szklany Panel Osłonowy RBMK")

        addItem(NTechItems.rbmkPelletBalefire, "Pastylki Paliwa Balefire")
        addItem(NTechItems.rbmkPelletBalefireGold, "Pastylki Paliwa Flashgold")
        addItem(NTechItems.rbmkPelletDrx, "§cPastylki Paliwa Digamma§r")
        addItem(NTechItems.rbmkPelletFlashlead, "Pastylki Paliwa Flashlead")
        addItem(NTechItems.rbmkPelletHea241, "Pastylki Paliwa HEA-241")
        addItem(NTechItems.rbmkPelletHea242, "Pastylki Paliwa HEA-242")
        addItem(NTechItems.rbmkPelletHeaus, "Pastylki Paliwa HEAus")
        addItem(NTechItems.rbmkPelletHen, "Pastylki Paliwa HEN")
        addItem(NTechItems.rbmkPelletHes, "Pastylki Paliwa HEP-239")
        addItem(NTechItems.rbmkPelletHep239, "Pastylki Paliwa HEP-241")
        addItem(NTechItems.rbmkPelletHep241, "Pastylki Paliwa HEU-233")
        addItem(NTechItems.rbmkPelletHeu233, "Pastylki Paliwa HEU-235")
        addItem(NTechItems.rbmkPelletHeu235, "Pastylki Paliwa HES")
        addItem(NTechItems.rbmkPelletLea, "Pastylki Paliwa LEA")
        addItem(NTechItems.rbmkPelletLeaus, "Pastylki Paliwa LEAus")
        addItem(NTechItems.rbmkPelletLep, "Pastylki Paliwa LEP")
        addItem(NTechItems.rbmkPelletLes, "Pastylki Paliwa LES")
        addItem(NTechItems.rbmkPelletMea, "Pastylki Paliwa MEA")
        addItem(NTechItems.rbmkPelletMen, "Pastylki Paliwa MEN")
        addItem(NTechItems.rbmkPelletMep, "Pastylki Paliwa MEP")
        addItem(NTechItems.rbmkPelletMes, "Pastylki Paliwa MES")
        addItem(NTechItems.rbmkPelletMeu, "Pastylki Paliwa MEU")
        addItem(NTechItems.rbmkPelletMox, "Pastylki Paliwa MOX")
        addItem(NTechItems.rbmkPelletPo210Be, "Pastylki Paliwa Po210Be")
        addItem(NTechItems.rbmkPelletPu238Be, "Pastylki Paliwa Pu238Be")
        addItem(NTechItems.rbmkPelletRa226Be, "Pastylki Paliwa Ra226Be")
        addItem(NTechItems.rbmkPelletThMeu, "Pastylki Paliwa ThMEU")
        addItem(NTechItems.rbmkPelletUeu, "Pastylki Paliwa NU")
        addItem(NTechItems.rbmkPelletZfbAmMix, "Pastylki ZFB Ameryku Klasy Paliwowej")
        addItem(NTechItems.rbmkPelletZfbBismuth, "Pastylki Bizmutu ZFB")
        addItem(NTechItems.rbmkPelletZfbPu241, "Pastylki Pu-241 ZFB")

        addItem(NTechItems.emptyRBMKRod, "Pusty Pręt Paliwowy RBMK")
        addItem(NTechItems.rbmkRodBalefire, "Pręt Paliwowy Balefire RBMK")
        addItem(NTechItems.rbmkRodBalefireGold, "Pręt Paliwowy Flashgold RBMK")
        addItem(NTechItems.rbmkRodDrx, "§cPręt Paliwowy Digamma RBMK§r")
        addItem(NTechItems.rbmkRodFlashlead, "Pręt Paliwowy Flashlead RBMK")
        addItem(NTechItems.rbmkRodHea241, "Pręt Paliwowy HEA-241 RBMK")
        addItem(NTechItems.rbmkRodHea242, " Pręt Paliwowy HEA-242 RBMK")
        addItem(NTechItems.rbmkRodHeaus, "Pręt Paliwowy  HEAus RBMK")
        addItem(NTechItems.rbmkRodHen, "Pręt Paliwowy HEN RBMK")
        addItem(NTechItems.rbmkRodHes, "Pręt Paliwowy HES RBMK")
        addItem(NTechItems.rbmkRodHep239, "Pręt Paliwowy HEP-239 RBMK")
        addItem(NTechItems.rbmkRodHep241, "Pręt Paliwowy HEP-241 RBMK")
        addItem(NTechItems.rbmkRodHeu233, "Pręt Paliwowy HEU-233 RBMK")
        addItem(NTechItems.rbmkRodHeu235, "Pręt Paliwowy HEU-235 RBMK")
        addItem(NTechItems.rbmkRodLea, "Pręt Paliwowy LEA RBMK")
        addItem(NTechItems.rbmkRodLeaus, "Pręt Paliwowy LEAus RBMK")
        addItem(NTechItems.rbmkRodLep, "Pręt Paliwowy LEP-239 RBMK")
        addItem(NTechItems.rbmkRodLes, "Pręt Paliwowy LES RBMK")
        addItem(NTechItems.rbmkRodMea, "Pręt Paliwowy MEA RBMK")
        addItem(NTechItems.rbmkRodMen, "Pręt Paliwowy MEN RBMK")
        addItem(NTechItems.rbmkRodMep, "Pręt Paliwowy MEP-239 RBMK")
        addItem(NTechItems.rbmkRodMes, "Pręt Paliwowy MES RBMK")
        addItem(NTechItems.rbmkRodMeu, "Pręt Paliwowy MEU RBMK")
        addItem(NTechItems.rbmkRodMox, "Pręt Paliwowy MOX RBMK")
        addItem(NTechItems.rbmkRodPo210Be, "Źródło Neutronów Po210Be RBMK")
        addItem(NTechItems.rbmkRodPu238Be, "Źródło Neutronów Pu238Be RBMK")
        addItem(NTechItems.rbmkRodRa226Be, "Źródło Neutronów Ra226Be RBMK")
        addItem(NTechItems.rbmkRodThMeu, "Pręt Paliwowy ThMEU RBMK")
        addItem(NTechItems.rbmkRodUeu, "Pręt Paliwowy NU RBMK ")
        addItem(NTechItems.rbmkRodZfbAmMix, "Pręt ZFB Ameryku Klasy Paliwowej RBMK")
        addItem(NTechItems.rbmkRodZfbBismuth, "Pręt ZFB Bizmutu RBMK")
        addItem(NTechItems.rbmkRodZfbPu241, "Pręt ZFB Pu-241 RBMK")

        addItem(NTechItems.meltdownTool, "Natychmiastowy Aplikator Roztopienia Dyatlova")

        addItem(NTechItems.graphiteDebris, "Gorący Kawałek Grafitu")
        addItem(NTechItems.metalDebris, "Zniszczony Metalowy Pręt")
        addItem(NTechItems.fuelDebris, "Kawałek Paliwa RBMK")

        addItem(NTechItems.machineTemplateFolder, "Folder Szablonów Maszynowych")
        addItemDesc(
            NTechItems.machineTemplateFolder,
            "Szablony Maszyn: Papier + Barwnik\n" +
                "Identyfikator Płynów: Płytka z Żelaza + Barwnik\n" +
                "Elementy Tłoczne: Element Tłoczny (Płaski)\n" +
                "Utwory Syreny: Izolator + Stalowa Płytka"
        )

        addItem(NTechItems.sirenTrackHatchSiren, "Syrena Włazu")
        addItem(NTechItems.sirenTrackAutopilotDisconnected, "Autopilot Odłączony")
        addItem(NTechItems.sirenTrackAMSSiren, "Syrena AMS")
        addItem(NTechItems.sirenTrackBlastDoorAlarm, "Alarm Drzwi Wybuchowych")
        addItem(NTechItems.sirenTrackAPCSiren, "Syrena APC")
        addItem(NTechItems.sirenTrackKlaxon, "Klakson")
        addItem(NTechItems.sirenTrackVaultDoorAlarm, "Alarm Drzwi Krypt")
        addItem(NTechItems.sirenTrackSecurityAlert, "Alarm Bezpieczeństwa")
        addItem(NTechItems.sirenTrackStandardSiren, "Standardowa Syrena")
        addItem(NTechItems.sirenTrackClassicSiren, "Klasyczna Syrena")
        addItem(NTechItems.sirenTrackBankAlarm, "Alarm Bankowy")
        addItem(NTechItems.sirenTrackBeepSiren, "Syrena Brzęczyk")
        addItem(NTechItems.sirenTrackContainerAlarm, "Alarm Kontenera")
        addItem(NTechItems.sirenTrackSweepSiren, "Syrena Wymiatająca")
        addItem(NTechItems.sirenTrackMissileSiloSiren, "Syrena Silosu Rakietowego")
        addItem(NTechItems.sirenTrackAirRaidSiren, "Syrena Nalotu Powietrznego")
        addItem(NTechItems.sirenTrackNostromoSelfDestruct, "Samozniszczenie Nostromo")
        addItem(NTechItems.sirenTrackEASAlarmScreech, "Krzyk alarmu EAS")
        addItem(NTechItems.sirenTrackAPCPass, "Przejazd APC")
        addItem(NTechItems.sirenTrackRazortrainHorn, "Klakson Razortrain")

        addItem(NTechItems.fluidIdentifier, "Identyfikator Płynów: %s")
        addItemDesc(NTechItems.fluidIdentifier, "Kliknij prawym przyciskiem myszy na Rurę Płynową, żeby nadać jej ten płyn.\nKliknij prawym przyciskiem myszy z Shiftem, żeby nadać pobliskim rurom ten płyn\ndo maksymalnej odległości 64 rur.")

        addItem(NTechItems.assemblyTemplate, "Szablon Montażowy: %s")
        addItem(NTechItems.chemTemplate, "Szablon Chemiczny: %s")

        run {
            val usedInLittleBoy = "Użyte w:\nLittle Boy"
            addItem(NTechItems.neutronShieldingLittleBoy, "Osłona Neutronów")
            addItemDesc(NTechItems.neutronShieldingLittleBoy, usedInLittleBoy)
            addItem(NTechItems.subcriticalUraniumTarget, "Podkrytyczny Cel U235")
            addItemDesc(NTechItems.subcriticalUraniumTarget, usedInLittleBoy)
            addItem(NTechItems.uraniumProjectile, "Pocisk U235")
            addItemDesc(NTechItems.uraniumProjectile, usedInLittleBoy)
            addItem(NTechItems.propellantLittleBoy, "Propelent")
            addItemDesc(NTechItems.propellantLittleBoy, usedInLittleBoy)
            addItem(NTechItems.bombIgniterLittleBoy, "Zapalnik Bomby")
            addItemDesc(NTechItems.bombIgniterLittleBoy, usedInLittleBoy)
        }
        addItem(NTechItems.bundleOfImplosionPropellant, "Paczka Paliwa Implozyjnego")
        addItemDesc(NTechItems.bundleOfImplosionPropellant, "Użyte w:\nFat Man\nIvy Mike\nTsar Bomba")
        addItem(NTechItems.bombIgniterFatMan, "Zapalnik Bomby")
        addItemDesc(NTechItems.bombIgniterFatMan, "Użyte w Fat Man")
        addItem(NTechItems.plutoniumCore, "Rdzeń Plutonowy")
        addItemDesc(NTechItems.plutoniumCore, "Użyte w:\nFat Man\nIvy Mike\nTsar Bomba")
        addItem(NTechItems.detonator, "Detonator")
        addItemDesc(NTechItems.detonator, "Kliknij w jakikolwiek materiał wybuchowy prawym przyciskiem\nmyszy z shiftem aby ustawić położenie,\nnaciśnij prawy przycisk myszy aby go zdetonować!")
        addItem(NTechItems.littleBoyKit, "Zestaw Little Boy")
        addItem(NTechItems.fatManKit, "Zestaw Fat Man")

        addItem(NTechItems.designator, "Wyznacznik Celu Bliskiego Zasięgu")
        addItem(NTechItems.heMissile, "Zwykła Rakieta Wybuchowa")
        addItem(NTechItems.incendiaryMissile, "Rakieta Zapalająca")
        addItem(NTechItems.clusterMissile, "Rakieta Kasetowa")
        addItem(NTechItems.bunkerBusterMissile, "Niszczyciel Bunkrów")
        addItem(NTechItems.strongMissile, "Silna Wybuchowa Rakieta")
        addItem(NTechItems.strongIncendiaryMissile, "Silna Zapalająca Rakieta")
        addItem(NTechItems.strongClusterMissile, "Silna Rakieta Kasetowa")
        addItem(NTechItems.strongBunkerBusterMissile, "Ulepszony Niszczyciel Bunkrów")
        addItem(NTechItems.burstMissile, "Rakieta Seryjna")
        addItem(NTechItems.infernoMissile, "Rakieta Inferno G.R.N. Mk.II")
        addItem(NTechItems.rainMissile, "Deszcz Bomb")
        addItem(NTechItems.drillMissile, "Pękacz Betonów")
        addItem(NTechItems.nuclearMissile, "Rakieta Jądrowa")
        addItem(NTechItems.tectonicMissile, "Rakieta Tektoniczna")
        addItemDesc(NTechItems.tectonicMissile, "Przy użyciu eksplozji nuklearnych, możliwe jest stworzenie wulkanu!")

        addItem(NTechItems.oilDetector, "Detektor Ropy Naftowej")
        addItemDesc(NTechItems.oilDetector, "Kliknij prawy przycisk myszy, aby zeskanować powierzchnie na olej.\nMożliwe jest tylko znalezienie dużych zbiorników.")
        addItem(NTechItems.rbmkLinker, "Łącznik Pulpiu Sterowniczego RBMK")
        addItemDesc(NTechItems.rbmkLinker, "Kliknij Prawym przyciskiem myszy i shiftem aby zapisać pozycję,\nKliknij prawym przyciskiem myszy i shiftem w pulpit\nsterowniczy albo dzwig, aby połączyć!")
        addItem(NTechItems.geigerCounter, "Ręczny Licznik Geigera")

        addItem(NTechItems.ivBag, "Torba IV")
        addItem(NTechItems.bloodBag, "Torba Krwi")
        addItem(NTechItems.emptyExperienceBag, "Pusta Torba Doświadczenia")
        addItem(NTechItems.experienceBag, "Torba Doświadczenia")
        addItem(NTechItems.radAway, "RadAway")
        addItem(NTechItems.strongRadAway, "Silny RadAway")
        addItem(NTechItems.eliteRadAway, "Elitarny RadAway")

        addItem(NTechItems.hazmatHelmet, "Hełm Hazmat")
        addItem(NTechItems.hazmatChestplate, "Napierśnik Hazmat")
        addItem(NTechItems.hazmatLeggings, "Nogawice Hazmat")
        addItem(NTechItems.hazmatBoots, "Buty Hazmat")
        addItem(NTechItems.advancedHazmatHelmet, "Zaawansowany Hełm Hazmat")
        addItem(NTechItems.advancedHazmatChestplate, "Zaawansowany Napierśnik Hazmat")
        addItem(NTechItems.advancedHazmatLeggings, "Zaawansowane Nogawice Hazmat")
        addItem(NTechItems.advancedHazmatBoots, "Zaawansowane Buty Hazmat")
        addItem(NTechItems.reinforcedHazmatHelmet, "Wysoko Wydajny Hełm Hazmat")
        addItem(NTechItems.reinforcedHazmatChestplate, "Wysoko Wydajny Napierśnik Hazmat")
        addItem(NTechItems.reinforcedHazmatLeggings, "Wysoko Wydajne Nogawice Hazmat")
        addItem(NTechItems.reinforcedHazmatBoots, "Wysoko Wydajne Buty Hazmat")
        addItem(NTechItems.titaniumHelmet, "Tytanowy Hełm")
        addItem(NTechItems.titaniumChestplate, "Tytanowy Napierśnik")
        addItem(NTechItems.titaniumLeggings, "Tytanowe Nogawice")
        addItem(NTechItems.titaniumBoots, "Tytanowe Buty")
        addItem(NTechItems.steelHelmet, "Stalowy Hełm")
        addItem(NTechItems.steelChestplate, "Stalowy Napierśnik")
        addItem(NTechItems.steelLeggings, "Stalowe Nogawice")
        addItem(NTechItems.steelBoots, "Stalowe Buty")
        addItem(NTechItems.advancedAlloyHelmet, "Hełm ze Zaawansowanego Stopu")
        addItem(NTechItems.advancedAlloyChestplate, "Napierśnik ze Zaawansowanego Stopu")
        addItem(NTechItems.advancedAlloyLeggings, "Nogawice ze Zaawansowanego Stopu")
        addItem(NTechItems.advancedAlloyBoots, "Buty ze Zaawansowanego Stopu")
        addItem(NTechItems.combineSteelHelmet, "Hełm ze Stali Kombinatu")
        addItem(NTechItems.combineSteelChestplate, "Napierśnik ze Stali Kombinatu")
        addItem(NTechItems.combineSteelLeggings, "Nogawice ze Stali Kombinatu")
        addItem(NTechItems.combineSteelBoots, "Buty ze Stali Kombinatu")
        addItem(NTechItems.paAAlloyChestplate, "Płyta Chroniąca Klatkę Piersiową PaA")
        addItem(NTechItems.paAAlloyLeggings, "Wzmocnienia Nóg PaA")
        addItem(NTechItems.paAAlloyBoots, "PaA \"Stare Dobre Buty\"")
        addItem(NTechItems.schrabidiumHelmet, "Hełm z Schrabidium")
        addItem(NTechItems.schrabidiumChestplate, "Napierśnik z Schrabidium")
        addItem(NTechItems.schrabidiumLeggings, "Nogawice z Schrabidium")
        addItem(NTechItems.schrabidiumBoots, "Buty z Schrabidium")

        addItem(NTechItems.polaroid, "Polaroid")

        addItem(NTechFluids.steam.bucket, "Wiadro Pary Wodnej")
        addItem(NTechFluids.steamHot.bucket, "Wiadro Gęstej Pary Wodnej")
        addItem(NTechFluids.steamSuperHot.bucket, "Wiadro Bardzo Gęstej Pary Wodnej ")
        addItem(NTechFluids.steamUltraHot.bucket, "Wiadro Niesamowicie Gęstej Pary Wodnej")
        addItem(NTechFluids.gas.bucket, "Wiadro Gazu Ziemnego")
        addItem(NTechFluids.oil.bucket, "Wiadro Ropy Naftowej")
        addItem(NTechFluids.uraniumHexafluoride.bucket, "Wiadro Sześciofluorku Uranu")
        addItem(NTechFluids.corium.bucket, "Wiadro Korium")
        addItem(NTechFluids.volcanicLava.bucket, "Wiadro Wulkanicznej Lawy")

        addItem(NTechItems.creativeNuclearExplosionSpawner, "Kreator Eksplozji Nuklearnych")
        addItemDesc(NTechItems.creativeNuclearExplosionSpawner, "Wyprodukowane przez CakeCo\nEast Spawn Rd 2, 68-419 RetroMC")

        addEntityType(EntityTypes.clusterFragment, "Bomba")
        addEntityType(EntityTypes.falloutRain, "Opad Promieniotwórczy")
        addEntityType(EntityTypes.missileBunkerBuster, "Niszczyciel Bunkrów")
        addEntityType(EntityTypes.missileBunkerBusterStrong, "Ulepszony Niszczyciel Bunkrów")
        addEntityType(EntityTypes.missileBurst, "Rakieta Seryjna")
        addEntityType(EntityTypes.missileCluster, "Rakieta Kasetowa")
        addEntityType(EntityTypes.missileClusterStrong, "Silna Rakieta Kasetowa")
        addEntityType(EntityTypes.missileDrill, "Pękacz Betonów")
        addEntityType(EntityTypes.missileHE, "Zwykła Rakieta Wybuchowa")
        addEntityType(EntityTypes.missileHEStrong, "Silna Wybuchowa Rakieta")
        addEntityType(EntityTypes.missileIncendiary, "Zwykła Rakieta Wybuchowa")
        addEntityType(EntityTypes.missileIncendiaryStrong, "Silna Zapalająca Rakieta")
        addEntityType(EntityTypes.missileInferno, "Rakieta Inferno G.R.N. Mk.II")
        addEntityType(EntityTypes.missileNuclear, "Rakieta Jądrowa")
        addEntityType(EntityTypes.missileRain, "Deszcz Bomb")
        addEntityType(EntityTypes.missileTectonic, "Rakieta Tektoniczna")
        addEntityType(EntityTypes.mushroomCloud, "Grzyb Atomowy")
        addEntityType(EntityTypes.nuclearExplosion, "Eksplozja Nuklearna")
        addEntityType(EntityTypes.oilSpill, "Wyciek Ropy Naftowej")
        addEntityType(EntityTypes.shrapnel, "Szrapnel")
        addEntityType(EntityTypes.volcanicShrapnel, "Szrapnel Wulkaniczny")

        addEntityTypeWithSpawnEgg(EntityTypes.nuclearCreeper, NTechItems.nuclearCreeperSpawnEgg, "Nuklearny Creeper", "Jajo przyzywające nuklearnego creepera")

        addMenuType(MenuTypes.sirenMenu, "Syrena")
        addMenuType(MenuTypes.safeMenu, "Sejf")
        addMenuType(MenuTypes.anvilMenu, "Kowadło Poziomu %s")
        addMenuType(MenuTypes.steamPressMenu, "Prasa na Parę")
        addMenuType(MenuTypes.blastFurnaceMenu, "Piec Hutniczy")
        addMenuType(MenuTypes.combustionGeneratorMenu, "Prądnica Spaleniowa")
        addMenuType(MenuTypes.electricFurnaceMenu, "Piec Elektryczny")
        addMenuType(MenuTypes.shredderMenu, "Strzępiarka")
        addMenuType(MenuTypes.assemblerMenu, "Monter")
        addMenuType(MenuTypes.chemPlantMenu, "Maszyna Chemiczna")
        addMenuType(MenuTypes.oilWellMenu, "Szyb Naftowy")
        add(LangKeys.CONTAINER_OIL_DERRICK, "Wiertnica Naftowa")
        add(LangKeys.CONTAINER_PUMPJACK, "Kiwon")
        addMenuType(MenuTypes.centrifugeMenu, "Wirówka")
        addMenuType(MenuTypes.rbmkRodMenu, "Pręt Paliwowy RBMK")
        add(LangKeys.CONTAINER_RBMK_REASIM_ROD, "Pręt Paliwowy RBMK (ReaSim)")
        addMenuType(MenuTypes.rbmkBoilerMenu, "Kanał Pary Wodnej RBMK")
        addMenuType(MenuTypes.rbmkManualControlMenu, "Pręty Sterujące RBMK")
        add(LangKeys.CONTAINER_RBMK_CONTROL_MODERATED, "Moderowane Pręty Sterujące RBMK")
        addMenuType(MenuTypes.rbmkAutoControlMenu, "Automatyczne Pręty Sterujące RBMK")
        addMenuType(MenuTypes.rbmkConsoleMenu, "Pulpit Sterowniczy RBMK")

        addMenuType(MenuTypes.littleBoyMenu, "Little Boy")
        addMenuType(MenuTypes.fatManMenu, "Fat Man")

        addMenuType(MenuTypes.launchPadMenu, "Wyrzutnia Rakiet")

        addDamageSource(DamageSources.extractBlood, "%1\$s wydobył za dużo energii życiowej", "%1\$s próbował zostawić starannie zapakowany soczek życiowy dla %2\$s")
        addDamageSource(DamageSources.murkyAnvil, "%1\$s NIEOKREŚLONY", "%1\$s NIEOKREŚLONY, podczas walki z %2\$s")
        addDamageSource(DamageSources.nuclearBlast, "%1\$s został zdmuchnięty z powierzchni ziemi przez eksplozje nuklearną", "%1\$s został rozłożony na cząsteczki subatomowe podczas walczenia z %2\$s")
        addDamageSource(DamageSources.radiation, "%1\$s umarł przez chorobę popromienną", "%1\$s umarł przez chorobę popromienną podczas walczenia z %2\$s")
        addDamageSource(DamageSources.shrapnel, "%1\$s został poszarpany szrapnelem", "%1\$s został poszarpany szrapnelem podczas walki z %2\$s")

        addAttribute(Attributes.RADIATION_RESISTANCE, "Odporności na promieniowanie")

        add(LangKeys.ARMOR_BLAST_PROTECTION, "Modyfikator obrażeń %s przeciwko eksplozjom")
        add(LangKeys.ARMOR_CUSTOM_GEIGER, "Wbudowany licznik Geigera na ekranie")
        add(LangKeys.ARMOR_DAMAGE_CAP, "Twardy limit obrażeń %s")
        add(LangKeys.ARMOR_DAMAGE_MODIFIER, "Ogólny modyfikator obrażeń %s")
        add(LangKeys.ARMOR_DAMAGE_RESISTANCE_MODIFIER, "Modyfikator obrażeń %s przeciwko %s")
        add(LangKeys.ARMOR_DAMAGE_THRESHOLD, "Próg obrażeń %s")
        add(LangKeys.ARMOR_DASH_COUNT, "Daje %s mknień")
        add(LangKeys.ARMOR_FIREPROOF, "Ognioodporny")
        add(LangKeys.ARMOR_FULL_SET_BONUS, "Bonus za pełny zestaw:")
        add(LangKeys.ARMOR_GEIGER_SOUND, "Słyszalny licznik Geigera")
        add(LangKeys.ARMOR_GRAVITY, "Modifikator grawitacji %s")
        add(LangKeys.ARMOR_HARD_LANDING, "Silne lądowanie")
        add(LangKeys.ARMOR_NULLIFIES_DAMAGE, "Anuluje wszystkie obrażenia od %s")
        add(LangKeys.ARMOR_PROJECTILE_PROTECTION, "Modyfikator obrażeń %s przeciwko pociskom")
        add(LangKeys.ARMOR_PROTECTION_YIELD, "Protekcja dotyczy ataków mniejszych od %s")
        add(LangKeys.ARMOR_THERMAL, "Wzrok termiczny")
        add(LangKeys.ARMOR_VATS, "Przeciwnicy na ekranie")

        add(LangKeys.BUTTON_CANCEL, "Anuluj")
        add(LangKeys.BUTTON_START, "Start")

        add(LangKeys.CHEMISTRY_URANIUM_HEXAFLUORIDE, "Produkcja Sześciofluorku Uranu")

        add(LangKeys.DETONATOR_INVALID_BLOCK_ENTITY, "Błąd serwera: BlockEntity celu jest niepoprawny!")
        add(LangKeys.DETONATOR_MISSING_COMPONENTS, "Brakuję komponentów w ładunku wybuchowym!")
        add(LangKeys.DETONATOR_NO_EXPLOSIVE, "Cel nie jest poprawnym ładunkiem wybuchowym!")
        add(LangKeys.DETONATOR_PROHIBITED, "Detonacja była zabroniona!")
        add(LangKeys.DETONATOR_SUCCESS, "Zdetonowane!")
        add(LangKeys.DETONATOR_UNKNOWN_ERROR, "Nieznany błąd nastąpił podczas detonacji")

        add(LangKeys.DEVICE_OIL_DETECTOR_BELOW, "Złoże ropy bezpośrednio poniżej!")
        add(LangKeys.DEVICE_OIL_DETECTOR_NEAR, "Złoże ropy jest w pobliżu")
        add(LangKeys.DEVICE_OIL_DETECTOR_NO_OIL, "Brak złoża ropy")
        add(LangKeys.DEVICE_POSITION_SET, "Pozycja zapisana!")
        add(LangKeys.DEVICE_POSITION_NOT_LOADED, "Pozycja nie jest teraz załadowana w tym świecie!")
        add(LangKeys.DEVICE_POSITION_NOT_SET, "Brak zapisanej pozycji!")

        add(LangKeys.ENERGY, "Energia")
        add(LangKeys.ENERGY_ENERGY_STORED, "Magazynowana energia: %s/%sHE")
        add(LangKeys.ENERGY_CHARGE_RATE, "Szybkość ładowania: %sHE/t")
        add(LangKeys.ENERGY_DISCHARGE_RATE, "Szybkość rozładowania: %sHE/t")

        add(LangKeys.EXPLOSION_SPAWNER_ERROR_EXTRA_FALLOUT, "Nie można przeanalizować dodatkowej ilości Opadu Promieniotwórczego")
        add(LangKeys.EXPLOSION_SPAWNER_ERROR_STRENGTH, "Nie można przeanalizować wartości siły")
        add(LangKeys.EXPLOSION_SPAWNER_EXTRA_FALLOUT, "Dodatkowy Opad Promieniotwórczy")
        add(LangKeys.EXPLOSION_SPAWNER_HAS_FALLOUT, "Posiada Opad Promieniotwórczy")
        add(LangKeys.EXPLOSION_SPAWNER_MUTED, "Wyciszony")
        add(LangKeys.EXPLOSION_SPAWNER_NO_PERMISSION, "Nie można użyć przedmiotu: Niewystarczające uprawnienia")
        add(LangKeys.EXPLOSION_SPAWNER_POSITION, "Pozycja")
        add(LangKeys.EXPLOSION_SPAWNER_STRENGTH, "Siła")

        add(LangKeys.GEIGER_CHUNK_RADIATION, "Radiacja w chunku:")
        add(LangKeys.GEIGER_PLAYER_IRRADIATION, "Napromieniowanie gracza:")
        add(LangKeys.GEIGER_PLAYER_RESISTANCE, "Odporność na promieniowanie gracza:")
        add(LangKeys.GEIGER_TITLE, "LICZNIK GEIGERA")
        add(LangKeys.GEIGER_TOTAL_ENVIRONMENTAL_RADIATION, "Całkowite napromieniowanie środowiskowe:")

        add(LangKeys.HAZARD_ASBESTOS, "[Azbest]")
        add(LangKeys.HAZARD_BLINDING, "[Oślepiające]")
        add(LangKeys.HAZARD_COAL, "[Pył węglowy]")
        add(LangKeys.HAZARD_DIGAMMA, "[Digamma]")
        add(LangKeys.HAZARD_EXPLOSIVE, "[Łatwopalne / Wybuchowe]")
        add(LangKeys.HAZARD_HEAT, "[Piroforyczny / Gorące]")
        add(LangKeys.HAZARD_HYDROREACTIVE, "[Hydroreaktywne]")
        add(LangKeys.HAZARD_RADIATON, "[Radioaktywne]")


        add(LangKeys.INFO_INPUT, "Wejście:")
        add(LangKeys.INFO_INPUTS, "Wejścia:")
        add(LangKeys.INFO_ORE_CLUSTER, "Wypada tylko po zniszczeniu przez gracza")
        add(LangKeys.INFO_OUTPUT, "Wyjście:")
        add(LangKeys.INFO_OUTPUTS, "Wyjścia:")
        add(LangKeys.INFO_POSITION, "Pozycja: %d %d %d")
        add(LangKeys.INFO_PRODUCTION_TIME, "Czas produkcji:")

        add(LangKeys.JEI_CATEGORY_ASSEMBLING, "Montowanie")
        add(LangKeys.JEI_CATEGORY_BLASTING, "Wytapianie")
        add(LangKeys.JEI_CATEGORY_CHEMISTRY, "Procesy chemiczne")
        add(LangKeys.JEI_CATEGORY_CONSTRUCTING, "Konstruowanie")
        add(LangKeys.JEI_CATEGORY_PRESSING, "Tłoczenie")
        add(LangKeys.JEI_CATEGORY_SHREDDING, "Strzępianie")
        add(LangKeys.JEI_CATEGORY_SMITHING, "Kowalstwo")
        add(LangKeys.JEI_CATEGORY_TEMPLATE_FOLDER, "Folder szablonów")
        add(LangKeys.JEI_EXPERIENCE, "%s Doświadczenia")
        add(LangKeys.JEI_OUTPUT_CHANCE, "Szansa stworzenia:")
        add(LangKeys.JEI_TIER_MINIMUM, "Minimalny poziom: %s")
        add(LangKeys.JEI_TIER_RANGE, "Zakres poziomów: %s..%s")

        add(LangKeys.OIL_WELL_STATUS_OK, "Status: Ok")
        add(LangKeys.OIL_WELL_STATUS_NO_OIL_SOURCE, "Status: Brak źródła ropy")
        add(LangKeys.OIL_WELL_STATUS_ERROR, "Status: Nie można operować")
        add(LangKeys.OIL_WELL_STATUS_OUT_OF_FLUID, "Status: Brak roztworu do szczelinowania")
        add(LangKeys.OIL_WELL_STATUS_LOOKING_FOR_OIL, "Status: Szukanie ropy")
        add(LangKeys.OIL_WELL_STATUS_NO_POWER, "Status: Brak zasilania")

        add(LangKeys.RBMK_BOILER_STEAM, "Para: %d / %d")
        add(LangKeys.RBMK_BOILER_TYPE, "Kompresor: %s")
        add(LangKeys.RBMK_BOILER_WATER, "Woda zasilająca: %d / %d")
        add(LangKeys.RBMK_BURN_EULER, "BEZPIECZNY / KĄT EULERA")
        add(LangKeys.RBMK_BURN_LINEAR, "NIEBEZPIECZNY / LINIOWY")
        add(LangKeys.RBMK_BURN_LOGARITHMIC, "ŚREDNI / LOGARYTMICZNY")
        add(LangKeys.RBMK_BURN_NEGATIVE_QUADRATIC, "NIEBIEZPIECZNY / NEGATYWNIE-KWADRATOWE")
        add(LangKeys.RBMK_BURN_PASSIVE, "BEZPIECZNY / PASYWNY")
        add(LangKeys.RBMK_BURN_QUADRATIC, "NIEBEZPIECZNY / KWADRATOWE")
        add(LangKeys.RBMK_BURN_SIGMOID, "BEZPIECZNY / SIGMOID")
        add(LangKeys.RBMK_BURN_SINE_SLOPE, "EKSPERYMENTALNY / NACHYLENIE SIN")
        add(LangKeys.RBMK_BURN_SQUARE_ROOT, "ŚREDNI / PIERWIASTEK KWADRATOWY")
        add(LangKeys.RBMK_CONSOLE_ASSIGN, "Przypisz wybrane kolumny do pulpitu #%d")
        add(LangKeys.RBMK_CONSOLE_DESELECT_CONTROL_RODS, "Odznacz wszystkie")
        add(LangKeys.RBMK_CONSOLE_LINK, "RBMK połączony!")
        add(LangKeys.RBMK_CONSOLE_SELECT_CONTROL_RODS, "Wybierz wszystkie pręty sterujące")
        add(LangKeys.RBMK_CONSOLE_SELECT_GROUP, "Wybierz grupę %s")
        add(LangKeys.RBMK_CONTROL_GROUP_BLUE, "§1Grupa niebieska")
        add(LangKeys.RBMK_CONTROL_GROUP_GREEN, "§aGrupa zielona")
        add(LangKeys.RBMK_CONTROL_GROUP_PURPLE, "§5Grupa purpurowa")
        add(LangKeys.RBMK_CONTROL_GROUP_RED, "§cGrupa czerwona")
        add(LangKeys.RBMK_CONTROL_GROUP_YELLOW, "§eGrupa żółta")
        add(LangKeys.RBMK_CONTROL_ROD_LEVEL, "%.1f%%")
        add(LangKeys.RBMK_HEAT, "Temperatura kolumny: %.1f°C")
        add(LangKeys.RBMK_MODERATED, "Moderowana")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE, "Smocze Płomienie")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE_GOLD, "Antywodór w namagnetyzowanej kracie Złota-198")
        add(LangKeys.RBMK_NAME_PELLET_DRX, "§kCzy nie słyszysz grzmotów?")
        add(LangKeys.RBMK_NAME_PELLET_FLASHLEAD, "Antywodór ograniczony przez namagnetyzowanej kraty Złota-198 i Ołowiu-209")
        add(LangKeys.RBMK_NAME_PELLET_HEA241, "Wysoce Wzbogacony Ameryk-241")
        add(LangKeys.RBMK_NAME_PELLET_HEA242, "Wysoce Wzbogacony Ameryk-242")
        add(LangKeys.RBMK_NAME_PELLET_HEAUS, "Wysoce Wzbogacone Australium (Ayerit)")
        add(LangKeys.RBMK_NAME_PELLET_HEN, "Wysoce Wzbogacony Neptun-237")
        add(LangKeys.RBMK_NAME_PELLET_HEP239, "Wysoce Wzbogacony Pluton-239")
        add(LangKeys.RBMK_NAME_PELLET_HEP241, "Wysoce Wzbogacony Pluton-241")
        add(LangKeys.RBMK_NAME_PELLET_HES, "Wysoce Wzbogacone Schrabidium-326")
        add(LangKeys.RBMK_NAME_PELLET_HEU233, "Wysoce Wzbogacony Uran-233")
        add(LangKeys.RBMK_NAME_PELLET_HEU235, "Wysoce Wzbogacony Uran-235")
        add(LangKeys.RBMK_NAME_PELLET_LEA, "Nisko Wzbogacony Ameryk-242")
        add(LangKeys.RBMK_NAME_PELLET_LEAUS, "Nisko Wzbogacone Australium (Tasmanit)")
        add(LangKeys.RBMK_NAME_PELLET_LEP, "Nisko Wzbogacony Pluton-239")
        add(LangKeys.RBMK_NAME_PELLET_LES, "Nisko Wzbogacone Schrabidium-326")
        add(LangKeys.RBMK_NAME_PELLET_MEA, "Średnio Wzbogacony Ameryk-242")
        add(LangKeys.RBMK_NAME_PELLET_MEN, "Średnio Wzbogacony Neptun-237")
        add(LangKeys.RBMK_NAME_PELLET_MEP, "Średnio Wzbogacony Pluton-239")
        add(LangKeys.RBMK_NAME_PELLET_MES, "Średnio Wzbogacone Schrabidium-326")
        add(LangKeys.RBMK_NAME_PELLET_MEU, "Średnio Wzbogacony Uran-235")
        add(LangKeys.RBMK_NAME_PELLET_MOX, "Zmieszane Tlenki MEU i LEP")
        add(LangKeys.RBMK_NAME_PELLET_PO210BE, "Źródło Neutronów Polon-210 i Beryl")
        add(LangKeys.RBMK_NAME_PELLET_PU238BE, "Źródło Neutronów Pluton-238 i Beryl")
        add(LangKeys.RBMK_NAME_PELLET_RA226BE, "Źródło Neutronów Rad-226 i Beryl")
        add(LangKeys.RBMK_NAME_PELLET_THMEU, "Paliwo Przyspieszające z Toru i MEU")
        add(LangKeys.RBMK_NAME_PELLET_UEU, "Niewzbogacony Uran")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_AM_MIX, "Szybki Hodowca Jądrowy z Cyrkonu - HEP-241#MEA")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_BISMUTH, "Szybki Hodowca Jądrowy z Cyrkonu - LEU/HEP-241#Bi")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_PU241, "Szybki Hodowca Jądrowy z Cyrkonu - HEU-235/HEP-240#Pu-241")
        add(LangKeys.RBMK_NEUTRON_FAST, "Szybkie Neutrony")
        add(LangKeys.RBMK_NEUTRON_SLOW, "Wolne Neutrony")
        add(LangKeys.RBMK_NEUTRON_ANY, "Wszystkie Neutrony")
        add(LangKeys.RBMK_PELLET_DEPLETION_FULL, "Całkowicie Wyczerpany")
        add(LangKeys.RBMK_PELLET_DEPLETION_HIGH, "Wysoce Wyczerpany")
        add(LangKeys.RBMK_PELLET_DEPLETION_MODERATE, "Średnio Wyczerpany")
        add(LangKeys.RBMK_PELLET_DEPLETION_NEW, "Świeży")
        add(LangKeys.RBMK_PELLET_DEPLETION_SLIGHT, "Ledwo Wyczerpany")
        add(LangKeys.RBMK_PELLET_XENON_POISONED, "Wysoka Ilość Trucizny Ksenonowej")
        add(LangKeys.RBMK_PELLET_RECYCLE, "Pastylka do recyklingu")
        add(LangKeys.RBMK_ROD_DEPLETION, "Wyczerpanie: %.3f%%")
        add(LangKeys.RBMK_ROD_DIFFUSION, "Dyfuzja: %s")
        add(LangKeys.RBMK_ROD_FLUX_FUNC, "Funkcja fluktuacji: %s")
        add(LangKeys.RBMK_ROD_FUNC_TYPE, "Typ funkcji: %s")
        add(LangKeys.RBMK_ROD_HEAT, "Ciepło na fluktancje: %s")
        add(LangKeys.RBMK_ROD_HEAT_CORE, "Temperatura rdzenia: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL, "Temperatura skóry: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL_TO_MELTING_POINT, "Temperatura skóry: %.1f°C / %.1f°C")
        add(LangKeys.RBMK_ROD_MELTING_POINT, "Temperatura topnienia: %s")
        add(LangKeys.RBMK_ROD_SOURCE, "Samozapłon")
        add(LangKeys.RBMK_ROD_SPLITS_INTO, "Rozczepia się na: %s")
        add(LangKeys.RBMK_ROD_SPLITS_WITH, "Rozczepia się dzięki: %s")
        add(LangKeys.RBMK_ROD_XENON, "Trucizna Ksenonowa: %.3f%%")
        add(LangKeys.RBMK_ROD_XENON_BURN, "Funkcja spalania Ksenonu: %s")
        add(LangKeys.RBMK_ROD_XENON_GEN, "Funkcja generacji Ksenonu: %s")
        add(LangKeys.RBMK_SCREEN_DEPLETION, "Wyczer: %.1f%%")
        add(LangKeys.RBMK_SCREEN_FUEL_TEMPERATURE, "Rdzeń: %.1f°C")
        add(LangKeys.RBMK_SCREEN_POISON, "Ksenon: %.1f%%")
        add(LangKeys.RBMK_SCREEN_ROD_EXTRACTION, "Kontrola: %.1f%%")
        add(LangKeys.RBMK_SCREEN_TEMPERATURE, "Temp: %.1f°C")
        add(LangKeys.RBMK_SCREEN_TYPE_COLUMN_TEMPERATURE, "Monitoruj średnią temperaturę kolumny")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_DEPLETION, "Monitoruj średnie wyczerpanie paliwa")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_POISON, "Monitoruj średnie zanieczyszczenie ksenonowe")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_TEMPERATURE, "Monitoruj średnią temperaturę paliwa")
        add(LangKeys.RBMK_SCREEN_TYPE_NONE, "Wył")
        add(LangKeys.RBMK_SCREEN_TYPE_ROD_EXTRACTION, "Monitoruj średiną ekstrakcje prętów sterujących")

        add(LangKeys.SIREN_TRACK_LOOP, "Typ: Pętla")
        add(LangKeys.SIREN_TRACK_ONCE, "Typ: Zagraj raz")
        add(LangKeys.SIREN_TRACK_RANGE, "Zasięg: %s Metrów")
        add(LangKeys.SIREN_TRACK_SIREN_TRACK, "Utwór Syreny")

        add(LangKeys.SUBTITLE_ANVIL_FALL, "Uderzenie kowadła")
        add(LangKeys.SUBTITLE_ASSEMBLER_OPERATE, "Monter pracuję")
        add(LangKeys.SUBTITLE_BLEEP, "Urządzenie beepuje")
        add(LangKeys.SUBTITLE_BLOCK_DEBRIS, "Gruz uderza w ziemie")
        add(LangKeys.SUBTITLE_BOOP, "Urządzenie boopuje")
        add(LangKeys.SUBTITLE_CENTRIFUGE_OPERATE, "Wirówka szumi")
        add(LangKeys.SUBTITLE_CHEM_PLANT_OPERATE, "Maszyna chemiczna operuję")
        add(LangKeys.SUBTITLE_GEIGER_CLICK, "Kliknięcia licznika Geigera")
        add(LangKeys.SUBTITLE_ITEM_INJECT, "Strzykawka wstrzykiwana")
        add(LangKeys.SUBTITLE_ITEM_UNPACK, "Przedmiot rozpakowany")
        add(LangKeys.SUBTITLE_MINI_NUKE_EXPLODE, "Mini nuke eksploduje")
        add(LangKeys.SUBTITLE_MISSILE_TAKEOFF, "Rakieta odlatuje")
        add(LangKeys.SUBTITLE_PRESS_OPERATE, "Prasa tłoczy")
        add(LangKeys.SUBTITLE_RBMK_AZ5_COVER, "AZ-3 pokrywa otwarta")
        add(LangKeys.SUBTITLE_RBMK_SHUTDOWN, "RBMK wyłącza się")
        add(LangKeys.SUBTITLE_SIREN_AIR_RAID, "Dźwięk Syreny: Air Raid Siren")
        add(LangKeys.SUBTITLE_SIREN_AMS, "Dźwięk Syreny: Syrena AMS")
        add(LangKeys.SUBTITLE_SIREN_APC, "Dźwięk Syreny: Syrena APC")
        add(LangKeys.SUBTITLE_SIREN_APC_PASS, "Dźwięk Syreny: Przejazd APC")
        add(LangKeys.SUBTITLE_SIREN_AUTOPILOT_DISCONNECTED, "Dźwięk Syreny: Autopilot Odłączony")
        add(LangKeys.SUBTITLE_SIREN_BANK, "Dźwięk Syreny: Alarm Bankowy")
        add(LangKeys.SUBTITLE_SIREN_BEEP, "Dźwięk Syreny: Syrena Brzęczyk")
        add(LangKeys.SUBTITLE_SIREN_BLAST_DOOR, "Dźwięk Syreny: Alarm Drzwi Wybuchowych")
        add(LangKeys.SUBTITLE_SIREN_CLASSIC, "Dźwięk Syreny: Klasyczna Syrena")
        add(LangKeys.SUBTITLE_SIREN_CONTAINER, "Dźwięk Syreny: Alarm Kontenera")
        add(LangKeys.SUBTITLE_SIREN_EAS, "Dźwięk Syreny: Krzyk alarmu EAS")
        add(LangKeys.SUBTITLE_SIREN_HATCH, "Dźwięk Syreny: Syrena Włazu")
        add(LangKeys.SUBTITLE_SIREN_KLAXON, "Dźwięk Syreny: Klakson")
        add(LangKeys.SUBTITLE_SIREN_MISSILE_SILO, "Dźwięk Syreny: Syrena Silosu Rakietowego")
        add(LangKeys.SUBTITLE_SIREN_NOSTROMO_SELF_DESTRUCT, "Dźwięk Syreny: Samozniszczenie Nostromo")
        add(LangKeys.SUBTITLE_SIREN_RAZORTRAIN_HORN, "Dźwięk Syreny: Klakson Razortrain")
        add(LangKeys.SUBTITLE_SIREN_SECURITY, "Dźwięk Syreny: Alarm Bezpieczeństwa")
        add(LangKeys.SUBTITLE_SIREN_STANDARD, "Dźwięk Syreny: Standardowa Syrena")
        add(LangKeys.SUBTITLE_SIREN_SWEEP, "Dźwięk Syreny: Syrena Wymiatająca")
        add(LangKeys.SUBTITLE_SIREN_VAULT_DOOR, "Dźwięk Syreny: Alarm Drzwi Krypt")
        add(LangKeys.SUBTITLE_UPGRADE_INSTALL, "Ulepszacz zainstalowany")
        add(LangKeys.SUBTITLE_USE_RADAWAY, "Płyn wlewany")

        add(LangKeys.UPGRADE_INFO_ACCEPTED_UPGRADES, "Akceptowane Ulepszacze:")
        add(LangKeys.UPGRADE_INFO_BURN_GAS, "Spal %smB gazu na %s")
        add(LangKeys.UPGRADE_INFO_CONSUMPTION, "Konsumpcja: %s")
        add(LangKeys.UPGRADE_INFO_DELAY, "Opóźnienie: %s")
        add(LangKeys.UPGRADE_INFO_STACKS_TO, "Stakuję do poziomu %s")
        add(LangKeys.UPGRADE_NAME_AFTER_BURNER, "Dopalacz")
        add(LangKeys.UPGRADE_NAME_OVERDRIVE, "Przesterowanie")
        add(LangKeys.UPGRADE_NAME_POWER_SAVING, "Oszczędzanie Energii")
        add(LangKeys.UPGRADE_NAME_SPEED, "Prędkość")
        add(LangKeys.UPGRADE_WARN_INCOMPATIBLE, "Ten Ulepszacz nie jest kompatybilny!")
        add(LangKeys.UPGRADE_WARN_MACHINE_NOT_UPGRADEABLE, "Ta maszyna nie jest ulepszalna!")
        add(LangKeys.UPGRADE_WARN_NOT_A_MACHINE, "To nie jest maszyna!")
        add(LangKeys.UPGRADE_WARN_VIEW_MACHINE, "Wejdź w ekran maszyny, by zobaczyć efekty")
        add(LangKeys.UPGRADE_WARN_UNKNOWN_COMPATIBILITY, "Kompatybilność z tą maszyną jest niewiadoma")

        add(LangKeys.VERSION_CHECKER_ANNOUNCEMENT, "-- Sprawdzacz wersji NTM --")
        add(LangKeys.VERSION_CHECKER_BLEEDING_EDGE, "Zainstalowana jest najnowsza wersja!")
        add(LangKeys.VERSION_CHECKER_CHANGES_LIST, "Krótka lista zmian:")
        add(LangKeys.VERSION_CHECKER_CUTTING_EDGE, "Zainstalowana jest najnowsza wersja beta!")
        add(LangKeys.VERSION_CHECKER_UPDATE, "Jest nowsza wersja NTM do zainstalowania!")
        add(LangKeys.VERSION_CHECKER_VIEW_RELEASES, "Kliknij tutaj, aby przejść do strony internetowej wersji!")

        add(LangKeys.VOLCANO_EXTINGUISHING, "GAŚNIE")
        add(LangKeys.VOLCANO_GROWING, "ROŚNIE")
        add(LangKeys.VOLCANO_NOT_EXTINGUISHING, "NIE GAŚNIE")
        add(LangKeys.VOLCANO_NOT_GROWING, "NIE ROŚNIE")
        add(LangKeys.VOLCANO_SMOLDERING, "WULKAN TARCZOWY")

        add(LangKeys.WORD_SECONDS, "Sekundy")

        addItem(NTechItems.goldPlate, "Płytka ze Złota")
        addItem(NTechItems.goldCrystals, "Kryształ ze Złota")
        addItem(NTechItems.goldWire, "Drut ze Złota")
        addItem(NTechItems.rawUranium, "Surowy Uran")
        addItem(NTechItems.rawPlutonium, "Surowy Pluton")
        addItem(NTechItems.rawTitanium, "Surowy Tytan")
        addItem(NTechItems.rawTungsten, "Surowy Wolfram")
        addItem(NTechItems.rawBeryllium, "Surowy Beryl")
        addItem(NTechItems.rawLead, "Surowy Ołów")
        addItem(NTechItems.rawCobalt, "Surowy Kobalt")
        addItem(NTechItems.rawLithium, "Surowy Lit")
        addItem(NTechItems.rawStarmetal, "Surowy Gwiazdometal")



    }
    private fun addMaterials() = with(Materials) {
        addMaterial(coal, "Węgla")
        addMaterial(iron, "Żelaza")
        addMaterial(copper, "Miedzi")
        addMaterial(gold, "Złota")
        addMaterial(redstone, "Redstone")
        addMaterial(emerald, "Szmaragdu")
        addMaterial(lazuli, "Lapisu Lazuli")
        addMaterial(diamond, "Diamentu")

        addMaterial(actinium227, "Aktynu-227")
        addMaterial(advancedAlloy, "Zaawansowanego Stopu")
        addMaterial(aluminium, "Aluminium")
        addMaterial(americium241, "Ameryku-241")
        addMaterial(americium242, "Ameryku-242")
        addMaterial(americiumFuel, "Paliwa z Ameryku")
        addMaterial(arsenic, "Arsenu")
        addMaterial(asbestos, "Azbestu")
        addMaterial(australium, "Australium")
        addMaterial(bakelite, "Bakelitu")
        addMaterial(beryllium, "Berylu")
        addMaterial(bismuth, "Bizmutu")
        addMaterial(boron, "Boru")
        addMaterial(cobalt, "Kobaltu")
        addMaterial(cobalt60, "Kobaltu-60")
        addMaterial(combineSteel, "Stali Kombinatu")
        addMaterial(daffergon, "Daffergonu")
        addMaterial(desh, "Deszu")
        addMaterial(dineutronium, "Dineutronu")
        addMaterial(electronium, "Electronu")
        addMaterial(euphemium, "Euphemium")
        addMaterial(ferricSchrabidate, "Schrabidanu Żelazowego")
        addMaterial(fiberglass, "Włókna szklanego")
        addMaterial(fluorite, "Fluorytu")
        addMaterial(ghiorsium336, "Giorsiumu-336")
        addMaterial(gold198, "Złota-198")
        addMaterial(graphite, "Grafitu")
        addMaterial(hesFuel, "Wysoce Wzbogaconego Paliwa Schrabidium")
        addMaterial(highSpeedSteel, "Stali Szybkotnącej")
        addMaterial(insulator, "Izolatora")
        addMaterial(lanthanum, "Lantanu")
        addMaterial(lead, "Ołowiu")
        addMaterial(lead209, "Ołowiu-209")
        addMaterial(lesFuel, "Nisko Wzbogaconego Paliwa Schrabidium")
        addMaterial(lignite, "Węgla Brunatnego")
        addMaterial(lithium, "Litu")
        addMaterial(magnetizedTungsten, "Namagnetyzowanego Wolframu")
        addMaterial(moxFuel, "Paliwa MOX")
        addMaterial(naturalPlutonium, "Plutonu")
        addMaterial(naturalUranium, "Uranu")
        addMaterial(neptunium, "Neptunu")
        addMaterial(neptuniumFuel, "Paliwa z Neptunu")
        addMaterial(niobium, "Niobu")
        addMaterial(niter, "Saletry")
        addMaterial(nuclearWaste, "Odpadów Nuklearnych")
        addMaterial(osmiridium, "Osmirydu")
        addMaterial(plutonium238, "Plutonu-238")
        addMaterial(plutonium239, "Plutonu-239")
        addMaterial(plutonium240, "Plutonu-240")
        addMaterial(plutonium241, "Plutonu-241")
        addMaterial(plutoniumFuel, "Paliwa z Plutonu")
        addMaterial(polonium, "Polonu")
        addMaterial(polymer, "Polimeru")
        addMaterial(radium226, "Radu-226")
        addMaterial(reactorGradeAmericium, "Ameryku Klasy Reaktora")
        addMaterial(reactorGradePlutonium, "Plutonu Klasy Reaktora")
        addMaterial(redCopper, "Czerwonej Miedzi")
        addMaterial(redPhosphorus, "Czerwonego Fosforu")
        addMaterial(reiium, "Reiitu")
        addMaterial(rubber, "Gumy")
        addMaterial(saturnite, "Saturnitu")
        addMaterial(schrabidium, "Schrabidium")
        addMaterial(schrabidiumFuel, "Paliwa z Schrabidium")
        addMaterial(schraranium, "Schraranu")
        addMaterial(solinium, "Solinu")
        addMaterial(starmetal, "Gwiazdometalu")
        addMaterial(steel, "Stali")
        addMaterial(strontium90, "Strontu-90")
        addMaterial(sulfur, "Siarki")
        addMaterial(tantalium, "Tantalu")
        addMaterial(technetium99, "Technetu-99")
        addMaterial(technetiumSteel, "Stali Technetowej")
        addMaterial(thorium, "Toru-232")
        addMaterial(thoriumFuel, "Paliwa z Toru")
        addMaterial(titanium, "Tytanu")
        addMaterial(trinitite, "Trynititu")
        addMaterial(tungsten, "Wolframu")
        addMaterial(unobtainium, "Unobtainium")
        addMaterial(uranium233, "Uranu-233")
        addMaterial(uranium235, "Uranu-235")
        addMaterial(uranium238, "Uranu-238")
        addMaterial(uraniumFuel, "Paliwa z Uranu")
        addMaterial(verticium, "Verticiumu")
        addMaterial(weidanium, "Weidaniumu")
        addMaterial(whitePhosphorus, "Białego Fosforu")
        addMaterial(yellowcake, "Yellowcake")
    }
    override val spawnEggFormat = "Jajo przyzywające %s"

    override val oreFormat = "Złoże %s"
    override val deepOreFormat = "Łupkowe Złoże %s"
    override val blockFormat = "Blok %s"
    override val rawFormat = "Surowe %s"
    override val ingotFormat = "Sztabka %s"
    override val billetFormat = "Pastylka %s"
    override val nuggetFormat = "Bryłka z %s"
    override val crystalsFormat = "Kryształ z %s"
    override val powderFormat = "Pył %s"
    override val plateFormat = "Płytka z %s"
    override val wireFormat = "Drut z %s"
}
