modLoader="javafml"
loaderVersion="[39,)"
license="LGPL v3.0"
issueTrackerURL="https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/issues"
[[mods]]
modId="nucleartech"
version="${file.jarVersion}"
displayName="Nuclear Tech Mod"
displayURL="https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake"
updateJSONURL="https://nucleartech.martinthedragon.at/raw/update.json"
credits="HbM: Did well..."
authors="MartinTheDragon"
description='''All the high quality nuclear bombs and machinery you can only find in this mod or in the older 1.7.10 version!
The mod with both quantity and quality ;D
A recreation by MartinTheDragon of HbMinecraft's Nuclear Tech Mod.
'''
[[dependencies.nucleartech]]
  modId="forge"
  mandatory=true
  versionRange="[40.1.59,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.nucleartech]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.18.2,1.19)"
  ordering="NONE"
  side="BOTH"
[[dependencies.nucleartech]]
  modId="jei"
  mandatory=false
  versionRange="[9.7.1.232,)"
  ordering="NONE"
  side="BOTH"
