package at.martinthedragon.nucleartech

import net.minecraft.resources.ResourceLocation
import net.minecraft.tags.BlockTags
import net.minecraft.tags.FluidTags
import net.minecraft.tags.ItemTags
import net.minecraft.tags.TagKey
import net.minecraft.world.item.Item
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.material.Fluid
import net.minecraftforge.registries.IForgeRegistry
import net.minecraftforge.registries.IForgeRegistryEntry
import net.minecraftforge.registries.tags.ITagManager

// look up forge tags here: https://github.com/Dente222/Minecraft-Forge-Tag-List
object NTechTags {
    object Blocks {
        private fun tag(name: String): TagKey<Block> =
            BlockTags.create(ntm(name))
        private fun forgeTag(name: String): TagKey<Block> =
            BlockTags.create(ResourceLocation("forge", name))

        val ORES_ALUMINIUM = forgeTag("ores/aluminium")
        val ORES_ASBESTOS = forgeTag("ores/asbestos")
        val ORES_AUSTRALIUM = forgeTag("ores/australium")
        val ORES_BERYLLIUM = forgeTag("ores/beryllium")
        val ORES_COBALT = forgeTag("ores/cobalt")
        val ORES_DAFFERGON = forgeTag("ores/daffergon")
        val ORES_FLUORITE = forgeTag("ores/fluorite")
        val ORES_LEAD = forgeTag("ores/lead")
        val ORES_LIGNITE = forgeTag("ores/lignite")
        val ORES_NITER = forgeTag("ores/salpeter")
        val ORES_OIL = forgeTag("ores/oil")
        val ORES_PHOSPHORUS = forgeTag("ores/phosphorus")
        val ORES_PLUTONIUM = forgeTag("ores/plutonium")
        val ORES_RARE_EARTH = forgeTag("ores/rare_earth")
        val ORES_REIIUM = forgeTag("ores/reiium")
        val ORES_SCHRABIDIUM = forgeTag("ores/schrabidium")
        val ORES_STARMETAL = forgeTag("ores/starmetal")
        val ORES_SULFUR = forgeTag("ores/sulfur")
        val ORES_THORIUM = forgeTag("ores/thorium")
        val ORES_TITANIUM = forgeTag("ores/titanium")
        val ORES_TRINITITE = forgeTag("ores/trinitite")
        val ORES_TRIXITE = forgeTag("ores/trixite")
        val ORES_TUNGSTEN = forgeTag("ores/tungsten")
        val ORES_UNOBTAINIUM = forgeTag("ores/unobtainium")
        val ORES_URANIUM = forgeTag("ores/uranium")
        val ORES_VERTICIUM = forgeTag("ores/verticium")
        val ORES_WEIDANIUM = forgeTag("ores/weidanium")

        val ORES_IN_GROUND_END_STONE = forgeTag("ores_in_ground/end_stone")

        val STORAGE_BLOCKS_ALUMINIUM = forgeTag("storage_blocks/aluminium")
        val STORAGE_BLOCKS_ASBESTOS = forgeTag("storage_blocks/asbestos")
        val STORAGE_BLOCKS_AUSTRALIUM = forgeTag("storage_blocks/australium")
        val STORAGE_BLOCKS_BERYLLIUM = forgeTag("storage_blocks/beryllium")
        val STORAGE_BLOCKS_COBALT = forgeTag("storage_blocks/cobalt")
        val STORAGE_BLOCKS_COMBINE_STEEL = forgeTag("storage_blocks/combine_steel")
        val STORAGE_BLOCKS_DAFFERGON = forgeTag("storage_blocks/daffergon")
        val STORAGE_BLOCKS_DESH = forgeTag("storage_blocks/desh")
        val STORAGE_BLOCKS_ELECTRICAL_SCRAP = forgeTag("storage_blocks/electrical_scrap")
        val STORAGE_BLOCKS_EUPHEMIUM = forgeTag("storage_blocks/euphemium")
        val STORAGE_BLOCKS_FIBERGLASS = forgeTag("storage_blocks/fiberglass")
        val STORAGE_BLOCKS_FLUORITE = forgeTag("storage_blocks/fluorite")
        val STORAGE_BLOCKS_HAZMAT = forgeTag("storage_blocks/hazmat")
        val STORAGE_BLOCKS_INSULATOR = forgeTag("storage_blocks/insulator")
        val STORAGE_BLOCKS_LEAD = forgeTag("storage_blocks/lead")
        val STORAGE_BLOCKS_LITHIUM = forgeTag("storage_blocks/lithium")
        val STORAGE_BLOCKS_MAGNETIZED_TUNGSTEN = forgeTag("storage_blocks/magnetized_tungsten")
        val STORAGE_BLOCKS_MOX = forgeTag("storage_blocks/mox")
        val STORAGE_BLOCKS_NEPTUNIUM = forgeTag("storage_blocks/neptunium")
        val STORAGE_BLOCKS_NITER = forgeTag("storage_blocks/salpeter")
        val STORAGE_BLOCKS_NUCLEAR_WASTE = forgeTag("storage_blocks/nuclear_waste")
        val STORAGE_BLOCKS_PHOSPHORUS = forgeTag("storage_blocks/phosphorus")
        val STORAGE_BLOCKS_PLUTONIUM = forgeTag("storage_blocks/plutonium")
        val STORAGE_BLOCKS_PLUTONIUM_FUEL = forgeTag("storage_blocks/plutonium_fuel")
        val STORAGE_BLOCKS_RED_COPPER = forgeTag("storage_blocks/red_copper")
        val STORAGE_BLOCKS_REIIUM = forgeTag("storage_blocks/reiium")
        val STORAGE_BLOCKS_SCHRABIDIUM = forgeTag("storage_blocks/schrabidium")
        val STORAGE_BLOCKS_SCHRABIDIUM_FUEL = forgeTag("storage_blocks/schrabidium_fuel")
        val STORAGE_BLOCKS_SCRAP = forgeTag("storage_blocks/scrap")
        val STORAGE_BLOCKS_SOLINIUM = forgeTag("storage_blocks/solinium")
        val STORAGE_BLOCKS_STARMETAL = forgeTag("storage_blocks/starmetal")
        val STORAGE_BLOCKS_STEEL = forgeTag("storage_blocks/steel")
        val STORAGE_BLOCKS_SULFUR = forgeTag("storage_blocks/sulfur")
        val STORAGE_BLOCKS_THORIUM = forgeTag("storage_blocks/thorium")
        val STORAGE_BLOCKS_THORIUM_FUEL = forgeTag("storage_blocks/thorium_fuel")
        val STORAGE_BLOCKS_TITANIUM = forgeTag("storage_blocks/titanium")
        val STORAGE_BLOCKS_TRINITITE = forgeTag("storage_blocks/trinitite")
        val STORAGE_BLOCKS_TUNGSTEN = forgeTag("storage_blocks/tungsten")
        val STORAGE_BLOCKS_UNOBTAINIUM = forgeTag("storage_blocks/unobtainium")
        val STORAGE_BLOCKS_URANIUM = forgeTag("storage_blocks/uranium")
        val STORAGE_BLOCKS_URANIUM_FUEL = forgeTag("storage_blocks/uranium_fuel")
        val STORAGE_BLOCKS_VERTICIUM = forgeTag("storage_blocks/verticium")
        val STORAGE_BLOCKS_WEIDANIUM = forgeTag("storage_blocks/weidanium")
        val STORAGE_BLOCKS_YELLOWCAKE = forgeTag("storage_blocks/yellow_cake_uranium")

        val SAND_OIL = forgeTag("sand/oil")
        val GLOWING_MUSHROOM_GROW_BLOCK = tag("glowing_mushroom_grow_block")
        val GLOWING_MYCELIUM_SPREADABLE = tag("glowing_mycelium_spreadable")

        val ANVIL = tag("anvil")
    }

    object Items {
        private fun tag(name: String): TagKey<Item> =
            ItemTags.create(ntm(name))
        private fun forgeTag(name: String): TagKey<Item> =
            ItemTags.create(ResourceLocation("forge", name))

        // Blocks

        val ORES_ALUMINIUM = forgeTag("ores/aluminium")
        val ORES_ASBESTOS = forgeTag("ores/asbestos")
        val ORES_AUSTRALIUM = forgeTag("ores/australium")
        val ORES_BERYLLIUM = forgeTag("ores/beryllium")
        val ORES_COBALT = forgeTag("ores/cobalt")
        val ORES_DAFFERGON = forgeTag("ores/daffergon")
        val ORES_FLUORITE = forgeTag("ores/fluorite")
        val ORES_LEAD = forgeTag("ores/lead")
        val ORES_LIGNITE = forgeTag("ores/lignite")
        val ORES_NITER = forgeTag("ores/salpeter")
        val ORES_OIL = forgeTag("ores/oil")
        val ORES_PHOSPHORUS = forgeTag("ores/phosphorus")
        val ORES_PLUTONIUM = forgeTag("ores/plutonium")
        val ORES_RARE_EARTH = forgeTag("ores/rare_earth")
        val ORES_REIIUM = forgeTag("ores/reiium")
        val ORES_SCHRABIDIUM = forgeTag("ores/schrabidium")
        val ORES_STARMETAL = forgeTag("ores/starmetal")
        val ORES_SULFUR = forgeTag("ores/sulfur")
        val ORES_THORIUM = forgeTag("ores/thorium")
        val ORES_TITANIUM = forgeTag("ores/titanium")
        val ORES_TRINITITE = forgeTag("ores/trinitite")
        val ORES_TRIXITE = forgeTag("ores/trixite")
        val ORES_TUNGSTEN = forgeTag("ores/tungsten")
        val ORES_UNOBTAINIUM = forgeTag("ores/unobtainium")
        val ORES_URANIUM = forgeTag("ores/uranium")
        val ORES_VERTICIUM = forgeTag("ores/verticium")
        val ORES_WEIDANIUM = forgeTag("ores/weidanium")

        val ORES_IN_GROUND_END_STONE = forgeTag("ores_in_ground/end_stone")

        val STORAGE_BLOCKS_ALUMINIUM = forgeTag("storage_blocks/aluminium")
        val STORAGE_BLOCKS_ASBESTOS = forgeTag("storage_blocks/asbestos")
        val STORAGE_BLOCKS_AUSTRALIUM = forgeTag("storage_blocks/australium")
        val STORAGE_BLOCKS_BERYLLIUM = forgeTag("storage_blocks/beryllium")
        val STORAGE_BLOCKS_COBALT = forgeTag("storage_blocks/cobalt")
        val STORAGE_BLOCKS_COMBINE_STEEL = forgeTag("storage_blocks/combine_steel")
        val STORAGE_BLOCKS_DAFFERGON = forgeTag("storage_blocks/daffergon")
        val STORAGE_BLOCKS_DESH = forgeTag("storage_blocks/desh")
        val STORAGE_BLOCKS_ELECTRICAL_SCRAP = forgeTag("storage_blocks/electrical_scrap")
        val STORAGE_BLOCKS_EUPHEMIUM = forgeTag("storage_blocks/euphemium")
        val STORAGE_BLOCKS_FIBERGLASS = forgeTag("storage_blocks/fiberglass")
        val STORAGE_BLOCKS_FLUORITE = forgeTag("storage_blocks/fluorite")
        val STORAGE_BLOCKS_HAZMAT = forgeTag("storage_blocks/hazmat")
        val STORAGE_BLOCKS_INSULATOR = forgeTag("storage_blocks/insulator")
        val STORAGE_BLOCKS_LEAD = forgeTag("storage_blocks/lead")
        val STORAGE_BLOCKS_LITHIUM = forgeTag("storage_blocks/lithium")
        val STORAGE_BLOCKS_MAGNETIZED_TUNGSTEN = forgeTag("storage_blocks/magnetized_tungsten")
        val STORAGE_BLOCKS_MOX = forgeTag("storage_blocks/mox")
        val STORAGE_BLOCKS_NEPTUNIUM = forgeTag("storage_blocks/neptunium")
        val STORAGE_BLOCKS_NITER = forgeTag("storage_blocks/salpeter")
        val STORAGE_BLOCKS_NUCLEAR_WASTE = forgeTag("storage_blocks/nuclear_waste")
        val STORAGE_BLOCKS_PHOSPHORUS = forgeTag("storage_blocks/phosphorus")
        val STORAGE_BLOCKS_PLUTONIUM = forgeTag("storage_blocks/plutonium")
        val STORAGE_BLOCKS_PLUTONIUM_FUEL = forgeTag("storage_blocks/plutonium_fuel")
        val STORAGE_BLOCKS_RED_COPPER = forgeTag("storage_blocks/red_copper")
        val STORAGE_BLOCKS_REIIUM = forgeTag("storage_blocks/reiium")
        val STORAGE_BLOCKS_SCHRABIDIUM = forgeTag("storage_blocks/schrabidium")
        val STORAGE_BLOCKS_SCHRABIDIUM_FUEL = forgeTag("storage_blocks/schrabidium_fuel")
        val STORAGE_BLOCKS_SCRAP = forgeTag("storage_blocks/scrap")
        val STORAGE_BLOCKS_SOLINIUM = forgeTag("storage_blocks/solinium")
        val STORAGE_BLOCKS_STARMETAL = forgeTag("storage_blocks/starmetal")
        val STORAGE_BLOCKS_STEEL = forgeTag("storage_blocks/steel")
        val STORAGE_BLOCKS_SULFUR = forgeTag("storage_blocks/sulfur")
        val STORAGE_BLOCKS_THORIUM = forgeTag("storage_blocks/thorium")
        val STORAGE_BLOCKS_THORIUM_FUEL = forgeTag("storage_blocks/thorium_fuel")
        val STORAGE_BLOCKS_TITANIUM = forgeTag("storage_blocks/titanium")
        val STORAGE_BLOCKS_TRINITITE = forgeTag("storage_blocks/trinitite")
        val STORAGE_BLOCKS_TUNGSTEN = forgeTag("storage_blocks/tungsten")
        val STORAGE_BLOCKS_UNOBTAINIUM = forgeTag("storage_blocks/unobtainium")
        val STORAGE_BLOCKS_URANIUM = forgeTag("storage_blocks/uranium")
        val STORAGE_BLOCKS_URANIUM_FUEL = forgeTag("storage_blocks/uranium_fuel")
        val STORAGE_BLOCKS_VERTICIUM = forgeTag("storage_blocks/verticium")
        val STORAGE_BLOCKS_WEIDANIUM = forgeTag("storage_blocks/weidanium")
        val STORAGE_BLOCKS_YELLOWCAKE = forgeTag("storage_blocks/yellow_cake_uranium")

        val SAND_OIL = forgeTag("sand/oil")
        val GLOWING_MUSHROOM_GROW_BLOCK = tag("glowing_mushroom_grow_block")

        val ANVIL = tag("anvil")

        // Items

        val RAW_MATERIALS_ALUMINIUM = forgeTag("raw_materials/aluminium")
        val RAW_MATERIALS_AUSTRALIUM = forgeTag("raw_materials/australium")
        val RAW_MATERIALS_BERYLLIUM = forgeTag("raw_materials/beryllium")
        val RAW_MATERIALS_COBALT = forgeTag("raw_materials/cobalt")
        val RAW_MATERIALS_LEAD = forgeTag("raw_materials/lead")
        val RAW_MATERIALS_LITHIUM = forgeTag("raw_materials/lithium")
        val RAW_MATERIALS_PLUTONIUM = forgeTag("raw_materials/plutonium")
        val RAW_MATERIALS_RARE_EARTH = forgeTag("raw_materials/rare_earth")
        val RAW_MATERIALS_SCHRABIDIUM = forgeTag("raw_materials/schrabidium")
        val RAW_MATERIALS_STARMETAL = forgeTag("raw_materials/starmetal")
        val RAW_MATERIALS_THORIUM = forgeTag("raw_materials/thorium")
        val RAW_MATERIALS_TITANIUM = forgeTag("raw_materials/titanium")
        val RAW_MATERIALS_TRIXITE = forgeTag("raw_materials/trixite")
        val RAW_MATERIALS_TUNGSTEN = forgeTag("raw_materials/tungsten")
        val RAW_MATERIALS_URANIUM = forgeTag("raw_materials/uranium")

        val INGOTS_ACTINIUM = forgeTag("ingots/actinium")
        val INGOTS_ALUMINIUM = forgeTag("ingots/aluminium")
        val INGOTS_AMERICIUM = forgeTag("ingots/americium")
        val INGOTS_ASBESTOS = forgeTag("ingots/asbestos")
        val INGOTS_AUSTRALIUM = forgeTag("ingots/australium")
        val INGOTS_BERYLLIUM = forgeTag("ingots/beryllium")
        val INGOTS_BISMUTH = forgeTag("ingots/bismuth")
        val INGOTS_COBALT = forgeTag("ingots/cobalt")
        val INGOTS_COMBINE_STEEL = forgeTag("ingots/combine_steel")
        val INGOTS_DAFFERGON = forgeTag("ingots/daffergon")
        val INGOTS_DESH = forgeTag("ingots/desh")
        val INGOTS_DINEUTRONIUM = forgeTag("ingots/dineutronium")
        val INGOTS_ELECTRONIUM = forgeTag("ingots/electronium")
        val INGOTS_EUPHEMIUM = forgeTag("ingots/euphemium")
        val INGOTS_FIBERGLASS = forgeTag("ingots/fiberglass")
        val INGOTS_HIGH_SPEED_STEEL = forgeTag("ingots/high_speed_steel")
        val INGOTS_LANTHANUM = forgeTag("ingots/lanthanum")
        val INGOTS_LEAD = forgeTag("ingots/lead")
        val INGOTS_LITHIUM = forgeTag("ingots/lithium")
        val INGOTS_MAGNETIZED_TUNGSTEN = forgeTag("ingots/magnetized_tungsten")
        val INGOTS_MOX = forgeTag("ingots/mox")
        val INGOTS_NEPTUNIUM = forgeTag("ingots/neptunium")
        val INGOTS_PHOSPHORUS = forgeTag("ingots/phosphorus")
        val INGOTS_PLASTIC = forgeTag("ingots/plastic")
        val INGOTS_PLUTONIUM = forgeTag("ingots/plutonium")
        val INGOTS_PLUTONIUM_FUEL = forgeTag("ingots/plutonium_fuel")
        val INGOTS_POLONIUM = forgeTag("ingots/polonium")
        val INGOTS_POLYMER = forgeTag("ingots/polymer")
        val INGOTS_RED_COPPER = forgeTag("ingots/red_copper")
        val INGOTS_REIIUM = forgeTag("ingots/reiium")
        val INGOTS_SATURNITE = forgeTag("ingots/saturnite")
        val INGOTS_SCHRABIDATE = forgeTag("ingots/schrabidate")
        val INGOTS_SCHRABIDIUM = forgeTag("ingots/schrabidium")
        val INGOTS_SCHRABIDIUM_FUEL = forgeTag("ingots/schrabidium_fuel")
        val INGOTS_SCHRARANIUM = forgeTag("ingots/schraranium")
        val INGOTS_SEMTEX = forgeTag("ingots/semtex")
        val INGOTS_SOLINIUM = forgeTag("ingots/solinium")
        val INGOTS_STARMETAL = forgeTag("ingots/starmetal")
        val INGOTS_STEEL = forgeTag("ingots/steel")
        val INGOTS_TEFLON = forgeTag("ingots/teflon")
        val INGOTS_THORIUM = forgeTag("ingots/thorium")
        val INGOTS_THORIUM_FUEL = forgeTag("ingots/thorium_fuel")
        val INGOTS_TITANIUM = forgeTag("ingots/titanium")
        val INGOTS_TUNGSTEN = forgeTag("ingots/tungsten")
        val INGOTS_UNOBTAINIUM = forgeTag("ingots/unobtainium")
        val INGOTS_URANIUM = forgeTag("ingots/uranium")
        val INGOTS_URANIUM_FUEL = forgeTag("ingots/uranium_fuel")
        val INGOTS_VERTICIUM = forgeTag("ingots/verticium")
        val INGOTS_WEIDANIUM = forgeTag("ingots/weidanium")

        val COKE = forgeTag("coal_coke")

        val DUSTS_ACTINIUM = forgeTag("dusts/actinium")
        val DUSTS_ALUMINIUM = forgeTag("dusts/aluminium")
        val DUSTS_ASBESTOS = forgeTag("dusts/asbestos")
        val DUSTS_AUSTRALIUM = forgeTag("dusts/australium")
        val DUSTS_BALLISTITE = forgeTag("dusts/ballistite")
        val DUSTS_BERYLLIUM = forgeTag("dusts/beryllium")
        val DUSTS_CERIUM = forgeTag("dusts/cerium")
        val DUSTS_CHLOROPHYTE = forgeTag("dusts/chlorophyte")
        val DUSTS_CLOUD = forgeTag("dusts/cloud")
        val DUSTS_COAL = forgeTag("dusts/coal")
        val DUSTS_COBALT = forgeTag("dusts/cobalt")
        val DUSTS_COLD = forgeTag("dusts/cold")
        val DUSTS_COMBINE_STEEL = forgeTag("dusts/combine_steel")
        val DUSTS_COPPER = forgeTag("dusts/copper")
        val DUSTS_CORDITE = forgeTag("dusts/cordite")
        val DUSTS_DAFFERGON = forgeTag("dusts/daffergon")
        val DUSTS_DESH = forgeTag("dusts/desh")
        val DUSTS_DIAMOND = forgeTag("dusts/diamond")
        val DUSTS_DINEUTRONIUM = forgeTag("dusts/dineutronium")
        val DUSTS_DUST = forgeTag("dusts/dust")
        val DUSTS_EMERALD = forgeTag("dusts/emerald")
        val DUSTS_ENCHANTMENT = forgeTag("dusts/enchantment")
        val DUSTS_ENERGY = forgeTag("dusts/energy")
        val DUSTS_EUPHEMIUM = forgeTag("dusts/euphemium")
        val DUSTS_FLUORITE = forgeTag("dusts/fluorite")
        val DUSTS_GOLD = forgeTag("dusts/gold")
        val DUSTS_IRON = forgeTag("dusts/iron")
        val DUSTS_LANTHANUM = forgeTag("dusts/lanthanum")
        val DUSTS_LAPIS = forgeTag("dusts/lapis")
        val DUSTS_LEAD = forgeTag("dusts/lead")
        val DUSTS_LIGNITE = forgeTag("dusts/lignite")
        val DUSTS_LITHIUM = forgeTag("dusts/lithium")
        val DUSTS_MAGNETIZED_TUNGSTEN = forgeTag("dusts/magnetized_tungsten")
        val DUSTS_METEORITE = forgeTag("dusts/meteorite")
        val DUSTS_NEODYMIUM = forgeTag("dusts/neodymium")
        val DUSTS_NEPTUNIUM = forgeTag("dusts/neptunium")
        val DUSTS_NIOBIUM = forgeTag("dusts/niobium")
        val DUSTS_NITER = forgeTag("dusts/salpeter")
        val DUSTS_PHOSPHORUS = forgeTag("dusts/phosphorus")
        val DUSTS_PLUTONIUM = forgeTag("dusts/plutonium")
        val DUSTS_POISON = forgeTag("dusts/poison")
        val DUSTS_POLONIUM = forgeTag("dusts/polonium")
        val DUSTS_POLYMER = forgeTag("dusts/polymer")
        val DUSTS_QUARTZ = forgeTag("dusts/quartz")
        val DUSTS_RED_COPPER = forgeTag("dusts/red_copper")
        val DUSTS_REIIUM = forgeTag("dusts/reiium")
        val DUSTS_SCHRABIDIUM = forgeTag("dusts/schrabidium")
        val DUSTS_SEMTEX = forgeTag("dusts/semtex")
        val DUSTS_STEEL = forgeTag("dusts/steel")
        val DUSTS_SULFUR = forgeTag("dusts/sulfur")
        val DUSTS_TEFLON = forgeTag("dusts/teflon")
        val DUSTS_THERMITE = forgeTag("dusts/thermite")
        val DUSTS_THERMONUCLEAR_ASHES = forgeTag("dusts/thermonuclear_ashes")
        val DUSTS_THORIUM = forgeTag("dusts/thorium")
        val DUSTS_TITANIUM = forgeTag("dusts/titanium")
        val DUSTS_TUNGSTEN = forgeTag("dusts/tungsten")
        val DUSTS_UNOBTAINIUM = forgeTag("dusts/unobtainium")
        val DUSTS_URANIUM = forgeTag("dusts/uranium")
        val DUSTS_VERTICIUM = forgeTag("dusts/verticium")
        val DUSTS_WEIDANIUM = forgeTag("dusts/weidanium")

        // from Mekanism
        val YELLOWCAKE_URANIUM = forgeTag("yellow_cake_uranium")

        // crystals
        val CRYSTALS = forgeTag("crystals")
        val CRYSTALS_ALUMINIUM = forgeTag("crystals/aluminium")
        val CRYSTALS_BERYLLIUM = forgeTag("crystals/beryllium")
        val CRYSTALS_COAL = forgeTag("crystals/coal")
        val CRYSTALS_COPPER = forgeTag("crystals/copper")
        val CRYSTALS_DIAMOND = forgeTag("crystals/diamond")
        val CRYSTALS_FLUORITE = forgeTag("crystals/fluorite")
        val CRYSTALS_GOLD = forgeTag("crystals/gold")
        val CRYSTALS_IRON = forgeTag("crystals/iron")
        val CRYSTALS_LEAD = forgeTag("crystals/lead")
        val CRYSTALS_LITHIUM = forgeTag("crystals/lithium")
        val CRYSTALS_NITER = forgeTag("crystals/salpeter")
        val CRYSTALS_PHOSPHORUS = forgeTag("crystals/phosphorus")
        val CRYSTALS_PLUTONIUM = forgeTag("crystals/plutonium")
        val CRYSTALS_RARE_EARTH = forgeTag("crystals/rare_earth")
        val CRYSTALS_REDSTONE = forgeTag("crystals/redstone")
        val CRYSTALS_SCHRABIDIUM = forgeTag("crystals/schrabidium")
        val CRYSTALS_SCHRARANIUM = forgeTag("crystals/schraranium")
        val CRYSTALS_STARMETAL = forgeTag("crystals/starmetal")
        val CRYSTALS_SULFUR = forgeTag("crystals/sulfur")
        val CRYSTALS_THORIUM = forgeTag("crystals/thorium")
        val CRYSTALS_TITANIUM = forgeTag("crystals/titanium")
        val CRYSTALS_TRIXITE = forgeTag("crystals/trixite")
        val CRYSTALS_TUNGSTEN = forgeTag("crystals/tungsten")
        val CRYSTALS_URANIUM = forgeTag("crystals/uranium")

        val GEMS_ACTINIUM = forgeTag("gems/actinium")
        val GEMS_ALUMINIUM = forgeTag("gems/aluminium")
        val GEMS_BERYLLIUM = forgeTag("gems/beryllium")
        val GEMS_CERIUM = forgeTag("gems/cerium")
        val GEMS_COAL = forgeTag("gems/coal")
        val GEMS_COBALT = forgeTag("gems/cobalt")
        val GEMS_COPPER = forgeTag("gems/copper")
        val GEMS_DIAMOND = forgeTag("gems/diamond")
        val GEMS_FLUORITE = forgeTag("gems/fluorite")
        val GEMS_GOLD = forgeTag("gems/gold")
        val GEMS_IRON = forgeTag("gems/iron")
        val GEMS_LANTHANUM = forgeTag("gems/lanthanum")
        val GEMS_LEAD = forgeTag("gems/lead")
        val GEMS_LITHIUM = forgeTag("gems/lithium")
        val GEMS_NEODYMIUM = forgeTag("gems/neodymium")
        val GEMS_NIOBIUM = forgeTag("gems/niobium")
        val GEMS_NITER = forgeTag("gems/salpeter")
        val GEMS_PHOSPHORUS = forgeTag("gems/phosphorus")
        val GEMS_PLUTONIUM = forgeTag("gems/plutonium")
        val GEMS_RARE_EARTH = forgeTag("gems/rare_earth")
        val GEMS_REDSTONE = forgeTag("gems/redstone")
        val GEMS_SCHRABIDIUM = forgeTag("gems/schrabidium")
        val GEMS_SCHRARANIUM = forgeTag("gems/schraranium")
        val GEMS_STARMETAL = forgeTag("gems/starmetal")
        val GEMS_SULFUR = forgeTag("gems/sulfur")
        val GEMS_THORIUM = forgeTag("gems/thorium")
        val GEMS_TITANIUM = forgeTag("gems/titanium")
        val GEMS_TRIXITE = forgeTag("gems/trixite")
        val GEMS_TUNGSTEN = forgeTag("gems/tungsten")
        val GEMS_URANIUM = forgeTag("gems/uranium")

        val RARE_EARTH_FRAGMENTS = tag("rare_earth_fragments")

        val BIOMASS = forgeTag("biomass")
        val COMPRESSED_BIOMASS = forgeTag("biomass/compressed")

        val NUGGETS_AUSTRALIUM = forgeTag("nuggets/australium")
        val NUGGETS_BERYLLIUM = forgeTag("nuggets/beryllium")
        val NUGGETS_BISMUTH = forgeTag("nuggets/bismuth")
        val NUGGETS_DAFFERGON = forgeTag("nuggets/daffergon")
        val NUGGETS_DESH = forgeTag("nuggets/desh")
        val NUGGETS_DINEUTRONIUM = forgeTag("nuggets/dineutronium")
        val NUGGETS_EUPHEMIUM = forgeTag("nuggets/euphemium")
        val NUGGETS_LEAD = forgeTag("nuggets/lead")
        val NUGGETS_MERCURY = forgeTag("nuggets/mercury")
        val NUGGETS_MOX = forgeTag("nuggets/mox")
        val NUGGETS_NEPTUNIUM = forgeTag("nuggets/neptunium")
        val NUGGETS_PLUTONIUM = forgeTag("nuggets/plutonium")
        val NUGGETS_PLUTONIUM_FUEL = forgeTag("nuggets/plutonium_fuel")
        val NUGGETS_POLONIUM = forgeTag("nuggets/polonium")
        val NUGGETS_REIIUM = forgeTag("nuggets/reiium")
        val NUGGETS_SCHRABIDIUM = forgeTag("nuggets/schrabidium")
        val NUGGETS_SCHRABIDIUM_FUEL = forgeTag("nuggets/schrabidium_fuel")
        val NUGGETS_SOLINIUM = forgeTag("nuggets/solinium")
        val NUGGETS_THORIUM = forgeTag("nuggets/thorium")
        val NUGGETS_THORIUM_FUEL = forgeTag("nuggets/thorium_fuel")
        val NUGGETS_UNOBTAINIUM = forgeTag("nuggets/unobtainium")
        val NUGGETS_URANIUM = forgeTag("nuggets/uranium")
        val NUGGETS_URANIUM_FUEL = forgeTag("nuggets/uranium_fuel")
        val NUGGETS_VERTICIUM = forgeTag("nuggets/verticium")
        val NUGGETS_WEIDANIUM = forgeTag("nuggets/weidanium")

        val PLATES = forgeTag("plates")
        val PLATES_ALUMINIUM = forgeTag("plates/aluminium")
        val PLATES_COMBINE_STEEL = forgeTag("plates/combine_steel")
        val PLATES_COPPER = forgeTag("plates/copper")
        val PLATES_GOLD = forgeTag("plates/gold")
        val PLATES_INSULATOR = forgeTag("plates/insulator")
        val PLATES_IRON = forgeTag("plates/iron")
        val PLATES_KEVLAR = forgeTag("plates/kevlar")
        val PLATES_LEAD = forgeTag("plates/lead")
        val PLATES_NEUTRON_REFLECTOR = forgeTag("plates/neutron_reflector")
        val PLATES_SATURNITE = forgeTag("plates/saturnite")
        val PLATES_SCHRABIDIUM = forgeTag("plates/schrabidium")
        val PLATES_STEEL = forgeTag("plates/steel")
        val PLATES_TITANIUM = forgeTag("plates/titanium")

        val BOLTS = forgeTag("bolts")
        val BOLTS_TUNGSTEN = forgeTag("bolts/tungsten")

        val FABRIC_HAZMAT = forgeTag("fabric_hazmat")

        val FILTERS = forgeTag("filters")
        val FILTERS_CARBON = forgeTag("filters/carbon")

        val WIRES = forgeTag("wires")
        val WIRES_ALUMINIUM = forgeTag("wires/aluminium")
        val WIRES_COPPER = forgeTag("wires/copper")
        val WIRES_GOLD = forgeTag("wires/gold")
        val WIRES_MAGNETIZED_TUNGSTEN = forgeTag("wires/magnetized_tungsten")
        val WIRES_RED_COPPER = forgeTag("wires/red_copper")
        val WIRES_SCHRABIDIUM = forgeTag("wires/schrabidium")
        val WIRES_SUPER_CONDUCTOR = forgeTag("wires/super_conductor")
        val WIRES_TUNGSTEN = forgeTag("wires/tungsten")

        val COILS = forgeTag("coils")
        val COILS_COPPER = forgeTag("coils/copper")
        val COILS_GOLD = forgeTag("coils/gold")
        val COILS_SUPER_CONDUCTOR = forgeTag("coils/super_conductor")
        val COILS_TUNGSTEN = forgeTag("coils/tungsten")

        val FISSILE_FUELS = forgeTag("fissile_fuels")
        val FISSILE_FUELS_MOX = forgeTag("fissile_fuels/mox")
        val FISSILE_FUELS_PLUTONIUM = forgeTag("fissile_fuels/plutonium")
        val FISSILE_FUELS_SCHRABIDIUM = forgeTag("fissile_fuels/schrabidium")
        val FISSILE_FUELS_THORIUM = forgeTag("fissile_fuels/thorium")
        val FISSILE_FUELS_URANIUM = forgeTag("fissile_fuels/uranium")

        val SCRAP = forgeTag("scrap")
        val NUCLEAR_WASTE = forgeTag("nuclear_waste")

        val WASTES = forgeTag("wastes")
        val WASTES_HOT_MOX = forgeTag("wastes/hot_mox")
        val WASTES_HOT_PLUTONIUM = forgeTag("wastes/hot_plutonium")
        val WASTES_HOT_THORIUM = forgeTag("wastes/hot_thorium")
        val WASTES_HOT_URANIUM = forgeTag("wastes/hot_uranium")
        val WASTES_MOX = forgeTag("wastes/mox")
        val WASTES_NUCLEAR_WASTE = forgeTag("wastes/nuclear_waste")
        val WASTES_PLUTONIUM = forgeTag("wastes/plutonium")
        val WASTES_SCRAP = forgeTag("wastes/scrap")
        val WASTES_THORIUM = forgeTag("wastes/thorium")
        val WASTES_URANIUM = forgeTag("wastes/uranium")

        val HOT_WASTES = tag("hot_wastes")
        val COLD_WASTES = tag("cold_wastes")

        val MACHINE_TEMPLATE_FOLDER_RESULTS = tag("machine_template_folder_results")
        val STAMPS = tag("stamps")
        val FOLDER_STAMPS = tag("stamps/template_folder")
        val FLAT_STAMPS = tag("stamps/flat")
        val PLATE_STAMPS = tag("stamps/plate")
        val WIRE_STAMPS = tag("stamps/wire")
        val CIRCUIT_STAMPS = tag("stamps/circuit")
        val STONE_STAMPS = tag("stamps/stone")
        val IRON_STAMPS = tag("stamps/iron")
        val STEEL_STAMPS = tag("stamps/steel")
        val TITANIUM_STAMPS = tag("stamps/titanium")
        val OBSIDIAN_STAMPS = tag("stamps/obsidian")
        val SCHRABIDIUM_STAMPS = tag("stamps/schrabidium")
        val SIREN_TRACKS = tag("siren_tracks")

        val SHREDDER_BLADES = tag("shredder_blades")
    }

    object Fluids {
        private fun tag(name: String): TagKey<Fluid> =
            FluidTags.create(ntm(name))
        private fun forgeTag(name: String): TagKey<Fluid> =
            FluidTags.create(ResourceLocation("forge", name))

        val CRUDE_OIL = forgeTag("crude_oil")
        val GAS = forgeTag("gas")
        val NATURAL_GAS = forgeTag("natural_gas")
        val OIL = forgeTag("oil")
        val URANIUM_HEXAFLUORIDE = forgeTag("uranium_hexafluoride")
    }
}

fun <V : IForgeRegistryEntry<V>> IForgeRegistry<V>.getTagManager(): ITagManager<V> = tags() ?: throw IllegalStateException("No tag manager bound")
